### PR TITLE
Update Ticketcorner.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by bardiharborow** [comment]
Likely broken due to #10873.

**Comment by J0WI** [comment]
WFM locally with curl (without additional headers)

**Comment by bardiharborow** [comment]
Maybe just an intermittent failure then, a `git commit --amend && git push -f` might fix it.

**Comment by jeremyn** [comment]
- [ ] Mark https://analytics.ticketcorner.ch as `Expired`
- [ ] Mark https://sport.ticketcorner.ch as `Expired` (and remove its `target`)

**Comment by J0WI** [comment]
See #10948 for `Eventim.xml`

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
