### PR TITLE
[Canon] Fixed problem with www.usa.canon.com

### PR DESCRIPTION
**Pull request by LoHub**

### CODE REVIEW

**Comment by donced** [comment]
Interested in fixing #2006?

**Comment by donced** [comment]
Improved by https://github.com/EFForg/https-everywhere/pull/2452.

**Comment by jsha** [comment]
The relevant issue is fixed in #2452, but this change adds some more domains. Can you pull in the latest master and change the rules to be simple rules (i.e. `<rule from='^http:' to='https:' />`)?

**Comment by J0WI** [comment]
Fixed in #2452 and #2725

**Pull request closed without merging**
