### PR TITLE
[Kontalk] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
HTTPS support tracked in https://github.com/kontalk/website/issues/14

### CODE REVIEW

**Comment by J0WI** [comment]
CA Cert on https://translate.kontalk.org/

**Comment by daniele-athome** [comment]
I'd like to note that https://translate.kontalk.org/ has migrated to StartSSL.

**Comment by rugk** [comment]
Okay, changed: https://github.com/EFForg/https-everywhere/pull/4728

**Comment by rugk** [comment]
@daniele-athome BTW: You are [sending the StartCom root certificate](https://www.ssllabs.com/ssltest/analyze.html?d=translate.kontalk.org) on your website, which is unnecessary.

**Comment by daniele-athome** [comment]
Thanks, I'll look into it.

**Pull request merged**
