### PR TITLE
Make HTTPS Everywhere always ON by default

### PR DESCRIPTION
**Pull request by cschanaj**
This PR will remove the On/Off switch from the extension UI and effectively make it an always-on extension. From many issues, e.g. #18055 it seems that the On/Off switch has been a cause of confusion for normal users to understand how HTTPS Everywhere operate. 

This change is also aligned with UX suggestion from https://github.com/uracreative/works/issues/29#issuecomment-530731106

### CODE REVIEW

**Comment by pipboy96** [comment]
We would need to fix the exclusions before doing that.

**Comment by cschanaj** [comment]
@pipboy96 would you mind to explain a little bit on the exclusion issue? We already have a feature to disable the extension per site since #16546. I might have missed something tho.

**Comment by pipboy96** [comment]
@cschanaj I mean allowing to whitelist websites without visiting them beforehand.

**Comment by zoracon** [comment]
Sorry for the delay on responding to this. Right now, taking away the ability to turn the extension "on/off" would likely not be ideal for many users out there who want to temporarily turn the extension off without going to the preferences panel.

We have not yet moved to implement Ura Design Labs suggestions, and the expectations that it will be implemented are still being negotiated with the feedback they will implement.

I do agree and it's backed by research and comments that people are very much confused by the 3 states this extension can have, But taking the on/off switch is a big design decision and can trigger more confusion & frustration with users if we do this without warning. Which is why we can't accept this change at the moment.

On addressing the confusion users have with the states, I plan on utilizing this guide for onboarding new and existing users: https://extensionworkshop.com/documentation/develop/onboard-upboard-offboard-users/

Right now Privacy Badger has a great onboarding page and they have had success with it. So I plan to create a page similar for HTTPS Everywhere after I address Manifest V3 testing.

**Comment by pipboy96** [comment]
@zoracon Thanks for clarifying. Browsers can already temporarily disable extensions, so we don't really "lose" any functionality. Primary issue is to avoid confusing our users.

**Comment by cschanaj** [comment]
> ...taking away the ability to turn the extension "on/off" would likely not be ideal for many users out there who want to temporarily turn the extension off without going to the preferences panel.

In addition to the extension toggle embeded in the browser, users can disable HTTPSE on a session basis since the latest release (#18417). I am more inclined to think that the users rarely needed to disable the entire extension to avoid site breakages, such scenarios are more frequent but limited to advanced users/ developers only. 

An on-boarding will help to address the confusions on how HTTPSE work, it is definitely a good idea :+1:

**Comment by zoracon** [comment]
Just to update, it is in motion with internal design to not only create an installation/onboarding page, but a style guide as well

**Comment by cschanaj** [comment]
Update: #18993 is merged and released in version `2020.3.16`

**Comment by cschanaj** [comment]
@zoracon https://github.com/EFForg/https-everywhere/issues/18069#issuecomment-705849864 mentions that the UX redesign works will be postponed to next year. Would you be interested to review/ close this PR to avoid the merge conflicts?

**Comment by zoracon** [comment]
I will close for now, but still have the idea to bring up the on-boarding page to our design team to address this.

**Pull request closed without merging**
