### PR TITLE
Update 126.net.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by ivysrono** [comment]
@pipboy96 It's better to understand that put special rules with the corresponding target hosts.

**Comment by pipboy96** [comment]
@ivysrono Rules are ruleset-global, and their position in the ruleset (except the order) does not matter.

**Comment by pipboy96** [comment]
I get dropped connection on lofter.ph.126.net and imgsize.ph.126.net from Sweden, but imglf1.ph.126.net is 404.

**Comment by ivysrono** [comment]
Both OK from China, Now.
BTW, you can see ruleset for baidu.com https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Baidu.xml
Move all rules to the bottom of the ruleset may hard to userstand.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
