### PR TITLE
Add Biocubafarma.cu.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by pipboy96** [comment]
@J0WI Please check the rest of subdomains:
```
comedics.biocubafarma.cu - Found open ports: 443, 80
directorio.biocubafarma.cu - Found open ports: 443, 80
www.biocubafarma.cu - Found open ports: 443, 80
combiomed.biocubafarma.cu - Found open ports: 443, 80
comas.biocubafarma.cu - Found open ports: 443, 80
www.8marzo.biocubafarma.cu - Found open ports: 443, 80
www.cdc.biocubafarma.cu - Found open ports: 443, 80
capital.biocubafarma.cu - Found open ports: 443, 80
ba.biocubafarma.cu - Found open ports: 80
ncmistral.biocubafarma.cu - Found open ports: 443, 80
mba.biocubafarma.cu - Found open ports: 80
ocs.biocubafarma.cu - Found open ports: 443, 80
atlantis.oc.biocubafarma.cu - Found open ports: 80
pci.biocubafarma.cu - Found open ports: 443, 80
www.sigestic.biocubafarma.cu - Found open ports: 443, 80
openvpn.biocubafarma.cu - Found open ports: 443
sisconcil.biocubafarma.cu - Found open ports: 443, 80
vc.biocubafarma.cu - Found open ports: 443, 80
webmail.biocubafarma.cu - Found open ports: 443, 80
webpanel.biocubafarma.cu - Found open ports: 443, 80
```

**Comment by pipboy96** [comment]
@J0WI Do you know what causes failing tests?

**Comment by J0WI** [comment]
Some hosts are blocking Travis servers or vice versa.

**Comment by pipboy96** [comment]
@J0WI Will clone and run tests locally, then merge.

**Pull request merged**
