### PR TITLE
brew.sh: expand existing ruleset

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
Not really sure why the `fetch` CI failed looking at that output, to be honest.

**Comment by jeremyn** [comment]
Thanks for the pull request. You've made some basic, but completely understandable, mistakes, for example `target`s like `brew.sh` don't automatically include subdomains like `jenkins.brew.sh`, and explicit `test`s are not needed except in special cases like with wildcards or `exclusion`s. Please take a look at [CONTRIBUTING.md](https://github.com/EFForg/https-everywhere/blob/5609071840e4016c5ed2859d0e99ffb328517b3c/CONTRIBUTING.md), particularly [this example](https://github.com/EFForg/https-everywhere/blob/5609071840e4016c5ed2859d0e99ffb328517b3c/CONTRIBUTING.md#example-ruleset-after-style-guidelines-are-applied-with-test-urls). Let us know here if you have any questions.

**Comment by DomT4** [comment]
Oh, apologies, I initially failed the tests & made some changes based off the advice it pointed to, but evidently I misunderstood that advice a little. Will tweak, thanks.

**Comment by DomT4** [comment]
Hopefully that's okay now. Hopefully.

I don't know how much this is a known thing but `makecrx.sh` makes some bad assumptions about what's available on macOS by default; one of the `sed` patterns isn't compatible with BSD-sed:
```
sed: 1: "s/\([0-9A-F]\{2\}\)/\\\ ...": bad flag in substitute command: 'I'
```
and there's no `sha1sum` on macOS by default. macOS has either `shasum` or obviously the usual `openssl sha -sha1` or `openssl dgst -sha1`.

**Comment by DomT4** [comment]
Failed CI. Ace 😓.

```
ERROR src/chrome/content/rules/brew.sh.xml: Fetch error: http://jenkins.brew.sh/ => https://jenkins.brew.sh/: (60, 'SSL certificate problem: unable to get local issuer certificate')
```

This isn't a problem in the browser (Tested with Chrome, at least), but can be if it's trying to verify it with `curl` or something like that. Unlike the main site `jenkins.brew.sh` runs on a separate server with its own unique certificate supplied by Let's Encrypt, which not everything does a good job of handling connections with.

**Comment by jeremyn** [comment]
I'm not sure how common MacOS is as a development environment for HTTPS Everywhere but please feel free to create an new issue or pull request for that problem. From my experience and observation, Ubuntu LTS is the (completely unofficially) preferred development environment, for example it's the base of the [Docker image](https://hub.docker.com/r/electronicfrontierfoundation/https-everywhere-docker-base/~/dockerfile/) used in the Travis tests. You may want to set up an Ubuntu VM for HTTPS Everywhere development, which is [what I do](https://github.com/jeremyn/https-everywhere-dev-environment).

For simple tests during development though, you can just run [`fetch-test.sh rules/YOUR-RULE.xml`](https://github.com/EFForg/https-everywhere/blob/088e1e1b85b4477b6acb70dd5cb429d5a60bdd98/fetch-test.sh). If you want to test in a browser, you can put the updated ruleset XML file into a [particular directory](https://www.eff.org/https-everywhere/rulesets#testing) for Firefox. You don't need to worry about the full test suite with `makecrx.sh` and everything just for simple ruleset changes.

The Travis error `(60, 'SSL certificate problem: unable to get local issuer certificate')` here means that the end server is misconfigured and doesn't provide a necessary intermediate certificate. It works in your browser because you've previously visited some other site that correctly served that intermediate certificate and your browser has cached it, so the misconfiguration isn't a problem. Try making a new profile and you should see something like this:

>jenkins.brew.sh uses an invalid security certificate.
>
>The certificate is not trusted because the issuer certificate is unknown.
>The server might not be sending the appropriate intermediate certificates.
>An additional root certificate may need to be imported.
>
>Error code: SEC_ERROR_UNKNOWN_ISSUER

We normally mark these domains as problematic in a top comment with a note like `Invalid certificate (incomplete certificate chain)`. You can find many examples of this in existing rulesets.

Also, please try to find some more domains for `brew.sh`. Sublist3r is a [good tool for that](https://github.com/EFForg/https-everywhere/blob/5609071840e4016c5ed2859d0e99ffb328517b3c/CONTRIBUTING.md#enumerating-subdomains). For example, `www.brew.sh` should be included.

**Comment by jeremyn** [comment]
@DomT4 Are you planning to work on this soon? If not, I'm going to unassign myself from this pull request.

**Comment by DomT4** [comment]
Apologies, got distracted by life & looking at things like https://github.com/EFForg/https-everywhere/pull/10328. Yes, will push some tweaks here soon, likely at some point tonight.

**Comment by jeremyn** [comment]
Okay thanks. It's not a huge rush.

**Comment by DomT4** [comment]
Hopefully this is okay now. Apologies for the numerous mistakes; the process has changed significantly since my last set of contributions & I should've done a better job reading the newer documentation. I'm a touch unsure about target ordering here but I think it's okay. Hopefully...

**Comment by jeremyn** [comment]
Thanks for the update. Please:

- [ ] Change the top comment to this:

```xml
<!--
	Connection refused:
		bot.brew.sh

	Invalid certificate:
		docs.brew.sh
		jenkins.brew.sh (incomplete certificate chain)

-->
```

This includes changes such as not mentioning domains that aren't in DNS (`community`), standardizing problem messages, and removing unnecessary comments.

**Comment by DomT4** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by DomT4** [comment]
Thanks for the assistance throughout.

**Pull request merged**
