### PR TITLE
Remove HSTS preload sites

### PR DESCRIPTION
**Pull request by galeksandrp**
You can test it with

``` sh
pip install tldextract
git diff origin/sslmate.com~2 origin/sslmate.com | grep '\-.*<target host="' | sed 's/-.*<target host="\(\*\.\)\?//' | cut -d '"' -f 1 | sort | uniq | xargs -n1 -i bash -c 'if [ $(tldextract {} | sed "s/^ //" | sed "s/ /\n/g" | wc -l) -ne 2 ]; then exit 1; fi && if [ "$(curl -s https://hstspreload.appspot.com/api/v2/preloadable?domain={})" != "$(echo -e "{\n  \"errors\": [],\n  \"warnings\": []\n}")" ]; then echo {}; fi'
```

### CODE REVIEW

**Comment by galeksandrp** [comment]
Hostname with platform '' shows up in 2 different rulesets

**Comment by J0WI** [comment]
They are still pending, so I can't remove them.

**Comment by galeksandrp** [comment]
Upd

**Comment by galeksandrp** [comment]
Updated.

**Comment by J0WI** [comment]
Maybe we can put this in our clean-up before release script?
cc @Hainish

**Comment by Hainish** [comment]
This is superceded by https://github.com/EFForg/https-everywhere/pull/8128

**Pull request closed without merging**
