### PR TITLE
Update and rename hidester.com.xml to Hidester.com.xml

### PR DESCRIPTION
**Pull request by ihave100openPRs**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Add `target` for https://devwp.hidester.com and remove it from `Invalid Certificate`
- [ ] Add `target` for https://piwik.hidester.com and remove it from `Invalid Certificate`

**Comment by ihave100openPRs** [comment]
@jeremyn Done!

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/13162/commits/0777758c86dbf0d2e33228be4f279d4329b4631b.

It looks like we need to remove `piwik`. I'm sorry for any confusion.

**Comment by ihave100openPRs** [comment]
@jeremyn Done!

**Pull request merged**
