### PR TITLE
Codestyle

### PR DESCRIPTION
**Pull request by J0WI**
converted linebreaks to unix style

### CODE REVIEW

**Comment by J0WI** [comment]
The fixes for the individual rules should be done in separate pull requests.

**Comment by J0WI** [comment]
Please merge #2961, #2962, #2963, #2964 and #2965 before.

**Comment by TheNavigat** [comment]
Our of pure curiosity, the changes tab shows that the deleted and added lines are identical. There are no differences when it comes to indentation, I just couldn't spot the difference. I'm wondering what has changed.

**Comment by J0WI** [comment]
@fuglede could you have a look at the depending pull request, that we can finally close this minor issue?

**Comment by semenko** [comment]
All deps should be close if you'd like to resolve the conflict. :+1:

**Comment by J0WI** [comment]
merged.

**Comment by J0WI** [comment]
ping @semenko

**Pull request merged**
