### PR TITLE
rm V2ex.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=15264), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10648), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11775)

### CODE REVIEW

**Comment by jeremyn** [comment]
Out of the eight subdomains covered by this ruleset, only `v2ex.com` is in the lists, so this rule is still partially valid.

**Comment by J0WI** [comment]
This host sends no preload header and refers to V2ex.co.xml

**Comment by jeremyn** [comment]
See pull request #7081 for a discussion on the `preload` header. I agree the reference in `V2ex.co.xml` should be removed.

**Comment by jeremyn** [comment]
See also issue #7126 .

**Comment by jeremyn** [comment]
https://v2ex.com does have `preload`: `Strict-Transport-Security:"max-age=10886400; includeSubDomains; preload"`.

**Pull request merged**
