### PR TITLE
[UnixStickers.com] New rule

### PR DESCRIPTION
**Pull request by chris-barry**

### CODE REVIEW

**Comment by J0WI** [comment]
Please use tabs instead of spaces to match our code style guide.

**Comment by chris-barry** [comment]
Sure. Sorry about that.
-- 
Chris Barry

**Comment by J0WI** [comment]
@chris-barry ping me if you fixed that

**Comment by chris-barry** [comment]
I fixed the space->tab (after way too long :dizzy_face:) @J0WI . The rule still says it's failing, but when I try in Firefox dev version, it works.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
