### PR TITLE
Create Backpack.tf.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by J0WI** [comment]
WFM:
ipv6.backpack.tf
csgo.backpack.tf
dota2.backpack.tf

Refused:
forums.backpack.tf

**Comment by ekaris** [comment]
Done

**Comment by J0WI** [comment]
There is something buggy with the tests, I'll merge this as soon as they are fixed.

**Comment by J0WI** [comment]
See #4645

**Pull request merged**
