### PR TITLE
Create Multinationales.org.xml

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Thank you!

btw @J0WI, I think you changed your settings to "Merge with merge commit" instead of "rebase and squash".

**Comment by J0WI** [comment]
@Hainish this just happened again. Has the merge policy in the repo setting been changed?

**Comment by Hainish** [comment]
@J0WI In my experience whatever merge method you chose last is set as the default the next time you go to merge.

**Comment by J0WI** [comment]
That was the case for me too until a few days (?) ago. Now it's always set to merge after logout.
The merge button can be configured in the repo settings (does not affect cli AFAIK). Should we force squash & merge?

**Comment by Hainish** [comment]
It can be configured to enable/disable certain merging methods, but not to prioritize merging methods.  I still use merge commits for releases, but could conceivably just do this on the command line.

Do you see any other problems with just disabling the other merge methods completely?

**Comment by J0WI** [comment]
Something has definitively been changed how GitHub is memorizing merge strategies.
If I look at the recent commit it sometimes worked after selecting it manually, but most of the time it didn't memorize my preference.

**Pull request merged**
