### PR TITLE
Add rule for mnultimate.org

### PR DESCRIPTION
**Pull request by ishults**

### CODE REVIEW

**Comment by J0WI** [comment]
Please also add the www subdomain as a target host an a comment, that the the server doesn't serve a mismatched cert for the dns subdomain.

Our code style recommends to use tabs.

**Comment by ishults** [comment]
Oh ok, sorry.  Should be fixed now.

**Comment by J0WI** [comment]
There is still a comment missing for the mismatch on `dns.mnultimate.org`.
Rule lgtm.

**Comment by ishults** [comment]
Shoot sorry, missed that point the first time.  I believe I've fixed it?  I looked over the README and other commits and think I did it right, but please let me know if I still missed something.

**Comment by J0WI** [comment]
Great!

**Comment by ishults** [comment]
Thanks for your help and patience!

**Pull request merged**
