### PR TITLE
Add tests against non-match groups being used in replacements (resolv…

### PR DESCRIPTION
**Pull request by Hainish**
…es #4327)

### CODE REVIEW

**Comment by Hainish** [comment]
Ready to review @jsha

**Comment by Hainish** [comment]
@cooperq

**Comment by cooperq** [comment]
How should I test this?

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/issues/4327#issue-140194129 lists a number of PRs.  For each of these, you can revert the PR and see if it throws errors.  Make sure to remove any affected files from `util/ruleset-coverage-whitelist.txt` first.

**Comment by cooperq** [comment]
lgtm

**Pull request merged**
