### PR TITLE
Update and re-enable ruleset: Igalia

### PR DESCRIPTION
**Pull request by fghzxm**
* Add targets

* Remove references to {jabalix,labs}.igalia.com which no longer exist

* Remove ruleset: Igalia-self-signed

### CODE REVIEW

**Comment by J0WI** [comment]
Looks good so far, please have a loo at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by J0WI** [comment]
Some misconfigured hosts are failing in our tests.

**Comment by fghzxm** [comment]
The failing hosts are websites that require HTTP authentication to access.  Our fetching test does not accept the 401 code they return; it may be a good idea to accept it (I have opened an [issue](
https://github.com/EFForg/https-everywhere/issues/17064) about this).

**Comment by J0WI** [comment]
The issue is on the server, because the hosts are working fine on HTTP, but requires authentication on HTTPS.
So these targets need to be removed. We have a guideline to document non-working hosts:
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts

**Comment by pipboy96** [comment]
@fghzxm Please confirm this PR still stands, else it may be closed for inactivity.

**Pull request closed without merging**
