### PR TITLE
[Skat.dk] Add new subdomains and comments on broken ones

### PR DESCRIPTION
**Pull request by fuglede**

### CODE REVIEW

**Comment by J0WI** [comment]
WFM:
inddrivelse.skat.dk
motorregister.skat.dk
export.skat.dk
extranet.skat.dk
pdcs.skat.dk

Refused:
(www.)tarif.skat.dk

**Comment by fuglede** [comment]
Thanks @J0WI, updated it a bit. Do you have any non-trivial test URLs for demonstrating the purpose of export.skat.dk and inddrivelse.skat.dk?

And by the way, do you have a script for finding subdomains? The one I'm using (which is based on Google searches) seems to be a bit inferior to whatever you are doing.

**Comment by J0WI** [comment]
Just use `site:inddrivelse.skat.dk` for search a valid test url.

Sadly Google limits the ability of scripting the searches, so I still search them manually.

**Comment by fuglede** [comment]
Updated again. It must be possible to bypass whatever checks Google might have come up with. (Or find a search engine with no such restrictions.)

**Pull request merged**
