### PR TITLE
update Addy.co.xml 

### PR DESCRIPTION
**Pull request by luciancor**

### CODE REVIEW

**Comment by J0WI** [comment]
This rule has no targets now.
You should default_off or removing it, because everything redirects to onfleet.co now.
If you remove it, do not forget to also remove the reference in Onfleet.com.xml

**Comment by tamoor-cliqz** [comment]
Alright thanks! We will send an updated PR

**Comment by J0WI** [comment]
@tamoor-cliqz @luciancor any update on this?

**Comment by luciancor** [comment]
@J0WI fixed!

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
