### PR TITLE
rm Riseup.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=609), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#8491), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n9386)

### CODE REVIEW

**Comment by jeremyn** [comment]
https://riseup.net doesn't have the `preload` header.

**Comment by jeremyn** [comment]
I've emailed Riseup to ask them whether they are planning to stay in the preload list or not.

**Comment by jeremyn** [comment]
I talked with some of the Riseup people on IRC (https://riseup.net/en/about-us/contact#irc). I was told they are looking at this and will update this PR soon.

**Comment by taggart** [comment]
Hi, we added preload to all our STS headers, thanks for the heads up!

**Comment by jeremyn** [comment]
Thanks @taggart. I can confirm that `preload` has been added to the STS header returned from https://riseup.net.

Checklist:

- [x] [Firefox release](https://dxr.mozilla.org/mozilla-release/rev/29f0e9c0d597f4922c55d7a5405132541eb5998e/security/manager/ssl/nsSTSPreloadList.inc#9587)
- [x] [Firefox ESR](https://dxr.mozilla.org/mozilla-esr45/rev/53ed48ebadea12f495e5391411dd7672fda7965b/security/manager/ssl/nsSTSPreloadList.inc#13166)
- [x] [Chromium 55.0.2883.87](https://chromium.googlesource.com/chromium/src.git/+/55.0.2883.87/net/http/transport_security_state_static.json#610)
- [x] [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.7.0esr-6.5-1#n11497)

So this looks fully preloaded. I've merged the ruleset deletion.

@taggart Just FYI:

* `preload` isn't on all your subdomains, for example it's missing from https://we.riseup.net, however Google only cares about the base domain (https://hstspreload.org/#submission-requirements) so that's fine.
* Without the ruleset you'll also lose the [secure cookie protection](https://github.com/EFForg/https-everywhere/blob/342768f2a9f1a5ff2a7fc3e1508e9751ed3cf1f4/src/chrome/content/rules/Riseup.xml#L29), so if you care about that then you'll need to take care of that yourself if you don't already.

**Comment by gloomy-ghost** [comment]
The securecookie protection is superceded by HSTS as the domain and its subdomains are automatically redirected to https.

**Pull request merged**
