### PR TITLE
Add SMWCentral.xml

### PR DESCRIPTION
**Pull request by smw-koops**

### CODE REVIEW

**Comment by jeremyn** [comment]
This looks fine. We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means combining and rewriting pull requests in your name. Are you okay with that for this and any other pull requests you submit to us?

**Comment by smw-koops** [comment]
@jeremyn Yes, go for it.

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by smw-koops** [comment]
@jeremyn I also made a duplicating pull request (#7458) and would like it to be merged with this one.

**Pull request merged**
