### PR TITLE
[StartMail] Add subdomain forum and remove subdomain beta

### PR DESCRIPTION
**Pull request by fuglede**
The host serves a HSTS header, so this should be trivial. This closes https://trac.torproject.org/projects/tor/ticket/14003.

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] You can delete the [list of covered domains](https://github.com/fuglede/https-everywhere/blob/bec7bc1a4f270cedc6105e3d8147a3d15675a008/src/chrome/content/rules/StartMail.xml#L7-L13) in the comment, right? The same information is about ten lines down.
- [ ] Change `beta` to `beta.startmail.com` in the comment
- [ ] https://beta.startmail.com has multiple problems for me, none of which `self-signed`. Maybe just use `invalid certificate`?
- [ ] The `www` target should go between `^` and `forum`.

**Comment by fuglede** [comment]
On Mon, Sep 19, 2016 at 04:23:39PM -0700, Jeremy Nation wrote:
> - [ ] You can delete the [list of covered domains](https://github.com/fuglede/https-everywhere/blob/bec7bc1a4f270cedc6105e3d8147a3d15675a008/src/chrome/content/rules/StartMail.xml#L7-L13) in the comment, right? The same information is about ten lines down.

That's a matter of taste, I suppose. I figure that MB probably has a reason to set it up like this for a reason.

> - [ ] Change `beta` to `beta.startmail.com` in the comment

I think it makes more sense this way; there's only one eTLD+1 here.

> - [ ] https://beta.startmail.com has multiple problems for me, none of which `self-signed`. Maybe just use `invalid certificate`?

The self-signed certificate is the intermediate one (`openssl` output below). Let me update the comment to be more precise.

> - [ ] The `www` target should go between `^` and `forum`.

As in the first comment above.

	$ openssl s_client -connect beta.startmail.com:443 </dev/null
	CONNECTED(00000003)
	depth=1 C = US, ST = New York, L = New York, O = I2X LLC., CN = Martijn de Vries, emailAddress = martijn@vo.com
	verify error:num=19:self signed certificate in certificate chain
	verify return:0
	---
	Certificate chain
	 0 s:/C=NL/ST=NH/L=Amsterdam/O=Ixquick/CN=s1.eu.ixquick.com/emailAddress=martijn@vo.com
	   i:/C=US/ST=New York/L=New York/O=I2X LLC./CN=Martijn de Vries/emailAddress=martijn@vo.com
	 1 s:/C=US/ST=New York/L=New York/O=I2X LLC./CN=Martijn de Vries/emailAddress=martijn@vo.com
	   i:/C=US/ST=New York/L=New York/O=I2X LLC./CN=Martijn de Vries/emailAddress=martijn@vo.com
	---
	Server certificate
	-----BEGIN CERTIFICATE-----
	MIIDgDCCAumgAwIBAgIBFjANBgkqhkiG9w0BAQQFADCBgDELMAkGA1UEBhMCVVMx
	ETAPBgNVBAgTCE5ldyBZb3JrMREwDwYDVQQHEwhOZXcgWW9yazERMA8GA1UEChMI
	STJYIExMQy4xGTAXBgNVBAMTEE1hcnRpam4gZGUgVnJpZXMxHTAbBgkqhkiG9w0B
	CQEWDm1hcnRpam5Adm8uY29tMB4XDTA1MDIwNjE3MTY0NFoXDTEzMDQyNTE3MTY0
	NFowezELMAkGA1UEBhMCTkwxCzAJBgNVBAgTAk5IMRIwEAYDVQQHEwlBbXN0ZXJk
	YW0xEDAOBgNVBAoTB0l4cXVpY2sxGjAYBgNVBAMTEXMxLmV1Lml4cXVpY2suY29t
	MR0wGwYJKoZIhvcNAQkBFg5tYXJ0aWpuQHZvLmNvbTCBnzANBgkqhkiG9w0BAQEF
	AAOBjQAwgYkCgYEA4ZxLQh8FFofq4VbMv+Au2Dj+5szuJ7pUnfE7WRJrx1DVneUK
	LyhJ9vVCtpvbqmZFuoZqphAEXWLBf8niZLDmI0Vfu5tWw4FXLrW08P7jc6KQPRk6
	Vc74jnPQhJ+DCwwngpXj2XTKsmC+qDNqqlLdSeDCVICzi8aLi7F+hwMDSA0CAwEA
	AaOCAQwwggEIMAkGA1UdEwQCMAAwLAYJYIZIAYb4QgENBB8WHU9wZW5TU0wgR2Vu
	ZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdDgQWBBRzcPQ6Yak294wFtfkGbfCi1hwV
	wDCBrQYDVR0jBIGlMIGigBSueQlipAQ4zmA17049FbJbsOaB/KGBhqSBgzCBgDEL
	MAkGA1UEBhMCVVMxETAPBgNVBAgTCE5ldyBZb3JrMREwDwYDVQQHEwhOZXcgWW9y
	azERMA8GA1UEChMISTJYIExMQy4xGTAXBgNVBAMTEE1hcnRpam4gZGUgVnJpZXMx
	HTAbBgkqhkiG9w0BCQEWDm1hcnRpam5Adm8uY29tggEAMA0GCSqGSIb3DQEBBAUA
	A4GBAHAR5LwMplH+/NPxQyKNHP4coNMaBG7TQYP7tHy3WjYaiDsuDSGiOWqbNKoo
	4ah4QhLiwoQr/ZGQ816mYWq7RDPsMSqoL5dUBHzyVdpp+j8ytSNj9Iob79PlzN0H
	hi0QrSwb5Y5HIwWE2j6/4AWaGjjF9DLiWfbmxhuFZUDQhEVX
	-----END CERTIFICATE-----
	subject=/C=NL/ST=NH/L=Amsterdam/O=Ixquick/CN=s1.eu.ixquick.com/emailAddress=martijn@vo.com
	issuer=/C=US/ST=New York/L=New York/O=I2X LLC./CN=Martijn de Vries/emailAddress=martijn@vo.com
	---
	No client certificate CA names sent
	---
	SSL handshake has read 2327 bytes and written 415 bytes
	---
	New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
	Server public key is 1024 bit
	Secure Renegotiation IS supported
	Compression: NONE
	Expansion: NONE
	SSL-Session:
	    Protocol  : TLSv1.2
	    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
	    Session-ID: E3516F914CFF4137749DCD7771E66E466C13C9CCAC724099BC899E79B3F27461
	    Session-ID-ctx: 
	    Master-Key: 73500BAF7CA4009430A4C8BE2DD2A2F1701347ECDB24029C4BA631FCD3C894EDB087732693D8C2277A3548CD9180AEFD
	    Key-Arg   : None
	    PSK identity: None
	    PSK identity hint: None
	    SRP username: None
	    TLS session ticket lifetime hint: 600 (seconds)
	    TLS session ticket:
	    0000 - ab f4 cb 43 79 06 aa d9-05 0a 91 8a 73 aa 58 78   ...Cy.......s.Xx
	    0010 - 48 e6 61 6b fe b8 67 c6-be f1 89 ac e3 3d 53 21   H.ak..g......=S!
	    0020 - 42 71 ea 85 10 df 4a 32-df a8 26 08 72 d8 1f 82   Bq....J2..&.r...
	    0030 - cf a4 43 9c 8b df 41 e1-b4 99 93 5b 88 02 60 6c   ..C...A....[..`l
	    0040 - 46 50 47 f9 3e c1 0f af-cf ee 7d 03 13 7b b2 f1   FPG.>.....}..{..
	    0050 - 24 25 ef 51 14 97 5f 91-e1 16 88 d4 41 a8 ed 22   $%.Q.._.....A.."
	    0060 - ad 77 59 6a 8c 2a 91 a0-86 aa ac 51 a7 ff 71 e4   .wYj.*.....Q..q.
	    0070 - 11 52 aa e6 79 36 37 26-69 42 b8 37 bd e8 6e da   .R..y67&iB.7..n.
	    0080 - bf 5c 40 f1 8f 67 18 52-5a e2 4b c5 08 4f 6d 00   .\@..g.RZ.K..Om.
	    0090 - de 28 02 39 7b 09 75 2b-1d d7 f8 2f df b7 ca 0f   .(.9{.u+.../....
	    00a0 - a7 97 40 77 dd 98 31 3f-a1 2b ba 5d 92 53 3e 19   ..@w..1?.+.].S>.
	    00b0 - 4b 67 93 90 5f 77 c1 82-c1 2f 6c e6 7b 4b 95 2b   Kg.._w.../l.{K.+

	    Start Time: 1474363405
	    Timeout   : 300 (sec)
	    Verify return code: 19 (self signed certificate in certificate chain)
	---
	DONE

**Comment by fuglede** [comment]
Looks like the comment on secure cookies didn't reach my inbox. That one is left out on purpose, since I didn't check whether or not it was safe in this case.

**Comment by jeremyn** [comment]
Completely extraneous comments should be deleted. Maybe that is a matter of taste but I don't think so. I don't know who MB is but if you want to call them in here and ask them if those comments have any special meaning, then sure.

I want people to start putting full domains in the top comments. It makes it easier to cut-and-paste for testing. If someone needs to add a new subdomain to a ruleset, then they don't have to go back and clarify the comments. It's a trivial problem in this small ruleset but much more dramatic for example [here](https://github.com/Riotism/https-everywhere/blob/6d2ce1e9c9e01cccb858041e10e57229afcf99ee/src/chrome/content/rules/CUHK.xml) and I'd like to be consistent.

Do you mean you think "MB" has some special reason for deliberately sorting `www` to the end of the list against our usual style?

How could a general `securecookie` not be safe? The only way I can think of is that one of the targets sets a cookie for `.startmail.com` and then it causes problems on `beta.` or some other subdomain we're  not covering. That was the same potential problem we had in #6903 and we used the `.+` `securecookie` there.

**Comment by fuglede** [comment]
> Completely extraneous comments should be deleted. Maybe that is a matter of taste but I don't think so. I don't know who MB is but if you want to call them in here and ask them if those comments have any special meaning, then sure.

I don't think they are complete redundant as they can help in providing an overview. MB is probably the most prolific ruleset writer; counting additions (which may or may not be a useful statistic), you'll get these numbers:

    $ git log --author="MB" --pretty=tformat: --numstat . | cut -f1 | awk '{s+=$1} END {print s}'
    695756

For comparison:

    $ git log --author="Fuglede" --pretty=tformat: --numstat . | cut -f1 | awk '{s+=$1} END {print s}'
    3171

Moreover, the comment pattern is extremely common in the database:

    $ grep 'Fully covered' * | wc -l
    1924

> I want people to start putting full domains in the top comments. It makes it easier to cut-and-paste for testing. If someone needs to add a new subdomain to a ruleset, then they don't have to go back and clarify the comments. It's a trivial problem in this small ruleset but much more dramatic for example [here](https://github.com/Riotism/https-everywhere/blob/6d2ce1e9c9e01cccb858041e10e57229afcf99ee/src/chrome/content/rules/CUHK.xml) and I'd like to be consistent.

Not that I think total consistency is necessarily necessary, I'd say we're already pretty consistent in only specifying the subdomain part of it.

> Do you mean you think "MB" has some special reason for deliberately sorting `www` to the end of the list against our usual style?

As above. Can't say what the exact reasoning is. It's certainly done that way in many other rulesets, cf. e.g. a quick look at `grep '<target host="www' * -B 1`.

> How could a general `securecookie` not be safe? The only way I can think of is that one of the targets sets a cookie for `.startmail.com` and then it causes problems on `beta.` or some other subdomain we're  not covering. That was the same potential problem we had in #6903 and we used the `.+` `securecookie` there.

That's also what I had in mind (and touched upon in https://github.com/EFForg/https-everywhere/issues/2907#issuecomment-2450582809). In #6903, the tag was there to begin with, so it seemed counterproductive to remove it.

**Comment by jeremyn** [comment]
I don't agree with the theory that just because MB included apparently useless comments or apparently mis-sorted something, that the way they did it must be correct, no matter how awesome MB normally is. If I submitted this as a new ruleset and had `www` at the bottom, you'd tell me to move it, and if I didn't have the useless comment, you wouldn't tell me to add it.

With the full subdomain, you didn't address the merits of the two reasons I gave, you just said that's how we've always done it. It would be a lot of work to redo the old stuff but we can do it better going forward, so when new contributors look at the most recent edits by reviewers, they can see what the current encouraged practice is.

That's fine about `securecookie`.

Anyway the substantive changes are valid, so if you don't intend to make the other changes, just confirm that in a comment and I'll merge it as-is.

**Comment by jeremyn** [comment]
Status on this one please?

**Comment by jeremyn** [comment]
@fuglede I'd like to clear this one out, please.

**Comment by jeremyn** [comment]
I'm unassigning myself from this pull request due to lack of response.

@fuglede For this specific pull request, please follow up with one of the other maintainers when you are ready to get this resolved.

**Comment by jeremyn** [comment]
I'm closing this PR in favor of my new PR https://github.com/EFForg/https-everywhere/pull/13622.

**Pull request closed without merging**
