### PR TITLE
[Axosoft.com] Added new targets

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by Roman3349** [comment]
@J0WI Fixed

**Comment by J0WI** [comment]
The following are also working:
sysys.axosoft.com
pmisportal.axosoft.com
practicesightssupportportal.axosoft.com
help.axosoft.com
amt-softwareportal.axosoft.com
iecisa-ift.axosoft.com
smg.axosoft.com

Mismatch on:
promos.axosoft.com
blog.axosoft.com

You can remove the "(partial)" flag then.

**Comment by Roman3349** [comment]
@J0WI Done

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
