### PR TITLE
masterpasswordapp.com

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by injust** [comment]
Please add `ssl.masterpasswordapp.com` as a target.

**Comment by theel0ja** [comment]
Done.

**Comment by J0WI** [comment]
Could you add a comment about the wildcard DNS record?

**Comment by theel0ja** [comment]
So something like this?

https://github.com/EFForg/https-everywhere/blob/620ad5f2ca607a3c45c6648b5781616aff000975/src/chrome/content/rules/Openshot.org.xml#L1-L3

**Comment by J0WI** [comment]
Exactly.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
