### PR TITLE
Create ecotrop.com.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
Previous PR #8400 was created in the wrong folder

### CODE REVIEW

**Comment by J0WI** [comment]
This host is currently not available.

**Comment by jeremyn** [comment]
https://ecotrop.com and https://www.ecotrop.com get 503 responses for me.

**Comment by jeremyn** [comment]
@Bisaloo I'm still getting 503s. Can we close this pull request?

**Comment by Bisaloo** [comment]
Well, I'd say it is up to you. I don't know your policy in this case.

The host was working when I submitted this PR. It doesn't at the moment and I have no idea whether it is going to come back or not.

So feel free to do as you see fit.

I can always resubmit if needed.

**Comment by jeremyn** [comment]
There's no specific policy that I know of, it's just good to close PRs we can't do anything with.

I'm closing this, but feel free to reopen it or make a new one if the site comes back.

**Pull request closed without merging**
