### PR TITLE
Create appinn.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

Note as `Invalid certificate`:
- [ ] https://g.appinn.com
- [ ] https://g1.appinn.com

Also, can you confirm your results for these? I get different responses from you, but I might just have trouble connecting. If you get what you originally had then you can leave it the way it is.
- [ ] I get `Refused` for https://img.appinn.com (instead of invalid certificate).
- [ ] I get `Timeout` for https://m.appinn.com (instead of `Redirect to http`).

Also:

- [ ] It seems [`*.appinn.me`](https://www.google.com/#q=site:*.appinn.me) is related to `appinn.com`, is that right? If so, can you add the `*.appinn.me` targets and change the ruleset name to `APPINN`, and filename to `Appinn.xml`?

**Comment by jeremyn** [comment]
[This comment](https://github.com/renyouguo/https-everywhere/blob/23965fd0dc24bff6428711a54a8bbec7556725b3/src/chrome/content/rules/Appinn.xml#L21) should be `*.appinn.me`, not `*.appinn.com`, right?

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by gloomy-ghost** [comment]
image

**Comment by renyouguo** [comment]
@gloomy-ghost 还是第一次碰到能通过自动测试但在Tor中无法通过的，见鬼了。
#6994

**Comment by gloomy-ghost** [comment]
@renyouguo 你仔细看一下我的名字→→

**Comment by renyouguo** [comment]
@gloomy-ghost 啊，鬼大人，失敬失敬～

英语差到两个单词都不认识…

**Comment by gloomy-ghost** [comment]
@renyouguo 在PR上强势刷了波屏，感觉还挺好玩的233

**Comment by renyouguo** [comment]
@gloomy-ghost 怎么一下子发了那么多……

**Comment by gloomy-ghost** [comment]
@renyouguo 我无聊呗→_→虽然本来可以当成打卡一样每天来一条的233

**Comment by renyouguo** [comment]
@gloomy-ghost 怎么发现那么多有问题需要删除的？

**Comment by gloomy-ghost** [comment]
@renyouguo <del>肉眼找</del>

**Pull request merged**
