### PR TITLE
reenable Beck_PC.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@jsha is 'missing certificate chain' obsolete since the ruleset tests has been fixed?

**Comment by jsha** [comment]
Missing certificate chain is a potential problem, not just for the ruleset tests, but also for browsers. Browser behavior when confronted with a missing intermediate is unpredictable: Effectively, if the browser has a cached copy of that intermediate, it will work; otherwise not.

You can see this in action by using a fresh Firefox profile to fetch the page:

`firefox -no-remote -profile `mktemp -d` https://beckpc.ch`

**Comment by jsha** [comment]
Also, just to be clear, this differs from "can't find issuer cert," which means that the chain was present, but the checker wasn't aware of the intermediate and so wasn't able to validate it (since the checker is bad at path building).

**Comment by J0WI** [comment]
okay, closing for now.

**Pull request closed without merging**
