### PR TITLE
Remove wildcard targets from HypeMachine.xml

### PR DESCRIPTION
**Pull request by cschanaj**

### CODE REVIEW

**Comment by cschanaj** [comment]
@J0WI Travis passed. thanks!!

**Comment by J0WI** [comment]
I suspected that `x.hypem.com` is already covered by Bitly, but for some reason it didn't show up when I searched for it...
Could you revert this please, because the list was updated by Bitly itself in the past.

**Comment by cschanaj** [comment]
@J0WI sorry for the delay. I have force-pushed a new commit accordingly. thanks.

**Comment by J0WI** [comment]
LGTM, thanks!

**Pull request merged**
