### PR TITLE
Added .editorconfig

### LINKED ISSUE #5837: .editorconfig
Let's set up our own :-)
http://editorconfig.org/

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #5837

cc: @fuglede, @J0WI, @Hainish

### CODE REVIEW

**Comment by Hainish** [comment]
Neat!

**Comment by luixxiul** [comment]
Should ``indent-size`` be 8? /cc: @Hainish

**Comment by Hainish** [comment]
I think 4 is fine for the `xml` indentation

**Comment by luixxiul** [comment]
It seems to me that the tab size became smaller because of the setting from [this](https://github.com/EFForg/https-everywhere/pull/6217/files) to [this](https://github.com/EFForg/https-everywhere/pull/5976/files). Let me know if it is not good.

**Comment by Hainish** [comment]
That probably depends on your editors previous setting.  One thing we could do is leave it unspecified, and that way indentation will be tabs but we won't be prescriptive in how that's displayed in the editors of our contributors.

**Comment by luixxiul** [comment]
OK got it, thanks.

**Comment by Hainish** [comment]
Thank you!

**Pull request merged**
