### PR TITLE
Add timus.online.xml

### PR DESCRIPTION
**Pull request by pipboy96**

### CODE REVIEW

**Comment by pipboy96** [comment]
`acm.timus.ru` is old domain that does not support https. You can verify the redirect by checking that IP points to same ASN (Ural Federal University, AS5468).

**Comment by cschanaj** [comment]
@pipboy96 I think you have mistakenly create a branch on the EFF repo. Would you re-open a PR on your own fork?

**Comment by pipboy96** [comment]
@cschanaj oops.

**Comment by pipboy96** [comment]
@cschanaj #18379

**Pull request closed without merging**
