### PR TITLE
[Pocketbook.com] Remove wildcard

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Change the `ruleset` `name` to `GetPocketbook.com`
- [ ] Change the filename to `GetPocketbook.com.xml`

**Comment by jeremyn** [comment]
Also, please squash your changes into one commit that refers to `GetPocketbook.com`, not `Pocketbook.com`.

**Comment by jeremyn** [comment]
This looks fine. I'll just squash the commits in GitHub. Is it all right if I use the commit message "[GetPocketbook.com] Remove wildcard (#14322)"?

**Comment by Bisaloo** [comment]
Yes, thank you. This will be easier.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
