### PR TITLE
New ruleset: cuhk.edu.hk

### PR DESCRIPTION
**Pull request by Riotism**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset! I can review this, but can you please first fix these errors in the tests?

```
ERROR src/chrome/content/rules/CUHK.xml: Fetch error: http://apps.osa.cuhk.edu.hk/ => https://apps.osa.cuhk.edu.hk/: (6, 'Could not resolve host: apps.osa.cuhk.edu.hk')
ERROR src/chrome/content/rules/CUHK.xml: Fetch error: http://e.cuhk.edu.hk/ => https://e.cuhk.edu.hk/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/CUHK.xml: Fetch error: http://webmail.e.cuhk.edu.hk/ => https://e.cuhk.edu.hk/: (60, 'SSL certificate problem: unable to get local issuer certificate')
```

The first error means that `apps.osa.cuhk.edu.hk` should be removed because it doesn't exist, and the second and third errors mean that https is misconfigured for `e.cuhk.edu.hk`, so you need to either get the site admin to fix their https configuration or make sure nothing rewrites to https://e.cuhk.edu.hk/ .

**Comment by jeremyn** [comment]
Thanks. Please make the following changes:

Note in a [top comment](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=problematic+domains) as `Invalid cert`:
- [ ] https://webmail3.se.cuhk.edu.hk

Note in the top comment as `Mixed content`:
- [ ] https://www.scs.cuhk.edu.hk (remove target)
- [ ] https://www5.cuhk.edu.hk (seen at https://www5.cuhk.edu.hk/itsc/ccd/ ) (remove target)
- [ ] https://strategicplan.cuhk.edu.hk (remove [this comment](https://github.com/Riotism/https-everywhere/blob/8d0c928143fac4141b3748dce07331e7382cce69/src/chrome/content/rules/CUHK.xml#L29))

Add targets for:
- [ ] https://onepass.cuhk.edu.hk
- [ ] https://iii.lib.cuhk.edu.hk
- [ ] https://alumni.se.cuhk.edu.hk
- [ ] https://logitsco.cuhk.edu.hk
- [ ] https://www.logitsco.cuhk.edu.hk

Also:
- [ ] Change the exclusion [here](https://github.com/Riotism/https-everywhere/blob/8d0c928143fac4141b3748dce07331e7382cce69/src/chrome/content/rules/CUHK.xml#L66) to `<exclusion pattern="^http://www\.cuhk\.edu\.hk/(chinese|english)/(?!css/|fonts/|images|js/)" />`
- [ ] Remove [this comment](https://github.com/Riotism/https-everywhere/blob/8d0c928143fac4141b3748dce07331e7382cce69/src/chrome/content/rules/CUHK.xml#L55) `<!-- *.itsc.cuhk.edu.hk -->`
- [ ] Remove [this comment](https://github.com/Riotism/https-everywhere/blob/8d0c928143fac4141b3748dce07331e7382cce69/src/chrome/content/rules/CUHK.xml#L29) `<!-- <target host="strategicplan.cuhk.edu.hk" /> expired cert (but keeping in case they renew) -->` and instead note the subdomain in the top comment under `Invalid cert`
- [ ] Sort the subdomains in order starting from the top-level `.hk` and working to the left. So, for example, the `*.ilc.cuhk.edu.hk` domains should be next to each other.
- [ ] Make the `rule` tag [here](https://github.com/Riotism/https-everywhere/blob/8d0c928143fac4141b3748dce07331e7382cce69/src/chrome/content/rules/CUHK.xml#L73) aligned with the `target` tags
- [ ] Using the [search trick](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) in the style guide (example search [here](https://www.google.com/search?q=site%3A*.ws.cuhk.edu.hk&ie=utf-8&oe=utf-8#q=site:*.cuhk.edu.hk+-site:www.cuhk.edu.hk+-site:adm.osp.cuhk.edu.hk+-site:alumni.law.cuhk.edu.hk+-site:cusis.cuhk.edu.hk+-site:cpdc.osa.cuhk.edu.hk+-site:department.obg.cuhk.edu.hk+-site:elearn.cuhk.edu.hk+-site:eshop.rct.cuhk.edu.hk+-site:ewebmail.ie.cuhk.edu.hk+-site:gradsrv.itsc.cuhk.edu.hk+-site:hlma.math.cuhk.edu.hk+-site:ilcnte.ilc.cuhk.edu.hk+-site:internet.mfpo.cuhk.edu.hk+-site:library.cuhk.edu.hk+-site:mbacoursereg.baf.cuhk.edu.hk+-site:pcp.med.cuhk.edu.hk+-site:perntc.per.cuhk.edu.hk+-site:portal.cuhk.edu.hk+-site:rbs.lib.cuhk.edu.hk+-site:rgsntl.rgs.cuhk.edu.hk+-site:staff.ie.cuhk.edu.hk+-site:strategicplan.cuhk.edu.hk+-site:sts.cuhk.edu.hk+-site:timetable4.cuhk.edu.hk+-site:veriguide1.cuhk.edu.hk+-site:veriguide4veriguide4.cse.cuhk.edu.hk+-site:webapp1.law.cuhk.edu.hk+-site:webapps.med.cuhk.edu.hk+-site:webmail.se.cuhk.edu.hk+-site:www.adm.cuhk.edu.hk+-site:www.aic.cuhk.edu.hk+-site:www.cpr.cuhk.edu.hk+-site:www.erg.cuhk.edu.hk)), I see that there are many other subdomains that should either be included as targets or noted in the top comment as bad, such as `www.ws.cuhk.edu.hk`, `www.oal.cuhk.edu.hk` etc. Please try to get more of these subdomains. Google search only allows a maximum of 32 "words", including exclusions like `-site:`, so I suggest doing the search trick by subdomain, for example `site:*.pharmacy.cuhk.edu.hk -site:www.pharmacy.cuhk.edu.hk`.

**Comment by jeremyn** [comment]
Thanks for making the changes, especially adding the new domains.

The only thing remaining is a little silly: in the search trick item, I mentioned as an example `*.pharmacy.cuhk.edu.hk` but you didn't add those. It turns out there are only two, and I've added them (unchecked) to the list.

**Comment by jeremyn** [comment]
I also added one more item asking that you add `.cuhk.edu.hk` to the items in the top comment.

**Comment by jeremyn** [comment]
Also, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means we rewrite commits in your name. Is that okay with you for this and any other pull requests you submit to us?

**Comment by jeremyn** [comment]
I've updated the checklist through 76ac35ae791fc240b7083e2da88938bf51106fee, which is now complete. Please answer my question in https://github.com/EFForg/https-everywhere/pull/4646#issuecomment-248314654 . If that's fine then I'll merge this.

**Comment by jeremyn** [comment]
This is ready to go, just waiting for approval to squash-and-merge.

**Comment by Riotism** [comment]
I approve squash and merge

**Comment by jeremyn** [comment]
I'm getting a time out for https://perntc.per.cuhk.edu.hk (both HTTPS and HTTP). Please remove [the target](https://github.com/Riotism/https-everywhere/blob/76ac35ae791fc240b7083e2da88938bf51106fee/src/chrome/content/rules/CUHK.xml#L181). Because it's timing out for HTTP as well, you don't need to add it to the top comment.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
