### PR TITLE
Update imagecurl.com.xml

### PR DESCRIPTION
**Pull request by zero77**

### CODE REVIEW

**Comment by J0WI** [comment]
Left wildcards requires at least 3 [test urls](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md).
Rule LGTM.

**Comment by zero77** [comment]
The tested https URLs I'm aware of currently are:
cdn.imagecurl.com
www.imagecurl.com
imagecurl.com
Does that meet the left wildcard requirements.

**Comment by J0WI** [comment]
^imagecurl.com doesn't match the wildcard, but if you are sure that there are no more subdomains and that there will no unsecured subdomains in near future, you can workaround using a test domain like `http://www.imagecurl.com/foo` as the third one.

**Comment by zero77** [comment]
yes they are all the subdomains I'm currently aware of although i don't know about the future.
Whats the time period be for it will be live within the add on.

**Pull request merged**
