### PR TITLE
Create ruleset for: Kompas.com

### PR DESCRIPTION
**Pull request by dikiaap**
They are some of the most visited news site and forum in Indonesia.

This is my first contribution here. If something goes wrong with the ruleset, let me know.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Hi, thank you for your contribution! Could you split this pull request into several smaller ones, with only one ruleset per pull request please?

**Comment by dikiaap** [comment]
@Bisaloo Sure. It's done.

**Comment by Bisaloo** [comment]
@dikiaap, sorry, it's not what I meant. It's easier for us to review one ruleset at a time. We usually ask contributors to only edit one ruleset per pull request (see https://github.com/EFForg/https-everywhere/pulls). Can you edit this PR to only add `kompas.com` for example and then open multiple PR for the others?

Is that clearer?

**Comment by J0WI** [comment]
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains, there are many more targets that can be added :wink:

**Pull request closed without merging**
