### PR TITLE
[Einstein@Home] Add .org rule

### PR DESCRIPTION
**Pull request by funkydude**
Adds rules for einstein@home's alternative .org domain and securecookie
entry for its uwm.edu domain.

### CODE REVIEW

**Comment by funkydude** [comment]
@J0WI any comments on this?

**Comment by J0WI** [comment]
Yes, the `Einstein@Home` rules lgtm, but `uwm.edu` is quite complex with a lot of content. I need a bit more time for it.

**Comment by J0WI** [comment]
Universities tend to have a complex domain structure. I list a bunch of them below:

WFM:
albertathome.org
www.albertathome.org

pantherfile.uwm.edu
www4dev.uwm.edu
web.sa.uwm.edu
apps.sa.uwm.edu
apps.uwm.edu
techmallshop.uwm.edu
people.uwm.edu
oar.uwm.edu
uwm.t2hosted.com
innovwthrdev.uwm.edu
roomscheduling.uwm.edu
www.lsc-group.phys.uwm.edu (some 404)


Timeout:
bookstore.uwm.edu
access*.r2d2.uwm.edu

Refused:
www.cs.uwm.edu
collections.lib.uwm.edu
studentorgs.uwm.edu
entech-dev.cuir.uwm.edu
entech.cuir.uwm.edu
everyday.uwm.edu

Mismatch:
dc.uwm.edu
guides.library.uwm.edu
greatlakesgenomics.uwm.edu
www.r2d2.uwm.edu
photoarchive.uwm.edu
surface.chem.uwm.edu
d2l.uwm.edu

Self-Signed:
ccr-test.uits.uwm.edu
onemolecule.chem.uwm.edu
derecho.math.uwm.edu
home.freshwater.uwm.edu

**Comment by funkydude** [comment]
@J0WI I'm finished with this branch.

**Comment by J0WI** [comment]
Great, Thank you!

**Pull request merged**
