### PR TITLE
update pandora

### PR DESCRIPTION
**Pull request by redranamber**
I checked pandora with a vpn and the region block works now. So I rewrote the rule to be more complete.

### CODE REVIEW

**Comment by jeremyn** [comment]
FYI: this is one of the sites referring to in issue #3069 .

**Comment by jeremyn** [comment]
@redranamber Thanks for the update. Can you please squash the eight commits you have into just one commit that updates `Pandora.xml`?

**Comment by redranamber** [comment]
I'm not sure how to do that. Is there an easier way than creating a new fork and submitting another pull request?

**Comment by TK-999** [comment]
@redranamber check out https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jeremyn** [comment]
@redranamber : @TK-999 's response is exactly on point (thanks!). The following URL might also help, as it's a little more general and a little more "official": https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by redranamber** [comment]
It's not working out for me. Nothing happens after I edit the file.

**Comment by jeremyn** [comment]
When all else fails with git:
 
1. Copy the changes you want to make to someplace outside of the git structure, so copy your modified `Pandora.xml` to your home directory or something.
2. Do a `git reset --hard` on your branch to a known good commit, something like: `git reset --hard origin/master`
3. Copy your changes back to your git directory, so copy your modified `Pandora.xml` back to where you found it
4. Make a new commit

**Pull request closed without merging**
