### PR TITLE
Create luosimao.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@Hainish

**Comment by Hainish** [comment]
Again, `<test>` URLs are helpful here.  All I see is a 404 when I try to access `client.luosimao.com`

**Comment by J0WI** [comment]
Yes, test urls would be helpful for every host that does not return 200, especially CDNs like s.luosimao.com.

rule itself lgtm.

**Comment by J0WI** [comment]
You need to exclude ^my.luosimao.com/$ for Travis.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
