### PR TITLE
Removing hsts-preloaded targets and rulesets (via hsts-prune utility)

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Great! Thank you!

However, I had noticed domains that have been preloaded but they weren't removed. For example:

- [twitter.com](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Twitter.xml)
- [aeon.co](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Aeon.co.xml)

and some others I lost on the way.

Any idea why?

**Comment by Hainish** [comment]
@Bisaloo this may be for various reasons.  One is that they aren't preloaded on *all* the browsers that we support.  Another possible reason is that they aren't delivering the "preload" directive in the `Strict-Transport-Security` header - this makes these preloads prone to removal in future iterations of the list, so we don't want to remove them from HTTPS Everywhere and leave them unprotected.

**Comment by Hainish** [comment]
Checking now, the absence of the `preload` directive seems to be the case.

**Comment by Hainish** [comment]
I've just talked with the Tor Project web admins, they've added the preload directive back to `torproject.org` and associated subdomains.

**Comment by Bisaloo** [comment]
@Hainish, the `preload` directive is indeed back but they also need to add the `includeSubDomains` directive.

**Comment by Hainish** [comment]
@Bisaloo I've talked with them about this and they are unwilling to do so.  I'm unsure why.

**Pull request merged**
