### PR TITLE
Create XBRL.org.xml

### PR DESCRIPTION
**Pull request by sampablokuper**

### CODE REVIEW

**Comment by J0WI** [comment]
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by jeremyn** [comment]
@sampablokuper Are you still interested in working on this pull request?

**Comment by sampablokuper** [comment]
@jeremyn , yes in principle, but I'm afraid I can't spare time at the moment. Anyone interested should feel free to work on it.

**Comment by jeremyn** [comment]
There are several more subdomains that should be added as `target`s or noted as problematic. See [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/d6967f2dfe659f35151216429e8593f3ef35396c/CONTRIBUTING.md#enumerating-subdomains) for instructions on finding them.

Also, the `ruleset` `name` should be `XBRL.org`.

**Comment by jeremyn** [comment]
These return `401` for both `https` and `http`. Either add a `test` for them that
doesn't return a `401`, or remove their `target` and mark them at the top as `No working
URL known`:
  
- [ ] https://cn.xbrl.org
- [ ] https://eu.xbrl.org
- [ ] https://fr.xbrl.org
- [ ] https://kr.xbrl.org
- [ ] https://lu.xbrl.org
- [ ] https://sa.xbrl.org
- [ ] https://svn.xbrl.org
 
Also:
- [ ] Add a `target` for https://conference.xbrl.org and remove it from the top comment
- [ ] Change https://www2.xbrl.org from `(h)` to `(m)`

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
