### PR TITLE
Create beeg.xml

### PR DESCRIPTION
**Pull request by IDKwhattoputhere**
NSFW
One part of the fix for https://github.com/EFForg/https-everywhere/issues/5055.

### CODE REVIEW

**Comment by J0WI** [comment]
It seems that this site has no content?

**Comment by IDKwhattoputhere** [comment]
Plenty of content here. **NSFW** screenshots:
Startpage: https://cloud.githubusercontent.com/assets/16030872/17083462/932db6f8-51a1-11e6-9ab0-66b44f89159f.jpg
When clicking on a thumbnail: https://cloud.githubusercontent.com/assets/16030872/17083461/93156968-51a1-11e6-98f3-d882d7cb5873.jpg
HTTP and HTTPS version looks exactly the same too.

**Comment by jeremyn** [comment]
Thanks for the ruleset. Please:

- [ ] Add targets for https://static.beeg.com , https://a2.beeg.com , https://api.beeg.com , https://api2.beeg.com , and https://img.beeg.com . You can see most of these by looking at `Developer tools > Network` when loading https://beeg.com , though I guessed `api` from `api2`.
- [ ] Note https://upload.beeg.com as broken in a top comment

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
