### PR TITLE
Update Malwarebytes ruleset

### PR DESCRIPTION
**Pull request by wesdawg**
* Re-enable Malwarebytes.xml
* ~~Merge and delete Malwarebytes.com.xml~~

### CODE REVIEW

**Comment by J0WI** [comment]
I prefer to keep them in separate files.

**Comment by wesdawg** [comment]
@J0WI Why ? They're the same organisation, the `.org` ones are just the older domains.

**Comment by J0WI** [comment]
Huge rulesets are more difficult to maintain and `com` and `org` have not the same subdomains.
We use comments to link related rulesets, see e.g. the Amazon rulesets for an example.

**Comment by wesdawg** [comment]
Fair enough.
Should I create a new PR for re-enabling Malwarebytes.xml or can I rewrite this branch ?

**Comment by J0WI** [comment]
You can use this branch.

**Pull request merged**
