### PR TITLE
[Nemzeti Adó- és Vámhivatal] Add ruleset

### PR DESCRIPTION
**Pull request by TK-999**
Website of the National Tax and Customs Administration of Hungary

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your contribution. Please:

Add `target`s:
- [ ] https://abpe.nav.gov.hu
- [ ] https://adatbazisok.nav.gov.hu
- [ ] https://kkk.nav.gov.hu
- [ ] https://hirlevel.nav.gov.hu
- [ ] https://secure.nav.gov.hu

Also:
- [ ] Sort the targets. They should be alphabetical starting from the top-level domain at the right, reading left, with `^` and `www` at the top. So in this case it should be `nav.gov.hu`, then `www.nav.gov.hu`, then the rest in alphabetical order.
- [ ] Delete [this `cert` comment](https://github.com/TK-999/https-everywhere/blob/ff57bbf3710619a47cfc71dfcd39195026df69ee/src/chrome/content/rules/NAV.xml#L2).
- [ ] Instead of [this `Nonfunctional subdomains:` heading](https://github.com/TK-999/https-everywhere/blob/ff57bbf3710619a47cfc71dfcd39195026df69ee/src/chrome/content/rules/NAV.xml#L3), write the specific problem, which here is `Different HTTP/HTTPS content:`.

Finally, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means we rewrite your commits in your name. Are you okay with that for this pull request and any other pull requests you submit to us?

**Comment by jeremyn** [comment]
@TK-999 Are you still interested in working on this?

**Comment by jeremyn** [comment]
@TK-999 I've pushed an update to your branch making the changes in the checklist in https://github.com/EFForg/https-everywhere/pull/6888#issuecomment-251683504 and also some others. Do the changes look okay to you?

**Comment by jeremyn** [comment]
@TK-999 Can you please review the changes I made?

**Comment by jeremyn** [comment]
Hi @TK-999, can you please review the changes? It should be quick to do. Otherwise I'm going to close this pull request. Thanks.

**Comment by TK-999** [comment]
@jeremyn Sorry, the previous notification seems to have disappeared among my other notifs so I didn't see that one.

Changes look great, thanks for taking the time for implementing them, and sorry about the delay!

**Comment by jeremyn** [comment]
That's fine @TK-999, thanks for letting me know.

@gloomy-ghost @J0WI Can one of you review this please? Please use regular merge instead of squash-and-merge because there are multiple contributors (me and @TK-999).

**Pull request merged**
