### PR TITLE
Update kantonalbanken.xml

### PR DESCRIPTION
**Pull request by J0WI**
false positive, works in all major browsers (with extra download).

### CODE REVIEW

**Comment by jsha** [comment]
You're correct about the false positive, thanks for catching and fixing that.

This will fail the ruleset coverage test, can you add some test URLs and/or update to match the latest style guide (which will usually add sufficient coverage)?

You can use utils/test-generator.py to assist in writing test URLs.

**Comment by J0WI** [comment]
@jsha
test-generator.py returns ImportError: No module named exrex

**Comment by jsha** [comment]
You need to pip install exrex.

**Comment by J0WI** [comment]
Sadly, the script is nor very helpful in this case. I need much more test urls -.-

**Comment by J0WI** [comment]
fixed important ruleset, please merge soon

**Pull request merged**
