### PR TITLE
[0bin.net] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
BTW the server is vulnerable to the [Logjam attack](https://weakdh.org/).

https://www.ssllabs.com/ssltest/analyze.html?d=0bin.net

@sametmax

### CODE REVIEW

**Comment by J0WI** [comment]
Could you add a comment for mismatched www?

**Comment by rugk** [comment]
Any news?

**Comment by J0WI** [comment]
Could you also redirect www to ^?

**Comment by rugk** [comment]
Done.

**Comment by J0WI** [comment]
You missed the target host.

**Comment by rugk** [comment]
Done.

**Comment by J0WI** [comment]
There was something wrong with the test server. Let me reopen.

**Pull request merged**
