### PR TITLE
[unitn.it] Ruleset for University of Tronto and their popular BOINC project

### PR DESCRIPTION
**Pull request by aladar42**
Ruleset for http://www.unitn.it/ and their BOINC project TN-Grid at http://gene.disi.unitn.it/test/

### CODE REVIEW

**Comment by jeremyn** [comment]
@aladar42 Thanks for your pull request. We don't really like to use wildcards. There are a lot of subdomains for `unitn.it`, so if you don't want to add them all individually, you can use `(partial)` in the `ruleset` `name` and only cover the ones you want. See pull request https://github.com/EFForg/https-everywhere/pull/9729 for an example of a similar situation.

After you do this, I or another maintainer can take a look at what you have more closely.

**Comment by aladar42** [comment]
I'm goign to take a look at it. Can't guarantee I'll do it all according to standards, though.

**Comment by aladar42** [comment]
Any updates?

**Comment by jeremyn** [comment]
Please rebase your specific changes additions onto master, instead of including what appears to be a merge.

**Comment by jeremyn** [comment]
In other words, the "Files changed" tab above should show one file, not the current 883.

**Comment by aladar42** [comment]
Sorry, I'm still pretty new to Git. Did I do it correctly now?

**Comment by jeremyn** [comment]
The git situation looks okay now, thanks.

- [ ] Please rewrite your pull request like this:
```xml
<!--
	Invalid certificate:
		unitn.it
		cimec.unitn.it
		economia.unitn.it

-->
<ruleset name="Unitn.it (partial)">
	<target host="unitn.it" />
	<target host="www.unitn.it" />
	<target host="alumni.unitn.it" />
	<target host="centro3a.unitn.it" />
	<target host="www.centro3a.unitn.it" />
	<target host="cimec.unitn.it" />
	<target host="www.cimec.unitn.it" />
	<target host="gene.disi.unitn.it" />
	<target host="economia.unitn.it" />
	<target host="www.economia.unitn.it" />
	<target host="international.unitn.it" />
	<target host="knowtransfer.unitn.it" />
	<target host="phd-researchfellow.unitn.it" />
	<target host="pressroom.unitn.it" />
	<target host="unitrentosport.unitn.it" />
	<target host="webapps.unitn.it" />
	<target host="webmagazine.unitn.it" />

	<rule from="^http://(cimec\.|economia\.)?unitn\.it/" to="https://www.$1unitn.it/" />
	<rule from="^http:" to="https:" />
</ruleset>
```

This makes various improvements. Please let me know if you have any questions.

I'm not sure what  you are asking in your question about proper pull requests, but you might like to look over our [CONTRIBUTING.md](https://github.com/EFForg/https-everywhere/blob/d6967f2dfe659f35151216429e8593f3ef35396c/CONTRIBUTING.md).

**Comment by aladar42** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
