### PR TITLE
[Azet.sk] Removed unnecessary rules

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for the cleanup!
Sadly, this ruleset is not up to date. Could you add the following subdomains and comments if they are broken?

Works:
link.azet.sk
dobruchut.azet.sk

Refused:
azet.sk
sport.aktuality.sk
kalendar.azet.sk
adam.azet.sk

Mismatch:
mobilmania.azet.sk

Redirect:
www.azet.sk
casprezeny.azet.sk

404:
pomoc.azet.sk
pocasie.aktuality.sk

Mixed Content:
dobruchut.azet.sk
slovnik.azet.sk
onas.azet.sk
tivi.cas.sk

**Comment by Roman3349** [comment]
Added comments

**Comment by J0WI** [comment]
Sorry `dobruchut.azet.sk` was listed twice and `tivi.cas.sk` belongs to another host.
Please also use tabs instead of spaces as our style guide recommends.

Lgtm then.

**Comment by Roman3349** [comment]
Fixed

**Pull request merged**
