### PR TITLE
Added liginc.co.jp

### PR DESCRIPTION
**Pull request by luixxiul**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset!

`creative.liginc.co.jp` is broken even if I disable mixed content protection.

**Comment by luixxiul** [comment]
Thanks for reviewing.
````
http://creative.liginc.co.jp/wp-content/themes/ligworks/fonts/ligiconfont.woff?h7yjwt' from origin 'http://creative.liginc.co.jp' has been blocked by CORS policy
````
So I removed it.

**Comment by jeremyn** [comment]
The domain in the comment should be `creative`, not `creatives`.

**Comment by luixxiul** [comment]
Updated.

**Pull request merged**
