### PR TITLE
Remove ift.tt from Bit.ly vanity domain ruleset

### PR DESCRIPTION
**Pull request by kevinebaugh**
Ahead of a more permanent fix for #1309, this should fix the issues affecting ift.tt URLs.

### CODE REVIEW

**Comment by jsha** [comment]
Hi Kevin,

Thanks for spotting and fixing this bug. Could you instead submit a patch that disables the whole ruleset until we get a chance to add enough test URLs to bring this ruleset up to our current testing standard?

Thanks,
Jacob

**Comment by kevinebaugh** [comment]
@jsha I'm in a bit over my head, but I'd be happy to help. Any chance you could point me in the direction of another pull request that disables a ruleset?

Cc'ing @jehiah to see if someone on the bit.ly team could take a look.

**Comment by jsha** [comment]
Hi @kevinebaugh,

Sorry, I should have added more context! Here's an example you can follow: https://github.com/EFForg/https-everywhere/pull/1230/files

**Comment by kevinebaugh** [comment]
Thanks!

**Pull request closed without merging**
