### PR TITLE
[Kontalk] Add translate subdomain

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by J0WI** [comment]
Mismatch on `beta.kontalk.net`

**Comment by rugk** [comment]
Oh, indeed. @daniele-athome Wanna fix this?

**Comment by daniele-athome** [comment]
Port 443 for beta.kontalk.net will be handled by the XMPP server, although I still need to configure it. For now I've fixed it with configuring just the certificate so browsers are OK.

**Comment by J0WI** [comment]
That should be fine for our tests., let me rerun them.
btw @daniele-athome you may be interested in [preloaded HSTS](https://hstspreload.appspot.com/), that's exactly what HTTPS Everywhere does, but on a servers side.

**Comment by daniele-athome** [comment]
Thanks, I'll look into it.

**Comment by rugk** [comment]
Another description of preloading: https://scotthelme.co.uk/hsts-preloading/

**Pull request merged**
