### PR TITLE
Update Microsoft.xml

### PR DESCRIPTION
**Pull request by cschanaj**
Add 'www.catalog.update.microsoft.com'.

KB4012598 Security updates (Fix WannaCry, https://www.catalog.update.microsoft.com/Search.aspx?q=KB4012598)

See https://technet.microsoft.com/en-us/library/security/ms17-010.aspx#KBArticle

### CODE REVIEW

**Comment by cschanaj** [comment]
This sub-domains really should have been redirecting to HTTPS by default.

**Comment by cschanaj** [comment]
Maybe we should have this merge before the next release #9851

**Comment by J0WI** [comment]
LGTM, but I would like to wait a bit to give Microsoft the chance to renew their expired certs.

**Comment by cschanaj** [comment]
Ok, thanks!!

**Pull request merged**
