### PR TITLE
Create duoshuo.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please list the rest of the subdomains, at least as many as you can find [here](https://www.google.com/search?q=site%3A*.duoshuo.com&ie=utf-8&oe=utf-8#q=site:*.duoshuo.com+-site:duozai.duoshuo.com+-site:dev.duoshuo.com+-site:official.duoshuo.com+-site:static.duoshuo.com+-site:www.duoshuo.com). As an example of how "bad" it can get listing a lot of subdomains, see [this comment](https://github.com/EFForg/https-everywhere/pull/5265#issuecomment-242941309).

**Comment by jeremyn** [comment]
Thanks. Please:

Remove as target and mark as `Mixed content` in a top comment:
- [ ] https://dev.duoshuo.com

Add target:
- [ ] https://cqbuswiki.duoshuo.com
- [ ] https://livesino.duoshuo.com
- [ ] https://puteulanus.duoshuo.com

**Comment by renyouguo** [comment]
@jeremyn Thank you very much for your patient.

**Comment by jeremyn** [comment]
I've updated the checklist through commit ff2a6f54e5a311033152747b4d2a716aae969bd8.

No problem, thanks to you too.

**Comment by jeremyn** [comment]
Thanks again, merged.

**Pull request merged**
