### PR TITLE
Update Ravenjs.com.xml

### PR DESCRIPTION
**Pull request by Giltyhub**

### CODE REVIEW

**Comment by injust** [comment]
Would be best to add a comment explaining that specific rule, too.

**Comment by Giltyhub** [comment]
@injust ok but it seems that it didn't fix it :( https://travis-ci.org/EFForg/https-everywhere/jobs/382079383

**Comment by injust** [comment]
Oops, can you try changing the rule to `<rule from="^http://cdn\.ravenjs\.com/$" to="https://cdn.ravenjs.com/" />`

**Comment by injust** [comment]
Okay, I don't know how to fix the validation error. The redirect rule seems to be working properly...

**Comment by J0WI** [comment]
You can just use an exclusion for `"^http://cdn\.ravenjs\.com/$"`.

**Pull request merged**
