### PR TITLE
add rule for Merkur.de

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by fuglede** [comment]
As far as I can see, this causes problems with video content; on https://www.merkur.de/multimedia/apple-keynote-wwdc-september-2016-iphone-7-zr-6685329.html there is a video missing towards the bottom of the page, due to http://www.snacktv.de/snacktag/snacktag.js being blocked (even though it is actually securable).

**Comment by numismatika** [comment]
SnackTV ruleset update will follow tomorrow.
Meanwhile i asked their customer support about the issue, hopefully it can be properly fixed on their site.

**Comment by jeremyn** [comment]
The embedded YouTube video under "**Update vom 8. September 2016:**" in https://www.merkur.de/multimedia/apple-keynote-wwdc-september-2016-iphone-7-zr-6685329.html, the URL @fuglede gave, looks okay now. I don't see any other video.

@numismatika Did you hear back from their customer support?

**Comment by numismatika** [comment]
@jeremyn no i didn't. Websites rarely reply to such e-mails i guess.
If they do like the public tv and radio stations "it is work in progress, please wait".
We should check the Outbrain and SnackTV rules though to make sure they do not break

**Comment by jeremyn** [comment]
I'm not sure what you mean. Is there some problem you see that I don't know about?

**Comment by numismatika** [comment]
Not so far

> Did you hear back from their customer support?
No and it is brazen to expect them to

**Comment by jeremyn** [comment]
Do you agree that the video problem @fuglede reported is fixed?

**Comment by numismatika** [comment]
looks fine, mixed content warnings do not block the iphone video on the bottom

**Comment by jeremyn** [comment]
Sublist3r reports several more domains, can you add them somewhere please?

```
www.merkur.de
autoanzeigen.merkur.de
www.autoanzeigen.merkur.de
branchenbuch.merkur.de
epaper.merkur.de
epaperapp.merkur.de
epaperkiosk.merkur.de
immobilien.merkur.de
jobs.merkur.de
markt.merkur.de
www.markt.merkur.de
media.merkur.de
on.merkur.de
playground.merkur.de
promo.merkur.de
www.promo.merkur.de
trauer.merkur.de
www.trauer.merkur.de
veranstaltungen.merkur.de
webviewer.merkur.de
```

**Comment by jeremyn** [comment]
Please:

Note as `Different HTTP/HTTPS content`:
- [ ] https://www.promo.merkur.de
  
Note as `Invalid certificate`:
- [ ] https://branchenbuch.merkur.de
- [ ] https://epaper.merkur.de
- [ ] https://epaperkiosk.merkur.de
- [ ] https://media.merkur.de
- [ ] https://veranstaltungen.merkur.de
- [ ] https://webviewer.merkur.de
 
Note as `Mixed content`:
- [ ] https://autoanzeigen.merkur.de
 
Note as `Refused`:
- [ ] https://jobs.merkur.de
 
Note as `Secure connection failed`:
- [ ] https://immobilien.merkur.de
 
Note as `Time out`:
- [ ] https://epaperapp.merkur.de
 
Add target:
- [ ] http://merkur.de
- [ ] https://www.merkur.de
- [ ] https://druckhaustour.merkur.de
- [ ] https://markt.merkur.de
- [ ] https://on.merkur.de
- [ ] https://playground.merkur.de
- [ ] https://trauer.merkur.de
- [ ] https://promo.merkur.de (test http://promo.merkur.de/abo/epaper/)
- [ ] http://www.trauer.merkur.de (redirect to trauer)
 
Also:
- [ ] All the full domain to the items in the comment, for example `branchenbuch.merkur.de` instead of just `branchenbuch`

**Comment by numismatika** [comment]
@jeremyn on.merkmerkur.de is already covered in the bitly ruleset. No need to duplicate that.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/6525/commits/e3482d1ec2d8e008ece034ec1a559ea3ac70204e. Can you please double-check your results for https://media.merkur.de and https://jobs.merkur.de ?

**Comment by numismatika** [comment]
media.merkur.de has a cert mismatch , served cert is only valid for tz.addev.de
jobs not even offers a cert.
Nothing changed.

**Comment by jeremyn** [comment]
I can confirm the certificate problem with https://media.merkur.de and I've checked that in the list.

For https://jobs.merkur.de I get "Unable to connect"/"This site can’t be reached", which we label as `Refused`. This is different from `Secure connection failed`, which you have labeled it with.

**Comment by jeremyn** [comment]
@numismatika The only thing stopping me from merging this PR is that you should move https://jobs.merkur.de/ from `Secure connection failed` to a new `Refused` category in the top comment.

**Comment by jeremyn** [comment]
I merged this and created pull request https://github.com/EFForg/https-everywhere/pull/9914 to fix the top comment for https://jobs.merkur.de .

**Pull request merged**
