### PR TITLE
Add ekoodit.fi

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your contribution.

The tests are failing because the ruleset filename should end in `.xml`. Try renaming your new file to `Ekoodit.fi.xml`.

**Comment by theel0ja** [comment]
Whoops! I'm going to fix it.

**Comment by jeremyn** [comment]
Thanks. Please make the following changes:

- [ ] Following our [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), please change leading spaces to tabs.
- [ ] Remove the internal comment about `www.ekoodit.fi` and instead note it in a top comment as `Certificate mismatch`. [Here](https://github.com/jeremyn/https-everywhere/blob/245f2f8812d56a7c16d4982bf59b97252cfac0b1/src/chrome/content/rules/Juno.com.xml) is a example.
- [ ] Change the ruleset name to `Ekoodit.fi.xml` instead of `ekoodit.fi.xml`, because that is more usual.

Also, https://ekoodit.fi causes active mixed content blocking that breaks jQuery. It looks like the broken functionality is slide-down functionality on mobile devices, or if your desktop browser has a small width, when you click the "Hae E-koodeilla" or "Tai nimillä" search fields. According to Google Translate, the slide-down text provides search instructions. I can't get the slide-down to happen on an Android device. This is minor enough that we can allow the ruleset, but I just want to point it out.

Finally, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which mean we rewrite your commits in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by theel0ja** [comment]
- Leading spaces are now tabs
- Removed internal comment

**Comment by theel0ja** [comment]
- Changed the name to `Ekoodit.fi.xml` instead of `ekoodit.fi.xml`

**Comment by theel0ja** [comment]
Also, notified ekoodit.fi owner on Twitter.
https://twitter.com/theel0ja/status/786830176881639424

**Comment by jeremyn** [comment]
This looks fine, thanks. Please answer the question at the end of https://github.com/EFForg/https-everywhere/pull/7300#issuecomment-252514669, and then I can merge this.

**Comment by theel0ja** [comment]
Ok, yes...
So it's like this?:
Squash-and-merge

**Comment by jeremyn** [comment]
That's right. There's a discussion about it in https://github.com/EFForg/https-everywhere/issues/5838 . I personally like to confirm with contributors that this is okay first, because technically squash and merge says you wrote `F`, when you didn't.

So, is that all right with you, for this and any other pull requests you submit to us?

**Comment by theel0ja** [comment]
Yes.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
