### PR TITLE
Create Enaza.ru.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by ekaris** [comment]
@fuglede can you pull?

**Comment by ekaris** [comment]
Can you pull @J0WI ?

**Comment by J0WI** [comment]
There is a bunch of subdomains:

WFM:
enter.enaza.ru
oks.enaza.ru
uks.enaza.ru
files2.enaza.ru
disel.enaza.ru
tvingo.enaza.ru
team.enaza.ru
jira.enaza.ru
redmine.enaza.ru
static.enaza.ru
books.enaza.ru
netbynet.enaza.ru
pntl.enaza.ru
dev.enaza.ru

Mismatch:
demo.activeboy.enaza.ru
rt.enaza.ru
ufanet.enaza.ru

Redirect:
activeboy.enaza.ru
up.enaza.ru

Mixed content:
alfa.enaza.ru
eset.enaza.ru
wimc.alarchenkov.dev.enaza.ru

**Comment by ekaris** [comment]
Good?

**Comment by J0WI** [comment]
Just reopen to run travis again.

**Comment by fuglede** [comment]
@J0WI: Just in case you are not already aware, I believe you have access to rerun tests in Travis directly (in case you would rather do that than go through the close/open trick).

**Pull request merged**
