### PR TITLE
Remove malformed regex from Globat.com.xml

### PR DESCRIPTION
**Pull request by cschanaj**
there was intention to protect HTTP on port 443 (?) but the regex is malformed.  #17965

### CODE REVIEW

**Comment by pipboy96** [comment]
I see it has a wildcard DNS (any subdomain returns `NOERROR`), but only some domains have `A` or `AAAA` record. I'm not sure how to handle that.

**Comment by cschanaj** [comment]
It doesn't seem to me that global.com has a wildcard dns, see https://dns.google.com/query?name=*.globat.com. In particular, https://https-everywhere.globat.com does not resolve.

**Comment by pipboy96** [comment]
@cschanaj

```
$ dig https-everywhere.globat.com

; <<>> DiG 9.10.6 <<>> https-everywhere.globat.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46721
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;https-everywhere.globat.com.	IN	A

;; AUTHORITY SECTION:
globat.com.		300	IN	SOA	ns1.globat.com. root.ns1.globat.com. 118 3600 600 86400 360
```

It's `NOERROR` but there are no `A` records.

**Comment by cschanaj** [comment]
Since this ruleset contains malformed regex which redirect users to a wrong URL, I think it worth merging this before the next release (with or without coverage improvement). 

cc @J0WI @pipboy96 @zoracon @Hainish

**Comment by Hainish** [comment]
Sounds good to me, merging.

**Comment by cschanaj** [comment]
thanks!

**Pull request merged**
