### PR TITLE
Use different default ciphers when using NSS

### PR DESCRIPTION
**Pull request by jeremyn**
This pull request resolves issue #5628.

### CODE REVIEW

**Comment by Hainish** [comment]
Thanks for this @jeremyn.  For the future, just @ me when you want a PR reviewed.

**Comment by Hainish** [comment]
This lgtm.  I'll note that when testing it on debian vs fedora, I get vastly different speeds:

Debian:
```
Testing test URLs in all changed rulesets.
INFO Finished comparing http://www.eff.org/ -> https://www.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://action.eff.org/ -> https://action.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://supporters.eff.org/ -> https://supporters.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://eff.org/ -> https://eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://defendinnovation.org/ -> https://defendinnovation.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.defendinnovation.org/ -> https://www.defendinnovation.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://globalchokepoints.org/ -> https://globalchokepoints.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.globalchokepoints.org/ -> https://www.globalchokepoints.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://httpsnow.org/ -> https://httpsnow.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.httpsnow.org/ -> https://www.httpsnow.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://ripmixmake.org/ -> https://ripmixmake.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.ripmixmake.org/ -> https://www.ripmixmake.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished in 7.46 seconds. Loaded rulesets: 1, URL pairs: 12.
Test URL test succeeded.
```

Fedora:
```
Testing test URLs in all changed rulesets.
INFO Finished comparing http://www.eff.org/ -> https://www.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://action.eff.org/ -> https://action.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://supporters.eff.org/ -> https://supporters.eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://eff.org/ -> https://eff.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://defendinnovation.org/ -> https://defendinnovation.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.defendinnovation.org/ -> https://www.defendinnovation.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://globalchokepoints.org/ -> https://globalchokepoints.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.globalchokepoints.org/ -> https://www.globalchokepoints.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://httpsnow.org/ -> https://httpsnow.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.httpsnow.org/ -> https://www.httpsnow.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://ripmixmake.org/ -> https://ripmixmake.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished comparing http://www.ripmixmake.org/ -> https://www.ripmixmake.org/. Rulefile: src/chrome/content/rules/EFF.xml.
INFO Finished in 81.10 seconds. Loaded rulesets: 1, URL pairs: 12.
```

I wonder why that would be?

**Comment by jeremyn** [comment]
I found and noted [here](https://github.com/EFForg/https-everywhere/pull/5584#issuecomment-239246808) a significant time difference between Fedora and Ubuntu because I had different configurations. In that case the important difference seemed to be using a Vagrant shared directory (Fedora, slow) vs. running entirely within the VM (Ubuntu, fast). When I made the configurations more similar, the times became more similar.

So, check that your configurations are roughly the same. That said, I get the following run times using `fetch-test.sh` with `EFF.xml` in Vagrant VMs with unshared directories and 4GB RAM:

```
Ubuntu 14.04, Fedora 24
34.11s, 48.72s
31.13s, 53.36s
30.27s, 50.59s
```

Fedora is consistently slower, but not by the huge difference you saw.

The following test script just runs pycurl and is based on the first example in the pycurl quick start guide [here](http://pycurl.io/docs/latest/quickstart.html).

```python
import pycurl
import re
import time
from StringIO import StringIO

_DEFAULT_CIPHERLIST_NSS = "rsa_3des_sha,rsa_des_sha,rsa_null_md5,rsa_null_sha,rsa_rc2_40_md5,rsa_rc4_128_md5,rsa_rc4_128_sha,rsa_rc4_40_md5,fips_des_sha,fips_3des_sha,rsa_des_56_sha,rsa_rc4_56_sha,rsa_aes_128_sha,rsa_aes_256_sha,rsa_aes_128_gcm_sha_256,dhe_rsa_aes_128_gcm_sha_256,ecdh_ecdsa_null_sha,ecdh_ecdsa_rc4_128_sha,ecdh_ecdsa_3des_sha,ecdh_ecdsa_aes_128_sha,ecdh_ecdsa_aes_256_sha,ecdhe_ecdsa_null_sha,ecdhe_ecdsa_rc4_128_sha,ecdhe_ecdsa_3des_sha,ecdhe_ecdsa_aes_128_sha,ecdhe_ecdsa_aes_256_sha,ecdh_rsa_null_sha,ecdh_rsa_128_sha,ecdh_rsa_3des_sha,ecdh_rsa_aes_128_sha,ecdh_rsa_aes_256_sha,echde_rsa_null,ecdhe_rsa_rc4_128_sha,ecdhe_rsa_3des_sha,ecdhe_rsa_aes_128_sha,ecdhe_rsa_aes_256_sha,ecdhe_ecdsa_aes_128_gcm_sha_256,ecdhe_rsa_aes_128_gcm_sha_256"

_DEFAULT_CIPHERLIST_OTHER = "RC4-MD5:RC4-SHA:DES-CBC3-SHA:AES128-SHA:AES256-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256"

cipher_list = _DEFAULT_CIPHERLIST_NSS if re.search('NSS/\d+\.\d+', pycurl.version) else _DEFAULT_CIPHERLIST_OTHER

start = time.time()
for _ in range(25):
    buffer = StringIO()
    c = pycurl.Curl()
    c.setopt(c.URL, 'https://www.eff.org/')
    c.setopt(c.WRITEDATA, buffer)
    c.setopt(c.SSL_CIPHER_LIST, cipher_list)
    c.perform()
    c.close()
end = time.time()
print("Duration: %.2f" % (end-start))
```

What's strange is that here, Ubuntu actually takes longer to run:

```
Ubuntu 14.04, Fedora 24
16.67s, 9.69s
```

I have no explanation.

**Comment by jeremyn** [comment]
Also it looks like I added inconsistent whitespace in bb63838. I can fix just that if you want, or you can. Should I make another PR?

Actually there's a lot of whitespace and other styling issues in that Python file and others. Would you accept one or more large PRs to clean things up?

**Comment by Hainish** [comment]
I didn't see that - yes, thanks, just create a new PR.

I've been meaning to autopep8 things for a while now, I can do that.

**Pull request merged**
