### PR TITLE
Update LLVM.org.xml

### PR DESCRIPTION
**Pull request by salty-horse**
Adding apt.llvm.org - a landing page that has repository URLs, and gpg key fingerprints

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Can you address the errors from ci?
```
ERROR src/chrome/content/rules/LLVM.org.xml: Fetch error: http://lnt.llvm.org/ => https://lnt.llvm.org/: (60, 'SSL certificate problem: certificate has expired')
ERROR src/chrome/content/rules/LLVM.org.xml: Fetch error: http://new-www.llvm.org/ => https://new-www.llvm.org/: (51, "SSL: no alternative certificate subject name matches target host name 'new-www.llvm.org'")
```

**Comment by salty-horse** [comment]
I've opened a [bug in LLVM](https://bugs.llvm.org/show_bug.cgi?id=35104) about the domains.
In the meantime, should they be commented out in the rules file?

**Comment by gloomy-ghost** [comment]
It depends on whether the LLVM project team can fix it quickly, since we have a long backlog and another PR that re-actives the targets may get delayed. I am fine with both approaches, you can just choose the one that you perfer.

**Comment by salty-horse** [comment]
I deactivated lnt and new-www.

**Comment by gloomy-ghost** [comment]
Thanks!

**Pull request merged**
