### PR TITLE
mobile01.com supports https all site now

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

- [ ] Remove the top comment.

Add `target`s:
- [ ] mobile01.com
- [ ] attach.mobile01.com
- [ ] attach2.mobile01.com
- [ ] attach4.mobile01.com
- [ ] download.mobile01.com
- [ ] m.mobile01.com
- [ ] static.mobile01.com

**Comment by PeterDaveHello** [comment]
Updated, thanks!

**Comment by gloomy-ghost** [comment]
There are some style issues, we are ready to go once these are fixed:

- [ ] Move www.mobile01.com directly under mobile01.com
- [ ] Delete the `test` as every target creates an implicit test by itself.

**Comment by PeterDaveHello** [comment]
@gloomy-ghost thanks for your review, hope it's good to go now :)

**Pull request merged**
