### PR TITLE
[SHOUTca.st] new ruleset

### PR DESCRIPTION
**Pull request by meyskens**
A new ruleset for SHOUTca.st and Radioca.st (the second one is where clients are hosted)

### CODE REVIEW

**Comment by J0WI** [comment]
I found mixed content on many subdomains from Google Fonts, but thats trivial I think.
Even worse is, that some subdomains are serving a wrong cert (e.g. https://metalrad.radioca.st/).

You should double check all subdomains and add exclusions or remove the wildcard.

**Comment by leoetlino** [comment]
@meyskens yes, there is mixed content for the old Icecast server frontends:

>Mixed Content: The page at 'https://metalrad.radioca.st/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600'. This request has been blocked; the content must be served over HTTPS.

The request is completely blocked. *.shoutca.st should be okay though.

**Comment by jeremyn** [comment]
@meyskens Thanks for the PR. It needs some changes before we can accept it. Are you interested in working on this more?

**Comment by jeremyn** [comment]
I'm closing this due to no response to https://github.com/EFForg/https-everywhere/pull/3753#issuecomment-252068334 .

**Pull request closed without merging**
