### PR TITLE
Add a script to trivialize a special form of securecookies

### PR DESCRIPTION
**Pull request by cschanaj**
supersedes #16539 close #16536 close #16537 close #16538 related #16029

### CODE REVIEW

**Comment by J0WI** [comment]
The changes LGTM.
@Hainish would you like to review the script?

**Comment by cschanaj** [comment]
I have found another pattern which can be trivialized in a similar way, namely

https://github.com/EFForg/https-everywhere/blob/bcbfbed60c72afd7d716807924a41c3ce3962178/src/chrome/content/rules/AboutMe.xml#L11

affecting 450+ rulesets. So it will be great if the script got reviewed before I proceed further trivialization (in another PR).

P.S. for a list of affected rulesets `$ git grep -lF '^(?:.*\.)?'`

**Comment by cschanaj** [comment]
@J0WI @Hainish Sorry that I have to push e55f367 to resolve the merge conflicts.

**Comment by cschanaj** [comment]
@Hainish would you be interested in looking at the script in this PR as well?

**Comment by Hainish** [comment]
Looking good - thank you!

**Pull request merged**
