### PR TITLE
remove Auditorius.ru.xml

### PR DESCRIPTION
**Pull request by J0WI**
still no HTTPS support

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Remove the reference from [`Audtd.com.xml`](https://github.com/EFForg/https-everywhere/blob/10586fb78d4c0fa9a9138f0070800545ae7949fa/src/chrome/content/rules/Audtd.com.xml)

**Comment by J0WI** [comment]
Done

**Comment by jeremyn** [comment]
I found a URL for `track.audtd.com` through Google and when I visited it with this ruleset active, it redirected forever. I've haven't been able to reproduce the problem but now I don't trust that these domains will work consistently with HTTPS. Also most of the other subdomains for `audtd.com` from `Sublist3r` look internal or at least non-user-facing. Maybe we should just delete `Audtd.com.xml` entirely. What do you think?

**Comment by J0WI** [comment]
I have no idea what `audtd.com` is for, so I'm very happy with just removing it.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
