### PR TITLE
 [FranceTVInfo.fr] Add targets 

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
I don't understand why the tests are failing here :(

**Comment by jeremyn** [comment]
You're closing the `target` tag incorrectly in https://github.com/Bisaloo/https-everywhere/blob/176944698223736ce9ba4291788af16b3432f748/src/chrome/content/rules/francetvinfo.fr.xml#L34.

**Comment by Bisaloo** [comment]
Good catch! Thank you @jeremyn.

**Comment by jeremyn** [comment]
- [ ] Mark https://m.geopolis.francetvinfo.fr as `Different HTTP/HTTPS content` and remove from `No working URL known`
- [ ] Add `target` for https://sport.francetvinfo.fr
- [ ] Remove `static.francetv.fr` entirely, because `francetv.fr` is a different domain from `francetvinfo.fr`. (I recognize that it was present in the original version of the ruleset.)
- [ ] Change the `ruleset` `name` to `FranceTVInfo.fr`
- [ ] Change the filename to `FranceTVInfo.fr.xml`

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/13900/commits/82142d3e2179cc6cc3214aba1967168ac73f2133. (You have a lower-case "i" in "info" in the `ruleset` `name`.)

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
