### PR TITLE
Update TieTuKu.xml

### PR DESCRIPTION
**Pull request by bob0627**

### CODE REVIEW

**Comment by ivysrono** [comment]
原规则第一条就是 p1.bpimg.com 重复了
把 p1.bqimg.com 移到他下面去。
把 #8995 #8996 #8997 都关闭了吧。

**Comment by ivysrono** [comment]
#9498

**Comment by jeremyn** [comment]
@bob0627 Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
The two `target`s added here, https://p1.bpimg.com and https://p1.bqimg.com , fail HTTPS, so this pull request is currently invalid. I'm closing it.

**Pull request closed without merging**
