### PR TITLE
Removed target host www.rzuser.uni-heidelberg.de because it breaks so…

### PR DESCRIPTION
**Pull request by KommX**
…me sites, e.g. http://www.rzuser.uni-heidelberg.de/~hu020/EWTS/index.html

### CODE REVIEW

**Comment by fuglede** [comment]
Thanks for the report. Which other sites are broken? (Is there a pattern to it that could be excluded?)

**Comment by KommX** [comment]
I don't know if other sites are affected but I guess so. This server hosts many different sites from university people.
Normally, you should get a list of sites at http://www.rzuser.uni-heidelberg.de/list/rzuser.html but that doesn't work obviously.

**Comment by fuglede** [comment]
Yeah, looks like a problem with http://whitepages.urz.uni-heidelberg.de -- unfortunate. I also agree that excluding the domain is probably the safest bet. In any case, do you want to add a comment on the removal in the ruleset file? That makes it a bit easier to navigate for future ruleset editors.

**Comment by KommX** [comment]
Done.

**Comment by fuglede** [comment]
Thanks.

**Pull request merged**
