### PR TITLE
Revert "Update geetest.xml —— fix page broken"

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Reverts EFForg/https-everywhere#7123

The URL doesn't exist anymore and I can pass the official [test](http://www.geetest.com/contact#report) with api.geetest.com redirected.

### CODE REVIEW

**Comment by ivysrono** [comment]
No.
Test to login bbs.kafan.cn

**Comment by gloomy-ghost** [comment]
Hum, interesting.

I'll ask geetest next week

**Comment by ivysrono** [comment]
#7854

**Comment by gloomy-ghost** [comment]
I don't have any official updates from Geetest but it seems like they have fixed the issue.

**Comment by ivysrono** [comment]
api.geetest.com still break bbs.kafan.cn

**Comment by ivysrono** [comment]
#10821

**Pull request closed without merging**
