### PR TITLE
Report issue format bot code coverage

### PR DESCRIPTION
**Pull request by strugee**

### CODE REVIEW

**Comment by strugee** [comment]
Ref #14616

**Comment by strugee** [comment]
Merge conflicts fixed (I forgot to pull before I changed stuff).

**Comment by strugee** [comment]
Just to clarify what this does, this is what the end of `npm test` looks like now:

```
[...lots of Perjury output...]

When we require the module and we pass it a new ruleset with a domain
  it returns an array: OK
  the array has no problems: OK
When we require the module and we pass it a ruleset issue with a domain
  it returns an array: OK
  the array has no problems: OK

SUMMARY
        Broken:         0
        Successes:      137
        Failures:       0
--------------|----------|----------|----------|----------|----------------|
File          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------|----------|----------|----------|----------|----------------|
All files     |    85.71 |    66.67 |    88.89 |    85.71 |                |
 issueedit.js |    83.33 |    57.89 |       75 |    84.78 |... 29,52,79,81 |
 labeler.js   |    61.54 |    28.57 |       75 |     62.5 |... 23,24,35,37 |
 newissue.js  |    90.91 |    81.82 |      100 |    90.63 |       17,18,41 |
 parse.js     |      100 |      100 |      100 |      100 |                |
 validate.js  |      100 |      100 |      100 |      100 |                |
--------------|----------|----------|----------|----------|----------------|
```

With some nice coloring too (to show low/medium/high numbers) that doesn't show up on GitHub :-)

**Comment by Hainish** [comment]
@strugee yes, that would be helpful.  Thanks.

**Comment by strugee** [comment]
Great. I'll continue to do so then. Thanks for merging!

**Pull request merged**
