### PR TITLE
Create sandros.hu.xml

### PR DESCRIPTION
**Pull request by sandrosdj**
Personal sites and server control panels used by clients.

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

Note as `Invalid Certificate`:
- [ ] bingle.sandros.hu
- [ ] cd.sandros.hu
- [ ] coding.sandros.hu
- [ ] www.filtr.sandros.hu
- [ ] api.filtr.sandros.hu
- [ ] 567.fr.sandros.hu
- [ ] music.sandros.hu
- [ ] rpi.sandros.hu
- [ ] vs.sandros.hu

Remove target and note as `MCB`:
- [ ] blog.sandros.hu
- [ ] www.blog.sandros.hu

Note as `No working URL known`:
- [ ] download.sandros.hu
- [ ] files.sandros.hu

Add targets:
- [ ] bullshit.sandros.hu
- [ ] dl.sandros.hu
- [ ] git.sandros.hu
- [ ] home.sandros.hu
- [ ] www.home.sandros.hu
- [ ] toolbox.sandros.hu
- [ ] vps.sandros.hu

Also:
- [ ] Move `www` straightly under `^` according to the ruleset style guide.
- [ ] Either delete the general securecookie or include a regex listing each of the targets.

**Comment by jeremyn** [comment]
@sandrosdj Are you still interested in working on this?

**Comment by jeremyn** [comment]
@sandrosdj I haven't looked too closely at @gloomy-ghost 's suggestions but that should be your starting point. Also in this case we don't consider targets like `www` unnecessary, even though they redirect to `^`.

**Comment by pipboy96** [comment]
I think this PR should be closed:

- Last commit Dec 4, 2017
- Failed Travis test
- Author's account is inactive
- We generally don't accept PRs from website owners, they should use HSTS preloading instead.

**Comment by zoracon** [comment]
Closing due to no revisions made. Can reopen if interest for revision is indicated

**Pull request closed without merging**
