### PR TITLE
[Xdebug.org] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
@xdebug seems to support HTTPS now thanks to Let's Encrypt.

/cc @derickr

### CODE REVIEW

**Comment by J0WI** [comment]
Sadly the cert is not valid for the www prefix. Could you ad a redirect for it?
Please also add bugs.xdebug.org and a comment for the unsupported svn.xdebug.org

**Comment by derickr** [comment]
The www prefix should really not be used, and redirect to the non-www host. I'll see if I can fix that. I did add https://bugs.xdebug.org earlier this morning already, and I'll drop svn.xdebug.org from the DNS all together. I will likely also set up a redirect for the non-https stuff on bugs as well. Or were you really asking @rugk ?

**Comment by rugk** [comment]
[**@derickr**](https://github.com/derickr) commented on [25. Jan. 2016, 00:09 MEZ](https://github.com/EFForg/https-everywhere/pull/3988#issuecomment-174351020 "2016-01-24T23:09:38Z - Replied by Github Comment Enhancer"):
> Or were you really asking [@rugk](https://github.com/rugk) ?

Yes he was. I'll added the redirect. It's just to be sure no one gets a HTTPS error.
I also added your other subdomain. Are there any subdomains (with HTTPS support or not) left?

**Comment by derickr** [comment]
I've now set up all the directions myself, so that when you go to any of my hosted domains, you end up on https (except for svn.xdebug.org, which I am going to decommission).

**Comment by J0WI** [comment]
Thanks @rugk for updating the rules.

@derickr as long as the hosts are not HSTS preloaded I'll merge this. This will also secure our users on their initial connect to the host.

**Pull request merged**
