### PR TITLE
volumio.org

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Add target for https://www.volumio.org

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Thanks. Please re-add https://new.volumio.org as a target. Looks good otherwise.

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
