### PR TITLE
Improvements to Deviantart.xml

### PR DESCRIPTION
**Pull request by BoffinbraiN**
2nd rule would previously fail for deviantart.net because it changed the TLD to into deviantart.com. Added 2nd capture group like the first rule.

### CODE REVIEW

**Comment by 2d1** [comment]
The comment above the rule you changed is still true for at least (www.)?deviantart.net.

Please either create a third rule for names for which the comment is still true, or add the names that you've observed as being broken to the first rule.

**Comment by BoffinbraiN** [comment]
Good spot. deviantart.net now has its own separate certificate, so I'm going to condense both rules into a single rule and test for a few days before proposing it.

**Comment by semenko** [comment]
Looks like this PR has conflicts -- and it hasn't been updated in a while. I'm going to close this for now, but if you'd like it merged, feel free to re-open. Thanks! :)

**Comment by BoffinbraiN** [comment]
I'm not exactly sure what's going on with this thread any more. My original changes still work fine on my local modified version of the extension. If I were to make another PR, where should I fork from?

**Comment by semenko** [comment]
Cool -- I think another user edited Deviantart in the meantime, which broke your PR:
https://github.com/EFForg/https-everywhere/commit/d915ffc02ffa0f66e4bd4379b3bd4c23073c0d40

So you'd need to rebase/pull from master, to make sure you have those changes.

**Pull request closed without merging**
