### PR TITLE
Schibsted.no

### PR DESCRIPTION
**Pull request by numismatika**
i added a couple of subdomains found on norwegian news-sites and those urls from the server alternative names that resolve to a valid ip.
Some internal or old hostnames that do not resolve here still are also found in the cert that matches most domains here.

### CODE REVIEW

**Comment by J0WI** [comment]
retest

**Comment by J0WI** [comment]
Can you document how all this different hosts are related? You may also find a more generic name for the ruleset.

**Comment by numismatika** [comment]
For now SAN they share the same cert, my norwegian is non existent so my guess is that it is the common service provider for these newspapers or a holding company.

**Comment by J0WI** [comment]
Such holdings can be quite large, I would separate the files than and link them in comments.

**Comment by numismatika** [comment]
I would have done a merge now and refinement later.
Breaking it into seperate files would require more time and a norwegian user to help.

**Comment by numismatika** [comment]
For me mail.schibsted.no offers a valid outlook web interface.
I therefore suggest to overwrite the changes 2weeks ago that @Hainish  did

**Comment by J0WI** [comment]
This branch has conflicts that must be resolved

**Comment by J0WI** [comment]
Some hosts are already listed in other rulesets.

**Comment by numismatika** [comment]
Probably right @J0WI , untangling the web of norwegian newssites takes a while.

**Comment by jeremyn** [comment]
`Schibsted.no.xml` should be split up into rulesets organized around specific domains, as @J0WI (partially) said in https://github.com/EFForg/https-everywhere/pull/4652#issuecomment-235309309. Also, just spot checking, some of the targets are bad and should be reviewed by @numismatika before a maintainer looks more closely.

The targets should be restricted to just public-user-facing domains like `www`. We don't need to cover really technical domains like `stoneboard.dev.vgnext.schibsted.io`.

I'm not personally committing to review this, but I think these are minimal requirements before any maintainer is likely to look more closely.

**Comment by numismatika** [comment]
I will split it by Domain.
Looks like wildcard dns is used as well by Schibsted so it needs some filtering indeed.

**Pull request closed without merging**
