### PR TITLE
[Openstreetmap.fr] Update and reactivate ruleset 

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by J0WI** [comment]
* The code style is not consistent, there are still some spaces.
* Why has this rule been added to the whitelist?

**Comment by J0WI** [comment]
Travis exposed some errors. For `nomino` you can try a static resource as test url.

**Comment by Bisaloo** [comment]
> Travis exposed some errors.

That's why I whitelisted. `nomino` and `polygons` both work fine for me.

**Comment by J0WI** [comment]
Their configuration is inconsistent:
https://www.ssllabs.com/ssltest/analyze.html?d=download.openstreetmap.fr
https://www.ssllabs.com/ssltest/analyze.html?d=polygons.openstreetmap.fr

**Comment by Bisaloo** [comment]
Good catch. Thank you!

**Comment by J0WI** [comment]
Okay, the workaround for `nomino` seems not to work.

**Comment by pipboy96** [comment]
Ruleset is already re-enabled. No updates since 2017. Feel free to reopen if you still want to work on this.

**Pull request closed without merging**
