### PR TITLE
Create 36Kr.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@Hainish Would you check it？

**Comment by Hainish** [comment]
Hey @renyouguo: be aware that @jeremyn is also available to check ruleset PRs

**Comment by renyouguo** [comment]
@Hainish Thanks.
By the way, what does the tags mean: top-1k / top-100k / top-1m ?

**Comment by Hainish** [comment]
@renyouguo that refers to this issue: https://github.com/EFForg/https-everywhere/issues/6424

**Pull request merged**
