### PR TITLE
Create TheMuslimahDiaries.com.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by koops76** [comment]
@I-have-50-open-PRs-to-HTTPS-EVERYWHERE Please do not change your name so often, it makes it difficult to track PRs opened by you.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@koops76 ok, sorry abt that!

**Comment by koops76** [comment]
@I-have-50-open-PRs-to-HTTPS-EVERYWHERE So many Muslim websites?

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@koops76 yeah, look at all those muslim websites ;) https://github.com/EFForg/https-everywhere/pulls?q=is%3Apr+author%3AI-have-50-open-PRs-to-HTTPS-EVERYWHERE+is%3Aclosed

**Pull request closed without merging**
