### PR TITLE
Update GMX.xml

### PR DESCRIPTION
**Pull request by J0WI**
removed obsolete domain

### CODE REVIEW

**Comment by jsha** [comment]
This rule will still be disabled until you remove the default_off.

Can you change the default_off reason to 'needs ruleset tests?' Alternately, add enough ruleset tests that it passes ./test-ruleset-coverage.sh?

Thanks,
Jacob

**Comment by J0WI** [comment]
@jsha I need a hint. I added a lot of test urls, but travis returns the following:

ERROR src/chrome/content/rules/GMX.xml: Not enough tests (0 vs 4) for <Rule from '^http://(www\.)?gmx\.(ca|it|se|ru)/' to 'https://www.gmx.com/'>
ERROR src/chrome/content/rules/GMX.xml: Not enough tests (1 vs 4) for <Rule from '^http://gmx\.(at|ch|co\.uk|fr)/' to 'https://www.gmx.\g<1>/'>
ERROR src/chrome/content/rules/GMX.xml: Not enough tests (0 vs 1) for <Rule from '^http://(www\.)?gmx\.de/' to 'https://www.gmx.net/'>

**Comment by jsha** [comment]
It looks like some of the output got cut off in your comment. Here's what I see:

```
ERROR src/chrome/content/rules/GMX.xml: Not enough tests (0 vs 4) for <Rule from '^http://(www\.)?gmx\.(ca|it|se|ru)/' to 'https://www.gmx.com/'>
ERROR src/chrome/content/rules/GMX.xml: Not enough tests (1 vs 4) for <Rule from '^http://gmx\.(at|ch|co\.uk|fr)/' to 'https://www.gmx.\g<1>/'>
ERROR src/chrome/content/rules/GMX.xml: Not enough tests (0 vs 1) for <Rule from '^http://(www\.)?gmx\.de/' to 'https://www.gmx.net/'>
```

So, for instance, you should add test URLs for www.gmx.ca, www.gmx.it, etc.

One thing I noticed: the previous version of this ruleset only rewrote specific subdomains (listed in the individual `rule` elements), but you removed those rules and replaced them with a global 'http -> https' rewrite. Since the ruleset still has wildcard targets *.gmx.de and www.gmx.*, the new style actually expands coverage significantly. For instance, now https://postmaster.gmx.de is covered, even though that's listed in the comments as non-functional.

My suggestion would be to modify the target hosts to remove wildcards and instead explicitly list each subdomain that was formerly listed in a `rule` tag. E.g., www.gmx.de, www.gmx.ca, www.gmx.it, help.gmx.com, images.gmx.com, etc.

**Comment by J0WI** [comment]
In Line 126 I added all these domains.

I already considered the 'white-listing' method, but in my opinion it's more secure when the default is https.

**Comment by jsha** [comment]
Ah, I see the problem now: Your test URLs need to end with a `/`.

**Comment by jsha** [comment]
BTW I currently get these errors with ./fetch-test.sh:

```
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://storage-file-eu.gmx.com => https://storage-file-eu.gmx.com: (7, 'Failed to connect to storage-file-eu.gmx.com port 80: Connection refused')
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.ca => https://gmx.ca: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.ca'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://www.gmx.ca => https://www.gmx.ca: (51, "SSL: no alternative certificate subject name matches target host name 'www.gmx.ca'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.se => https://gmx.se: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.se'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://www.gmx.se => https://www.gmx.se: (51, "SSL: no alternative certificate subject name matches target host name 'www.gmx.se'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.ru => https://gmx.ru: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.ru'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://www.gmx.ru => https://www.gmx.ru: (51, "SSL: no alternative certificate subject name matches target host name 'www.gmx.ru'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.at => https://gmx.at: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.at'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.ch => https://gmx.ch: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.ch'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.co.uk => https://gmx.co.uk: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.co.uk'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://gmx.de => https://gmx.de: (51, "SSL: no alternative certificate subject name matches target host name 'gmx.de'")
ERROR src/chrome/content/rules/GMX.xml: Fetch error: http://www.gmx.de => https://www.gmx.de: (60, 'SSL certificate problem: certificate has expired')
```

**Comment by J0WI** [comment]
Thanks, I'll fix that!

**Comment by J0WI** [comment]
test passed.

**Comment by jsha** [comment]
Have you run `./fetch-test.sh src/chrome/content/rules/GMX.xml` ?

**Comment by J0WI** [comment]
I just run `fetch-test.sh` and got a few `port 80: connection refused` and timeouts, but they work well when opening in browser (using https).

**Comment by J0WI** [comment]
Would be great to have this rule back soon. GMX is a very popular service in Austria, Germany and Switzerland.

**Pull request merged**
