### PR TITLE
[Levo.com] Update targets

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] https://pages.levo.com/jetset/ has an HTTP redirect caused by a script. https://pages.levo.com/guides/ also has an HTTP redirect. Other `pages` URLs, for example https://pages.levo.com/for-companies/ and https://pages.levo.com/women-in-politics/ , seem okay. I think we should remove the `pages` `target` and the `securecookie` and move `pages` to the top under `HTTP redirect`. Maybe note it like this:
```xml
    HTTP redirect:
        pages.levo.com ( https://pages.levo.com/guides/ , https://pages.levo.com/jetset/ )
```

**Comment by Bisaloo** [comment]
Should I leave the securecookie for `^` ?

**Comment by jeremyn** [comment]
No, the `^` `securecookie` should be removed too. The `^` `securecookie` should be removed if there are some subdomains that don't support HTTPS.

This looks ready to me. Is it okay for me to merge?

**Comment by Bisaloo** [comment]
yes, you can merge it.

**Pull request merged**
