### PR TITLE
[Github] replace *.github.com and *.githubusercontent.com, use ^http: → https:

### PR DESCRIPTION
**Pull request by julianladisch**
Fix #1117 by adding test coverage and reenabling rule

### CODE REVIEW

**Comment by jsha** [comment]
This looks good. Have you run the ruleset checker in manual test mode? That will check each domain to make sure it still exists and answers on 443.

```
python2.7 https-everywhere-checker/src/https_everywhere_checker/check_rules.py https-everywhere-checker/manual.checker.config src/chrome/content/rules/GitHub.xml
```

**Comment by 2d1** [comment]
Note: This has made github tracking cookies insecure.

If @jsha doesn't care about that, be warned I won't be using/testing the same github ruleset as is in master (because I care). I guess the use of the ruleset is widespread enough for that not to matter.

**Comment by julianladisch** [comment]
I was not my intention to make secure cookies insecure. Can you give an example which cookie may be affected?

**Comment by jsha** [comment]
@2d1: I do care about fixing the securecookie issue you flagged on IRC, thanks for the reminder. I've been punting it down the road in favor of improving the ruleset library, but I'll consider it a blocker for the next dev release: https://github.com/EFForg/https-everywhere/issues/1145.

**Pull request merged**
