### PR TITLE
[LimeSurvey.org] Fix cert mismatch

### PR DESCRIPTION
**Pull request by youdly**
https://github.com/EFForg/https-everywhere/pull/15977

### CODE REVIEW

**Comment by J0WI** [comment]
Please document the wildcard DNS record and mismatching certificate on each of them.

**Comment by J0WI** [comment]
Thanks, LGTM so far. Cloud you please do the same on all referenced PRs in https://github.com/EFForg/https-everywhere/pull/15977#issuecomment-478447312?

**Comment by youdly** [comment]
Added comment to https://github.com/EFForg/https-everywhere/pull/15977. Others have mismatch cert issue.

**Comment by J0WI** [comment]
Some fetch tests are failing and it's a circular dependency to #15977.

**Comment by youdly** [comment]
`https://limesurvey.org` is valid again. As this PR depends on https://github.com/EFForg/https-everywhere/pull/15977, I removed reference in that PR.

**Pull request merged**
