### PR TITLE
Delete Daily_Fantasy_Radio.xml

### PR DESCRIPTION
**Pull request by pipboy96**
nxdomain

### CODE REVIEW

**Comment by Bisaloo** [comment]
@pipboy96, are you using a custom script to find those rulesets? If so, it would be better to submit a PR with the script, so we can review it and merge all your changes at once instead of reviewing each ruleset one by one.

**Comment by pipboy96** [comment]
@Bisaloo Yes, but the script is only used to generate candidates for manual review. I try buying/WHOISing the domain from multiple registrars in order to find out if it actually does not exist.

**Comment by pipboy96** [comment]
I guess I will limit myself to 10 active rulesets at any point of time to not overload the reviewers.

**Comment by pipboy96** [comment]
Here's the candidate list:

- `16chan.nl.xml`
- `24img.com.xml`
- `33option.com.xml`
- `350zEvolution.com.xml`
- `5000etherhomepage.com.xml`
- `6to4.ru.xml`
- `A1A_Fast_Cash.xml`
- `AdExcite.xml`
- `AEMI.xml`
- `Amblin.io.xml`
- `arhivach.org.xml`
- `Asset_Insight.xml`
- `AustralianEmergencyManagement.xml`
- `AustralianGovernmentBoards.xml`
- `Auto_Rims_and_Accessories.xml`
- `BarkerJr.net.xml`
- `BazzApp.xml`
- `Beanstock_Media.xml`
- `Beender.co.xml`
- `belaruspartisan.org.xml`
- `BerliOS.de.xml`
- `Bet555.xml`
- `BlackZNC.net.xml`
- `Bored_to_Death.xml`
- `Braveinfo.net.xml`
- `BTDB.to.xml`
- `Buzzhosting.org.xml`
- `CacheBrowser.info.xml`
- `California_Polytechnic_State_University_Ponoma.xml`
- `cihan.com.tr.xml`
- `CineSport.xml`
- `cloud3.me.xml`
- `Creative_Little_Readers.com-falsemixed.xml`
- `Creative_Little_Readers.com.xml`
- `Credit_Repair_Trust.com.xml`
- `Daily_Fantasy_Radio.xml`
- `DarknetMarkets.today.xml`
- `Dealfish.co.th.xml`
- `diymealbox.com.xml`
- `dribper.com.xml`
- `du00.cc.xml`
- `Eide-ITC.no.xml`
- `eme.moe.xml`
- `Engaged_Doncaster.co.uk.xml`
- `Feminism.lgbt.xml`
- `FlutterToday.com.xml`
- `Folkestone.lgbt.xml`
- `ForAndBy.lgbt.xml`
- `freecode.club.xml`
- `Freight_Calculator_Australia.xml`
- `Gayby.lgbt.xml`
- `GearSourceCDN.com.xml`
- `GetItHere.xyz.xml`
- `GirlLoveGirl.net.xml`
- `Gistmarks.com.xml`
- `Goaldet.com.xml`
- `Green_Coffee_Bean_Extract.xml`
- `Grouper_Social_Club.com.xml`
- `Guardian_Subscriptions.co.uk.xml`
- `Halcyon.sh.xml`
- `HealthyEating.science.xml`
- `Howinerd.com.xml`
- `hsbc.com.mu.xml`
- `hsbc.com.om.xml`
- `huaban.com.xml`
- `hyb.pw.xml`
- `Iamnoone-solutions.net.xml`
- `Infamous.xml`
- `Infinow.net.xml`
- `mi-pro.co.uk.xml`
- `Intent-Media.xml`
- `Investigative-News-Network.xml`
- `kaprica.com.xml`
- `Kdelive.org.xml`
- `KHOC.co.xml`
- `Kr36.co.xml`
- `Krautchan.xml`
- `Liberdade.Digital.xml`
- `Linuxslut.net.xml`
- `ListaGay.lgbt.xml`
- `Marketplace_Used.xml`
- `Mazacha.in.xml`
- `MegaBigPower.com.xml`
- `Mightyupload.com.xml`
- `MindWeb.network.xml`
- `MiniMundos_online.com.xml`
- `NationalEthicsApplicationForm.xml`
- `ncar.cc.xml`
- `Netcloude.cz.xml`
- `NeverDDoS.com.xml`
- `Nevistas_Health.com.xml`
- `New_Flag.xml`
- `newferre.com.xml`
- `NewMuslimVoice.com.xml`
- `newpiratebay.co.uk.xml`
- `ntkstatic.org.xml`
- `Nie-wieder-VDS.de.xml`
- `No-DPI-campaign.xml`
- `Odesk.by.xml`
- `oldbayproxy.eu.xml`
- `One_Health_Talk.org.xml`
- `One-Good-Driver.xml`
- `OpenBitTorrent.com.xml`
- `OTR.to.xml`
- `packetflagon.is.xml`
- `Patent-Baristas.xml`
- `Philosophy.lgbt.xml`
- `PhotoBTC.com.xml`
- `pigtown.news.xml`
- `pixhost.org.xml`
- `pixxxels.org.xml`
- `PlantCommunity.de.xml`
- `portalpiratebay.co.uk.xml`
- `Portland_State_University-falsemixed.xml`
- `Portland_State_University.xml`
- `postovoy.org.xml`
- `PrivateInvestigator.lgbt.xml`
- `RB_Invest_WDC.eu.xml`
- `Rebel_Torrent.net.xml`
- `ReligMag.com.xml`
- `rubri.co.xml`
- `SavvyHawk.com.xml`
- `Secureuk.net.xml`
- `SEMABUZZ.COM.xml`
- `Seower.com.xml`
- `Shipment.xml`
- `Sidibouras.xml`
- `Silva_Wood_Flooring.xml`
- `Smartling-problematic.xml`
- `Speed_World_Grafix.com.xml`
- `Srcclr.help.xml`
- `SSE_Events_Group.com.xml`
- `storm-chasers.de.xml`
- `Sunrise_Print_Online.xml`
- `TheMuslimahDiaries.com.xml`
- `thepiratebay.red.xml`
- `torrentz2.eu.xml`
- `TransTravels.lgbt.xml`
- `Travelspecialistsite.com.xml`
- `Trgt.eu.xml`
- `TriDeci.xml`
- `TVLinks.xml`
- `Twky.in.xml`
- `upload.af.xml`
- `VARCentral.com.au.xml`
- `Vetbiz.gov.xml`
- `Vital_Gamers.com.xml`
- `vodkamethod.com.xml`
- `voidlinux.eu.xml`
- `VoIPDistributor.net.xml`
- `W00tads.com.xml`
- `Web_Tune_Factory.xml`
- `WebD.AM.xml`
- `Weboolu.xml`
- `WebXakep.Net.xml`
- `Wed.is.xml`
- `WeRoSys.de.xml`
- `White_Lisbon.com.xml`
- `Wood_Green_Shop.org.uk.xml`
- `Wordentropy.org.xml`
- `Xperia_Studio.xml`
- `Xxx24hr.com.xml`
- `YoutubeUnblocks.com.xml`

Here's the relevant part of the script:
```js
'use strict'

const axios = require('axios')

const resolverUrls = [
  'https://dns9.quad9.net/dns-query',
  'https://cloudflare-dns.com/dns-query',
  'https://dns.google.com/resolve'
]

// returns true ONLY for NXDOMAIN responses

const createResolver = url => async domain => {
  try {
    const response = await axios({
      method: 'get',
      url: `${url}?name=${encodeURIComponent(domain)}&type=A`,
      headers: { accept: 'application/dns-json' },
      timeout: 60000
    })
    return response.data['Status'] === 3
  } catch (e) {
    console.error(`Domain ${domain} failed to resolve, assuming it exists`)
    return false
  }
}

const resolvers = resolverUrls.map(createResolver)

exports = module.exports = async domain => {
  const results = await Promise.all(resolvers.map(resolver => resolver(domain)))

  if (results.every(r => r)) {
    return true
  }

  if (results.some(r => r)) {
    console.error(`${domain} exists only partially!?`)
  }

  return false;
}
```

**Comment by pipboy96** [comment]
Related: #17474

**Pull request closed without merging**
