### PR TITLE
Minor style fixes to cschanaj script

### PR DESCRIPTION
**Pull request by pipboy96**
Feel free to partially merge/cherrypick if needed.

### CODE REVIEW

**Comment by Hainish** [comment]
Looks good and confirmed it still performs as intended

**Comment by pipboy96** [comment]
@Hainish can you also do `s/new Array()/[]/`? I accidentally missed it.

**Comment by Hainish** [comment]
@pipboy96 I don't think it necessary to change all instances of this since this is only performed by admins and only once in a while, the performance gains will be minimal.  `new Array()` is still valid even if it is slightly optimized.

**Comment by pipboy96** [comment]
@Hainish should https://github.com/EFForg/https-everywhere/pull/18065 be closed or can you still merge, even though it's not really 100% necessary?

**Comment by Hainish** [comment]
Merged.

**Pull request merged**
