### PR TITLE
axelname.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
Please see also:
expired.axelname.ru
expired1.axelname.ru
vizitca2.axelname.ru
pages.axelname.ru

**Comment by galeksandrp** [comment]
Added.

**Comment by J0WI** [comment]
I still miss `pages.axelname.ru`

**Comment by galeksandrp** [comment]
`pages.axelname.ru` refused

**Comment by J0WI** [comment]
So is it worth to add a comment?

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
