### PR TITLE
Re-activate and update FlyersRights.xml

### PR DESCRIPTION
**Pull request by cschanaj**
#17965

### CODE REVIEW

**Comment by pipboy96** [comment]
Do you mean that both have wildcard DNS records?

**Comment by cschanaj** [comment]
> Do you mean that both have wildcard DNS records?

No, it only mean to be a separator :smile:

**Comment by pipboy96** [comment]
I mean, is `anything.flyersrights.com` an actual domain, or it it because of the wildcard?

**Comment by cschanaj** [comment]
`anything.flyersrights.com` has a valid DNS records and `flyersrights.com` itself does not have a wildcard DNS. However, `anything.flyersrights.com` does not seems to serve any content. I am okay to remove it if it is leading to confusion.

**Comment by pipboy96** [comment]
If this subdomain exists, keep it.

**Comment by pipboy96** [comment]
```
anything.flyersrights.com
flyersrights.com
www.flyersrights.com
ftp.flyersrights.com
imap.flyersrights.com
email.flyersrights.com
mobilemail.flyersrights.com
pda.flyersrights.com
pop.flyersrights.com
e.flyersrights.com
smtp.flyersrights.com
mail.flyersrights.com
webmail.flyersrights.com
```

**Comment by cschanaj** [comment]
Since none of the subdomains found for `*.flyersrights.com` support HTTPS, I prefer to remove them entirely from this rulesets.

```
	Non-functional hosts

		Couldn't connect to server:
		- smtp.flyersrights.com

		Timeout was reached:
		- imap.flyersrights.com
		- pop.flyersrights.com
		- mail.flyersrights.com

		SSL connect error:
		- anything.flyersrights.com

		SSL peer certificate was not OK:
		- flyersrights.com
		- www.flyersrights.com
		- ftp.flyersrights.com
		- email.flyersrights.com
		- mobilemail.flyersrights.com
		- pda.flyersrights.com
		- e.flyersrights.com
		- webmail.flyersrights.com
```

**Comment by pipboy96** [comment]
```
flyersrights.org
www.flyersrights.org
admin.flyersrights.org
mail.flyersrights.org
new.flyersrights.org
imap.flyersrights.org
email.flyersrights.org
ftp.flyersrights.org
sucuriip.flyersrights.org
e.flyersrights.org
pop.flyersrights.org
smtp.flyersrights.org
pda.flyersrights.org
webmail.flyersrights.org
mobilemail.flyersrights.org
www.admin.flyersrights.org
```

**Comment by pipboy96** [comment]
`http://(www\.)?flyersrights.com/` can be snapped to `https://www.flyersrights.org/`.

**Comment by pipboy96** [comment]
```
$ curl -I http://flyersrights.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Sun, 05 May 2019 23:21:49 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Location: http://www.flyersrights.org

$ curl -I http://www.flyersrights.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.2
Date: Sun, 05 May 2019 23:21:58 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Location: http://www.flyersrights.org
```

**Comment by cschanaj** [comment]
I think the CONTRIBUTING.md explicitly stated that we should avoid snapping redirects, not to mention that `flyersrights.com` does not support HTTPS correctly.

> HTTPS Everywhere rulesets should change requests the minimum amount necessary to ensure a secure connection.

**Comment by pipboy96** [comment]
@cschanaj I believe HTTP 301 is fine to cache due to the nature of such redirect.

**Comment by cschanaj** [comment]
Just to note that in general I do not like cross-domain snapping rules. For the reason that they cannot be easily disabled from the extension UI and they cause CORS blocking sometimes. 

However, since the domain `flyersrights.com` does not seem to serve any content other than 301 redirects, I will add the snapping rewrite this time, as an exception.

**Pull request merged**
