### PR TITLE
[Correios.com.br] Please add the brazilian post tracking service

### PR DESCRIPTION
**Pull request by u451f**
Thanks & cheers!

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for contributing to HTTPS-Everywhere!
First, please have a look at our [guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md). Your rule does not yet fit our style guide.
We also have automated tests for new rulesets and they found a typo in your redirect.

Just ping me for questions or when you're ready for a review.

**Comment by koops76** [comment]
Duplicate of #11222.

**Comment by jeremyn** [comment]
@u451f Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @u451f . I've noted `correios.com.br` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353636630` in case someone else wants to make a pull request for this domain.

**Pull request closed without merging**
