### PR TITLE
Only fetch upstream-for-travis with a depth of 1

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
https://github.com/EFForg/https-everywhere/pull/7553/files#diff-bbe2fbd85330a6c5ddfb5070a4028d5cL15

Oops, does this affect the hooked testing?

**Comment by Hainish** [comment]
@gloomy-ghost yep, should work either way

**Comment by gloomy-ghost** [comment]
Can I merge this now? It saves 600+MB for every build (I don't pay for the bandwidth though)

**Comment by Hainish** [comment]
@gloomy-ghost merged!

**Pull request merged**
