### PR TITLE
Re-activate Library_Freedom_Project.org.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**
#12677

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
It doesn't include subdomains in Firefox's preloading list, nor does it serve `preload` in header now. Can you change this PR to re-active the ruleset?

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@gloomy-ghost So why does https://hstspreload.org/?domain=libraryfreedomproject.org say that it's `Status: libraryfreedomproject.org is currently preloaded.`?

**Comment by gloomy-ghost** [comment]
I don't know the exact reason, but I guess it _might_ be preloaded in early days when `includeSubDomains` is not yet a requirement. 
https://dxr.mozilla.org/mozilla-central/rev/967c95cee709756596860ed2a3e6ac06ea3a053f/security/manager/ssl/nsSTSPreloadList.inc#15213

**Comment by Bisaloo** [comment]
Some domains are also manually added to the preload list. In this case, they don't need to meet the requirements. This is usually limited to high profile websites (see twitter.com, paypal.com, torproject.org, google-analytics.com, etc.)

Related: https://github.com/chromium/hstspreload.org/issues/111

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@Bisaloo @gloomy-ghost Thanks for all the information, I've re-activated it now

**Pull request merged**
