### PR TITLE
Create Toronto-Police-Services

### PR DESCRIPTION
**Pull request by tossj**
Add rule set for [torontopolice.on.ca](https://torontopolice.on.ca).

### CODE REVIEW

**Comment by christianheinrichs** [comment]
@tossj 3 Travis CI checks have failed with the error message:
> `src/chrome/content/rules/Toronto-Police-Services failed validity: Rule filenames must end in .xml` 

Simply append .xml in another commit to fix this.

**Comment by jeremyn** [comment]
@tossj Are you still interested in working on this pull request?

**Comment by tossj** [comment]
@jeremyn I believe I was already finished with this and was only awaiting a merge. Is there anything else to do for this PR?

**Comment by jeremyn** [comment]
@tossj There are some improvements you can make:

- [ ] Use this with filename `TorontoPolice.on.ca` :
```xml
<!--
	Invalid certificate:
		data.torontopolice.on.ca
		maps.torontopolice.on.ca

	Mixed content blocking:
		c4s.torontopolice.on.ca

-->
<ruleset name="TorontoPolice.on.ca">
	<target host="torontopolice.on.ca" />
	<target host="www.torontopolice.on.ca" />
	<target host="bike.torontopolice.on.ca" />
	<target host="careers.torontopolice.on.ca" />
	<target host="clearance.torontopolice.on.ca" />
	<target host="core.torontopolice.on.ca" />
	<target host="secure.torontopolice.on.ca" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

See our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md) for more information.

Optionally, you can also find some related domains in `Developer Tools > Network` while loading https://torontopolice.on.ca such as `tpsmedia.ca` and `tpsnews.ca`. If you want to cover those, you can add new ruleset files to this PR.

**Comment by tossj** [comment]
@jeremyn I added the changes you suggested. Does everything look good?

**Comment by jeremyn** [comment]
With closely related domains like this, we sometimes want to have them refer to each other, by having the "secondary" rulesets point to one "primary" ruleset which refers to the others.

Also, unfortunately it looks like https://tpsnews.ca has some mixed content blocking, for example notice that the section under "Social Media" is mostly blank gray. However we want to cover some of this domain, particularly the URLs that are loaded for the main https://torontopolice.on.ca site. So we'll handle this by splitting your current `Tpsnews.ca.xml` into two files.

So we'll have five rulesets:

- [ ] `TorontoPolice.on.ca.xml`
```xml
<!--
	Other TPS (Toronto police) rulesets:
		Tpsmedia.ca.xml
		Tpsnet.ca.xml
		Tpsnews.ca.xml
		Tpsnews.ca-mixedcontent.xml

	Invalid certificate:
		data.torontopolice.on.ca
		maps.torontopolice.on.ca

	Mixed content blocking:
		c4s.torontopolice.on.ca

-->
<ruleset name="TorontoPolice.on.ca">
	<target host="torontopolice.on.ca" />
	<target host="www.torontopolice.on.ca" />
	<target host="bike.torontopolice.on.ca" />
	<target host="careers.torontopolice.on.ca" />
	<target host="clearance.torontopolice.on.ca" />
	<target host="core.torontopolice.on.ca" />
	<target host="secure.torontopolice.on.ca" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

- [ ] `Tpsmedia.ca.xml`:
```xml
<!--
	For other TPS (Toronto police) rulesets, see TorontoPolice.on.ca.xml.

-->
<ruleset name="Tpsmedia.ca">
	<target host="tpsmedia.ca" />
	<target host="www.tpsmedia.ca" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

- [ ] `Tpsnet.ca.xml`:
```xml
<!--
	For other TPS (Toronto police) rulesets, see TorontoPolice.on.ca.xml.

-->
<ruleset name="Tpsnet.ca">
	<target host="tpsnet.ca" />
	<target host="www.tpsnet.ca" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

- [ ] `Tpsnews.ca.xml`:
```xml
<!--
	See also Tpsnews.ca-mixedcontent.xml.

	For other TPS (Toronto police) rulesets, see TorontoPolice.on.ca.xml.

-->
<ruleset name="Tpsnews.ca">
	<target host="tpsnews.ca" />
		<exclusion pattern="^http://tpsnews.ca/$" />
		<test url="http://tpsnews.ca/feeds/stories.json?format=json" />
	<target host="www.tpsnews.ca" />
		<exclusion pattern="^http://www.tpsnews.ca/$" />
		<test url="http://www.tpsnews.ca/static/images/grey.gif" />

	<rule from="^http://(www\.)?tpsnews.ca/(feeds|static)/"
		to="https://$1tpsnews.ca/$2/" />
</ruleset>
```

- [ ] `Tpsnews.ca-mixedcontent.xml`:
```xml
<!--
	See also Tpsnews.ca.xml.

	For other TPS (Toronto police) rulesets, see TorontoPolice.on.ca.xml.

-->
<ruleset name="Tpsnews.ca-mixedcontent" platform="mixedcontent">
	<target host="tpsnews.ca" />
	<target host="www.tpsnews.ca" />

	<!-- Exclude URLs covered by Tpsnews.ca.xml -->
	<exclusion pattern="^http://(www\.)?tpsnews.ca/(feeds|static)/" />
		<test url="http://tpsnews.ca/feeds/stories.json?format=json" />
		<test url="http://tpsnews.ca/static/images/grey.gif" />
		<test url="http://www.tpsnews.ca/static/images/grey.gif" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

**Comment by jeremyn** [comment]
@gloomy-ghost @J0WI Could one of you please double-check what I'm asking @tossj to do in my previous comment https://github.com/EFForg/https-everywhere/pull/12503#issuecomment-350031660?

**Comment by tossj** [comment]
Sometimes these TPS pages have links that point to [`tps.on.ca`](http://tps.on.ca), which is just a redirect to `torontopolice.on.ca`. `tps.on.ca` doesn't have any `https` support, so if the `href` of an anchor tag is created using `//tps.on.ca` these links will not work as intended.

Should rulesets be provided for `tps.on.ca` and `tps.to` that change `https` to `http`, or are these considered snapping redirects and should not have rulesets?

**Comment by jeremyn** [comment]
Do you have an example of a page with an https://tps.on.ca link? https://torontopolice.on.ca > `Services` > `Community Asset Portal` is http://cap.tps.on.ca , not `https`.

**Comment by tossj** [comment]
https://tpsnews.ca/ > `social media` points to https://tps.on.ca. This is on the navigation banner in between `my division` and `news releases`, not the social media feed.

**Comment by jeremyn** [comment]
We shouldn't be rewriting http://tpsnews.ca to HTTPS since it is covered by `Tpsnews.ca-mixedcontent` which is (sort of) disabled by default, being `mixedcontent`.

I want to get a sense for how big this relative href problem actually is for TPS sites. Literally any site could theoretically have relative hrefs to some domain that doesn't work with HTTPS, so if we were too strict about this then we wouldn't have any rulesets at all.

**Comment by tossj** [comment]
On tpsnews.ca there is only one instance of `//tps.on.ca`, and no other `href="//` type links. On torontopolice.on.ca there are more `href="//` types links but they all have working https, so I don't think the one bad link on tpsnews.ca is a problem.

**Comment by jeremyn** [comment]
Okay, thanks.

I've updated the checklist in https://github.com/EFForg/https-everywhere/pull/12503#issuecomment-350031660 based on your regex fixes in https://github.com/EFForg/https-everywhere/pull/12503/commits/ba2a4c7562222b075a9b56e837f2cbe919bbc961. I'm sorry for any confusion there.

I think this is ready to merge but I'd like a double-check from @gloomy-ghost or @J0WI first, especially on the more complicated behavior of `Tpsnews.ca.xml` and `Tpsnews.ca-mixedcontent.xml`. So let's wait for that.

**Comment by J0WI** [comment]
I can only find mixed content issues on some sites.
The pages on stories, blogs, photos, videos and  events (main navigation) seems to be fine.

**Comment by jeremyn** [comment]
@J0WI There might be more parts of https://tpsnews.ca besides `/feeds` and `/static` that don't have mixed content blocking, but those are the two that I see on https://torontopolice.on.ca . Do you think we should move more stuff from the `Tpsnews.ca-mixedcontent.xml` into `Tpsnews.ca.xml`, or is it okay the way it is now?

**Comment by J0WI** [comment]
This shouldn't be a blocker for merge.

**Comment by jeremyn** [comment]
Thanks @tossj and @J0WI , merged.

**Pull request merged**
