### PR TITLE
update Coop.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Remove entirely:
- [ ] https://games.coop.ch (not in DNS)
- [ ] https://quizshow.coop.ch (not in DNS)
- [ ] https://streamingneu.coop.ch (not in DNS)
- [ ] https://sudoku.coop.ch (not in DNS)
- [ ] https://superchance.coop.ch (not in DNS)
- [ ] https://supergambler.coop.ch (not in DNS)
- [ ] https://mycoopmobile.coop.ch (times out in both HTTP and HTTPS)
- [ ] https://libs.coop.ch (403 in both HTTP and HTTPS; remove target)
 
Mark as `Different HTTP/HTTPS content`:
- [ ] https://webservice.fust.ch (303->404 HTTP, 200 HTTPS; remove target)
 
Mark as `HTTP redirect`:
- [ ] https://neu.coop.ch (remove target)
 
Mark as `Invalid certificate`:
- [ ] https://christ-swiss.ch
- [ ] https://cooperazione.ch
- [ ] https://interdiscount.ch
- [ ] https://microspot.ch
- [ ] https://the-body-shop.ch
- [ ] https://www.the-body-shop.ch
- [ ] https://thebodyshop.ch
 
Mark as `Mixed content`:
- [ ] https://www.cooperazione.ch
- [ ] https://www.thebodyshop.ch (video player is broken)
 
Mark as `Secure connection failed`:
- [ ] https://disney.coop.ch (remove target)
 
Add `target`:
- [ ] https://bankcoop.ch (remove from HTTP redirect)
- [ ] https://www.bankcoop.ch (remove from HTTP redirect)
- [ ] https://mobile.bankcoop.ch (remove from HTTP redirect)
- [ ] https://img.christ-swiss.ch (with `test` https://img.christ-swiss.ch/layout/aktionen/050-small-de.png )
- [ ] https://www2.coop.ch (remove from timeout)
- [ ] https://supercard.ch
 
Remove these special `rule`s since both `^` and `www` have problems noted above:
- [ ] `(www\.)?cooperazione.ch`
- [ ] `(www\.)?thebodyshop.ch`
- [ ] `(www\.)?the-body-shop.ch`
 
Also:
- [ ] Remove [`<!-- cert only matchin www. -->`](https://github.com/J0WI/https-everywhere/blob/f88a1d997bd6785ae4dd0426caac0c9bbc6eb7f8/src/chrome/content/rules/Coop.ch.xml#L106) comment (see `Invalid certificate` items; let me know if you feel strongly about keeping it the way it is now)

The coverage for `fust.ch` could be expanded since we are removing the wildcard, however @Bisaloo made pull request https://github.com/EFForg/https-everywhere/pull/10433 that does that. So let's finish this current pull request, and then @Bisaloo can rebase their pull request on this one.

**Comment by Bisaloo** [comment]
@J0WI, are those domains related? In other words, if I split this ruleset, should the children rulesets still link to each other in the top comment?

**Comment by J0WI** [comment]
@jeremyn Thanks, I've updated the targets and comments.
* I also added a test url for `libs.coop.ch`.
* I moved `cooperazione.ch` and `thebodyshop.ch` to the mixed content ruleset.
* I didn't notice any issues with `disney.coop.ch`

@Bisaloo yes, please keep them related.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/6781/commits/241fee64d182b3daf5b8b348d2114c9c148be54c.

https://disney.coop.ch has an OCSP revoked certificate. To see this in Firefox you need to go to `about:preferences#advanced > Certificates` and make sure `Query OCSP responder servers to confirm the current validity of certificates` is checked. You can also use the process at https://raymii.org/s/articles/OpenSSL_Manually_Verify_a_certificate_against_an_OCSP.html to check revocation on the command line.

**Comment by jeremyn** [comment]
I updated the checklist to ask that you add extra clarification to `disney.coop.ch` about the revoked certificate.

**Comment by J0WI** [comment]
For some reason OCSP is broken in current Nightly Build. I removed the target.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
