### PR TITLE
update betabeat.com

### PR DESCRIPTION
**Pull request by luciancor**

### CODE REVIEW

**Comment by J0WI** [comment]
This is default_off anyway and redirects to observer.com, which itself redirects to http.
So I think it's safe to remove the whole rule here.

**Comment by jeremyn** [comment]
@luciancor Are you still interested in working on this?

**Comment by luciancor** [comment]
@jeremyn definitely! Sorry for the delay.
I removed the whole rule as suggested by @J0WI . Please let me know if this is not fine.

**Comment by jeremyn** [comment]
Deleting the whole rule is fine.

We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by luciancor** [comment]
Sure - no problem. Feel free to squash this one and any other future PRs. Thanks for the feedback!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
