### PR TITLE
Create ejtaal.net.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks, lgtm except space indentations.

**Comment by Folant** [comment]
Fixed spaces.

**Comment by gloomy-ghost** [comment]
Please also fix comments and the blank newline.

**Comment by Folant** [comment]
Sorry, should be fine now.

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Pull request merged**
