### PR TITLE
Computerbase.de:

### PR DESCRIPTION
**Pull request by numismatika**
- add test-urls and more files
- remove stylesheets path, not used anymore
- remove wildcard
- fix forum editor

### CODE REVIEW

**Comment by J0WI** [comment]
I found some more:

/api/stats
/css/
/login/
/abo/
/push/

They are also working for ^computerbase.de

**Comment by numismatika** [comment]
have you checked that those don't break the page and especially the forum?
Forum was a bit evil on my first attempts.

**Comment by J0WI** [comment]
Resource rewriting should be quite safe. Do you have an account to check the behaviour for logged in visitors?

The following pattern is working for me:
```
<rule from="^http://www\.computerbase\.de/(api/|css/|login/|abo/|push/|clientscripts/|js/|design/|img/|forum/images/|forum/clientscript/)" to="https://www.computerbase.de/$1"/>
```
They are just some broken 404, but this is trivial I think.

You can also safely redirect videos.computerbase.de.

**Comment by numismatika** [comment]
Yes i have, that is how i uncovered the forum issue.
I'll check a few more days before i consider it working.
Shouldn't be a problem though, they offer TLS for their paid users.

**Comment by numismatika** [comment]
so far it looks fine @J0WI

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
