### PR TITLE
Create planetemu.net.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by zoracon** [comment]
There is an existing ruleset living in this file `Planet_Emu.net.xml`. You can update that file if it's needed.

**Comment by pipboy96** [comment]
@TotalCaesar659 @zoracon Old ruleset is `default_off="expired, mismatched, self-signed"`, it's fine to delete it.

**Comment by pipboy96** [comment]
@TotalCaesar659 Simply do https://github.com/TotalCaesar659/https-everywhere/delete/planetemu.net.xml/src/chrome/content/rules/Planet_Emu.net.xml

**Comment by zoracon** [comment]
It seems like the cert chain for this is still broken. Closing for now.

**Pull request closed without merging**
