### PR TITLE
Fedorainfracloud.org.xml

### PR DESCRIPTION
**Pull request by J0WI**
This replaces #6564

### CODE REVIEW

**Comment by jeremyn** [comment]
Remove entirely:
- [ ] https://eclipse.fedorainfracloud.org (refused HTTPS, error codes HTTP)

Mark as `Invalid certificate` or similar:
- [ ] https://modularity.fedorainfracloud.org
- [ ] https://piwik.fedorainfracloud.org (and remove from `(m)`)
 
Mark as `Refused`:
- [ ] https://testdays.fedorainfracloud.org

Add `target`:
- [ ] https://fedorainfracloud.org
- [ ] https://www.fedorainfracloud.org

**Comment by jeremyn** [comment]
Also you can rid of the `Note that...` comment if you want.

**Comment by J0WI** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
