### PR TITLE
[Interior Savings Credit Union] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark under `Invalid certificates`:
- [ ] https://beremarkable.interiorsavings.com
- [ ] https://mdws.interiorsavings.com

Add `test` directly under the corresponding `rule`:
- [ ] https://forms.myinteriorsavings.com/community/application-selector
- [ ] https://community.myinteriorsavings.com/community/

Also:
- [ ] Delete [this empty line](https://github.com/lucaspetter/https-everywhere/blob/53ca253491f998c667851d32ba6ed3a9583b2184/src/chrome/content/rules/Interior-Savings-Credit-Union.xml#L10)
- [ ] Add an empty line [here](https://github.com/lucaspetter/https-everywhere/blob/53ca253491f998c667851d32ba6ed3a9583b2184/src/chrome/content/rules/Interior-Savings-Credit-Union.xml#L13-L14) to separate `interiorsavings.com` and `myinteriorsavings.com`.
- [ ] Remove the general `securecookie` and (optionally) add multiple, specific `securecookie`s, because of the various nonworking domains.

**Comment by lucaspetter** [comment]
Thanks for your help. I made most of the changes you requested.

However, are you sure `mdws.interiorsavings.com` has an invalid certificate? It loads in Chrome and SSL Labs reports [no issues](https://www.ssllabs.com/ssltest/analyze.html?d=mdws.interiorsavings.com). I left it as a `target` and in the `securecookie` tag for now.

**Comment by jeremyn** [comment]
https://mdws.interiorsavings.com looks fine now, I'm not sure why I marked it as bad before.

Everything looks good, except could you please add a tab indent for the two `test` tags to offset them from the `target`s? So it should look like this:

```xml
	<target host="community.myinteriorsavings.com" />
		<test url="http://community.myinteriorsavings.com/community/" />
```

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by lucaspetter** [comment]
Thanks.

**Pull request merged**
