### PR TITLE
Update file and contents for DogsbodyTechnology

### PR DESCRIPTION
**Pull request by dogsbody**
Thank you for a great tool

### CODE REVIEW

**Comment by pipboy96** [comment]
If possible, use [HSTS preloading](https://hstspreload.org) instead. This will upgrade the connection even if the user does not have HTTPS Everywhere installed.

**Comment by dogsbody** [comment]
Thank you and apologies for getting the ordering slightly wrong :+1: 

> Also, maybe you should also add `webhook01.dogsbodytechnology.com`?

This hostname will literally be deleted within the next month with no redirects. It seemed wrong to list this now or as something that was broken as it's going away but think you for raising it.

> If possible, use [HSTS preloading](https://hstspreload.org) instead. This will upgrade the connection even if the user does not have HTTPS Everywhere installed.

We are definitely working towards this goal :100:  :+1:

**Comment by pipboy96** [comment]
@dogsbody Great! Thanks for applying the changes.

**Comment by dogsbody** [comment]
I can't quite work out why the CI tests are failing.

I can see it's only on Chrome and `test_httpnowhere_blocks` but can't find any details of what that is testing for. Any hints appreciated :+1:

**Comment by pipboy96** [comment]
@dogsbody This error can be safely ignored, it's not related to your ruleset.

**Pull request merged**
