### PR TITLE
Added rule for padi.com

### PR DESCRIPTION
**Pull request by le4ker**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

Note as `Refused`:
- [ ] mypadi.padi.com

`PROTOCOL_ERROR`:
- [ ] amsi.padi.com

`Invalid Certificate`:
- [ ] b2bpilstaging.padi.com
- [ ] dive.padi.com
- [ ] elearning.padi.com
- [ ] emeasi.padi.com
- [ ] travel.padi.com

`Redirect to http`:
- [ ] b2bamericas.padi.com

`MCB`:
- [ ] apps.padi.com (can be secured)

Add targets:
- [ ] autodiscover.padi.com
- [ ] b2bamstaging.padi.com
- [ ] b2bap.padi.com
- [ ] b2bcanada.padi.com
- [ ] b2bpil.padi.com
- [ ] esynergy.padi.com
- [ ] livewebservices.padi.com
- [ ] mailsvr.padi.com
- [ ] pros.padi.com
- [ ] scubavacations.padi.com
- [ ] securetravel.padi.com
- [ ] tecrec.padi.com
- [ ] www2.padi.com

**Comment by PanosSakkos** [comment]
Thank @gloomy-ghost.

How did you detect these errors? Is there a script that crawls the website under https and detects the errors?

Also, can you please explain in more details what do I need to add in the ruleset?

Thanks!

**Comment by gloomy-ghost** [comment]
The general suggestions of subdomains searching and ruleset style are at https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

Also you need to list problematic subdomain in a top comment, [here](https://github.com/EFForg/https-everywhere/blob/abe8d958dd8ebe345532f045d13ee1fa5d90bb25/src/chrome/content/rules/alarabiya.net.xml) is an example.

Script of searching subdomains is under discussion, please check #7277 for more information.

**Comment by J0WI** [comment]
ping @PanosSakkos

**Comment by jeremyn** [comment]
@le4ker Are you still interested in working on this?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @le4ker . I've noted `padi.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353117944` in case someone else wants to make a pull request for this domain.

**Pull request closed without merging**
