### PR TITLE
New ruleset Hestore.hu.xml

### PR DESCRIPTION
**Pull request by hzsolt94**

### CODE REVIEW

**Comment by hzsolt94** [comment]
Is there anything blocking this PR?

**Comment by hzsolt94** [comment]
Refactored securecookie.

**Comment by hzsolt94** [comment]
Refactored to the format @gloomy-ghost usually requests.

**Comment by hzsolt94** [comment]
Sorry for messing up with git.

**Comment by gloomy-ghost** [comment]
I'm okay with this PR but in the future please don't ping me on PRs unless I am already involved in them and might have missed the most recent update.

**Comment by hzsolt94** [comment]
Thanks, noted.

**Pull request merged**
