### PR TITLE
Rewrite Alexa Labeller

### PR DESCRIPTION
**Pull request by zoracon**
- Updated npm packages
- Migrate old Github API package to new one (Octokit)
- Rewrite Labeller node app

~~@TODO discard old `index.js` for `app.js` once draft phase is over~~

### CODE REVIEW

**Comment by pipboy96** [comment]
@zoracon Maybe it's a good idea to make this a GitHub Action?

**Comment by pipboy96** [comment]
This is an example of one, though I have stopped working on it: https://github.com/pipboy96/https-everywhere-labeler/

**Comment by zoracon** [comment]
@pipboy96 I'm not a savant when it comes to Github Actions, but I been looking into this to see if this is feasbible.

**Comment by zoracon** [comment]
> @pipboy96 I'm not a savant when it comes to Github Actions, but I been looking into this to see if this is feasbible.

Update: So far so good trying to get an action together. Thanks @pipboy96 for the previous attempt, I'm largely borrowing from that and making this a local action inside the repo since I finally found a good tool to test actions locally.

Fingers crossed. If works out I can archive the labeler in `utils`, save this rewrite for the sake of keeping a separate component not tied to Github Actions, and close this PR out for another one.

**Comment by zoracon** [comment]
With the lack of local testing tools for Github Actions the workflow to actually see what the underlying issue to completion is getting tougher and tougher. I don't want to spend too much time on this so I will go ahead with this PR at the moment. Especially since so much needs attention in the repo with other matters.

It would have been nice to utilize Github Actions, but for now a working labeling tool is sufficient.

**Pull request merged**
