### PR TITLE
Delete CSdata1.com.xml

### PR DESCRIPTION
**Pull request by youdly**
`dsa` could not be resolved. Other subdomains simply timeout.

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Remove the reference to this file from [`EBay.xml`](https://github.com/EFForg/https-everywhere/blob/29f984ea472021978cb9c619c6de6050494cde33/src/chrome/content/rules/EBay.xml#L7)

**Comment by youdly** [comment]
Pending https://github.com/EFForg/https-everywhere/pull/13773

**Comment by jeremyn** [comment]
I merged this despite the Travis error `ERROR src/chrome/content/rules/EBay.xml: Dangling reference to CSdata1.com.xml` since that should be fixed in #13773 .

**Comment by jeremyn** [comment]
I'm reverting this change with pull request #14277 . The "dangling reference" error will break all Travis runs until https://github.com/EFForg/https-everywhere/pull/13773 is merged.

I recommend moving this intended deletion directly into https://github.com/EFForg/https-everywhere/pull/13773.

**Pull request merged**
