### PR TITLE
update mobile.de.xml

### PR DESCRIPTION
**Pull request by luciancor**
Location search function breaks on mobile.de - please see attached screenshot 

screen shot 2016-12-28 at 12 04 20

### CODE REVIEW

**Comment by luciancor** [comment]
@J0WI there is something I should do for these failing tests?

**Comment by J0WI** [comment]
Yes, please. It seems that some parts of the site now redirect to http.

**Comment by J0WI** [comment]
@luciancor are you still interested in working on this?

**Comment by jeremyn** [comment]
I'm closing this PR in favor of PR https://github.com/EFForg/https-everywhere/pull/11363 and due to lack of response from @luciancor .

**Pull request closed without merging**
