### PR TITLE
Delete ttmeiju.xml

### PR DESCRIPTION
**Pull request by ivysrono**
Does not work anymore.

### CODE REVIEW

**Comment by jeremyn** [comment]
I'm getting timeouts for all four targets https://ttmeiju.com , https://bbs.ttmeiju.com , https://ucenter.ttmeiju.com , https://www.ttmeiju.com . Is that what you're getting?

**Comment by ivysrono** [comment]
Yeah

**Comment by jeremyn** [comment]
How long has it been broken, do you know? I don't want to disable a ruleset if it's just a temporary problem, especially a `top-10k` ruleset.

**Comment by ivysrono** [comment]
How long? I'm not sure.
However, site owners have expressed his desire not to maintain.

**Comment by jeremyn** [comment]
Let's deactivate it with `default_off="All targets time out as of 2016-10-02"`. A while from now someone will see it and if everything still times out, they can delete it then. Does that sound okay?

**Comment by ivysrono** [comment]
OK.
I am outside, away from my computer for several days.
You can edit and merge it by yourself.

**Comment by jeremyn** [comment]
Reviewers aren't supposed to merge their own commits. Unless this is a rush, I'll wait for you to do it.

**Comment by ivysrono** [comment]
#7286

**Pull request closed without merging**
