### PR TITLE
peachosi.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks! Issues:

- [ ] This site is a little broken from [mixed-content blocking](https://www.eff.org/https-everywhere/rulesets#mixed-content). Do you want to mark it `platform="mixedcontent"`?
- [ ] Note https://cpanel.peachosi.com as a certificate mismatch.

**Comment by galeksandrp** [comment]
- 1 font can't load.
- Google Custom Search branding does not work.

Should we prefer security over usability or try 'compromise' `platform="mixedcontent"` way?

**Comment by jeremyn** [comment]
If your browser is maximized when visiting the site, then the mixed content blocking causes the rightmost `Download/Donate/Purchase` menu item to move down and become mostly hidden by the picture. That's too broken.

**Comment by galeksandrp** [comment]
Added `platform="mixedcontent"`

**Comment by jeremyn** [comment]
Thanks.

**Pull request merged**
