### PR TITLE
cherry-pick Acessa.xml from #4609

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Sadly the author deleted the original repo, so I can't do a real cherry-pick.

**Comment by J0WI** [comment]
Reopen to ping Travis.

**Comment by jeremyn** [comment]
Make the reason for problems in the top comment more explicit:
- [ ] https://usuarios.acessa.com (unable to connect)
- [ ] https://webmail.acessa.com (invalid certificate)
- [ ] https://aol.acessa.com (invalid certificate)
- [ ] https://estevao.acessa.com (certificate mismatch)
- [ ] https://crcmg.acessa.com (certificate mismatch)
- [ ] https://discovirtual.acessa.com (certificate mismatch)

Add to top comment:
- [ ] https://hdvirtual.acessa.com (invalid certificate)
- [ ] https://banner.acessa.com (invalid certificate)

**Comment by J0WI** [comment]
comments updated.

**Pull request merged**
