### PR TITLE
Update Expedia.xml

### PR DESCRIPTION
**Pull request by koops76**
#10782

### CODE REVIEW

**Comment by J0WI** [comment]
Looks like a false positive. The host WFM in browser, but requests by curl are dropped.

**Comment by J0WI** [comment]
Can you retry with a static resource as test url? Otherwise we need to whitelist it.

**Comment by koops76** [comment]
@J0WI I CBA to look for a URL. Sorry, look for it yourself.

**Comment by cschanaj** [comment]
Be noted that this is still `default_off`

**Comment by koops76** [comment]
@cschanaj Done.

**Pull request merged**
