### PR TITLE
added Bernina.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by fuglede** [comment]
ERROR src/chrome/content/rules/Bernina.xml: Not enough tests (0 vs 1) for <Rule from '^http://bernina-zürich\.ch/' to 'https://www.bernina-zürich.ch/'>

Looks like a charset related bug in https-everywhere-checker.

**Comment by J0WI** [comment]
Hmm, whitlelist didn't work. Is there another way?

**Comment by julianladisch** [comment]
punycode: replace bernina-zürich.ch by xn--bernina-zrich-4ob.ch

**Comment by J0WI** [comment]
This may work for our tests, but HTTPS Everywhere didn't trigger on bernina-zürich.ch then.

**Comment by J0WI** [comment]
rebased

**Comment by jeremyn** [comment]
Here's what I think the ruleset should look like. I'm describing the final state, not just changes from the most recent commit https://github.com/EFForg/https-everywhere/pull/3726/commits/144140d7ce1a41a06853d5374d2e314d949c815b, so for example I ask you to add a `target` for `^bernina.com` even though https://github.com/EFForg/https-everywhere/pull/3726/commits/144140d7ce1a41a06853d5374d2e314d949c815b already has that `target`.

Mark as `Invalid certificate`:
- [ ] https://3series.bernina.com
- [ ] https://5series.bernina.com
- [ ] https://bsr.bernina.com
- [ ] https://ca.bernina.com
- [ ] https://ch.bernina.com
- [ ] https://challenge.bernina.com
- [ ] https://de.bernina.com
- [ ] https://dk.bernina.com
- [ ] https://es.bernina.com
- [ ] https://factory.bernina.com
- [ ] https://fr.bernina.com
- [ ] https://in.bernina.com
- [ ] https://nz.bernina.com
- [ ] https://shop.bernina.com
- [ ] https://survey.bernina.com
- [ ] https://us.bernina.com
- [ ] https://bernina-chur.ch
- [ ] https://bernina-lausanne.ch
- [ ] https://bernina-lugano.ch
- [ ] https://bernina-mels.ch
- [ ] https://bernina-solothurn.ch
- [ ] https://bernina-wil.ch
- [ ] https://xn--bernina-zrich-4ob.ch
 
Add `target`:
- [ ] https://bernina.com
- [ ] https://www.bernina.com
- [ ] https://blog.bernina.com
- [ ] https://checkout.bernina.com
- [ ] https://newsletter.bernina.com
- [ ] https://registration.bernina.com
- [ ] https://service.bernina.com
- [ ] https://sm.bernina.com
- [ ] https://weallsew.bernina.com
- [ ] https://webmail.bernina.com
- [ ] https://www.bernina-chur.ch (with special rewrite `rule` from `^`)
- [ ] https://www.bernina-lausanne.ch (with special rewrite `rule` from `^`)
- [ ] https://www.bernina-lugano.ch (with special rewrite `rule` from `^`)
- [ ] https://www.bernina-mels.ch (with special rewrite `rule` from `^`)
- [ ] https://www.bernina-solothurn.ch (with special rewrite `rule` from `^`)
- [ ] https://www.bernina-wil.ch (with special rewrite `rule` from `^`)
- [ ] https://www.xn--bernina-zrich-4ob.ch (with special rewrite `rule` from `^`)
 
Mark as `Secure connection failed`:
- [ ] https://registrierung.bernina.com
- [ ] https://sk.bernina.com
 
Mark as `No working URL known`:
- [ ] https://secure.bernina.com (403)
 
Also:
- [ ] Delete https://adfs.bernina.com , I guess it's an internal Active Directory subdomain we don't need to worry about
- [ ] I don't know what `refused: www.youngfashion` is telling me. 
- [ ] Use full domain names in the top comment, which is easier to read and particularly important with multiple domains

**Comment by J0WI** [comment]
done

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/3726/commits/9c4115fe2f1955d0883b297a190fc2f81148c2f0.

I see why you added the `exclusion` for `www.bernina.com`, but we don't need it (or the `test`) for `^` because `^` 301 redirects to `www`.

Should we have a redirect from `(www\.)?bernina-zuerich.ch` to `(www\.)?bernina-zürich.ch`?

Your `adfs` `test` https://adfs.bernina.com/adfs/portal/logo/logo.png gets a `503` for HTTP. Maybe we should note this? I'm still not convinced we should include this URL at all, but we can if you really want to.

**Comment by J0WI** [comment]
Test urls are required, see https://travis-ci.org/EFForg/https-everywhere/jobs/244233730#L217
`bernina-zuerich.ch` and `bernina-zürich.ch` don't have the same content.

**Comment by jeremyn** [comment]
Oh okay, I see Travis failed on `^` so I agree we need the `exclusion` and `test` for both `^` and `www`. I wonder why it failed for `^` though, I don't see multiple redirects for `^` in the browser.

http://bernina-zuerich.ch is strange. It loads a full page borderless frame for http://www.bernina-zuerich.ch, which 301 redirects to http://www.bernina-zürich.ch , which 301 redirects to https://www.bernina-zürich.ch . In my Firefox configuration the resulting page is entirely blank due to `Load denied by X-Frame-Options: https://www.bernina-zürich.ch/ does not permit cross-origin framing.` I think this is logically a redirect even if it's implemented in this weird way, so a rewrite `rule` would be okay. What do you think?

I'm okay with listing `adfs.bernina.com` under `Different content` but could you please add https://adfs.bernina.com/adfs/portal/logo/logo.png to the comment as an example? The root URLs http://adfs.bernina.com and https://adfs.bernina.com have the same content.

**Comment by J0WI** [comment]
Okay, I added a redirect for `bernina-zuerich.ch`

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
