### PR TITLE
Create webpack.js.org.xml

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by J0WI** [comment]
How about other hosts in js.org?

**Comment by koops76** [comment]
`js.org` is a public suffix.

**Comment by J0WI** [comment]
Lookls like you can easily fetch them from here: https://github.com/js-org/dns.js.org/blob/master/cnames_active.js
HTTPS seems to be default for new hosts.

**Comment by koops76** [comment]
@J0WI Anyway, each of them should be in its own ruleset, since it's a public prefix.

**Comment by koops76** [comment]
@J0WI Merge this if you can, please.

**Comment by J0WI** [comment]
We should use the same practice as we use for `Github-Pages.xml` or `GitLab.io.xml`: wildcard with exclusions.

**Comment by koops76** [comment]
@J0WI it's a *public prefix*, bruh, just like `.com`. We can't be sure every (or most) `.js.org` domains will support HTTPS. Not all of them are powered by CloudFlare and GitHub Pages, and some of them may still not support HTTPS correctly.

**Comment by J0WI** [comment]
These are also in the [Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat):
```
github.io
githubusercontent.com
gitlab.io
```
But we maintain wildcard rules for them. In the case of `js.org` we even know which subdomains exists and which are problematic, see https://github.com/EFForg/https-everywhere/pull/11109#issuecomment-317007072.

**Comment by koops76** [comment]
@J0WI Ok, if you're going to maintain the rule and constantly add exclusions, I'll do it this way.

**Comment by J0WI** [comment]
We can automate it from https://raw.githubusercontent.com/js-org/dns.js.org/master/cnames_active.js

**Comment by koops76** [comment]
Duplicate of #11718.

**Pull request closed without merging**
