### PR TITLE
Bot housekeeping

### PR DESCRIPTION
**Pull request by strugee**
* Bump deps
* Squash a deprecation

Note that I upgraded to `probot@3` and only had time to do minimal testing. But I'm not too worried.

### CODE REVIEW

**Comment by koops76** [comment]
@strugee Why pinging me?

**Comment by strugee** [comment]
@koops76 ¯\_(ツ)_/¯ you've reviewed my PRs in the past so I figured you might want to do so again. No particular reason though.

**Comment by koops76** [comment]
@strugee I think the bot should be moved into a separate repository since it doesn't depend on HTTPSE and vice-versa.

**Comment by strugee** [comment]
@koops76 I would be fine with that; it'd make issue tracking easier as well. @Hainish requested it to go into `util/`: https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-306967722

**Comment by Hainish** [comment]
I think it's convenient to have all HTTPS Everywhere-related utilities in the same repo, for easy reference.

**Comment by koops76** [comment]
@Hainish These tools have different licenses, different authors and possibly should have different maintainers. I think it's better to move it to a separate repo and give @strugee push access to it.

**Comment by Hainish** [comment]
@koops76 

Luckily we state the different license in `LICENSE.txt`, see the relevant discussion here: https://github.com/EFForg/https-everywhere/pull/13062#issuecomment-341272152

We may want to have someone else maintain this tool if @strugee becomes unavailable.  Other tools are under `utils/` for similar reasons.

**Comment by koops76** [comment]
@Hainish Can't you add yourself and @cowlicks to collaborators too?

**Pull request merged**
