### PR TITLE
Create creationkit.com.xml

### PR DESCRIPTION
**Pull request by Folant**
#8262

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. https://creationkit.com can redirect to www.creationkit.com by itself, so you don't need a special rule for rewriting it. Please remove that and then we are ready to go.

**Comment by gloomy-ghost** [comment]
Oops, forgot to mention that a `securecookie` would be great.

**Comment by Folant** [comment]
Done.

**Comment by gloomy-ghost** [comment]
Thanks again!

**Pull request merged**
