### PR TITLE
Create ruleset: Tvp.pl

### PR DESCRIPTION
**Pull request by injust**

### CODE REVIEW

**Comment by injust** [comment]
What is the best way to have a left-wildcard target that only affects third-level domains but not fourth-level domains? i.e. hosts that match `*.tvp.pl` but not `*.*.tvp.pl`.

**Comment by Bisaloo** [comment]
> What is the best way to have a left-wildcard target that only affects third-level domains but not fourth-level domains? i.e. hosts that match *.tvp.pl but not *.*.tvp.pl.

You can use `<target host="*.example.com" />` with `<rule from="^http://([\w-]+)\.example\.com/" to="https://$1.example.com/" />`

**Comment by Bisaloo** [comment]
But I'd rather avoid wildcards unless absolutely necessary.

**Comment by injust** [comment]
> But I'd rather avoid wildcards unless absolutely necessary.

Agreed, I decided to explicitly list all targets, even though there are >100 of them, because the exclusions would have been too complex.

**Comment by zoracon** [comment]
Rounding back to these older PRs. 

Ran the build and these urls popped up in error, if you are able to get to these this week they will be on my radar to merge once addressed.

```
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://1-forum.tvp.pl/ => https://1-forum.tvp.pl/: (6, 'Could not resolve host: 1-forum.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://biznes.tvp.pl/ => https://biznes.tvp.pl/: (6, 'Could not resolve host: biznes.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://euroexpress.tvp.pl/ => https://euroexpress.tvp.pl/: (6, 'Could not resolve host: euroexpress.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://forum.tvp.pl/ => https://forum.tvp.pl/: (6, 'Could not resolve host: forum.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://mail.tvp.pl/ => https://mail.tvp.pl/: (6, 'Could not resolve host: mail.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://mojefaktury.tvp.pl/ => https://mojefaktury.tvp.pl/: (6, 'Could not resolve host: mojefaktury.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://player.tvp.pl/ => https://player.tvp.pl/: (6, 'Could not resolve host: player.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://pvr-v2.tvp.pl/ => https://pvr-v2.tvp.pl/: (6, 'Could not resolve host: pvr-v2.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Non-2xx HTTP code: http://s.tvp.pl/ (200) => https://s.tvp.pl/ (404)
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://spor.tvp.pl/ => https://spor.tvp.pl/: (6, 'Could not resolve host: spor.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://spot.tvp.pl/ => https://spot.tvp.pl/: (6, 'Could not resolve host: spot.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://szarp.tvp.pl/ => https://szarp.tvp.pl/: (6, 'Could not resolve host: szarp.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://testwiedzyekonomicznej.tvp.pl/ => https://testwiedzyekonomicznej.tvp.pl/: (6, 'Could not resolve host: testwiedzyekonomicznej.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://tvpabc.tvp.pl/ => https://tvpabc.tvp.pl/: (6, 'Could not resolve host: tvpabc.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://tvpsport.tvp.pl/ => https://tvpsport.tvp.pl/: (6, 'Could not resolve host: tvpsport.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://vop.tvp.pl/ => https://vop.tvp.pl/: (6, 'Could not resolve host: vop.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://vot.tvp.pl/ => https://vot.tvp.pl/: (6, 'Could not resolve host: vot.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://ww.tvp.pl/ => https://ww.tvp.pl/: (6, 'Could not resolve host: ww.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://ww2.tvp.pl/ => https://ww2.tvp.pl/: (6, 'Could not resolve host: ww2.tvp.pl')
ERROR src/chrome/content/rules/Tvp.pl.xml: Fetch error: http://wwwsport.tvp.pl/ => https://wwwsport.tvp.pl/: (6, 'Could not resolve host: wwwsport.tvp.pl')
INFO Finished in 336.78 seconds. Loaded rulesets: 1, URL pairs: 132.
Test URL test failed.
```

**Comment by injust** [comment]
Looks like `s.tvp.pl` alternates between HTTP `200` and `404`. Both point to the same content, so should be good to include it.

**Pull request merged**
