### PR TITLE
added rule for blog.fefe.de

### PR DESCRIPTION
**Pull request by sjjh**
the new rule is untested (but looks trivial to me).

### CODE REVIEW

**Comment by sjjh** [comment]
fixes #3510

**Comment by sjjh** [comment]
seems that someone was faster than me?

**Comment by numismatika** [comment]
Fefe.xml exists for some time now, but it was off by default for using Cacert.
You should check its domains and base your PR on that file.

**Comment by sjjh** [comment]
I'm just talking about blog.fefe.de, not about any possible other subdomains. blog.fefe.de uses a cert from Let's Enrcrypt and thus could be enabled by default.

**Comment by youdly** [comment]
Since `blog.fefe.de` is added in https://github.com/EFForg/https-everywhere/pull/3521, this PR can be closed.

**Pull request closed without merging**
