### PR TITLE
Delete UI_CDN.net.xml

### PR DESCRIPTION
**Pull request by koops76**
#10595

### CODE REVIEW

**Comment by cschanaj** [comment]
Not all of its subdomain are gone.

**Comment by koops76** [comment]
@cschanaj Which ones are up right now?

**Comment by cschanaj** [comment]
well, you can list the subdomain as described in https://github.com/EFForg/https-everywhere/pull/9955#issuecomment-302730641. (auto gen rule do not apply directly). why do you delete the forks?
```
<!--
	Non-functional hosts
		Timeout was reached:
			 - uicdn.net

		SSL peer certificate was not OK:
			 - origin.g-ha.uicdn.net
-->
<ruleset name="">
	<target host="ce1.uicdn.net" />
	<target host="ce2.uicdn.net" />
	<target host="ce3.uicdn.net" />
	<target host="ce4.uicdn.net" />
	<target host="cors.uicdn.net" />
	<target host="cu1.uicdn.net" />
	<target host="cu2.uicdn.net" />
	<target host="cu3.uicdn.net" />
	<target host="cu4.uicdn.net" />
	<target host="var.uicdn.net" />

	<rule from="^http:" to="https:" />
</ruleset>

```

**Comment by koops76** [comment]
@cschanaj #10769

**Pull request closed without merging**
