### PR TITLE
Update ruleset-whitelist.csv for rulesets without sufficient coverage

### PR DESCRIPTION
**Pull request by Bisaloo**
This was caused by commits merged from branches that didn't include the work from @cschanaj in https://github.com/EFForg/https-everywhere/pull/11998.

@gloomy-ghost, @jeremyn, @J0WI,  please aware that this may be an issue for "old" PR. When in doubt, you should probably ask for a rebase and whitelisting of the faulty ruleset.

### CODE REVIEW

**Comment by Hainish** [comment]
@Bisaloo @gloomy-ghost thanks for the quick action here.

**Comment by jeremyn** [comment]
A small problem here is `privacyintyqcroe.onion.xml` being [sorted unalphabetically](https://github.com/Bisaloo/https-everywhere/blob/a71255b7fc90d3617a4d7fe6fd5a6598752027f3/utils/ruleset-whitelist.csv#L4014) to the bottom of the list. It's not a big deal but it's something to keep in mind for later updates to the whitelist.

**Comment by Bisaloo** [comment]
> A small problem here is privacyintyqcroe.onion.xml being sorted unalphabetically to the bottom of the list. It's not a big deal but it's something to keep in mind for later updates to the whitelist.

I know but it's not an issue because the clean up script will sort domains automatically: https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-whitelist-cleanup.sh#L39

**Comment by jeremyn** [comment]
@Bisaloo When does that run?

**Comment by Bisaloo** [comment]
It's part of the release process. See for example https://github.com/EFForg/https-everywhere/pull/12959/files

**Comment by jeremyn** [comment]
@Bisaloo Oh okay, that's great. Thanks.

**Pull request merged**
