### PR TITLE
Update McAfee_SECURE.xml

### LINKED ISSUE #5036: Update McAfee_SECURE.xml
Cert not valid for domain (add to comments):
email.mcafeesecure.com
email-cio.mcafeesecure.com

Working domains:
blog.mcafeesecure.com
support.mcafeesecure.com
www.mcafeesecure.com
mcafeesecure.com

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Add support, blog
  Comment email, email-cio
  Securecookie for all
Close #5036

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Have to say that underscores are easier to read...

**Comment by jeremyn** [comment]
Please:

- [ ] Add full domain to items in top comment
- [ ] I get `Invalid certificate` for `email-cio`, not `Timeout`
- [ ] Change the ruleset `name` to `mcafeesecure.com`
- [ ] Add `target` for https://www2.mcafeesecure.com
- [ ] List each `target` as a regex for the `securecookie` `host` instead of `.+`

**Comment by jeremyn** [comment]
Also just to note, it looks like we use both `_` and `-` in our ruleset filenames. Personally I prefer `_` to represent spaces, however in this particular case using a `-` means the name now matches the name in [`Intel.xml`](https://github.com/EFForg/https-everywhere/blob/15bb7e08a70869fbb2a5d996e69048527d433813/src/chrome/content/rules/Intel.xml#L26), so I'm fine with a `-` here.

**Comment by gloomy-ghost** [comment]
www2.mcafeesecure.com is already a target

The style guide prefers dashes...

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/6980/commits/fb2a544d5ea0885d77da04f286bb40c7d1403916 , just the `securecookie` thing left.

You're right about the style guide, hm. Underscores are better -- with dashes, how can we distinguish between space and actual dashes? Anyway, what you have is fine.

**Comment by gloomy-ghost** [comment]
I've already changed the `securecookie` to original one.

**Comment by jeremyn** [comment]
Please add `support` and `www2` to the regex, like `(support\.|www\.|www2\.)` .

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
