### PR TITLE
Added myescambia.com and firehousesubs.com

### PR DESCRIPTION
**Pull request by Caboosey**
Added myescambia.com ruleset

### CODE REVIEW

**Comment by Caboosey** [comment]
Note: This website is a local government website. It ranks in the top 1m globally, but ranks in top 100k in United States.

**Comment by Caboosey** [comment]
firehousesubs.com is a top 100k site globally.

**Comment by jeremyn** [comment]
@Caboosey Are you still interested in working on this?

**Comment by Caboosey** [comment]
@jeremyn I am. I submitted changes and awaiting for it to be merged.

**Comment by jeremyn** [comment]
Great! First thing, these two rulesets seem unrelated to each other. Please create a new pull request for one of them and delete it from this pull request. Please ping me on the new pull request. I'll work with you on both, I just want to split them up to organize things better.

**Comment by jeremyn** [comment]
@Caboosey Will you be able to work on this pull request soon? If not, I would prefer to close it and note the domains you wanted to add in issue #3069, which is where we currently list domains that could use attention.

**Comment by jeremyn** [comment]
Please make the following changes to `myescambia.com.xml` and delete `firehousesubs.com.xml`:

Add `target`:
- [ ] https://aq.myescambia.com
- [ ] https://itsupport.myescambia.com
- [ ] https://pensacolabeachpass.myescambia.com
- [ ] https://www.co.escambia.fl.us
- [ ] https://cfhost.co.escambia.fl.us
- [ ] https://livelink.co.escambia.fl.us
- [ ] https://pa.co.escambia.fl.us
- [ ] https://sao1.co.escambia.fl.us

Mark as `Invalid certificate` in a top comment ([example](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71)):
- [ ] https://agenda.myescambia.com
- [ ] https://gismaps.myescambia.com
- [ ] https://inmatelookup.myescambia.com
- [ ] https://inmatevisitation.myescambia.com
- [ ] https://sitefinity.myescambia.com
- [ ] https://submittals.myescambia.com
- [ ] https://co.escambia.fl.us
- [ ] https://clerk.co.escambia.fl.us
- [ ] https://www.clerk.co.escambia.fl.us
- [ ] https://public.clerk.co.escambia.fl.us

Mark as `Redirects to HTTP` in a top comment:
- [ ] https://www.escambiaclerk.com
- [ ] https://dory.escambiaclerk.com
- [ ] https://public.escambiaclerk.com

Also:
- [ ] Delete `firehousesubs.com.xml`, which should go into another pull request
- [ ] Rename `myescambia.com.xml` to `Escambia_County_FL_US.xml`
- [ ] Change the ruleset `name` to `Escambia County, FL, US`
- [ ] Indent with one tab instead of spaces, following our [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md)

**Comment by jeremyn** [comment]
@Caboosey I'm checking in on this pull request. Are you planning on making the changes I asked for?

**Comment by Caboosey** [comment]
Someone else can make changes.

**Pull request closed without merging**
