### PR TITLE
remove nginx.org

### PR DESCRIPTION
**Pull request by nanaya1**
The only site in the rule, `trac`, doesn't actually work.

### CODE REVIEW

**Comment by reedy** [comment]
Looks like an old SSL config or something based on Chromes response: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by nanaya1** [comment]
it's like the ssl/sni is active but nothing is configured.

```
openssl s_client -connect trac.nginx.org:443 -servername trac.nginx.org
CONNECTED(00000003)
140010415498912:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

**Comment by reedy** [comment]
Do you know if it ever/recently worked?

I do agree with just deleting the whole file if it hasn't worked in a long time...

**Comment by nanaya1** [comment]
I don't remember it ever worked. I'll try contacting relevant people to see how it should be.

**Comment by nanaya1** [comment]
For reference, https is indeed not supported for that (sub)domain:

https://marc.info/?l=nginx&m=143598891015623&w=2

**Pull request merged**
