### PR TITLE
Create CookMinute.com.xml

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Bisaloo I'm not sure what's going on with the tests here. They are failing because they are timing out while downloading various unneeded dependencies. Is that why you closed/opened this a lot already?

**Comment by Bisaloo** [comment]
Yes, I was confused with the tests and I thought it was only a temporary glitch.

**Comment by jeremyn** [comment]
Maybe this PR is somehow permanently broken in Travis. Do you want to try making a new PR for the same ruleset and close this one? You can ping me on that.

**Comment by Bisaloo** [comment]
Closed in favour of #13840

**Pull request closed without merging**
