### PR TITLE
add rule for ORF.at

### PR DESCRIPTION
**Pull request by numismatika**
Work in Progress,
some "subfolders" of the websites that relink to plain can be secured.
Needs a few more exceptions therefore

### CODE REVIEW

**Comment by J0WI** [comment]
Is this still work in progress?

**Comment by numismatika** [comment]
Seems like a very small subset of fonts and files can be secured on the main sites, certificate situation didn't change yet. I would consider this best effort for the time being and finished for now

**Comment by J0WI** [comment]
Please make sure that all tests on Travis pass.

**Comment by numismatika** [comment]
Looks like the content wasn't static after all. Removed the rewrites

**Pull request merged**
