### PR TITLE
new-ruleset labeller

### PR DESCRIPTION
**Pull request by galeksandrp**
image

@Hainish

### CODE REVIEW

**Comment by J0WI** [comment]
Well, up to now I used it as a indicator that somebody already did a quick review.
But in future I may use the new review feature of GitHub.

**Comment by Hainish** [comment]
This is great, and love the graphic :smile_cat:

**Comment by galeksandrp** [comment]
@Hainish seems you need `git pull` on your cron workdir.

**Comment by Hainish** [comment]
I did - is this not working?

**Comment by Hainish** [comment]
I see this label is being misapplied a bunch...

**Comment by Hainish** [comment]
I'm going to revert the labeller to the previous known-good state until I have a better chance to look at this.

**Comment by Hainish** [comment]
It's reverted now, let me know if it is still misbehaving.

**Comment by Hainish** [comment]
@galeksandrp I'm going to revert these changes, can you re-submit this PR and I can do a proper review?

**Comment by galeksandrp** [comment]
@Hainish #9345

**Pull request merged**
