### PR TITLE
Add rheinpfalz.de (partial)

### PR DESCRIPTION
**Pull request by DavidLiedke**
Add rheinpfalz.de from #9099

### CODE REVIEW

**Comment by jeremyn** [comment]
Please sort the `target`s and indent with a single tab as described in our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md). I'll review this closer after you do that.

**Comment by DavidLiedke** [comment]
@jeremyn it is now okay?

**Comment by jeremyn** [comment]
- [ ] Remove the `target` for https://epaper.rheinpfalz.de and mark it as `Mixed content blocking` in a top comment like this:
```xml
<!--
	Mixed content blocking:
		epaper.rheinpfalz.de
  
-->
```

**Comment by DavidLiedke** [comment]
@jeremyn

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
