### PR TITLE
Update CUHK.xml

### PR DESCRIPTION
**Pull request by ipaucek4680**
Changes:
- Removed and documented non-working / non-existent hosts
- These domains seem to work fine under HTTPS:
  - `home.ie.cuhk.edu.hk`
  - `personal.ie.cuhk.edu.hk`
- Removed `default_off="failed ruleset test"`

### CODE REVIEW

**Comment by ivysrono** [comment]
https://travis-ci.org/EFForg/https-everywhere/jobs/584945966#L376
You can disable them and add comment to pass travis.

**Comment by ivysrono** [comment]
https://travis-ci.org/EFForg/https-everywhere/jobs/585120323#L374

**Comment by ipaucek4680** [comment]
@ivysrono 
I tested `https://www.lihs.cuhk.edu.hk/` just now and it connects fine. If you are also able to connect to that (sub)domain, that means this may be a Travis problem.

Should we disable that (sub)domain? Or should we ignore the error?

**Comment by ivysrono** [comment]
We should pass all tests, for example: https://github.com/EFForg/https-everywhere/pull/4849
Congratulations!

**Pull request merged**
