### PR TITLE
Update Neelwafurat.com.xml [remove mixedcontent platform]

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by J0WI** [comment]
I still get some MCB errors.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@J0WI I know but they're all images so they get loaded, I haven't been able to hit some JS script or something else that gets blocked by mixed content.

**Comment by J0WI** [comment]
I get `Blocked loading mixed active content “http://api.yamli.com/js/yamli_api.js”`

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@J0WI Thanks, closing

**Pull request closed without merging**
