### PR TITLE
Add maxdome.de

### PR DESCRIPTION
**Pull request by games647**

### CODE REVIEW

**Comment by games647** [comment]
Fixed

**Comment by jeremyn** [comment]
@games647 Are you still interested in working on this?

**Comment by games647** [comment]
yes

**Comment by jeremyn** [comment]
Great! Please make the following changes:

Mark as `Invalid certificate`:
- [ ] https://hilfe.maxdome.de
- [ ] https://static.maxdome.de

Mark as `Mixed content`:
- [ ] https://community.maxdome.de

Mark as `Redirect to HTTP`:
- [ ] https://sony.maxdome.de

Add `target`:
- [ ] https://angebote.maxdome.de
- [ ] https://bild.maxdome.de
- [ ] https://catchall.maxdome.de
- [ ] https://computerbild.maxdome.de
- [ ] https://kunde.maxdome.de
- [ ] https://live.maxdome.de
- [ ] https://prepaid.maxdome.de
- [ ] https://register.maxdome.de
- [ ] https://service.maxdome.de
- [ ] https://shopfinder.maxdome.de
- [ ] https://01.static-maxdome.de
- [ ] https://02.static-maxdome.de
- [ ] https://03.static-maxdome.de
- [ ] https://04.static-maxdome.de
- [ ] https://05.static-maxdome.de
- [ ] https://06.static-maxdome.de
- [ ] https://07.static-maxdome.de
- [ ] https://08.static-maxdome.de
- [ ] https://09.static-maxdome.de

Also:
- [ ] Move https://presse.maxdome.de from `Mismatching cert` to `Invalid certificate` and delete the empty `Mismatching cert` category
- [ ] Alphabetize the error categories in the top comment, so first `Invalid certificate`, then `Mixed content`, then `Redirect to HTTP`
- [ ] In all cases where there is a list of domains, sort them in alphabetical order starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group. For example:
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```

**Comment by games647** [comment]
Subdomains that redirects to existing rules and so aren't included in the last commit.
- bild
- catchall
- computerbild
- prepaid
- register
- service
- shopfinder
- live

**Comment by jeremyn** [comment]
Do you mean redirect to existing domains? Redirected domains are valid `target`s.

**Comment by games647** [comment]
For example: 
https://bild.maxdome.de redirects to https://www.maxdome.de
or https://live.maxdome.de redirects to http://store.maxdome.de/live (only http)

So I meant all redirect destinations are already covered.

**Comment by jeremyn** [comment]
It's still valid to have a `target` for http://bild.maxdome.de so that it is rewritten to https://bild.maxdome.de in the browser before making the request. Otherwise someone with MITM access could intercept the unencrypted HTTP request and send back a malicious response.

**Comment by games647** [comment]
Good point. I fixed that.

**Comment by jeremyn** [comment]
Great, thanks! One last thing: we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite changes in your name. Is that all right you with for this and any other pull requests you submit to us?

**Comment by games647** [comment]
Of course. I expected that.

**Comment by jeremyn** [comment]
Thanks, I just like to check in advance. Merged.

**Pull request merged**
