### PR TITLE
Update and combine Steam related rulesets

### LINKED ISSUE #15086: Steam Now HTTPS
Type: new ruleset

Domain: store.steampowered.com

Now runs over HTTPS but not by default. Steam Community already has a ruleset so maybe combine into one ruleset.

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #15086.

Valve just recently stopped redirecting https to http, as they're preparing for full https roll out. Steam community already forces https.

### CODE REVIEW

**Comment by Bisaloo** [comment]
@xPaw, why did you put `^https?` on all rules?

We are trying to get rid of HTTPS->HTTPS rewrites (#10843).

**Comment by xPaw** [comment]
Because these URLs don't serve correct certificate or content when requested over `https`. Technically nothing would break if you changed it to `^http` as these subdomains are not referenced anywhere directly.

**Comment by DXGLdotinfo** [comment]
Maybe now add a ruleset for store.steampowered.com to circumvent the requirement that users' date of birth be submitted via plaintext http?

**Comment by xPaw** [comment]
@DXGLdotinfo Does https everywhere rewrite form submissions? Because I have create a rule to redirect the entire subdomain to https.

I wouldn't rush adding other rules because Valve will be further improving their https setup.

**Comment by apaloma** [comment]
You already have some of these in your rule, but here's the full list of http -> https conversion for Steam's various CDN hosts.

These all become https://steamcdn-a.akamaihd.net/
http://media.steampowered.com/
http://cdn.akamai.steamstatic.com/
http://cdn.edgecast.steamstatic.com/

http://storefront.steampowered.com/v/gfx/ should become https://steamcdn-a.akamaihd.net/steam/

These all become https://steamcommunity-a.akamaihd.net/
http://cdn.steamcommunity.com/
http://community.akamai.steamstatic.com/
http://community.edgecast.steamstatic.com/

These all become https://steamstore-a.akamaihd.net/
http://cdn.store.steampowered.com/
http://store.akamai.steamstatic.com/
http://store.edgecast.steamstatic.com/

**Pull request merged**
