### PR TITLE
Create michelbergerhotel.com.xml

### PR DESCRIPTION
**Pull request by DavidXochipilli**
New ruleset for the website of the [Michelberger](https://michelbergerhotel.com)

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for your contribution!
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains and make sure that all ruleset tests are passing.

**Comment by J0WI** [comment]
@DavidXochipilli would you like to fix the remaining issues?

**Comment by pipboy96** [comment]
Closed by #17592.

**Comment by pipboy96** [comment]
@zoracon :ping_pong:

**Comment by pipboy96** [comment]
Duplicate of #17592, author is inactive.

**Pull request closed without merging**
