### PR TITLE
Netflix:

### PR DESCRIPTION
**Pull request by numismatika**
- disable the securecookies rule  as it breaks dvd.netflix.com

### CODE REVIEW

**Comment by numismatika** [comment]
has to be verified as the subdomain is available over https as well now

**Comment by numismatika** [comment]
#5117 could be fixed by it

**Comment by J0WI** [comment]
Please add a comment to document the issue with Cookies.

**Comment by J0WI** [comment]
rerun tests

**Comment by J0WI** [comment]
Thanks for fixing this!

**Pull request merged**
