### PR TITLE
Added apply55gx.com rule

### PR DESCRIPTION
**Pull request by Apply55gx**

### CODE REVIEW

**Comment by koops76** [comment]
Better use HSTS preloading.

**Comment by koops76** [comment]
https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere

**Comment by Apply55gx** [comment]
@koops76 I already did. Thought it would be still good to add a rule.

**Comment by koops76** [comment]
@Apply55gx OK.

**Comment by Apply55gx** [comment]
Latest Commit: Added a rule for ag.ch

**Comment by koops76** [comment]
It would be removed when it will become preloaded in all browsers.

**Comment by Apply55gx** [comment]
Oh OK

**Pull request closed without merging**
