### PR TITLE
rm Unseen.is.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=15252), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10574), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11694)

### CODE REVIEW

**Comment by jeremyn** [comment]
This domain is not currently in released stable Firefox: https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc .

**Comment by gloomy-ghost** [comment]
Update: It's in https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#10606

**Comment by gloomy-ghost** [comment]
@jeremyn Could you merge this one please?

**Comment by jeremyn** [comment]
Checklist:

- [ ] [Chromium 53.0.2785.143](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json)
- [x] [Firefox ESR 45](https://hg.mozilla.org/releases/mozilla-esr45/file/f2792b829193/security/manager/ssl/nsSTSPreloadList.inc#l14480)
- [x] [Firefox Stable 50.0.2](https://hg.mozilla.org/releases/mozilla-release/file/cc272f7d48d3/security/manager/ssl/nsSTSPreloadList.inc#l10606)
- [x] [Tor 45.5.1esr-6.0-1](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.5.1esr-6.0-1#n14480)

**Pull request merged**
