### PR TITLE
Delete 24-7-Media-clients.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
All targets gone from DNS.

### CODE REVIEW

**Comment by J0WI** [comment]
This conflicts for some reason.

**Comment by Bisaloo** [comment]
@J0WI, should I fix `24-7-Media.xml` in this PR or simply whitelist it?

**Comment by J0WI** [comment]
If it's easy to fix, your very welcome to do so. Otherwise I'm okay with whitelisting it.

**Comment by Bisaloo** [comment]
I will probably come back to it at some point because messy rulesets annoy me but I don't have the time right now.

**Pull request merged**
