### PR TITLE
[fastmail.com] Add blog subdomain, remove wildcard

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by J0WI** [comment]
I also found:
fbl.fastmail.com (mismatch)
classic.fastmail.com (works)

There are multiple non working customer subdomains on fastmail.fm and user.fm. You should leave some comments about that.

**Comment by youdly** [comment]
> There are multiple non working customer subdomains on fastmail.fm and user.fm. You should leave some comments about that.
Example?

**Comment by youdly** [comment]
Added classic subdomain, awaiting clarification on ruleset comment.

**Comment by J0WI** [comment]
>> There are multiple non working customer subdomains on fastmail.fm and user.fm. You should leave some comments about that.

> Example?

http://joewalton.fastmail.fm/
http://copyrightx.org.user.fm/

**Comment by youdly** [comment]
Updated comment.

**Pull request merged**
