### PR TITLE
Add nhentai.net

### PR DESCRIPTION
**Pull request by Balgden**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Balgden Are you still interested in working on this?

**Comment by Balgden** [comment]
Does it need any work?

**Comment by jeremyn** [comment]
Yes, there are some problems with what you have. Please:

- [ ] Make the ruleset look like this:
```xml
<!--
	Invalid certificate:
		blog.nhentai.net

-->
<ruleset name="nhentai.net">
	<target host="nhentai.net" />
	<target host="static.nhentai.net" />
		<test url="http://static.nhentai.net/robots.txt" />
	<target host="t.nhentai.net" />
		<test url="http://t.nhentai.net/galleries/1149886/4t.png" />

	<rule from="^http:" to="https:"/>
</ruleset>
```
- [ ] Change the filename to `Nhentai.net.xml`.

Also, please take a look at our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md) guide and let me know if you have any questions about the guide or the changes I've asked you to make.

**Comment by Balgden** [comment]
Updated the PR with the changes you requested and added a target for `i.nhentai.net`.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
