### PR TITLE
[Tribler.org] Update and reactivate ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**
#9842

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Invalid certificate`:
- [ ] https://dispersyreporter.tribler.org
- [ ] https://dl.tribler.org
- [ ] https://old.forum.tribler.org
- [ ] https://kayapo.tribler.org
- [ ] https://svn.tribler.org
  
Add `target`:
- [ ] https://jenkins.tribler.org

**Comment by Bisaloo** [comment]
Do you have a test url for http://dl.tribler.org? I get a test page over `http`.

**Comment by jeremyn** [comment]
I don't have a test URL other than the root page, which looks like a VMware ESXi "Welcome" page. As you know, we normally don't have test URLs for problematic domains in the top comment.

Do you think we should remove this URL entirely because it's both problematic and apparently internal?

**Comment by Bisaloo** [comment]
Yes, I think it should be removed entirely because we have no evidence it is currently used.

**Comment by jeremyn** [comment]
That's fine. Merged.

**Pull request merged**
