### PR TITLE
Add patterns to trivialize additional forms of securecookies

### PR DESCRIPTION
**Pull request by cschanaj**
For d7c053c

```bash
wget https://api.travis-ci.org/v3/job/434901070/log.txt
grep ^ERROR ~/log.txt | grep -Eo '[^/]+.xml'  | sort -u | xargs sha256sum >> ~/https-everywhere/utils/ruleset-whitelist.csv
sed -i 's/  /,1,0,0,/g' ~/https-everywhere/utils/ruleset-whitelist.csv
```

### CODE REVIEW

**Comment by cschanaj** [comment]
@Hainish would you be interested to take a look at this PR as well?

**Comment by J0WI** [comment]
Otherwise I'll just merge it before the next release. The changes in `trivialize-cookie-rules.js` are trivial.

**Comment by Hainish** [comment]
Thanks @J0WI, I'd say you can take the liberty of merging this whenever convenient.

**Comment by cschanaj** [comment]
@Hainish @zoracon @J0WI it seem that this PR missed the major release... would this get into the next ruleset release? 

P.S. fixed the merge conflict in c228bcc

**Comment by J0WI** [comment]
Sorry, I wasn't aware of the release date. I'll merge this as soon as Travis is happy.

**Comment by cschanaj** [comment]
@J0WI This PR works on `securecookie` only so I didn't entertain the `fetch-test`, do you want me to whitelist failing rulesets from `fetch-test` as well?

**Comment by J0WI** [comment]
I through it was a regression, but after a closer look nothing relevant changed since I approved this.
Thanks for working on this!

**Comment by cschanaj** [comment]
Thank you!

**Comment by Hainish** [comment]
Thanks, this will make it into this weeks ruleset release, usually made on Wednesdays.

**Pull request merged**
