### PR TITLE
[Peter_Dave_Hello.org.xml] Remove already preloaded domains

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by loveithateit** [comment]
@PeterDaveHello I've tried grepping [torbrowser's nsSTSPreloadList.inc] (https://gitweb.torproject.org/tor-browser.git/tree/security/manager/boot/src/nsSTSPreloadList.inc?h=tor-browser-38.5.0esr-5.0-2&id=4f14bbdba650ba51858e5426515a13ba39a3057c) for 'peterdavehello' and can't find anything.

**Comment by PeterDaveHello** [comment]
hmmm ... I saw it from [here](https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsSTSPreloadList.inc#2135) (reference: https://github.com/EFForg/https-everywhere/pull/3820#issuecomment-175265528), so should I wait for the deplyment until it's added into browsers?

**Comment by J0WI** [comment]
The domain has been added to Firefox 45 in December, so it will be in the Tor Browser Bundle on March.

**Comment by J0WI** [comment]
Just checked, it seems that thiis domain is already in Tor browser, the reference in SSL Labs is outdated.

**Pull request merged**
