### PR TITLE
Create keep4u.ru.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by zoracon** [comment]
```
ERROR src/chrome/content/rules/keep4u.ru.xml: Not enough tests (0 vs 1) for <Rule from '^http://www\.keep4u\.ru/' to 'https://keep4u.ru/'>

Ruleset test coverage was insufficient.
```
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#ruleset-style-guide

**Comment by pipboy96** [comment]
@TotalCaesar659 Maybe it's a good idea to rename this label to make it shorter, like `low-coverage`?

**Comment by TotalCaesar659** [comment]
@pipboy96 Is this for me? I don't know what label needs to be renamed.

**Comment by pipboy96** [comment]
@TotalCaesar659 no, sorry. I meant @zoracon.

**Pull request merged**
