### PR TITLE
Create Discordapp.com.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by J0WI** [comment]
There are some subdomains:
support
status
blog
feedmach
merch
i18n

Since this host serves a HSTS header with the `includeSubdomains` attribute you can also safely use a wildcard target.

**Comment by ekaris** [comment]
Done

**Comment by J0WI** [comment]
wildcard targets requires test urls. You can just use the targets that are already covered by the wildcards as test urls.

**Comment by ekaris** [comment]
I think is good

**Comment by J0WI** [comment]
Yes, thanks!

**Pull request merged**
