### PR TITLE
[thebluealliance.com] New ruleset

### PR DESCRIPTION
**Pull request by legoktm**

### CODE REVIEW

**Comment by fuglede** [comment]
This appears to break http://www.thebluealliance.com/gameday.

**Comment by legoktm** [comment]
Ugh, you're right. Let me do some more testing...

**Comment by fuglede** [comment]
Thanks for the update. As you can see, the integration test isn't quite happy;

    ERROR src/chrome/content/rules/Thebluealliance.com.xml: Not enough tests (0 vs 2) for <Exclusion pattern '^http://(www\.)?thebluealliance\.com/gameday$'>

    ERROR src/chrome/content/rules/Thebluealliance.com.xml: Not enough tests (0 vs 3) for <Exclusion pattern '^http://(www\.)?thebluealliance\.com/_/.*$'>

Check out [this document](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md) for more information on how to add tests to rulesets.

**Comment by legoktm** [comment]
Thanks for the pointer. Running that locally, I'm getting:
```
km@km-tp ~/p/https-everywhere> ./fetch-test.sh rules/Thebluealliance.com.xml
INFO Finished comparing http://www.thebluealliance.com/events -> https://www.thebluealliance.com/events. Rulefile: rules/Thebluealliance.com.xml.
INFO Finished comparing http://thebluealliance.com/ -> https://thebluealliance.com/. Rulefile: rules/Thebluealliance.com.xml.
INFO Finished comparing http://www.thebluealliance.com/ -> https://www.thebluealliance.com/. Rulefile: rules/Thebluealliance.com.xml.
ERROR rules/Thebluealliance.com.xml: Fetch error: http://www.thebluealliance.com/events => https://www.thebluealliance.com/events: (59, 'Unknown cipher in list: RC4-MD5:RC4-SHA:DES-CBC3-SHA:AES128-SHA:AES256-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-S')
ERROR rules/Thebluealliance.com.xml: Fetch error: http://thebluealliance.com/ => https://thebluealliance.com/: (59, 'Unknown cipher in list: RC4-MD5:RC4-SHA:DES-CBC3-SHA:AES128-SHA:AES256-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-S')
ERROR rules/Thebluealliance.com.xml: Fetch error: http://www.thebluealliance.com/ => https://www.thebluealliance.com/: (59, 'Unknown cipher in list: RC4-MD5:RC4-SHA:DES-CBC3-SHA:AES128-SHA:AES256-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-S')
INFO Finished in 0.28 seconds. Loaded rulesets: 1, URL pairs: 3.
```

Are those errors actually a problem?

**Comment by fuglede** [comment]
Thanks for checking. That looks a bit weird indeed; missing a dependency perhaps? The test runs fine here:

    $ ./fetch-test.sh rules/Thebluealliance.com.xml
    INFO Finished comparing http://www.thebluealliance.com/events -> https://www.thebluealliance.com/events. Rulefile: rules/Thebluealliance.com.xml.
    INFO Finished comparing http://thebluealliance.com/ -> https://thebluealliance.com/. Rulefile: rules/Thebluealliance.com.xml.
    INFO Finished comparing http://www.thebluealliance.com/ -> https://www.thebluealliance.com/. Rulefile: rules/Thebluealliance.com.xml.
    INFO Finished in 1.76 seconds. Loaded rulesets: 1, URL pairs: 3.

**Comment by legoktm** [comment]
Thanks! :)

**Pull request merged**
