### PR TITLE
Update ruleset: Katwarn.de

### PR DESCRIPTION
**Pull request by injust**

### CODE REVIEW

**Comment by injust** [comment]
I'm assuming that `ww.katwarn.de` is a misspelling of `www.katwarn.de` that was indexed somewhere.
Since this domain has wildcard coverage, would it be preferable to add a wildcard target instead?

**Comment by J0WI** [comment]
The wild card won't work for something like `foo.bar.katwarn.de`.

**Comment by injust** [comment]
@J0WI What's the proper regex for matching first-level wildcards?

**Comment by J0WI** [comment]
There is an example [here](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#regex-conventions), but I'm not sure if its worth to use a wildcard here.

**Comment by injust** [comment]
Right...not sure what I even used a wildcard anymore. Fixing.

**Pull request merged**
