### PR TITLE
Create GeekPark.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by J0WI** [comment]
It seems that you just redirect CDNs?
So rules for those CDNs would make more sense, to avoid duplicates.

**Comment by renyouguo** [comment]
@J0WI qiniu (seven cows) is an popular CDN in China. We can't list all the sites which are using it. No way to add rule for qiniu CDN.

**Comment by renyouguo** [comment]
@Hainish @jeremyn

**Comment by J0WI** [comment]
At least this rule should be marked as partial.
It's hard to say if the redirected CDNs will also affect other sites, so the name of the rule can be irritating.

**Comment by renyouguo** [comment]
@J0WI Long time no see，miss you much.

**Comment by J0WI** [comment]
I think I can live with test urls here.

**Pull request merged**
