### PR TITLE
Update Youku.com.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by ivysrono** [comment]
Related: #7785

**Comment by ivysrono** [comment]
@J0WI Would you review this biggest Chinese video site?

**Comment by J0WI** [comment]
Please see also:
hudong.pl.youku.com
p.comments.youku.com
ykrec.youku.com

Is this related to `ykimg.com.xml`?

**Comment by J0WI** [comment]
@Hainish I wonder why this has not been flagged as a top-* alexa rank host

**Comment by Hainish** [comment]
@J0WI looks like this was a bug, fixed in https://github.com/EFForg/https-everywhere/commit/6f28364d0f96a160d693be6136e550f6b6e32f85

**Comment by ivysrono** [comment]
@J0WI @Hainish For my opening 26 PRs https://github.com/EFForg/https-everywhere/pulls/ivysrono
only 4 of them have top-* flag.

**Comment by Hainish** [comment]
@ivysrono the next time the labeller is run, it will look back through all the open PRs and label them appropriately.

**Comment by ivysrono** [comment]
@Hainish 
There are 7/22 PRs no label.
Why?
Especially #7413 #8557 are so popular.

**Comment by Folant** [comment]
@ivysrono 
Maybe because it checks only targets (from [this](https://s3.amazonaws.com/alexa-static/top-1m.csv.zip) list) and not ruleset name. 
https://github.com/EFForg/https-everywhere/blob/6f28364d0f96a160d693be6136e550f6b6e32f85/utils/labeller/index.js#L101-L107

19624,fanli.com is not present in Fanli.com.xml
and 
1313,58.com not present in 58.com.xml

**Comment by ivysrono** [comment]
Thanks!

**Pull request merged**
