### PR TITLE
Add and update UK Police Force rules

### PR DESCRIPTION
**Pull request by tomodwyer**
Continuation of work in #4001

I've attempted to standardise the UK Police force rules and have made the following modifications...

**Added:**
- Cheshire Constabulary
- Dorset Police
- Lincolnshire Police
- Merseyside Police
- Northamptonshire Police
- Police Service of Northern Ireland

**Updated:**
- Ask The Police
- Ask the Scottish Police
- British Transport Police
- Gwent Police
- National Crime Agency CEOP
- Police Scotland
- Police UK
- South Wales Police

**Other modified:**
- GOV.UK

**Ref:** [UK Police Forces](https://www.police.uk/forces/)

### CODE REVIEW

**Comment by tomodwyer** [comment]
Anyone know how I can replicate these build errors? The tests pass on my local machine, but seem to be failing on Travis CI 😕

**Comment by jeremyn** [comment]
@tomodwyer Are you still interested in working on this?

**Comment by tomodwyer** [comment]
Ah yes, thanks for the reminder. I'll take another look at this tonight 👍

**Comment by jeremyn** [comment]
No problem.

Also, please split this pull request into much smaller ones, ideally one ruleset file per pull request. Also, please only submit one or two new ones at a time. This for example will help you improve each pull request you submit, rather than making similar mistakes in a bunch of them. And due to limited reviewers, it may take a while to get through them, so having only a couple open at a time means there's less chance of a pull request becoming out-of-date while you wait for a review.

**Comment by tomodwyer** [comment]
No worries. I'll split these into a couple of PRs and close this one.

**Pull request closed without merging**
