### PR TITLE
Delete On-web.fr.xml

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by J0WI** [comment]
Needs rebasing after #11239

**Comment by Bisaloo** [comment]
I was previously removing planet-work.com because it is preloaded but I am leaving this job to `HSTS-prune`. So this PR simply removes `On-web.fr.xml` now.

**Comment by J0WI** [comment]
But some hosts in `*.on-web.fr` support HTTPS.

**Comment by Bisaloo** [comment]
You are right, I must have overlooked that.

**Pull request closed without merging**
