### PR TITLE
[Nerdsniped] use significant parallelism for warmup IO

### PR DESCRIPTION
**Pull request by pde**
- This will let the OS disk scheduler seek efficiently

### CODE REVIEW

**Comment by pde** [comment]
@2d1 this reverts a change you made to have the build script invoked under <tt>sh</tt> rather than <tt>bash</tt>; does that matter?

**Comment by jsha** [comment]
So as long as you were getting nerdsniped, you tested the current time difference on your slow machine, right? :-)

**Comment by pde** [comment]
Of course not :)

**Comment by pde** [comment]
Build times from scratch on a laptop with slowish disk:
* no cat: 59 seconds
* one cat: 50 seconds
* many cats: 45 seconds

**Comment by pde** [comment]
But it took me 20+ minutes to determine that :\

**Comment by jsha** [comment]
According to XKCD, shaving five seconds off a daily task is worth up to two hours of work (provided a five year amortization period): https://xkcd.com/1205/. But of course HTTPS Everywhere will no longer be necessary in five years because everyone will be on HSTS.

**Pull request merged**
