### PR TITLE
Add api.ooyala.com to Ooyala.xml

### PR DESCRIPTION
**Pull request by numismatika**
- add api-subdomain

### CODE REVIEW

**Comment by jeremyn** [comment]
Do you have an example of an `api.ooyala.com` URL where the response isn't empty? It's a `200`, which is fine, but it would be nice to add a (stable) `test`.

**Comment by numismatika** [comment]
https://api.ooyala.com/docs/api_scratchpad?url=&method=GET&api_key=

**Comment by jeremyn** [comment]
Good find, but let's use https://api.ooyala.com/docs/v2/ , which I found from your example but is simpler.

Can you please change the ruleset so it has this?

```xml
	<target host="api.ooyala.com" />
		<test url="https://api.ooyala.com/docs/v2/" />
```

Otherwise this pull request is ready to merge.

**Comment by numismatika** [comment]
Coming right up, in general we should revisit all the ooyala domains and the exclusion later.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
