### PR TITLE
Add chromium/package-lock.json

### PR DESCRIPTION
**Pull request by YegorIevlev**
[`package-lock.json`](https://docs.npmjs.com/files/package-lock.json) is an important security feature of `npm` which allows to check integrity of downloaded packages to protect against repository compromise or man-in-the-middle attacks.

### CODE REVIEW

**Comment by J0WI** [comment]
On the other other hand this locks packages to a specific version without having automated (security) updates.
@Hainish what do you think?

**Comment by YegorIevlev** [comment]
@J0WI Not doing that makes package versions you get completely unpredictable, also `package-lock.json` contains SHA-512 hashes of packages, ensuring that you get correct, unmodified versions of packages.

**Comment by Hainish** [comment]
I'm fine with this, but we should also add it to `.build_exceptions`.  Once this is done I'll be ready to merge.

**Comment by Hainish** [comment]
Thank you!

**Pull request merged**
