### PR TITLE
Removed 'spamcop.net' from target hosts since this domain doesn't sen…

### LINKED ISSUE #2583: spamcop.net doesn't offer valid certificate
spamcop.net (without subdomain www) doesn't offer a valid certificate (anymore?).

### PR DESCRIPTION
**Pull request by KommX**
…d a valid vert

This should fix #2583.

### CODE REVIEW

**Comment by fuglede** [comment]
Hi @KommX. This certainly works: another solution that you'll find is quite normal is to leave in the target host but to change the rule so that it says

    <rule from="http://(www\.)?spamcom\.net/" to="https://www.spamcop.net/" />

instead. This way, the user is taken directly to the https://www version in both cases. While at the end of the day this will lead to the same thing, this does save a redirect and more importantly, all parts of the connection become secure.

**Comment by KommX** [comment]
Ok, I understand. I now did this but the Travis CI build failed and I don't understand the error message.

**Comment by fuglede** [comment]
Ah, sorry, my bad, the 'to' attribute should have been <code>^http://(www\\.)?spamcom\\.net/</code> rather than <code>http://(www\\.)?spamcom\\.net/</code> (with the extra <code>^</code>).

**Comment by KommX** [comment]
You mean the 'from' attribute, don't you?

**Comment by fuglede** [comment]
I did ...

**Comment by fuglede** [comment]
Also I wrote spamcom instead of spamcop ... :)

**Comment by semenko** [comment]
Cool -- thanks!

**Pull request merged**
