### PR TITLE
Fix BusinessInsider.xml video

### PR DESCRIPTION
**Pull request by jeremyn**
This should fix issue #5014 regarding broken video on businessinsider.com (example [here](http://www.businessinsider.com/how-plucking-nose-hairs-can-cause-lethal-infections-2016-6)). Commits 9ea45fbf452bbc49e6f97810e2b2631c9f353ff0 and 1e0802e635d9038d51320bd5b63d8b5725a0c48f fix these errors I get with `fetch-test.sh`:

```
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/account => https://www.businessinsider.com/account: Too many redirects while fetching 'https://www.businessinsider.com/account'
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/register => https://www.businessinsider.com/register: Too many redirects while fetching 'https://www.businessinsider.com/register'
ERROR rules/BusinessInsider.xml: Fetch error: http://jobs.businessinsider.com/c/ => https://businessinsider.jobamatic.com/c/: (7, 'Failed to connect to businessinsider.jobamatic.com port 443: Connection refused')
ERROR rules/BusinessInsider.xml: Fetch error: http://insider.businessinsider.com/ => https://insider.businessinsider.com/: (6, 'Could not resolve host: insider.businessinsider.com')
ERROR rules/BusinessInsider.xml: Fetch error: http://oascentral.businessinsider.com/ => https://oascentral.businessinsider.com/: (6, 'Could not resolve host: oascentral.businessinsider.com')
```

### CODE REVIEW

**Comment by J0WI** [comment]
Why did you change [this](1e0802e635d9038d51320bd5b63d8b5725a0c48f)?

**Comment by jeremyn** [comment]
Your "[this](https://github.com/EFForg/https-everywhere/pull/1e0802e635d9038d51320bd5b63d8b5725a0c48f)" link is 404ing for me. What change do you mean?

**Comment by jeremyn** [comment]
If this mean [this](https://github.com/EFForg/https-everywhere/pull/6683/commits/1e0802e635d9038d51320bd5b63d8b5725a0c48f), that change is to fix these errors:

```
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/account => https://www.businessinsider.com/account: Too many redirects while fetching 'https://www.businessinsider.com/account'
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/register => https://www.businessinsider.com/register: Too many redirects while fetching 'https://www.businessinsider.com/register'
```

**Comment by J0WI** [comment]
This means this:
https://github.com/EFForg/https-everywhere/pull/6683/commits/1e0802e635d9038d51320bd5b63d8b5725a0c48f

**Comment by jeremyn** [comment]
That's what I guessed you were referring to in [this comment](https://github.com/EFForg/https-everywhere/pull/6683#issuecomment-244246828), so my answer there applies.

**Comment by J0WI** [comment]
All right, therefore it lgtm.

**Pull request merged**
