### PR TITLE
Add "deepin.org" ruleset

### PR DESCRIPTION
**Pull request by lqf96**

### CODE REVIEW

**Comment by J0WI** [comment]
If this host is related to #4154, you should merge them or add a comment, that they are linked.
Please also include all available subdomains.

**Comment by lqf96** [comment]
Actually they are somehow related...
Deepin.org is the offical website for Deepin OS (a debian-based distribution), and it's more of non-profit and community sense, while deepin.com is the offical site of the company behind the operating system.
I'm not sure if it's proper to put them together.
Also I'm not sure whether to add other domains or not. I know that "account.deepin.org" and "api.deepin.org" supports HTTPS, but requests to these domains are already forced to go over HTTPS. So it's kind of unnecessary to do so...

**Comment by J0WI** [comment]
Okay I see...
I looked a bit at the hosts at it seems that they are not clearly separated. So I propose to create a global Deepin rule.

Since account and api are not supporting preloaded HSTS, their redirect to https could still be hijacked, so please add them as well.

Here are some more domains (you may know even more, Chinese is quite hard for me):

Works:
bbs.deepin.org
deepin.org (mistach, use www.deepin.org)
packages.deepin.org (mismatch, use packages.linuxdeepin.com)

deepin.com (mistach, use www.deepin.com)
packages.deepin.com (mismatch, use packages.linuxdeepin.com)
cdimage.deepin.com (mismatch, use cdimage.linuxdeepin.com)

packages.linuxdeepin.com
img1.linuxdeepin.com
cdimage.linuxdeepin.com


Mismatch:
wiki.deepin.org
blog.deepin.org
feedback.deepin.org

old.linuxdeepin.com
(www.)linuxdeepin.com
mantis.linuxdeepin.com
wiki.linuxdeepin.com
start.linuxdeepin.com
u.linuxdeepin.com
beta.linuxdeepin.com
mail.linuxdeepin.com

Timeout:
rsync.linuxdeepin.com

**Comment by lqf96** [comment]
OK, I'll close these two PR and create a new one...

**Pull request closed without merging**
