### PR TITLE
Always provide a default value for the chromedriver_path variable

### PR DESCRIPTION
**Pull request by Tenzer**
This implements the change discussed in #2901.

### CODE REVIEW

**Comment by TheNavigat** [comment]
LGTM

**Comment by TheNavigat** [comment]
However, can you please remove the extra empty lines? :)

**Comment by semenko** [comment]
WHooooo! Too awesome. :ribbon:  :tophat: :crown: :womans_hat: :mans_shoe: :closed_umbrella: :briefcase: :handbag: :pouch: :purse: :eyeglasses: :fishing_pole_and_fish: :coffee: :tea: :sake: :baby_bottle: :beer: :beers: :cocktail: :tropical_drink: :wine_glass: :fork_and_knife: :pizza: :hamburger: :fries: :poultry_leg: :meat_on_bone: :spaghetti: :curry: :fried_shrimp: :bento: :sushi: :fish_cake: :rice_ball: :rice_cracker: :rice: :ramen: :stew: :oden: :dango: :egg: :bread: :doughnut: :custard: :icecream:

**Comment by Tenzer** [comment]
@TheNavigat Lines 45-46 AND 75-76 or only one of the sets? I didn't add any blank lines so it's not obvious to me which ones you mean.

**Comment by TheNavigat** [comment]
Line 35, 45, and 75

**Pull request merged**
