### PR TITLE
Add Listings360.bf.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by ivysrono** [comment]
@Bisaloo

**Comment by ivysrono** [comment]
@J0WI Rename file from .bf.xml to .xml ?

**Comment by J0WI** [comment]
The file is called `Listings360.xml` :confused:

**Comment by ivysrono** [comment]
<ruleset name="Listings360">
Listings360.bf.xml

I just omitted `Listings`

**Pull request merged**
