### PR TITLE
Revert moot icon to its previous state of existence

### PR DESCRIPTION
**Pull request by fuglede**
'Moot' was removed, then partially reintroduced, in d28729967680a70d06f916176b8da1350c563227 and 3d1c38a76a359bb1580239cfb7cab75d393f26a5; along the way, its corresponding dropdown menu icon was removed even though it is actually still referenced. This simply reintroduces the icon, which in particular fixes https://github.com/EFForg/https-everywhere/issues/4082.

### CODE REVIEW

**Comment by fuglede** [comment]
Looks like #2618 is also relevant here.

**Comment by jsha** [comment]
LGTM, thanks! We do plan to re-remove 'moot' as a concept eventually, but good to fix this in the meantime.

**Comment by fuglede** [comment]
I think you might have unintentionally closed this one instead of merging it? :)

**Comment by jsha** [comment]
Whoops, sorry I missed this! Can you merge master into your branch so tests will pass?

**Comment by fuglede** [comment]
No worries; updated.

**Pull request merged**
