### PR TITLE
Create CookMinute.com.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
@jeremyn

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Change the `ruleset` `name` to `CookMinute.com`

**Comment by jeremyn** [comment]
I don't know why the tests won't pass. @gloomy-ghost @J0WI Any ideas?

**Comment by J0WI** [comment]
Nope :/

**Comment by jeremyn** [comment]
I made PR https://github.com/EFForg/https-everywhere/pull/13846 (now closed) with the same ruleset and Travis mysteriously failed there too.

**Comment by jeremyn** [comment]
If we compare the latest failed "rules" test at https://travis-ci.org/EFForg/https-everywhere/jobs/310667403 to the successful "rules" test https://travis-ci.org/EFForg/https-everywhere/jobs/310628747 in PR https://github.com/EFForg/https-everywhere/pull/13844 (just as an example), the important differences seem to be

https://travis-ci.org/EFForg/https-everywhere/jobs/310628747#L598-L607 (good)

```
+++/home/travis/build/EFForg/https-everywhere/test/travis.sh
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 4), reused 1 (delta 1), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/EFForg/https-everywhere
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> upstream-for-travis/master
Performing comprehensive coverage test.
Validation of included rulesets completed.
```

vs https://travis-ci.org/EFForg/https-everywhere/jobs/310667403#L598-L604 (bad)

```
+++/home/travis/build/EFForg/https-everywhere/test/travis.sh
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/EFForg/https-everywhere
 * branch              master     -> FETCH_HEAD
 * [new branch]        master     -> upstream-for-travis/master
Performing comprehensive coverage test.
Validation of included rulesets completed.
```

and https://travis-ci.org/EFForg/https-everywhere/jobs/310628747#L629-L631 (good)

```
Status: Downloaded newer image for node:latest
0 of 23213 files have changed (0%).
+result=0
```

vs https://travis-ci.org/EFForg/https-everywhere/jobs/310667403#L626-L629 (bad)

```
Status: Downloaded newer image for node:latest
"CookMinute.com.xml" has been modified.
1 of 23214 files have changed (0.004307745326096322%).
+result=1
```

I'm not really sure what this means.

**Comment by cschanaj** [comment]
It seemed to be a bug in [`utils/normalize-securecookie.js`](https://github.com/EFForg/https-everywhere/blob/master/utils/normalize-securecookie.js). Suppose a `securecookie` tag matched the regex defined in the source code, it will replace it with _standard one_. More specifically, a space must follow after `name=".+"`.

To fix this bug, the code should not perform trivial rewrite like this. As for this PR, the following patch can be applied. See #13847 .

```diff
-	<securecookie host=".+" name=".+"/>
+	<securecookie host=".+" name=".+" />
```

**Pull request merged**
