### PR TITLE
[Expedia.com] Update subdomains and rename ruleset

### PR DESCRIPTION
**Pull request by youdly**
Move ccTLDs to separate rulesets.

### CODE REVIEW

**Comment by youdly** [comment]
will rename `Expedia_affiliate.com.xml` to `EAN.com.xml` in a separate PR.

**Comment by youdly** [comment]
- [ ] Expedia.at.xml
- [ ] Expedia.be.xml
- [ ] Expedia.ca.xml
- [ ] Expedia.ch.xml
- [ ] Expedia.cn.xml
- [ ] Expedia.co.id.xml
- [ ] Expedia.co.in.xml
- [ ] Expedia.co.jp.xml
- [ ] Expedia.co.kr.xml
- [ ] Expedia.co.nz.xml
- [ ] Expedia.co.th.xml
- [ ] Expedia.co.uk.xml
- [ ] Expedia.com.ar.xml
- [ ] Expedia.com.au.xml
- [ ] Expedia.com.br.xml
- [ ] Expedia.com.hk.xml
- [ ] Expedia.com.my.xml
- [ ] Expedia.com.ph.xml
- [ ] Expedia.com.sg.xml
- [ ] Expedia.com.tw.xml
- [ ] Expedia.com.vn.xml
- [ ] Expedia.de.xml
- [ ] Expedia.dk.xml
- [ ] Expedia.es.xml
- [ ] Expedia.fi.xml
- [ ] Expedia.fr.xml
- [ ] Expedia.ie.xml
- [ ] Expedia.it.xml
- [ ] Expedia.mx.xml
- [ ] Expedia.nl.xml
- [ ] Expedia.no.xml
- [ ] Expedia.se.xml
- [ ] EAN.com.xml
- [ ] travel-assets.com.xml
- [ ] trvl-media.com.xml
- [ ] trvl-px.com.xml

**Comment by youdly** [comment]
Temporarily removed `Expedia.co.uk.xml` to make way for the ruleset's PR. Reference will be re-added in that PR.

**Comment by youdly** [comment]
Removed non-functional subdomains

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
