### PR TITLE
Added rules for bundeswehr.de.

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by jeremyn** [comment]
Delete entirely:
- [ ] https://ipz.bwb.bundeswehr.de (times out with both HTTPS and plain HTTP)
- [ ] https://statistik.treff.bundeswehr.de (times out with both HTTPS and plain HTTP)
- [ ] https://community.bundeswehr.de (gone from DNS)

Mark as `Rejected`:
- [ ] https://www.hns.bundeswehr.de
- [ ] https://www.ieb.bundeswehr.de
- [ ] https://www.iudbw.bundeswehr.de
- [ ] https://www.lkdo-nw.skb.bundeswehr.de
- [ ] https://www.logistikzentrum.bundeswehr.de
- [ ] https://www.mad.bundeswehr.de
- [ ] https://www.militaermusik.bundeswehr.de
- [ ] https://www.planungsamt.bundeswehr.de
- [ ] https://www.sanitaetsdienst.bundeswehr.de
- [ ] https://www.sdbw.bundeswehr.de
- [ ] https://www.sozialdienst.bundeswehr.de
- [ ] https://www.sportschule.bundeswehr.de
- [ ] https://www.streitkraefteamt.bundeswehr.de
- [ ] https://www.streitkraefteunterstuetzungskommando.bundeswehr.de
- [ ] https://www.untrgcentre.bundeswehr.de
- [ ] https://www.wachbataillon.bundeswehr.de
- [ ] https://www.zinfoabw.bundeswehr.de

Mark as `Invalid certificate`:
- [ ] https://www.kinderbetreuung.bundeswehr.de

Add `test`:
- [ ] http://statistik.bundeswehr.de/robots.txt
- [ ] http://treff.bundeswehr.de/robots.txt

Also:
- [ ] Change the `ruleset` `name` to `Bundeswehr.de`
- [ ] Change the filename to `Bundeswehr.de`

Optionally:

You can link together all the Bundeswehr rulesets with this ruleset as primary, so add something like:
```
	Other Bundeswehr rulesets:
		BundeswehrEntdecken.de.xml
		Bundeswehr-Karriere.de.xml
		BundeswehrKarriere.de.xml
```
and add/change the reference in those files to point here.

Also, for most of the domains I asked you to add to the top comment, and for some of your domains you have there already, the `^` version redirects to the `www` version of the URL. I don't think we need both versions in a comment. In this case you can delete:

* http://eka.militaerseelsorge.bundeswehr.de
* http://kmba.militaerseelsorge.bundeswehr.de

Please add a comment when you are done making changes, so I know if you're going to make the optional changes or not.

**Comment by Jochen-A-Fuerbacher** [comment]
I made the optional changes. However I didn't delete the `^` versions in the comments, but grouped them with the `www` versions to a regex style: `(www.)?`

**Comment by jeremyn** [comment]
Okay, that's all fine.

It looks like the certificate for https://treff.bundeswehr.de just recently expired. Let's remove the `target` (and `test`) for `treff` and move it to `Invalid certificate`. If/when they fix the certificate for `treff` -- and I suppose they will, since they have a redirect from http://treff.bundeswehr.de to the `https` URL -- we can add it back as a `target` then.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
