### PR TITLE
Create a Pridewatch.tw.xml rules

### PR DESCRIPTION
**Pull request by ymhuang0808**
Add a new rules for lightup.pridewatch.tw

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please see:

- [ ] There are a number of minor problems with the ruleset as you submitted it. I've rewritten it below. Please review my changes and if you agree with them, change the ruleset to match and I'll accept it.
```xml
<!--
	HTTP 525:
		- pridewatch.tw
		- www.pridewatch.tw

-->
<ruleset name="Pridewatch.tw (partial)">
	<target host="lightup.pridewatch.tw" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by jeremyn** [comment]
Thanks, this looks fine now. Before I merge it though, what are you asking with:

> By the way, does the ruleset also include the domain status?

I don't understand that question, sorry.

**Comment by ymhuang0808** [comment]
Sorry for my poor English. 

I found that there is a comment in the ruleset file. It seems like that the HTTP response status from the host. Therefore, I would like to know if there is a convention for adding the host/domain status in the ruleset file. 

Thanks.

On 2017年1月26日 下午11:56:42 [台北], Jeremy Nation <notifications@github.com> wrote:
>Thanks, this looks fine now. Before I merge it though, what are you
>asking with:
>
>> By the way, does the ruleset also include the domain status?
>
>I don't understand that question, sorry.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/pull/8231#issuecomment-275425648

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeremyn** [comment]
No problem. The `HTTP 525` comment for `pridewatch.tw` and `www.pridewatch.tw` just lets other people who look at this ruleset later know why we didn't include those domains. You can see this in other rulesets too, for example [here](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71). There are different ways of noting these domains but yes, it is a convention.

I hope that answers your question. Is it okay if I merge the pull request now?

**Comment by ymhuang0808** [comment]
Thanks for youe clear explanation.
Sure, please merge the pull request.

On 2017年1月28日 上午12:39:04 [台北], Jeremy Nation <notifications@github.com> wrote:
>No problem. The `HTTP 525` comment for `pridewatch.tw` and
>`www.pridewatch.tw` just lets other people who look at this ruleset
>later know why we didn't include those domains. You can see this in
>other rulesets too, for example
>[here](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71).
>There are different ways of noting these domains but yes, it is a
>convention.
>
>I hope that answers your question. Is it okay if I merge the pull
>request now?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/pull/8231#issuecomment-275710572

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
