### PR TITLE
rm With_Google.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=323), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#11154), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n12338)

### CODE REVIEW

**Comment by jeremyn** [comment]
The preload lists only cover `withgoogle.com`, but not `*.withgoogle.com`, at least not `rework.withgoogle.com`, so this rule is at least partially valid.

**Comment by J0WI** [comment]
This host sends no preload header an refers to GoogleServices.xml

**Comment by jeremyn** [comment]
See pull request #7081 for a discussion on the `preload` header. I agree the `GoogleServices.xml` reference should be removed.

**Comment by jeremyn** [comment]
See also issue #7126 .

**Comment by jeremyn** [comment]
https://withgoogle.com has no `Strict-Transport-Security` header at all.

**Pull request merged**
