### PR TITLE
Emphasize temporary exceptions in EASE mode, fix #18970

### LINKED ISSUE #11203: Remove right-wildcard targets (if possible)
**This issue might take a long long long time to complete since a rewrite is not always possible.**

Using a modified command from https://github.com/EFForg/https-everywhere/pull/11187#issuecomment-315766782
```bash
egrep -l '<target\s+host=\s*"[^"]*\.\*"\s*/>' *.xml
```

- [x] EBay.xml
- [x] Eventim.xml #10948 
- [x] GoogleImages.xml (e8bb995071c473f4cb30596f42dcaf0a9b523d3a)
- [x] GoogleMaps.xml (30ac44802700ac9c964d53e447e99a75c181e60e)
- [x] GoogleShopping.xml (4c82624193b46e9079067124ced78d1e66713cf7) 
- [ ] Google.tld_Subdomains.xml
- [x] GoogleVideos.xml
- [ ] Google.xml
- [x] Live-Nation.xml (#14255)
- [x] Ticketmaster.xml (#19215)
- [x] Wyndham.xml #12672
- [x] All-Inkl.xml #11054 
- [x] Bytename.xml #11242 
- [x] Capital-One-Connect.xml #11237 
- [x] Directbox.xml #11246 
- [x] EKomi.xml #11302 
- [x] F5-mismatches.xml #12519 
- [x] Foresters.xml #11205 
- [x] GlobalSign.xml #11201 
- [x] GymGlish.xml, GymGlish-problematic.xml #11278 
- [x] ~HSBC.xml~ (does not use a right-wildcard)
- [x] Jako-O.xml #11248 
- [x] KickNews.xml #11202 
- [x] Kimberly-Clark.xml #11249 
- [x] Krisostomus.xml #11056 ~#11200~
- [x] LoveFilm.xml #11207 
- [x] Nokia.xml #11285 
- [x] Nordea.xml #11250 
- [x] Planet-Work.xml #11239
- [x] Red_Bull.xml #11852 
- [x] Rochesterhomepage.net.xml #11551 
- [x] SamKnows.xml #11206 
- [x] Servage.net.xml #11245 
- [x] ShopStyle.xml, ShopStyle-mismatches.xml #12521
- [x] Siemens.com.xml #11451 
- [x] SimFlight-problematic.xml #12616 
- [x] STRATO.xml #11279 
- [x] Thumbshots.xml #11765 
- [x] Tickengo.xml #11204 
- [x] Trusted-Shops.xml #12522 
- [x] UltraDNS.xml #11241 
- [x] World_of_Warplanes.xml #11055 
- [x] World_of_Warships.xml #11057

### LINKED ISSUE #18970: Emphasize temporary exceptions over permanent ones.
Type: feature request

**Current State**
The left button is used to deactivate HTTPS permanently for this page.
Current state of Buttons

**Requested State**
Make the temporary option the default option.

**Recommended list of available solutions**
- make a radio button option beneath the disable HTTPS button, (for this session only, default)
- make a checkbox (default, checked!) beneath the button, saying "for this session only"
- switch the order of the buttons for disabling HTTPS 'permanently' vs 'per session'

**Related history**
- issue #17217
- issue #10041

**Visual preview to allow for easy decision making**
- make a radio button option beneath the disable HTTPS button, (for this session only, default)
Button with radio option

- make a checkbox (default, checked!) beneath the button, saying "for this session only"
Button with checkbox

- switch the order of the buttons for disabling HTTPS 'permanently' vs 'per session'
Button reordered

### LINKED ISSUE #19825: Warning screen actions improvements
Type: feature request
On http warning screen, make allow session action primary and hide allow permanent action by default.

### PR DESCRIPTION
**Pull request by cschanaj**
Fixes #18970 Fixes #19825 

This PR emphasize temporary exceptions in EASE mode as requested in #18970 and #19825. See below for a preview of the new cancel page. 

I have included bootstrap as a new dependency because I believe that a responsive UI will be much more user-friendly. By using a CSS framework throughout the project will also add consistency to the extension design. As FF83 introduces the HTTPS-Only Mode, I am inclined to think HTTPSE should shift the focus to mobile browsers where the security features are less extensive as compared to their Desktop alternatives. A responsive UI could be the first step to attract the mobile users to try HTTPS Everywhere. 

Only the bootstrap CSS are included at the moment. Feel free to close this if it is not desirable to include a third-party framework/ it conflicts with the extension redesign planning. Thanks.

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring existing code
- [ ] New Ruleset
- [ ] Existing Ruleset

## For Rulesets: Testing

- [ ] Travis CI completed without errors (triggered upon pull request)

## Existing Contributors
If you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`.

### CODE REVIEW

**Comment by zoracon** [comment]
I will cross check this with our internal design team, to check for consistency and feedback.

I like this approach, however I would like to refrain from Bootstrap and utilize native CSS frameworks like CSS Grid and Flexbox, which is supported in all major browsers.

**Comment by zoracon** [comment]
Update: Internal review pending

**Comment by zoracon** [comment]
## Feedback from EFF Design

> "Hi there, thanks for submitting this issue!
> Our design team uses the following considerations when thinking about design changes. That said,
> 
> While we may not go with Bootstrap specifically, you make a great point regarding making the page responsive, and we're talking about how we can factor a responsive grid into our page designs going forward.
> 
> Separate styling for the URL:http://___ is a good suggestion. We might go with a different monospaced typeface choice, such as VeraMono, which we use on Certbot.eff.org for strings.
> 
> Different styling for the "Copy URL" button is a good suggestion, and we like how you stacked it (though we might bump up the button size to be a bit more uniform). To meet color contrast standards, we might suggest adding a border to the button, or upping the contrast in a different manner, since the present light grey is hard to distinguish from the white background.
> 
> The wording that you suggest for the buttons is an improvement, and we really appreciate your contributions on that. We quite like "Proceed anyway (unsafe)" and "Disable for this site", and are recommending making that change. The change for "Proceed anyway (unsafe)" to being the only one red is a nice change as well.
> 
> Thanks again for your contribution!"

For the typeface and Grid CSS, and other feedback I can submit a commit adding to this PR. It will then go under review again. I know this process is new in our repo, but trying to normalize for future design contributions this so thank you for your patience!

**Comment by cschanaj** [comment]
Thank you @zoracon and EFF design teams for the quick and useful response. I agree that using native Grid CSS and a typeface which align with EFF overall design guidelines are great idea. Please feel free to add more commits to my PR and ping me anytime for testing. 

When I created this PR and I was also looking into modifying the extension option page. We have notably different design/ themed UI elements, e.g. buttons in the extension popup, option and cancel pages. It would be great if EFF design team could provide a master CSS/ SCSS file which we can follow and use consistently across this project.

**Comment by zoracon** [comment]
@cschanaj A master file is a great suggestion and I will definitely discuss this with our design people. Coordination with design hasn't always been stable but I am doing my best to integrate better design guidance for this project.

**Comment by zoracon** [comment]
I have new commit in with adjustments. Had to commit some groundwork for CSS files and global variables.

I have below what it looks like now with suggestions from EFF Design and @cschanaj 

EFF is going on holiday soon, so won't be able to get the proper sign off until after the holidays (Dec. 24-January 3)

Desktop:
image

Tablet:
image

Mobile:
image

**Comment by cschanaj** [comment]
@zoracon they looks great to me. thank you so much for the excellent work!

**Comment by pipboy96** [comment]
@zoracon It would be better if a "Go back" button was added, and the other actions were less emphasized than "Go back" (see default browser error pages for example).

**Comment by zoracon** [comment]
> @zoracon It would be better if a "Back to safety" button was added, and the other actions were less emphasized than "Back to safety" (see default browser error pages for example).

@pipboy96 I can run that by UX review for an added workflow, for now we can get these changes in.

**Comment by zoracon** [comment]
Pushed in a final round of minor edits and will merge soon

**Comment by zoracon** [comment]
Just adding the last round's feedback for context

>Thanks for sending that ticket and asking me about the designs. Just checked in with the design team :slightly_smiling_face:

>Overall, we approve of the changes! We had a few suggestions (ranging from easy changes to something that might require more work) if it’s helpful.

>Easier change:
>We’d like to increase the white space between the logo and text above. Image included for reference around general breathing room.

>Easier change:
> We thought the URL still gets a little lost. We wanted to suggest a way to differentiate the http://badssl.com text from the rest of the text. A suggestion was to use `#666666` grey (a11y compliant at a large size of 14pt), and to bold the monospaced font.
..
>We like the way the buttons stack on tablet and mobile, but thought the 3 buttons on desktop look a little awkward. We were wondering about moving the “copy URL” button logo to the right of the link. (It could even be an icon instead of a button.)

**Review by zoracon — APPROVED** [review]

**Comment by cschanaj** [comment]
Thank you!!

**Pull request merged**
