### PR TITLE
Create KOOORA.com.xml

### PR DESCRIPTION
**Pull request by 6u621jpq6ybdw**

### CODE REVIEW

**Comment by J0WI** [comment]
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by 6u621jpq6ybdw** [comment]
@J0WI I used the iterative Google search method but I didn't any other subdomains that I didn't mention, do you have anyone in mind?

**Comment by J0WI** [comment]
See also:
```
o.kooora.com

kooora.ws
www.kooora.ws
ktv.kooora.ws

**Comment by 6u621jpq6ybdw** [comment]
@J0WI Added.

**Pull request merged**
