### PR TITLE
[Agol.dk] Remove https rewrite

### PR DESCRIPTION
**Pull request by Bisaloo**
#10843

### CODE REVIEW

**Comment by Bisaloo** [comment]
@J0WI, FYI, we don't get notifications when you add tags. Conflicts would probably be solved faster if you could simply ping us as well.

**Comment by J0WI** [comment]
Ok, I'll try to ping you in future. Btw: you should prefer rebaseing over merge commits in the case of a conflict.

**Comment by Bisaloo** [comment]
> Btw: you should prefer rebaseing over merge commits in the case of a conflict.

Is there a technical reason for this? Or is it simply to avoid merge commits?

I usually work on Github for simple cases so I also solve conflicts via the web interface when possible. I only fetch, rebase and force push when it's too complicated.

**Comment by J0WI** [comment]
It's simply to avoid merge commits, because they blow up the repo. But I'm not sure if this is still the case after I squashed your commits.

**Pull request merged**
