### PR TITLE
[KeywordDiscovery.com] Simplify and reactivate ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
I'm not sure why the tests are failing here.

**Comment by jeremyn** [comment]
- [ ] Add a `target` for https://api.keyworddiscovery.com and delete it from the top comment. Optionally add a `test` for http://api.keyworddiscovery.com/cgi-bin/addme/free.cgi though this isn't really needed because the root URL returns a `200` even though the page is blank.
- [ ] Change the `ruleset` `name` to `KeywordDiscovery.com`.
- [ ] Delete the `securecookie` or limit its `host` to `target` subdomains other than `^`.
- [ ] Update the [filename reference](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Trellian.xml#L6) in `Trellian.xml`.

**Comment by jeremyn** [comment]
You can just delete the `bid` `rule` [here](https://github.com/Bisaloo/https-everywhere/blob/f094cb54f57c4266c2ca853c48546e39146dec35/src/chrome/content/rules/Trellian.xml#L33-L34) from `Trellian.xml` if you want, to pass Travis.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
