### PR TITLE
Update OpenBSD.org.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by massoc** [comment]
**Update/Alteration Announcement (HTTPS Everywhere Change Needed) for OpenBSD.org subdomains**

Hi,

The TLS certificate for www.openbsd.org has been updated to include these new fields:
"Subject Alternative Name=
DNS Name=ftp.openbsd.org
DNS Name=libressl.org
DNS Name=openbsd.org
DNS Name=openssh.com
DNS Name=www.libressl.org
DNS Name=www.openbsd.org
DNS Name=www.openssh.com
"

My testing (with curl --tlsv1.2 $site, and https://$site in chrome 54.0.2840.59, and https://$site in firefox 49.0.1 ) has confirmed that HTTPS is working for:
https://openbsd.org (301 moved permanently to www.openbsd.org)
https://ftp.openbsd.org/
https://libressl.org/ (301 moved permanently to www.libressl.org)
https://openssh.com (301 moved permanently to www.openssh.com)
https://www.libressl.org
https://www.openbsd.org/
https://www.openssh.com/

curl --tlsv1.2 $site works fine for the above domains and receives the 301 redirect over TLS on the aforementioned domains.



Could the HTTPS Everywhere ruleset please be updated to reflect the New Domains enabled for TLS by the OpenBSD Project?

For example, in the current ruleset at https://www.eff.org/https-everywhere/atlas/domains/openbsd.org.html it mentions:
"Nonfunctional hosts in *openbsd.org
ftp, ftp.eu, ftp2.eu, &c, man"

**ftp.openbsd.org has been updated to support TLS.**
ftp.eu, ftp2.eu, man, cvsweb, are still not responding via TLS.

firmware and portroach are still problematic subdomains.



Thank You for the Superb HTTPS Everywhere Project =)

**Comment by mnordhoff** [comment]
#7377 #7378 #7379

**Comment by J0WI** [comment]
Thanks for the updates!

**Comment by massoc** [comment]
Ruleset Update for OpenBSD.org subdomains


New subdomains for *openbsd.org have been enabled for TLS.

Testing was conducted on all the domains below using:
	curl --tlsv1.2 $site 
	https://$site in firefox 52.0.2
	https://$site in chrome 57.0.2987.133

All the subdomains below work fine via TLS:
	https://ftp.OpenBSD.org
	https://ftp.fr.openbsd.org
	https://ftp.eu.openbsd.org
	https://ftp3.usa.openbsd.org/pub/
	https://ftp4.usa.openbsd.org/pub/
	https://ftp5.usa.openbsd.org/pub/
	https://cvsweb.openbsd.org
	https://ftp.usa.openbsd.org/pub/
	https://portroach.openbsd.org/

Note: ftp*.usa. show 403 at the / root of the webserver, which is irrelevant as everything is fine under the /pub/ subdirectory.

I attached a pull request with the changes added to the OpenBSD.org.xml file, pull request = #9453

**Pull request merged**
