### PR TITLE
Create imgmini.eastday.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by fuglede** [comment]
Looks good to me, but could you rename the ruleset and file to `eastday.com`? (Unless there's a good reason for specifying the subdomain.)

**Comment by renyouguo** [comment]
@fuglede No match for other *eastday.com sites.

**Comment by fuglede** [comment]
Still, then it would be better to add a comment in `Eastday.com.xml` with notes on the errors that appear in the other eastday.com subdomains. This makes it a bit easier to find the right ruleset file if changes need to be imposed later on.

**Comment by fuglede** [comment]
Thanks. 👍

**Pull request merged**
