### PR TITLE
Added swebus.se

### PR DESCRIPTION
**Pull request by Foorack**
This pull request partially resolves issue #3069

### CODE REVIEW

**Comment by smw-koops** [comment]
You forgot <target host="fia.swebus.se" />.

**Comment by gloomy-ghost** [comment]
Thanks. 

I'm getting `403` for 
- [ ] swebooktest.swebus.se
- [ ] wstest2.swebus.se
- [ ] wwwtest.swebus.se

`503` for
- [ ] mobil.swebus.se
- [ ] ws.swebus.se
- [ ] wstest.swebus.se

Could you provide any valid tests?

Also:
- [ ] Note `^` as `ERR_RESPONSE_HEADERS_TRUNCATED` and redirect it to `www`
- [ ] Either delete the securecookie or specifically list the subdomains it covers aside from swebus.se

**Comment by Foorack** [comment]
@gloomy-ghost 

- The domains mentioned returning 403 and 503 have been commented out due to no tests available.
- `^`  now redirects to `www`, added a comment on why.
- Spaces have been replaced with tabs.
- Secure-cookie deleted.

**Comment by gloomy-ghost** [comment]
Thanks, I've updated the checklist through a79d5a2

**Comment by Foorack** [comment]
Waiting a few days with this issue. It seems like they will be doing some maintenance today and tomorrow.

**Comment by gloomy-ghost** [comment]
@Foorack Hi, are you still interested to do the further changes?

**Comment by Foorack** [comment]
@gloomy-ghost No I'm not. At least not at the moment. Closing this and other pull requests I have.

**Pull request closed without merging**
