### PR TITLE
Create strana.ua.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please:

- [ ] Use tabs instead of spaces.
- [ ] Redirect `http://amp.strana.ua/` to `https://strana.ua/`
- [ ] Add a securecookie tag between the targets and rule: `<securecookie host=".+" name=".+" />`

**Comment by gloomy-ghost** [comment]
Thanks, you will need to add a target for `amp` before add a rule for it. Also please include slash in the rule.

**Comment by Folant** [comment]
Done, thank you.

**Comment by gloomy-ghost** [comment]
Merged, thanks again.

**Pull request merged**
