### PR TITLE
Remove redundant rulesets with hsts-prune.

### PR DESCRIPTION
**Pull request by bardiharborow**
The following domains fully meet the [guideline for removal of HSTS preloaded properties](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#hsts-preloaded-rules):

```
*.express-vpn.com
*.ivpn.net
*.namepros.com
www.amazon.ca
*.peirong.me
*.reaganlibrary.gov
```

### CODE REVIEW

**Comment by koops76** [comment]
Maybe separate this pull request into one pull request per removed ruleset?

**Comment by bardiharborow** [comment]
Closing in favor of #10915, #10918, #10920 and #10921. Leaving Amazon as is, as it's a manual preload that is only for `www` and given the general instability of their domain affairs in general, it might be better to leave untouched until the next iteration. I now have a nice little git alias called `nukepreload` that allows me to quickly queue up individual PRs for this stuff.

**Comment by bardiharborow** [comment]
Also, out of curiousity I disabled header checks on hsts-prune and [generated a branch](https://github.com/bardiharborow/https-everywhere/tree/all-preloaded-domains) with all the preloaded domains that are currently failing header checks removed.

**Comment by Zenexer** [comment]
I'm in charge of HSTS for `*.namepros.com`; I'm also an active HTTPS Everywhere user.  Will this require any changes on our end to maintain the same level of security?

**Comment by koops76** [comment]
@Zenexer No, if your domain is already preloaded you don't need to do anything.

**Pull request closed without merging**
