### PR TITLE
[Phpdoc] Activate ruleset [DNM]

### PR DESCRIPTION
**Pull request by rugk**
Continuing https://github.com/EFForg/https-everywhere/pull/3184

Preparing ruleset for the change of phpdoc to @letsencrypt [they announced](https://twitter.com/phpDocumentor/status/677591475354476544). You can merge this once they have switched.

### CODE REVIEW

**Comment by J0WI** [comment]
Hopefully they will also fix their subdomains:
- demo
- manual
- pear

**Comment by rugk** [comment]
Yes, [I reminded them](https://twitter.com/rugkme/status/677977363515351040).

**Comment by rugk** [comment]
BTW interesting that Travis CI does not fail. Should not it fail currently as the domain is using self-signed certs?

**Comment by fuglede** [comment]
@rugk: The Travis tests don't do any testing against the actual web servers; it only checks local stuff. (#3107 is relevant here.)

**Comment by rugk** [comment]
Ah okay. Thanks for the information.

**Comment by semenko** [comment]
Closing this given their continued breakage & self-signing. Please reopen if they get a real set of certs.

**Comment by rugk** [comment]
[I've got](https://twitter.com/phpDocumentor/status/703269428968947714) it. They now use real certs.
Can you please reopen this PR? I've already adjusted the ruleset.

**Comment by rugk** [comment]
Nice, this was fast.

**Pull request merged**
