### PR TITLE
Update to PR 836

### PR DESCRIPTION
**Pull request by numismatika**
#836 is outdated, i added a few more

### CODE REVIEW

**Comment by jsha** [comment]
Please update this as necessary to pass tests.

We'll be more likely to have time to review this if you break it into smaller chunks.

**Comment by donced** [comment]
why not commit to different branch for each ruleset instead of everything in `rule_lab` branch? you might have functional ruleset. The build error prevents those functional rulesets from being merged.

**Comment by numismatika** [comment]
@donced this one wass open from before the point where i managed to get the travis check active on my fork as well. I left it open back then to get the rulesets checked by 
the script on a regular basis.
I do work on my "test branch" aka rule_lab and then cherry pick and sqash commits to small pull-request branches once i feel they work well enough

**Comment by donced** [comment]
Alright, I thought you were using EFForg's travis check (instead of personal's) because I've seen a few users just create PR without doing their own testing. My apology for misunderstood you.

**Comment by semenko** [comment]
Whoops, didn't mean to close this one. It replaces #836

**Comment by semenko** [comment]
Actually looks like numismatika closed this above -- kinda unclear on github. Sorry for the spew!

**Comment by numismatika** [comment]
@semenko it was closed in between when i reset the branch and forced the push back to github.
I haven't noticed any issue with the pages included in here for a while. Therefore i still would appreciate a merge or at least a note about what prevents it. It might have the same problem like #1928 with stuff that is outdated by now :)

**Comment by semenko** [comment]
Of course! Here's why this PR isn't great:
- It's a huge PR touching lots of files, making it harder to review. Smaller PRs are friendlier :)
- There are a ton of commits & merges in here, which is weird and hard to review
- You touch a lot of unrelated code in chromium/, etc. that seems erroneous
- (If it's not erroneous, those commits should be a separate PR)
- This didn't catch the Travis automated tests (there's no green checkbox by your code), so this requires more careful review.

A cleaner way to do this is to make lots of PRs for

**Comment by semenko** [comment]
It might help to look at the merged / closed PRs -- especially the awesome work by @J0WI https://github.com/EFForg/https-everywhere/pulls?q=is%3Apr+is%3Aclosed+author%3AJ0WI

Things like this are super easy & fast to review and merge: #2815 #2800

More complex rulesets should also be their own PR, like #2651

**Pull request closed without merging**
