### PR TITLE
Anaxago.com rules file

### PR DESCRIPTION
**Pull request by patheticcockroach**
Rules for Anaxago.com

### CODE REVIEW

**Comment by J0WI** [comment]
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains to increase the coverage of this ruleset.

**Comment by jeremyn** [comment]
@patheticcockroach Are you still interested in working on this pull request?

**Comment by patheticcockroach** [comment]
No, I didn't understand J0WI's comment, and anyway the site in question now automatically redirects all non-HTTPS requests to the HTTPS version, so the rule is now useless

**Comment by jeremyn** [comment]
@patheticcockroach Of course you are welcome to close your PR if you want, however `*.anaxago.com` is still a valid set of domains because there is an initial request with unencrypted HTTP. See https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages. Generally any domain is valid for HTTPS Everywhere unless the domain is HSTS preloaded ( https://hstspreload.org ).

**Pull request closed without merging**
