### PR TITLE
rm BitMEX.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1640), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#1178), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n1299)

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by J0WI** [comment]
This host does not send the preload header.

**Comment by jeremyn** [comment]
My response is [here](https://github.com/EFForg/https-everywhere/pull/7081#issuecomment-249433391).  Going forward I'll check for the `preload` header until we've come to some decision. Feel free to revert this change if you want.

**Comment by jeremyn** [comment]
See also issue #7126 . I'm going to stop reviewing these `preload` deletions until we've settled on the policy.

**Pull request merged**
