### PR TITLE
add rule for Stadtwerke München

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
You missed some subdomains:
planauskunft.swm.de
issibn.swm.de

Mismatch:
portal.muenchen.swm.de
bg.muenchen.swm.de
lhm.muenchen.swm.de
branchenbuch.muenchen.swm.de
orte.muenchen.swm.de
s[0-4].muenchen.swm.de

**Comment by numismatika** [comment]
Who cares about mismatched domains as comments?
The important thing is that domains that work get rewritten.

**Comment by J0WI** [comment]
It makes it much easier to maintain all the rules.

**Comment by numismatika** [comment]
@J0WI added a couple more domains and the comments you suggested.

**Comment by J0WI** [comment]
Please do not remove your previous commits in future, so we can just review the corrections.

**Pull request merged**
