### PR TITLE
Remove wildcards from Live-Nation.xml

### PR DESCRIPTION
**Pull request by cschanaj**
Ref: http://www.livenationentertainment.com/content/js/angular/controllers/views/data/oomapdata.js

### CODE REVIEW

**Comment by jeremyn** [comment]
As in for example PR https://github.com/EFForg/https-everywhere/pull/10948, this ruleset would be better broken out into domain-specific files as such `LiveNation.ae.xml` etc.

**Comment by cschanaj** [comment]
@jeremyn Travis is passing now, would you please merge this?

**Comment by jeremyn** [comment]
@cschanaj Please note that my earlier comment should not have been understood as me taking ownership of this pull request, or I would have assigned this to myself at the time.

However, here is my review:

`LiveNation.ae.xml`:

This is okay.

`LiveNation.asia.xml`:

This is okay.

`LiveNation.be.xml`:

- [ ] Add a `target` for https://fr.livenation.be
- [ ] Add a `target` for https://nl.livenation.be

`LiveNation.co.jp.xml`:

This is okay.

`LiveNation.co.uk.xml`:

- [ ] Mark https://media.livenation.co.uk as `SSL peer certificate was not OK`

`LiveNation.com.au.xml`:

This is okay.

`LiveNation.com.xml`:

- [ ] Remove the `target` and `rule` for `^`, because `^` times out with both `https` and `http`
- [ ] Remove https://ads.livenation.com entirely, because it times out with both `https` and `http`
- [ ] Add a `target` for https://concerts.livenation.com and remove it from the top comment
- [ ] Add a `test` for https://assets.livenation.com
- [ ] Add a `test` for https://media.livenation.com

`LiveNation.cz.xml`:

This is okay.

`LiveNation.de.xml`:

This is okay.

`LiveNation.dk.xml`:

This is okay.

`LiveNation.es.xml`:

This is okay.

`LiveNation.fi.xml`:

This is okay.

`LiveNation.fr.xml`:

This is okay.

`LiveNation.hu.xml`:

This is okay.
 
`LiveNation.it.xml`:

This is okay.

`LiveNation.kr.xml`:

This is okay.

`LiveNation.nl.xml`:

This is okay.

`LiveNation.no.xml`:

This is okay.

`LiveNation.pl.xml`:

This is okay.

`LiveNation.se.xml`:

This is okay.

`LiveNationEntertainment.com.xml`:

- [ ] Delete this file entirely, and the reference in `LiveNation.com.xml`, because we don't need to create a new `default_off` `ruleset`

`LiveNationInternational.com.xml`:

- [ ] Delete https://lincs.livenationinternational.com entirely, it looks internal and times out with  `https`
- [ ] Add a `test` for https://media.livenationinternational.com
- [ ] Add `(partial)` to the `ruleset` `name`

Also:
- [ ] Update the references in `GETMEIN.com.xml`, `Ticketmaster.xml`, and `TicketsNow.xml`
- [ ] Remove the `Live-Nation.xml` entry from `utils/ruleset-whitelist.csv`

**Comment by cschanaj** [comment]
@jeremyn done.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/14255/commits/f645b475a8e10b0e9477d74f2d1da6de30d4bfcb and modified the list for `LiveNation.com.xml`.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/14255/commits/3b351e8ac35ba0bccc9d13e40f3414f960c9d6ce. Note that, for example, the ruleset as of https://github.com/EFForg/https-everywhere/commit/3b351e8ac35ba0bccc9d13e40f3414f960c9d6ce will send https://concerts.livenation.com/citi into a redirect loop.

**Comment by jeremyn** [comment]
Also, as a side comment, `Secure connection redirects to plaintext:` is not a good description for redirecting to HTTP. This -- https://raw.githubusercontent.com/EFForg/https-everywhere/master/README.md -- is an example of a plaintext response, which is unrelated to whether the protocol is `http` or `https`. However we use `Secure connection redirects to plaintext:` in other rulesets, so we can keep it here for consistency.

**Comment by cschanaj** [comment]
@jeremyn thanks!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
