### PR TITLE
Create LocalWiki.org.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
`www.` and `ja.` do also exist

**Comment by jeremyn** [comment]
@davidabian Are you still interested in working on this?

**Comment by jeremyn** [comment]
Great! Please do the following and that should be it:

- [ ] Add a `target` for https://es.localwiki.org
- [ ] In all cases where there is a list of domains, sort them in alphabetical order starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group. For example:
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```
In this case, it's just the four `target`s, which should be in this order: `^localwiki.org`, `www`, `es`, `ja`.

**Comment by davidabian** [comment]
Done. Thanks!

**Comment by jeremyn** [comment]
Thanks, this looks fine.

One more thing: we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) rulesets, which means we combine and rewrite commits in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by davidabian** [comment]
Of course, @jeremyn, all right!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
