### PR TITLE
add rule for PopCash.net

### PR DESCRIPTION
**Pull request by numismatika**
PopUnder Advertiser , nevertheless it should be secured.

### CODE REVIEW

**Comment by J0WI** [comment]
I got several mixed content warnings.
And you should add ```tb.popcash.net``` too.

**Comment by numismatika** [comment]
Yea they are embedding googleapis on their main page (active mixed content) and pictures (passive mixed content), it is a browser problem with the detection of mixed content.

**Comment by J0WI** [comment]
Sadly most users won't notice that and interpret the rule/Add-On as broken.
We have ```platform="mixedcontent"``` for such cases.

**Comment by J0WI** [comment]
mixed content problems seems to be fixed.

**Pull request merged**
