### PR TITLE
Update Twitch.tv

### PR DESCRIPTION
**Pull request by ekaris**
Twitch.tv now works

### CODE REVIEW

**Comment by J0WI** [comment]
You missed a bunch of domains:
secure.twitch.tv
help.twitch.tv
discuss.dev.twitch.tv
passport.twitch.tv (not yet preloaded)
player.twitch.tv
api.twitch.tv
pubsub-edge.twitch.tv
pubster.twitch.tv
spade.twitch.tv
web-cdn.ttvnw.net
tmi.twitch.tv
main-ws.tmi.twitch.tv
darklaunch.tmi.twitch.tv
chatdepot.twitch.tv
streams.twitch.tv
chatdepot.twitch.tv
minixperiment.twitch.tv
client-event-reporter.twitch.tv
main-ws.tmi.twitch.tv

justin.tv
www.justin.tv
www-cdn.jtvnw.net
static-cdn.jtvnw.net
secure.justin.tv
s.jtvnw.net

Mismatch:
blog.twitch.tv
dev.twitch.tv

Timeout;
cs.twitch.tv

Refused:
link.twitch.tv
science.twitch.tv


You should add comments for non-working hosts for future maintenance.
Also note, that most *.justin.tv domains are deprecated.

**Comment by ekaris** [comment]
Done, @J0WI could you remove main-ws.tmi.twitch.tv from other rules because it is in conflict with mine now.

**Comment by J0WI** [comment]
You should do this yourself, that the PR passes the tests.
Just edit the file in your own branch and commit.

**Comment by ekaris** [comment]
Search doesn’t return anything, can you tell me the name of the files?

**Comment by J0WI** [comment]
Ah, the target is listed twice in you ruleset.

Note that the deprecated justin hosts are still in use and needs to be redirected.

**Comment by ekaris** [comment]
Done

**Comment by J0WI** [comment]
Thanks!

**Comment by AnAkkk** [comment]
This was actually also missing *.hls.ttvnw.net which is used for their HTML5/HLS player.

**Comment by J0WI** [comment]
@AnAkkk could you please open a follow-up PR?

**Pull request merged**
