### PR TITLE
Update Smzdm.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@J0WI This is urgent, please check it as soon as possible.

**Comment by J0WI** [comment]
Sadly, I don't have much time today, maybe @fuglede, @loveithateit or @Hainish could catch this before next release.

**Comment by J0WI** [comment]
I finally had some time to look at it.
There is some mixed passive content on zhiyou, but that's trivial.
Thanks for updating!

**Comment by renyouguo** [comment]
@J0WI Thanks.
If you have time, please check my 30+ PRs : Pull Requests · EFForg/https-everywhere
https://github.com/EFForg/https-everywhere/pulls/renyouguo
The oldest is pulled at 14 may.

**Comment by J0WI** [comment]
@renyouguo most of them do not cover enough subdomains, it would be great if you could have a look on them again.

**Pull request merged**
