### PR TITLE
Added edu.turku.fi

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by jeremyn** [comment]
@theel0ja Are you still interested in working on this?

**Comment by theel0ja** [comment]
@jeremyn Yes.

**Comment by jeremyn** [comment]
Can you please expand the ruleset to cover `turku.fi` in general, not just `edu.turku.fi`?

**Comment by jeremyn** [comment]
@theel0ja I'm checking in on this pull request. Are you planning on adding more `turku.fi` subdomains as I requested?

**Comment by jeremyn** [comment]
I'm unassigning myself from this due to lack of response from @theel0ja .

**Comment by jeremyn** [comment]
I'm closing this due to no response.

**Pull request closed without merging**
