### PR TITLE
getbootstrap.com

### PR DESCRIPTION
**Pull request by galeksandrp**
Fix https://trac.torproject.org/projects/tor/ticket/19396

### CODE REVIEW

**Comment by J0WI** [comment]
Please also leave a comment in the rule about the issue there.

**Comment by galeksandrp** [comment]
Added.

**Comment by fuglede** [comment]
The site appears to work fine for me, and in particular I did not notice any redirect loops. Are there any specific steps to reproduce?

**Comment by jeremyn** [comment]
@fuglede The torproject bug labels it specifically for Chrome. I can't reproduce it on Firefox, and I can't test it on Chrome because of the #5874 .

**Comment by jeremyn** [comment]
Now that there's a fix/workaround for #5874 , I can confirm that https://themes.getbootstrap.com/products/dashboard loops in Chrome but not Firefox.

**Comment by jeremyn** [comment]
- [ ] Update the `securecookie` [here](https://github.com/galeksandrp/https-everywhere/blob/c2f1dc875be3b0cfb8a67dd4d6996729fb6893c0/src/chrome/content/rules/Getbootstrap.com.xml#L17) to remove `themes\.|`. Otherwise what can happen is that a secure cookie is set at, for example, https://themes.getbootstrap.com but then can't be read at http://themes.getbootstrap.com/products/dashboard .

**Comment by galeksandrp** [comment]
Updated.

**Comment by J0WI** [comment]
I wonder why this works in Firefox, because of the
```
  <!-- sad hack because github pages doesn't support https -->
  <script>
     if (window.location.protocol == "https:") window.location.protocol = "http:"
  </script>
```
Console shows
```
NS_ERROR_UNEXPECTED:   dashboard:6
	<anonymous> https://themes.getbootstrap.com/products/dashboard:6:48
```

**Comment by jeremyn** [comment]
@J0WI I didn't dig into too much but it looks like this is a thing with Firefox, see [here](https://stackoverflow.com/questions/4723213/detect-http-or-https-then-force-https-in-javascript/10036029#10036029) and [here](https://stackoverflow.com/questions/34218769/set-window-location-protocol-in-different-browsers) for example.

**Comment by fuglede** [comment]
I contacted the webmasters regarding the issue.

**Comment by fuglede** [comment]
And here's their response:

> We appreciate you letting us know – it's an unfortunate necessity. Basically the way Shopify works it required us to force just the product pages to be insecure to iFrame our content in without issue
in some situations. It wasn't our favorite either, but was the only surefire way to solve the issue without basically getting Shopify to accept a feature request. That said, every other page is
secure, so we figured we could deal with the inconvenience.

**Pull request merged**
