### PR TITLE
update migros.xml to redirect ^ and www

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
There are a lot of missing `*.migros.ch` subdomains, and I see you added https://cdn.migros.ch and https://image.migros.ch. Do you want to add the rest? [Here](https://www.google.com/search?q=site%3A*.migros.ch&ie=utf-8&oe=utf-8#q=site:*.migros.ch+-site:www.migros.ch+-site:100ideen.migros.ch+-site:cdn.migros.ch+-site:filialen.migros.ch+-site:image.migros.ch+-site:migros-service.migros.ch+-site:theke.migros.ch+-site:shop.m-budget.migros.ch+-site:produits.migros.ch+-site:valflora.migros.ch+-site:photoservice.migros.ch+-site:aha.migros.ch+-site:jobs.migros.ch+-site:selection.migros.ch+-site:gmz75.migros.ch+-site:famigros.migros.ch+-site:momente.migros.ch+-site:newsroom.migros.ch+-site:kaffee.migros.ch+-site:faq.migros.ch+-site:prodotti.migros.ch+-site:report.migros.ch+-site:weidebeef.migros.ch+-site:sommer.migros.ch+-site:farmmania.migros.ch+-site:farmchips.migros.ch+-site:annasbest.migros.ch+-site:minimania.migros.ch+-site:avsb.migros.ch+-site:produkte.migros.ch+-site:migipedia.migros.ch) is the maximum Google search.

**Comment by J0WI** [comment]
Thanks, I tried to catch them.

**Comment by J0WI** [comment]
tests fixed.

**Comment by jeremyn** [comment]
This is a lot, please double-check it.

`Mixed content`:
- [ ] https://migros-shop.de
- [ ] https://www.migros-shop.de

`Mismatch`:
- [ ] https://banane.migros.ch
- [ ] https://captormania.migros.ch and remove from `HTTP redirect`
- [ ] https://sommer.cloud.migros.ch
- [ ] https://facebook.migros.ch
- [ ] https://minimania.migros.ch
- [ ] https://photoservice.migros.ch
- [ ] https://blog.bancamigros.ch
- [ ] https://p2p.bancamigros.ch
- [ ] https://blog.banquemigros.ch
- [ ] https://p2p.banquemigros.ch
- [ ] https://doit-garden-migros.ch
- [ ] https://www.doit-garden-migros.ch
- [ ] https://nl.doit-garden-migros.ch
- [ ] https://micasa.ch
- [ ] https://myhome.micasa.ch
- [ ] https://news.migrosmagazin.ch

`Invalid certificate`:
- [ ] https://cloud.migros.ch
- [ ] https://www.cloud.migros.ch

`Refused`:
- [ ] https://aha.migros.ch

`Incomplete cert chain`:
- [ ] https://newsroom.migros.ch

`Redirect to HTTP`:
- [ ] https://generation-m.migros.ch
- [ ] https://sell.m-budget.migros.ch
- [ ] https://www.micasa.ch

Add target:
- [ ] https://chinoise.migros.ch
- [ ] https://famigros.migros.ch
- [ ] https://faq.migros.ch
- [ ] https://kundenrat.gmaare.migros.ch
- [ ] https://gmz75.migros.ch
- [ ] https://jobs.migros.ch
- [ ] https://kaffee.migros.ch
- [ ] https://cockpit.m-budget.migros.ch
- [ ] https://guenstig.m-budget.migros.ch
- [ ] https://occasion.m-budget.migros.ch
- [ ] https://selfcare.m-budget.migros.ch
- [ ] https://momente.migros.ch
- [ ] https://prodotti.migros.ch
- [ ] https://produits.migros.ch
- [ ] https://selection.migros.ch
- [ ] https://valflora.migros.ch
- [ ] https://wartung.migros.ch
- [ ] https://web-api.migros.ch
- [ ] https://www.migipedia.ch
- [ ] https://cdn1.micasa.ch
- [ ] https://cdn2.micasa.ch
- [ ] https://cdn3.micasa.ch
- [ ] https://cdn4.micasa.ch
- [ ] https://banking.migrosbank.ch
- [ ] https://blog.migrosbank.ch
- [ ] https://boerse.migrosbank.ch
- [ ] https://lieferanten.migrosbank.ch
- [ ] https://onlinesupport.migrosbank.ch
- [ ] https://secure.migrosbank.ch
- [ ] https://standorte.migrosbank.ch
- [ ] https://stats.migrosbank.ch
- [ ] https://www.banquemigros.ch
- [ ] https://www.bancamigros.ch

Also:
- [ ] Remove rewrite rule for http://brueckenbauer.ch , domain doesn't exist (`www` does, though)
- [ ] Remove rewrite rule for http://m-fanshop.ch , not needed
- [ ] Add rewrite from `http://bancamigros\.ch/` to `https://www.migrosbank.ch/it/`
- [ ] Add rewrite from `http://banquemigros\.ch/` to `https://www.migrosbank.ch/fr/`
- [ ] Add rewrite from `http://migipedia\.ch/` to `https://www.migipedia.ch/`

**Comment by J0WI** [comment]
There are much more shops that belongs to this company. I will add them/spilt them off in further PRs.

**Comment by jeremyn** [comment]
Do you mean split them off into different files but keep them in this pull request?

**Comment by J0WI** [comment]
Yes, like I already did with `migros-bank.xml` in this PR

**Comment by jeremyn** [comment]
Okay that's fine. Please let me know when you're done and it's ready for review.

**Comment by J0WI** [comment]
I'm done with `migros.ch` here.
Other hosts will follow in future PRs and likely in different files.

**Comment by jeremyn** [comment]
I've updated the list through commit 88827ba44ebd40d1691bfa1817ca5cb304c1c014. I did not check any new changes you added that weren't in my list, for example the change to `hotelplan.xml` or anything related to `*.leshop.ch`, unless I comment on it below.

[This comment](https://github.com/J0WI/https-everywhere/blob/88827ba44ebd40d1691bfa1817ca5cb304c1c014/src/chrome/content/rules/migros.xml#L50) should have `migros` and not `igros`.

You have `Mirgos` instead of `Migros` in two comments.

https://www.migros-shop.de/newsletter (for example) has significant mixed content blocking, so `(www.)?migros-shop.de` shouldn't be a target and the rewrite rule should be removed. Also, https://migros-shop.de should be under `Mismatch` too, which I've added to the list.

I don't get a mismatch for https://www.banquemigros.ch or https://www.bancamigros.ch , just `^`. Also you could rewrite `^` to `www`, though the redirect chain for the site itself doesn't go through `www`, so it's questionable whether we should do that ourselves.

**Comment by J0WI** [comment]
Feedback addressed and tests passed.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
