### PR TITLE
add Mermaid Kat Shop rules

### PR DESCRIPTION
**Pull request by fabianfrz**
looks like everything is OK.

probably low priority

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your pull requests but you don't need to note them as "low priority" :smiley:

**Comment by jeremyn** [comment]
Also, please take a look at our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md). You've made some basic but understandable mistakes, for example you don't need to include `test`s for the simple case, and your subdomains aren't sorted correctly.

Please keep trying though! And let us know if you have any questions.

**Comment by fabianfrz** [comment]
Hi @jeremyn, I removed the tests and it seems like I don't know how to handle a dash. It is in before the characters in the code to I have sorted this host to the top. The tool sort ignores it. How should they be handled?

**Comment by jeremyn** [comment]
[ASCII](https://en.wikipedia.org/wiki/ASCII) sorting is fine, so a dash sorts before letters.

**Comment by jeremyn** [comment]
@fabianfrz Are you still interested in working on this pull request?

**Comment by fabianfrz** [comment]
as far as I know there is no change required

**Comment by jeremyn** [comment]
This would be better as four different rulesets, one for each domain covering the root URL (`^`) and `www`. You can submit them together in this same PR.

**Comment by jeremyn** [comment]
For example, filename `Mermaid-kat-shop.de.xml`, file contents:

```xml
<ruleset name="mermaid-kat-shop.de">
	<target host="mermaid-kat-shop.de" />
	<target host="www.mermaid-kat-shop.de" />

	<rule from="^http:" to="https:" />
</ruleset>
```

and so on.

**Comment by jeremyn** [comment]
The rulesets look fine, however these domains are obviously related, and in that case we sometimes like to link them to one another. So:

- [ ] Add this as a comment at the top of `Mermaidtailaustralia.com.au.xml` (it looks like the store is based in Australia, so we'll make that the "primary" ruleset):
```xml
<!--
	For other Mermaid Kat Shop coverage, see:
		Mermaid-kat-shop.de.xml
		Mermaidkatshop.co.uk.xml
		Mermaidkatshop.com.xml

-->
```

- [ ] Add this as a comment at the top of the other three files:
```xml
<!--
	For other Mermaid Kat Shop coverage, see Mermaidtailaustralia.com.au.xml

-->
```

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
