### PR TITLE
Show the grey icon for whitelisted sites with a port number 

### LINKED ISSUE #19293: Icon does not reflect some site are whitelisted
Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

# Steps to reproduce:

1. Install HTTPS Everywhere version 2019.11.7 and disable automatic updates.
2. Turn on Ease mode, visit `http://www.pettigrew.lib.nc.us:8080/`
3. After being redirected to the HTTPS Everywhere warning page, choose "Open insecure page" 
4. HTTPSE redirects user to HTTP version of the webpage 

# Observations:

Icon remained to show the EASE mode (the red icon).

# Expected:

Icon show that HTTPS Everywhere is disabled (the grey icon).

### PR DESCRIPTION
**Pull request by cschanaj**
The general rule is that 1) use `url.hostname` when we are dealing with the rulesets. 2) use `url.host` when we are dealing with the whitelists. 

### List related issues if any

- closes #19293

### CODE REVIEW

**Comment by zoracon** [comment]
Will pull this down soon and review this week.

**Comment by cschanaj** [comment]
@zoracon I have rebased the branch and fixed the loop back. Would you mind to try again?

**Comment by zoracon** [comment]
Sorry this fell off the radar a bit, can you path the conflict and I can review again before the next release?

**Review by zoracon — APPROVED** [review]
Seems to check out in testing back and forth for a few days. Merging

**Pull request merged**
