### PR TITLE
Add rule for piquadro.com

### PR DESCRIPTION
**Pull request by Liudvikam**
[Piquadro.com](https://piquadro.com) fails to redirect to HTTPS despite supporting it.

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for your contribution!

Sadly https is not supported on all subdomains. Could you also add comments for the non working ones?
Mismatch on corporategift.piquadro.com
Timeout on cdnlevel3.piquadro.com

**Comment by Liudvikam** [comment]
Okay, sure. Commit coming up.

**Comment by J0WI** [comment]
We use to write comments above the rule. Otherwise lgtm.

**Comment by Liudvikam** [comment]
Okay. Done.

**Comment by fuglede** [comment]
I'm seeing some mixed content issues: If one types "test" in the search bar, no product images appear on HTTPS, yet they do on the insecure version of the site.

**Comment by Liudvikam** [comment]
> I'm seeing some mixed content issues: If one types "test" in the search bar, no product images appear on HTTPS, yet they do on the insecure version of the site.

Hmm, you're right. I'll go ahead and make the rule off by default then.

**Comment by semenko** [comment]
Gonna merge because travis is confused, but, in general, I'm not a huge fan of default_off rules (they just add clutter).

**Pull request merged**
