### PR TITLE
Add Not Always ruleset

### PR DESCRIPTION
**Pull request by VoidPhantom**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also add (www.)notalwayshopeless.com?

**Comment by VoidPhantom** [comment]
Is that the new one? Right now it seems to be an empty look-alike of Not Always Learning.

**Comment by J0WI** [comment]
I don't know, I just found that domain and it seems to be related and working.

**Comment by VoidPhantom** [comment]
Alright, so this now clearly states that Not Always Hopeless is a new Not Always website that is going to launch on March 18. I figured it’s OK to add it to this ruleset, so here goes.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
