### PR TITLE
Update Bitly Branded Short Domain list

### PR DESCRIPTION
**Pull request by SeanOC**
This is a periodic update to the list of Branded Short Domains powered by Bitly with current HTTPS support. (The list was last updated in #5611)

It's expected that there is some natural churn on this list due to domains being added or removed from the Bitly platform, or SSL certificates becoming available or unavailable for a given domain.

Methodology:

This is the list of domains on the Bitly platform that were verified with valid DNS settings that point to Bitly in the last 12 hours, and for which Bitly has a valid SSL certificate with >20 days remaining. (20 days is important as our current threshold for renewing LetsEncrypt certificates is 21 days.)

The ruleset directory was checked for potential duplicates via the https-everywhere test suite and 3 were removed.

cc: @jsha @Hainish and #11439

### CODE REVIEW

**Comment by SeanOC** [comment]
Yup, removed duplicate domains below:

```
go.dmoruzzi.com
s.nikkei.com
st.aastocks.com
```

As far as I can tell, these users each submitted their own domains directly.

**Comment by SeanOC** [comment]
Huh, looks like the tests timed out on Travis CI.

I haven't run the specific number of added vs removed domains but it shouldn't be anything super massive (a few hundred, maybe 1k).

Any guidance or recommendations on further changes I can make to the update to get things to play nice would be greatly appreciated.

**Comment by Hainish** [comment]
@SeanOC this is expected, as Travis has a limited timeout.  I can test this manually.  Please note that some of the domains included in this PR is already in the HSTS preload list, see the `preload` test.  Please remove the following:

```bash
Removing go.nien.co from Bitly_branded_short_domains.xml
Removing go.danny.fm from Bitly_branded_short_domains.xml
Removing get.seolib.org from Bitly_branded_short_domains.xml
Removing goto.yombo.net from Bitly_branded_short_domains.xml
Removing l.alyoung.com from Bitly_branded_short_domains.xml
Removing d.jahner.xyz from Bitly_branded_short_domains.xml
Removing u.tinkertry.com from Bitly_branded_short_domains.xml
Removing u.nil.gs from Bitly_branded_short_domains.xml
Removing eco.citrusui.me from Bitly_branded_short_domains.xml
Removing go.dwtm.ch from Bitly_branded_short_domains.xml
Removing s.ocg-card.com from Bitly_branded_short_domains.xml
Removing s.jan-cermak.cz from Bitly_branded_short_domains.xml
Removing on.g1.ie from Bitly_branded_short_domains.xml
Removing short.nassi.me from Bitly_branded_short_domains.xml
Removing bl.skimming.net from Bitly_branded_short_domains.xml
Removing s.robi-net.it from Bitly_branded_short_domains.xml
Removing l.tallcraft.com from Bitly_branded_short_domains.xml
Removing b.thebimhub.com from Bitly_branded_short_domains.xml
Removing jump.tarsan.cz from Bitly_branded_short_domains.xml
```

Thanks so much for this PR!

**Comment by cschanaj** [comment]
thank you very much!! this PR should close #11679 and close #11439

**Pull request merged**
