### PR TITLE
Add rule for Danish bank Danske Bank

### PR DESCRIPTION
**Pull request by kimsey0**

### CODE REVIEW

**Comment by J0WI** [comment]
You may add other subdomains:
https://app.danskebank.dk/
https://business.danskebank.dk/
https://business2.danskebank.dk/
https://danskeanalyse.danskebank.dk/
https://mobil.danskebank.dk/
https://netbank.danskebank.dk/
https://netbank2.danskebank.dk/
https://online.danskebank.dk/
https://www-2.danskebank.dk/

Broken:
https://cem.danskebank.dk/
https://www.cem.danskebank.dk/
https://insights.danskebank.dk/
https://foreninger.danskebank.dk/

**Comment by kimsey0** [comment]
I've added those of the suggested domains that responded. I've also added cem.danskebank.dk www.cem.danskebank.dk, since they seem to be working fine over HTTPS, even though they redirect to cem.danskebank.com. I have not added any international domains, since I don't want to affect international Danske Bank customers negatively and haven't tested the international domains properly.

**Comment by J0WI** [comment]
You should add comments for the other domains, for further work on this rule.

**Comment by kimsey0** [comment]
I don't understand. What should those comments say? Are per-domain comments required before merging?

**Comment by J0WI** [comment]
Like in this rule: https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Rl0.ru.xml
commenting which domains doens't work and why.

**Comment by kimsey0** [comment]
Sure. I have added a comment for the two domains that are not available over HTTPS. app.danskebank.dk isn't available over either HTTP or HTTPS, and I haven't been able to find any links to it, so I haven't added that. (Honestly, I'm not sure how you dug it up.

**Comment by J0WI** [comment]
e.g. https://app.danskebank.dk/da-dk/

**Comment by J0WI** [comment]
LGTM (cc @fuglede)

**Pull request merged**
