### PR TITLE
Create Backdrift.org.xml

### PR DESCRIPTION
**Pull request by christianheinrichs**

### CODE REVIEW

**Comment by christianheinrichs** [comment]
According to the Travis CI build at https://travis-ci.org/EFForg/https-everywhere/jobs/269904180#L620 there are "not enough tests".

Help on how to fix this would be appreciated

**Comment by J0WI** [comment]
Can you please add a comment here and in `Backpack.tf.xml` to show the relationship between those files?

**Comment by christianheinrichs** [comment]
@J0WI Sorry for getting so late back to you, but what exactly do you mean? AFAIK, there is no relation between `backdrift.org` and `backpack.tf`.

**Comment by J0WI** [comment]
Oh okay, I don't know why I thought there is a relation.

**Pull request merged**
