### PR TITLE
Quotes

### PR DESCRIPTION
**Pull request by koops76**
ping @Hainish, @cowlicks.

### CODE REVIEW

**Comment by cowlicks** [comment]
I do prefer single quotes, but I think enforcing it like this is too pedantic.

**Comment by koops76** [comment]
@cowlicks Consistency is very important. Reopen this please and tell what changes, if any should be done. I am against keeping random quotes.

@Hainish Do you think we should keep the quotes as they are?

**Comment by koops76** [comment]
Ah, there are too many conflicts. This may not be reopened.

**Comment by koops76** [comment]
This PR is not urgent, do not reopen please.

**Comment by cowlicks** [comment]
@koops76 my comments here are basically the same as #12559 

Some folks prefer `"` some prefer `'`. Forcing folks to use either `"` or `'` will give us some consistency about something that is fairly arbitrary, at the expense of annoying devs.

Personally, if I were making a pull request to an OSS project, I'd be pretty annoyed if the tests failed because I used the wrong kind of quotes that are essentially interchangable.

**Comment by koops76** [comment]
@cowlicks There is such a thing as coding style. Requiring consistent code style for all code in the repository is not something crazy, or uncommon.

**Comment by Hainish** [comment]
@koops76 there's also a balance to strike between enforcing style and allowing flexibility.  If the enforcement of style is too strict, it discourages participation for a benefit which is at best spurious.

**Comment by koops76** [comment]
@Hainish This config is very flexible. It allows exceptions like `"'"` and allows to use template literals.
```json
{
  "quotes": ["error", "single", {
    "avoidEscape": true,
    "allowTemplateLiterals": true
  }]
}
```

**Comment by koops76** [comment]
We are going to adopt StandardJS or another style guide someday.

**Pull request closed without merging**
