### PR TITLE
Re-enabling OpenSignal.com.xml

### PR DESCRIPTION
**Pull request by Giltyhub2**
(I didn't check if there are other subdomains)

### CODE REVIEW

**Comment by pipboy96** [comment]
Please check these subdomains:

```
opensignal.com
www.opensignal.com
assets.opensignal.com
data-api.opensignal.com
data-api-prod.opensignal.com
data-api-stag.opensignal.com
engineering.opensignal.com
meteor.opensignal.com
meteor-stag.opensignal.com
opensignal-api.opensignal.com
opensignal-api-stag.opensignal.com
opensignal-web-prod.opensignal.com
solutions.opensignal.com
solutions-stag.opensignal.com
support.opensignal.com
tiles.opensignal.com
tiles-prod.opensignal.com
tiles-stag.opensignal.com
upload.opensignal.com
www-prod.opensignal.com
```

**Comment by Giltyhub2** [comment]
@pipboy96 i do not wish to examine more subdomains for this ruleset, i'm contempt with this much for this particular ruleset

**Comment by pipboy96** [comment]
@Giltyhub2 If you can, please submit another PR adding working domains from this list later.

**Comment by Giltyhub2** [comment]
@pipboy96 sure thing, thanks for always adding finding more domains and posting them here, muchh appreciated

**Comment by Giltyhub2** [comment]
@pipboy26 ended up incorporating the subdomains, thanks again :+1: , one request if possible: can you change the script you use to lookup all the subdomains by making a check at the end to see if the urls are at least reachable via http, since one didn't even work with http

**Comment by pipboy96** [comment]
@Giltyhub2 There is no script. I use a tool called Amass. I ditched Sublist3r because of false positives (domains that actually return NXDOMAIN when you actually `dig` them).

**Pull request merged**
