### PR TITLE
Delete rules for my (old) domain.

### PR DESCRIPTION
**Pull request by Flameeyes**
None of these are useful as none of the hostnames are currently in use. Also, they should all be on HSTS.

### CODE REVIEW

**Comment by pipboy96** [comment]
@Flameeyes Please add your website to https://hstspreload.org/, this will make `hsts-prune` remove your website's ruleset automatically.

**Comment by Flameeyes** [comment]
The flameeyes.eu domains are actually phased out, so adding them to the preload list is kind of pointless.

**Comment by pipboy96** [comment]
@Flameeyes Thanks for clarification.

**Comment by pipboy96** [comment]
@zoracon Can you check why Travis doesn't restart?

**Pull request merged**
