### PR TITLE
Rules for lymo.fr

### PR DESCRIPTION
**Pull request by patheticcockroach**
Rules for lymo.fr

### CODE REVIEW

**Comment by jeremyn** [comment]
@patheticcockroach Are you still interested in working on this pull request?

**Comment by patheticcockroach** [comment]
The check only failed because of a temporary downtime and I don't know how to force re-run it. Running it again should pass.

**Comment by jeremyn** [comment]
Your pull request needs some minor changes. Please make these changes and let me know if you have any questions:

- [ ] Add a comment at the top that looks like this:
```xml
<!--
	Invalid certificate:
		blog.lymo.fr

-->
```
- [ ] Remove the two `test`s (there is already an automatic `test` added for each `target`, your extra `test`s are not needed)
- [ ] Indent using a single tab instead of spaces

**Comment by patheticcockroach** [comment]
Well, apparently deleting my fork was a pretty bad idea... not sure how I can resume working on this PR, I seem to be locked out of editing the file in it :/
Is it okay if I just create a new PR with the updated file, and then refer to this one in it?

**Comment by jeremyn** [comment]
Yes, that's fine. Note that you can still recover the contents of the original PR by clicking on the git hashes above on this page, if you don't have a local copy.

**Comment by patheticcockroach** [comment]
I guess it makes sense to close this PR now that I sent the new one. If it's good I'll do Anaxago later, the same way.

**Pull request closed without merging**
