### PR TITLE
Update Sinaimg.cn.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by J0WI** [comment]
I'm also getting a mismatch on `www.sinaimg.cn`, I don't know why Travis is not catching this. cc @Hainish

**Comment by ivysrono** [comment]
snipaste_20170307_193044

I can redirect www to wwws.
However, I can't get a mismatch.

**Comment by jeremyn** [comment]
I'm also getting a mismatch:

>www.sinaimg.cn uses an invalid security certificate.
>
>The certificate is only valid for the following names: *.akamaihd.net, *.akamaized-staging.net, *.akamaized.net, *.akamaihd-staging.net, a248.e.akamai.net
>
>Error code: SSL_ERROR_BAD_CERT_DOMAIN

Maybe this is a situation where the site uses Akamai outside the Chinese GFW, something else inside the GFW that doesn't get a mismatch, and @ivysrono is checking inside the GFW and @J0WI and I are checking outside of it?

**Comment by J0WI** [comment]
I think it's because the host resolves to different IPs and the servers are not configured the same.

**Comment by ivysrono** [comment]
@J0WI Ok on wwws.sinaimg.cn ?

**Comment by J0WI** [comment]
That one seems always fine.

**Pull request merged**
