### PR TITLE
Added rule for HsKA IWI faculty.

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Jochen-A-Fuerbacher Are you still interested in working on this?

**Comment by Jochen-A-Fuerbacher** [comment]
@jeremyn Yes, I am still interested in working on this. However, for the moment I think this could be merged.

**Comment by jeremyn** [comment]
There are several more subdomains for `hs-karlsruhe.de` that should be added either as working `target`s or noted in a comment at the top as non-working. Please look at our [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) and use either Sublist3r or the Google search strategy described there to find more subdomains. See [here](https://github.com/EFForg/https-everywhere/blob/33b1705128793ea25f926efab201249de32c6786/src/chrome/content/rules/glavbukh.ru.xml#L1-L71) for an example of a top comment.

Also, please fix the indentation. Each indentation should be one tab, no spaces.

**Comment by Jochen-A-Fuerbacher** [comment]
@jeremyn Thank you for your comment. I added more targets.

**Comment by jeremyn** [comment]
Please make the following changes. For the removal items, these are based some informal rules: don't include domains if they aren't in DNS (`Server not found`); don't include domains if both HTTPS and HTTP have problems. I also don't like to include domains that are purely internal infrastructure like VPN, webmail, or security devices, but there's some room for debate there. I give reasons for most of the changes in parentheses but let me know if you have questions about any of these requested changes.

Remove these domains from the top comment:
- [ ] https://ads.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://mmt-cw-skimmer.ads.hs-karlsruhe.de (not in DNS)
- [ ] https://apps.hs-karlsruhe.de (`400` HTTPS, refused HTTP)
- [ ] https://cisco-3060.hs-karlsruhe.de (not in DNS)
- [ ] https://eit-st.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://filestation-01.hs-karlsruhe.de (not in DNS)
- [ ] https://idp.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://iwi-i-lfm.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://iz-aix-212a.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://pop.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://proxyads.hs-karlsruhe.de (HTTP redirect to invalid certificate, too internal)
- [ ] https://rz01.hs-karlsruhe.de (time out for HTTPS and HTTP)
- [ ] https://vwe1.hs-karlsruhe.de (not in DNS)
- [ ] https://w.hs-karlsruhe.de (not in DNS)

Remove these `target`s:
- [ ] https://activesync.hs-karlsruhe.de (`403`, too internal)
- [ ] https://autodiscover.hs-karlsruhe.de (`403`, too internal)
- [ ] https://plot.hs-karlsruhe.de (`401` Authorization Required)
- [ ] https://proxyexchange.hs-karlsruhe.de (too internal)
- [ ] https://vpn.hs-karlsruhe.de (too internal)
- [ ] https://webmail.hs-karlsruhe.de (too internal)
- [ ] https://wsa.hs-karlsruhe.de (too internal)

Move to comment `Invalid certificate`:
- [ ] https://iz-scgu48.hs-karlsruhe.de and remove from `Timeout`
- [ ] https://wpad.hs-karlsruhe.de and remove from `Redirect to HTTP`

Add `target`, remove from comment:
- [ ] https://idp-pilot.hs-karlsruhe.de
- [ ] https://www.iz.hs-karlsruhe.de
- [ ] https://iz-apple.hs-karlsruhe.de

Also:
- [ ] Change the top comment from [this](https://github.com/Jochen-A-Fuerbacher/https-everywhere/blob/c9b64ad4b41bde313d50773326f55b921f4bf96e/src/chrome/content/rules/HsKA.xml#L3-L40) to have formatting and placement like [this](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71)
- [ ] Delete the `<!-- General -->` and `<!-- Faculty of ... -->` comments and move the `Faculty` domains into the `General` list

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7406/commits/414ac3762623e0792a15c18bc7faffb3d212c39a, thanks. The remaining items are not finished because you didn't delete the requested comments.

Also, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us? Additionally, for this pull request, I want to delete all of your individual commits when I do the merge. Is that all right? (Please don't do that yourself, it might make it harder to review your remaining changes.)

**Comment by Jochen-A-Fuerbacher** [comment]
Yes, you can squash-and-merge the pull request and delete the individual commits.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
