### PR TITLE
Calacademy.org make trivial rule.

### PR DESCRIPTION
**Pull request by jish**
Also added:

* store.calacademy.org
* ticketing.calacademy.org

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. 

Please remove targets and note as `incomplete certificate chain`:
calacademy.org
www.calacademy.org

Note as `Invalid certificate`:
calendar.calacademy.org
hotels.calacademy.org

**Comment by jish** [comment]
I've added and removed the domains listed.

I'm not sure how to use the legend at the bottom of the comment, so I looked through some of the other commits and found one letter notations at the end of the line wrapped in parenthesis, so I followed that convention.

    subdomain.example.org (t)

Let me know if anything looks off.

**Comment by gloomy-ghost** [comment]
There are some different styles of comments, you can have a look at #6868

I personally prefer listing subdomains in categories. It's ok if you want to list them in order and mark their status one by one, but it's wired to use both styles in one ruleset.

**Comment by gloomy-ghost** [comment]
I've updated https://github.com/EFForg/https-everywhere/pull/7517#issuecomment-260094044

We can't secure `legacy` after remove `www`, I'm sorry for that.

**Comment by jish** [comment]
I removed `legacy.calacademy.org` and added as a comment.

I'm sorry for all of the back and forth, the tests do not run properly on my machine. When I run `bash test.sh` a new instance of Firefox opens up and just sits there and does nothing forever. Both my Terminal and the new Firefox instance will both just hang forever.

**Comment by gloomy-ghost** [comment]
I'm using Windows, so I usually leave the testing to Travis CI. But did you run `install-dev-dependencies.sh` before testing?

The ruleset is good, thanks.

**Comment by jish** [comment]
> "I'm using Windows, so I usually leave the testing to Travis CI."

I'm using Mac OS, but I guess Travis CI will have to be my strategy as well.

> "did you run install-dev-dependencies.sh before testing?"

Yes, I did.

**Pull request merged**
