### PR TITLE
Update and rename ToSDR.org.xml to ToS_DR.xml

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Actually, I renamed this one. I personally prefer when the ruleset name is the same as the domain name. That way, you can guess the domain name just by looking at the list of files. 

Only exception is when several domains are covered in a single ruleset.

**Comment by J0WI** [comment]
Underscores are not preferable (https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#filenames)

**Comment by koops76** [comment]
@Bisaloo @J0WI Done.

**Comment by Bisaloo** [comment]
Also, why did you change targets ordering?

**Comment by koops76** [comment]
@Bisaloo oops.

**Pull request merged**
