### PR TITLE
umftgm.ro

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please [add more subdomains](https://www.google.com/search?q=site%3A*.umftgm.ro&ie=utf-8&oe=utf-8#q=site:*.umftgm.ro+-site:uniweb.umftgm.ro+-site:roelme.umftgm.ro+-site:www.umftgm.ro+-site:admitere.umftgm.ro+-site:blog.umftgm.ro+-site:librarie.umftgm.ro+-site:70.umftgm.ro+-site:ccamf.umftgm.ro+-site:phteachingcourse.umftgm.ro+-site:phd.umftgm.ro+-site:zilele.umftgm.ro+-site:admission.umftgm.ro+-site:ums.umftgm.ro+-site:simulationconference.umftgm.ro+-site:webmail.umftgm.ro+-site:quantis.umftgm.ro+-site:fise.umftgm.ro+-site:trr.umftgm.ro) and sort them.

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Add a target for https://quantis.umftgm.ro and delete it from the top comment. It looks like it has the same content as http://quantis.umftgm.ro .
- [ ] Sort the targets and comment.

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Please sort the domains in the top comment.

**Comment by galeksandrp** [comment]
Sorted.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
