### PR TITLE
Update AlaskaAirlines.xml

### PR DESCRIPTION
**Pull request by pipboy96**
No evidence of mixed content issues.

### CODE REVIEW

**Comment by J0WI** [comment]
You can easily add more targets here: https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by pipboy96** [comment]
@J0WI Of course I know about Sublist3r. Not sure why I didn't run it, or why I did not add more subdomains.

**Comment by pipboy96** [comment]
@J0WI There are way too many subdomains to test:
```
airwatch.alaskaair.com - Found open ports: 443
aagmms.alaskaair.com - Found open ports: 443, 80
api.alaskaair.com - Found open ports: 443
alaskaguest.alaskaair.com - Found open ports: 443
access.alaskaair.com - Found open ports: 443, 80
aagsecure.alaskaair.com - Found open ports: 80
activefit.alaskaair.com - Found open ports: 443, 80
apphangar.alaskaair.com - Found open ports: 443, 80
arch.alaskaair.com - Found open ports: 443, 80
archpci.alaskaair.com - Found open ports: 443
cherwell.alaskaair.com - Found open ports: 443, 80
ascom.alaskaair.com - Found open ports: 443, 80
asainflight.alaskaair.com - Found open ports: 80
www.alaskaair.com - Found open ports: 443, 80
aspilot.alaskaair.com - Found open ports: 80
access.bc.alaskaair.com - Found open ports: 443, 80
aspilotlockscreen.alaskaair.com - Found open ports: 443, 80
alaskaguest.bc.alaskaair.com - Found open ports: 443
api.bc.alaskaair.com - Found open ports: 443
www.bc.alaskaair.com - Found open ports: 443, 80
arch.bc.alaskaair.com - Found open ports: 443, 80
asainflight.bc.alaskaair.com - Found open ports: 80
aspilot.bc.alaskaair.com - Found open ports: 80
ascts.bc.alaskaair.com - Found open ports: 80
careers.bc.alaskaair.com - Found open ports: 443, 80
autodiscover.alaskaair.com - Found open ports: 80
crew.bc.alaskaair.com - Found open ports: 443, 80
cargo.bc.alaskaair.com - Found open ports: 443, 80
ec.bc.alaskaair.com - Found open ports: 80
ebusiness.bc.alaskaair.com - Found open ports: 443, 80
crxs.bc.alaskaair.com - Found open ports: 80
esprit.bc.alaskaair.com - Found open ports: 80
fin.bc.alaskaair.com - Found open ports: 443, 80
fit.bc.alaskaair.com - Found open ports: 443, 80
fogs.bc.alaskaair.com - Found open ports: 443, 80
groundops.bc.alaskaair.com - Found open ports: 443, 80
me.bc.alaskaair.com - Found open ports: 443, 80
jobs.bc.alaskaair.com - Found open ports: 80
image.bc.alaskaair.com - Found open ports: 80
mftp.bc.alaskaair.com - Found open ports: 443
apis.alaskaair.com - Found open ports: 443
pm.bc.alaskaair.com - Found open ports: 443, 80
psmc.bc.alaskaair.com - Found open ports: 443, 80
tableau.bc.alaskaair.com - Found open ports: 443, 80
tam.bc.alaskaair.com - Found open ports: 443, 80
aw135cgrelay.alaskaair.com - Found open ports: 443
totem.bc.alaskaair.com - Found open ports: 443, 80
training.bc.alaskaair.com - Found open ports: 443, 80
travelagent.bc.alaskaair.com - Found open ports: 80
crewaccess.bc.alaskaair.com - Found open ports: 443
ezweb.bc.alaskaair.com - Found open ports: 443
fedauth.bc.alaskaair.com - Found open ports: 443
vendorvpn.bc.alaskaair.com - Found open ports: 443, 80
vpn.bc.alaskaair.com - Found open ports: 443, 80
mp.bc.alaskaair.com - Found open ports: 80
web.bc.alaskaair.com - Found open ports: 443, 80
operations.bc.alaskaair.com - Found open ports: 443
webmcgeepri.bc.alaskaair.com - Found open ports: 443
blog.alaskaair.com - Found open ports: 443, 80
webselfservice.bc.alaskaair.com - Found open ports: 443
realtime.bc.alaskaair.com - Found open ports: 443
steptrade.bc.alaskaair.com - Found open ports: 443
webui.bc.alaskaair.com - Found open ports: 443, 80
alias.www.bc.alaskaair.com - Found open ports: 443, 80
careers.alaskaair.com - Found open ports: 443, 80
cargo.alaskaair.com - Found open ports: 443, 80
vdisecccboi.bc.alaskaair.com - Found open ports: 443
vdiseccckvy.bc.alaskaair.com - Found open ports: 443
vdisecadm.bc.alaskaair.com - Found open ports: 443
vdisecccphx.bc.alaskaair.com - Found open ports: 443
vdiseccde.bc.alaskaair.com - Found open ports: 443
companystore.alaskaair.com - Found open ports: 443, 80
crew.alaskaair.com - Found open ports: 443, 80
cms-qa.alaskaair.com - Found open ports: 443, 80
cms.alaskaair.com - Found open ports: 443, 80
cms-test.alaskaair.com - Found open ports: 443, 80
archpci.bc.alaskaair.com - Found open ports: 443
webtukpri.bc.alaskaair.com - Found open ports: 443
crewstg.alaskaair.com - Found open ports: 443, 80
crosscheckapi.alaskaair.com - Found open ports: 443, 80
developer.alaskaair.com - Found open ports: 443, 80
outofservice.dev.alaskaair.com - Found open ports: 443, 80
crxs.alaskaair.com - Found open ports: 80
bomgar.alaskaair.com - Found open ports: 443
easybiz.alaskaair.com - Found open ports: 443, 80
ebusiness.alaskaair.com - Found open ports: 443, 80
edct.alaskaair.com - Found open ports: 443, 80
cmgaag.alaskaair.com - Found open ports: 443
facturacion.alaskaair.com - Found open ports: 443, 80
falockscreen.alaskaair.com - Found open ports: 443, 80
ezweb.alaskaair.com - Found open ports: 443
crewaccess.alaskaair.com - Found open ports: 443
feedback.alaskaair.com - Found open ports: 443, 80
fit.alaskaair.com - Found open ports: 443, 80
fogs.alaskaair.com - Found open ports: 443, 80
geoservice.alaskaair.com - Found open ports: 443, 80
developers.alaskaair.com - Found open ports: 443
home.alaskaair.com - Found open ports: 443, 80
hotels.alaskaair.com - Found open ports: 443, 80
ifly2.alaskaair.com - Found open ports: 443, 80
ifly.alaskaair.com - Found open ports: 443, 80
insights.alaskaair.com - Found open ports: 443, 80
igqvpn.alaskaair.com - Found open ports: 443, 80
investor.alaskaair.com - Found open ports: 443, 80
inflight.alaskaair.com - Found open ports: 443, 80
m.alaskaair.com - Found open ports: 443, 80
lyncdiscover.alaskaair.com - Found open ports: 443, 80
fedauth.alaskaair.com - Found open ports: 443
jobs.alaskaair.com - Found open ports: 80
labs.alaskaair.com - Found open ports: 80
kafkapoc.alaskaair.com - Found open ports: 443
mow-qa.alaskaair.com - Found open ports: 443, 80
me.alaskaair.com - Found open ports: 443, 80
newsroom.alaskaair.com - Found open ports: 443, 80
mftp.alaskaair.com - Found open ports: 443
omni.alaskaair.com - Found open ports: 443, 80
pm.alaskaair.com - Found open ports: 443, 80
pilots.alaskaair.com - Found open ports: 443, 80
preview.alaskaair.com - Found open ports: 443, 80
psmc.alaskaair.com - Found open ports: 443, 80
api.qa.alaskaair.com - Found open ports: 443
edct.qa.alaskaair.com - Found open ports: 443, 80
outofservice.qa.alaskaair.com - Found open ports: 443, 80
managementapi.alaskaair.com - Found open ports: 443
resource.alaskaair.com - Found open ports: 443, 80
quickclaim.alaskaair.com - Found open ports: 443, 80
operations.alaskaair.com - Found open ports: 443
rain.alaskaair.com - Found open ports: 443, 80
receipts.alaskaair.com - Found open ports: 443, 80
ascts.alaskaair.com - Found open ports: 80
se4vpn.alaskaair.com - Found open ports: 443, 80
apis.qa.alaskaair.com - Found open ports: 443
developers.qa.alaskaair.com - Found open ports: 443
managementapi.qa.alaskaair.com - Found open ports: 443
shoppingapi-prod.alaskaair.com - Found open ports: 443, 80
shoppingapi-qa.alaskaair.com - Found open ports: 80
realtime.qa.alaskaair.com - Found open ports: 443
sitecore.alaskaair.com - Found open ports: 443, 80
sitecoreqa.alaskaair.com - Found open ports: 443, 80
somni.alaskaair.com - Found open ports: 443
webselfservice.stg.alaskaair.com - Found open ports: 443, 80
realtime.alaskaair.com - Found open ports: 443
ebusiness.stage.alaskaair.com - Found open ports: 443
surveys.alaskaair.com - Found open ports: 80
tableau.alaskaair.com - Found open ports: 443, 80
tam.alaskaair.com - Found open ports: 443, 80
tamuat.alaskaair.com - Found open ports: 443, 80
tam92.alaskaair.com - Found open ports: 443, 80
api.test.alaskaair.com - Found open ports: 443
developer.test.alaskaair.com - Found open ports: 443, 80
securetransfer.alaskaair.com - Found open ports: 443
edct.test.alaskaair.com - Found open ports: 443, 80
geoservice.test.alaskaair.com - Found open ports: 443, 80
totem.alaskaair.com - Found open ports: 443, 80
training.alaskaair.com - Found open ports: 443, 80
tukaccess.alaskaair.com - Found open ports: 443, 80
v.alaskaair.com - Found open ports: 443, 80
gate.v.alaskaair.com - Found open ports: 443, 80
updates.alaskaair.com - Found open ports: 443, 80
steptrade.alaskaair.com - Found open ports: 443
apis.test.alaskaair.com - Found open ports: 443
developers.test.alaskaair.com - Found open ports: 443
managementapi.test.alaskaair.com - Found open ports: 443
operations.train.alaskaair.com - Found open ports: 443
vendorvpn.alaskaair.com - Found open ports: 443, 80
transfer.alaskaair.com - Found open ports: 443
vpn.alaskaair.com - Found open ports: 443, 80
web.alaskaair.com - Found open ports: 443, 80
webmcgeepri.alaskaair.com - Found open ports: 443
webselfservice.alaskaair.com - Found open ports: 443
vdisecadm.alaskaair.com - Found open ports: 443
vdiseccc.alaskaair.com - Found open ports: 443
vdisecccboi.alaskaair.com - Found open ports: 443
vdiseccckvy.alaskaair.com - Found open ports: 443
vdisecccphx.alaskaair.com - Found open ports: 443
webui.alaskaair.com - Found open ports: 443, 80
xids.alaskaair.com - Found open ports: 443, 80
vdiseccde.alaskaair.com - Found open ports: 443
vii-alerts.alaskaair.com - Found open ports: 80
webtukpri.alaskaair.com - Found open ports: 443
alias.www.alaskaair.com - Found open ports: 443, 80
```

**Comment by J0WI** [comment]
If you use scripts anyway you could also `curl` the domain to quickly find (in)valid targets ;)

**Comment by pipboy96** [comment]
@J0WI Scripts can't replace manual review, especially when there may be mixed content issue.

**Comment by J0WI** [comment]
Sure, but they reduce the amount of hosts that need to be checked manually.

**Comment by pipboy96** [comment]
@J0WI Ok. Will do then.

**Comment by pipboy96** [comment]
For my own reference:
```
301s:

http://aagsecure.alaskaair.com/*
to
https://sendsecure.m86security.com/s/login?b=alaskaair

http://autodiscover.alaskaair.com/
to
https://outlook.office365.com/owa/?realm=alaskaair.com&vd=autodiscover

http://autodiscover.alaskaair.com/*
to
https://outlook.office365.com/$1?realm=alaskaair.com&vd=autodiscover

http://jobs.bc.alaskaair.com/*
to
https://www.alaskasworld.com/jobs/asjobs/default.asp

http://travelagent.bc.alaskaair.com/*
to
https://www.alaskaair.com/travel-agent

http://jobs.alaskaair.com/*
to
https://www.alaskasworld.com/jobs/asjobs/default.asp
```

**Comment by pipboy96** [comment]
@J0WI I will work on this tomorrow. Feel free to work on this now though.

**Pull request merged**
