### PR TITLE
unian.net

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Before a more thorough review, please:

- [ ] Add related `*.unian.ua` and `*.unian.info` domains
- [ ] Sort the domains
- [ ] Most of the pages I checked have mixed content blocking, like this in the web console from https://unian.net :

```
Blocked loading mixed active content "http://c.bigmir.net/?s12815&t0&l1&o1"
Blocked loading mixed active content "http://pogoda.unian.net/widget?lang=ukr"
Blocked loading mixed active content "http://social.unian.net/css/comments-new-design.css"
Blocked loading mixed active content "http://social.unian.net/js/commentsLoader-new-design.js?r=9"
Blocked loading mixed active content "http://c.bigmir.net/?o1&v13701&s12815&t6&c1&n36205&w0&m22&y0&d24&r1920"
Blocked loading mixed active content "http://ad.adriver.ru/cgi-bin/erle.cgi?sid=1&ad=478941&bt=40&pid=1699334&bn=1699334&rnd=202720372&tail256=https%3A//unian.net/"
Blocked loading mixed active content "http://vid4.tsn.ua/adv/dfpunianpr1.html"
Blocked loading mixed active content "http://uamobile.net/lib/js/id/210115"
```

(Many other messages show up in the web console too that I haven't included.) Some of that looks like advertising but some of it looks important, maybe comments? I can't tell what's broken on the page. Do you know what this is?

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Thanks. I've updated the checklist through 6b6631a0b8ed1a01f9cbbdec6d1c6e4cf20ebc12.

Please sort the domains in this order: `.info`, `.net`, and `.ua` in both the comment and targets. Also, please change the ruleset name from `unian.net` to `UNIAN`.

**Comment by galeksandrp** [comment]
Done, thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
