### PR TITLE
Re-enable and update Google.com_Subdomains.xml

### PR DESCRIPTION
**Pull request by koops76**
Removed preloaded domains and domains that fail fetch test. Also removed obsolete rules.

### CODE REVIEW

**Comment by Bisaloo** [comment]
#11068

**Comment by koops76** [comment]
@Bisaloo Does your PR have any changes missing from my PR?

**Comment by koops76** [comment]
BTW @Bisaloo look at #11114

**Comment by cschanaj** [comment]
Be noted that this is still `default_off`

**Comment by koops76** [comment]
@cschanaj Well I manually checked https://chromium.googlesource.com/chromium/src.git/+/59.0.3071.115/net/http/transport_security_state_static.json
https://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc
https://hg.mozilla.org/releases/mozilla-esr52/raw-file/FIREFOX_52_2_1esr_RELEASE/security/manager/ssl/nsSTSPreloadList.inc
https://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc

It seems `hsts-prune` doesn't remove all preloaded domains.

**Comment by koops76** [comment]
@cschanaj Fixed.

**Comment by bardiharborow** [comment]
Ref #11179

**Comment by J0WI** [comment]
closed by #11068. Preloaded hosts will be removed by our hsts-prune script.

**Pull request closed without merging**
