### PR TITLE
Update 126.net.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Comment by Hainish** [comment]
Re-running `rules` test now.  I've been seeing a lot of intermittent failures on Travis in the last few days.  I wonder if something is amiss.

**Comment by Hainish** [comment]
Looks like the answer is "yes": https://twitter.com/travisci/status/923280634193285120

**Comment by gloomy-ghost** [comment]
And this one as well: https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Comment by gloomy-ghost** [comment]
Testing passed, merging since it's blocking all builds

**Comment by Hainish** [comment]
As of 16:16 UTC (21 minutes ago) Travis is reporting the issue as resolved.

**Pull request merged**
