### PR TITLE
Update Unizar.es.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by davidabian** [comment]
False negative?

**Comment by J0WI** [comment]
retest

**Comment by J0WI** [comment]
I hope we can get rid of such errors after #5015 has been merged.

**Comment by davidabian** [comment]
Don't worry, @J0WI. Subdomain webdiis.unizar.es is exceptionally down today and tomorrow for electrical maintenance issues. I'm sure that these checks are now working well. You can check again in a few days (or ignore webdiis.unizar.es right now if that's possible).

https://twitter.com/DIIS_UZ/status/752787459839229952

**Comment by davidabian** [comment]
It seems to be working now, @J0WI.

**Comment by J0WI** [comment]
retest

**Comment by davidabian** [comment]
Hallelujah! :laughing:

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
