### PR TITLE
Fix typos in rules comments and ruleset names

### PR DESCRIPTION
**Pull request by jwilk**
Originally these commits were included in #3390.

### CODE REVIEW

**Comment by J0WI** [comment]
I think some of them needs revision.

**Comment by jwilk** [comment]
I updated ruleset-coverage-whitelist to make the testsuite happy.

**Comment by J0WI** [comment]
lgtm, but the second commit should trigger the tests

**Comment by jwilk** [comment]
I don't follow…

**Comment by J0WI** [comment]
7ef8bba touches rules that are in a white list, so Travis should check the hash sums.

**Comment by fuglede** [comment]
Weird; let me try rebooting the PR.

**Comment by jwilk** [comment]
Oops, sorry for the confusion.
Let me bump date on the other commit...

**Comment by jsha** [comment]
LGTM, thanks!

**Pull request merged**
