### PR TITLE
Create Loverpi.com.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by J0WI** [comment]
There is also `share.loverpi.com` (refused) and `share.loverpi.com` (working).

**Comment by ekaris** [comment]
How can it be working and refusing at same time?

**Comment by J0WI** [comment]
Ah, sorry. `forum.loverpi.com` is the working one.

**Comment by ekaris** [comment]
Done

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
