### PR TITLE
Create hexieshe.com.xml

### PR DESCRIPTION
**Pull request by bob0627**
hsts list

### CODE REVIEW

**Comment by ivysrono** [comment]
几个月前大规模清理过一次已经进入 preloadlist 的规则，正是由中文区第一大佬 @gloomy-ghost 发起的~

**Comment by gloomy-ghost** [comment]
Ping @Hainish for the false-negative of preload checking

**Comment by Hainish** [comment]
This is the correct result.  Here is the result for the domain `hexieshe.com` being preloaded in the supported browsers:

Firefox ESR: false
Firefox Aurora: true
Firefox Stable: false
Chromium Stable: false

**Comment by jeremyn** [comment]
@bob0627 Are you still interested in working on this?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @bob0627 . I've noted `hexieshe.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353126784` in case someone else wants to make a pull request for this domain.

**Pull request closed without merging**
