### PR TITLE
Get rid of wildcards in Google.tld_Subdomains.xml using Google's supported domains list (alternate)

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Why did you remove many test urls?

**Comment by Bisaloo** [comment]
Also, I'm fine with this single PR but I don't think we should work on Google rulesets at the same time. It's already confusing enough as it is without having to check pending changes / guess in which direction other contributors are going.

**Comment by Bisaloo** [comment]
Depends on https://github.com/EFForg/https-everywhere/pull/12576

**Comment by koops76** [comment]
`groups` does not exist for `google.cn`, WTF?

**Comment by koops76** [comment]
@Bisaloo Would you like to continue the work on this PR?

**Comment by koops76** [comment]
The current problem is that I don't know what subdomains exist for all `google.tld` variations.

**Comment by koops76** [comment]
This should work:

```bash
git remote add koops76 https://github.com/koops76/https-everywhere.git
git fetch koops76 patch-47
git checkout -b google.tld-subdomains koops76/patch-47

# do your work

git push origin google.tld-subdomains
```

**Comment by Bisaloo** [comment]
Okay, I will look at it. I am working on the low hanging fruit in these rulesets first. Thank you for your work!

**Pull request closed without merging**
