### PR TITLE
Added piliapp.com

### PR DESCRIPTION
**Pull request by Foorack**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks!

Can you also add the following subdomains?
fashion.piliapp.com
comic.piliapp.com
food.piliapp.com
travel.piliapp.com
recipe.piliapp.com
ar.piliapp.com
hu.piliapp.com
pl.piliapp.com
nl.piliapp.com
no.piliapp.com
sv.piliapp.com
hu.piliapp.com
cs.piliapp.com
th.piliapp.com
el.piliapp.com
iw.piliapp.com

Please also add a comment on the top, that https on blog.piliapp.com is refused.

**Comment by Foorack** [comment]
@J0WI Done, sorted alphabetically. :smile:

**Comment by J0WI** [comment]
For some reason the fetch failed.
Let me rerun the tests.

**Comment by J0WI** [comment]
Now we have a different error...

**Comment by J0WI** [comment]
@Hainish I thought we test twice on an error. Is this a regression?

**Pull request merged**
