### PR TITLE
Update Cloudfront.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
It looks like http://aww.bugsplatsoftware.com/Blog/ makes calls to http://d22iv91mzdv9l4.cloudfront.net , which doesn't exist in DNS. Is the point of this pull request to fix their page for them by rewriting http://d22iv91mzdv9l4.cloudfront.net to https://www.bugsplat.com ? If so, that is not something we should be doing in HTTPS Everywhere.

**Comment by renyouguo** [comment]
I think it is http to https...
Why?
Does #6889 same?

**Comment by renyouguo** [comment]
No, iwgc.cn is not CDN.

**Comment by jeremyn** [comment]
In that case, what we're discussing here may not apply to pull request #6889.

**Comment by renyouguo** [comment]
All the *.bugsplatsoftware.com show:
`Error establishing a database connection`
Thank you, @jeremyn

**Pull request closed without merging**
