### PR TITLE
Create 1over1.xml

### PR DESCRIPTION
**Pull request by 15556133244**

### CODE REVIEW

**Comment by 15556133244** [comment]
@pipboy96

**Comment by pipboy96** [comment]
?

**Comment by ivysrono** [comment]
you  approved these changes 3 months ago

**Comment by pipboy96** [comment]
@15556133244 I currently don't have merge permission to this repo, so I can't merge that. Sorry. You have to wait for another reviewer.

**Comment by Bisaloo** [comment]
I get MCB on this domain (e.g. https://1over1.net/forum.php). Could you double check please?

**Comment by pipboy96** [comment]
@Bisaloo Indeed, this URL has active mixed content.

**Comment by 15556133244** [comment]
@Bisaloo

**Comment by Bisaloo** [comment]
The changes in 45f243 don't solve the MCB issues for me.

**Pull request closed without merging**
