### PR TITLE
Update 163.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by J0WI** [comment]
Slow host, rerun test

**Comment by renyouguo** [comment]
I have to say, 163 and 126 is one of the fastest sites in china.
Slow in other county?Maybe.

**Comment by J0WI** [comment]
It's the connection from China to Travis (US?) that is slow.

**Comment by renyouguo** [comment]
Yes,there is the Great Fire Wall, so you will get the different errors for each time.

**Comment by J0WI** [comment]
It finally passed all tests :)

**Pull request merged**
