### PR TITLE
[Locale] Add French translation for showCounter

### PR DESCRIPTION
**Pull request by FoxyAntho**
Update forgotten french locale in the addon main menu.

### CODE REVIEW

**Comment by reedy** [comment]
I've got a +1 from a native French speaker. Not 100% sure if I can just merge such changes...

**Comment by reedy** [comment]
@jsha Can I just merge this? Or is there something special to do?

**Comment by jsha** [comment]
@FoxyAntho: Can you sign up on Transifex and submit this translation through there?

I'm going to merge this for now, to get it in the next release, but next time I pull translations from Transifex it will get clobbered.

This will all get more obvious once I do https://github.com/EFForg/https-everywhere/issues/2313.

**Comment by FoxyAntho** [comment]
@jsha Okay :wink: Everything is already translated is French, so, it's already done.

**Pull request merged**
