### PR TITLE
added Glueckspost.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@fuglede any idea why GnuTLS refuses to connect?

**Comment by fuglede** [comment]
@J0WI: I don't have time to look into it at the moment, but from the surface, it looks like an instance https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708 (but <code>https-everywhere-checker</code> should catch those, so maybe it's something different).

**Comment by jeremyn** [comment]
This looks fine to me. I'd merge it except @fuglede has already commented on it and I don't want to step on toes.

@fuglede Do you mind if I merge this in?

**Comment by fuglede** [comment]
@jeremyn: Sure; it looks like the original issue is no longer present. And don't worry about stepping on me in the future (at least not if the comment is about something that does not need further fixing. :)).

**Pull request merged**
