### PR TITLE
Prefer const

### PR DESCRIPTION
**Pull request by koops76**
Includes changes by @RReverser.

Doesn't touch non-ES6 `var` declarations yet.

### CODE REVIEW

**Comment by koops76** [comment]
ping @Hainish, @cowlicks.

**Comment by cowlicks** [comment]
We need to have a real module system instead of specifying globals and exports everywhere. I'll make a PR with these changes ASAP.

**Comment by koops76** [comment]
@cowlicks See [Webpack](https://webpack.github.io/).

**Comment by koops76** [comment]
They were needed to figure out what needs to be exported/imported.

**Comment by RReverser** [comment]
Webpack might be overkill here, I'd suggest going with Rollup.

**Comment by koops76** [comment]
@RReverser I doubt it. Maybe you can explain why you think it is overkill?

**Comment by RReverser** [comment]
Performance-wise, plus webpack has various hacks for CommonJS which extension doesn't use, plus it still includes its own `require` shims even with tree-shaking. For pure ES6 modules Rollup is faster and produces smaller output, which is why it's so often used for libraries.

**Comment by cowlicks** [comment]
@RReverser @koops76 see #12586 for modules. 

@koops76 I am not very fond of this change. Can we just use `const` for global constants? The constants in `util.js` are a good case for this. Otherwise, it seems like we are using `const` to describing existing code usage devoid of context, instead of having the code describe what it should do.... Also const has 2 more letters than let.

**Comment by koops76** [comment]
@cowlicks `const` prevents accidental modification of variable. It should be preferred over `let`.

**Comment by RReverser** [comment]
I agree with @cowlicks, I think using const literally everywhere is noisy and, despite being popular, is rather an antipattern (especially whrn used for things that are still mutable by nature like objects). But then, it's not really up to me to decide.

**Comment by koops76** [comment]
I wish there was a `prefer-let` rule, but there is no such ESLint rule. So I guess that for consistency we should prefer `const` where possible, since we can't prefer `let` instead. It is obvious that we should prefer `let` or `const` over `var` but that depends on namespace PR by @cowlicks since `var` and `let`/`const` behave differently at global scope.

**Comment by cowlicks** [comment]
@koops76 closing this. There are arguments for and against using `const` everywhere, but at the end of the day, it isn't a big deal. So I'd prefer to trust devs to use their best judgement, instead of strictly enforcing a style.

**Comment by koops76** [comment]
@cowlicks Will you also close a PR that adds no-var ESLint rule, requiring either `let` or `const`?

**Pull request closed without merging**
