### PR TITLE
glavbukh.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please add missing subdomains, see [here](https://www.google.com/search?q=site%3A*.kprf.ru&ie=utf-8&oe=utf-8#q=site:*.glavbukh.ru+-site:www.glavbukh.ru+-site:e.glavbukh.ru+-site:school.glavbukh.ru+-site:rz.glavbukh.ru+-site:usn.glavbukh.ru+-site:top.glavbukh.ru+-site:otchet.glavbukh.ru+-site:lifeart.glavbukh.ru+-site:kadry.glavbukh.ru+-site:premia.glavbukh.ru+-site:premia2015.glavbukh.ru).

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Make https://forum.glavbukh.ru a `target`
- [ ] Replace the entire top comment with this:
```xml
<!--
	Invalid certificate:
		8marta.glavbukh.ru
		8marta2015.glavbukh.ru
		8marta2016.glavbukh.ru
		attestat.glavbukh.ru
		bdn.glavbukh.ru
		cok.glavbukh.ru
		den2013.glavbukh.ru
		den2014.glavbukh.ru
		dod.glavbukh.ru
		www.forum.glavbukh.ru
		forum2.glavbukh.ru (incomplete certificate chain)
		www.kkt.glavbukh.ru
		www.lifeart.glavbukh.ru
		linate.glavbukh.ru (incomplete certificate chain)
		msb.glavbukh.ru
		ng.glavbukh.ru
		ng2015.glavbukh.ru
		ng2016.glavbukh.ru
		obr.glavbukh.ru
		otpusk.glavbukh.ru
		www.pclub.glavbukh.ru
		podarok.glavbukh.ru
		premia.glavbukh.ru
		www.premia.glavbukh.ru
		premia2015.glavbukh.ru
		reshebnik.glavbukh.ru
		dev.seminar.glavbukh.ru
		www.top.glavbukh.ru
		www.vs.glavbukh.ru (incomplete certificate chain)
		www.vseminar.glavbukh.ru (incomplete certificate chain)

	Redirect to HTTP:
		8marta2013.glavbukh.ru
		den.glavbukh.ru
		foto.glavbukh.ru
		go.glavbukh.ru
		golos.glavbukh.ru
		kadry.glavbukh.ru
		kkt.glavbukh.ru
		konf2013.glavbukh.ru
		lifeart.glavbukh.ru
		lifeartbend.glavbukh.ru
		ng2013.glavbukh.ru
		otchet.glavbukh.ru
		premia2012.glavbukh.ru
		rz.glavbukh.ru
		srz.glavbukh.ru
		top.glavbukh.ru
		usn.glavbukh.ru
		zarplata.glavbukh.ru

	Refused:
		e.glavbukh.ru
		www.e.glavbukh.ru
		m.e.glavbukh.ru
		epromo.glavbukh.ru
		www.epromo.glavbukh.ru
		partners.glavbukh.ru
		school.glavbukh.ru
		sgb.glavbukh.ru
		test.glavbukh.ru
		webinar.glavbukh.ru

	Time out:
		psd.glavbukh.ru
		str.glavbukh.ru
		turizm.glavbukh.ru

-->
```

**Comment by galeksandrp** [comment]
Oops.

And you forgot
```
counter.glavbukh.ru
talant.glavbukh.ru
union.glavbukh.ru
wp.glavbukh.ru
```

**Comment by jeremyn** [comment]
https://counter.glavbukh.ru times out in both HTTPS and plain HTTP, and https://union.glavbukh.ru is refused for both. I don't like adding domains to the non-working list if they don't work under plain HTTP either.

**Comment by jeremyn** [comment]
The `forum` `target` is causing a problem I can't explain. I wrote it up in issue #7711.

In the meantime, please comment it out like this:

```xml
	<target host="glavbukh.ru" />
	<target host="www.glavbukh.ru" />
	<!--Fails for unknown reason, see https://github.com/EFForg/https-everywhere/issues/7711
	<target host="forum.glavbukh.ru" />
	-->
	<target host="m.glavbukh.ru" />
```

Note also that I've moved `forum` above `m` to make it alphabetical.

**Comment by galeksandrp** [comment]
Commented, thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
