### PR TITLE
Remove the `--user` flag when installing dev dependencies.

### PR DESCRIPTION
**Pull request by jish**
Suggested fix from https://github.com/EFForg/https-everywhere/issues/983

### CODE REVIEW

**Comment by jsha** [comment]
The `--user` flag is correct for most environments: we don't want to install globally. There was something about your environment that caused an issue, though:

```
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

Can you figure out if you have default flags set for pip somewhere? E.g. environment variables or an rc file?

**Comment by jish** [comment]
I use a pretty stock MacBook Air, and I do not do any Python development. Whatever is set, came with Mac OS.

I tried this a few months ago when I first filed the issue #983 and it was broken, and I actually just wiped and re-installed my MacBook Air a few days ago and I'm getting the same issue. So it seems the install script with the `--user` flag is just not really compatible with Mac OS / MacBook Airs. =/

**Comment by jsha** [comment]
Good to know, thanks. I will try and get my hands on a Mac to do some testing. Do you have Xcode installed?

**Comment by jish** [comment]
Yes, I have XCode installed now, and I did when I originally opened the issue.

I'm not sure if it was installed yet when I opened this PR.

Josh

**Pull request closed without merging**
