### PR TITLE
Create hd.se.xml

### PR DESCRIPTION
**Pull request by itsdf**

### CODE REVIEW

**Comment by herrniemand** [comment]
@itsdf 
['src/chrome/content/rules/HD.se.xml', 'src/chrome/content/rules/hd.se.xml'] failed case-insensitivity testing.
Rules exist with identical case-insensitive names, which breaks some filesystems.

**Comment by herrniemand** [comment]
@itsdf Why dont you rename it to `HelsingborgsDagblad.se.xml`?

**Comment by herrniemand** [comment]
@itsdf actually, there already Helsingborgs Dagblad
https://github.com/itsdf/https-everywhere/blob/719ca209be62bc53ef25d78cbd37bff406ae96c8/src/chrome/content/rules/HD.se.xml

**Comment by itsdf** [comment]
mb didn't know that hd.se already existed!

**Pull request closed without merging**
