### PR TITLE
Revert "[Drugcom.de] New ruleset"

### PR DESCRIPTION
**Pull request by fuglede**
Reverts EFForg/https-everywhere#2585

### CODE REVIEW

**Comment by semenko** [comment]
Whoops, my comment wasn't clear. Actually, looks like the bare host just doesn't resolve.

I'm OK leaving this in, or dropping the bare drugcom.de

**Comment by fuglede** [comment]
Both hosts have comments: the bare one doesn't resolve, and the www one serves a bad certificate chain, causing warnings in all modern browsers that haven't cached the intermediate certificates from some third party. (Having #3107 in Travis would be pretty useful for catching stuff like this.)

**Comment by semenko** [comment]
Oh man, intermediate cert chaining bugs are weird, since this just worked for me on OS X in Chrome + curl.

Do we really want to 

screen shot 2015-12-17 at 3 43 43 pm

```
curl -Iv https://www.drugcom.de/
*   Trying 194.153.219.166...
* Connected to www.drugcom.de (194.153.219.166) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: www.drugcom.de
* Server certificate: thawte SSL CA - G2
* Server certificate: thawte Primary Root CA
> HEAD / HTTP/1.1
```

**Comment by fuglede** [comment]
Here's what it looks like in a clean profile Firefox:

skaermbillede fra 2015-12-17 22 52 08

[Relevant Bugzilla post](https://bugzilla.mozilla.org/show_bug.cgi?id=399324).

**Comment by jsha** [comment]
I think our metric should be "does it load in a clean FF profile and a clean Chrome profile." The `--justrun` flag to chromium.sh and firefox.sh make it relatively easy to test.

I believe both Chrome will fetch the URLs from Authority Information Access in an attempt to find missing intermediates, but as @fuglede's linked Bugzilla post says, Firefox won't.

**Comment by semenko** [comment]
Cool -- merging revert.  What's blocking #3107? Just this issue ->? https://github.com/jsha/https-everywhere-checker/pull/4

**Comment by fuglede** [comment]
@semenko: Yep.

**Pull request merged**
