### PR TITLE
Added Rage4

### PR DESCRIPTION
**Pull request by rugk**
#2324

### CODE REVIEW

**Comment by rugk** [comment]
Does anything speaks against merging this?

**Comment by semenko** [comment]
Hey -- sorry for the slow reply. Looks great -- please rebase so I can merge :)

**Comment by rugk** [comment]
Sorry, but what should I do? How can I rebase this?

**Comment by semenko** [comment]
Take a look at: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by rugk** [comment]
`git status` shows that it's all right:

```
On branch patch-rule-rage4
Your branch is up-to-date with 'origin/patch-rule-rage4'.

nothing to commit, working directory clean
```

**Comment by rugk** [comment]
Okay, just created a new PR: https://github.com/EFForg/https-everywhere/pull/2922

**Pull request closed without merging**
