### PR TITLE
Add vozpopuli.com

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
The following are working too:
www.vozpopuli.com
estatico.vozpopuli.com

Please also add comments for non working hosts.
Mismatched:
social.vozpopuli.com
gestion.vozpopuli.com
bolsa.vozpopuli.com

**Comment by davidabian** [comment]
Done. Thanks for the comments.

**Comment by J0WI** [comment]
Thanks, rule lgtm.

Please move the comments above the ruleset tag.
Btw: test urls are not required for simple redirects without any regex or exclusions.

**Comment by davidabian** [comment]
Done, and all test URLs removed.

**Pull request merged**
