### PR TITLE
[MyFitnessPal.com] Default_off and add platform (fix #11029)

### LINKED ISSUE #11029: myfitnesspal.com partially broken
This is a food diary/fitness tracking site, and on it, with HTTPS Everywhere forcing secure connections to MyFitnessPal, most lists of food items don't load properly, with the following or similar appearing in the browser console:
XMLHttpRequest cannot load https://www.myfitnesspal.com/food/load_recent. Response for preflight is invalid (redirect)

Additionally, if a list is working, attempting to add an item from it to the food diary will trigger the site's "under maintenance" message, with the following appearing in the browser console:
POST https://www.myfitnesspal.com/food/add_favorites 502 (Bad Gateway)

### LINKED ISSUE #11312: Myfitnesspal.com issue
I am not certain the exact cause, but using HTTPS Everywhere with myfitnesspal.com causes an error on the site.

Some details are here on a ticket opened by someone else with myfitnesspal.com

http://myfitnesspal.desk.com/customer/portal/questions/17101256-site-down-for-maintenance

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #11029.
Fix #11312.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Some comments:

- `platform="mixedcontent"` is probably not strictly needed. Indeed, the only mixed content I could find are ads (not a big loss IMO) and the website redirects to `https` on its own on this page.

**Comment by J0WI** [comment]
I would like to keep this rule activated, at least for some of the domains. Or would you like to create a separate file for selected redirects on the problematic hosts?
`platform="mixedcontent"` is definitely not needed here.

See also:
```
blog.myfitnesspal.com
community.myfitnesspal.com
images.myfitnesspal.com
tickers.myfitnesspal.com
tickers2.myfitnesspal.com

**Comment by Bisaloo** [comment]
Do you have a test url for images.fitnesspal.com?

The other subdomains look really broken and I don't think we can really secure anything on them. I tested with an account.

**Comment by Bisaloo** [comment]
I found a post from their tech team:

https://myfitnesspal.desk.com/customer/en/portal/articles/2840040-some-members-are-having-trouble-adding-food-to-their-food-diary-from-the-website

I am not entirely sure why they didn't contact us directly but it sounds like they don't want us to try and secure the site at the moment.

**Comment by J0WI** [comment]
> Do you have a test url for images.fitnesspal.com?

See e.g. `http://images.myfitnesspal.com/images/brands/4/584/4584_small.gif`

Yes, it's really sad that they couldn't contact us directly and now give us all the blame.

> "the actual login "lightbox" or pop-over window on the home page does send your login credentials via https."
> "We work with a number of ad aggregation companies, and these partners serve their ads to us via http."

If the "lightbox" is on an unencrypted page, you can still hijack it 🤦
And with this practices you can never secure cookies.
The excuse with adverts is also quire poor. Major advert networks support https. And they should never prefer adverts over security.
Sorry for the off-topic.

**Comment by J0WI** [comment]
LGTM, but this needs a rebase after #11274 has been landed.

**Comment by J0WI** [comment]
Thanks!

**Comment by cschanaj** [comment]
Fix #11941

**Pull request merged**
