### PR TITLE
[E-activist.com] Add exclusion

### PR DESCRIPTION
**Pull request by fuglede**
This fixes https://github.com/EFForg/https-everywhere/issues/7319

### CODE REVIEW

**Comment by jeremyn** [comment]
The test URL http://www.e-activist.com/ea-action/broadcast.record.message.click.do?ea.url.id=742999&amp;ea.campaigner.email=4DvyaN3Tko8gYHTECbwHV5ku6OPFCMj%2F&amp;ea.campaigner.id=MHk1zxzJpriZkArzVWMSmA==&amp;ea_broadcast_target_id=0 , which you got from https://github.com/EFForg/https-everywhere/issues/7319#issuecomment-253039002 , looks like it has personal identification stuff in it . Can you substitute a more generic URL from [Google](https://www.google.com/#q=site:www.e-activist.com%2Fea-action)?

**Comment by jeremyn** [comment]
I agree with the test URL change.

Do you think we should remove the general `securecookie` given this new exclusion?

**Comment by fuglede** [comment]
On 12 October 2016 19:10:10 CEST, Jeremy Nation <notifications@github.com> wrote:
>I agree with the test URL change.
>
>Do you think we should remove the general `securecookie` given this new
>exclusion?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/pull/7324#issuecomment-253276132

I did consider it briefly, but it looks like it should be safe? If the URLs matching the pattern all come from email newsletters, I think it should be, at least.

**Comment by jeremyn** [comment]
The failure case is if the user already has a secure `www.e-activist.com` cookie set in their browser, and the email URL is supposed to read it, but can't.

**Comment by fuglede** [comment]
Or for `e-activist.com` (which actually happens, even though the site serves nothing but redirects); it does seem unlikely to play any role here though, doesn't it?

**Comment by jeremyn** [comment]
Yeah, it would also be a problem if the `http` exclusion URL tried to read a secure `^e-activist.com` cookie.

Following the discussion in https://github.com/EFForg/https-everywhere/issues/2907 , I'm seeing fewer good cases for a wildcard `securecookie`. I would get rid of it for everything but the tiniest, simplest sites. But for this issue we can do whatever you prefer.

**Comment by fuglede** [comment]
Having no particularly strong opinion on the matter, I went ahead and removed the `securecookie`.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
