### PR TITLE
[WIP][Columbia.edu] Remove broken redirects

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by pipboy96** [comment]
ping @Bisaloo.

**Comment by ivysrono** [comment]
@pipboy96 This is too hard to maintain, I have no time to fix up it today.
Maybe this ruleset need to be totally rewriten.

**Comment by pipboy96** [comment]
@ivysrono probably yes, but these university websites may have up to a few millions of subdomains.

**Comment by pipboy96** [comment]
I will try to fix this ruleset later.

**Pull request closed without merging**
