### PR TITLE
add Gittigidiyor.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@jeremyn any chance to get this top host into the next release?

**Comment by jeremyn** [comment]
Add `target`:
- [ ] https://mhd.gittigidiyor.com , with an `exclusion` for `/$` (time out) and `test` of `http://mhd.gittigidiyor.com/servlet/files/19595`
- [ ] https://st.gittigidiyor.net , with an `exclusion` for `/$` (secure connection failed) and `test` of `http://st.gittigidiyor.net/rsrc/devgg/images/ebay-pt.png`

Mark `Secure connection failed`:
- [ ] https://gittigidiyor.net
- [ ] https://www.gittigidiyor.net

Also:
- [ ] https://mcdn01.gittigidiyor.net gets a `404` at `/$`, so add an `exclusion` for `/$` and `test` of `http://mcdn01.gittigidiyor.net/29801/tn24/298011980_tn24_0.jpg`
- [ ] Change ruleset `name` to `GittiGidiyor` and filename to `GittiGidiyor.xml`, since we have both `.com` and `.net` domains in this ruleset and the site itself uses this casing. Be sure to change the comment in `EBay.xml`, too.

Sublist3r shows a bunch of other domains like https://fotograf-kamera.gittigidiyor.com. I'll merge without them though, this is just FYI.

**Comment by J0WI** [comment]
I think an exclusion for `mcdn01.gittigidiyor.net/$`isn't necessary, the tests will pass anyway.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9251/commits/a628065638911225ece7532623c91838e0ad82f3 and added a minor new item based on your changes.

**Comment by J0WI** [comment]
I had a timeout before and now secure connection failed again. But I can confirm that HTTPS doesn't work at all.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
