### PR TITLE
Create TafasirStore.com.xml

### PR DESCRIPTION
**Pull request by Giltyhub2**

### CODE REVIEW

**Comment by J0WI** [comment]
This seems to be related to `Salla.sa.xml`. Could you document this in comments?

**Comment by Giltyhub2** [comment]
@J0WI thanks, done

**Comment by Giltyhub2** [comment]
> Please do the same on `Salla.sa.xml`

I don't think it makes sense for that one since this site just redirects to an online store on Salla.sa and it isn't officially related to that website.

**Comment by J0WI** [comment]
We always add cross ruleset references on both sides. If they are not related you can revert 627a868469a52057f655ce07ae3b20227d829b16.

**Comment by Giltyhub2** [comment]
@J0WI thanks, i will take that into consideration next time, meanwhile i reverted my change

**Pull request merged**
