### PR TITLE
Add rules for cdninstagram.com & igcdn.com

### PR DESCRIPTION
**Pull request by johnp**
Two simple rulesets for passive (instagram) content I encountered on wired.com (the second one is just an alternate name).

### CODE REVIEW

**Comment by reedy** [comment]
Can you provide an example where these are used? (or, more specifically, just urls that work on these cdn sites?)

Thanks

**Comment by johnp** [comment]
Reddit domains has some collected URLs here: 
http://i.reddit.com/domain/scontent-a.cdninstagram.com/

IIRC one can just replace '' cdninstagram '' with '' igcdn ''... 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by johnp** [comment]
I encountered these on ign.com; dunno if they're still used there. 

On April 10, 2015 3:51:27 AM CEST, Sam Reed <notifications@github.com> wrote:
>Can you provide an example where these are used? (or, more
>specifically, just urls that work on these cdn sites?)
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/pull/1151#issuecomment-91398772

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by reedy** [comment]
LGTM from simple testing

**Pull request merged**
