### PR TITLE
fixed sciencemag.org

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by fuglede** [comment]
Thanks for the update; however, the chain is still incomplete.

    $ curl -I https://www.sciencemag.org
    curl: (60) SSL certificate problem: unable to get local issuer certificate

**Comment by KOLANICH** [comment]
>Thanks for the update; however, the chain is still incomplete.
Why do we need it to be complete?

**Comment by fuglede** [comment]
Since otherwise users who have not cached the intermediate certificate and who do not download it automatically will receive warnings about the misconfiguration. See e.g. #3496.

**Comment by J0WI** [comment]
The chain seems to be fixed, but this branch needs to be rebased.

**Comment by jeremyn** [comment]
@KOLANICH Are you interested in working on this anymore? Otherwise I want to close the PR.

**Comment by KOLANICH** [comment]
OK, if I needed, I'd create a new one.

**Comment by jeremyn** [comment]
Okay, thanks @KOLANICH . I'm closing this pull request, but please feel free to reopen it with a comment or create a new pull request if you want to work on this more.

**Pull request closed without merging**
