### PR TITLE
Update ruleset: News Corporation

### PR DESCRIPTION
**Pull request by injust**

### CODE REVIEW

**Comment by J0WI** [comment]
The ruleset is still `default_off`, is this expected?
I would prefer new rulesets for each host and delete this one after all of them have been merged.

**Comment by injust** [comment]
Blocked on #16457 (for removal of dangling reference to `News-Corporation.xml`)

**Comment by injust** [comment]
@zoracon Why was this closed? `News-Corporation.xml` has been split into other rulesets and requires deletion.

**Comment by zoracon** [comment]
> @zoracon Why was this closed? `News-Corporation.xml` has been split into other rulesets and requires deletion.
Since the rule was already default off, I had assumed that there is no conflict with the rules that were split off from this one. I can reopen and merge. Reading through the history it seems the others were merged.

**Comment by injust** [comment]
Thanks, this was actually blocking a few other PRs from merging.

**Pull request merged**
