### PR TITLE
Add eslint config

### PR DESCRIPTION
**Pull request by CapacitorSet**
This PR adds the eslint config used in [EFForg/privacybadger](https://github.com/EFForg/privacybadger), and fixes some linting issues.

### CODE REVIEW

**Comment by J0WI** [comment]
@Hainish maybe this can also be added to Travis?

**Comment by CapacitorSet** [comment]
If it is approved, I can add it to Travis in the same PR.

**Comment by CapacitorSet** [comment]
Ping @Hainish, I fixed the weird braces.

**Comment by Hainish** [comment]
When I run the linter I'm getting a larger number of spaces before the opening of blocks.  I'm using your `.eslintrc.yml` file.  Any idea why this might be?

**Comment by koops76** [comment]
Duplicate of #10909, #10931 and #10932.

**Pull request closed without merging**
