### PR TITLE
Update Doodle.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@Hainish seems like this didn't trigger the labeler.

**Comment by Hainish** [comment]
Not sure why the labeller missed that on first pass.  It may be that one of the other PRs that were checked in the same run of the labeller was malformed, thus causing the node script to crash.  Seems to have labelled it correctly on this pass.

**Comment by jeremyn** [comment]
@J0WI Can this be rewritten without the wildcard `target`?

**Comment by J0WI** [comment]
Nope, see comment about "Premium users"

**Comment by jeremyn** [comment]
I think we should make this a `(partial)` ruleset and limit it to company domains, like I suggested for ning.com domains in PR https://github.com/EFForg/https-everywhere/pull/9536#issuecomment-341248319.

**Comment by J0WI** [comment]
The site has changed a lot, so I think we can get rid of the wildcard now.

**Comment by J0WI** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
