### PR TITLE
Fix rewrite rule for code.nsnam.org

### PR DESCRIPTION
**Pull request by labdsf**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your pull request. Why are you making this change? https://code.nsnam.org/ looks okay to me.

**Comment by ilabdsf** [comment]
@jeremyn 
Because everything except index does not work.
For example, http://code.nsnam.org/ns-3-dev is ok, but https://code.nsnam.org/ns-3-dev/ is 404.

**Comment by jeremyn** [comment]
I think I understand. In that case what you probably want are rewrite rules for `^http://code.nsnam.org/$` and `^http://code.nsnam.org/index.cgi/`, and any other URL that works, and no general rewrite rules. I don't think you should rewrite `^http://code.nsnam.org/$` to `^http://code.nsnam.org/index.cgi/`.

**Comment by ilabdsf** [comment]
@jeremyn General rewrite rule is for www.nsnam.org.

**Comment by labdsf** [comment]
@jeremyn Ping. I think I have fixed all the problems, is this change going to be merged?

**Comment by jeremyn** [comment]
I looked at this again and think that, despite what I wrote in https://github.com/EFForg/https-everywhere/pull/9273#issuecomment-290124897, your changes seem safe.

Thanks again, merged.

**Comment by labdsf** [comment]
@jeremyn It is probably because I force-pushed to this branch, so now you reviewed a different, updated version.

**Pull request merged**
