### PR TITLE
Update and rename beeg.xml to Beeg.com.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] I'm getting a `403` error for https://video.beeg.com . This needs a `test`.

**Comment by Folant** [comment]
@jeremyn It seems that all working `video.beeg.com` URLs is redirected to `*.ahcdn.com` and required to have some key specified (see `video.beeg.com/test.txt`) 
Test URLs like `video.beeg.com/data={platform}_{country_code}_{IP}_2509_HZmTBAH3/key={23_CHAR_KEY}2Cend=1514482984/720p/{VIDEO_ID}.mp4` have some expiration date, so they are probably useless.
There's probably no direct way to find URLs like that, other than through `F12 -> Network` on video pages. 
Should I mark it as `No working URL known` or we can add some comment about that?

**Comment by jeremyn** [comment]
Can you add instructions on how to find examples of `video.beeg.com` URLs, like we did at [`Hentai-Foundry.com.xml#L16-L17`](https://github.com/EFForg/https-everywhere/blob/599b34d8d2ed0b5ffd597b73e72f03bcf6c5f40e/src/chrome/content/rules/Hentai-Foundry.com.xml#L16-L17)?

**Comment by jeremyn** [comment]
The instructions should be a little more specific than what you have in https://github.com/EFForg/https-everywhere/pull/14029/commits/aa8ebe69d70a7ba3079aa6fdd42ee67d065a8877 since there are no `video` requests directly off https://beeg.com. More like:

```xml
	<!-- Test URLs for video.beeg.com can be found by clicking a thumbnail at
		https://beeg.com/ -->
```

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
