### PR TITLE
Delete DeusM-clients.xml

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Both https://internetevolution.com/ and https://www.internetevolution.com/ have invalid certificates, so probably `DeusM-clients.xml` should simply be deleted and the reference removed from `DeusM.xml`, without creating `InternetEvolution.com.xml`.

I guess Travis didn't catch the problem with these domains because git considered `InternetEvolution.com.xml` to be a renaming of `DeusM-clients.xml`, not a new ruleset.

**Comment by Bisaloo** [comment]
I think travis is acting as it should. `InternetEvolution.com.xml` is `default_off`. Should I remove it entirely?

**Comment by jeremyn** [comment]
That makes sense, with `default_off`.

Yes, please go ahead and remove/leave out `InternetEvolution.com.xml` entirely, thanks.

**Comment by Bisaloo** [comment]
@jeremyn, feel free to remove the intermediate commit messages when you squash.

**Comment by jeremyn** [comment]
Thanks, merged. (Also, FYI, I regularly remove all intermediate commit messages when I squash-and-merge.)

**Pull request merged**
