### PR TITLE
reenable LongTail.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
This needs some additional tests for all the exclusions.

**Comment by J0WI** [comment]
This rule needs a lot of work and the JW player is quite popular. Any help is welcome :)

**Comment by TheNavigat** [comment]
I might try helping with these. Can you give me a brief on the problem you're facing with JW player?

**Comment by J0WI** [comment]
fixed in #3531 :)

**Pull request closed without merging**
