### PR TITLE
[PolitiFact.com] Simplify ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by J0WI** [comment]
Host is currently broken.

**Comment by J0WI** [comment]
Looks like HTTPS is really broken here.

**Comment by Bisaloo** [comment]
I'm pretty sure it was working when I submitted with PR. Can we just keep this on hold? I don't think there is an urgent need to close this PR.

**Comment by J0WI** [comment]
Sure. I'll have another look before the next release.

**Comment by Bisaloo** [comment]
This looks severely outdated. Closing to the benefit of the recently merged PR #16518

**Pull request closed without merging**
