### PR TITLE
Run hsts-prune and fix impacted rulesets

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
@Hainish, I think the labeller script crashed again

**Comment by Hainish** [comment]
Closing to fix labeller

**Comment by Bisaloo** [comment]
@J0WI, I updated this. Only one additional target has been removed since your comment https://github.com/EFForg/https-everywhere/issues/16122#issuecomment-412341640.

**Comment by Hainish** [comment]
Looks good to me - thanks @Bisaloo !

**Pull request merged**
