### PR TITLE
Create Pornwikileaks.com.xml

### PR DESCRIPTION
**Pull request by ryanbr**
First commit, learning on the job. Just picked a domain to work on. any feedback welcome :)

### CODE REVIEW

**Comment by pipboy96** [comment]
mail.pornwikileaks.com
    ftp.pornwikileaks.com

**Comment by ryanbr** [comment]
`mail.pornwikileaks.com`

Okay.

`http://ftp.pornwikileaks.com/cgi-sys/defaultwebpage.cgi`

Seems to be 404.

**Comment by ryanbr** [comment]
What caused the failure?

**Comment by pipboy96** [comment]
You put your ruleset file into incorrect directory. I have fixed it.

**Pull request merged**
