### PR TITLE
Update opera.com rules

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
CI tests now pass.

**Comment by J0WI** [comment]
Would be great to have each subdomain commented.

works for me:
redir
people
get.geo.opera.com
download1.operacdn.com
www-static.operacdn.com
www-static-blogs.operacdn.com
(www.)operamediaworks.com
performance.operamediaworks.com
wiki.operamediaworks.com

Timeout:
help
blog.operamediaworks.com

404:
arc

Refused:
appcatalog
webpass
viettelappsclub

Mismatch:
business
[language subdomains]
(www.)operasoftware.com
demo.operamediaworks.com

**Comment by mathiasbynens** [comment]
@J0WI Could you submit that as a follow-up patch?

**Comment by J0WI** [comment]
Done in #4178

**Pull request closed without merging**
