### PR TITLE
Ruleset for dpskolkata.com

### PR DESCRIPTION
**Pull request by ankitpati**
Added a ruleset for a [site](https://www.dpskolkata.com/ "Delhi Public School, Ruby Park").

### CODE REVIEW

**Comment by J0WI** [comment]
This site has some mixed content issues. Can you confirm that this breaks no functionality?

**Comment by ankitpati** [comment]
No, the mixed content issues do not break any functionality. In fact, if the rule is added, users of HTTPS Everywhere will magically see the mixed content issues disappear.

Manually navigating to the HTTPS version gets you the HTML content over HTTPS, but it loads resources over insecure connections because the URLs have HTTP hardcoded into them. HTTPS Everywhere will rewrite all of those URLs, and make the page completely secure.

**Comment by J0WI** [comment]
The problem is, that the mixed content blocker of the browser blocks this content before we can redirect it.

**Comment by ankitpati** [comment]
Mixed content blocker? I believe that requires user action to enable. None of the browsers have it enabled by default. Most will just warn.

**Comment by J0WI** [comment]
All major browsers block mixed active content by default:
https://security.googleblog.com/2011/06/trying-to-end-mixed-scripting.html
https://blogs.msdn.microsoft.com/ie/2011/06/23/internet-explorer-9-security-part-4-protecting-consumers-from-malicious-mixed-content/
https://bugzilla.mozilla.org/show_bug.cgi?id=834836

**Comment by ankitpati** [comment]
Mixed ***active*** content gets blocked. The site serves all scripts over HTTPS when the HTML is requested over HTTPS. I tried browsing to all parts of the site, and Chrome did not report any blocked scripts.

**Comment by J0WI** [comment]
Firefox reports me mixed active content from `http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js`

**Comment by ankitpati** [comment]
Yes, there are mixed active content warnings, but they did not seem to affect the page in the browsing that I did, in both Chrome and Firefox.

Unrelated to this PR, but something that HTTPS Everywhere should consider: why not rewrite all recognised URLs in a page to HTTPS before the browser has a chance to take over? For example, the specific URL you have mentioned is already known to HTTPS Everywhere, and visiting it directly forces it to HTTPS.

**Comment by J0WI** [comment]
Thanks for your feedback. Therefore I'm fine with merging this.

For security reasons browsers do not allow Add-Ons to bypass their mixed content blocker like this. We could disable the mixed content blocker completely, like Tor does, but this brings MITM risks for all other sites, that are not redirected by HTTPS Everywhere.

**Comment by ankitpati** [comment]
Thank you for the merge.

**Pull request merged**
