### PR TITLE
Enable for www.montereybayaquarium.org

### PR DESCRIPTION
**Pull request by illicitonion**
The cert is only valid for www., so exclude the bare host.

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. If there is no `target` for a domain like `montereybayaquarium.org`, then it won't be matched and you don't need to add an `exclusion` for it.

**Comment by jeremyn** [comment]
Thanks. Please make the following changes. The ruleset should look something like [this one](https://github.com/jeremyn/https-everywhere/blob/245f2f8812d56a7c16d4982bf59b97252cfac0b1/src/chrome/content/rules/Juno.com.xml) when you're done.

Mark as `Invalid certificate`:
- [ ] https://montereybayaquarium.org
- [ ] https://tmp.montereybayaquarium.org

Mark as `Time out`:
- [ ] https://static.montereybayaquarium.org
- [ ] https://storage.montereybayaquarium.org

Add `target`:
- [ ] https://affiliate.montereybayaquarium.org
- [ ] https://m.montereybayaquarium.org
- [ ] https://mobile.montereybayaquarium.org
- [ ] https://newsroom.montereybayaquarium.org
- [ ] https://tickets.montereybayaquarium.org

Also:
- [ ] Delete [this 'test'](https://github.com/illicitonion/https-everywhere/blob/9969a6a0c35aaea02e5ee12b196fec267f41e948/src/chrome/content/rules/Monterey_Bay_Aquarium.xml#L8), because there is an implicit test created for the `target` already. See [the style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) for more information.
- [ ] Change [the `securecookie` `host`](https://github.com/illicitonion/https-everywhere/blob/9969a6a0c35aaea02e5ee12b196fec267f41e948/src/chrome/content/rules/Monterey_Bay_Aquarium.xml#L4) to `^(www|affiliate|m|mobile|newsroom|tickets)\.montereybayaquarium\.org`

Finally, we like to [squash and merge](https://help.github.com/articles/about-pull-request-merges/) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by illicitonion** [comment]
Thanks for taking the time :) I think everything's done now.

Happy to be squashed and merged.

For future reference, how did you generate that list of domains?

**Comment by jeremyn** [comment]
Thanks, I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7323/commits/6edf1dc84236aab0a3c0fa15f80f4e44d7c6a4d6 . The `securecookie` `host` should have a trailing `$`, which was not in my original checklist, so it's my fault you didn't have it. I've updated the checklist accordingly.

Also we normally only have e.g. `tmp.montereybayaquarium.org` in the top comment, not `https://tmp.montereybayaquarium.org` so please change that. I include `https://` to make it easy to click on from the GitHub comment but I understand how that might be confusing.

You can find those domains using the [Google search trick](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), [Sublist3r](https://github.com/EFForg/https-everywhere/issues/7277), and knowing that if `m.` is a domain, then `mobile.` might be too.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
