### PR TITLE
Create nvidia.ru.xml

### PR DESCRIPTION
**Pull request by kronblase**
Mentioned in #3069

### CODE REVIEW

**Comment by kronblase** [comment]
Help. I can not understand why it does not pass the test

**Comment by kronblase** [comment]
I do not know why the script does not pass the Travis check. There are no errors. The script is fully working. Even the driver is downloaded in the https version.

**Comment by jeremyn** [comment]
You have what look like non-breaking spaces in lines 2 and 3 of 7cc0780d4ebdd7a2790f7a75d9d905916a3b9e49:

```
$ xmllint --relaxng utils/relaxng.xml rules/nvidia.ru.xml 
<?xml version="1.0"?>
<ruleset name="nvidia.ru">        
&#xA0;&#xA0;&#xA0;<target host="nvidia.ru"/>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; 
   <target host="www.nvidia.ru"/>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; 
   <target host="ru.download.nvidia.com"/>	
   
   <rule from="^http://nvidia\.ru/" to="https://www.nvidia.ru/"/>
   <rule from="^http:" to="https:"/>
</ruleset>
rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Expecting an element test, got nothing
rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Expecting an element target, got nothing
rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Invalid sequence in interleave
rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Element ruleset failed to validate content
rules/nvidia.ru.xml fails to validate
$ 
```

It looks like `xmllint` doesn't like those characters.

Rulesets should be indented with tabs only and have no whitespace at the end of the lines. See [here](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#indentation--misc-stylistic-conventions) in `CONTRIBUTING.md` for more information.

Also, you can check this error yourself running `bash test.sh` locally, which runs `makexpi.sh`, which runs `utils/validate.sh`, which runs `xmllint`.

**Comment by kronblase** [comment]
Damned Unicode. Thanks for the help. I spent so much time looking for errors.

**Comment by jeremyn** [comment]
Yeah, that was tricky to figure out.

Can you please add back some of the subdomains you removed, like `store`?

**Comment by kronblase** [comment]
Done.

**Comment by jeremyn** [comment]
Please:

Mark as `Refused` in a top comment:
- [ ] https://nvidia.ru (and keep the redirect `rule`)
 
Add `target`:
- [ ] https://akamai-www.nvidia.ru
 
Also:
- [ ] Indent with tabs instead of spaces
- [ ] Sort the `target`s like you see [here](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#target-ordering) (for example `shield` should go before `store`)
- [ ] Move https://ru.download.nvidia.com to [`NVidia.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/NVidia.xml)
- [ ] [`NVidia.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/NVidia.xml) should refer to this ruleset [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/NVidia.xml#L4-L7) after `GeForce.com.xml`, and this ruleset should refer to `NVidia.xml` like you see [here](https://github.com/EFForg/https-everywhere/blob/403e25bfbf8fe29c06c60d6ed7b6b68cbbaf1e59/src/chrome/content/rules/ACLU-of-Arizona.xml#L3).

**Pull request closed without merging**
