### PR TITLE
Add k2b-bulk.ebay.de, fix ebay.de ruleset

### PR DESCRIPTION
**Pull request by ytausch**
This is a page for sellers on ebay - some links are still HTTP but HTTPS is available.

To see any content on this domain, you have to register on ebay.de, enable "Verkäufer-Cockpit Pro" on https://www.ebay.de/sh/landing, open "Mein ebay" at the top right, click on "Bestellungen" (orders), and select "Archiviert" (archived) on the left hand side. Adding a rule to HTTPS Everywhere upgrades this HTTP connection to HTTPS and does not break things.

### CODE REVIEW

**Comment by ytausch** [comment]
Why is Travis failing in `TEST="chrome beta" BROWSER=google-chrome-beta`? I only changed some ebay.de rules.

**Comment by ivysrono** [comment]
https://travis-ci.org/github/EFForg/https-everywhere/jobs/693888968#L450

**Comment by ytausch** [comment]
@ivysrono This domain sometimes works in your tests - but sometimes it fails. See https://travis-ci.org/github/EFForg/https-everywhere/jobs/693412263#L339 for a working example.

ebay DID NOT shut down this domain - see for example [here](https://cgi6.ebay.de/ws/eBayISAPI.dll?AdPreferenceInterstitialPopup&partner=0) or [here](https://cgi6.ebay.de/ws/eBayISAPI.dll?SolutionsDirectory&page=results&subgroup=8) or [here (Google)](https://www.google.com/search?q=site%3Acgi6.ebay.de). Its ruleset should not be deleted.

I guess cgi6.ebay.de is a weirdly behaving legacy domain...

**Comment by ytausch** [comment]
Finally working!

**Pull request merged**
