### PR TITLE
Update Sfconservancy.org

### PR DESCRIPTION
**Pull request by anand-bhat**

### CODE REVIEW

**Comment by anand-bhat** [comment]
New to git. Didn't realize that syncing my fork would cause that commit to be included in future pull requests.

**Comment by reedy** [comment]
Use branches :)

**Comment by anand-bhat** [comment]
Let me know if this pull request is usable. If it isn't, I'll read up on what I need to do without having to delete my fork and start over (I have other pull requests pending).

**Comment by rrooij** [comment]
@anand-bhat 
Look into using `git rebase -i`

**Comment by anand-bhat** [comment]
@rrooij @reedy Thanks! This pull request has been cleaned up to remove polluted commits.

**Comment by rrooij** [comment]
Nice. Glad to see that it helped. :+1:

**Pull request merged**
