### PR TITLE
Add rulesets for various thepiratebay.org proxies

### PR DESCRIPTION
**Pull request by koops76**
#11481, #11478.

Ping @J0WI.

### CODE REVIEW

**Comment by J0WI** [comment]
I'm not okay with removing the whole `proxybay.one.xml`. We still have a lot of working hosts there.

**Comment by koops76** [comment]
@J0WI OK, can you check which ones work, please?

**Comment by J0WI** [comment]
No, but we have tools for such jobs:

```
$ ./fetch-test.sh rules/proxybay.one.xml 
INFO Finished comparing http://pirateproxy.red/ -> https://pirateproxy.red/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.pirateproxy.red/ -> https://www.pirateproxy.red/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://ahoy.one/ -> https://ahoy.one/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thepiratebay.lu/ -> https://thepiratebay.lu/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thepiratebay.lu/ -> https://www.thepiratebay.lu/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://tpb.proxyduck.co/ -> https://tpb.proxyduck.co/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://tpb.patatje.eu/ -> https://tpb.patatje.eu/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thepirate.zone/ -> https://thepirate.zone/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thepirate.zone/ -> https://www.thepirate.zone/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thehiddenbay.xyz/ -> https://thehiddenbay.xyz/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thehiddenbay.xyz/ -> https://www.thehiddenbay.xyz/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://pbp.rocks/ -> https://pbp.rocks/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.piratesbay.pe/ -> https://www.piratesbay.pe/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://piratesbay.pe/ -> https://piratesbay.pe/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://tpb.dashitz.com/ -> https://tpb.dashitz.com/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thepiratesbay.pw/ -> https://thepiratesbay.pw/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thepiratesbay.pw/ -> https://www.thepiratesbay.pw/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thepiratebay.run/ -> https://thepiratebay.run/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thepiratebay.run/ -> https://www.thepiratebay.run/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://pirateportal.xyz/ -> https://pirateportal.xyz/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.pirateportal.xyz/ -> https://www.pirateportal.xyz/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://thepirateshore.eu/ -> https://thepirateshore.eu/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.thepirateshore.eu/ -> https://www.thepirateshore.eu/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://123bay.online/ -> https://123bay.online/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.123bay.online/ -> https://www.123bay.online/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://vicetorrent.com/ -> https://vicetorrent.com/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.vicetorrent.com/ -> https://www.vicetorrent.com/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://pirateproxy.club/ -> https://pirateproxy.club/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.pirateproxy.club/ -> https://www.pirateproxy.club/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://kuiken.co/ -> https://kuiken.co/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.kuiken.co/ -> https://www.kuiken.co/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://piratebayblocked.com/ -> https://piratebayblocked.com/. Rulefile: rules/proxybay.one.xml.
INFO Finished comparing http://www.piratebayblocked.com/ -> https://www.piratebayblocked.com/. Rulefile: rules/proxybay.one.xml.
ERROR rules/proxybay.one.xml: Fetch error: http://ahoy.one/ => https://ahoy.one/: (7, 'Failed to connect to ahoy.one port 443: Connection timed out')
ERROR rules/proxybay.one.xml: Fetch error: http://thepiratebay.lu/ => https://thepiratebay.lu/: (51, "SSL: no alternative certificate subject name matches target host name 'thepiratebay.lu'")
ERROR rules/proxybay.one.xml: Fetch error: http://www.thepiratebay.lu/ => https://www.thepiratebay.lu/: (51, "SSL: no alternative certificate subject name matches target host name 'www.thepiratebay.lu'")
ERROR rules/proxybay.one.xml: Fetch error: http://tpb.proxyduck.co/ => https://tpb.proxyduck.co/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR rules/proxybay.one.xml: Fetch error: http://thepirate.zone/ => https://thepirate.zone/: (7, 'Failed to connect to thepirate.zone port 443: Connection refused')
ERROR rules/proxybay.one.xml: Fetch error: http://www.thepirate.zone/ => https://www.thepirate.zone/: (7, 'Failed to connect to www.thepirate.zone port 443: Connection refused')
ERROR rules/proxybay.one.xml: Fetch error: http://pbp.rocks/ => https://pbp.rocks/: (6, 'Could not resolve host: pbp.rocks')
ERROR rules/proxybay.one.xml: Fetch error: http://www.piratesbay.pe/ => https://www.piratesbay.pe/: (6, 'Could not resolve host: www.piratesbay.pe')
ERROR rules/proxybay.one.xml: Fetch error: http://piratesbay.pe/ => https://piratesbay.pe/: (6, 'Could not resolve host: piratesbay.pe')
ERROR rules/proxybay.one.xml: Fetch error: http://thepiratesbay.pw/ => https://thepiratesbay.pw/: (51, "SSL: no alternative certificate subject name matches target host name 'thepiratesbay.pw'")
ERROR rules/proxybay.one.xml: Fetch error: http://www.thepiratesbay.pw/ => https://www.thepiratesbay.pw/: (51, "SSL: no alternative certificate subject name matches target host name 'www.thepiratesbay.pw'")
ERROR rules/proxybay.one.xml: Fetch error: http://thepiratebay.run/ => https://thepiratebay.run/: (7, 'Failed to connect to thepiratebay.run port 443: Connection timed out')
ERROR rules/proxybay.one.xml: Fetch error: http://www.thepiratebay.run/ => https://www.thepiratebay.run/: (7, 'Failed to connect to www.thepiratebay.run port 443: Connection timed out')
ERROR rules/proxybay.one.xml: Fetch error: http://thepirateshore.eu/ => https://thepirateshore.eu/: (51, "SSL: no alternative certificate subject name matches target host name 'thepirateshore.eu'")
ERROR rules/proxybay.one.xml: Fetch error: http://www.thepirateshore.eu/ => https://www.thepirateshore.eu/: (51, "SSL: no alternative certificate subject name matches target host name 'www.thepirateshore.eu'")
ERROR rules/proxybay.one.xml: Fetch error: http://123bay.online/ => https://123bay.online/: (6, 'Could not resolve host: 123bay.online')
ERROR rules/proxybay.one.xml: Fetch error: http://www.123bay.online/ => https://www.123bay.online/: (6, 'Could not resolve host: www.123bay.online')
ERROR rules/proxybay.one.xml: Fetch error: http://vicetorrent.com/ => https://vicetorrent.com/: (6, 'Could not resolve host: vicetorrent.com')
ERROR rules/proxybay.one.xml: Fetch error: http://www.vicetorrent.com/ => https://www.vicetorrent.com/: (6, 'Could not resolve host: www.vicetorrent.com')
ERROR rules/proxybay.one.xml: Fetch error: http://www.pirateproxy.club/ => https://www.pirateproxy.club/: (51, "SSL: no alternative certificate subject name matches target host name 'www.pirateproxy.club'")
ERROR rules/proxybay.one.xml: Fetch error: http://kuiken.co/ => https://kuiken.co/: (60, 'SSL certificate problem: certificate has expired')
ERROR rules/proxybay.one.xml: Fetch error: http://www.kuiken.co/ => https://www.kuiken.co/: (60, 'SSL certificate problem: certificate has expired')
INFO Finished in 135.90 seconds. Loaded rulesets: 1, URL pairs: 33.

**Comment by koops76** [comment]
@J0WI Review before the next release please.

**Comment by J0WI** [comment]
Please make sure that all tests are passing.

**Comment by koops76** [comment]
@J0WI Done.

**Pull request merged**
