### PR TITLE
Update yikeweiqi.com.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by pipboy96** [comment]
```xml
<!--
	HTTP ≠ HTTPS:
		- go4go

	Mismatched:
		- res
-->
<ruleset name="yikeweiqi.com">
	<target host="yikeweiqi.com" />
	<target host="www.yikeweiqi.com" />
	<target host="apis.yikeweiqi.com" />
	<target host="baoming.yikeweiqi.com" />
	<target host="cdn.yikeweiqi.com" />
	<target host="image.yikeweiqi.com" />
	<target host="portal.yikeweiqi.com" />
	<target host="rtgame.yikeweiqi.com" />
	<target host="share.yikeweiqi.com" />

	<securecookie host=".+" name=".+" />

	<rule from="^http:" to="https:" />
</ruleset>
```
`golinksworld.com` rules should be a part of a separate ruleset file.

**Comment by ivysrono** [comment]
@pipboy96 the domains `*.golinksworld.com` belong the yikeweiqi company, and are used in yikeweiqi.com , last but not least, they are equal to cdn.yikeweiqi.com , so in my opinion, we should add comments as detailed as possible and put them in one ruleset file.

**Comment by pipboy96** [comment]
@ivysrono OK, keep them.

**Comment by ivysrono** [comment]
@pipboy96 thanks. Would you please review my other [PRs](https://github.com/EFForg/https-everywhere/pulls/ivysrono) ?

**Pull request merged**
