### PR TITLE
Webextensions

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by Hainish** [comment]
These are the builds I've been using (with minor modifications) for the dev version.  I plan on merging these before a new WebExtensions release early next week.

**Comment by Hainish** [comment]
Note: once this is merged remember to inform the Tor Project since they have `./makexpi` hard-coded in their build scripts.

**Comment by koops76** [comment]
@Hainish I think it's a good idea to delete everything but `src/chrome/content/rules` from `src` in this PR since we are not using this code base anymore.

**Comment by Hainish** [comment]
@koops76 we also need `src/META-INF` for our release process and `src/chrome/locale` for translations.  We may change the locations of these paths in the future, but it's not necessary for WebExtensions launch.

**Comment by Hainish** [comment]
Creating a merge commit for granularity's sake, since so many files have changed.

**Comment by koops76** [comment]
@Hainish You may delete the `webextensions` branch now.

**Pull request merged**
