### PR TITLE
Update default_off="mismatched" rulesets

### PR DESCRIPTION
**Pull request by cschanaj**
Related: #9906

### CODE REVIEW

**Comment by Bisaloo** [comment]
You should also add `expired`.

**Comment by cschanaj** [comment]
We have around 218 variants of error messages... I think we should figure out a list of keyword first...

**Comment by cschanaj** [comment]
FYI, I would like to work on updating the `default_off` messages first. Then modify `relaxng.xml` to enforce the grammar, please refer to 9906 if you are interested.

**Comment by cschanaj** [comment]
Revert 6a3fc30f89e9a95c1123167f80e5c003ec491fe7 because it was caused by #9891

**Pull request merged**
