### PR TITLE
[Infogr.am] Disable subdomain e.infogr.am

### PR DESCRIPTION
**Pull request by fuglede**
This particular subdomain has caused issues a number of places, and the most recent ones do not suggest an easy fix. This closes https://github.com/EFForg/https-everywhere/issues/6791.

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Did you mean to remove the `securecookie`? The `host` was for everything except `e.infogr.am`.

**Comment by fuglede** [comment]
Good catch; I was a bit too fast there.

**Comment by jeremyn** [comment]
You can change it to just `<securecookie host=".+" name=".+" />`, of course there is no need to refer to `e.infogr.am` any more.

**Comment by fuglede** [comment]
Looks like you're right. I was wondering if this was there to somehow prevent infogr.am from settings cookies on the subdomain specifically, but that's not possible anyway. Updated.

**Comment by jeremyn** [comment]
Do you mean the problem of setting a cookie on `.infogr.am` that now can't be read on `e.infogr.am`? The only way we can fix that is to not use `securecookie` at all. Both options are equally good/bad.

**Comment by jeremyn** [comment]
Should I just merge this, then?

**Comment by fuglede** [comment]
Yep, no further changes from here.

**Comment by jeremyn** [comment]
Done.

**Pull request merged**
