### PR TITLE
Re-activate and Update MSFN.org.xml

### PR DESCRIPTION
**Pull request by cschanaj**
Related: #9842

### CODE REVIEW

**Comment by Tallefer** [comment]
"Follow content" is not working, instead of a subscription options menu a small popup is shown with "There was a problem loading this content." Some other site functions are similarly affected.

**Comment by J0WI** [comment]
@Tallefer could you please open an issue?

**Comment by Tallefer** [comment]
I will, but I didn't find any clear guidelines for doing that. :) Could you show me some proper one to copy its style?

**Comment by J0WI** [comment]
That one has quite a complex regex, but that's how we make exclusions: https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/amazon.in.xml

**Pull request merged**
