### PR TITLE
Add pittsburgzoo.org

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Change the [ruleset name](https://github.com/illicitonion/https-everywhere/blob/769cccec018e685917dc577f2697127553abf2fa/src/chrome/content/rules/PittsburghZoo.org.xml#L5) to `Pittsburgh Zoo`.

Also, with your permission, I'll modify the commit message for https://github.com/EFForg/https-everywhere/pull/7479/commits/769cccec018e685917dc577f2697127553abf2fa in the squash-and-merge to  `Add pittsburghzoo.org`.

**Comment by jeremyn** [comment]
Thanks. Do you want me to correct the commit message? Or you can squash/rewrite your commits here instead if you prefer. Or we can just leave it.

**Comment by illicitonion** [comment]
Feel free to rewrite as you wish :)

**Comment by jeremyn** [comment]
Thanks, merged.

I modified the squashed commit message, deleted the individual commit messages, and edited the GitHub pull request title.

**Pull request merged**
