### PR TITLE
Add chaosradio.ccc.de

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Comment by J0WI** [comment]
I fear the whole rule needs to be rebased to match our current style.
Would you like to do this?

**Comment by jeremyn** [comment]
@dotlambda Are you still interested in working on this?

**Comment by dotlambda** [comment]
Actually, I don't think I'm gonna do any more work on this.
I'm sorry.

**Comment by jeremyn** [comment]
That's fine, thanks for updating the issue @dotlambda .

**Pull request closed without merging**
