### PR TITLE
add rule for Queer.de

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

In a top comment:
- [ ] Note `queer.de` and `www.queer.de` under `Redirect to HTTP`
- [ ] Note `en.queer.de` under `Mixed content` (see below)

Also:
- [ ] Do you need the complicated rule and tests [here](https://github.com/numismatika/https-everywhere/blob/b32ca43fed7d7b28192a4c77443fe13b34bb117c/src/chrome/content/rules/Queer.de.xml#L9-L17)? If I comment them out, the test URLs I checked are still caught by the general rule at the end.
- [ ] Add support for `en.queer.de`. Unfortunately this site has broken mixed content, for example the YouTube videos don't show up at https://en.queer.de/2013/09/01/berlin-thousands-protest-russian-anti-gay-law/ . So, add a `target` for `en.queer.de` and a `rule` for `http://en\.queer\.de/(wp-content|wp-includes)/`

**Comment by jeremyn** [comment]
[This error](https://travis-ci.org/EFForg/https-everywhere/jobs/167858602#L206-L211) is happening in the tests because you need a leading `^` [here](https://github.com/numismatika/https-everywhere/blob/26e3fd42a1d186cf19aed0dc7f2b8d7638498a39/src/chrome/content/rules/Queer.de.xml#L14).

**Comment by jeremyn** [comment]
@numismatika Do you need any help or have any questions about what to do here?

**Comment by numismatika** [comment]
@jeremyn they killed TLS outside of www&^ , but also switched to LetsEncrypt as CA there.
It is a waste of time to work on this for now if they are changing their page.
Hopefully it is a sign for upcoming proper TLS support.

**Comment by jeremyn** [comment]
This ruleset is still valid with some changes and I think we should move forward with it. However if you want to stop, then we can close the pull request and I'll un-assign myself from it.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7007/commits/6a60040503813449952e7ca8da2fc0822bb06657 . For the remaining items:

* Instead of [this comment](https://github.com/numismatika/https-everywhere/blob/6a60040503813449952e7ca8da2fc0822bb06657/src/chrome/content/rules/Queer.de.xml#L2), note them under a section like you did for `Cert mismatch`
* `queercom.de` should go under `queer.de` in the top comment and for the targets
* `en.` should go between `ads.` and `mobil.` in the comment
* You can delete the complicated rule and tests that I noted in the checklist

Also, re-add a target for `queer.de`.

**Comment by jeremyn** [comment]
@numismatika It's been a while on this one. Can we move forward with this?

**Comment by numismatika** [comment]
Rebased to current master and amended

**Comment by jeremyn** [comment]
Some small changes:

- [ ] Change the top comment to:
```xml
<!-- 
	Invalid certificate:
		- ad.queer.de
		- ads.queer.de
		- en.queer.de
		- mobil.queer.de
		- wap.queer.de
		- mail.queercom.de

	Redirect to http:
		- (www\.)?queer.de/$
-->
```

This standardizes the `Cert mismatch on` comment, orders the two groups alphabetically with `Invalid...` first and `Redirect...` second, and clarifies the `Redirect to http` exclusion.
- [ ] Remove [these blank lines](https://github.com/numismatika/https-everywhere/blob/8a875f7dc1c7537f69e0a132dd92c7247b531cdf/src/chrome/content/rules/Queer.de.xml#L22-L23)

**Comment by jeremyn** [comment]
Hi @numismatika , it'd be nice to get this one done, especially since the remaining changes are small. If for some reason you can't do it, let me know and I'll push the changes myself, though then we'll need to wait for another reviewer to review my changes.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
