### PR TITLE
Add Freerangekitten.com.xml as a simple ruleset (controlled by EFF) a…

### PR DESCRIPTION
**Pull request by Hainish**
…nd use it for the URL rewrite test

### CODE REVIEW

**Comment by jeremyn** [comment]
Great, thanks @Hainish.

Do you want to make a note in the file that this is an EFF site and/or is used in our tests and/or that empty responses are expected?

Also, you can remove the current no-information top comment. (I know it's added by the provided ruleset generator.)

**Comment by Hainish** [comment]
@jeremyn comment added in both `EFF.xml` and `Freerangekitten.com.xml`

**Comment by Hainish** [comment]
This failed due to a certificate expiration for https://globalchokepoints.org/, which I believe is a problem we need to fix.  I'll follow up with the internal team which handles this and comment on this issue when that's resolved.

**Comment by Hainish** [comment]
The certificate problem is fixed, re-running fetch test.

**Pull request merged**
