### PR TITLE
[Airbnb] Remove right and left wildcards

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by J0WI** [comment]
I would keep the wildcards here, because Airbnb owns most TLD, even if they are not all secured. It's unlikely to break any third party site that are not fishy.
We have the same behavior for other high traffic sites like Google.

**Comment by Bisaloo** [comment]
There is no loss of coverage in the modifications I made.

**Comment by Bisaloo** [comment]
Also, the contributing guide says that right wildcards are "*highly discouraged*".

**Comment by J0WI** [comment]
Yes, the current list of TLDs is incomplete. Here are some random examples:
* airbnb.at
* airbnb.be
* airbnb.com.br
* airbnb.co.nz
* airbnb.fi
* airbnb.lu
* airbnb.mx
* airbnb.no
* airbnb.se
* airbnb.co.ve

**Comment by Bisaloo** [comment]
Even though they are included in the wildcard, there was no rule to rewrite those hosts.

**Comment by J0WI** [comment]
Well, yes. There is no regression in this PR. But what are your doubts to not expand the coverage?

**Comment by Bisaloo** [comment]
I know I could merge the two first rewrite rules but I think it is clearer that way.

**Comment by J0WI** [comment]
Well, I'm sure there are many more TLD, but le't go with this for now. Thanks!

**Pull request merged**
