### PR TITLE
[Mbl.is] Add exclusion to fix redirect loop and breakage

### PR DESCRIPTION
**Pull request by fuglede**
The entirety of the "fasteignir" subpage would appear to serve redirects to HTTP, so we exclude that to avoid some loops. In some (but apparently not quite all) cases, this would also break the search form on http://www.mbl.is/fasteignir/.

### CODE REVIEW

**Comment by J0WI** [comment]
The wildcard target will need some test urls for future tests.

**Comment by fuglede** [comment]
In case the testing mechanism is changed, you mean? For now it runs fine.

**Comment by J0WI** [comment]
I required them in the past as documented in our guides.

**Comment by fuglede** [comment]
Yeah, it's also pretty strange that it didn't complain. Anyway, I added a few.

**Comment by J0WI** [comment]
Rule lgtm.
Could you add comments for the refused secure connection on `icelandmonitor.mbl.is` and `media.mbl.is`?

**Comment by fuglede** [comment]
Done.

**Pull request merged**
