### PR TITLE
Fixes #2274 and #2430

### LINKED ISSUE #2274: List of broken rules.
I have an extensive list of rules that break websites. What's the prefered mode of action? Should I post them here in one thread? Should I make a separate issue for each rule? Or should I go and add `default_off="Breaks site"` to each rule?
Thanks.

### PR DESCRIPTION
**Pull request by terrorist96**
https://github.com/EFForg/https-everywhere/issues/2274#issuecomment-139583876

### CODE REVIEW

**Comment by TheNavigat** [comment]
It would be nice if you could squash the "Fixes #2274 partially" commits.

**Comment by terrorist96** [comment]
What's that mean?

**Comment by semenko** [comment]
`default_off="breaks site"` is a bit of a nuclear option. Please don't use it in these rules -- unless the sites are truly, irreparably broken.

Here, lots of these rules look valid. my.teslamotors.com almost certainy works (see https://my.teslamotors.com/user/login) -- the issue in https://github.com/EFForg/https-everywhere/issues/2274#issuecomment-122752763 is better addressed as an exclusion -- we shouldn't disable the whole site.

(Same for secure.websimages.com, etc.)

**Comment by TheNavigat** [comment]
You can merge commits, or squash them, into a single commit using a command that git offers called "rebase". I think that article explains it nicely. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

The reason why I think that's preferable is because the 3 commits are basically the same thing. It's only logical to merge them into a single commit.

**Comment by terrorist96** [comment]
I don't know anything about how to do this stuff. I understand it's the nuclear option, but it's the only option I know that works and no one else has volunteered to fix these rules (or hasn't fixed them by their attempt).

**Comment by semenko** [comment]
Hey cool -- take a look at this ruleset styleguide: https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

There aren't hard rules for when it's OK to disable a ruleset. It's a balancing act between "How severely is the site broken?" and "How important is the site?"

For the Tesla example above -- it's clearly a very popular site (and has user login pages, etc.) -- and the breakage isn't huge (breaking a side panel on their interactive map) -- so it's not a site we'd `default_off`.

**Comment by terrorist96** [comment]
So can you please show me the correct way to fix it? I looked at your link, but it doesn't give me insight into how to fix this. Thanks.

**Comment by terrorist96** [comment]
...?

**Comment by TheNavigat** [comment]
Sorry about that, almost everyone is busy right now, including EFForg's members who are busy working on Let's Encrypt.

Giving help on 4 different file edits is counter-productive. What I think you should start with is to create an independent branch for each of the commits, and then create independent Pull Requests.

To do that, first of all, reset your repo to the remote HEAD commit.

```git reset --hard HEAD~4```

4 here is the number of commits you want to skip. In this case, it's 4, since according to the PR you only had 4 commits on the master branch. If you have additional local commits, you should adjust the number accordingly.

Also, that command will delete all your edits so make sure you save them somehow.

After doing that, create a new branch.

```git checkout -b branchname```

And of course replace branchname with the desired branch name you'd like to have. That command will also switch to the new branch automatically.

When you're on that branch, apply the edits, preferably for only 1 file. Commit normally and push the branch to your repository using ```git push origin branchname```. Afterwards, use Github's website to initiate a pull request.

Switch back to master branch using ```git checkout master```, create another branch, and apply edits to another ruleset, and so on, creating an independent PR for each site. That makes the PRs more organized and makes it easier for people to help.

**Comment by terrorist96** [comment]
I don't know where I'm supposed to input those commands. I'm not a programmer/dev. I'm just trying to help fix some broken rules so https everywhere doesn't ruin people's web experience.

**Comment by TheNavigat** [comment]
In any case I don't really have write access, so I'd rather ping @fuglede

**Comment by semenko** [comment]
Closing since this has some outstanding work and hasn't been touched in a while. Feel free to re-open if you'd like this merged. :+1:

**Pull request closed without merging**
