### PR TITLE
censornet.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you please check for other subdomains here?

**Comment by galeksandrp** [comment]
Added.

**Comment by J0WI** [comment]
There are also:
blud.censornet.com
secure.censornet.com
apt.censornet.com
vma.aus.censornet.com

You can use Google to find them:
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by galeksandrp** [comment]
Added, thanks.

**Pull request merged**
