### PR TITLE
Create busnavi-okinawa.com.xml

### PR DESCRIPTION
**Pull request by ipaucek4680**

### CODE REVIEW

**Comment by pipboy96** [comment]
```
busnavi-okinawa.com
dns2.busnavi-okinawa.com
ns2.busnavi-okinawa.com
ns1.busnavi-okinawa.com
smtp.busnavi-okinawa.com
tt.busnavi-okinawa.com
www2.busnavi-okinawa.com
```

Please try these too.

**Comment by ipaucek4680** [comment]
```
busnavi-okinawa.com: no DNS A record, cannot resolve IP address
dns2.busnavi-okinawa.com: no website available, probably a DNS (Nameserver) subdomain
ns2.busnavi-okinawa.com: DNS (Nameserver) subdomain, no website available
ns1.busnavi-okinawa.com: DNS (Nameserver) subdomain, no website available
smtp.busnavi-okinawa.com: SMTP server subdomain, no website available
tt.busnavi-okinawa.com: no website available / timeout
www2.busnavi-okinawa.com: no website available / timeout
```

**Comment by pipboy96** [comment]
Please add comment:

**Comment by Bisaloo** [comment]
I'd rather not have this comment. It doesn't have any useful info. Some rulesets have it but mainly because they haven't been updated in a very long time. Otherwise LGTM!

**Comment by ipaucek4680** [comment]
I will close this first and submit a new pull request then.

**Pull request closed without merging**
