### PR TITLE
Remove shopping.rsbp.org.uk

### PR DESCRIPTION
**Pull request by illicitonion**
It's currently broken. I have gotten in touch, but there will naturally
be some lag in getting a fix.

### CODE REVIEW

**Comment by J0WI** [comment]
Could you please use regex exclusions for the specific locations?

**Comment by gloomy-ghost** [comment]
Is this still an issue?

**Comment by illicitonion** [comment]
Sorry, just checked this - the entire subdomain is broken, so I guess I can use a regex exclusion, but it will look like:

```
<target host="shopping.rspb.org.uk" />
<exclusion pattern="^http://shopping\.rspb\.org\.uk/.*" />
```

which seems a little pointless?

**Comment by illicitonion** [comment]
(Each of the pages will load and display, but if you try to interact with them, they are all broken)

**Comment by gloomy-ghost** [comment]
Yes I see, let's just merge it

**Pull request merged**
