### PR TITLE
Misc New Rulesets

### PR DESCRIPTION
**Pull request by StevenRoddis**

### CODE REVIEW

**Comment by jsha** [comment]
When I run the manual checker (which does fetching) I get these errors:

```
git diff --name-only master -- src | xargs ls | xargs python2.7 https-everywhere-checker/src/https_everywhere_checker/check_rules.py https-everywhere-checker/manual.checker.config
...
ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://ib.nab.com.au/ => https://ib.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): (7, 'Failed to connect to ib.nab.com.au port 80: Connection refused')
ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://mobile.nab.com.au/ => https://mobile.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): (51, "SSL: no alternative certificate subject name matches target host name 'mobile.nab.com.au'")
ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://nabconnect1.nab.com.au/ => https://nabconnect1.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): Redirect for 'https://nabconnect1.nab.com.au/' missing Location
ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://nabconnect2.nab.com.au/ => https://nabconnect2.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): Redirect for 'https://nabconnect2.nab.com.au/' missing Location
ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://auth.nabtrade.com.au/ => https://auth.nabtrade.com.au/ set([<Rule from '^http:' to 'https:'>]): (28, 'Connection timed out after 10000 milliseconds')
```

**Comment by StevenRoddis** [comment]
>ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://ib.nab.com.au/ => https://ib.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): (7, 'Failed to connect to ib.nab.com.au port 80: Connection refused')

Should this be an error? It can connect over HTTPS just not HTTP.

> ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://mobile.nab.com.au/ => https://mobile.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): (51, "SSL: no alternative certificate subject name matches target host name 'mobile.nab.com.au'")

Hm.. they must have discontinued their mobile web interface. Removing.
```
http://mobile.nab.com.au
HTTP/1.1 301 Moved Permanently
Date: Sat, 28 Feb 2015 05:33:35 GMT
Server: IBM_HTTP_Server/6.0.2.43 Apache/2.0.47 (Unix)
Location: http://www.nab.com.au/
```

>ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://nabconnect1.nab.com.au/ => https://nabconnect1.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): Redirect for 'https://nabconnect1.nab.com.au/' missing Location
>ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://nabconnect2.nab.com.au/ => https://nabconnect2.nab.com.au/ set([<Rule from '^http:' to 'https:'>]): Redirect for 'https://nabconnect2.nab.com.au/' missing Location

This appears to be because:
```
HTTP/1.1 302 Moved Temporarily
content-length: 1
content-type: text/html
date: Sat, 28 Feb 2015 05:30:13 GMT
location: https://nabconnect1.nab.com.au/auth/nabclogin/login.do?TAM_OP=login
```
HTTP spec says headers are case insensitive. Could we adjust our checker for that?

>ERROR src/chrome/content/rules/NAB.xml: Fetch error: http://auth.nabtrade.com.au/ => https://auth.nabtrade.com.au/ set([<Rule from '^http:' to 'https:'>]): (28, 'Connection timed out after 10000 milliseconds')

It connects for me, however the http url does not
```
https://auth.nabtrade.com.au
HTTP/1.1 403 Forbidden
Date: Sat, 28 Feb 2015 05:31:53 GMT
Server: Oracle-Application-Server-11g
Content-Type: text/html; charset=iso-8859-1
```

**Comment by jsha** [comment]
The "can't connect on port 80" error is correct. If a site doesn't provide any services on port 80, there are no links on the web to their port 80 version, and they must additionally expect that it's unusual to type in that site name by hand. I think we should in general only include rules that rewrite an actually-existing HTTP website to an HTTPS website.

The Location thing is indeed a bug in the checker, I'll work on it.

**Comment by StevenRoddis** [comment]
I'd take a slightly different view in that HTTPS-Everywhere should be forcing HTTPS whenever possible.

**Comment by jsha** [comment]
Unfortunately, that's not a clearly-defined goal. HTTPS Everywhere aims to replace an insecure URL with an equivalent secure URL. If there is no insecure URL, we can't define what it means for the secure URL to be equivalent.

**Comment by jsha** [comment]
I updated the checker to look for headers in a case-insensitive way.

**Comment by jsha** [comment]
Here are the latest errors I get from this rule. You can disregard the timeouts but some of the SSL errors are real:

```
ERROR src/chrome/content/rules/ShoeShow.xml: Fetch error: http://shoeshow.com.au/ => https://shoeshow.com.au/: (51, "SSL: no alternative certificate subject name matches target host name 'shoeshow.com.au'")
ERROR src/chrome/content/rules/ForeverNew.xml: Fetch error: http://forevernew.com.au/ => https://forevernew.com.au/: (35, 'Unknown SSL protocol error in connection to forevernew.com.au:443 ')
ERROR src/chrome/content/rules/GEMoney.xml: Fetch error: http://apply.gemoney.com.au/ => https://apply.gemoney.com.au/: (28, 'Connection timed out after 10001 milliseconds')
ERROR src/chrome/content/rules/GEMoney.xml: Fetch error: http://28degrees-online.gemoney.com.au/ => https://28degrees-online.gemoney.com.au/: (28, 'Connection timed out after 10001 milliseconds')
ERROR src/chrome/content/rules/MEBank.xml: Fetch error: http://mebank.com.au/ => https://www.mebank.com.au/: (35, 'Unknown SSL protocol error in connection to www.mebank.com.au:443 ')
ERROR src/chrome/content/rules/MEBank.xml: Fetch error: http://www.mebank.com.au/ => https://www.mebank.com.au/: (35, 'Unknown SSL protocol error in connection to www.mebank.com.au:443 ')
ERROR src/chrome/content/rules/MEBank.xml: Fetch error: http://apply.mebank.com.au/ => https://apply.mebank.com.au/: (28, 'Connection timed out after 10000 milliseconds')
ERROR src/chrome/content/rules/MEBank.xml: Fetch error: http://ib.mebank.com.au/ => https://ib.mebank.com.au/: (28, 'Connection timed out after 10001 milliseconds')
```

**Comment by StevenRoddis** [comment]
Thanks.

I must have skipped checking if non-www worked.
The others appear to connect with no problems for me even in curl.

**Comment by StevenRoddis** [comment]
Is this waiting on anything?

**Comment by jsha** [comment]
Thanks for the reminder!

**Pull request merged**
