### PR TITLE
Create sumatrapdfreader.org.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by jeremyn** [comment]
@kjk Are you okay with HTTPS Everywhere forcing HTTPS for http://sumatrapdfreader.org and http://www.sumatrapdfreader.org ? HTTPS blocks the Google ad. I notice the certificate is new so maybe you're still setting things up.

**Comment by kjk** [comment]
Sure, that's fine.

**Comment by jeremyn** [comment]
Great, thanks @kjk .

**Comment by jeremyn** [comment]
@ivysrono Thanks, merged.

**Pull request merged**
