### PR TITLE
Added hotpepper

### PR DESCRIPTION
**Pull request by luixxiul**

### CODE REVIEW

**Comment by luixxiul** [comment]
Updated, please review.

**Comment by jeremyn** [comment]
Thanks for the ruleset! Please add a target for `hotpepper.jp`, but otherwise it looks good.

**Comment by luixxiul** [comment]
Rebased and added ``hotp.jp``. Resources delivered from this domain can be found on ``http://beauty.hotpepper.jp/``

**Comment by jeremyn** [comment]
Please remove the tests from `hotp.jp`. The default tests for the targets are fine.

Contrary to my advice in other issues, please don't rebase/squash. It's easier for me to see changes if you don't squash.

**Comment by luixxiul** [comment]
I see, but I do not want to see my comments of commits left in the commit squashed at merging like [this](https://github.com/EFForg/https-everywhere/commit/945d8c74b00570fa16f358392b8e1133ab25e163). I will let you know difference by commenting on PR page, if you do not mind.

**Comment by luixxiul** [comment]
FYI if you leave a note on files changed, you can track the diff. Please see: https://github.com/EFForg/https-everywhere/pull/6457

**Comment by jeremyn** [comment]
I'm sorry but I need to insist that you don't squash. When you squash, I need to look through the entire new commit.

**Comment by luixxiul** [comment]
OK but plz don't leave the commit messages

**Comment by jeremyn** [comment]
I don't want to handle merge commits differently for you than for others. That might be confusing to anyone reviewing the history.

If you're worried that multiple `Update X` commits looks silly, you could use more descriptive git commit messages. I don't think it's a big deal either way though.

Is that all right? I don't want to merge your changes if you're uncomfortable.

**Comment by luixxiul** [comment]
Because my primary object was to make the ruleset of Rakuten, which was merged in #5827, I don't care well the other PRs I have done.

**Pull request closed without merging**
