### PR TITLE
Deletes the rules for PostNord.se and Posten.se.

### PR DESCRIPTION
**Pull request by davorb**
This company has changed their website(s), which has lead to this rule no longer working. Unfortunately, it can't be fixed either, since their changes broke their SSL-functionality.

### CODE REVIEW

**Comment by J0WI** [comment]
This conflicts, @davorb could you check if this PR is still needed?

**Comment by davorb** [comment]
@J0WI This seems to have been fixed in #5355, which turned the rule off instead of deleting it.

`<ruleset name="PostNord.se" default_off="Causes redirect loop">`

`Posten.se` should still be deleted, though. Posten AB has merged together with another company and changed their name, and all that domain does (and will continue to do) is redirect to `postnord.se`. I could open a new pull request that does that.

**Comment by fuglede** [comment]
Whoops, sorry, I hadn't seen this PR when I submitted mine. Please do feel free to open a PR for fixing posten.se as well.

**Comment by fuglede** [comment]
Ah, posten.se has already been submitted as well; https://github.com/EFForg/https-everywhere/pull/6488.

**Comment by J0WI** [comment]
closing by #6601

**Pull request closed without merging**
