### PR TITLE
Create annmichaelsen.com.xml

### PR DESCRIPTION
**Pull request by 6u621jpq6ybdw**

### CODE REVIEW

**Comment by koops76** [comment]
@6u621jpq6ybdw Can you create one PR per five created rulesets? You currently create lots of PRs that clutter the list. Also maybe you can wait until some of your current PRs are merged to not overburden the reviewers?

**Comment by 6u621jpq6ybdw** [comment]
@koops76 I followed `CONTRIBUTING.md` suggestion of one ruleset per PR, but if that's a problem I can as well use your proposition.

**Comment by koops76** [comment]
@6u621jpq6ybdw It's only a problem if there's a very high number of rulesets created at once.

**Comment by J0WI** [comment]
I prefer to have one PR for each new rule.

**Pull request merged**
