### PR TITLE
Create ptt.cc.xml

### PR DESCRIPTION
**Pull request by chennien**

### CODE REVIEW

**Comment by J0WI** [comment]
Please have a look ad our docs, especially [this](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains) topic. This will save us a lot of work wen reviewing your pending PRs.

**Comment by jeremyn** [comment]
@chennien Please:

- [ ] Make the ruleset look like this:

```xml
<!--
    Invalid certificate:
        news.ptt.cc
        pcman.ptt.cc
  
    Secure connection failed:
        ptt.cc
  
--> 
<ruleset name="ptt.cc">
    <target host="www.ptt.cc" />
    <target host="images.ptt.cc" />
        <test url="http://images.ptt.cc/bg6.gif" />
    <target host="mrtg.ptt.cc" />
    <target host="ptt20.ptt.cc" />
    <target host="term.ptt.cc" />
 
    <rule from="^http:"
        to="https:" />
</ruleset>
```
- [ ] Change the filename to `Ptt.cc.xml`

Please let me know if you have any questions.

If you don't want to work on this anymore, let us know so we can make a new PR for these domains. (I'll close the PR and open a new one myself if we don't hear from you soon.)

**Comment by jeremyn** [comment]
@chennien You have over 30 open PRs with us, many of which have a follow-up from us that you haven't responded to. It's fine if you don't want to work on a PR anymore, but it will help us if you close any PRs you have that you are not interested in anymore.

Please go through your open PRs and add a comment to the ones you are willing to keep working on, and close them otherwise. I'll go through your PRs myself soon and close any that you haven't said you want to keep open.

**Comment by jeremyn** [comment]
I'm closing this PR due to lack of response from @chennien . I've made a new PR https://github.com/EFForg/https-everywhere/pull/14012 that replaces this one.

**Pull request closed without merging**
