### PR TITLE
New ruleset: hkma.gov.hk

### PR DESCRIPTION
**Pull request by Riotism**

### CODE REVIEW

**Comment by J0WI** [comment]
Please also document non working subdomains for future maintenance.

**Comment by Riotism** [comment]
Rules no longer needed - http subdomains are automatically redirected to https counterparts

**Comment by J0WI** [comment]
I do not agree as long as this host isn't HSTS preloaded.
The browser will send a unsecured request and the server will response a unsecured redirect to the secure version. An attacker could still hijack this response to redirect to an evil third party site.

So feel free to reopen.

**Comment by Riotism** [comment]
Understood.

**Pull request merged**
