### PR TITLE
Added rule for cryptopals.com

### PR DESCRIPTION
**Pull request by PanosSakkos**

### CODE REVIEW

**Comment by J0WI** [comment]
@PanosSakkos the served cert does not match `www.cryptopals.com`, that's why our tests are failing.
You can add a redirect from `www.cryptopals.com` to `cryptopals.com` with a comment about the mismatch.

**Comment by PanosSakkos** [comment]
@J0WI good point!

**Comment by J0WI** [comment]
Could you add a comment about the mismatch?

**Comment by J0WI** [comment]
closed by #9408

**Pull request closed without merging**
