### PR TITLE
Update IETF.xml

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Notes to reviewer:

- `ns0.ietf.org` redirects to an outside domain. Should it be added in the rewrite rules?
- `ztp.meeting.ietf.org`, `etherpad.sql1.ietf.org` and `permatrac.sql1.ietf.org` return `401`

**Comment by Bisaloo** [comment]
Fixes #8314

**Comment by Bisaloo** [comment]
Ok, travis and I still disagree but I think the mistake is his in this case.

`curl -v https://noc.ietf.org/` indeed complains about invalid certificate but using firefox, the certificate is fine.

**Comment by gloomy-ghost** [comment]
noc.ietf.org doesn't serve a full certificate chain, maybe you can reproduce it on Firefox by using a brand-new profile.

**Comment by Bisaloo** [comment]
You're right! I removed `noc.ietf.org` and added a comment.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
