### PR TITLE
Simplemachines fixes

### PR DESCRIPTION
**Pull request by redranamber**

### CODE REVIEW

**Comment by J0WI** [comment]
There is an error with `media.simplemachinesweb.com`

**Comment by redranamber** [comment]
It seems to be working correctly when I test it. I have the rule enabled in Firefox and it's rewriting it correctly. There isn't anything at media.simplemachinesweb.com itself but the test url "http://media.simplemachinesweb.com/smf/default/images/theme/backdrop.png" is working, so I think Travis is doing something wrong.

**Comment by J0WI** [comment]
Travis is also checking `https://media.simplemachinesweb.com/`. You need to make an exclusion for `^http://media\.simplemachinesweb\.com/$` to avoid this error (please also document the error with a comment in the ruleset).

**Comment by redranamber** [comment]
Not sure what you wanted commented but the test is passing now.

**Comment by J0WI** [comment]
That's fine for me, thanks!

**Comment by cschanaj** [comment]
this should close #9696

**Pull request merged**
