### PR TITLE
Update yr.no

### PR DESCRIPTION
**Pull request by DavidLiedke**

### CODE REVIEW

**Comment by DavidLiedke** [comment]
@J0WI the Google Chrome Beta check failed. Is this an issue from my PR?

**Comment by Bisaloo** [comment]
Probably not. Travis is having a lot of issues lately. Just keep trying.

**Comment by DavidLiedke** [comment]
yr.no added again

api.yr.no is a redirect to api.met.no (see comment)

**Comment by J0WI** [comment]
> api.yr.no is a redirect to api.met.no (see comment)

So what's wrong with our (secure) redirect?

**Comment by DavidLiedke** [comment]
api.yr.no has a wrong certificate,

**Comment by J0WI** [comment]
That's why we had the extra redirect to `api.met.no`. ;)

**Comment by DavidLiedke** [comment]
I hope now it is okay :)

**Pull request merged**
