### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jwilk**
This PR was brought to you by [mwic](http://jwilk.net/software/mwic).

### CODE REVIEW

**Comment by reedy** [comment]
Unfortunately, as you modified XML rulesets, travis doesn't like it.

We could merge this anyway, and ignore travis, but that's not brilliant

If we could split the commits, so that they're not all in one PR, that might be easier

**Comment by jwilk** [comment]
Would it be sufficient to move the commits that touch rules (5564e1b14534 and 9dcc7c92526d) to a separate PR?

**Comment by reedy** [comment]
Yup, exactly, that'd do the job

**Comment by jwilk** [comment]
Moved the two commits to #3449.

**Pull request merged**
