### PR TITLE
Create JS.org.xml

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by koops76** [comment]
ping @J0WI

**Comment by J0WI** [comment]
I assume that you generated this ruleset from [here](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js). If you used a script to do so, could you share this please? Then I just have to review the script instead of all rules and we could also use it to update the ruleset in future.

**Comment by koops76** [comment]
@J0WI No, it was manual editing using Sublime Text's multi line selection 😊. I will make the script in some time.

**Comment by koops76** [comment]
@J0WI The JS file has many errors and requires manual editing to correct them. This should be solved on JS.org's side.

**Comment by J0WI** [comment]
Please add a link to the upstream domain list in a comment.

**Comment by koops76** [comment]
@J0WI Done.

**Pull request merged**
