### PR TITLE
Add rule for img.ifcdn.com

### PR DESCRIPTION
**Pull request by Liudvikam**

### CODE REVIEW

**Comment by J0WI** [comment]
Are you know if there is any related domain/company where this host fits in?
Rule lgtm.

**Comment by Liudvikam** [comment]
> Are you know if there is any related domain/company where this host fits in?

Not really, and ifcdn.com doesn't resolve to an IP address.

**Comment by J0WI** [comment]
Okay, thanks!

**Comment by Liudvikam** [comment]
You're welcome.

**Pull request merged**
