### PR TITLE
rm Waze.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=3352), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10915), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n12078)

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by J0WI** [comment]
(!) This HSTS header is with `max-age=0`

**Comment by jeremyn** [comment]
See issue #7126 .

**Comment by jeremyn** [comment]
The https://www.waze.com header has `max-age=0`, and the https://waze.com header is missing `preload`. Both of these are bad.

**Pull request merged**
