### PR TITLE
Exclude non-https protected #1663 (mixed content causing it not to load)

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by fuglede** [comment]
Travis complains about the lack of testing;

    ERROR src/chrome/content/rules/xkcd.xml: Not enough tests (0 vs 1) for <Exclusion pattern '^http://xkcd\.com/1663/'>

Otherwise LGTM.

**Comment by Hainish** [comment]
Updated @fuglede

**Comment by fuglede** [comment]
Come to think of it, don't you want to exclude <code>http://(www\\.|m\\.)?xkcd\\.com/1663/</code>?

**Comment by Hainish** [comment]
Good catch @fuglede, fixed

**Pull request merged**
