### PR TITLE
Update GMX.xml

### PR DESCRIPTION
**Pull request by donced**
Remove unnecessary server redirection.
Addresses https://github.com/EFForg/https-everywhere/issues/1895#issuecomment-124518687

### CODE REVIEW

**Comment by julianladisch** [comment]
gmx.co.uk mismatched, CN: *.mail.com, therefore add a rule for gmx.co.uk → www.gmx.co.uk.

**Comment by donced** [comment]
@julianladisch GMX seems to have fixed the mismatched cert issue. Unfortunately, currently there is MCB issue, so I exclude gmx.co.uk for now.

**Comment by julianladisch** [comment]
I don't see any Mixed Content Blocking (MCB) on https://www.gmx.co.uk/
On which URL do you notice MCB, what is the URL of the blocked content?

**Comment by donced** [comment]
i0.gmx.com i1.gmx.com i2.gmx.com have mismatch cert. These URLs also cause MCB issue on https://www.gmx.com/ (it's mentioned in the ruleset comment).
MCB issue on gmx.co.uk

**Comment by julianladisch** [comment]
@donced Thank you for the screenshot, this is very useful because here (Germany) I get other content without mismatch/MCB.

Does this rule for i0.gmx.com, i1.gmx.com, i2.gmx.com fix the problem?

    <rule from="^http://i[012]\.gmx\.com/"
 	    	to="https://sec-s.uicdn.com/" />

**Comment by donced** [comment]
My mistake, MCB only apply to www.gmx.com. i0.gmx.com actually loads just fine (I forgot to scroll down). I don't know the exact cause, but it maybe something to deal with CSS. Nevertheless, I will incorporate your suggested rule on i0.gmx.com.

**Comment by semenko** [comment]
Awesome -- thanks! Manually verified that the GMX -> https://sec-s.uicdn.com/ is correct.

**Pull request merged**
