### PR TITLE
Create fackforbunden.se.xml

### PR DESCRIPTION
**Pull request by HTTPSNowhere**
https://github.com/EFForg/https-everywhere/issues/11930

### CODE REVIEW

**Comment by J0WI** [comment]
This site has mixed content issues, please add the platform attribute.

**Comment by jeremyn** [comment]
@HTTPSNowhere Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
@J0WI I don't see any mixed content blocking here. This ruleset isn't perfect -- I'd change the `ruleset` `name`/filename casing and remove the `securecookie` tag since no cookies are set for these domains -- but I think we can merge this as it is since @HTTPSNowhere is unresponsive.

Can you confirm this ruleset is okay to merge? Feel to merge it yourself, or I can do it.

**Comment by J0WI** [comment]
I cannot reproduce any MCB issues anymore.
For me the ruleset name and the securecookie are no blockers for merge.

**Pull request merged**
