### PR TITLE
[Adbusters.org] Add subdomains

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
If the `521` for https://adbusters.org doesn't go away soon, you can rewrite it to `www`.

**Comment by Bisaloo** [comment]
Do you get `521` as well or is it only travis? 

https://adbusters.org works fine for me

**Comment by jeremyn** [comment]
Sometimes it works in a browser for me, and sometimes I get a `521`.

**Comment by jeremyn** [comment]
I'm still sometimes getting a `521` for https://adbusters.org and sometimes not.

**Comment by Bisaloo** [comment]
Yes, I can reproduce now. I'm not sure what to do...

**Comment by jeremyn** [comment]
I suggested rewriting from `^` to `www` in https://github.com/EFForg/https-everywhere/pull/14897#issuecomment-373221876, which I still support.

**Comment by jeremyn** [comment]
I wonder if the comment should say something like `521 error (sometimes)`. What do you think?

This looks okay otherwise.

**Comment by Bisaloo** [comment]
Yes, this is fine. I wasn't sure how to put it.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
