### PR TITLE
Create Tariq_Ramadan.com.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Please remove the `securecookie` tag. A top-level `securecookie` can be problematic when some domains aren't covered by HTTPS, for example see https://github.com/EFForg/https-everywhere/pull/7527#issuecomment-262405979.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn Done

**Comment by jeremyn** [comment]
Can you please just remove it entirely instead of leaving it as a comment?

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn Done

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
