### PR TITLE
Update Samsung.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@J0WI @fuglede 
Strange time out error : https://travis-ci.org/EFForg/https-everywhere/jobs/134390118#L327

**Comment by renyouguo** [comment]
@J0WI I have try my best, however, there are other rules' error:
https://travis-ci.org/EFForg/https-everywhere/jobs/134431167#L219

**Comment by J0WI** [comment]
They don't matter, the relevant error is here: https://travis-ci.org/EFForg/https-everywhere/jobs/134431167#L318

**Comment by renyouguo** [comment]
@J0WI Thanks,done.

**Comment by renyouguo** [comment]
#5017 #5018 #5019 #5020 #5021 #5022 #5023 #5024 #5027 
@J0WI Sorry, I should update both of them here......

**Comment by renyouguo** [comment]
@J0WI 
In #5024 ,There is no check error: Too many redirects while fetching 'https://apps.samsung.com/mercury/main/getMain.as
Why?
https://travis-ci.org/EFForg/https-everywhere/jobs/136125461#L1471

**Comment by renyouguo** [comment]
@J0WI

**Comment by renyouguo** [comment]
@J0WI @Hainish Would you check this?

**Comment by Hainish** [comment]
For some reason the core codebase tests are failing.  @renyouguo I suggest squashing and rebasing this PR, hopefully then the tests will pass

**Comment by renyouguo** [comment]
#6485

**Pull request closed without merging**
