### PR TITLE
re-enable blackphone

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Mark https://appstore.blackphone.ch as `No working URL known` and remove the `target`.
- [ ] Remove the `securecookie` or make it more specific. Some of these domains have login functionality and I'm uncomfortable with blanket `securecookie` coverage.

**Comment by J0WI** [comment]
The Cookie rule is fine here, all targets are already redirected server side.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/12515/commits/aeb451f0fea535924c5e699a3f110f3207c64d0a. Please remove the `appstore` `target` as well.

**Comment by J0WI** [comment]
Oops, now it's really disabled.

**Pull request merged**
