### PR TITLE
Fixcppcheck1.osuosl.org:8000

### LINKED ISSUE #20151: osuosl.org, unable to load daca@home results page
Type: other

Hi,

I am unable to access this http-only website because it is forcefully redirected to https when HTTPS Everywhere is active. Disabling HTTPS Everywhere makes the website available again. 

URL : http://cppcheck1.osuosl.org:8000/
Description : Debian's Automated Code Analysis (DACA) result server. This particular subdomain show results of cppcheck analysis for debian software packages. 

Extension : HTTPS Everywhere 2021.4.15
Browser : 78.14.0esr (64-bit)
OS : Debian GNU/Linux

### PR DESCRIPTION
**Pull request by guillaume-uH57J9**
Fixes #20151 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Existing Ruleset

### CODE REVIEW

**Review by zoracon — APPROVED** [review]

**Review by zoracon — CHANGES_REQUESTED** [review]
Please remove this domain since it can't be resolved
`oprod-controller-openpower.osuosl.org`

**Comment by guillaume-uH57J9** [comment]
@zoracon with pleasure. done!

**Comment by guillaume-uH57J9** [comment]
One automated test that fails because of a timeout when accessing https://oprod-controller1.osuosl.org/
cf https://app.travis-ci.com/github/EFForg/https-everywhere/jobs/549573382

The change I have submitted does not touch this subdomain, and is not causing this error. 
Please consider accepting this. 

I did check and this URL load for me https://oprod-controller1.osuosl.org/ so I guess it was either temporarily unavailable during the test, or there may be a different kind of network issue between that subdomain and the CI server.

**Comment by guillaume-uH57J9** [comment]
I made a typo in a previous commit message (confusion between hostnames) so I amended it

**Pull request merged**
