### PR TITLE
Re-enable srg-ssr.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
#10882

**Comment by J0WI** [comment]
I plan to split this rule into multiple files anyway. Should I push my changes into this branch or separate PRs?
@jeremyn what would be easier to review?

**Comment by jeremyn** [comment]
I haven't committed to review this, but if I were going to review it, I would prefer more and smaller PRs.

**Comment by J0WI** [comment]
@jeremyn could you review this to complete #10882?

**Comment by jeremyn** [comment]
`drs.ch`:

Mark as `Time out`:
- [ ] https://jobs.drs.ch
- [ ] https://mobile.drs.ch
- [ ] https://podcast.drs.ch

Can we break up `ssr-ssg.xml` into smaller rulesets that are each focused on one domain?

**Comment by J0WI** [comment]
I'll create follow-up PRs to split this ruleset, see our discussion above.

**Comment by jeremyn** [comment]
I've updated/completed the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/a64a484fd4490455b081ebfed11d6bcf15ffc73d.

I didn't notice that we had discussed this earlier. When you say you'll create follow-up PRs, do you mean you want to do that after we merge this one? I would rather do it all at once, for various reasons, for example so there's no urgency to fix it right after we merge it.

**Comment by J0WI** [comment]
I split off the major sites from the holding.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/9040fb5beb6530faaaca755cccd4e038b3635418 with clearly-marked items remaining.

**Comment by J0WI** [comment]
Added.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/600888ba80224304af71d38a97112e4085ecf6b2 and added items for `RTS.ch.xml`.

**Comment by J0WI** [comment]
Done.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/0814234c64110a8f42f3617ddfdae5da4537405b and added items for `SRF.ch.xml`.

`srg-ssr.xml` should still be broken up more. `broadcast.ch` and `swissinfo.ch` should be moved into their own files. `srfcdn.ch` should have its own file. `srg-ssr.xml` should be changed to just `SSGSSR.ch.xml` and the `ruleset` `name` changed to match, like the other files.

**Comment by J0WI** [comment]
Done.
I think it's not worth to create a new file for `srfcdn` and `broadcast`.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/dc7ddd3f201170797e9371af51380ba61c475f32 and added items for `Swissinfo.ch.xml`.

I really think `broadcast.ch` should go into its own file. We have plenty of rulesets that are just `^` and `www`. Smaller rulesets makes maintenance easier. Also there is no connection between the domain name `broadcast.ch` and the ruleset name `SRG SSR` for someone who doesn't know about these domains.

We don't need a separate file for `www.srfcdn.ch` but it should at least be moved to `SRF.ch.xml`, because of the name similarity.

**Comment by J0WI** [comment]
Done.
Would be great if this could ship with the announced release.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/11256/commits/68c0b1fa325f27ef3b0476e0def48fd01fb204fa and added items for `srg-ssr.xml`.

https://forum.swissinfo.ch should be marked as mixed content because it blocks jQuery. I don't think we should include it as a `target` just because some pages seem okay.

**Comment by J0WI** [comment]
@jeremyn done.

**Comment by jeremyn** [comment]
Merged.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
