### PR TITLE
[Tocco.ch] add missing hosts

### PR DESCRIPTION
**Pull request by pgerber**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

Note as `Invalid certificate`
- [ ] juventus.tocco.ch

Note as `No working URL known` (and remove targets) unless you can find working URLs for them:
- [ ] magenta.tocco.ch
- [ ] zgptest3.tocco.ch

Add target:
- [ ] app06.tocco.ch
- [ ] container03.tocco.ch
- [ ] enga.tocco.ch

**Comment by pgerber** [comment]
• magenta.tocco.ch has now a test page that's online at [https://magenta.tocco.ch](https://magenta.tocco.ch)
• enga.tocco.ch is already a target
• zgptest3.tocco.ch is scheduled for removal. The only reason it is still online is that I wanted to see for myself how broken certificate revocation is. [I revoked it a while back.](https://certificate.revocationcheck.com/zgptest3.tocco.ch).
• I'm not sure how you usually deal with names like container03.tocco.ch and app06.tocco.ch. The former only exist for use in CNAMEs. The latter is not used for HTTP at all. It's a mere coincident that at the moment a web server is reachable on the same external IP address.

**Comment by gloomy-ghost** [comment]
I can't remember how I did I progress this. My log says `container03` was 403 and `app06` was 404, but I wrote "add targets". 😵 Also I'm getting invalid certificate for `app06` now. I've crossed them out on the checklist, my apologies.

**Comment by pgerber** [comment]
I believe zgptest3.tocco.ch can now be crossed off as well. DNS entry for it no longer exists.

**Comment by gloomy-ghost** [comment]
Yes, thanks again. Merged.

**Pull request merged**
