### PR TITLE
New rule for drillisch.de

### PR DESCRIPTION
**Pull request by KommX**

### CODE REVIEW

**Comment by reedy** [comment]
Not a major issue, but an annoying one... Visiting https://drillish.de 301s to http://www.drillish.de - dropping the HTTPS

```
 reedy@ko-kra:~$ curl -I https://www.drillisch.de/
HTTP/1.1 200 OK
Set-Cookie: drillisch=oljjp5rko1aj8c6bnssanv95f2; path=/
Set-Cookie: drillisch=oljjp5rko1aj8c6bnssanv95f2; path=/; domain=.drillisch.de; secure; httponly
Cache-Control: no-cache
Date: Mon, 13 Apr 2015 03:15:25 GMT
Content-Type: text/html; charset=UTF-8
Server: Apache

reedy@ko-kra:~$ curl -I https://drillisch.de/
HTTP/1.1 301 Moved Permanently
Location: http://www.drillisch.de/
Content-type: text/html
Date: Mon, 13 Apr 2015 03:15:35 GMT
Server: Apache

reedy@ko-kra:~$
```

**Comment by KommX** [comment]
Is this really a problem? When I use Firefox to go to http://drillisch.de I end up at https://www.drillisch.de/ - this looks fine, doesn't it?

**Comment by reedy** [comment]
Yeah, was more of a comment against the site than your rules/HTTPSE

**Comment by KommX** [comment]
Is there a problem with this pull request?

**Pull request merged**
