### PR TITLE
Create ruleset: nianet.dk

### PR DESCRIPTION
**Pull request by netravnen**

### CODE REVIEW

**Comment by ivysrono** [comment]
@pipboy96 All PRs opened by @netravnen do not get travis?
https://github.com/EFForg/https-everywhere/pulls/netravnen

**Comment by pipboy96** [comment]
@ivysrono Weird.

**Comment by ivysrono** [comment]
@zoracon

**Comment by pipboy96** [comment]
@ivysrono May have something to do with `/` in branch name.

**Comment by ivysrono** [comment]
That's it.

**Pull request closed without merging**
