### PR TITLE
Add parl.gc.ca to rules.

### PR DESCRIPTION
**Pull request by lexgill**

### CODE REVIEW

**Comment by jeremyn** [comment]
This pull request needs various updates. Please see the comment I made at https://github.com/EFForg/https-everywhere/pull/14042#issuecomment-353694020 on another pull request you made, and make similar improvements here. After that I will review this more closely.

**Comment by jeremyn** [comment]
@lexgill Can we move forward on this one?

**Comment by lexgill** [comment]
Thanks @jeremyn! I think this is better now? let me know if anything else needs to change.

**Comment by jeremyn** [comment]
- [ ] Please replace what you have with this, which includes various improvements
```xml
<!--
	Invalid certificate:
		jobs-emplois.parl.ca

-->
<ruleset name="Parl.ca">
	<target host="parl.ca" />
	<target host="www.parl.ca" />
	<target host="bdp.parl.ca" />
	<target host="decouvrez.parl.ca" />
	<target host="learn.parl.ca" />
	<target host="lop.parl.ca" />
	<target host="res.parl.ca" />
		<test url="http://res.parl.ca/prs/" />
	<target host="visit.parl.ca" />
	<target host="visitez.parl.ca" />

	<rule from="^http:" to="https:" />
</ruleset>
```

Please let me know if you have any questions.

**Comment by jeremyn** [comment]
Also, since the ruleset is now for `parl.ca` and not `parl.gc.ca`, I want to squash-and-merge it with the commit message `Add parl.ca to rules. (#14041)` instead of `Add parl.gc.ca to rules. (#14041)` which is what it would normally be. (This is done by me when I merge in GitHub, you don't need to do anything for it.) Please confirm that this change in the commit message is okay with you.

**Comment by jeremyn** [comment]
@lexgill I'd like to finish this pull request if we can, please.

**Comment by jeremyn** [comment]
@lexgill I'd like to get this finished if we could. If we don't hear from you soon, I'm going to go ahead and make a new pull request myself for these domains.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
