### PR TITLE
Create hentai-foundry.com.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Add a rewrite `rule` from `^` to `www`
- [ ] Mark `^` in the top comment as `Different HTTP/HTTPS content`
- [ ] Add a `test` for http://thumbs.hentai-foundry.com/robots.txt
- [ ] Add a `test` for http://img.hentai-foundry.com/themes/default/js/ads.js
 
For https://avatars.hentai-foundry.com and https://pictures.hentai-foundry.com the root URLs return a `403`, so normally we would add a `test` for each, however I didn't find any `test` `url`s I'm totally comfortable including. So for these, how about:
 
- [ ] Above the `target` for `avatars`, add a comment:
```xml
	<!-- Test URLs for avatars.hentai-foundry.com can be found at
		https://www.hentai-foundry.com -->
``` 
- [ ] Above the `target` for `pictures`, add a comment:
```xml
	<!-- Test URLs for pictures.hentai-foundry.com can be found at
		https://www.hentai-foundry.com > "Browse Submissions" -->
```     
    
- [ ] https://profiles.hentai-foundry.com returns a `403` and I couldn't find any valid URLs for it. Can you find any appropriate URLs, or at least where these URLs can be found? Otherwise please add `profiles` to the top comment marked as `No working URL known`.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9998/commits/e2f37fde1d016dc786f2b8c5431d3350f525cadb.

Where did you find the `test` `url` for `profiles`? Another thing that `test` `url`s should be, besides SFW and having a small filesize, is non-personal. If the URL you have is associated with some particular site user, we should probably pick something else.

**Comment by Folant** [comment]
@jeremyn I couldn't find other URL not associated with site users for profiles.hentai-foundry.com, therefore removed it from targets. 
As for
>Can you find any appropriate URLs, or at least where these URLs can be found? 

we can find links to it in users profiles, under ```Member Info``` section.
e.g
https://www.hentai-foundry.com/user/admin/profile/page/all
https://profiles.hentai-foundry.com/1.jpg
So maybe we can add a comment about it above ```target``` like for avatars/pictures.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9998/commits/15621977c81024d27fa62f941afe759bbacad127.

Yes, let's add a comment for `profiles`. I've edited the `profiles` item in the checklist with one possible wording.

**Comment by Folant** [comment]
@jeremyn Done, thanks.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9998/commits/6e445bdf4031d1ea478b4e5656a1c41001467c49.

I've added two items about changing names. I'm sorry I didn't include those items before. These really should be the last additions.

**Comment by Folant** [comment]
Sorry. I should have known.

**Comment by jeremyn** [comment]
Looks good now. Thanks, merged.

**Pull request merged**
