### PR TITLE
[AmazonAWS.com] Add exclusion (fix #4510)

### LINKED ISSUE #4510: Amazon Web Services breaking video (and graphics) on multiple sites
http://losangeles.cbslocal.com/2016/03/27/ventura-police-search-for-suspect-in-connection-with-gun-store-break-in/

http://losangeles.cbslocal.com/2016/04/04/court-employers-must-allow-workers-to-sit-if-they-prefer-while-on-the-job/

Amazon Web Services needs to be turned off in order to fix the video.

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by J0WI** [comment]
I'm not able to reproduce #4510, maybe @gloomy-ghost or @jeremyn can?

**Comment by gloomy-ghost** [comment]
I can't verify it because I don't have flash installed, sorry

**Comment by jeremyn** [comment]
I've followed some of the links in the original issue but I'm still not sure what this PR is fixing, in the sense of, what behavior changes on some site before and after including this fix.

**Comment by Bisaloo** [comment]
The video [here](http://up.anv.bz/latest/anvload.html?key=eyJtIjoiY2JzIiwicCI6ImRlZmF1bHQiLCJ2IjoiMzM4NTA0MSIsInBsdWdpbnMiOnsiY29tc2NvcmUiOnsiY2xpZW50SWQiOiIzMDAwMDIzIiwiYzMiOiJuZXd5b3JrLmNic2xvY2FsLmNvbSJ9LCJkZnAiOnsiY2xpZW50U2lkZSI6eyJhZFRhZ1VybCI6Imh0dHA6Ly9wdWJhZHMuZy5kb3VibGVjbGljay5uZXQvZ2FtcGFkL2Fkcz9zej0yeDImaXU9LzQxMjgvQ0JTLk5ZJmNpdV9zenMmaW1wbD1zJmdkZnBfcmVxPTEmZW52PXZwJm91dHB1dD14bWxfdmFzdDImdW52aWV3ZWRfcG9zaXRpb25fc3RhcnQ9MSZ1cmw9W3JlZmVycmVyX3VybF0mZGVzY3JpcHRpb25fdXJsPVtkZXNjcmlwdGlvbl91cmxdJmNvcnJlbGF0b3I9W3RpbWVzdGFtcF0iLCJrZXlWYWx1ZXMiOnsiY2F0ZWdvcmllcyI6IltbQ0FURUdPUklFU11dIiwicHJvZ3JhbSI6IltbUFJPR1JBTV9OQU1FXV0iLCJzaXRlU2VjdGlvbiI6ImZlYXR1cmVkIn19fSwiaGVhcnRiZWF0QmV0YSI6eyJhY2NvdW50IjoiY2JzbG9jYWwtZ2xvYmFsLXVuaWZpZWQsY2JzbG9jYWwtc3RhdGlvbi1uZXd5b3JrLW5ld3lvcmstdW5pZmllZCxjYnNsb2NhbC1zdWJwcmltYXJ5LXN3dHYtdW5pZmllZCxjYnNsb2NhbC1tYXJrZXQtbmV3eW9yay11bmlmaWVkIiwicHVibGlzaGVySWQiOiI4MjNCQTAzMzU1Njc0OTdGN0YwMDAxMDFAQWRvYmVPcmciLCJqb2JJZCI6InNjX3ZhIiwibWFya2V0aW5nQ2xvdWRJZCI6IjgyM0JBMDMzNTU2NzQ5N0Y3RjAwMDEwMUBBZG9iZU9yZyIsInRyYWNraW5nU2VydmVyIjoiY2JzZGlnaXRhbG1lZGlhLmhiLm9tdHJkYy5uZXQiLCJjdXN0b21UcmFja2luZ1NlcnZlciI6ImNic2RpZ2l0YWxtZWRpYS5kMS5zYy5vbXRyZGMubmV0IiwidmVyc2lvbiI6IjEuNSJ9LCJyZWFsVGltZUFuYWx5dGljcyI6dHJ1ZX0sImFudmFjayI6ImFudmF0b19jYnNsb2NhbF9hcHBfd2ViX3Byb2RfNTQ3ZjNlNDkyNDFlZjBlNWQzMGM3OWIyZWZiY2E1ZDkyYzY5OGY2NyJ9) was not playing because of MCB. Now it does.

**Comment by Bisaloo** [comment]
@jeremyn, both `cbslocal-download` and `cbs-uploads` needed to be whitelisted for the video to work. I am not sure why you don't get any traffic from `cbslocal-download` and why the video is not playing.

**Comment by jeremyn** [comment]
Is there any other URL, anywhere that you know of, that this PR fixes? We probably shouldn't add an `exclusion` to fix just one very specific video URL in any case.

**Comment by Bisaloo** [comment]
No idea sorry, I was just working with the info from #4510. I'm not even sure where this URL comes from.

**Comment by jeremyn** [comment]
@Hainish Could you please review this PR? For one reason or another (see above), none of the current maintainers are able to approve this.

**Comment by Hainish** [comment]
Thanks @jeremyn, I'll take a look tomorrow.

**Comment by Hainish** [comment]
@jeremyn I'm not seeing your test ruleset change anything for that link.  I am still getting the "Please install the latest Adobe Flash Player Plugin to watch this content" text and banner in Chrome.

**Comment by Bisaloo** [comment]
@Hainish, yes you need flash to reproduce. This issue here is that ,even with flash, the video won't play because of MCB.

**Comment by Hainish** [comment]
Thanks!

**Pull request merged**
