### PR TITLE
Add rule for RustFest.eu

### PR DESCRIPTION
**Pull request by dns2utf8**
### List related issues if any

- some subdomains do not always redirect to https

### CODE REVIEW

**Comment by pipboy96** [comment]
Please enumerate subdomains using [Amass](https://github.com/OWASP/Amass).

**Comment by dns2utf8** [comment]
Thank you for running the amass tool, I have never heard of it.
May I ask why you would like to have it's output?

**Comment by pipboy96** [comment]
You should not use a wildcard but list individual domains and document the ones that do not work.

**Comment by dns2utf8** [comment]
Thank you :)

**Pull request merged**
