### PR TITLE
[HTWK Leipzig] Rewrite & Cleanup ruleset

### PR DESCRIPTION
**Pull request by rugk**
Recreating/Continuing
https://github.com/EFForg/https-everywhere/pull/4000

### CODE REVIEW

**Comment by rugk** [comment]
It seems fine now. What about merging?

**Comment by rugk** [comment]
Any news?

**Comment by J0WI** [comment]
Please use tabs instead of spaces. The host is quite huge and so it's hard to check every single site.
What I tested so far works for me, so as long as it passes our tests I'll merge it.

**Comment by rugk** [comment]
I've changed the spaces to tabs.

**Comment by J0WI** [comment]
`www.bmb.htwk-leipzig.de` is buggy

**Comment by rugk** [comment]
Indeed, removed.

**Comment by J0WI** [comment]
Passed all tests now.

**Pull request merged**
