### PR TITLE
Fix ITunes.com.xml HTTPS Mismatch

### PR DESCRIPTION
**Pull request by weems**
Closing #6870

### CODE REVIEW

**Comment by jeremyn** [comment]
@weems Thanks for the pull request.

@fuglede @J0WI I'm not sure why the test is giving this error:

```
ERROR src/chrome/content/rules/ITunes.com.xml: Fetch error: http://itunes.com/ => https://itunes.com/: Redirect for 'https://itunes.com/' missing Location
```

I can reproduce it locally with `fetch-test.sh`, but it works fine in Firefox and the response has a `Location` header. I haven't investigated the code though. Ideas?

**Comment by J0WI** [comment]
I can reproduce using curl., but I have no proper solution for it.

**Comment by jeremyn** [comment]
I think I see it. [This](https://github.com/EFForg/https-everywhere/blob/a37a897b014360893646a8699715bc5e58c011d0/test/rules/src/https_everywhere_checker/http_client.py#L387) should look for the key `Location`, not `location`. Give me a little while to look into it more.

**Comment by weems** [comment]
@jeremyn is this a error with the test or my changes?

**Comment by jeremyn** [comment]
@weems The test.

**Comment by jeremyn** [comment]
It's still the part of the code I linked above. The regex is bad:

```
(Pdb) self._headerRe
regex.Regex('(?P<name>\\S+?): (?P<value>.*?)\\r\\n', flags=regex.V0)
(Pdb) headerStr
'HTTP/1.1 301 Moved Permanently\nServer: Apache\nDate: Tue Jun  1 12:48:03 PDT 1999 PDT\nReferer: http://itunes.com/\nLocation: http://www.apple.com/itunes/?cid=OAS-US-DOMAINS-itunes.com\nContent-type: text/html\nContent-length: 311\n\n'
(Pdb) headers = self._headerRe.findall(headerStr)
(Pdb) headers
[]
(Pdb)
```

**Comment by jeremyn** [comment]
By the way there are a lot of rules that have excluded URLs due to `missing Location`, see [here](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=missing+Location). We really should fix it though.

**Comment by weems** [comment]
@jeremyn so it's a problem with the code that checks the xml to make sure it will work?

**Comment by weems** [comment]
@jeremyn ah.

**Comment by jeremyn** [comment]
Pull request #6878 should fix the test problem.

**Comment by jeremyn** [comment]
@weems The problem with the testing has been fixed by pull request #6878 so that's not a blocker anymore. Before we merge, please:

- [ ] Clean up the comments by removing lines 3-4, 9-10, and 12-13 from your modified `iTunes.com.xml` in 232e702eeb00ec625f1faf41f6e0e254cec2ef92

Also, there are some other `itunes.com` subdomains that could be included either as `target`s or noted as bad, for example see [here](https://www.google.com/search?q=site%3A*.itunes.com&ie=utf-8&oe=utf-8#q=site:*.itunes.com+-site:www.itunes.com+-site:tw.itunes.com+-site:facebook.itunes.com+-site:rss.itunes.com+-site:new.itunes.com+-site:newmusic.itunes.com+-site:store.itunes.com+-site:apple.itunes.com+-site:itunesu.assets.itunes.com). Are you willing to add them as part of this issue? I won't require it because you're just trying to fix a simple issue, but it would be nice if you could add them. Either way is fine though.

**Comment by jeremyn** [comment]
Thanks, but you deleted the wrong lines from the top. Deleting lines 3-4 should have ended up with:

```xml
<!--
	For other Apple coverage, see Apple.xml.
		Mismatch-https://www.itunes.com has a certificate mismatch
-->
```

Also, are you going to pass on adding the new subdomains?

Finally, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means rewriting commits in your name. Is that all right with you for this and other pull requests you submit?

**Comment by weems** [comment]
@jeremyn Apologies, I am new, I will try to get sufficient changes in. Thanks

**Comment by gloomy-ghost** [comment]
Just a notice, `closing` is not a [keyword](https://help.github.com/articles/closing-issues-via-commit-messages/) which can close issues automatically after merging.

**Comment by jeremyn** [comment]
@weems I'm checking in on this pull request. Do you need anything from me to move forward?

**Comment by jeremyn** [comment]
Hi @weems , I'm checking in again here. Do you want us to just make any remaining changes ourselves to your branch? I see you've enabled `Allow edits from maintainers`.

**Comment by weems** [comment]
@jeremyn If you could, I'm still trying to learn the syntax here, maybe I can review for future commits. Thanks for tolerating this newbie :)

**Comment by jeremyn** [comment]
@fuglede @gloomy-ghost @J0WI I've made changes on top of @weems 's pull request. Can one of you please review this? Please do a regular merge instead of squash-and-merge because we have multiple contributors.

**Comment by gloomy-ghost** [comment]
Possible target: https://apps.itunes.com, can't find any tests though

Will review other details later.

**Comment by jeremyn** [comment]
@gloomy-ghost I can't find any tests for https://apps.itunes.com either. I don't want to include a `target`, or a even a failure comment, for a domain without any URLs that return a `200`.

**Comment by gloomy-ghost** [comment]
https://apps.itunes.com/files/ios-music-app/

There we go

**Comment by jeremyn** [comment]
The URL you give in https://github.com/EFForg/https-everywhere/pull/6871#issuecomment-261412592 returns an `HTTP 400`.

**Comment by gloomy-ghost** [comment]
How about https://apps.itunes.com/files/ios-music-app/ ?

**Comment by jeremyn** [comment]
https://apps.itunes.com/files/ios-music-app/ gives me a `HTTP 503`.

**Comment by gloomy-ghost** [comment]
I also had 503, but it works after some times

**Comment by weems** [comment]
http://apps.itunes.com/files/ has some interesting information which may assist: "vailableProjects: [itu-web-unsupported,atv-podcasts-app-custom,tvos-search-app,static-resources,ios-music-js-seed,itu-material-fix,ios-music-app-custom,itu-material-replace,atv-appstore-app-custom,itu-web-teacher,itu,tvos-books-app-custom,desktop-music-app-seed-custom,athena-ui,desktop-music-app-seed,desktop-music-app,itu-coursemanager,crossfire-ui,artistconnect,podcasts-connect,atv-search-app,tvos-whats-new-app,itu-universal-links,itu-web,atv-podcasts-app,atv-music-app-custom,atv-search-app-custom,appcontent,desktop-music-app-custom,atv-music-app-2.0-custom,finance-app-custom,tvos-books-app,ios-music-app-90seed,watchlist-app,ios-music-js-custom,tvos-whats-new-app-custom,ios-music-js,watchlist-app-custom,ios-music-js-seed-custom,ios-appstore-app,silverbullet-athena,atv-music-app-2.0,artistconnect-ui,atv-subscription-mgmt-app-custom,static-config,itu-sis-statics,atv-appstore-app,atv-music-app,atv-subscription-mgmt-app,tvos-search-app-custom,finance-app,atv-videos-app-custom,atv-videos-app,ios-music-app,foo]"

**Comment by gloomy-ghost** [comment]
Retest

**Pull request merged**
