### PR TITLE
Add royal.uk ruleset

### PR DESCRIPTION
**Pull request by VoidPhantom**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please note `www.everydayexceptional.royal.uk` as `Invalid certificate` in a top comment.

**Comment by jeremyn** [comment]
@VoidPhantom Are you still interested in working on this?

**Comment by VoidPhantom** [comment]
Sorry for the long absence. :frowning_face:

I added a rule for www.everydayexceptional.royal.uk.

**Comment by jeremyn** [comment]
- [ ] Remove the `www.everydayexceptional.royal.uk` extra comment and rule [here](https://github.com/VoidPhantom/https-everywhere/blob/a2b101ab750445ca7b5c3c2a5d7490feaf030ccc/src/chrome/content/rules/Royal.uk.xml#L10-L17). This doesn't seem to be useful and it complicates the ruleset. We can keep the top comment, though.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
