### PR TITLE
I18N support for popup.html. German and English.

### PR DESCRIPTION
**Pull request by Thorsten-Sick**
We at Avira want to start contributing to HTTPS-Everywhere (Chrome). Here is a first PR (low hanging fruit). More to come.

### CODE REVIEW

**Comment by reedy** [comment]
Niiiice :+1:

**Comment by reedy** [comment]
I think my only comment here is that you can/should remove the english descriptions directly from the html too.

From popup.html

```
<section id="UnstableRules" class="rules">
  <h3 i18n="chrome_experimental_rules"></h3>
  <p class="description" i18n="chrome_experimental_rules_description"></p>
</section>
```

If you do that, I think this should be good to merge :)

**Comment by Thorsten-Sick** [comment]
Ok, did that.

**Comment by reedy** [comment]
@jsha Any comments on this? Or am I good to merge it? :D

**Comment by jsha** [comment]
Thanks so much for your contribution! Merging this.

FYI if you're looking for a next task: I have a pull request https://github.com/EFForg/https-everywhere/pull/1351 that arranges for Chrome and Firefox to share the same translation infrastructure. This makes it easier for our Transifex community to contribute Chrome translations, and reduces overhead since many of the strings are the same. Feel free to pull that branch and start making the needed changes to make it compatible with this branch. Thanks again,

Jacob

**Pull request merged**
