### PR TITLE
101weiqi.com

### PR DESCRIPTION
**Pull request by J0WI**
Thanks to @renyouguo for the previous work on this rule.

### CODE REVIEW

**Comment by renyouguo** [comment]
@J0WI It is not ok.
http://www.101weiqi.com/play/p/82481/#main
http://7j1yxi.com1.z0.glb.clouddn.com/file/headicon_128.png

**Comment by J0WI** [comment]
What's the error there?
I can't see any errors. Do I have to be logged in to reproduce?

**Comment by renyouguo** [comment]
Yes, I have logged.
In https, the robot can not go.
Or we can say, we cannot see what is the robot go.

**Comment by renyouguo** [comment]
#4976 @J0WI

**Pull request closed without merging**
