### PR TITLE
Add Parter.ru.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Another strage `403` error in fetch tests. @Hainish are our tests broken?

**Comment by Hainish** [comment]
@J0WI wow, tracking this problem down was a doozy. With this script, that isolates the logic in https://github.com/EFForg/https-everywhere/blob/94de81a773a6e6936ec23850c61d8b7e421606f8/test/rules/src/https_everywhere_checker/http_client.py#L309-L326

```python
import pycurl                                                              
import cStringIO                                                           
                                                                           
url = "https://www.parter.ru/"                                             
ua = "Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"
                                                                           
buf = cStringIO.StringIO()                                                 
                                                                           
c = pycurl.Curl()                                                          
c.setopt(c.VERBOSE, True)                                                  
c.setopt(c.URL, url)                                                       
c.setopt(c.WRITEFUNCTION, buf.write)                                       
c.setopt(c.USERAGENT, ua)                                                  
c.perform()                                                                
httpCode = c.getinfo(pycurl.HTTP_CODE)                                     
print httpCode                                                             
```

in the docker environment I get the following output:

```shell
root@ec6f1ee2e8c6:/opt# python curl.py
*   Trying 23.197.97.43...
* Connected to www.parter.ru (23.197.97.43) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*        subject: C=DE; ST=Bremen; L=Bremen; O=CTS EVENTIM Solutions GmbH; OU=CTS EVENTIM Solutions GmbH; CN=secure.eventim.de
*        start date: Mar 17 00:00:00 2017 GMT
*        expire date: Jun 16 23:59:59 2018 GMT
*        subjectAltName: www.parter.ru matched
*        issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust SSL CA - G3
*        SSL certificate verify ok.
> GET / HTTP/1.1
Host: www.parter.ru
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Accept: */*

< HTTP/1.1 403 Forbidden
< Mime-Version: 1.0
< Content-Type: text/html
< Content-Length: 263
< Expires: Sat, 08 Jul 2017 21:58:19 GMT
< Date: Sat, 08 Jul 2017 21:58:19 GMT
< Connection: close
< Set-Cookie: ak_bmsc=B1934465F0C51A93A07F5358DD2C29A417C5331FAE0300007B5561598591C211~pldy+5rqYxFGuVLgCP/+8ZeAip5LMpGeWkc6cuJRAE2jq0iqGCwZirHWT3aV0NrFQsLVY2Qo300mP+OJOEXbEjuLgcl/voTBctIwpTRQutpj7gUaB+OZpLlNoLj08i/V0ZHlHIBvhRF2PfZR2wIe3DsKcEwVMqyQqM1mL52pM0tC3XYHXkCaPb14xzycVCNmzc5qWYpxSU80QliB6JwMdf031tv4bQGq1av8n4es/V+Ts=; expires=Sat, 08 Jul 2017 23:58:19 GMT; max-age=7200; path=/; domain=.parter.ru; HttpOnly
< X-Powered-By: ASP.NET
< Server: Microsoft-IIS/7.0
< P3P: CP="ALL DSP NID CURa OUR LEG UNI"
< 
* Closing connection 0
403
```

and on my local I get

```shell
user@https-everywhere ~ $ cat workspace/https-everywhere/blah 
user@https-everywhere ~/workspace/https-everywhere (J0WI-parter) $ python curl.py
* Hostname was NOT found in DNS cache
*   Trying 23.197.97.43...
* Connected to www.parter.ru (23.197.97.43) port 443 (#0)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
*        server certificate verification OK
*        common name: secure.eventim.de (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=DE,ST=Bremen,L=Bremen,O=CTS EVENTIM Solutions GmbH,OU=CTS EVENTIM Solutions GmbH,CN=secure.eventim.de
*        start date: Fri, 17 Mar 2017 00:00:00 GMT

*        expire date: Sat, 16 Jun 2018 23:59:59 GMT

*        issuer: C=US,O=GeoTrust Inc.,CN=GeoTrust SSL CA - G3
*        compression: NULL
*        cipher: AES-256-GCM
*        MAC: AEAD
> GET / HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Host: www.parter.ru
Accept: */*

< HTTP/1.1 200 OK
< Cache-Control: no-cache
< X-UA-Compatible: IE=IE10
< Content-Type: text/html;charset=UTF-8
< Vary: host
< Vary: user-agent
< Date: Sat, 08 Jul 2017 21:54:40 GMT
< Transfer-Encoding:  chunked
< Connection: keep-alive
< Connection: Transfer-Encoding
< Set-Cookie: Eventim+RU_time=68888;Max-Age=31536000
< Set-Cookie: permInfo=1499456883148064139A08072017A08072017;Max-Age=630720000;domain=parter.ru;path=/
< Set-Cookie: dd=1;domain=parter.ru;path=/
< Set-Cookie: webid=UlVFX05PX1NFU1NJT04=;domain=parter.ru;path=/;HttpOnly
< Set-Cookie: webshop=YWZmaWxpYXRlPVJVRSZsb2dpbj0wJnByaWNlPTAuMDAmZ2lmdHdyYXBwZXI9MC4wMCZpbnN1cmFuY2U9MC4wMCZjb3Vwb249MC4wMCZzaGlwcGluZz0wLjAwJnRvdGFsPTAuMDAmb3JkZXJfdG90YWw9MC4wMCZ0aWNrZXRwcmljZT0wLjAwJmFtb3VudD0wJm1lcmtpdGVtcz0wJnJlc2VydmF0aW9uX2R1cmF0aW9uPTAma3BzX3VybD0mYW1vdW50X2V2aWRzPTAmcGtpZHNfaW5fY2FydD0mZXZpZHNfaW5fY2FydD0mcmFuZG9tPTYzOTU0JnJlZmVyZXI9Jmxhbmd1YWdlPXJ1JmxvY2FsZT1ydV9ydSZrZXk9UEtRTmhtQjJqUHpKJm1vZD0xJmRldmljZV9pbmZvPTAmcHJpY2VfZm9ybWF0dGVkPTAlMkMwMCZnaWZ0d3JhcHBlcl9mb3JtYXR0ZWQ9MCUyQzAwJmluc3VyYW5jZV9mb3JtYXR0ZWQ9MCUyQzAwJmNvdXBvbl9mb3JtYXR0ZWQ9MCUyQzAwJnNoaXBwaW5nX2Zvcm1hdHRlZD0wJTJDMDAmdG90YWxfZm9ybWF0dGVkPTAlMkMwMCZvcmRlcl90b3RhbF9mb3JtYXR0ZWQ9MCUyQzAwJnRpY2tldHByaWNlX2Zvcm1hdHRlZD0wJTJDMDAmY3VycmVuY3lfY29kZT1SVUImY3VycmVuY3lfc3ltYm9sPSUyNiUyMzEwODglM0IlMjYlMjMxMDkxJTNCJTI2JTIzMTA3MyUzQi4=;domain=parter.ru;path=/
< X-Powered-By: ASP.NET
* Server Microsoft-IIS/7.0 is not blacklisted
< Server: Microsoft-IIS/7.0
< P3P: CP="ALL DSP NID CURa OUR LEG UNI"
<
* Connection #0 to host www.parter.ru left intact
200
```

Notice that the only thing different in the two requests is the headers.  If `Host` comes before `User-Agent`, `403` is returned.  If `User-Agent` comes before `Host`, we get a `200` response.

This looks like a server misconfiguration.  Referring to [RFC 2616 section 4.2](https://tools.ietf.org/html/rfc2616#section-4.2)

```
The order in which header fields with differing field names are
received is not significant. However, it is "good practice" to send
general-header fields first, followed by request-header or response-
header fields, and ending with the entity-header fields.
```

This isn't, therefore, a problem with our tests.  If this works in all supported browsers, I'd say add it to https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-whitelist.csv with the values `1,0`.

**Comment by J0WI** [comment]
@Hainish thanks to investigate here!
The problem has coming up quite frequently in the last days, so I wonder if something changed in our tests or in the infrastructure of a popular cloud server provider.

**Comment by Hainish** [comment]
Looks like this one is Akamai:

```shell
user@https-everywhere ~ $ dig +short www.parter.ru                                                                                                    
secure.parter.ru.edgekey.net.
e4138.b.akamaiedge.net.
184.25.148.206
user@https-everywhere ~ $ dig +short -x 23.197.97.43
a23-197-97-43.deploy.static.akamaitechnologies.com.
```

**Comment by J0WI** [comment]
That's sad, because we don't want to exclude all Akamai hosts from our fetch tests :(

**Comment by Hainish** [comment]
@J0WI I'll see what I can do.  I don't think that'll be necessary.  We have several options:

1. Reach out to Akamai and ask them to stop doing this, since it seems like a server misconfiguration
2. Change our travis build environment so that it is closer to my local testing environment above, since that seems to work

**Comment by Hainish** [comment]
I'm searching for a contact at Akamai to reach out to currently.

**Comment by Hainish** [comment]
This is due to their Web Application Firewall, it's an option that customers can turn on to prevent certain types of attacks.  I've narrowed the discrepancy down to the version of `libcurl` that is being used by the system.

If `libcurl` version `7.38.0` is used, `User-Agent` comes before `Host`, we get a `200` response.
If `libcurl` version `7.47.0` is used, `Host` comes before `User-Agent`, `403` is returned.

We could change https://github.com/EFForg/https-everywhere-docker-base/blob/master/Dockerfile to inherit from Debian 8, in which case the version of `libcurl` would be old enough to not encounter this problem.  Force-downgrading `libcurl` seems like a less than ideal solution, though.  There may be a compile-time option or patch that we could apply to `libcurl` that fixes the problem, but that seems complicated.  I'll try to think of a better solution.

**Comment by Hainish** [comment]
It looks like simply setting an extra header bypasses this problem.  Applied a fix in https://github.com/EFForg/https-everywhere/commit/db8d6495dddb1c954faf2c9f4b65d4320a873e86

**Comment by Hainish** [comment]
Re-ran the `fetch` test, it passes now.

**Comment by J0WI** [comment]
I just had to update the hash

**Comment by jeremyn** [comment]
`Parter.ru.xml` looks fine. This should be ready to merge after the whitelist and `Eventim.xml` are updated.

**Comment by J0WI** [comment]
I've updated `Eventim.xml` in #10948.

**Comment by jeremyn** [comment]
Can we finish this one first?

**Comment by J0WI** [comment]
I d'like to avoid rebasing twice, so I would postpone the change in `Eventim.xml` to #10948 then. Is that okay for you?

**Comment by jeremyn** [comment]
How about you remove the changes to both `Eventim.xml` and the whitelist from this PR, and add the reference to `Parter.ru.xml` to `Eventim.xml` in the other PR? That way you won't need to rebase this one.

**Comment by J0WI** [comment]
Created #13556

**Pull request closed without merging**
