### PR TITLE
Created ruleset for D.O.H.P. sites. See details.

### PR DESCRIPTION
**Pull request by advaith1**
I am the administrator of the sites listed. Some are to add security until we implement additional HTTPS redirects, and the rest are to add additional security, even if already enforced.

### CODE REVIEW

**Comment by J0WI** [comment]
Since you are the admin, please have a look at https://hstspreload.org/

**Comment by advaith1** [comment]
@J0WI: Not all of our subdomains are compatible with TLS, which is why we did not use a wildcard in the ruleset. HSTS Preload requires all subdomains have HSTS enabled.

**Comment by jeremyn** [comment]
@advaith1 Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @advaith1 . I've noted `dohp.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353635946` in case anyone else wants to make a pull request for this domain.

**Pull request closed without merging**
