### PR TITLE
Update Smutty.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Mark https://e.smutty.com as `Invalid certificate` and remove the `target`
- [ ] Mark https://i.smutty.com as `No working URL known` and remove the `target`, or add a `test`
- [ ] Add a `test` for `http://a.smutty.com/robots.txt`
- [ ] Add a `test` for `http://s.smutty.com/templates/COMMON/toCDN/overlay.png`
- [ ] Change the filename to `Smutty.com.xml`
- [ ] Change the `ruleset` `name` to `Smutty.com`
- [ ] Everything in the top comment should have at least a single tab indent

**Comment by Folant** [comment]
@jeremyn I think it's good to go. Thanks!

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9989/commits/eeb00818b671975f6112cf561eae3ff18b87ec04 and added a new item for the `www` `rule`. I'm sorry I didn't include that the first time.

Can you find a different `test` `url` for `i.smutty.com`? The ideal `test` `url` is both safe-for-work and has a small filesize. (For example `/robots.txt` is usually good to use, when it's available.)

**Comment by Folant** [comment]
@jeremyn Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
