### PR TITLE
[Just Eat] Cleanup and expand to cover more countries

### PR DESCRIPTION
**Pull request by funkydude**

### CODE REVIEW

**Comment by J0WI** [comment]
There is a lot of mixed content on
https://www.just-eat.co.uk/blog
https://www.just-eat.co.uk/apps

There are also
help.just-eat.co.uk
restaurants.just-eat.co.uk
partnerblog.just-eat.co.uk (refused)
uk.justeat-blogs.co.uk (refused)


You may want to continue with other sites from this company (see https://just-eat.com/)

**Comment by funkydude** [comment]
Stupid Chrome bug, added exclusions.
Will look into adding all the other TLDs soon.

**Comment by J0WI** [comment]
There is also a `beta` subdomain. I'm not sure if this should be included.
Everything else looks great!

**Comment by funkydude** [comment]
@J0WI France should be looked at more carefully as it doesn't follow the typical "just-eat" template.

You can merge this as-is if you want as I'm going to stop here for now. Missing regions are listed in the comments if anyone else wants to take over, I may add them in the future if not.

**Comment by J0WI** [comment]
Great work so far, thank you!
Future regions that differs from the current structure should have a separate ruleset, that is mentioned in the comments.

**Pull request merged**
