### PR TITLE
Add traintimes.org.uk

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please add target:
gingerbread.traintimes.org.uk

Please note as `Invalid certificate` in a top comment:
www.gingerbread.traintimes.org.uk
i.traintimes.org.uk
m.traintimes.org.uk
mx.traintimes.org.uk
pto.traintimes.org.uk
www.pto.traintimes.org.uk
split.traintimes.org.uk

**Comment by jeremyn** [comment]
Please:

- [ ] Sort both the `Invalid certificate` list and the `target`s alphabetically starting with the top-level domain at the right reading left, and move `^` and `www` to the top. For example:

```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```

**Comment by jeremyn** [comment]
Thanks, but please put the `securecookie` back the way it was, without `gingerbread`. The `gingerbread` site is silly, it doesn't set a cookie, and it clutters up the regex.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
