### PR TITLE
[Defense One] Fix #7881

### LINKED ISSUE #7881: defenseone.com constantly reloads
[defenseone.com](http://www.defenseone.com/) constantly reloads for new user with HTTPS Everywhere enabled. 

It appears to be cookie dependent, after certain interactions with the site, the flickering goes away. I was able to get the flicker via incognito.

### PR DESCRIPTION
**Pull request by synthtech**

### CODE REVIEW

**Comment by jeremyn** [comment]
@synthtech Are you still interested in working on this pull request?

**Comment by synthtech** [comment]
@jeremyn At this point, no.

Oddly enough, I can't reproduce the original issue on the latest version of httpse anyways, so this pr is probably not relevant anymore.

**Comment by jeremyn** [comment]
I also don't get the flickering effect at http://www.defenseone.com/ described in issue #7881, so it looks fixed to me too.

This could still be a general clean-up PR for this ruleset, but if you're not interested in working on this any more -- in particular, if you're not interested in implementing any feedback we might have after reviewing the PR more closely-- then please close this.

**Comment by synthtech** [comment]
Alright then.

**Pull request closed without merging**
