### PR TITLE
[ourcommons.ca] New rule

### PR DESCRIPTION
**Pull request by lexgill**

### CODE REVIEW

**Comment by jeremyn** [comment]
@lexgill Thanks for your pull request. Your ruleset has various small problems. Please:

- [ ] Replace what you have with this:
```xml
<ruleset name="OurCommons.ca">
	<target host="ourcommons.ca" />
	<target host="www.ourcommons.ca" />
	<target host="apps.ourcommons.ca" />
		<test url="http://apps.ourcommons.ca/ErrorPage/Templates/Images/ce-hoc-emblem-e.png" />
	<target host="petitions.ourcommons.ca" />
	<target host="subscription.ourcommons.ca" />
		<test url="http://subscription.ourcommons.ca/Committees/en/Newsletter" />

	<securecookie host=".+" name=".+" />

	<rule from="^http:" to="https:" />
</ruleset>
```

Please review the differences between this and what you have carefully, and also review [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md), and let me know if you have any questions. In particular note: tabs vs. spaces; name casing; additional `target`s; `target` sort order; `test`s for those `target`s that fail on their main/root URL; the `securecookie` (this is optional but okay to add here).

It looks like there is a related site in French, `noscommunes.ca`. You can add another file with another ruleset to this pull request for this domain if you want, but you don't have to. If you do, the two rulesets should point at each other in their top comment, for example compare [`3FM.nl`](https://github.com/EFForg/https-everywhere/blob/add11ce64ececf017edb8674d41ae1698df27728/src/chrome/content/rules/3FM.nl.xml#L2) and [`NPO3FM.nl`](https://github.com/EFForg/https-everywhere/blob/add11ce64ececf017edb8674d41ae1698df27728/src/chrome/content/rules/NPO3FM.nl.xml#L2).

**Comment by jeremyn** [comment]
@lexgill Can we move forward on this one?

**Comment by lexgill** [comment]
Thanks @jeremyn! I think this is better now? let me know if anything else needs to change.

**Comment by jeremyn** [comment]
Please:

`NosCommunes.ca.xml`:
- [ ] Change the filename from `noscommunes.ca.xml` to `NosCommunes.ca.xml` and update the reference in the other file.
- [ ] Remove both `test`s, they are not needed.

`OurCommons.ca.xml`:
- [ ] Rename `ourcommons.ca.xml` to `OurCommons.ca.xml` and update the reference in the other file.
- [ ] Remove both `test`s, they are not needed. For uncomplicated situations like this, extra `test`s are only needed when the direct response of the root URL such as https://apps.ourcommons.ca is not a 2XX or 3XX. In this case both https://apps.ourcommons.ca and https://subscription.ourcommons.ca return a 302. I know that I asked for `test`s in my earlier comment at https://github.com/EFForg/https-everywhere/pull/14042#issuecomment-353694020 and I'm sorry for any confusion.

**Comment by jeremyn** [comment]
@lexgill I'd like to finish this pull request if we can, please.

**Comment by jeremyn** [comment]
@lexgill I'd like to get this finished if we could. If we don't hear from you soon, I'm going to go ahead and make a new pull request myself for these domains.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/14042/commits/b4d8a4c1c6b44d2d57f0b1ef6375966ae488ed5c. The filename references are fine but the filenames themselves are still all lower-case. Also, there's a blank line at the end of `noscommunes.ca.xml`, please remove that.

**Comment by jeremyn** [comment]
@lexgill Can you please take a look at this?

**Comment by jeremyn** [comment]
@lexgill You've renamed the files without the final `.xml`. It should be `NosCommunes.ca.xml` and `OurCommons.ca.xml`, not `NosCommunes.ca` and `OurCommons.ca`.

**Comment by jeremyn** [comment]
@lexgill I'd like to get this merged. It's ready other than the problem with the names.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
