### PR TITLE
[BlueShore Financial] New Ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by jeremyn** [comment]
This looks fine. We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means combining and rewriting pull requests in your name. Are you okay with that for this and any other pull requests you submit to us?

**Comment by lucaspetter** [comment]
@jeremyn This pull request has only one commit, so how would squash-and-merge work here? Are you asking me to combine commits or pull requests?

**Comment by jeremyn** [comment]
@lucaspetter In this specific case, see the related discussion [here](https://github.com/EFForg/https-everywhere/issues/5838#issuecomment-247353766). Also I normally use the default commit message, so the commit message will be `Create BlueShore-Financial.xml (#7562)` instead of `Create BlueShore-Financial.xml` .

**Comment by lucaspetter** [comment]
Okay, it's squashed now.

**Comment by jeremyn** [comment]
@lucaspetter Squash-and-merge is something that we do as maintainers with pull requests through the GitHub interface. It's not something you can do for us ahead of time, and in fact I personally prefer that contributors not squash their own commits, for example see [here](https://github.com/EFForg/https-everywhere/issues/5838#issuecomment-248925155). I encourage you to try this yourself on your own repositories if you're not sure what I mean.

**Comment by lucaspetter** [comment]
Oh, I was confused! In your initial comment, it sounded like you were asking me to squash my own commits before you'd consider merging. Now I understand that you were just asking if I'm okay with you squash-and-merging. Yes, I'm okay with that.

**Comment by jeremyn** [comment]
Great, I'm glad that's cleared up, and thanks for the ruleset. Merged.

**Pull request merged**
