### PR TITLE
Create easyicon.net.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please:

Note as `Timeout`:
- [ ] ann.easyicon.net
- [ ] download.easyicon.net (See [SSLLABS](https://www.ssllabs.com/ssltest/analyze.html?d=download.easyicon.net))

Also I prefer using less newlines, likes the example in style guide. What do you think?

**Comment by ivysrono** [comment]
The MC break something?

**Comment by gloomy-ghost** [comment]
For example, "反馈意见" doesn't work on https://www.easyicon.net/thank.php

我的格式基本是用回车空开`target`, `securecookie`, `rule`，如果规则特别大的话看情况分割。
如果把`^`重定向到`www`可以考虑下规则缩进一格（可以看一下[这个](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/MondeDiplo.com.xml#L37)）

按照style guide里的例子的话是`from`和`to`放两行，但是一般只有`http:`到`https:`我嫌两行太空就放一行了，供参考……

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Pull request merged**
