### PR TITLE
Delete sign-rulesets-airgap.sh

### PR DESCRIPTION
**Pull request by koops76**
ping @Hainish @cowlicks.

This doesn't make signing any more secure.

Quoting https://github.com/EFForg/https-everywhere/issues/12087#issuecomment-325048106:
> Your "air-gap" scheme is no more secure than simply signing on a Internet-connected machine.
A compromised machine can output **any hash**, tricking you into *signing **any hash***.
Also it's easier to sneak a dodgy ruleset into the GitHub repository than trying to fool your "air-gap" scheme. Are you going to personally read each ruleset file?

### CODE REVIEW

**Comment by Hainish** [comment]
This does, we're not changing this process.  It prevents malware on a developer machine from automatically making a malicious signature of rulesets.  Malware which is detected is able to be removed (or the development machine rebuilt) befope a malicious signature is made, since the signing keys are separated by a physical airgap

**Comment by koops76** [comment]
Are you sure you will be able to notice the malware before it's too late?

**Comment by Hainish** [comment]
Certainty is never certain

**Comment by koops76** [comment]
What are you going to do if you find any malware? I hope you won't simply delete the executable and continue using this machine for signing.

**Pull request closed without merging**
