### PR TITLE
Rebased Amazon main shopping sites

### LINKED ISSUE #4997: HTTPS on Amazon
Amazon announced to finally support HTTPS. We should rebase our Amazon rules to check which sites can be secured now.

See also #1578 #3323 #3444 #4255 #4366

### PR DESCRIPTION
**Pull request by J0WI**
This should fix #4997 and all issues mentioned there.

ping @fuglede @Hainish for review

### CODE REVIEW

**Comment by J0WI** [comment]
Blocked by https://github.com/EFForg/https-everywhere/issues/4997#issuecomment-223850798

**Comment by J0WI** [comment]
rebased

**Comment by Hainish** [comment]
@J0WI lmk when this is ready for review again and I can check & merge

**Comment by J0WI** [comment]
@Hainish should already be ready.

**Comment by Hainish** [comment]
@J0WI okay, I'll review next week (I'm off today)

**Comment by J0WI** [comment]
I also addressed https://github.com/EFForg/https-everywhere/issues/4997#issuecomment-237163840 now.
cc @loveithateit

**Comment by Hainish** [comment]
Some things have come up which means I'll have to postpone reviewing this till next week

**Comment by Hainish** [comment]
Looks like ruleset validation isn't passing: `payments.amazon.com` is included in both `src/chrome/content/rules/Amazon.xml` as well as `src/chrome/content/rules/AmazonAWS.xml`.  Seems more appropriate in `Amazon.xml`

**Comment by Hainish** [comment]
All the fetch tests look good, and I've looked over the ruleset changes, these look fine.  Ready to merge once you remove `payments.amazon.com` from either of the above-mentioned rulesets.

**Comment by J0WI** [comment]
done

**Pull request merged**
