### PR TITLE
Added rule for predb.me

### PR DESCRIPTION
**Pull request by bvhr**
Added rule for PreDB (predb.me).

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Change the [`name`](https://github.com/bvhr/https-everywhere/blob/bd21f9c5c0f9247dcc996e3b5addcfceb42cc3fe/src/chrome/content/rules/predb.me.xml#L1) attribute to `predb.me`
- [ ] Change the leading spaces [here](https://github.com/bvhr/https-everywhere/blob/bd21f9c5c0f9247dcc996e3b5addcfceb42cc3fe/src/chrome/content/rules/predb.me.xml#L2) to one tab
- [ ] Remove the tab [here](https://github.com/bvhr/https-everywhere/blob/bd21f9c5c0f9247dcc996e3b5addcfceb42cc3fe/src/chrome/content/rules/predb.me.xml#L4)

**Comment by bvhr** [comment]
Sorry these were some stupid mistakes on my part. Hopefully it's all corrected now.

**Comment by jeremyn** [comment]
Thanks, I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7703/commits/f2f26871e784c50c00996dd97c64aed5526f2966. Can you please delete that last tab?

**Comment by bvhr** [comment]
I don't know how I missed that, but it should be fixed now.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
