### PR TITLE
PornHub: add cdn-d-vid-public, ht & services subdomain

### PR DESCRIPTION
**Pull request by numismatika**
Found a couple more subdomains while checking #6680

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] https://ht.pornhub.com is broken from mixed content, for example the `Learn More` button under `Industry Leading Payouts` doesn't expand. We shouldn't include this as a target. Can you move it under `Mixed content:` in the top comment?

**Comment by numismatika** [comment]
You are right. Google-API is blocked for mixed-content before we can rewrite it.

**Comment by jeremyn** [comment]
Not to rush you just but so the status is clear: the next step is for you to make the requested change, unless you have questions for me.

**Comment by jeremyn** [comment]
Looks good, thanks.

Last thing: we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means we rewrite commits in your name. Is that all right with you for this and any other pull requests you submit?

**Comment by numismatika** [comment]
I used to sqash my commits in a local branch before submitting the PR anyway.
Do how you want to do it. As long as everyone gets better rules i am fine with it.

**Comment by jeremyn** [comment]
Thanks. I've squash-and-merged.

I don't want contributors to squash their own commits. Unsquashed commits are easier to review. Instead, contributors should let us handle it. 

We're discussing what we should do in issue #5838 . Please feel free to add to that discussion. The current process is to squash-and-merge like I described.

**Pull request merged**
