### PR TITLE
Update ruleset: Real World OCaml.org

### PR DESCRIPTION
**Pull request by fghzxm**
* Add targets

* Remove target www.realworldocaml.org which seems forever broken

### CODE REVIEW

**Comment by J0WI** [comment]
> Remove target www.realworldocaml.org which seems forever broken

Could you add a comment for it?

**Comment by fghzxm** [comment]
`www.realworldocaml.org` uses an invalid certificate. The CN does not match the domain name, and the certificate is self-signed.

    $ openssl s_client -connect www.realworldocaml.org:443 | openssl x509 -text
    depth=0 CN = TRAEFIK DEFAULT CERT
    verify error:num=20:unable to get local issuer certificate
    verify return:1
    depth=0 CN = TRAEFIK DEFAULT CERT
    verify error:num=21:unable to verify the first certificate
    verify return:1
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                f5:cb:b7:c7:b7:ef:f7:e6:03:c1:32:c7:f7:3a:61:4b
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: CN = TRAEFIK DEFAULT CERT
            Validity
                Not Before: Aug 17 16:55:40 2018 GMT
                Not After : Aug 17 16:55:40 2019 GMT
            Subject: CN = TRAEFIK DEFAULT CERT
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        00:c4:7f:1b:2e:3f:04:d4:0e:b1:26:8c:09:ef:a0:
                        50:4c:97:c4:20:b9:28:66:79:3f:1b:85:9c:82:7f:
                        f4:e6:3b:33:81:bd:58:4f:e6:ba:c7:bf:d7:03:c0:
                        1a:c6:4b:02:ee:0c:84:62:5d:82:a2:78:42:46:82:
                        56:15:dd:ef:8e:14:59:1f:de:95:0e:f7:ab:d2:de:
                        00:21:19:2d:ba:d9:02:d5:54:52:19:0f:e9:47:97:
                        fc:ba:0f:51:8b:5b:be:36:5c:08:ce:4a:e1:52:70:
                        af:12:08:73:8a:82:9c:dc:df:02:f6:1d:a3:ef:74:
                        27:4c:ba:84:d5:98:24:de:63:97:2b:13:39:d0:ff:
                        70:f9:c9:28:ee:46:b1:d1:4c:08:14:f8:75:ad:6d:
                        f9:a4:24:9c:10:fa:de:bd:9e:61:2e:4f:36:ee:05:
                        d5:2d:b6:1f:55:bf:cf:79:2b:7c:ce:5a:e0:5e:31:
                        b5:25:b2:3e:d0:26:43:58:7f:d2:2b:88:36:40:bc:
                        39:16:54:00:b5:f8:f7:0d:57:64:5c:5b:10:cd:f5:
                        4a:d2:0d:9e:6b:a5:66:80:91:b9:a8:e8:a6:77:f1:
                        6d:53:c5:ca:e2:41:90:d9:fc:78:c3:e3:12:dc:6e:
                        2b:92:ec:5d:56:81:40:58:3b:ed:d6:c4:fb:d4:40:
                        40:9d
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Key Usage: critical
                    Key Encipherment
                X509v3 Basic Constraints: critical
                    CA:FALSE
                X509v3 Subject Alternative Name: 
                    DNS:62195012c1e9a8a703e7db917649c1fd.ab87d8683f8da97cd529e5135548637a.traefik.default
        Signature Algorithm: sha256WithRSAEncryption
             46:80:a9:17:63:c1:16:a7:76:c5:24:12:82:88:92:6e:5b:80:
             0b:71:01:0e:d7:3f:59:68:40:9e:b0:21:77:db:33:25:df:21:
             1c:84:ad:79:35:b2:06:5e:77:01:90:21:23:69:68:e1:5c:bd:
             ee:5e:fc:46:94:a3:b7:80:b3:eb:fa:64:c9:d4:35:97:fc:8c:
             26:5e:30:e8:46:2e:09:cd:04:22:bd:ae:6c:9a:3a:66:79:16:
             02:97:2f:b1:2d:e9:97:5d:d1:dc:92:0f:a0:ff:38:77:96:63:
             fa:5c:bb:ef:13:b3:c4:e8:de:0b:da:44:10:25:f6:c7:01:c6:
             a9:8a:1b:91:04:09:b5:f3:49:32:6a:6e:37:e5:f5:b3:ac:92:
             a2:3b:a6:d4:27:c6:c6:39:27:c1:cf:3d:5d:40:41:83:11:a8:
             7d:f5:1f:e8:db:01:c2:53:1f:4d:c3:14:88:f9:7e:a5:74:5b:
             02:1f:59:6e:24:12:24:12:5f:09:6b:a5:98:3f:33:7c:f2:1d:
             04:40:71:28:eb:87:4e:ea:ad:67:7e:46:41:77:a9:5a:15:fe:
             d6:17:64:95:a7:d5:7a:8f:30:23:fc:9d:93:71:f1:69:72:ee:
             21:b5:d0:a4:19:7f:0d:26:76:20:8d:82:5d:b6:fe:7b:2c:58:
             2e:ad:4a:be
    -----BEGIN CERTIFICATE-----
    MIIDRzCCAi+gAwIBAgIRAPXLt8e37/fmA8Eyx/c6YUswDQYJKoZIhvcNAQELBQAw
    HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMTgwODE3MTY1NTQw
    WhcNMTkwODE3MTY1NTQwWjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
    VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMR/Gy4/BNQOsSaMCe+g
    UEyXxCC5KGZ5PxuFnIJ/9OY7M4G9WE/muse/1wPAGsZLAu4MhGJdgqJ4QkaCVhXd
    744UWR/elQ73q9LeACEZLbrZAtVUUhkP6UeX/LoPUYtbvjZcCM5K4VJwrxIIc4qC
    nNzfAvYdo+90J0y6hNWYJN5jlysTOdD/cPnJKO5GsdFMCBT4da1t+aQknBD63r2e
    YS5PNu4F1S22H1W/z3krfM5a4F4xtSWyPtAmQ1h/0iuINkC8ORZUALX49w1XZFxb
    EM31StINnmulZoCRuajopnfxbVPFyuJBkNn8eMPjEtxuK5LsXVaBQFg77dbE+9RA
    QJ0CAwEAAaN+MHwwDgYDVR0PAQH/BAQDAgUgMAwGA1UdEwEB/wQCMAAwXAYDVR0R
    BFUwU4JRNjIxOTUwMTJjMWU5YThhNzAzZTdkYjkxNzY0OWMxZmQuYWI4N2Q4Njgz
    ZjhkYTk3Y2Q1MjllNTEzNTU0ODYzN2EudHJhZWZpay5kZWZhdWx0MA0GCSqGSIb3
    DQEBCwUAA4IBAQBGgKkXY8EWp3bFJBKCiJJuW4ALcQEO1z9ZaECesCF32zMl3yEc
    hK15NbIGXncBkCEjaWjhXL3uXvxGlKO3gLPr+mTJ1DWX/IwmXjDoRi4JzQQiva5s
    mjpmeRYCly+xLemXXdHckg+g/zh3lmP6XLvvE7PE6N4L2kQQJfbHAcapihuRBAm1
    80kyam435fWzrJKiO6bUJ8bGOSfBzz1dQEGDEah99R/o2wHCUx9NwxSI+X6ldFsC
    H1luJBIkEl8Ja6WYPzN88h0EQHEo64dO6q1nfkZBd6laFf7WF2SVp9V6jzAj/J2T
    cfFpcu4htdCkGX8NJnYgjYJdtv57LFgurUq+
    -----END CERTIFICATE-----

(Or should I just make `www.realworldocaml.org` redirect to `realworldocaml.org` in this case? Those sites have exactly identical contents, but are different sites nontheless (neither site redirects to the other).)

**Comment by J0WI** [comment]
See e.g. here: https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts

**Comment by fghzxm** [comment]
I have added the comment.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
