### PR TITLE
Fix two JS errors by replacing sync XHR

### PR DESCRIPTION
**Pull request by pipboy96**
This PR fixes these errors:
- `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/`
- `XML Parsing Error: syntax error` (This error is specific to Firefox)

Please test if this PR breaks anything before merging, even though it doesn't seem to.

### CODE REVIEW

**Comment by zoracon** [comment]
@pipboy96 which environments have you tested on for FF? I'll pull and test this week before the release to make sure this pans out well enough

**Comment by pipboy96** [comment]
@zoracon Firefox Nightly on Linux. I can also test on different versions of Firefox and also on Windows and macOS.

**Comment by pipboy96** [comment]
@J0WI Conflict resolved.

**Comment by pipboy96** [comment]
Closing for now.

**Pull request closed without merging**
