### PR TITLE
Update SLU.se.xml

### LINKED ISSUE #7502: SLU.se rule not working
Seems to be some issues with 
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/SLU.se.xml
I think the space between " and /> should be removed
Please also add rules to these URLs: student.slu.se, internt.slu.se, universitetsdjursjukhuset.se

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Close #7502

### CODE REVIEW

**Comment by jony0008** [comment]
This line is not right "^http://internt.slu.se/" to="https://internet.slu.se/"/>
It's https://internt.slu.se not https://internet.slu.se
Please fix it.

**Comment by jeremyn** [comment]
Please:

Mark as `Different HTTP/HTTPS content`:
- [ ] https://zeus.slu.se

Mark as `Other SSL error` (see "Also", below) and remove from `Invalid certificate`:
- [ ] https://www.saco.slu.se
- [ ] https://vmf.slu.se

Add `(incomplete certificate chain)` after these domains:
- [ ] https://vbsg-bio1.vbsg.slu.se (so: `vbsg-bio1.vbsg.slu.se (incomplete certificate chain)`)
- [ ] https://vbsg-nas1.vbsg.slu.se
- [ ] https://my-krakatau.mykopat.slu.se (and move from `Timeout` to `Invalid certificate`)

Add `target`:
- [ ] https://data-vc-cs1.data.slu.se (remove from `Reset`)
- [ ] https://pluto.slu.se (remove from `Invalid certificate`)
- [ ] https://vpn-alnarp.slu.se (remove from `Invalid certificate`)
- [ ] https://alumndb.slu.se (remove from `Timeout`)
- [ ] https://kronox-rapport.slu.se (remove from `Timeout`)
- [ ] https://lokalbokningwebb.slu.se (remove from `Timeout`)

Also:
- [ ] Rename `Protocol Error` to `Other SSL error`
- [ ] Remove the `securecookie`, there are too many non-working subdomains

Remove these entirely. My logic is that we shouldn't mention domains that fail both HTTPS and plain HTTP, even if they fail for different reasons.
- [ ] https://emma.slu.se
- [ ] https://ladok.slu.se
- [ ] https://mittslu.slu.se
- [ ] https://publikationer.slu.se
- [ ] https://sluportal.slu.se
- [ ] https://slwgeo.artdata.slu.se
- [ ] https://umea-met-fe03-1-vl2511.noc.slu.se
- [ ] https://pinus.slu.se
- [ ] https://vaxt2.vbsg.slu.se
- [ ] https://wayback.slu.se
- [ ] https://kamera4.vfp.slu.se
- [ ] https://atlas.slu.se
- [ ] https://info.adm.slu.se
- [ ] https://qpc.adm.slu.se
- [ ] https://exchange2013tes.adtest.slu.se
- [ ] https://exchange2013utv.adutv.slu.se
- [ ] https://alnarpsstudent.slu.se
- [ ] https://alnarpstennisklubb.slu.se
- [ ] https://www.apula.slu.se
- [ ] https://www.artdata.slu.se
- [ ] https://barngis.slu.se
- [ ] https://bilder.slu.se
- [ ] https://www.bioenergi.slu.se
- [ ] https://biostochastics.slu.se
- [ ] https://www.biotron.slu.se
- [ ] https://branschdag.slu.se
- [ ] https://www.bvf.slu.se
- [ ] https://www.cbm.slu.se
- [ ] https://disa.slu.se
- [ ] https://www.ekol.slu.se
- [ ] https://vilt.ekol.slu.se
- [ ] https://www.ekon.slu.se
- [ ] https://asa.esf.slu.se
- [ ] https://vfp.esf.slu.se
- [ ] https://www.ess.slu.se
- [ ] https://fagel.slu.se
- [ ] https://www.ffe.slu.se
- [ ] https://fiskbiologi.slu.se
- [ ] https://formastradgard.slu.se
- [ ] https://fortbildningalnarp.slu.se
- [ ] https://futurefaculty.slu.se
- [ ] https://www.genfys.slu.se
- [ ] https://heureka.slu.se
- [ ] https://www.hipp.slu.se
- [ ] https://www.hmh.slu.se
- [ ] https://www.huv.slu.se
- [ ] https://www.kemi.slu.se
- [ ] https://kt-et.slu.se
- [ ] https://kummel.slu.se
- [ ] https://kurs.slu.se
- [ ] https://langtidsforsok.slu.se
- [ ] https://lantbruketsarbetsmiljo.slu.se
- [ ] https://www.lmv.slu.se
- [ ] https://kv.lmv.slu.se
- [ ] https://www.lpal.slu.se
- [ ] https://www.lt.slu.se
- [ ] https://www.ma.slu.se
- [ ] https://www.mark.slu.se
- [ ] https://mkb.slu.se
- [ ] https://monitoringn60.slu.se
- [ ] https://bgf.mv.slu.se
- [ ] https://www.mykopat.slu.se
- [ ] https://naturenskalenderiskolan.slu.se
- [ ] https://nils.slu.se
- [ ] https://www.njv.slu.se
- [ ] https://www.nlfak.slu.se
- [ ] https://nobanis.slu.se
- [ ] https://www.nvb.slu.se
- [ ] https://ograsradgivaren.slu.se
- [ ] https://oringracet.slu.se
- [ ] https://partnerskapalnarp.slu.se
- [ ] https://plantarum.slu.se
- [ ] https://www.resgeom.slu.se
- [ ] https://www.sek.slu.se
- [ ] https://www.sfak.slu.se
- [ ] https://www.sfp.slu.se
- [ ] https://skogis.slu.se
- [ ] https://skogskarta.slu.se
- [ ] https://skoldkortelrubbninghoshund.slu.se
- [ ] https://slukarriar.slu.se
- [ ] https://slukurs.slu.se
- [ ] https://www.sml.slu.se
- [ ] https://www.smsk.slu.se
- [ ] https://www.sol.slu.se
- [ ] https://www.srh.slu.se
- [ ] https://www.ssko.slu.se
- [ ] https://superplot3d.slu.se
- [ ] https://www.svek.slu.se
- [ ] https://tillvaxtnotkott.slu.se
- [ ] https://tillvaxttradgard.slu.se
- [ ] https://pervenio.ucl.slu.se
- [ ] https://utbildning.slu.se
- [ ] https://uwa.slu.se
- [ ] https://www.vabr.slu.se
- [ ] https://www.vfm.slu.se
- [ ] https://www2.vfm.slu.se
- [ ] https://www.vhfak.slu.se
- [ ] https://webmap.slu.se
- [ ] https://webmap1.slu.se
- [ ] https://woodash.slu.se
- [ ] https://woodsupplygame.slu.se
- [ ] https://www-cru.slu.se
- [ ] https://www-data.slu.se
- [ ] https://www-genfys.slu.se
- [ ] https://www-genvagar.slu.se
- [ ] https://www-moosetrack.slu.se
- [ ] https://www-moosetrackbd.slu.se
- [ ] https://www-nfi.slu.se
- [ ] https://www-njv.slu.se
- [ ] https://www-sekon.slu.se
- [ ] https://www-skara.slu.se
- [ ] https://www-skogsskada.slu.se
- [ ] https://www-umea.slu.se
- [ ] https://ad.slu.se
- [ ] https://ess-server4.ess.slu.se
- [ ] https://gisweb.slu.se
- [ ] https://nj-booking.slu.se
- [ ] https://vbsg-serv2.vbsg.slu.se
- [ ] https://kamera5.vfp.slu.se
- [ ] https://epidrift-ext.slu.se
- [ ] https://epidrift-int.slu.se
- [ ] https://akkonferens.slu.se
- [ ] https://arbetsplats.slu.se
- [ ] https://blogg.slu.se
- [ ] https://cas.slu.se
- [ ] https://epi-resurs.slu.se
- [ ] https://personalkurser.slu.se
- [ ] https://resurs.slu.se
- [ ] https://slunik.slu.se
- [ ] https://student2.slu.se

**Comment by gloomy-ghost** [comment]
Ouch, this was generated by a earlier version script, thanks for checking them. I'll do it after.

BTW mittslu.slu.se is working for me now.

**Comment by jeremyn** [comment]
I've moved https://mittslu.slu.se to the `(incomplete certificate chain)` part of the checklist.

**Comment by gloomy-ghost** [comment]
I'm getting:

Reset
 https://www.saco.slu.se
 https://vmf.slu.se

Not failing http
 http://publikationer.slu.se/Filer/Mat-klimat-listanversion10-120413.pdf
 http://slwgeo.artdata.slu.se:8080/geoserver/web/
 http://wayback.slu.se:8080/
 http://info.adm.slu.se (301)
 http://qpc.adm.slu.se/6_Fundamentals_of_WHC/
 http://www.artdata.slu.se/guest/SSCBryo/SSCBryo.html 
 http://bilder.slu.se/puffbilder/large/dispenserw.jpg
 http://www.bioenergi.slu.se (301)
 http://www.biotron.slu.se (301)
 http://www.bvf.slu.se (301)
 http://www.cbm.slu.se (301)
 http://disa.slu.se
 http://www.ekol.slu.se (301)

Not finished yet, it's a quite long list =.=

**Comment by jony0008** [comment]
Is it possible to merge the partial changes?

**Comment by jeremyn** [comment]
@gloomy-ghost Please add a comment when you're ready for me to review everything.

**Comment by gloomy-ghost** [comment]
@jeremyn It's getting a bit messy, can we have a check that how much of the list are done at the moment?

**Comment by jeremyn** [comment]
@gloomy-ghost Sure. Can you please squash just the commits between and including https://github.com/EFForg/https-everywhere/pull/7504/commits/b57397ff41107e11bc00370e0a9c53ed2bd36515 and https://github.com/EFForg/https-everywhere/pull/7504/commits/f4bf206fc58926525ac6504cea62d911b309cd4e to make it easier to check what's changed?

**Comment by jeremyn** [comment]
@jony0008 If we only merged the partial changes, I think we would need to create a new pull request to do the rest, which would be confusing.

**Comment by jony0008** [comment]
@jeremyn I understand, thank you for working on it.

**Comment by jony0008** [comment]
@gloomy-ghost @jeremyn Will it be in the next release?

**Comment by jeremyn** [comment]
@gloomy-ghost Is this done and ready for a full review of the checklist?

**Comment by gloomy-ghost** [comment]
Not yet, and I'm currently not available to go through the checklist. Sorry for that.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7504/commits/2ae8a60582c197cc6f8798ee36f10ad0f24cea90.

**Comment by jeremyn** [comment]
I've freely updated the checklist in https://github.com/EFForg/https-everywhere/pull/7504#issuecomment-262857009 without marking all changes, for example I've deleted rather than ~~crossed out~~ many items from under `Remove these entirely` that now seem to be correct in the pull request. I guess there is heavy overlap with the changes I made and the items in @gloomy-ghost 's comment [here](https://github.com/EFForg/https-everywhere/pull/7504#issuecomment-262880080), but I did not go through that comment to make the updates.

I've also pushed changes to fix the remaining problems in the checklist. This pull request should now be ready to go.

@J0WI Could you review this please?

**Pull request merged**
