### PR TITLE
Update Tilera.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by fuglede** [comment]
Insofar that this PR only changes the <code>default_off</code> note: I'm not actually seeing refused connections here:

	$ curl -v https://support.tilera.com
	* Rebuilt URL to: https://support.tilera.com/
	* Hostname was NOT found in DNS cache
	*   Trying 104.171.11.181...
	* Connected to support.tilera.com (104.171.11.181) port 443 (#0)
	* successfully set certificate verify locations:
	*   CAfile: none
	  CApath: /etc/ssl/certs
	* SSLv3, TLS handshake, Client hello (1):
	* Unknown SSL protocol error in connection to support.tilera.com:443 
	* Closing connection 0
	curl: (35) Unknown SSL protocol error in connection to support.tilera.com:443

**Comment by J0WI** [comment]
Okay, it's not refused, but the server doesn't support TLS nor SSL. Do we have a state for that?

**Comment by fuglede** [comment]
I don't think there's any rules for what the notes should be like; I think the curl error message is descriptive enough. If you want to choose between the ones already used, here's a complete list:

default_off note | count
--------------------|-------
mismatched | 746
mismatch | 557
self-signed | 524
expired | 393
expired, self-signed | 233
missing certificate chain | 207
connection refused | 104
mismatched, self-signed | 79
expired, mismatched, self-signed | 73
mismatch, self-signed | 73
Certificate mismatch | 59
expired, mismatched | 55
broken | 53
connection dropped | 50
expired, mismatch, self-signed | 45
expired, mismatch | 29
expired, missing certificate chain | 28
needs clearnet testing | 21
redirects to http | 20
plaintext reply | 20
connection reset | 18
Needs ruleset tests | 17
404 | 15
untrusted root | 15
mismatches | 14
handshake failure | 14
Breaks site | 13
Akamai | 12
Cert warning | 12
Bad Cert | 12
shows default page | 11
webmaster request | 9
reported broken | 9
needs testing | 8
handshake fails | 8
521 | 8
522 | 8
breaks site | 8
akamai cert | 8
Akamai certificate | 7
akamai certificate | 7
testing | 6
invalid certificate | 5
shows another domain | 5
cert expired | 4
Expired certificate | 4
certificate mismatch | 4
JS redirect to http | 4
missing certificate chain, needs clearnet testing | 4
Invalid Certificate | 4
redirect loops | 4
503 | 4
js redirect to http | 4
cert warning | 4
Breaks login | 3
403 | 3
Breaks some images | 3
http redirect | 3
Breaks some games | 3
breaks for non-logged-in users | 3
invalid cert | 3
Breaks videos | 3
breaks some embedded videos | 2
breaks images | 2
all infinite loops | 2
Appears to break certain registration pages when JavaScript scripting is enabled. | 2
user choice | 2
Redirect loops | 2
It remains to be determined which URLs indicate SSL support | 2
breaks background | 2
causes image problems | 2
Needs review | 2
https://www.eff.org/r.b6G9 | 2
akamai | 2
ruleset coverage test fails | 2
breaks images on the OKC blog | 2
breaks MyWOT extension | 2
No HTTPS support anymore | 2
Breaks login functionality | 2
https://trac.torproject.org/projects/tor/ticket/7107 | 2
breaks login | 2
Redirects to HTTP | 2
expired, mismatched, missing certificate chain | 2
tender certificate | 2
mimatched | 2
JS redirection loops | 2
expired, mismatched, untrusted root | 2
Full SSL not supported | 2
Akamai certificate, expired | 2
expired, untrusted root | 2
Breaks abc.go.com | 2
broken? | 2
self signed | 2
Breaks many redirectors | 2
No longer supports HTTPS | 2
Breaks some functions | 2
Breaks functionality | 2
breaks videos | 2
https://www.eff.org/r.1bF6 | 2
https://www.eff.org/r.5E5 | 2
Breaks linux.dell.com | 2
currently broken | 2
Cacert signed | 2
Support section redirect loops | 2
displays error message | 2
breaks streaming | 2
Site does not support HTTPS currently | 2
400, expired, missing certificate chain | 2
comment threads fail to load | 2
wrong host in certificates | 2
broken assets | 2
Doesn't support HTTPS anymore | 2
Breaks startpage image search | 2
md5, self-signed | 2
breaks CSS on pastes | 2
breaks CSS | 2
revoked | 2
breaks www.reuters.com | 2
TLS error | 2
registration, avatar system not fully supported | 2
Cert wildcard depth mismatch | 2
https gone | 2
Breaks video content, probably best to block doubleclick instead | 2
breaks Look Inside the Book | 2
SSL error | 2
Breaks blog | 2
cert mismatches | 2
breaks downloads | 2
no response | 2
JS redirect loop | 2
Some parts of the sites don't work | 2
expired certificate | 2
sometimes returns 500 | 2
502 | 2
500 | 2
https://trac.torproject.org/projects/tor/ticket/7278 | 2
breaks bytelove | 2
expired, md5 signed | 2
Connection refused | 2
apparently breaks downloads for logged-in users | 2
breaks shopping cart | 2
trips on its own referrers | 2
Breaks form submission | 2
self-siged | 2
Breaks video | 2
Bad redirects | 2
https://www.eff.org/r.2arJ | 2
Breaks cart | 2
default off by site request | 2
waiting for webmasters to indicate site is ready | 2
missing certificate chain, self-signed | 2
Cert expired in 2009 | 2
mismatched, self-signed, some pages 404 | 2
Breaks certain pop-up content (such as the &quot;Find Internet access numbers&quot; option at [http://www.earthlink.net/membercenter/gethelp.faces]) | 2
https://trac.torproject.org/projects/tor/ticket/5804 | 2
Breaks comments | 2
shows incontri5stelle.com | 2
breaks image zoom | 2
various things break | 2
mismatch, missing certificate chain | 2
Expired | 2
expired cert | 2
missing certificate chain, untrusted root | 2
JS redirection loop | 2
redirects to HTTP | 2
Certificate mismatch, self-signed | 2
breaks some flash content | 2
invalid certificates | 2
HTTPS and HTTP content differ | 2
sometimes 403s | 2
Certificate for tv.jobindex.dk is only valid for *.23video.com (ssl_error_bad_cert_domain) | 2
Breaks steam games | 2
https://www.eff.org/r.1apH | 2
Breaks icon font | 2
breaks some URLs | 2
mismatched, missing certificate chain, untrusted root | 1
Breaks overlays | 1
mismatched, missing certificate chain | 1
JS redirects back to HTTP | 1
Broken login form, may work seamlessly with platform='mixedcontent' | 1
possibly superseded | 1
https://trac.torproject.org/projects/tor/ticket/9613 | 1
Mixed content block breaks advert editing and certain images | 1
Breaks fonts | 1
breaks site, cert expired | 1
breaks video | 1
breaks some video embedding | 1
Additional testing recommended | 1
Site no longer exists | 1
Redirect loop | 1
refused | 1
Certificates are invalid | 1
https://www.eff.org/r.3bSc | 1
can't add items to cart | 1
breaks surveys! | 1
no longer supports SSL | 1
differs from http | 1
Breaks lenovo `ask a question' | 1
Broken | 1
HTTPS URL not found | 1
https://lists.eff.org/pipermail/https-everywhere-rules/2013-November/001737.html | 1
buggy | 1
breaks some games | 1
breaks storm reports | 1
No valid certificates | 1
self-signed, mismatch | 1
bluehost certificate | 1
Breaks the SU extension | 1
Certificate expired | 1
default page | 1
mismatch, self-signed, may need more exclusions | 1
mismatched, missing certificate chain, self-signed | 1
Breaks icons | 1
Have not caught all exclusion patterns | 1

**Comment by J0WI** [comment]
cc @fuglede @loveithateit

**Pull request merged**
