### PR TITLE
Update Edubuntu.org.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by J0WI** [comment]
Why did you remove wiki.edubuntu.org? The host is still up and WFM.

**Comment by ekaris** [comment]
Because it redirects to wiki.ubuntu.com

**Comment by J0WI** [comment]
Only the http version, https works.
Your branch conflicts with some other changes, could you rebase it?

**Comment by ekaris** [comment]
Apparently someone fixed the issues before my pull was accepted.

**Pull request closed without merging**
