### PR TITLE
Added Alternativet.dk.xml

### PR DESCRIPTION
**Pull request by fuglede**
Marked partial as a few ressources are fetched over HTTP. Still, the site itself works fine.

### CODE REVIEW

**Comment by reedy** [comment]
Test failure is unrelated, it's in WeeklyPlus.xml which is now fixed

**Comment by reedy** [comment]
But the site loads a lot of mixed content when visited in HTTPS

**Comment by fuglede** [comment]
A few stylesheets and a Google API font, right? I just noticed now that this actually causes the four gray links at the top to become hidden. I notified the website devs about this, so hopefully they will fix the hardcoded references.

default_off="mixedcontent" until then?

**Comment by fuglede** [comment]
Updated to the new ruleset style

**Pull request merged**
