### PR TITLE
Create IRCTC.co.in.xml

### PR DESCRIPTION
**Pull request by anand-bhat**

### CODE REVIEW

**Comment by TheNavigat** [comment]
Would be nice if you could squash both those commits.

**Comment by anand-bhat** [comment]
I appear to have delete my fork and am not sure how to squash these commits now :(

**Comment by TheNavigat** [comment]
Well, that's okay. Squashing the commits isn't that critical. However, I need a little bit more time before I check this.

And I don't have merging permissions, really. I just help the team responsible for merging by LGTM-ing PRs, and by creating my own PRs as well.

**Comment by TheNavigat** [comment]
Okay, LGTM!

**Pull request merged**
