### PR TITLE
Fixes #2430

### LINKED ISSUE #2430: BROKEN RULESET (Scene7)
https://www.verizonwireless.com/wcms/consumer/products/verizon-messages.html

Scene7 breaks video at bottom.

### PR DESCRIPTION
**Pull request by terrorist96**

### CODE REVIEW

**Comment by fuglede** [comment]
Thanks for the PR! The ruleset does the job but the ruleset test runs into a few errors:

    ERROR src/chrome/content/rules/Scene7.xml: Not enough tests (1 vs 2) for <Rule from '^http://(?:www\.)?scene7\.com/[^\?]*(\?.*)?' to 'https://www.adobe.com/products/scene7.html\g<1>'>
    ERROR src/chrome/content/rules/Scene7.xml: Not enough tests (0 vs 1) for <Rule from '^http://www1\.scene7\.com/' to 'https://www1.scene7.com/'>
    ERROR src/chrome/content/rules/Scene7.xml: Not enough tests (0 vs 2) for <Rule from '^http://([\w-]+)\.scene7\.com/' to 'https://a248.e.akamai.net/f/248/9086/10h/\g<1>.scene7.com/'>
    ERROR src/chrome/content/rules/Scene7.xml: Not enough tests (0 vs 1) for <Exclusion pattern 'http://s7mbrstream\.scene7\.com/'>
    Ruleset test coverage was insufficient.

Fixing this amounts to adding the relevant test URLs (which should be added for all newly changed rulesets); you can find more information [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md).

**Comment by terrorist96** [comment]
Good god, this is too much. I can't do this anymore. I just want HTTPS Everywhere not to break stuff.

**Comment by fuglede** [comment]
That's fair enough; I added a fix in #3181.

**Comment by terrorist96** [comment]
Sigh, thank you!

**Pull request closed without merging**
