### PR TITLE
Add ottos.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by reedy** [comment]
There's a load of mixed content on this site

**Comment by J0WI** [comment]
It doesn't seem to break anything and online shops are related with sensitive data.

**Comment by jsha** [comment]
https://www.ottos.ch redirects to HTTP.

**Comment by J0WI** [comment]
Noo, I sent them a mail about the mixed content issues, no it went from bad to worse :'(

**Pull request merged**
