### PR TITLE
update DYC.edu.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Mixed content breaks calendar at the bottom right of https://www.dyc.edu and https://careers.dyc.edu
- [ ] Add https://ads.dyc.edu/dyouville_g_freshmen/ as a `test` for https://ads.dyc.edu
- [ ] Add https://services.dyc.edu/Student/ as a `test` for https://services.dyc.edu

Do something with these:

- [ ] https://casi.dyc.edu
- [ ] https://gallery.dyc.edu
- [ ] https://portal.dyc.edu
- [ ] https://publications.dyc.edu
- [ ] https://services.dyc.edu
- [ ] https://spartancentral.dyc.edu
- [ ] https://student.dyc.edu

**Comment by jeremyn** [comment]
@J0WI I saw the same [Travis handshake error](https://travis-ci.org/EFForg/https-everywhere/jobs/204591854#L211) in PR #8614 and mentioned it [here](https://github.com/EFForg/https-everywhere/pull/8614#issuecomment-282105007). I want to wait to hear from @Hainish on that before giving up on the `moodle` subdomain.

**Comment by Hainish** [comment]
This should be fixed by https://github.com/EFForg/https-everywhere/commit/403c46296f54b9e9e402c82ac0b6ca71c24dbcc2

Rerunning tests

**Comment by jeremyn** [comment]
Thanks @Hainish!

**Comment by J0WI** [comment]
rebased

**Comment by jeremyn** [comment]
Thanks, merged. I also deleted the individual commit messages when I squash-and-merged.

**Pull request merged**
