### PR TITLE
ulteo.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks.

- [ ] Make these targets and remove them from the comment: https://docs.ulteo.com , https://project.ulteo.com , https://code.ulteo.com , https://servicedesk.ulteo.com
- [ ] Note these as timeouts: https://ulteo.com , https://archive.ulteo.com , https://doc.ulteo.com
- [ ] https://www.ulteo.com has mixed-content blocking, so remove the target and note it as having mixed-content blocking in the top comment

Because of the previous item:
- [ ] remove the rule and test for http://ulteo.com/
- [ ] rename the ruleset to `ulteo.com (partial)`

**Comment by galeksandrp** [comment]
Oops.

**Comment by jeremyn** [comment]
In addition to the failing tests, I get a `timeout` for the three domains in the remaining to-do item above, not `refused`.

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of pull request #7492 .

**Pull request closed without merging**
