### PR TITLE
Create bgm.tv.xml

### PR DESCRIPTION
**Pull request by Coxxs**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Coxxs Thanks for your pull request. Your ruleset has various small problems. Please:

- [ ] Replace what you have with this, with filename `Bgm.tv.xml`:
```xml
<ruleset name="Bgm.tv">
	<target host="bgm.tv" />
	<target host="www.bgm.tv" />
	<target host="doujin.bgm.tv" />
	<target host="lain.bgm.tv" />
	<target host="navi.bgm.tv" />

	<securecookie host=".+" name=".+" />

	<rule from="^http:" to="https:" />
</ruleset>
```

Please carefully review the differences between this and what you have, and also review [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md), and let me know if you have any questions. In particular note: name casing; additional `target`s; `target` sort order; the `securecookie` (this is optional but okay to add here).

**Comment by jeremyn** [comment]
@Coxxs We don't need the extra `test`s, please remove them.

**Comment by Coxxs** [comment]
I see, Thank you. The CI failed previously so I thought add tests would help.

**Comment by jeremyn** [comment]
Thanks, merged.

I'm not sure why the CI testing failed before. The tests should give a clear message if you need to add tests, see [`test/rules/src/https_everywhere_checker/rules.py#L300-L302`](https://github.com/EFForg/https-everywhere/blob/32e9cac42ddde7f23c1dc26470546c4dce9d9cc1/test/rules/src/https_everywhere_checker/rules.py#L300-L302).

**Pull request merged**
