### PR TITLE
Fix #1656

### LINKED ISSUE #1656: Lenovo unable to customize computers or see "Sold Out" when enabled in https-everywhere
Eg:
http://shop.lenovo.com/us/en/laptops/thinkpad/x-series/x1-carbon/

Fixed by disabling Lenovo in https-everywhere

### PR DESCRIPTION
**Pull request by galeksandrp**
#1656

### CODE REVIEW

**Comment by J0WI** [comment]
retest

**Comment by J0WI** [comment]
This seems very difficult to rebase, but at least it requires some more test urls.

**Comment by J0WI** [comment]
See also https://github.com/EFForg/https-everywhere/issues/1656#issuecomment-223468231

**Comment by J0WI** [comment]
Let me ask @Hainish if he still want to disable it.

**Comment by Hainish** [comment]
@J0WI it looks like some commits were made since I made that comment.

Can you review, and if it looks like this is still failing then we can disable it.  LMK if it's failing and I'll open a separate PR to just disable

**Comment by J0WI** [comment]
Closed by #9381

**Pull request closed without merging**
