### PR TITLE
Create new rules for Bluesnews, Controllerpro, Gamecritics, Gamegeekdenter, Gamesandpals, Gameselectors, Gamewithyourbrain, Howinerd, PCgamer, and Siliconera.

### PR DESCRIPTION
**Pull request by pn303**

### CODE REVIEW

**Comment by pn303** [comment]
Merge pull request #9692 @Hainish @Bisaloo. Rulesets created for Eventhubs and Gamerswithjobs.

**Comment by J0WI** [comment]
Could you please open one separate PR for each new ruleset?

**Comment by pn303** [comment]
Sure, will do. Just need to play around a bit and see how to do it.

**Comment by J0WI** [comment]
You should use a new branch for each new ruleset.

**Comment by pn303** [comment]
Ok, thank you for the information

**Comment by pn303** [comment]
I might have to delete my repository and start a new one, so that things can be done again properly. What I did not quite get is the branches for every new ruleset. For example, if I have made 15 rulesets, do I need to have 15 separate branches for each and send pull request from each branch separately, or I can have one branch for all of my new rulesets, but have them as different commits?

**Comment by J0WI** [comment]
You need 15 separate branches and pull requests.

**Pull request closed without merging**
