### PR TITLE
Specify the exact python version, don't just assume it's python 2.7

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by Hainish** [comment]
This fixes the issue raised in https://github.com/EFForg/https-everywhere/issues/6749#issuecomment-245541379

**Comment by J0WI** [comment]
I think `#!/usr/bin/env python2.7` would be even better.

**Comment by Hainish** [comment]
Ready to review again

**Comment by Hainish** [comment]
cc @cooperq

**Comment by cooperq** [comment]
LGTM

**Pull request merged**
