### PR TITLE
Create Dogecoin-P2Pool.xml

### PR DESCRIPTION
**Pull request by CohibAA**

### CODE REVIEW

**Comment by reedy** [comment]
Attackers might be trying to steal your information from dogecoin-p2pool.com (for example, passwords, messages or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

This server could not prove that it is dogecoin-p2pool.com; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.

```
This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store.
```

**Comment by CohibAA** [comment]
The certificate is not trusted because it is [self-signed](https://en.wikipedia.org/wiki/Self-signed_certificate).  I wasn't able to find specifications for submitting a self-signed SSL xml ruleset if they are different than CA signed rulesets.  Are self-signed certs not accepted to the master httpseverywhere rules?  If they are permitted for inclusion but I missed something, can you please point me in the right direction if I need to modify something in the ruleset?

**Comment by jsha** [comment]
Generally no, we don't accept rulesets for sites with self-signed certs.

**Comment by CohibAA** [comment]
Understood, thank you for the quick reply.

**Comment by reedy** [comment]
Closing as self signed cert

**Pull request closed without merging**
