### PR TITLE
added dict.cc

### PR DESCRIPTION
**Pull request by J0WI**
rebased #1692 / #1946 
Couldn't reproduce the problems on options.php.

### CODE REVIEW

**Comment by J0WI** [comment]
Very popular domain in Germany (cc @fuglede)

**Comment by tomwys** [comment]
It seams that they have wildcard domain configuration because random domains such as https://asdfasdfsad.dict.cc/ work. So maybe it is the case we should use *.dict.cc rather than enumerating domains? @fuglede any opinion on that topic?

**Comment by fuglede** [comment]
I don't necessarily disagree entirely. However, there are already quite a few subdomains which would have to be excluded, so it boils down to the following: Do we expect more subdomains to arise which would then be automatically broken by not being excluded? And sort-of-conversely: do we expect more language-style subdomains to arise which would then have to be maintained individually? Both are pains, and we want the least of them.

**Comment by J0WI** [comment]
It's harder to maintain wildcard rules with wildcard exclusions, so I decided to support just the common domains.

**Comment by fuglede** [comment]
Some issues:
- The ruleset redirects http://dict.cc to https://dict.cc which serves a bad cert.
- https://www9.dict.cc [serves an incomplete chain](https://www.ssllabs.com/ssltest/analyze.html?d=www9.dict.cc&latest) and should be removed from the ruleset.
- pocket.dict.cc might be securable.
- you could add contribute.dict.cc to the list of bad subdomains.
- if one goes to a non-secured page, say http://contribute.dict.cc, and presses "Optionen", then [things break](https://www.dict.cc/dict/options.php?ref=http%3A%2F%2Fcontribute.dict.cc%2F%3Faction%3D%26id%3D%26p%3D%26goback%3D%26f%3D%26o%3D).

**Comment by J0WI** [comment]
Thanks for the feedback. All points should be fixed now.

**Comment by fuglede** [comment]
Thanks for the fixes. The first four points are fixed, but the last one persists: [this page](https://www.dict.cc/dict/options.php?ref=http%3A%2F%2Fcontribute.dict.cc%2F%3Faction%3D%26id%3D%26p%3D%26goback%3D%26f%3D%26o%3D) is not downgraded, for instance.

**Comment by J0WI** [comment]
(updated)

**Pull request merged**
