### PR TITLE
Update JD.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by lqf96** [comment]
Seems that Jingdong just added https support for their site, because in https version of the site links are still pointing to http. also there are broken scripts (https://item.jd.com/1055517884.html). Anyway it's still a huge step towards better internet in china.

**Comment by J0WI** [comment]
@renyouguo would you like to continue here?

**Comment by renyouguo** [comment]
@J0WI Sorry,where are the conflicts?

**Comment by J0WI** [comment]
This branch needs to be rebased, I can't merge it.

**Pull request closed without merging**
