### PR TITLE
Updated Mining.Bitcoin.cz.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by fuglede** [comment]
Is the domain beta.mining.bitcoin.cz still in use? It seems that that part of the ruleset could still be used.

**Comment by J0WI** [comment]
Got mismatch and 301 on https://beta.mining.bitcoin.cz/

**Comment by fuglede** [comment]
Ah, you're right, what I meant to say was that since http://beta.mining.bitcoin.cz redirects, one could add a <code>\<rule from="http://beta\\.mining\\.bitcoin\\.cz" to="https://mining.bitcoin.cz" /\></code>

**Comment by fuglede** [comment]
Whoops, looks like I forgot the trailing slashes in my suggestion. It should be <code>http://beta\\.mining\\.bitcoin\\.cz/</code> and <code>https://mining.bitcoin.cz/</code> respectively.

**Comment by J0WI** [comment]
Oops, I didn't double check.

**Comment by fuglede** [comment]
... and I also forgot the leading <code>^</code>. Sorry about that.

**Comment by J0WI** [comment]
green :)

**Comment by fuglede** [comment]
Thanks.

**Pull request merged**
