### PR TITLE
Create pornolab.net.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

- [ ] Remove the comment for `mail` since it's refusing both http and https

**Comment by Folant** [comment]
Done.

**Comment by gloomy-ghost** [comment]
Merged, thanks again!

**Comment by EgorKeke69** [comment]
Hi. Please add official mirror:
http://pornolab.cc
http://pornolab.biz

**Pull request merged**
