### PR TITLE
Create SageMath.org.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by Bisaloo** [comment]
The tests should warn that we already have rules for some of those targets. I can't find anything about it. Can you, @I-have-50-open-PRs-to-HTTPS-EVERYWHERE ?

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@Bisaloo Yes https://travis-ci.org/EFForg/https-everywhere/jobs/287891828 

['src/chrome/content/rules/SageMath.org.xml', 'src/chrome/content/rules/Sagemath.org.xml'] failed case-insensitivity testing.

Rules exist with identical case-insensitive names, which breaks some filesystems.

Will make a new PR

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@Bisaloo Here's the new PR https://github.com/EFForg/https-everywhere/pull/13142

**Comment by Bisaloo** [comment]
> ['src/chrome/content/rules/SageMath.org.xml', 'src/chrome/content/rules/Sagemath.org.xml'] failed case-insensitivity testing.
>
> Rules exist with identical case-insensitive names, which breaks some filesystems.

Hum, that's not what I was talking about. We are supposed to have a test that prevents duplicated targets (see `utils/duplicate-whitelist.txt`). In this case, if you named your ruleset differently, it could have gone through. This shouldn't happen.

**Pull request closed without merging**
