### PR TITLE
rk37.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Note `www.rk37.ru` at the top as `Connection reset` and remove the inline comment

**Comment by galeksandrp** [comment]
Retest.

**Comment by jeremyn** [comment]
I'm still getting a connection reset message from Firefox with https://www.rk37.ru . `curl` reports `Unknown SSL protocol error`.

**Comment by galeksandrp** [comment]
Yep, `curl https://www.rk37.ru` works, when `curl https://www.rk37.ru/` not.

**Comment by jeremyn** [comment]
https://www.rk37.ru gets a `Secure Connection Failed`/`connection reset` error so we can't include in the ruleset. Are you waiting on me for something?

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of pull request #7493 .

**Pull request closed without merging**
