### PR TITLE
[openblox.org] Delete OpenBlox.xml

### PR DESCRIPTION
**Pull request by JohnMHarrisJr**
I have added a new test for another subdomain of openblox.org. Hope this helps!

### CODE REVIEW

**Comment by jeremyn** [comment]
@JohnMHarrisJr Thanks for the update.

It looks `openblox.org` is fully HSTS preloaded: it's in [Chromium](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json#10529), [Firefox](https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#6383), and [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n8172), and otherwise looks correctly HSTS configured. We like to delete rulesets that are completely HSTS preloaded. Can you change this pull request to instead delete `OpenBlox.xml`?

**Comment by JohnMHarrisJr** [comment]
Sure, I didn't realize it was preloaded.

On October 8, 2016 10:47:50 AM EDT, Jeremy Nation <notifications@github.com> wrote:
>@JohnMHarrisJr Thanks for the update.
>
>It looks `openblox.org` is fully HSTS preloaded: it's in
>[Chromium](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json#10529),
>[Firefox](https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#6383),
>and
>[Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n8172),
>and otherwise looks correctly HSTS configured. We like to delete
>rulesets that are completely HSTS preloaded. Can you change this pull
>request to instead delete `OpenBlox.xml`?

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by jeremyn** [comment]
No problem.

We like to [squash-and-merge`](https://help.github.com/articles/about-pull-request-merges/) commits, which means we rewrite commits in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by JohnMHarrisJr** [comment]
@jeremyn That's absolutely fine.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
