### PR TITLE
Update 360.cn

### PR DESCRIPTION
**Pull request by gloomy-ghost**
1. `down.360.cn` does not have a valid certificate
2. `yunpan.360.cn` has been supporting https

### CODE REVIEW

**Comment by renyouguo** [comment]
@gloomy-ghost I get https://c[2-79].yunpan.360.cn
You may need to edit.

**Comment by gloomy-ghost** [comment]
@renyouguo

I through that subdomains under `yunpan.360.cn` are exactly the same before I found`huodong.yunpan.360.cn`, and I was considering the readability... Would `c*.yunpan.360.cn` be acceptable?

反正感觉现在v2ex的气氛很奇怪눈_눈

**Comment by renyouguo** [comment]
@gloomy-ghost The project team will ask you list all the subdomains, as they hate wildcards.

**Comment by gloomy-ghost** [comment]
@renyouguo There are 78+1 subdomains... I will use a script to generate them if they really ask this...

**Comment by renyouguo** [comment]
@gloomy-ghost I am writing a python script to generate universial HTTPSEW rule.
问题是，我TM是个文科生啊！我还没对象啊！我才自学了一点点Python，连面向对象编程都理解不了啊！说好的Python库应有尽有呢！

**Comment by gloomy-ghost** [comment]
@renyouguo universial rule?

我早就放弃去理解OOP了……基本当成namespace用，偶尔发现可以继承一下少写很多东西。<del>话说不看看Java么</del>

以及不管是文科的帅哥还是逛GitHub的妹子都是稀有生物吧ε=ε=ε=┏(゜ロ゜;)┛

**Comment by renyouguo** [comment]
@gloomy-ghost universal……
不是说Python最适合文科生入门么，我就上了——结果上了贼船才发现，说三天就能上手Python写项目的，他们杀都会，仅仅是没碰过Python而已！

**Comment by gloomy-ghost** [comment]
@renyouguo 知道universal但是不太能理解universal rule……是指用template自动生成还是什么……

半年200条也是挺拼的……我表示脑子里根本没多少国内网站，能想到的基本都有规则了……以后还有规则要处理的时候可以叫我，有空的话一定来233

Python用来入门确实没什么不对劲的地方啊……拿封装好的库先做点东西出来会有点成就感，然后再思考算法之类的东西……<del>说起来我在Coursea上选的两门algorithm开课快半个月了都还没看呢</del>

突然想到这个： https://www.zhihu.com/question/49913095/answer/118418616

**Comment by renyouguo** [comment]
@gloomy-ghost 好吧，我的烂英语，大概就是我希望能做到填入文件名、顶部注释、规则名、主域名、子域名、规则、等等来自动生成规则文件。
以我这三脚猫功夫，大概只能做一个很简陋的模板然后每次用都直接修改源码……
算了，就当见证自己学习的脚步吧。

**Comment by jeremyn** [comment]
I don't understand the non-English text here so I'm sorry if I'm repeating something.

We don't like wildcards but having individual entries for each of `c[2-79].yunpan.360.cn` is also not good. Look [here](https://github.com/EFForg/https-everywhere/pull/6867#issuecomment-246965475) and the following discussion for a strategy on how to do it. Basically, you use a wildcard `target` and a specific regex in the `rule`.

**Comment by renyouguo** [comment]
I get 
```sdl*.yunpan.360.cn```

test url:
```http://sdl67.yunpan.360.cn/share.php?method=Share.download&cqid=c9ac68fc3c76f78b00e5ed9c27f493d8&dt=67.7fb3361146a98fa59cf4ea88237ec186&e=1474299761&fhash=039e5a2052c0fc2ad7c3f1f28b61f36b34eac729&fname=%25E5%25BE%25AE%25E4%25BF%25A1v6.3.25_8%25E6%259C%258830%25E5%258F%25B7_%25E6%25AD%25A3%25E5%25BC%258F%25E7%2589%2588.apk&fsize=36731436&nid=14725424049497483&st=59204acc958796a92f4ff0f76304c1aa&xqid=1290207811```

**Comment by jeremyn** [comment]
@renyouguo Are you asking me something? I can't tell, I'm sorry.

**Comment by renyouguo** [comment]
@jeremyn I am asking you in 6830...

**Comment by gloomy-ghost** [comment]
@renyouguo I got a 514 FatalError for your test url.

@jeremyn Nevermind about the chats in Chinese, they are not relating to this PR. Can you check that the new commit is okay or not?

**Comment by renyouguo** [comment]
@gloomy-ghost you may need to test it in tor. There are several https sites only available in China. See #6889

**Comment by gloomy-ghost** [comment]
@renyouguo Checked. There is no problem to access it outside China.

**Comment by renyouguo** [comment]
@gloomy-ghost I mean the 514 FatalError.

**Comment by gloomy-ghost** [comment]
@renyouguo I thought you meant simulating overseas accesses when you mentioned Tor... It is getting confusing now.

**Comment by gloomy-ghost** [comment]
@renyouguo 我现在不在国内，你那个`sdl67.yunpan.360.cn`的URL我让别人有空再测试下

`c*.yunpan.360.cn`我这边访问正常

嗯…大炮是一部分，还有一些是海外CDN的问题导致证书错误

**Comment by renyouguo** [comment]
in China: OK

sp20160919_205343

**Comment by gloomy-ghost** [comment]
@renyouguo Is there a range of `sdl*.yunpan.360.cn` subdomains? I cannot find any of these on Google.

所以之前你说Tor的时候是假定我不在天朝的么……感觉越来越迷糊了orz

**Comment by renyouguo** [comment]
@gloomy-ghost 这地址是那天看到某人分享的地址，不是自己获取的。
我也发现很多子域名其实是不会在google上找到的。这些域名存在range——反正我只会自己手动试出来，这个sdl*的地址我也没找到类似的。
用Tor其实与人是否在天朝毫无关系。我第一次碰到这个问题的时候，是自动测试无论如何无法通过，把各式各样的proxy都用了一遍，基本都很正常，只有上Tor，才会与自动测试结果相一致。
然后大概是我首创了默认禁用特定规则的理由：Only avaiable in China

**Comment by gloomy-ghost** [comment]
@renyouguo 为什么proxy都没问题…按说也是墙外啊…

刚开始以为你用Tor代指任何一种翻墙工具用来测试c*的海外可用性，后来又说是sdl*的514，然后我就以为你是说sdl*这个要翻回墙内了…还是好乱…

**Comment by renyouguo** [comment]
@gloomy-ghost 不懂，只能说只有Tor才能与本项目自动测试结果保持一致。我测了下，应该能通过。
sp20160919_212842

**Comment by gloomy-ghost** [comment]
@renyouguo 链接又挂了……我找别人测出来也是514，感觉是360的问题

**Comment by gloomy-ghost** [comment]
`sdl*.yunpan.360.cn` is quite unstable now, so I am not adding it in this PR.

@jeremyn Here is ready for merging.

**Comment by jeremyn** [comment]
I don't think having a mixed wildcard like `c*.yunpan.360.cn` is understood by the code. When I use your rule, your test URL http://c2.yunpan.360.cn isn't recognized as a target by the browser. Can you confirm?

Also, the original ruleset had a comment for `c33.yunpan.360.cn`, which I think should still be a target, but your new rule misses that.

Do you see any problem changing [these lines](https://github.com/gloomy-ghost/https-everywhere/blob/86359099a6f8ed56b9250b6f25d22cd9eb2810fb/src/chrome/content/rules/360.cn.xml#L84-L86):

```xml
	<target host="c*.yunpan.360.cn" />
		<rule from="^http://c([2-9]|[1-7]\d)\.yunpan\.360\.cn"
			to="https://c$1.yunpan.360.cn" />
```

to this?

```xml
	<target host="*.yunpan.360.cn" />
		<rule from="^http://c(\d+)\.yunpan\.360\.cn"
			to="https://c$1.yunpan.360.cn" />
```

**Comment by gloomy-ghost** [comment]
@jeremyn Sorry, I just saw the [build](https://travis-ci.org/EFForg/https-everywhere/jobs/160754232#L206) passed and did not open a virtual host to test it.

However, the build fails after changing it... Any ideas?

**Comment by jeremyn** [comment]
I'm not totally sure why this error is happening, but both `from` and `to` should either have or not have a trailing slash. The [usual pattern](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=rule) for complex rules seems to be a trailing slash in both, so try that.

**Comment by gloomy-ghost** [comment]
@jeremyn Thanks, it has passed.

**Comment by jeremyn** [comment]
I found a problem. When we use wildcards like `<target host="*.yunpan.360.cn" />`, then we can't use the general `<rule from="^http:" to="https:" />` or else everything matching the wildcard will be converted to HTTPS, even if it doesn't match the more specific rule. For example the ruleset as of a1233db56e8c6d44c323e102311753c000c6e1da catches and breaks http://huodong.yunpan.360.cn/ithink .

The solution is to replace the [general rule](https://github.com/gloomy-ghost/https-everywhere/blob/a1233db56e8c6d44c323e102311753c000c6e1da/src/chrome/content/rules/360.cn.xml#L102-L103) with a more specific rule listing the subdomains, like this:

```xml
	<rule from="^http://(captcha|hao|jiagu|msoftdl|openapi|s|yunpan)\.360\.cn/"
		to="https://$1.360.cn/" />
```

**Comment by gloomy-ghost** [comment]
@jeremyn Will it be ok if I use a exclusion rule for all `*.yunpan.360.cn` except `c*`?

Like this:
`<exclusion pattern="^http://(?!c\d+).+\.yunpan\.360\.cn" />`

Or if you think that is confusing to `have exclusion tags that contain negative lookahead operators`, then consider this one:
`<exclusion pattern="^http://\w+\.yunpan\.360\.cn" />`

**Comment by jeremyn** [comment]
I like the exclusion idea. The negative lookahead is fine. It's slightly more correct than `\D+`, for example maybe there are non `c*.yunpan.360.cn` URLs with digits in them.

What is the `.+` in `^http://(?!c\d+).+\.yunpan\.360\.cn` for? What's an example URL for it?

Also, usually exclusions for simple subdomains end in `/`, see [here](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=exclusion) for example. It's not a big deal in this case but in another example it might make the difference between `.co` and `.com`.

**Comment by gloomy-ghost** [comment]
`^http://(?!c\d+)\.yunpan\.360\.cn`  seems not matching `huodong.yunpan.360.cn`.

**Comment by jeremyn** [comment]
Okay, let's take a step back. The style guide says:

```
Some rulesets have exclusion tags that contain negative lookahead operators, which is very confusing.
```

So we're doing exactly the wrong thing here and I am finding it confusing. For example the ruleset with

```xml
<exclusion pattern="^http://(?!dev|c\d{1,2}).+\.yunpan\.360\.cn/" />
```

currently matches http://dev.yunpan.360.cn which I guess it shouldn't, and it matches http://c1x.yunpan.360.cn and I don't know if it should or shouldn't. Confusing.

Anyway, please delete the exclusion and do the approach I suggested in [this earlier comment](https://github.com/EFForg/https-everywhere/pull/6899#issuecomment-248645488), which matches the style guide.

**Comment by gloomy-ghost** [comment]
Well, it doesn't match either `dev` or `c1*` when I test it on Firefox. It just a simple math theorem that you get a positive when there are pairs of negative, so subdomains in the brackets are not being matched.

The style guide actually wants a target list of all subdomains which is not suitable here. We are violating it anyway because it also says `Avoid regexes with long strings of subdomains`. Compares with writing all subdomains again in general rule, the exclusion rule is shorter.

**Comment by jeremyn** [comment]
http://dev.yunpan.360.cn and http://c1x.yunpan.360.cn match for me in Firefox with the 7ee8b98eea39f346acc58d056a19c1bf32396c60 ruleset. I don't know how to explain our different results.

We have three options:

* About eighty new targets of the form `c\d+.yunpan.360.cn`, one new target for `dev.yunpan.360.cn`, generic `rule`, and no `exclusion`.
* Wildcard target `<target host="*.yunpan.360.cn" />`, no `exclusion`, and these `rule`s:
```xml
<rule from="^http://(c(\d{1,2})|dev)\.yunpan\.360\.cn/"
         to="https://$1.yunpan.360.cn/" />
<rule from="^http://(captcha|hao|jiagu|msoftdl|openapi|s|yunpan)\.360\.cn/"
         to="https://$1.360.cn/" />
```
* Wildcard target as above, generic `rule`, and something like this `exclusion`:
```xml
<exclusion pattern="^http://(?!dev|c\d{1,2}).+\.yunpan\.360\.cn/" />
```

I don't like the `exclusion` option and the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) specifically calls that out as bad. Neither of the first two options are great. I prefer more complicated rules over eighty new targets but I'll leave it up to you whether you want to do the first or second.

If you really want the `exclusion` option, then we can ask some of the other reviewers to take a look and get other opinions.

**Comment by gloomy-ghost** [comment]
Maybe I will open an issue to discuss it because there is a same problem when I try to update McAfee's ruleset -- I have to use complicated rules which include all targets if exclusions are not allowed, but both of solutions are noted as bad in style guide.

**Comment by jeremyn** [comment]
@gloomy-ghost So, how do you want to proceed on this pull request?

**Comment by gloomy-ghost** [comment]
I have updated it

**Comment by jeremyn** [comment]
Thanks. Pleaes also:

https://update.yunpan.360.cn doesn't 404 for me, so
- [ ] remove the comment
- [ ] update the `*.yunpan.360.cn` regex
- [ ] add `test` for it

Also:
- [ ] Remove `passive mixed content` comment
- [ ] Move `target` for `i.360.cn` with other `*.360.cn` targets
- [ ] Move `test` for https://dev.yunpan.360.cn under the appropriate `rule`

**Comment by gloomy-ghost** [comment]
See https://update.yunpan.360.cn/recommended_app_list.html

**Comment by jeremyn** [comment]
Thanks.

[This change](https://github.com/EFForg/https-everywhere/pull/6899/commits/d730741ac43e9eea8350fd2788fbdaf76ae3f6d5#diff-f8aafc419d97cfcfd3f90cac344af738R87) is bad, for example it now matches `cdev.yunpan.360.cn` but not `dev.yunpan.360.cn`.

**Comment by gloomy-ghost** [comment]
Oops, sorry.

**Comment by jeremyn** [comment]
I've added a new item to the checklist about using the full domain name in the top comment.

Also, although I understand that you want to make as many changes as you can to this ruleset while it's still under active review, please stop adding changes unrelated to what I've asked for. It makes it difficult to see what I've already reviewed, especially with a complex ruleset like this.

**Comment by jeremyn** [comment]
I've updated the checklist through the latest commit 174d39b49ef2a3b971bfb4885f025023de9f10b2.

**Comment by jeremyn** [comment]
I deleted an extra item from the checklist about https://update.yunpan.360.cn because we'd already discussed that domain.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
