### PR TITLE
add rule for Mux.de

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also include ^?
It seems that some locations got their own subdomains, but there are horrible mixed content issues.

**Comment by numismatika** [comment]
@J0WI  better this way or do you want additional changes?

**Comment by J0WI** [comment]
>  It seems that some locations got their own subdomains, but there are horrible mixed content issues.

Please document this behavior.

**Comment by numismatika** [comment]
@J0WI so far i couldn't find a subdomain with that issue. All quarters i can see are located in a subfolder of the main site. Do you have an example for me?

**Comment by J0WI** [comment]
- beatrixzurek.mux.de
- bidjanbek.mux.de
- reichenbachdelikatessen.mux.de

**Comment by J0WI** [comment]
retest

**Pull request merged**
