### PR TITLE
Added popre.net

### PR DESCRIPTION
**Pull request by PopRe**

### CODE REVIEW

**Comment by jeremyn** [comment]
@PopRe Are you still interested in working on this?

**Comment by PopRe** [comment]
Not really necessary now as all traffic is forwarded to https on the site

**Comment by jeremyn** [comment]
http://www.popre.net doesn't redirect to https for me.

**Comment by PopRe** [comment]
Whoops, it does now - just got to it this week for a few related sites

**Comment by jeremyn** [comment]
Of course you don't have to submit a ruleset, but FYI domains that redirect to HTTPS are still valid targets for HTTPS Everywhere (see [here](https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages)). You could also look into HSTS preloading your site (see [here](https://hstspreload.appspot.com/)).

**Comment by jeremyn** [comment]
Also, consider marking your cookies as "isSecure" or "HTTPS only" or equivalent. This is what our `securecookie` attribute does (see [here](https://www.eff.org/https-everywhere/rulesets#secure-cookies)).

Anyway, thanks for responding so quickly.

**Pull request closed without merging**
