### PR TITLE
[Pfizer] Fix #7781

### LINKED ISSUE #7781: Pfizer.com (partial) messes with font
http://www.pfizer.com/

`Pfizer.com (partial)` causes the font to look ugly.

### PR DESCRIPTION
**Pull request by synthtech**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
www.pfizer.com has migrated to https, @synthtech are you still interested in updating this PR?

**Comment by synthtech** [comment]
@gloomy-ghost Sure, I'll check it out soon.

**Comment by synthtech** [comment]
Used a wildcard since there were around 91 unique subdomains found with sublist3r.

**Comment by gloomy-ghost** [comment]
Thanks for updating this PR. There are many subdomains not available in https yet, so wildcards should be avoided as much as possible since we don't want to break things while extending our ruleset coverage. There is a list of subdomains that I roughly scanned through and seemed to be working, you might want to use it as a reference.

<details><summary>Click to expand</summary>

```
www.pfizer.com
ace.pfizer.com
acoach.pfizer.com
action.pfizer.com
amer-anyconnect.pfizer.com
anyconnect.pfizer.com
apac-anyconnect.pfizer.com
aribaprime.pfizer.com
bjd-anyconnect.pfizer.com
bjd-asa-vpn-01-ext.pfizer.com
bjd-asa-vpn-02-ext.pfizer.com
bjd-asa-vpn-vip01.pfizer.com
cpid.pfizer.com
digitalondemand.pfizer.com
dm-federate.pfizer.com
dm-sso.pfizer.com
ebusiness-sso.pfizer.com
ebusiness-suppliers.pfizer.com
edc-anyconnect.pfizer.com
edc-asa-vpn-01-ext.pfizer.com
edc-asa-vpn-02-ext.pfizer.com
edc-asa-vpn-03-ext.pfizer.com
edc-asa-vpn-vip01.pfizer.com
edetail.pfizer.com
emea-anyconnect.pfizer.com
emtech.pfizer.com
esamplesweb.pfizer.com
login.grv.eu.pfizer.com
globalhealthfellows.pfizer.com
ich-anyconnect.pfizer.com
ich-asa-vpn-01-ext.pfizer.com
ich-asa-vpn-02-ext.pfizer.com
ich-asa-vpn-vip01.pfizer.com
id.pfizer.com
impala.pfizer.com
impalastg.pfizer.com
incentive-europe.pfizer.com
innovationspace.pfizer.com
investors.pfizer.com
lyncdiscover.pfizer.com
ndh-anyconnect.pfizer.com
ndh-asa-vpn-01-ext.pfizer.com
ndh-asa-vpn-02-ext.pfizer.com
ndh-asa-vpn-03.pfizer.com
ndh-asa-vpn-03-ext.pfizer.com
ndh-asa-vpn-vip01.pfizer.com
on.pfizer.com
openid.pfizer.com
pfizer-online-temp.pfizer.com
rdctst.pfizer.com
resources.pfizer.com
sdc-anyconnect.pfizer.com
sdc-asa-vpn-01-ext.pfizer.com
sdc-asa-vpn-02-ext.pfizer.com
sdc-asa-vpn-vip01.pfizer.com
som-anyconnect.pfizer.com
som-asa-vpn-01-ext.pfizer.com
som-asa-vpn-02-ext.pfizer.com
som-asa-vpn-vip01.pfizer.com
spire.pfizer.com
spire-amend2.pfizer.com
www.spire-amend2.pfizer.com
tc.pfizer.com
login.grv.us.pfizer.com
wry-anyconnect.pfizer.com
wry-asa-vpn-01-ext.pfizer.com
wry-asa-vpn-02-ext.pfizer.com
wry-asa-vpn-vip01.pfizer.com
```
</details>

**Pull request closed without merging**
