### PR TITLE
Add ruleset for Hive.co.uk.xml

### PR DESCRIPTION
**Pull request by sampablokuper**

### CODE REVIEW

**Comment by sampablokuper** [comment]
Failing with:

```
ERROR src/chrome/content/rules/Hive.co.uk.xml: Fetch error: http://www.hive.co.uk/books => https://www.hive.co.uk/books: Too many redirects while fetching 'https://www.hive.co.uk/books'

ERROR src/chrome/content/rules/Hive.co.uk.xml: Fetch error: http://hive.co.uk/ => https://hive.co.uk/: Too many redirects while fetching 'https://hive.co.uk/'

ERROR src/chrome/content/rules/Hive.co.uk.xml: Fetch error: http://www.hive.co.uk/ => https://www.hive.co.uk/: Too many redirects while fetching 'https://www.hive.co.uk/'
```

Maddeningly, HTTPS support on hive.co.uk seems to be intermittent. Yesterday, these rules seemed to be OK (e.g. https://www.hive.co.uk/books did not redirect to https://www.hive.co.uk/books ). Yet today, now that I have added, committed and pushed them to GitHub and made a PR, the website's HTTPS support seems to have vanished.

Perhaps Hive's webmasters are making changes to the server, and I just happened to get lucky yesterday? I've emailed Hive and asked them to properly support HTTPS across their website.

**Comment by sampablokuper** [comment]
@sampablokuper [wrote](https://github.com/EFForg/https-everywhere/pull/10875#issuecomment-313094950):
> I've emailed Hive and asked them to properly support HTTPS across their website.

Hooray, Hive has now implemented site-wide HTTPS! :tada:

**Comment by sampablokuper** [comment]
Closing this PR temporarily, in order to be able to re-open it to [trigger a Travis CI rebuild](https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915).

**Comment by jeremyn** [comment]
@sampablokuper Are you still interested in working on this pull request?

**Comment by sampablokuper** [comment]
@jeremyn , yes in principle, but I'm afraid I can't spare time at the moment. Anyone interested should feel free to work on it.

**Comment by sampablokuper** [comment]
@jeremyn wrote:
> Are you still interested in working on this pull request?

Out of curiousity, which additional work do you think it needs? LGTM.

**Comment by jeremyn** [comment]
- [ ] Add `target` for https://blog.hive.co.uk
- [ ] Remove entire top comment
- [ ] Remove both `test`s

**Comment by sampablokuper** [comment]
Thanks for the helpful, point-by-point answer - much appreciated :)

@jeremyn wrote:
> * Add target for https://blog.hive.co.uk

Good catch. I wasn't aware of that subdomain.

> * Remove entire top comment

OK, I hadn't expected that. Seems fair, though.

Maybe [CONTRIBUTING.md](https://github.com/EFForg/https-everywhere/blob/d6967f2dfe659f35151216429e8593f3ef35396c/CONTRIBUTING.md) should explicitly state this recommendation/requirement, for the benefit of contributors like me to whom it is non-obvious (and reviewers like you who have to decide whether or not to accept our PRs)?

> * Remove both tests

This is definitely a surprise. Did the project's policy about tests change at some point, from favouring them to rejecting them?

Thanks again :)

**Comment by jeremyn** [comment]
Your top comment doesn't list any subdomains or have any other notes, so it doesn't need to be there. I don't think we need to document that we should omit comments that have no information. (I assume in this case you used the ruleset generator. Possibly some documentation could be added to that.)

`test` information is documented at [`CONTRIBUTING.md#left-wildcards`](https://github.com/EFForg/https-everywhere/blob/d6967f2dfe659f35151216429e8593f3ef35396c/CONTRIBUTING.md#left-wildcards). Each `target` has an implicit test added for the root URL, in this case http://www.hive.co.uk . There is no need to add extra `test`s unless there is some special situation with the `target`, which doesn't seem to be the case here. There has not been any recent change in this standard.

Are you planning on making the changes I requested in the near future? If not, I'm going to unassign myself from this PR, and there may be different requirements by the time someone looks at this again.

**Comment by sampablokuper** [comment]
@jeremyn wrote:
> Your top comment doesn't list any subdomains or have any other notes, so it doesn't need to be there. I don't think we need to document that we should omit comments that have no information. (I assume in this case you used the ruleset generator. Possibly some documentation could be added to that.)

I did use the ruleset generator. What you say above raises the question: why have the generator add material to the file, that the user is then expected by default to delete, without notifying the user of this expectation? At the very least, the boilerplate comment inserted by the ruleset generator should make this expectation clear to the user.

> `test` information is documented at [`CONTRIBUTING.md#left-wildcards`](https://github.com/EFForg/https-everywhere/blob/d6967f2dfe659f35151216429e8593f3ef35396c/CONTRIBUTING.md#left-wildcards).

Hm. That's not an obvious section under which a reader would seek advice about `<test/>` elements.

> Each `target` has an implicit test added for the root URL, in this case http://www.hive.co.uk . There is no need to add extra `test`s unless there is some special situation with the `target`, which doesn't seem to be the case here.

The section mentions a "reduced need", but not "no need unless there is some special situation".

> There has not been any recent change in this standard.

IIRC, not all that many months or years ago, the CI failed my rulesets unless they contained at least one test per rule. So, my impression is that this _has_ changed. Whether or not the change was recent is subjective ;)

> Are you planning on making the changes I requested in the near future?

Not right now. I'm grateful for your answers, even though some of their content surprised me. I will sleep on them. Thank you for helping me to better understand how my ruleset PRs look to a reviewer.

**Comment by jeremyn** [comment]
You're welcome to make a PR to improve the generator, or `CONTRIBUTING.md`.

`test`s are required by the CI process in certain situations, such as if you use wildcards or `exclusion`s. We might also ask for `test`s to be added during the review process in other situations, that are not caught by the CI process, if there is some unusual thing happening. `test`s are not needed in uncomplicated cases. Some maintainers might be more permissive than others in allowing extraneous `test`s.

Also please note that it takes some effort from a maintainer to provide detailed feedback on a PR. It is not really appropriate to ask for this feedback unless you are willing to act on it.

**Comment by sampablokuper** [comment]
> It is not really appropriate to ask for this feedback unless you are willing to act on it.

I was willing, but not yet ready, because - by a similar token - it is not really appropriate to act unless one understands and agrees with the reason(s) for the action :)

Your concerns about this ruleset have now all been resolved.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
