### PR TITLE
add more hosts to swissgov.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
I think the fetch errors here are false positives.

**Comment by jeremyn** [comment]
I get `Secure Connection Failed` in Firefox with https://parlament.ch . https://www.elcom.admin.ch and https://www.parlament.ch work though. I've restarted the tests.

**Comment by J0WI** [comment]
I commented the host out for now, so test are passing.

**Comment by J0WI** [comment]
ping @jeremyn for a review

**Comment by jeremyn** [comment]
Checklist for [`Swiss_Federal_Institute_of_Intellectual_Property.xml`](https://github.com/J0WI/https-everywhere/blob/d17915ad104a4276169cab9c6f6aa8aa4601e450/src/chrome/content/rules/Swiss_Federal_Institute_of_Intellectual_Property.xml#L3):

Note as `Refused`:
- [ ] https://client.ip-search.ch
- [ ] https://swissreg.ch
  
Add `target`:
- [ ] https://e-trademark.ige.ch
- [ ] https://gz.ige.ch
- [ ] https://ip-search.ch
  
Also:
- [ ] Fix misspelling: `govnerment`
- [ ] Fix misspelling: `ip-seacrh.ch`
- [ ] Add a note about how `ige.ch`, `swissreg.ch`, and `ip-search.ch` are related to each other, if that's easy to do.

**Comment by J0WI** [comment]
`^ip-search.ch` does not exist.
I would like to keep the comments for `first` and `webmail` for now.

I addressed all other points.

**Comment by jeremyn** [comment]
`Swiss_Federal_Institute_of_Intellectual_Property.xml` is done.

`Swiss_Financial_Market_Supervisory_Authority.xml` is done except for a minor spelling problem that I've added to the checklist.

**Comment by jeremyn** [comment]
I've added `dot.swiss.xml` to the checklist.

**Comment by jeremyn** [comment]
`swissgov.xml` really needs to be broken up and reformatted before I look at it more closely, sorry. I guess it's obvious what most of the problems are but I can elaborate if you need me to.

I recommend splitting the three approved rulesets into a new pull request, and then make new pull requests as you split stuff off of `swissgov.xml`. Maybe one PR for `admin.ch` and one for each canton, at least.

**Comment by J0WI** [comment]
That would have been nice to know before you started to review...

**Comment by J0WI** [comment]
It's not easy to just split this now in different PRs, because of the all the references.

Can we just merge the updates on `*.admin.ch` (and code stye) in `swissgov.xml` and then I will fill follow-up PRs for the other hosts and to split some hosts into new files?

**Comment by jeremyn** [comment]
I think it's okay to have unreturned references from the other files to `swissgov.xml` for now, if we merge those separately.

I'm not sure what to suggest for the `swissgov.xml` changes. It is very difficult to read. For example the top comment uses `no certificate`, `self-signed`, `Mismatch`, and the `¬` symbol to all mean `Invalid certificate`. I don't want to figure out what I'm testing with forty rows like:

```
	admin.ch:
		- rpvz.nb ¬
		- www.afd ²	
```

`www.publica.ch` is between `www.webftp.admin.ch` and `www.wbf.admin.ch` for some reason, and anyway `www.wbf` should come before `www.webftp`. There are triple indented `target`s. Etc, this is not a complete list of problems.

**Comment by J0WI** [comment]
@jeremyn I rebased this branch and reorganized the comments.

Please review with the following notes in mind:
- This adds some hosts to *.admin.ch
  - This is the only functional change in this PR
  - Maybe you can use some filters in `git diff` for a clearer view
- This adds some additional comments and code style changes
- canton hosts are not changed and may be spitted into multiple files and rebased in further PRs
  - However, some minor changes where necessary to fix tests

**Comment by J0WI** [comment]
@jeremyn I would really like to continue here. Can you manage to spend some attention on this again?

**Comment by jeremyn** [comment]
I've updated the checklist through the https://github.com/EFForg/https-everywhere/pull/6771/commits/4ddaa991c1895c2e10d4de3a322e9499a87a8013, and only through the top comment.

Please get rid of the nested `target`s. I don't know why you did it that way, or what it "means" to have a hierarchy of for example `www.wbf.admin.ch` > `www.blw.admin.ch`, or `www.edi.admin.ch` > `www.bsv.admin.ch` > `www.regress.admin.ch`. It makes the diff harder to read.

**Comment by J0WI** [comment]
Thanks for the feedback.

> `www.afd.admin.ch`, incomplete certificate chain, different http/https

Well, this host has both issues, but the chain is just a minor thing.

> `www.bit.admin.ch`, works correctly, redirect

Only `http://www.bit.admin.ch/$` works, all other sites redirect to http. So I think it's not worth to add a rule.

> `<!-- hosts sorted by department -->`

I think it's much easier to maintain this way. You can find each host in the breadcrumb in the same structure.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/6771/commits/b6f52f7731e32e82d6200f89b1580bd4c10e7aef and have otherwise finished reviewing.

**Comment by J0WI** [comment]
I'm fine with redirecting `rab-asr.ch`.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/6771/commits/d82b29149c4f37b3e056077f9a7488a32bc383e8.

In your last comment, just to confirm, do you mean that you are okay with the way you have it now, where we rewrite http://rab-asr.ch to https://rab-asr.ch even though the site itself redirects http://rab-asr.ch to https://www.rab-asr.ch ?

**Comment by J0WI** [comment]
Yes, both have exactly the same content. Let's keep it simple.

**Comment by jeremyn** [comment]
Merged.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
