### PR TITLE
Create Ibercaja.es.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
I got some errors with curl when testing locally, let me rerun the tests here.

**Comment by J0WI** [comment]
Yep, there were some changes on these hosts. This needs to be rebased or updated.

**Comment by davidabian** [comment]
@J0WI: I can access to <https://portalempleado.ibercaja.es>. Could a firewall be blocking the test connections?

**Comment by J0WI** [comment]
I think so: http://downforeveryoneorjustme.com/portalempleado.ibercaja.es

**Comment by davidabian** [comment]
So should I delete the rule for this subdomain (although it's an important one)?

**Comment by J0WI** [comment]
The very best solution would be a separate file for this host that is whitelisted in the tests.
I think utils/ruleset-coverage-whitelist.txt would be the right place then.

**Comment by jeremyn** [comment]
@davidabian Are you still interested in working on this?

**Comment by davidabian** [comment]
I would like to contribute more, but I fear that my time is really limited right now. I'm sorry.

**Comment by jeremyn** [comment]
Thanks @davidabian . I'm going to close this for now, but please feel free to reopen it in the future with a comment when you are ready to work on it some more.

**Pull request closed without merging**
