### PR TITLE
Add openbudget and news subdomains to City_of_Seattle.gov

### PR DESCRIPTION
**Pull request by andschwa**
Two more sub domains for `seattle.gov`.

### CODE REVIEW

**Comment by cschanaj** [comment]
You can avoid adding the test URLs by listing the `target` explicitly instead of using a wildcard. Besides, please also have a look on the Travis error.

**Comment by jeremyn** [comment]
@andschwa Are you still interested in working on this pull request?

**Comment by andschwa** [comment]
Taking a look, the original ruleset looks pretty old. That Travis CI failure is because the `wald1` subdomain is down. Maybe I'll just rewrite some of this...

**Comment by andschwa** [comment]
I'm just going to close this, there are so many weird things about their website :( Like, `https://seattle.gov` just 404s.

**Comment by jeremyn** [comment]
@andschwa Thanks for the update. If you like, you're welcome to rewrite the existing ruleset to cover at least the most important subdomains. It doesn't need to provide exhaustive coverage, especially since the ruleset is `(partial)` anyway. In particular it would be nice to cover https://www.seattle.gov . But it is up to you.

**Comment by jeremyn** [comment]
Actually on closer inspection it looks like `www` is already covered by the wildcard target. We generally don't like wildcards so it would be nice for this to get rewritten, but in any case my specific complaint about `www` is not an issue, just to clarify.

**Pull request closed without merging**
