### PR TITLE
Create K-tb.com.xml

### PR DESCRIPTION
**Pull request by Giltyhub**

### CODE REVIEW

**Comment by Giltyhub** [comment]
@J0WI but the CSP policy automatically redirects those resources to HTTPS

```
Content Security Policy: Upgrading insecure request ‘http://k-tb.com/css/bootstrap.css’ to use ‘https’  (unknown)
Content Security Policy: Upgrading insecure request ‘http://k-tb.com/css/style.css’ to use ‘https’  (unknown)
Content Security Policy: Upgrading insecure request ‘http://k-tb.com/css/jquery-ui.min.css’ to use ‘https’  (unknown)
Content Security Policy: Upgrading insecure request ‘http://k-tb.com/css/cover.css’ to use ‘https’  (unknown)
Content Security Policy: Upgrading insecure request ‘http://k-tb.com/imgs/logo1.png’ to use ‘https’  (unknown)
```

So I think it's safe to have it enabled by default, no?

**Comment by J0WI** [comment]
I don't get any CSP header from this host.

**Comment by Giltyhub** [comment]
@J0WI add locally this ruleset to https everywhere then fetch this website with https everywhere enabled and check your browser console (i tested it with firefox)

**Comment by J0WI** [comment]
I cannot reproduce using the same setup.

**Comment by Giltyhub** [comment]
seems to only happen with "Block all unencrypted requests", anyway i set platform="mixedcontent" and sorry for the confusion

**Pull request merged**
