### PR TITLE
Update Baidu.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Combine the two `tieba` exclusions [here](https://github.com/renyouguo/https-everywhere/blob/75831f14d508acf6841571876ac7033583392d2b/src/chrome/content/rules/Baidu.xml#L271) and [here](https://github.com/renyouguo/https-everywhere/blob/75831f14d508acf6841571876ac7033583392d2b/src/chrome/content/rules/Baidu.xml#L276). Right now each of them is causing the other to be excluded. You probably want this:

```xml
<exclusion pattern="^http://tieba\.baidu\.com/(?!mo/|mo_wowap_pb/)" />
```
- [ ] Related to the previous item, you can reduce the tests if you want.
- [ ] Is [this comment](https://github.com/renyouguo/https-everywhere/blob/75831f14d508acf6841571876ac7033583392d2b/src/chrome/content/rules/Baidu.xml#L270) about mixed content blocking still needed?

**Comment by renyouguo** [comment]
@jeremyn Sorry, the comment means tieba.baidu.com is PC mode, /mo/ is mobile mode. I have change them to avoid misunderstandings.

**Comment by renyouguo** [comment]
@jeremyn https://travis-ci.org/EFForg/https-everywhere/jobs/158634782#L292
I don't know how to find the third exclusion.

**Comment by jeremyn** [comment]
Thanks for making the comment more clear.

You need three tests for the exclusion, which means you need three tests with `tieba` and without `mo/` or `mo_wowap_pb/`. Right now the two tests you have are:

1. the automatic test for the `tieba` `target`, and
2. `<test url="http://tieba.baidu.com/" />`

You can replace all the `tieba` tests with these:

```xml
        <test url="http://tieba.baidu.com/kb/" />
        <test url="http://tieba.baidu.com/zjstv/" />
        <test url="http://tieba.baidu.com/mo/" />
        <test url="http://tieba.baidu.com/mo_wowap_pb/" />
```

The three exclusion tests are now the automatic test, the `kb` test, and the `zjstv` test. The `mo` and `mo_wowap_pb` tests are extra, not required, and just make sure that those correctly redirect to HTTPS.

**Comment by renyouguo** [comment]
@jeremyn Thank you very much.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
