### PR TITLE
Ruleset for www.nic.cl

### PR DESCRIPTION
**Pull request by huguei**
We're issuing a 302 redirect from plain http since a couple of weeks.

### CODE REVIEW

**Comment by huguei** [comment]
Thanks J0WI.
But our rules are just for nic.cl, www.nic.cl and clientes.nic.cl websites. The other are hosted in another infrastructure and aren't subject to the same policies.
I wonder if my securecookie is the problem? Is it too wide? I can change it to

`<securecookie` host="^(www\.|clientes\.)?nic\.cl$" name=".+" /> 

if it's more clear.

Thanks.

**Comment by J0WI** [comment]
@huguei we try to keep our rulesets complete and the comments are helping us to maintain the rules.
If there is a strong reason to not add working hosts like `blog.nic.cl`, you should also document this in comments, otherwise somebody might add it accidentally.

As long as there are no exclusions, the securecookie rule should be fine.

**Comment by huguei** [comment]
Updated pull with comments and new cookie rule, as requested. Thanks.

**Comment by J0WI** [comment]
Thanks for documenting this!

**Pull request merged**
