### PR TITLE
[New ruleset] mingpao.com.xml

### PR DESCRIPTION
**Pull request by Riotism**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Riotism Are you still interested in working on this pull request?

**Comment by Riotism** [comment]
Yes. Is there anything else I need to fix?

**Comment by jeremyn** [comment]
Delete entirely:
- [ ] https://mail.mingpao.com (I get a time out with HTTPS and refused or time out with plain HTTP)
- [ ] https://oldjump.mingpao.com (I get an SSL error with HTTPS and a sort of soft timeout in Firefox/`ERR_EMPTY_RESPONSE` in Chrome with plain HTTP)

Mark as `Different content in HTTPS`:
- [ ] https://happypama2.mingpao.com (plain HTTP redirects to https://happypama.mingpao.com without the `2`, and that looks like a slightly different site)

Mark as `Invalid certs`:
- [ ] https://www.life.mingpao.com and remove the `target` and `rule`. Regarding your fix with the special `rule`, none of the `www.life.mingpao.com` URLs I tested seem to work if I remove the `www`, so this isn't a good enough fix.

Mark as `Mixed content`:
- [ ] https://video3.mingpao.com and remove the `target` and `test`

Mark as `Refused`:
- [ ] https://mpdeluxe.mingpao.com

Mark as `SSL error`:
- [ ] https://premium.mingpao.com and remove from `Invalid certs`
- [ ] https://tssl.mingpao.com and remove from `Invalid certs`
- [ ] https://video.mingpao.com and remove from `Invalid certs`

Mark as `Time out`:
- [ ] https://code.mingpao.com and remove from `Different content for HTTPS`
- [ ] https://ebook.mingpao.com
- [ ] https://indepth.mingpao.com
- [ ] https://link.mingpao.com
- [ ] https://reading.mingpao.com
- [ ] https://studentreporter.mingpao.com

Add `(incomplete certificate chain)` after the domain in the comment:
- [ ] https://books.mingpao.com

Add `target`:
- [ ] https://member.mingpao.com and remove from `SSL error`

Add `test` or mark as `No working URL known`:
- [ ] https://fs1.mingpao.com
- [ ] https://fs2.mingpao.com
- [ ] https://marketing2.mingpao.com
- [ ] https://ol2.mingpao.com

https://fs.mingpao.com could also be in this category, but I found some URLs for it through searching.
 They're all PDFs though, and I don't understand the language they're in, so I don't feel comfortable
including them as `test`s.

Also:
- [ ] Change the `ruleset` `name` to `MingPao.com`
- [ ] Change the filename to `MingPao.com.xml`

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9324/commits/2cbfbaed6f992674250061387963e4bbf55d1d20. (`mail.mingpao.com` is still listed under `Different content in HTTPS`.)

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
