### PR TITLE
wien.gv.at

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by julianladisch** [comment]
Thank you, please also add wien.at, www.wien.at, gemeinderecht.wien.at, www.gemeinderecht.wien.at, www.fluechtlinge.wien.gv.at, www.fluechtlinge.wien.at, fluechtlinge.wien.at, www.open.wien.gv.at, www.open.wien.at, open.wien.at, www.smartcity.wien.gv.at, www.smartcity.wien.at, smartcity.wien.at.

**Comment by galeksandrp** [comment]
Added.

**Comment by J0WI** [comment]
Looks good so far, let me trigger Travis again.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
