### PR TITLE
Add YourOnlineChoices.eu.xml

### LINKED ISSUE #18771: Add youronlinechoices.eu
Type: new ruleset
Domain: youronlinechoices.eu

### PR DESCRIPTION
**Pull request by pipboy96**
Closes #18771.

### CODE REVIEW

**Comment by J0WI** [comment]
The site does not really work for me over HTTPS and in some cases I get redirected to the `.com` variant:
- `https://www.youronlinechoices.eu/nl/` conatins MCB
- `https://www.youronlinechoices.com/nl/interest-based-advertising` conatins MCB
- `https://www.youronlinechoices.com/nl/` redirects back to HTTP

**Comment by pipboy96** [comment]
@J0WI Can confirm, website seems to be too broken to attempt to make a ruleset.

**Comment by J0WI** [comment]
You could secure static resources.

**Comment by pipboy96** [comment]
@J0WI Ok, I will try.

**Pull request closed without merging**
