### PR TITLE
Rewrite subdomains for strugee.net

### PR DESCRIPTION
**Pull request by strugee**
As a side note, it would be nice if the test framework let me disable tests if I know the website maintainer (me) will check this.

### CODE REVIEW

**Comment by strugee** [comment]
Also, the Travis build hasn't completed yet, but it's going to fail for unrelated reasons.

**Comment by fuglede** [comment]
There's a typo in the comment and some inconsistent usage of <code>'</code> vs. <code>"</code>. Otherwise looks good to me; merging.

**Comment by strugee** [comment]
@fuglede I'll prepare another PR; nice catch!

Looks like `"` is preferred, is that correct?

**Comment by fuglede** [comment]
Yep, <code>"</code> is more popular.

**Comment by strugee** [comment]
Great. I'll send a patch to the style guide as well.

**Pull request merged**
