### PR TITLE
Create LearnShell.org.xml

### PR DESCRIPTION
**Pull request by opsteroids**

### CODE REVIEW

**Comment by J0WI** [comment]
Would you also like to add all other learn* hosts from this project?

**Comment by 6u621jpq6ybdw** [comment]
@J0WI Ok, and how do I name the ruleset? Or you mean I create different rulesets for each?

**Comment by 6u621jpq6ybdw** [comment]
@J0WI Added the second approach.

**Comment by J0WI** [comment]
Please choose one rule with a complete reference to other rulesets and link just to this file. Otherwise we have to update all the rules if we need to change something.

**Comment by 6u621jpq6ybdw** [comment]
@J0WI Added.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
