### PR TITLE
Create Wikia-partial.xml

### PR DESCRIPTION
**Pull request by IDKwhattoputhere**
It's a CDN for Wikia. I found these:

```
images2.wikia.nocookie.net
images3.wikia.nocookie.net
images4.wikia.nocookie.net
img.wikia.nocookie.net
img1.wikia.nocookie.net
img2.wikia.nocookie.net
img3.wikia.nocookie.net
img4.wikia.nocookie.net
slot1.images.wikia.nocookie.net
slot1.images1.wikia.nocookie.net
slot1.images2.wikia.nocookie.net
slot1.images3.wikia.nocookie.net
slot1.images4.wikia.nocookie.net
static.wikia.nocookie.net
static3.wikia.nocookie.net
vignette1.wikia.nocookie.net
vignette2.wikia.nocookie.net
vignette3.wikia.nocookie.net
vignette4.wikia.nocookie.net
```

To test:
`http://logos.wikia.com/wiki/Movie_Maker`
`http://de.leagueoflegends.wikia.com/wiki/League_of_Legends_Wiki`
`https://en.wikipedia.org/w/index.php?title=3D_Movie_Maker&oldid=690285174#Actors`

### CODE REVIEW

**Comment by IDKwhattoputhere** [comment]
I'm testing in Firefox right now and it only seems to work if I also activate the broken Wikia rule. :confused:

**Comment by J0WI** [comment]
This requires some test urls.

**Comment by IDKwhattoputhere** [comment]
Do you mean like this?
`<test url="http://leagueoflegends.wikia.com/wiki/League_of_Legends_Wiki" />`
And how many?

**Comment by J0WI** [comment]
Yes. For Wikia.xml it doesn't matter, since it's broken/off anyway.
But please add all urls you listed above as test urls.

**Comment by jeremyn** [comment]
@IDKwhattoputhere Are you still interested in working on this?

**Comment by IDKwhattoputhere** [comment]
I added the test URLs. Not sure why it's not working.

**Comment by jeremyn** [comment]
According to https://travis-ci.org/EFForg/https-everywhere/jobs/148011061#L1504 , it's erroring because of a certificate mismatch with https://de.leagueoflegends.wikia.com/wiki/League_of_Legends_Wiki , which I can confirm in the browser.

**Comment by IDKwhattoputhere** [comment]
They must have changed something that it doesn't work anymore. I wonder why I put that URL there anyways. It doesn't match the target host. Also a bunch of other hosts don't seem to work anymore (like `slot1.images3.wikia.nocookie.net`). I tried to make some changes which hopefully work.

**Comment by jeremyn** [comment]
I don't think the ruleset validator likes partial wildcards such as `images*.wikia.nocookie.net`. Wildcards are discouraged anyway according to the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md). Please rewrite the ruleset with positive `target`s. I get the following from Sublist3r ([more info](https://github.com/EFForg/https-everywhere/issues/7277)) running against `nocookie.net`. The list needs to be reviewed but it's not too many `target`s.

```
www.nocookie.net
a.nocookie.net
holdwiki.nocookie.net
mercury.nocookie.net
millionwiki.nocookie.net
mobile-apps-fandom-feed.nocookie.net
wikia.nocookie.net
ads.wikia.nocookie.net
api.wikia.nocookie.net
ignette3.wikia.nocookie.net
ignette4.wikia.nocookie.net
images.wikia.nocookie.net
slot1.images.wikia.nocookie.net
slot2.images.wikia.nocookie.net
images0.wikia.nocookie.net
images1.wikia.nocookie.net
slot1.images1.wikia.nocookie.net
images2.wikia.nocookie.net
slot1.images2.wikia.nocookie.net
images3.wikia.nocookie.net
slot1.images3.wikia.nocookie.net
images4.wikia.nocookie.net
slot1.images4.wikia.nocookie.net
img.wikia.nocookie.net
img1.wikia.nocookie.net
www.img1.wikia.nocookie.net
img2.wikia.nocookie.net
www.img2.wikia.nocookie.net
img3.wikia.nocookie.net
www.img3.wikia.nocookie.net
img4.wikia.nocookie.net
imgages.wikia.nocookie.net
mg2.wikia.nocookie.net
mg3.wikia.nocookie.net
static.wikia.nocookie.net
static1.wikia.nocookie.net
static2.wikia.nocookie.net
static3.wikia.nocookie.net
static4.wikia.nocookie.net
statics.wikia.nocookie.net
vignette.wikia.nocookie.net
vignette1.wikia.nocookie.net
vignette1fsdfdsfsdfsdfsdfsdfsd.wikia.nocookie.net
vignette2.wikia.nocookie.net
vignette3.wikia.nocookie.net
www.vignette3.wikia.nocookie.net
vignette4.wikia.nocookie.net
vignette99.wikia.nocookie.net
vvvignette3.wikia.nocookie.net
img1.wkia.nocookie.net
```

**Comment by IDKwhattoputhere** [comment]
To me it looks like `Wikia.xml` (the one in the extension) works again. Can you confirm this? If yes then I should revert the rule removal I did and maybe activate it by default.

**Comment by jeremyn** [comment]
Just looking at `Wikia-partial.xml`, most of the URLs have some invalid response (`404` etc) for the automatic test at the root subdomain. For each `target` where the root subdomain is invalid, we'd like to have a `test` URL for that `target` (see the discussion in https://github.com/EFForg/https-everywhere/issues/7662). Can you add those `test`s please? Also my own preference for `test`s is to put them directly under the `target` and indented, like this:

```xml
	<target host="images3.wikia.nocookie.net" />
		<test url="http://images3.wikia.nocookie.net/__cb20080316165340/terminator/images/2/24/Terminator.gif" />
```

Also, we prefer tab indents instead of spaces, following the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md).

For `Wikia.xml`, I'm not sure what you mean by works, but we really want to avoid wildcard `target`s like `	<target host="*.wikia.com" />`. We need to do something about that `target` before re-enabling the rule by default.

**Comment by jeremyn** [comment]
@IDKwhattoputhere I'm having trouble finding working test URLs for these domains. I'm not really sure what to do. Do you have any ideas?

**Comment by IDKwhattoputhere** [comment]
Sorry, I don't know either. The way I did it was simply visit Wikia pages until I had an example for every subdomain.

**Comment by jeremyn** [comment]
I've sent an email to community@wikia.com hoping to talk to someone that can provide us with test URLs or at least more information about the nocookie.net subdomains.

**Comment by jeremyn** [comment]
The person I emailed with at Wikia has asked us to exclude all `nocookie.net` domains.

@IDKwhattoputhere Please

- [ ] Remove `Wikia-partial.xml` entirely
- [ ] Add a note to the top comment of `Wikia.xml` saying something like `At site administrator's request, please do not rewrite nocookie.net subdomains to HTTPS. See https://github.com/EFForg/https-everywhere/pull/4888 for more information.`
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by IDKwhattoputhere** [comment]
> Is that all right with you for this and any other pull requests you submit to us?

Other projects I contributed to seem to do the same so sure, do that.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
