### PR TITLE
delovoe.tv

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also check:
ohtinskoe.delovoe.tv
rostehnologii.delovoe.tv
vgk.delovoe.tv
l1.delovoe.tv
petmol.delovoe.tv

**Comment by galeksandrp** [comment]
Add.

**Comment by galeksandrp** [comment]
Added.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
