### PR TITLE
[WineHQ] Update rule

### PR DESCRIPTION
**Pull request by funkydude**
Update WineHQ rule to add "dl" and (now working) "wiki" subdomains.

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for the additions. Could you also add forums.winehq.org?

**Comment by funkydude** [comment]
@J0WI that entry already exists (forum not forums)

**Comment by J0WI** [comment]
Yes, but the subdomain forums does also exist.

**Comment by funkydude** [comment]
@J0WI As far as I can see any attempt to access `forums` is redirected to `forum`. What is the benefit of adding `forums`?

**Comment by J0WI** [comment]
Every unsecured access to forums.winehq.org could be MITM attacked. That's the same reason why we add forum.winehq.org and all other domains, that doesn't support preloaded HSTS.

**Comment by funkydude** [comment]
@J0WI I see, added. How did you come across the forums subdomain anyway?

**Comment by J0WI** [comment]
Thanks!

> How did you come across the forums subdomain anyway?

Just found it on Google, see https://github.com/EFForg/https-everywhere/pull/3517#issuecomment-165904237

**Pull request merged**
