### PR TITLE
 Add Travis test for obsolete ruleset references 

### PR DESCRIPTION
**Pull request by cschanaj**
Failing Travis is expected, blocked by #13657. This will help to keep the ruleset references up-to-date when we have some bulk ruleset updates, e.g. when running `hsts-prune` etc. The effort required by contributors should be minimal in each PR as they are only responsible for ruleset they have changed.

ping @Hainish @cowlicks @J0WI @jeremyn for opinions and reviews. Thanks!!

EDIT: ~It seem that when the script is ran in debug mode, the output doesn't fit Travis console....~

Where to `chmod +x` ???

### CODE REVIEW

**Comment by jeremyn** [comment]
My comment at https://github.com/EFForg/https-everywhere/pull/13657#issuecomment-346944585 applies here too.

**Comment by Hainish** [comment]
I'll take a look at this (as well as #13657) next week.

**Comment by Hainish** [comment]
Thanks, this looks good to me.  A future improvement would be to remove the entire comment, or at least the `Other [Ruleset] rulesets:` text and blank lines, surrounding the list if all entries in the list are removed.

**Comment by cschanaj** [comment]
@Bisaloo This is expected since a generic way to cover all the variants introduce false positive results which needed to be cleanup before merging. Personally, I prefer the regex to be strict such that any contributor who want the references to be tracked can _opt-in_ this test (since the inclusions of the references are more or less optional anyway). 

You might be interested in the following command (slow) to find all the dangling references. There is 300 such dangling references and I suspect a lot of them are actually false positive. 

```bash
for f in *.xml; do 
  egrep -o "[a-zA-Z0-9][-a-zA-Z0-9._]*\.xml" "$f" | while read x; do 
    if [ ! -f "$x" ]; then
       echo "$x $f"; 
    fi; 
  done; 
done | sort -u
```

**Comment by Bisaloo** [comment]
>  I prefer the regex to be strict such that any contributor who want the references to be tracked can opt-in this test (since the inclusions of the references are more or less optional anyway).

Maybe we should add something about this in `CONTRIBUTING.md` then.

**Comment by jeremyn** [comment]
I don't like the idea of programmatically checking comments in general. If we want tests to fail then we should move the references out of the comments.

Also this test makes it awkward to work on files that refer to each other, in separate PRs. See PR https://github.com/EFForg/https-everywhere/pull/14258#issuecomment-357244015 for an example.

Probably we should move this into a periodic clean-up task, like we do with `hsts-prune`, rather than a Travis test.

**Comment by jeremyn** [comment]
`hsts-prune` isn't a great example since we run it in Travis, but I hope my point was clear.

**Comment by Bisaloo** [comment]
I agree with @jeremyn's comment in https://github.com/EFForg/https-everywhere/pull/13657#issuecomment-346944585 this is starting to  become too much of a hassle.

I don't see any clear benefit for those comments. IMO, we should only keep them when `target`s *from the same domain* are scattered over more than one ruleset. Otherwise, I am voting for removing them completely.

Should we open a new issue to discuss this?

**Comment by Hainish** [comment]
@Bisaloo I'd rather not create the overhead of a new issue if we're in agreement here, which I suspect we are for the purposes of a stop-gap solution.

I agree with @jeremyn's assessment that this doesn't need to be a test built into our CI, and it's already coded in a way that will allow us to run it as a periodic clean-up task.  If we're all in agreement, I can remove this line from `travis.sh`.

**Comment by Bisaloo** [comment]
@Hainish, we are not only talking about removing this task from the tests but removing/not adding "useless" references in general.

@jeremyn probably explained it better than me in https://github.com/EFForg/https-everywhere/pull/13657#issuecomment-346944585.

**Comment by Bisaloo** [comment]
See for example [`Conde-Nast.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Conde-Nast.xml). I am not sure why we care about the list of the companies they own.

**Comment by Hainish** [comment]
@Bisaloo I've seen that proposal, but that would take a lot more work and is a more comprehensive overhaul.  I'm fine with opening up a discussion for how to deal with related ruleset references if it's becoming an increasing maintenance headache.  I suspect when the ruleset list was still small, years ago, the informal process of adding the references in comments made more sense than it does today - that warrants discussion.  But we should deal with the immediate problem first.

**Comment by jeremyn** [comment]
@Hainish What is the immediate problem?

**Comment by Hainish** [comment]
@jeremyn this:

> I don't like the idea of programmatically checking comments in general. If we want tests to fail then we should move the references out of the comments.
> 
> Also this test makes it awkward to work on files that refer to each other, in separate PRs. See PR #14258 (comment) for an example.

**Comment by Hainish** [comment]
The above can be solved very easily, by just removing this line.  At the same time, we should create a list of periodic clean-up tasks (probably in the wiki).

**Comment by Bisaloo** [comment]
As a first step, we should at least stop adding this kind of comments then and remove them when we get the chance.

**Comment by jeremyn** [comment]
The questions of what to do with this test and what to do with references are related. If we want to remove references entirely then we should remove the test, but if we want to keep references then we can think about improving the test.

**Comment by Hainish** [comment]
@Bisaloo I think there is a use to having ruleset references included.  It makes it clearer to discern what file targets should be added to, when it's ambiguous.  For instance, if someone discovers a new subdomain for `fbcdn.net` which should be covered, they may not know that a ruleset file exists for that specific scope.  If they open `Facebook.xml` and it does not reference `FbCDN.net.xml`, they're likely to miss it and simply add that subdomain to the wrong file.

@jeremyn I think there is a simple solution to the immediate problem: removing the test from CI.  If you're running into problems with this test, we should simply remove it for now.  Then we can consider the long-term questions in a separate issue: if we want to improve it, how to improve it, and what to do with ruleset references in general.

**Comment by jeremyn** [comment]
@Hainish The `fbcdn.net` example could be solved by encouraging contributors to grep for domains before adding them.

I think the current test is better than nothing if we want to keep references. We can keep it in place while we have a larger discussion.

**Pull request merged**
