### PR TITLE
[Dodo.com] New ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by J0WI** [comment]
See also:
footy.dodo.com
web.dodo.com
home.dodo.com
mobile.dodo.com
pfs.dodo.com
accountmanagement.dodo.com
rugby.dodo.com
dealer.dodo.com
speedtest.dodo.com

Please also check *.dodo.com.au for subdomains.

**Comment by J0WI** [comment]
ping @youdly

**Comment by youdly** [comment]
Added subdomains.

**Comment by J0WI** [comment]
Please have a look at the list in my comment. Some of them are still missing.

**Comment by youdly** [comment]
Separated into `dodo.com` and `dodo.com.au` rulesets. Tested/Added a bunch of subdomains.

**Comment by J0WI** [comment]
There's an error on `images.dodo.com`

**Comment by youdly** [comment]
Removed `images.dodo.com`

**Comment by J0WI** [comment]
Please keep an eye on Travis: `wholesale.dodo.com.au` serves an incomplete cert chain.

**Comment by youdly** [comment]
`wholesale` WFM on Firefox and Chrome.

**Comment by J0WI** [comment]
This is only working because the cert is already cached in your profile. `firefox --new-instance --profile $(mktemp -d) https://wholesale.dodo.com.au/` does not work.

**Comment by youdly** [comment]
Removed `wholesale`.

**Comment by youdly** [comment]
`www` `click2talk` `cms` `facebook` `my` `new` `pfs` WFM on `curl`.

**Pull request merged**
