### PR TITLE
[Pinterest] Remove preloaded ruleset.

### PR DESCRIPTION
**Pull request by bardiharborow**
`pinterest.com` meets the [guideline for removal of HSTS preloaded properties](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#hsts-preloaded-rules). `pinimg.com` is preloaded in Chrome and is currently pending preload in Firefox and Tor. The fetch test was broken for one disused subdomain and many subdomains were missing, so I've replaced it with a wildcard, pending removal when it is fully preloaded.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Can you remove [comments linking to this ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Pinimg.com.xml#L2) as well when you remove rulesets please ?

**Comment by bardiharborow** [comment]
@Bisaloo yep, that would be smart I guess. :joy:

**Comment by bardiharborow** [comment]
@gloomy-ghost we should be good to go here.

**Comment by gloomy-ghost** [comment]
https://hstspreload.com/api/v1/status/pinterest.com
Isn't `pinterest.com` pending in Fx as well?

**Comment by bardiharborow** [comment]
@gloomy-ghost I think `hstspreload.com` is malfunctioning, as the record is clearly in https://hg.mozilla.org/releases/mozilla-esr52/raw-file/FIREFOX_52_3_0esr_RELEASE/security/manager/ssl/nsSTSPreloadList.inc

**Comment by adamcaudill** [comment]
@gloomy-ghost There was an issue loading data, due to a file format change; this has been corrected and the data being returned is now correct.

**Comment by gloomy-ghost** [comment]
Thanks!

**Pull request merged**
