### PR TITLE
Added rules for ble.de.

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by J0WI** [comment]
Is this related to bund.de?

**Comment by Jochen-A-Fuerbacher** [comment]
It is the domain of a federal office of Germany and it is also listed on the bund.de website. However it doesn't contain any bund.de domain. I can put a comment to this file referencing the main bund.de ruleset, if you think that this would be useful.

**Comment by J0WI** [comment]
That would be great!

**Comment by J0WI** [comment]
Travis detected an error on `download.ble.de`. Is this subdomain no longer in use or do we just need a more specific test url?

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
