### PR TITLE
Added wired.com

### PR DESCRIPTION
**Pull request by Foorack**
https://www.wired.com/2016/09/now-encrypting-wired-com/

### CODE REVIEW

**Comment by jeremyn** [comment]
Wow, good catch! Please:

Mark as `Refused`:
- [ ] https://feeds.wired.com

Add target:
- [ ] https://assets.wired.com

Also:
- [ ] Add a generic `<securecookie host=".+" name=".+" />` tag (see [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md)) between the `target`s and `rule`. These are good to have when a site lets users log in and everything supports HTTPS.

**Comment by jeremyn** [comment]
Good find on the old `Wired.xml` file. I've updated the checklist with some more items related to that.

**Comment by Foorack** [comment]
@jeremyn All done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
