### PR TITLE
Update ImQuQu.com.xml

### PR DESCRIPTION
**Pull request by qgy18**
remove the 'www.' of begin.

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the update! https://imququ.com looks fine now so can you please delete the top comment?

Also, it would be nice if you could make these changes too:

* Remove the complex rewrite rule and just do https to http.
* Add target `st.imququ.com`

**Comment by qgy18** [comment]
done!

**Comment by jeremyn** [comment]
Thanks but can you delete the [top comment](https://github.com/qgy18/https-everywhere/blob/c878f40f3d206739ed6b451fec981c3df473d63a/src/chrome/content/rules/ImQuQu.com.xml#L2) too?

**Comment by qgy18** [comment]
fixed :)

**Comment by jeremyn** [comment]
Thanks.

**Comment by jeremyn** [comment]
@Hainish When I merged this in, somehow it went into branch `EFForg:release`, which I think is different from the normal merge branch. What happened?

**Comment by Hainish** [comment]
@jeremyn: The normal merge branch is `master`.  It looks like @qgy18 requested to merge this into `release`.  This may have been unintentional - if the PR branch was forked from `release` then github may have defaulted the open PR dialogue to request it be merged back into `release`.

The `release` branch is used to build the [HTTPS Everywhere Atlas](https://www.eff.org/https-everywhere/atlas/) ([repo](https://github.com/EFForg/https-everywhere-atlas)) tool, which compares with `master` to let users know how if the rulesets are current and what has changed since the last release.  Every day, a cron job is run to build the Atlas based on the current state of `master` and `release`.

In the past few days I've overwritten the `release` branch, since we made a few releases of the tool, so if any problems resulted due to this, they should be resolved by now.

**Comment by Hainish** [comment]
Indeed, it seems to be missing from `release`:

```shell
user@https-everywhere ~/workspace/https-everywhere (release) $ git diff upstream/release
user@https-everywhere ~/workspace/https-everywhere (release) $ git log | grep f27c9a1c68310b9640c0b473f3dc14d264ca4c30
user@https-everywhere ~/workspace/https-everywhere (release) $
```

**Comment by Hainish** [comment]
I've merged this into master with https://github.com/EFForg/https-everywhere/commit/5207ba15ce2c52ca71c4567df49d3d14e3ff4007

**Comment by jeremyn** [comment]
Thanks @Hainish .

**Comment by qgy18** [comment]
Thanks @Hainish @jeremyn

**Pull request merged**
