### PR TITLE
Create bewelcome.org.xml

### PR DESCRIPTION
**Pull request by simison**
Copied from http://www.bewelcome.org/forums/s13127/#post77868 (requires login)

### CODE REVIEW

**Comment by fuglede** [comment]
Thanks for the PR. As you might have seen, [Travis complains](https://travis-ci.org/EFForg/https-everywhere/jobs/113548602) about the lack of tests in this ruleset. You can refer [to this part of the documentation](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md) for more information on ruleset testing.

**Comment by simison** [comment]
Yep, noticed, but sadly I don't have time for that right now.

I asked from the BW community for some help though: http://www.bewelcome.org/forums/s13127/#post78001 (link requires login)
>posted 2016/03/07 03:26
>Ah, my code request to HTTPSEverywhere can't go trough due missing tests.
>
>If you're tech savvy, feel free to add them to my repository and I'll add them, or send a new PR to HTTPS Everywhere. I unfortunately don't have time for this now.

**Comment by simison** [comment]
^ That said, feel free to close this, since frankly I don't think nobody would step up with tests. I can come over and re-open if someone else decides to work on this.

**Comment by fuglede** [comment]
Thanks for getting back on this. In this case, cooking up the tests really boils down to coming up with all the relevant subdomains of the site.

**Comment by simison** [comment]
Closing, follow ups @ #4587

**Pull request closed without merging**
