### PR TITLE
Update Baidu.xml

### PR DESCRIPTION
**Pull request by renyouguo**
#4577

### CODE REVIEW

**Comment by mnordhoff** [comment]
The XML syntax is off. You changed `<!--` to `<` but didn't change `-->` to `>`. E.g.:

    	<target host="pan.baidu.com" />

**Comment by renyouguo** [comment]
@mnordhoff Thanks.However,what is the error now?

**Comment by mnordhoff** [comment]
There's a disabled ruleset called `Baidu.com-problematic.xml` that includes (only) the same two hosts you're adding to `Baidu.xml`. You should delete it.

**Comment by renyouguo** [comment]
@mnordhoff I have pull request to delete it yesterday. #4577

**Comment by mnordhoff** [comment]
Oh. Then you've done everything right, but the tests don't know it because everything is in two separate pull requests. Your options are to wait until the other pull request is merged and trigger a retest; merge the branches together; or ignore the matter and cross your fingers.

**Comment by mnordhoff** [comment]
For what it's worth, I tried it, and taking master 3b3df378285783b9f58bba9e51a40912acf63297 + merge #4577 + merge #4584 **does** pass Travis.

https://github.com/mnordhoff/https-everywhere/tree/Baidu-4577-4584
https://travis-ci.org/mnordhoff/https-everywhere/builds/121878198

**Comment by J0WI** [comment]
There are some issues on `open2` and `yun` (see Test log).

**Comment by renyouguo** [comment]
@J0WI Sorry，I do not know how to fix it.

**Comment by mnordhoff** [comment]
@J0WI open2 and yun both work for me in-browser (Chrome). Command line `curl` -- which seems more forgiving than pycurl in multiple ways -- works too. Maybe this should be classified as a test suite problem.

https://www.ssllabs.com/ssltest/analyze.html?d=open2.baidu.com

open2's certificate chain is out of order, something that's a fail for pycurl but ignored by browsers.

(It also has a _shockingly_ insecure TLS configuration, and can be MITMed in more than one way, but browsers don't care about _that_.)

https://www.ssllabs.com/ssltest/analyze.html?d=yun.baidu.com

I can't figure what's wrong with this one...

**Comment by J0WI** [comment]
See https://github.com/EFForg/https-everywhere/pull/2668#issuecomment-134683296 for the chain problem

**Comment by renyouguo** [comment]
#4743

**Pull request closed without merging**
