### PR TITLE
Nav-dem.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] I see the mixed content warning but the site looks okay to me. Do you see anything that's broken?

**Comment by J0WI** [comment]
Nope

**Comment by jeremyn** [comment]
So do you want to remove the `mixedcontent` platform or...?

**Comment by J0WI** [comment]
sure

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
