### PR TITLE
Update Deutschebahn.com.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by J0WI** [comment]
Would be great if you could add some more subdomains here.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Finally went through all subdomains! @J0WI

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Finally added all subdomains, phew! :fireworks:  @J0WI

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
