### PR TITLE
Break loop in thread run function (issue #6240)

### PR DESCRIPTION
**Pull request by jeremyn**
This pull request should resolve issue #6240.

@Hainish, can you review this please?

### CODE REVIEW

**Comment by jeremyn** [comment]
@fuglede @Hainish @J0WI Can someone please review this? The problem is annoying.

**Comment by Hainish** [comment]
This change will make it so that if the number of files being checked exceeds the number of threads allowed, the process never completes.

For the fetch test, the number of threads is specified in https://github.com/EFForg/https-everywhere/blob/master/test/rules/http.checker.config#L23 as `40`.  To reproduce the above:

1. Change the number of threads in https://github.com/EFForg/https-everywhere/blob/master/test/rules/http.checker.config#L23 to `1`
2. Modify > 1 ruleset
3. Run the fetch test

It will never exit.

This is because without the loop, the UrlComparisonThread only checks exactly one changed ruleset (specified as ComparisonTasks in `taskQueue`) before exiting.  If the number of threads allowed exceeds the number of rulesets changed, there will not be enough threads to process the `taskQueue`.  Thus, https://github.com/EFForg/https-everywhere/blob/master/test/rules/src/https_everywhere_checker/check_rules.py#L433 never completes.

**Comment by jeremyn** [comment]
That makes sense. My normal use case is running `fetch-test.sh` against one ruleset so I didn't notice the problem.

Regarding your improved fix in #6692: it looks like originally, the threads were started before the taskQueues were filled, so `while True` was a "lazy" way of making sure everything put into the queues would be completed. Because you now properly check that the queue is empty, you can't start the threads until after the queues have actually been filled. Do I understand the fix correctly?

**Comment by Hainish** [comment]
That's almost right.  Here:

> Because you now properly check that the queue is empty, you can't start the threads until after the queues have actually been filled.

I would phrase this differently - it is not that we can't start the threads until the queues have been filled *because* we check that the queue is empty.  It's that, procedurally, we first fill the queue, and only then run the `UrlComparisonThread` which begins processing the queue, exiting when the queue is empty.

If we changed the conditional without moving the block below, all the `UrlComparisonThreads` would immediately exit, because the queue would be empty, because we wouldn't have filled it with tasks yet.

**Comment by jeremyn** [comment]
Thanks @Hainish .

Closing pull request.

**Pull request closed without merging**
