### PR TITLE
Create ruleset for seriouseats.com

### PR DESCRIPTION
**Pull request by injust**

### CODE REVIEW

**Comment by Bisaloo** [comment]
@Injust, can you add `Fix #9263` to your PR description please? It will automatically close #9263 once this PR is merged.

More info: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by Bisaloo** [comment]
Oh, I didn't see it was `platform="mixedcontent"`. Do we have a way to fix #9263 for everybody?

**Comment by Bisaloo** [comment]
As far as I can tell, only active mixed content is from http://www.assoc-amazon.com/. I think it's okay to break ads so I would remove the `platform`.

**Comment by Injust** [comment]
@Bisaloo The site also uses mixed content for comments.

**Comment by J0WI** [comment]
I wasn't able to reproduce MCB issues with comments.

**Comment by Injust** [comment]
@J0WI Seems that between the time when I opened the PR and when you checked, SSL was deployed on the site.
Removing `platform="mixedcontent"` from the ruleset.

**Pull request merged**
