### PR TITLE
[Root.cz] New ruleset

### PR DESCRIPTION
**Pull request by oskar456**
Root.cz recently enabled HTTPS on their servers.

### CODE REVIEW

**Comment by Roman3349** [comment]
The following are also working:
blog.root.cz
rss.root.cz

Mismatch on:
partner.root.cz
butik.root.cz

**Comment by J0WI** [comment]
@oskar456 please also add comments for non working hosts. This makes future maintenance easier.

**Comment by oskar456** [comment]
@J0WI added, thanks for the tip.

**Comment by J0WI** [comment]
I also got:
zdrojak.root.cz
butik.root.cz
autoconfig.root.cz
partner.root.cz
blok.root.cz

Please move comments on the top of the rule.

**Comment by oskar456** [comment]
OK, I'v added all subdomains I've discovered. Most of them are however only some sort of redirects, sometimes to http-only websites.

**Comment by J0WI** [comment]
There is a problem on with ipv6.root.cz.
Maybe Travis is not IPv6 compatible?
@fuglede do you know that?

**Comment by fuglede** [comment]
@J0WI: No clue.

**Comment by J0WI** [comment]
I just browsed some travis issues and others have similar [problems](https://github.com/travis-ci/travis-ci/issues/4964#issuecomment-159748141).
cc @Hainish

**Pull request merged**
