### PR TITLE
Re-activate Doubleclick.net.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
https://github.com/EFForg/https-everywhere/pull/13419/files#diff-be1acc0640c5d39f6da27a663a34bd0fR77 is broken, maybe we should add some exclusions here.

**Comment by gloomy-ghost** [comment]
Quoting from https://github.com/EFForg/https-everywhere/issues/13273#issuecomment-339826920, we can even just remove that rule and leave a plain rewrite.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@gloomy-ghost Is my last commit sufficient for that purpose?

**Comment by gloomy-ghost** [comment]
Merged, thanks.

**Pull request merged**
