### PR TITLE
Added a ruleset for website: www.brandweeruitgeest.nl

### PR DESCRIPTION
**Pull request by SvenKortekaas**
Added a ruleset for the website https://www.brandweeruitgeest.nl

### CODE REVIEW

**Comment by fuglede** [comment]
Looks good to me; thanks! Also fixes the site's own weird redirect bug at http://www.brandweeruitgeest.nl/.

**Comment by SvenKortekaas** [comment]
Cool. Can you please explain the weird redirect bug? Maybe I can fix that.

**Comment by fuglede** [comment]
http://www.brandweeruitgeest.nl/ currently redirects to https://www.www.brandweeruitgeest.nl/ which does not exist.

    $ curl www.brandweeruitgeest.nl
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>301 Moved Permanently</title>
    </head><body>
    <h1>Moved Permanently</h1>
    <p>The document has moved <a href="https://www.www.brandweeruitgeest.nl/">here</a>.</p>
    </body></html>

If you have something to do with the site, you may also want to know that there is a problematic link to https://monitor.bmhvd.nl/afmelden in the menu on the left.

**Comment by SvenKortekaas** [comment]
Thank you for the info. I will try to fix this asap.

**Pull request merged**
