### PR TITLE
Update ruleset Google.tld_Subdomains.xml

### PR DESCRIPTION
**Pull request by itochan**
I added target host `cse.google.com` to Google.com_Subdomains.xml

### CODE REVIEW

**Comment by J0WI** [comment]
Please add this here: https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.tld_Subdomains.xml

**Comment by itochan** [comment]
I missed this file. I fixed.

**Comment by J0WI** [comment]
You need to update the hash in `utils/ruleset-whitelist.csv`.
Please also add `cse.google.co.*` and `cse.google.com.*` as targets.

**Comment by itochan** [comment]
I understood, updated!

**Comment by itochan** [comment]
I'm sorry 😢
I added, is it mergeable?

**Pull request merged**
