### PR TITLE
Add 800HelpFla.com.xml

### PR DESCRIPTION
**Pull request by gopherit**

### CODE REVIEW

**Comment by jeremyn** [comment]
@gopherit Are you still interested in working on this pull request?

**Comment by gopherit** [comment]
Yes, it's ready to go.  It's a weird domain in that it only applies to a couple hosts:

- http://chat.800helpfla.com/HPPC/hppcwis.dll?varUserRequest=REQ_WEBCHAT_MAIN&varUserLanguage=english&varBusinessUnitName=DEFAULT
- http://csapp.800helpfla.com/csrep/

I had Travis errors when including these two as Test URLs.

**Comment by jeremyn** [comment]
@gopherit Okay so, first, here's how I would make this ruleset:

```xml
<!--
	Invalid certificate:
		800helpfla.com
		www.800helpfla.com

	Secure connection failed:
		app1.800helpfla.com

-->
<ruleset name="800HelpFla.com (partial)">
	<target host="chat.800helpfla.com" />
	<target host="csapp.800helpfla.com" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

There are some minor changes from what you have. Please review these changes and let me know if you have any questions.

That said, I'm not sure this is a good ruleset to have at all. The only thing it does is provide HTTPS coverage to some complex web applications for a state agency where core parts of the site (`^`, `www`) don't support HTTPS. I'm not confident that these web applications will be robust enough to work correctly with our rewrites, particularly `chat` which doesn't redirect itself to HTTPS (`csapps` does redirect itself). So I'm tempted to say we should just close this PR as `wontfix`. What do you think?

**Comment by gopherit** [comment]
@jeremyn, FWIW, I tested both web applications with HTTPS Everywhere's rewrites back when we had the "HTTPSEverywhereUserRules" directory, and they rewrote fine, including cookies.  The `chat` web application is actually my biggest concern, since Social Security Number is routinely sent through when residents ask for help.

**Comment by jeremyn** [comment]
By the way, there's a new ruleset debugger, intended for testing, in the extension itself that sort of replaces the old `HTTPSEverywhereUserRules` directory. You can access it through `about:addons` > HTTPS Everywhere > click under `General Settings` > press <kbd>Ctrl-Z</kbd>. The Chrome extension has something similar, accessed in a similar way.

Anyway, the direct rewrites appear fine but I'm concerned that the actual complicated behavior of the web applications won't work, particularly the `chat` application. For example you can imagine the `chat` application having some option to upload files to the person you're talking to and maybe that upload option fails with the rewrite.

**Comment by gopherit** [comment]
Heh, the chat application isn't that complex (no upload functionality).  I've used it several times, and I've manually used HTTPS 100% of the time.

**Comment by jeremyn** [comment]
Just because you type `https` in the browser doesn't mean that all of the secondary requests for the page will be in HTTPS, though HTTPS Everywhere will write them. So one of them might break the chat application.

Anyway I can't find an excuse not to cover this domain, so let's proceed. Please narrow the `securecookie` tag to just the included `target`s, and add some `test`s.

- [ ] Use this:

```xml
<!--
    Invalid certificate:
        800helpfla.com
        www.800helpfla.com

    Secure connection failed:
        app1.800helpfla.com

-->
<ruleset name="800HelpFla.com (partial)">
    <target host="chat.800helpfla.com" />
        <test url="http://chat.800helpfla.com/HPPC/hppcwis.dll?varUserRequest=REQ_WEBCHAT_MAIN" />
    <target host="csapp.800helpfla.com" />
        <test url="http://csapp.800helpfla.com/csrep/" />

    <securecookie host="^(chat|csapp)\.800helpfla\.com$" name=".+" />

    <rule from="^http:"
        to="https:" />
</ruleset>
```

**Comment by gopherit** [comment]
@jeremyn, done, thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
