### PR TITLE
Update Bitly_branded_short_domains.xml

### PR DESCRIPTION
**Pull request by cschanaj**
Remove 'target' which are gone from DNS. Theoretically this should improve the memory usage of this extension.

### Resources
GO script used to remove the resolve the `target`: [`dns-prune.go`](https://github.com/cschanaj/lambda/blob/master/src/dns-prune.go)

**WORK IN PROGRESS**

### CODE REVIEW

**Comment by J0WI** [comment]
Personally I would love to see an update by @jehiah itself. :)

**Comment by cschanaj** [comment]
This ruleset contains around 25% of all the `target` in the code base. It will be great if @jehiah is willing to help, I will close this PR in such case.

**Comment by Bisaloo** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/10017

**Comment by J0WI** [comment]
@Hainish do you have a way to contact @jehiah?

**Comment by Hainish** [comment]
I tagged him in the old PR: https://github.com/EFForg/https-everywhere/pull/5611#issuecomment-317180708, and just reached out to him over email.

**Comment by Hainish** [comment]
Looks like he's out on extended leave until September.  Being that it's been a year since the last update, I think it'll be fine for us to punt on this another month.

**Comment by cschanaj** [comment]
closing as this is a duplicate of #11804. thanks!

**Pull request closed without merging**
