### PR TITLE
[Woolworths.com.au] Add subdomains and rename ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by youdly** [comment]
Travis: `No output has been received in the last 10m0s.`

**Comment by youdly** [comment]
Rebase and update comment

**Comment by youdly** [comment]
`ssmt.intdns.woolworths.com.au` WFM on curl and openssl

**Comment by J0WI** [comment]
Thanks for this big contribution. Could you please split this into multiple PRs, otherwise it takes too long to review all parts.

**Comment by youdly** [comment]
Moved rulesets to separate PRs.

**Comment by youdly** [comment]
rebased

**Pull request merged**
