### PR TITLE
Delete make-json.py

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by koops76** [comment]
ping @Hainish @cowlicks.

**Comment by cowlicks** [comment]
We also use `make-json.py` inside `makecrx.sh`. What is the purpose of this script and the `rulesets.json` file it generates?

**Comment by koops76** [comment]
@cowlicks Seems to be a leftover.

**Comment by cowlicks** [comment]
Would you mind:
* removing the usage from makecrx.sh
* rewording the commit messages to be more descriptive
* explaining when/why the usage of `make-json.py` was deprecated

**Comment by koops76** [comment]
@cowlicks I think it was deprecated when we moved back to XML.

**Pull request merged**
