### PR TITLE
Fixing #2880

### PR DESCRIPTION
**Pull request by TheNavigat**
I had to push using ```no-verify``` to get this through. It's a bit too much to refactor the whole thing while the fix is that simple.

### CODE REVIEW

**Comment by TheNavigat** [comment]
Ugh I hate this...

**Comment by TheNavigat** [comment]
I tried to fix this, but I ended up with a failure: ```Symantec.xml failed test: Rule redirects to something other than https.``` error. I commented stuff, trying to find the error, and then I ended up with this.

http://pastebin.com/BTty3dGE

That still returned the same error.

Any help, @fuglede ?

**Comment by fuglede** [comment]
If I run <code>test/rules.sh</code> against your commit, I get the same result as Travis which is just that a bunch of tests are missing from the ruleset; I'm not actually seeing the error you're mentioning.

In your pastebin link though, <code>http</code> should be <code>http:</code> and <code>https</code> should be <code>https:</code>.

**Comment by TheNavigat** [comment]
Yea, the errors are different indeed. I figured that I need to restructure the code in order to get this passing, and the error in the comment above was what the code in Pastebin produced.

Thanks for the ```http:``` and ```https:``` note, that fixed it.

**Comment by TheNavigat** [comment]
@fuglede Can you check this PR again, please?

**Comment by semenko** [comment]
Seems good + fixes a user-reported bug. Merging.

**Pull request merged**
