### PR TITLE
Add humandesign.fi

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by pipboy96** [comment]
Please also try:

- `autodiscover.humandesign.fi`
- `ftp.humandesign.fi`

**Comment by scop** [comment]
>     * `autodiscover.humandesign.fi`
>     * `ftp.humandesign.fi`

Interesting, Sublist3r didn't find these. Anyway, added as nonfunctional as the https versions are lacking the respective name in certificate SAN.

**Comment by pipboy96** [comment]
@scop Try using Amass (https://github.com/OWASP/Amass).

**Comment by scop** [comment]
Thanks. BTW amass didn't reveal any additional names for me either.

**Pull request merged**
