### PR TITLE
[Lenovo] Add exclusion

### PR DESCRIPTION
**Pull request by fuglede**
This closes https://trac.torproject.org/projects/tor/ticket/18055

### CODE REVIEW

**Comment by jeremyn** [comment]
What's the purpose of `utils/ruleset-coverage-whitelist.txt`? I don't know what that file is for or when it should be changed.

**Comment by fuglede** [comment]
@jeremyn: When the ruleset test requirements were introduced, the requirements would not be satisfied for a large part of the existing ruleset collection. Thus, a whitelist was introduced to allow the test to run. Each entry consists of the name of the whitelisted ruleset together with its `sha256sum`, and if a ruleset is included, it will not be included in the test. As we continue to update the database, the length of the whitelist will continue to decrease, but in this case, I'll not have the time to produce the thorough update required to remove it from the whitelist, so I simply updated the hash. You'll probably see that happen every now and then.

Now, the obvious question is why the test ran anyway ...

**Comment by jeremyn** [comment]
Oh, I see. I just had a hassle with test failures in pull request #6683, though not as many as you have here. If I had added `BusinessInsider.xml` to the whitelist, I could have avoided the extra rewrites. Of course that would not have been good to do especially since `BusinessInsider.xml` isn't in the whitelist already.

**Comment by jeremyn** [comment]
By the way, I looked at this and couldn't figure it out. My vague idea is that something is wrong in Travis.

**Comment by fuglede** [comment]
I found the explanation; see #6689.

**Comment by jeremyn** [comment]
Why did you remove the trailing slash from 

```xml
<exclusion pattern="^http://www\.lenovo\.com/(?:lenovorecovery|support|training)" />
```

and the related tests? Also, you can remove the `?:` for simplicity.

**Comment by fuglede** [comment]
Fixed the non-capturing groups. I removed the slash to ensure that the pattern would match both http://www.lenovo.com/lenovorecovery and http://www.lenovo.com/lenovorecovery/ (and similarly for the others; note that https://www.lenovo.com/training is currently broken).

**Comment by jeremyn** [comment]
Thanks for updating the non-capturing groups.

I see what you mean about the trailing slash. In #5601 we're discussing some ambiguity about trailing slashes. It'd be great if you could contribute to that discussion.

**Pull request merged**
