### PR TITLE
Create forest.go.th.xml

### PR DESCRIPTION
**Pull request by weeix**
Allow Cloudflare to enforce Automatic HTTPS Rewrites for websites under forest.go.th so visitors could safely browse them without seeing mixed content warning.

### CODE REVIEW

**Comment by J0WI** [comment]
This wildcard rule will break various subdomains. Please have a look at our [Enumerating Subdomains](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains) section.

**Comment by jeremyn** [comment]
@weeix Are you still interested in working on this pull request?

**Comment by weeix** [comment]
No. The pull request can be removed. Thank you.

เมื่อ 6 ธ.ค. 2017 4:21 ก่อนเที่ยง "Jeremy Nation" <notifications@github.com>
เขียนว่า

@weeix <https://github.com/weeix> Are you still interested in working on
this pull request?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/EFForg/https-everywhere/pull/9917#issuecomment-349445473>,
or mute the thread

**Comment by jeremyn** [comment]
@weeix Thanks for responding. I'm closing this pull request. I've also added `forest.go.th` to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-349729502` in case someone wants to work on this in the future.

**Pull request closed without merging**
