### PR TITLE
Cleanup HSTS rules

### PR DESCRIPTION
**Pull request by J0WI**
- removed broken rules completely for nonexistent hosts
- fixed/rewrote broken rules
- removed rules that duplicates the HSTS preload list
- removed platform="firefox" and HSTS comment, since Firefox supports preloaded HSTS
- merged auto generated rules with existing rules
- set rules to default off if they need a complete rebasing

### CODE REVIEW

**Comment by jsha** [comment]
Looks great, thanks for this big cleanup!

**Comment by 2d1** [comment]
@jsha Looks great, hey? Do you know what your next fetch testing deluge is going to do to Atlassian.xml? Do you even read anything aside from summary and filenames changed when you review pull requests? I mean, I know you are worth so much more than I am, but for fuck's sake.

I think it's absolutely appalling that the torbrower includes https-everywhere considering this nonchalance.  Anyone using https-everywhere except as a badge for their identity of 'sticking it to the man' is just asking for trouble.

**Comment by J0WI** [comment]
Note that Atlassian.xml is already marked with ```default_off="Needs ruleset tests"```

> I suspect these changes generally confuse the initial generation of rulesets from the preload list with the current state of the rulesets.
Can you explain that?
In my opinion the auto generated rulesets were unusable because they didn't cover all (sub-) domains or duplicates Firefox' preloaded HSTS list. Some of them were broken anyway.
In the end, we don't care about HSTS, because the rules have to pass our test and we want to protect all (sub-) domains, even when the admins didn't add a HSTS header.

**Comment by jsha** [comment]
@2d1: Thank you for editing to remove your earlier post. I would still like to respond to it here: Your work is tremendously important. You're easily the most prolific member of the HTTPS Everywhere community, you write good rulesets, and you test them well.

That said, I absolutely will not tolerate an abusive member of our community, no matter how good their contributions. If I or anyone else makes you mad like that again, hold off on posting until you can contribute something valuable.

**Comment by jsha** [comment]
Also, @2d1's comment about the Tor Browser Bundle led me to double-check TBB's HSTS preload list. It appears to be almost a year out of date, which was a surprise to me. I filed an issue: https://trac.torproject.org/projects/tor/ticket/16584.

@J0WI, could you make a follow-on PR to restore rulesets for hosts that are not yet in TBB's list? I filed an issue for it: https://github.com/EFForg/https-everywhere/issues/2192.

**Pull request merged**
