### PR TITLE
Update LaPatilla.com.xml

### PR DESCRIPTION
**Pull request by koops76**
~~https://lapatilla.com/ redirects to HTTP.~~

#10782

### CODE REVIEW

**Comment by cschanaj** [comment]
there exist some sub-domain work over HTTPS, please re-activate the ruleset instead.

**Comment by koops76** [comment]
@cschanaj Sublist3r doesn't show any.

**Comment by koops76** [comment]
@cschanaj cdn.lapatilla.com may have a different CNAME that supports HTTPS but I don't know it.

**Comment by cschanaj** [comment]
what about `www` ?

**Comment by koops76** [comment]
@cschanaj cdn.lapatilla.com doesn't resolve.

**Comment by koops76** [comment]
@cschanaj works.

**Comment by cschanaj** [comment]
Yes, but `www` works over HTTPS. given this is a `top-1k` domain, you should update the ruleset instead of deletion IMHO.

**Comment by koops76** [comment]
@cschanaj Done.

**Comment by koops76** [comment]
@J0WI Request review.

**Comment by koops76** [comment]
@J0WI Request review.

**Comment by koops76** [comment]
ping @J0WI.

**Pull request merged**
