### PR TITLE
Ruleset for thefirehoseproject.com

### PR DESCRIPTION
**Pull request by ankitpati**
Added a ruleset for a [site](https://www.thefirehoseproject.com/ "The Firehose Project").

### CODE REVIEW

**Comment by J0WI** [comment]
Please see also:
blog.thefirehoseproject.com
community.thefirehoseproject.com
forum.thefirehoseproject.com
phoenix.thefirehoseproject.com
stories.thefirehoseproject.com

**Comment by J0WI** [comment]
@ankitpati would be great if you cloud finish this PR :)

**Comment by jeremyn** [comment]
@ankitpati Are you still interested in working on this?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @ankitpati . I've noted `thefirehoseproject.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353119782` in case someone else wants to make a pull request for this domain.

**Pull request closed without merging**
