### PR TITLE
Added th-nuernberg.de (Fixed #5143)

### LINKED ISSUE #5143: [Applied University of Nuremberg] add www.th-nuernberg.de
Please add this https://www.th-nuernberg.de
They don't redirect to https themselves..

### PR DESCRIPTION
**Pull request by Foorack**
Fixes https://github.com/EFForg/https-everywhere/issues/5143

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. There are many other subdomains for `*.th-nuernberg.de` than `^` and `www`, for example see [this search](https://www.google.com/search?q=site%3A*.th-nuernberg.de&ie=utf-8&oe=utf-8#q=site:*.th-nuernberg.de+-site:www.th-nuernberg.de). Please add these, and then we'll review it more closely.

**Comment by Foorack** [comment]
@jeremyn Updated.

**Comment by Foorack** [comment]
"SSL certificate problem: unable to get local issuer certificate"?

**Comment by jeremyn** [comment]
That means those sites are misconfigured and you should remove the targets and note them as bad. See the discussion in issue #6569 .

**Comment by Foorack** [comment]
@jeremyn It seems like I have managed to mess up with git. Will recreate this pull as it seems I can no longer make changes to the current one.

**Comment by jeremyn** [comment]
FYI: the new pull request is #6857 .

**Pull request closed without merging**
