### PR TITLE
Create akixi.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
This ruleset is generated by a script... Hope it works.

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Mark https://akixi.com under `Refused`
- [ ] Alphabetize the error types in the top comment
- [ ] Many of the `target`s have logins, which are especially appropriate for `securecookie`s. Do you want to add a specific `securecookie` to cover all the matching subdomains? The host would be `^(alto|broadconnect|cirrus|cumulus|epik|gamma|horizon|howdens|icore|inclarity|intech|masergy|mcmtelecom|momentum|nexogy|nimans|onecloud|onecloudnet|pressone|redcentric|redgap|saicom|stage2networks|support|tvf|vibe|voicenet|vonage)\.akixi\.com$` .

**Comment by gloomy-ghost** [comment]
Such a long `securecookie`...

Also I'm getting `Reset` for both `^` and `www` now, not sure what's going on.

**Comment by jeremyn** [comment]
I know, the `securecookie` is silly. It would be a nice enhancement to add an attribute or special `host` value to `securecookie` that means "every `target` without any `exclusion`s".

`^` and `www` are `Refused` for me now.

Looks good, merged.

**Comment by gloomy-ghost** [comment]
Does `^\w` mean "every `target` except `^`"?

`.` generally doesn't match with `\w`, but it looks like the leading dot is ignored in https-ew. 

I've seen a great number of `^\w` usages in rulesets, however the style guide only mentioned that `.+`, `.*` and `.` are functionally equivalent.

**Comment by jeremyn** [comment]
In a `securecookie`, `^` probably means "must start at the beginning". According to https://www.eff.org/https-everywhere/rulesets#secure-cookies , hosts in cookies with leading dots are matched as if the dot were stripped, so the fact that `\w` excludes a dot doesn't matter. I guess that `^\w` is an old way of saying `.*` before the project standardized on `.*`.

By the way, I like to use https://regex101.com for regex experimenting.

**Comment by gloomy-ghost** [comment]
Thanks. Would it be okay to replace all of them to `.+` in one pull request?

**Comment by jeremyn** [comment]
You mean in all 20000+ rulesets?

**Comment by gloomy-ghost** [comment]
Yeah, we can do it both side and use diff to confirm that nothing goes
wrong.

**Comment by jeremyn** [comment]
I would rather not. That's too many rulesets to review manually. Why do you want to do that?

**Comment by gloomy-ghost** [comment]
It's confusing to have different patterns even they are functionally equivalent.

Also the replacing is not that hard. I used python in #7892 because I'm not good at bash, maybe we can use awk and compare the difference (There were some `UnicodeDecodeError`s while python were trying to read files)

**Comment by gloomy-ghost** [comment]
163.com.xml currently uses `^\w`:

image

After change to `.+`:

image

...

**Comment by jeremyn** [comment]
I don't know why `.+` encrypts the `__utmz` cookie and `^\w` doesn't, but given that, we should be even more careful before doing a mass search-and-replace.

**Pull request merged**
