### PR TITLE
Replace non-standard for each statement with for

### LINKED ISSUE #7676: Broken on Firefox Nightly
Addon does not work on Firefox Nightly.

I am getting for syntax error in Browser Console.
https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/code/IOUtil.js#L130

Disable non-standard for-each:
https://bugzilla.mozilla.org/show_bug.cgi?id=1293305

### PR DESCRIPTION
**Pull request by smw-koops**
Closes #7676.

### CODE REVIEW

**Comment by evilpie** [comment]
This patch looks wrong to me. for each .. in and for .. in are different. 
For example:
```
for each (var x in ["a", "b"]) { print(x); } // Prints a, b 
for (var x in ["a", "b"]) { print(x); } // Prints 0, 1 (The array indexes) 
```

Sometimes it's possible to replace for each with [for .. of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).

**Comment by smw-koops** [comment]
@evilpie Nice one! This pull request was made in a rush without reading the docs carefully. If ES6 features can be used, then for of is indeed a good choice.

**Comment by arai-a** [comment]
apparently all cases are iterating over array, so you can use `for...of`

**Comment by smw-koops** [comment]
@arai-a I changed `for each...in` to `for...of`. I think that's correct.

**Comment by Hainish** [comment]
lgtm. thanks for the fix @smw-koops!

**Pull request merged**
