### PR TITLE
Delete multiple default_off rulesets (^W)

### PR DESCRIPTION
**Pull request by cschanaj**
#9906 https://github.com/EFForg/https-everywhere/pull/10516#issue-237085032

### CODE REVIEW

**Comment by Bisaloo** [comment]
#10595

**Comment by J0WI** [comment]
Please don't mix those two issues.

**Comment by cschanaj** [comment]
@J0WI do you mean this PR and #11041 ? AFAIK, there is no file changed in common,

**Comment by J0WI** [comment]
I mean #10595 and #9906 (deleting because of default_off and deleting because of gone from DNS).

**Comment by cschanaj** [comment]
@J0WI this PR was created according to the conditions listed in https://github.com/EFForg/https-everywhere/pull/10516#issue-237085032. The script does not distinguish SSL error and DNS resolution error. The same hold true for #10518 #10519 #10520 and #10523. Do you want me to split them?

**Comment by J0WI** [comment]
Split into which categories?

**Pull request closed without merging**
