### PR TITLE
added rule for ioquake3

### PR DESCRIPTION
**Pull request by magicgoose**

### CODE REVIEW

**Comment by J0WI** [comment]
Please also check:
mobile.ioquake3.org
mumble.ioquake3.org
master.ioquake3.org
server.ioquake3.org
smiletheory.ioquake3.org
wiki.ioquake3.org

Our styleguide requires tabs to indent lines.

**Comment by J0WI** [comment]
ping @magicgoose

**Comment by magicgoose** [comment]
@J0WI 
I officially refuse to use tabs because [doing so would reduce my salary](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/), but you are free to replace indentation, it must be easy. 😄

**Comment by J0WI** [comment]
@gloomy-ghost @jeremyn I've added my own changes here. Let's finish this PR.

**Comment by jeremyn** [comment]
- [ ] Add `target` for https://upd.ioquake3.org

**Comment by J0WI** [comment]
Done.

**Pull request merged**
