### PR TITLE
Create Douyu.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. Please:

Note as `Invalid certificate`:
- [ ] https://douyu.com
- [ ] https://pay.douyu.com
- [ ] https://capi.douyucdn.cn

Note as 'Timeout':
- [ ] https://wan.douyu.com
- [ ] https://image.wan.douyu.com

Note as 'Refused'
- [ ] https://tc-tct.douyucdn.cn

Also:
- [ ] Move `www.douyu.com` above `staticyb.douyu.com`. (Generally, `^` and `www` should go at the top of any list.)

**Comment by jeremyn** [comment]
I've updated the checklist through 3c8a454c8c762152f545f7d3a3165d260c637f95. Everything is checked off, but please delete the old `Redirect to http:` comments [here](https://github.com/renyouguo/https-everywhere/blob/3c8a454c8c762152f545f7d3a3165d260c637f95/src/chrome/content/rules/Douyu.xml#L14-L17).

**Comment by renyouguo** [comment]
@jeremyn Sorry!

**Comment by jeremyn** [comment]
That's fine, thanks. Merged.

**Pull request merged**
