### PR TITLE
added Gutefrage.net.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Regarding the stats on alexa and the fact, that this popular host doesn't use https by default, it's worth to have this in next release.

**Comment by fuglede** [comment]
The exclusion pattern is non-functional since www.gutefrage.net is not among the target hosts; I think you intended to add that one as well?

Some other resources, besides /js/, that appear to be securable, are /images/, /login, /serviceapi, and /favicon.ico.

**Comment by J0WI** [comment]
I skipped `serviceapi` becaue the host doesn't return a 2xx response.
It's odd that our tests require test urls that are not redirected.

**Comment by fuglede** [comment]
Yeah, I'm not actually sure, what the logic behind that is (and I couldn't seem to find a description in the code after having had a brief look), but as you've probably also noted, they're not actually checked in the checker runs.

**Pull request merged**
