### PR TITLE
Add Wahiduddin.net.xml

### PR DESCRIPTION
**Pull request by jeremyn**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
http://mail.wahiduddin.net says "Please visit: http://wahiduddin.net", and https://mail.wahiduddin.net shows https://wahiduddin.net after ignore the mismatch error. Would it be abandoned? I think at least we can add a securecookie for wahiduddin.net.

**Comment by jeremyn** [comment]
I'm not sure what you're asking for with `mail`, could you please be more specific? Also I don't want to add a `securecookie` for `wahiduddin.net` while there are certificate problems at https://mail.wahiduddin.net.

**Comment by gloomy-ghost** [comment]
It seems like that `mail.` doesn't function properly anyway, so I think the certificate issue on `mail.` can be ignore while considering a `securecookie`.

**Comment by jeremyn** [comment]
The site owner runs an [email newsletter](http://wahiduddin.net/saki/) and it's possible that the `mail` subdomain is important for that in some way we don't know about, so I don't think we should ignore `mail`.

**Comment by gloomy-ghost** [comment]
alright, merging

**Pull request merged**
