### PR TITLE
Update torrentdownloads.me.xml

### PR DESCRIPTION
**Pull request by koops76**
#12151

### CODE REVIEW

**Comment by terrorist96** [comment]
@koops76 for some reason navigating to http://www.torrentsdownload.co/ doesn't redirect to https even though this rule was updated. Do you think why?

**Comment by J0WI** [comment]
This rule is only for `torrentsdownloads.co` (plural).

**Comment by terrorist96** [comment]
@J0WI ah, thanks! That's confusing. Going to `torrentdownloadS.co` redirects to `torrentSdownload.co` so this should be updated.

**Comment by J0WI** [comment]
You're welcome to open an issue or a PR :)

**Pull request merged**
