### PR TITLE
New rules for BME university main sites.

### PR DESCRIPTION
**Pull request by hzsolt94**
Rules for using Budapest University of Technology and Economics sites over https.

### CODE REVIEW

**Comment by hzsolt94** [comment]
This is my first rule contribution, please let me know if I need to fix anything. Thanks.

**Comment by J0WI** [comment]
Thanks for contributing to HTTPS-Everywhere!
In our [ruleset style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) we documented an easy way to find even more subdomains. Please have a look at it.

Please also be consistent in your code style. We prefer to use tabs.

**Comment by hzsolt94** [comment]
Updated the domain names. Please note that bme.hu is a large university domain, so it's nearly impossible to list all the sites, but I've done my best. 
Also updated style to use tabs wherever possible.

**Comment by J0WI** [comment]
Thanks a lot for updating the list!

Sadly a few hosts sends an incomplete certificate chain, which is problematic:
mit.bme.hu
teteny.bme.hu
www.teteny.bme.hu
uszoda.teteny.bme.hu
tir.teteny.bme.hu
ihfs.teteny.bme.hu
cs.bme.hu
www.cs.bme.hu

Please remove those targets and add a comment on the top documenting the issues on these hosts.

**Comment by hzsolt94** [comment]
Could you please inform me how to check for an incomplete chain in the future? My browser accepted all these sites ‎by default.I'll do the update, and document all the problems (redirections, missing sites, chain errors) in the comments.                                                                                                                                                                                                                From: J0WI‎Sent: Wednesday, 13 July 2016 15:02‎To: EFForg/https-everywhereReply To: EFForg/https-everywhereCc: Herczeg Zsolt; AuthorSubject: Re: [EFForg/https-everywhere] New rules for BME university main sites. (#5605)Thanks a lot for updating the list!

Sadly a few hosts sends an incomplete certificate chain, which is problematic:
mit.bme.hu
teteny.bme.hu
www.teteny.bme.hu
uszoda.teteny.bme.hu
tir.teteny.bme.hu
ihfs.teteny.bme.hu
cs.bme.hu
www.cs.bme.hu

Please remove those targets and add a comment on the top documenting the issues on these hosts.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by J0WI** [comment]
The problem is described in https://github.com/EFForg/https-everywhere/pull/2668#issuecomment-134683296
I usually use curl and SSL Labs to verify.

**Comment by hzsolt94** [comment]
However I understand the problem with incomplete cert chains, I would still prefer to use these sites over https. Is there a way to still include them in the rule sets, while conforming to EFF requirements? I found no documentation on this topic, but there is an `default_off="missing certificate chain"` option in the rulesets.

Is it a good practice, to include two rulesets in the file, one for the fully working, domains, and another for the broken domains with default_off? Are the  @J0WI Could you please give me an advice on this?

I'll also try to get in touch with the administrators of the broken sites, but it's not always possible to do that.

**Comment by J0WI** [comment]
> Is it a good practice, to include two rulesets in the file, one for the fully working, domains, and another for the broken domains with default_off? Are the @J0WI Could you please give me an advice on this?

Yes, that would be perfect. But make sure that you mention the relation between them in comments, that we are aware of in future.

**Comment by hzsolt94** [comment]
I just noticed that the test system is not capable of handling more than one ruleset in one file, so I split the rulesets to two files. Hopefully, the comments will explain the situation to anyone editing in the future.

**Comment by J0WI** [comment]
Thank you, looks great!

**Pull request merged**
