### PR TITLE
add rule for SpeedBurger.com

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
wrong content is served on speed-burger.com over https (redirects on http).

**Comment by numismatika** [comment]
^ is rewritten to www which works fine here.
Where exactly did you get a problem?

**Comment by J0WI** [comment]
Could you document that?
Also `-` don't need to be escaped. Please also add trailing slashes to the urls.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
