### PR TITLE
Add Staszic XIV LO rule

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
Didn't know it is in the top-1m...

Anyway, would be good to have those rules mered because they support, but don't redirect to HTTPS and get some resources from HTTP (They put the complete HTTP URL :P)

**Comment by J0WI** [comment]
Please have a look at https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by mimi89999** [comment]
@J0WI I updated the PR.

**Comment by J0WI** [comment]
I can still find much more subdomains over search engines. Are you also aware of [this](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts) practice?

**Comment by jeremyn** [comment]
@mimi89999 Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @mimi89999 . I've noted `staszic.waw.pl` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353125131` in case someone else wants to make a pull request for this domain.

**Pull request closed without merging**
