### PR TITLE
Make trivial rule for gobot.io

### PR DESCRIPTION
**Pull request by jish**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset! Please remove the target for `www.gobot.io`, because that domain doesn't exist. Also, make sure to squash all changes into one commit.

**Comment by jish** [comment]
Whoops, sorry about that. I have updated this branch to remove the `www.` target.

**Comment by jeremyn** [comment]
Thanks! Can you do one more thing? Please add a properly-indented [securecookie tag](https://www.eff.org/https-everywhere/rulesets#secure-cookies) like:

```xml
<securecookie host=".+" name=".+" />
```

I'm sorry to come back to you twice to make changes on a simple rule.

**Comment by jish** [comment]
Added the `<securecookie>` tag.

**Comment by jeremyn** [comment]
Thanks again!

**Pull request merged**
