### PR TITLE
Added rules for bmvg.de.

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Rejected`:
- [ ] https://www.eng.bmvg.de
- [ ] https://seminare.bmvg.de
- [ ] https://www.seminare.bmvg.de
  
Also:
- [ ] Add `target` for https://bmvg.de and remove the `Mismatch on ^` comment
- [ ] Change the `ruleset` `name` to `BMVg.de` or `BMVG.de`
- [ ] Change the filename to `BMVg.de.xml` or `BMVG.de.xml` including the reference in `Verwaltung_Online.xml`

**Comment by jeremyn** [comment]
Actually please go ahead and sort that whole list in `Verwaltung_Online.xml`, if you don't mind.

EDIT: Like this (to prevent confusion over lower-case/upper-case or sorting from the left or the right):
```
	- bbk.bund.de.xml
	- BMVg.de.xml
	- Bundesministerium_des_Innern.xml
	- Bundesnachrichtendienst.xml
	- Federal-Office-for-Information-Security.xml
	- Federal_Office_of_Administration.xml
```

**Comment by jeremyn** [comment]
It looks like the version of `Verwaltung_Online.xml` in this PR is old. Try this instead, and please double check that I got it right:
```
	- badv.bund.de.xml
	- bag.bund.de.xml
	- bakoev.bund.de.xml
	- baks.bund.de.xml
	- bbk.bund.de.xml
	- bbr.bund.de.xml
	- bbsr.bund.de.xml
	- BDBOS.bund.de.xml
	- bescha.bund.de.xml
	- bfe.bund.de.xml
	- Bundesamt_fuer_Kartographie_und_Geodaesie.xml
	- Bundesamt_fuer_Strahlenschutz.xml
	- Bundesministerium_des_Innern.xml
	- Bundesnachrichtendienst.xml
	- bvl.bund.de.xml
	- Federal-Office-for-Information-Security.xml
	- Federal_Office_of_Administration.xml
	- lernplattform-bakoev.bund.de.xml
	- Umweltbundesamt.de.xml
```

**Comment by jeremyn** [comment]
My list in my previous comment https://github.com/EFForg/https-everywhere/pull/9705#issuecomment-359533213 left out `BMVg.de`, which should be there and which you included. I've added it to my list.

Some of the indentation for your changes in `Verwaltung_Online.xml` is incorrect, for example you have a leading space and tab in front of have [`- badv.bund.de.xml`](https://github.com/Jochen-A-Fuerbacher/https-everywhere/blob/d9398f7a25399106b70de2af54daf974e8d7ff0c/src/chrome/content/rules/Verwaltung_Online.xml#L3). Please fix that.

**Comment by jeremyn** [comment]
Also, please rebase your changes to remove the merge conflicts.

**Comment by Jochen-A-Fuerbacher** [comment]
Thanks for your feedback. I rebased my changes.

**Comment by jeremyn** [comment]
As of https://github.com/EFForg/https-everywhere/pull/9705/commits/0c5146dc1bd3ea7ddf9b0d6181288ddbe9fc2354 the [`bag.bund.de.xml`](https://github.com/Jochen-A-Fuerbacher/https-everywhere/blob/0c5146dc1bd3ea7ddf9b0d6181288ddbe9fc2354/src/chrome/content/rules/Verwaltung_Online.xml#L4) line still has the space+tab indentation. Everything else looks okay.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
