### PR TITLE
added cash.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by fuglede** [comment]
The subdomain beta has some issues; for instance, https://beta.cash.ch/news/top-news/preise-zentren-kommen-unter-druck-428487?autostart=1 is broken. Aso, some content from disqus is blocked; is that a problem?

If you want to, some parts of the www domain, could be secured, cf. e.g. https://www.cash.ch/services/img/news/235/111057_Credit_Suisse_New_York_0.jpg.

**Comment by J0WI** [comment]
I thought about the static content on `www`, but I think it's not worth when they launch the new `beat`site soon.

The only problematic content is the video from simplex.tv. I 'll see if they fix this before the launch.

**Comment by fuglede** [comment]
Makes sense; do you want to remove the problematic domain or close/reopen this PR then to keep the backlog cleaner?

**Comment by J0WI** [comment]
I made an exclusion for now.

**Pull request merged**
