### PR TITLE
Create mondediplo.net.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
As requested in https://github.com/EFForg/https-everywhere/pull/8415#issuecomment-280950635.

### CODE REVIEW

**Comment by jeremyn** [comment]
See also [`MondeDiplo.com.xml`](https://github.com/EFForg/https-everywhere/blob/37d167ccc1539e9ba74bf662fdc793e9a31763af/src/chrome/content/rules/MondeDiplo.com.xml)

**Comment by jeremyn** [comment]
@Bisaloo We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by Bisaloo** [comment]
Yes, it's fine, you can squash-and-merge.

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Change the `ruleset` `name` to `MondeDiplo.net (partial)`
- [ ] Change the filename to `MondeDiplo.net.xml`
- [ ] When we have multiple rulesets related to one organization, we usually have one ruleset as the main one that points to all of the others, and all the others point to just the main one. In this case I think `MondeDiplo.com.xml` should be the main one because of how many working HTTPS domains it has. So please arrange it so `MondeDiplo.com.xml` points to the other files and the other files, including this one, point to it.
- [ ] Remove the `target` for `intra.mondediplo.net`. I'm uncomfortable with `target`s for domains that are internal to the organization because we can't really test them. You can either leave it out entirely or add it to the top domain marked `Internal`.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/8559/commits/cd7299ed04ec401ccfa753e499632de5427e261b.

About the references, I'm sorry that I wasn't more clear. What we want is to have exactly one ruleset point to the others and the others point to exactly one. We don't want each of the three to point to the other two. See [`ACLU.xml`](https://github.com/EFForg/https-everywhere/blob/403e25bfbf8fe29c06c60d6ed7b6b68cbbaf1e59/src/chrome/content/rules/ACLU.xml#L3-L30) and [`ACLU-of-Washington.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/ACLU-of-Washington.xml#L4) for an example of what I mean.

**Comment by jeremyn** [comment]
Thanks again, merged. I also deleted the intermediate commit messages when I squash-and-merged.

**Pull request merged**
