### PR TITLE
Add mindfactory.de

### PR DESCRIPTION
**Pull request by rzlourenco**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please make the following changes. For the first two groups, please add them into a comment at the top ([examples](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=problematic&type=Code)) marked with the given problem type.

`Different content`:
- [ ] https://blog.mindfactory.de

`Invalid certificate`:
- [ ] https://user.mindfactory.de

Add `target`:
- [ ] https://forum.mindfactory.de
- [ ] https://m.mindfactory.de
- [ ] https://mobile.mindfactory.de

**Comment by rzlourenco** [comment]
Whoops, I don't understand what I did, but had duplicate commits. Sorry for the unnecessary pings. I have added the commend and targets as you've asked.

**Comment by jeremyn** [comment]
That's fine. I've updated the checklist and added a couple more items.

Also, please don't squash your commits. Leaving them unsquashed makes it easier for me to review your changes. Instead, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits ourselves at the end, which means we combine your commits into one under your name. Is that all right with you for this and any other pull requests you submit?

**Comment by rzlourenco** [comment]
It is. I'll pay attention to squashing; this time I didn't exactly squash, but since I did something weird to the repository (had over 500 commits in the pull request) I just deleted it, recreated it, and added back the file.

**Comment by jeremyn** [comment]
Thanks, merged.

If you had some kind of glitch that spammed 500 commits into the repository, then it's fine that you didn't push them all. But -- just talking git strategy here -- depending on what was going on, maybe you could have `git reset --hard` to the remote and then re-edited? Anyway, it's fine.

**Comment by rzlourenco** [comment]
Thanks for the tip. I didn't understand what happened so I started clean because I didn't want to deal with it at the moment.

**Comment by jeremyn** [comment]
I totally understand that strategy, too.

**Pull request merged**
