### PR TITLE
Remove support for wildcard in the middle

### PR DESCRIPTION
**Pull request by Bisaloo**
#4369

### CODE REVIEW

**Comment by RReverser** [comment]
Ha, I just added this as a Python test locally, didn't notice the XML linter. This lint will run automatically just like any other tests, right?

**Comment by Bisaloo** [comment]
Yes, you can notice that the tests failed because of the rulesets that currently have a wildcard in the middle.

**Comment by RReverser** [comment]
Awesome, thanks for doing this.

**Comment by RReverser** [comment]
Can you please rerun the build to see how many are left to get this unblocked? I suppose only ones in https://github.com/EFForg/https-everywhere/issues/4369#issuecomment-326727385, but better to double-check.

**Comment by pipboy96** [comment]
Thanks @Bisaloo!

**Pull request merged**
