### PR TITLE
add static.lwn.net

### PR DESCRIPTION
**Pull request by pgerber**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your pull request, but please split this ruleset into two, one for the changes to `tocco.ch` and the other for the changes to `lwn.net`.

**Comment by jeremyn** [comment]
I know you're just making a small change, but this is a short ruleset so let's clean it up completely.

Please:

Mark these subdomains as `Invalid certificate` in a top comment, using the format you see [here](https://github.com/EFForg/https-everywhere/blob/03e4d70af7cdaee89acc803f6d65c46ab2d0d103/src/chrome/content/rules/Juno.com.xml#L1-L13) (and like in the example, don't include `https://` in the comment):
- [ ] https://tex.lwn.net
- [ ] https://vena.lwn.net

Also:
- [ ] Indent everything with one tab instead of spaces, following the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md).
- [ ] Delete the [blank line at the end](https://github.com/pgerber/https-everywhere/blob/e4452427717a0ee3773714510511938b0bb42895/src/chrome/content/rules/LWN.xml#L11).
- [ ] In all cases where there is a list of domains, sort them in alphabetical order starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group. For example:
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```
In this particular case, please move the `www.lwn.net` `target` directly below the `lwn.net` `target`.
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite changes in your name. Is that all right you with for this and any other pull requests you submit to us?

**Comment by pgerber** [comment]
I took a look at the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) and I noticed that the examples are sorted alphabetically, element by element, right to left, just the way you mentioned. However, I couldn't see any special treatment for `www`. To be honest I prefer it that way.

I do have access to a few DNS zone files and I'd like to generate the xml out of it. Sorting it that way makes that unnecessarily hard. Also, to me, having `www` out of order seems unnatural and harder to read.

Sorting without the www is far easier:
```
$ python3
>>> sorted(['www.example.net', 'a.example.net', 'example.net', 'www.example.com', 'b.example.com', 'www.a.example.com', 'b.a.example.com', 'a.example.com', 'example.com'], key=lambda i: i.split('.')[::-1])
['example.com', 'a.example.com', 'b.a.example.com', 'www.a.example.com', 'b.example.com', 'www.example.com', 'example.net', 'a.example.net', 'www.example.net']
```

Yes, you may squash-and-merge any pull request from me.

**Comment by jeremyn** [comment]
Thanks for making the extra changes.

The style guide is out of date, for example wildcard domains are almost entirely deprecated. I know the special handling for `www` is annoying. The decision to do special handling for `^`/`www` was I think made before I started participating here, but it's true these subdomains have special prominence (for example in HSTS preloading, see [here](https://hstspreload.appspot.com/)) so it's nice to have these pulled up front.

I submitted pull request https://github.com/aboul3la/Sublist3r/pull/38 to the Sublist3r domain-finder tool to have the output from that tool sorted in the way we like. Feel free to use [the sort function I added](https://github.com/aboul3la/Sublist3r/blob/46eba4b8bace50e4cba4feb74f78d7133f5a337e/sublist3r.py#L98-L135) in your own code, subject to Sublist3r's licensing is, of course.

Please feel free to create an issue to discuss this sorting rule if you like.

**Comment by pgerber** [comment]
I think I can live with the peculiar sorting for `www`.

I decided to implement the sorting in a slightly different way
```
>>> def sort_key(host):
...     if host.startswith('www.'):
...         return host.split('.')[:0:-1], 1
...     return host.split('.')[::-1], 0
... 
>>> sorted(['www.example.net', 'a.example.net', 'example.net', 'www.example.com', 'b.example.com', 'www.a.example.com', 'b.a.example.com', 'a.example.com', 'example.com'], key=sort_key)
['example.com', 'www.example.com', 'a.example.com', 'www.a.example.com', 'b.a.example.com', 'b.example.com', 'example.net', 'www.example.net', 'a.example.net']
```

**Comment by jeremyn** [comment]
Thanks, merged.

Your sorting approach is significantly simpler than mine. I encourage you to submit a pull request to https://github.com/aboul3la/Sublist3r to update the logic, or else I can do that with your permission.

For general reference and to save any other readers the effort, here is what the `sort_key` function transforms the sort into:

```python                                 
[                                                                          
    (['com', 'example'], 0),           # example.com                            
    (['com', 'example'], 1),           # www.example.com                        
    (['com', 'example', 'a'], 0),      # a.example.com                          
    (['com', 'example', 'a'], 1),      # www.a.example.com                      
    (['com', 'example', 'a', 'b'], 0), # b.a.example.com                        
    (['com', 'example', 'b'], 0),      # b.example.com                          
    (['net', 'example'], 0),           # example.net                            
    (['net', 'example'], 1),           # www.example.com                        
    (['net', 'example', 'a'], 0),      # a.example.net                          
]
```

**Comment by pgerber** [comment]
@jeremyn FYI, I submitted a  [pull request](https://github.com/aboul3la/Sublist3r/pull/56) to Sublist3r.

**Pull request merged**
