### PR TITLE
add rule for Ippen Digital

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
There is no host on www.idcdn.de

**Comment by numismatika** [comment]
yea there isn't, just copied it from the alternative name field of the cert.

**Comment by J0WI** [comment]
I wonder why this passed the tests @fuglede @jsha

**Comment by fuglede** [comment]
@J0WI: Because a run of https-everywhere-checker would have caused the issue, you mean? Adding such tests on a by-PR basis is the content of #3107.

**Comment by J0WI** [comment]
fetch-test.sh exposed the issue:

```
$ ./fetch-test.sh rules/IppenDigital.xml 
INFO Finished comparing http://idcdn.de/ -> https://idcdn.de/. Rulefile: rules/IppenDigital.xml.
INFO Finished comparing http://www.idcdn.de/ -> https://www.idcdn.de/. Rulefile: rules/IppenDigital.xml.
ERROR rules/IppenDigital.xml: Fetch error: http://www.idcdn.de/ => https://www.idcdn.de/: (6, 'Could not resolve host: www.idcdn.de')
INFO Finished in 1.30 seconds. Loaded rulesets: 1, URL pairs: 2.
```

**Comment by numismatika** [comment]
@J0WI second commit removes that host

**Pull request merged**
