### PR TITLE
Delete GO.com.xml

### PR DESCRIPTION
**Pull request by pipboy96**
Ruleset is extremely complex, effectively disabled (`platform="mixedcontent"`) and most of the website doesn't support HTTPS.

### CODE REVIEW

**Comment by J0WI** [comment]
With this removal we lost a lot of information and also some popular targets like `abc.go.com` :confused:

**Comment by pipboy96** [comment]
@J0WI These targets were effectively disabled for everyone anyway.

**Comment by J0WI** [comment]
There is a preference to enable all mixedcontent platform rules.

**Comment by pipboy96** [comment]
@J0WI Currently not even Tor Browser has MCB disabled, and disabling it greatly reduces security of HTTPS.

**Comment by J0WI** [comment]
I was referring to #9971

**Comment by pipboy96** [comment]
@J0WI I was going to discuss no longer treating mixedcontent breakage as "platform", but treat it simply as a broken ruleset, due to security implications of allowing active (or even passive, given the possibility of a 0day for "passive" formats like svg images) mixed content, and the fact Tor Browser now does not treat mixed content in a different way than normal browsers, and enabling active missing content is not an "official", easily enabled feature in either FF or Chromium (about:config in FF, console flag in Chromium).

**Comment by pipboy96** [comment]
Also the fact that we will most likely eventually make an actual interface for viewing all rulesets and enabling/disabling them without visiting the websites they are triggered on. Users can simply enable all broken rulesets with default_off reason being `mixedcontent` or similar if they want to.

**Comment by J0WI** [comment]
In fact HTTPS Everywhere can mitigate mixed content issues. The reason why they are disabled is because the browsers security feature block mixed content before we can rewrite the url to HTTPS:
https://www.eff.org/https-everywhere/rulesets#mixed-content-blocking-mcb
https://bugzilla.mozilla.org/show_bug.cgi?id=878890

There are concepts to fix this, but most unexpired users will just blame the extension or the browser to be broken:
https://bugzilla.mozilla.org/show_bug.cgi?id=1435733

The Tor Browser has a completely different security philosophy and blocks content such as JavaScript and SVGs entirely (depending on your [security level](https://tb-manual.torproject.org/security-slider/)).

**Comment by pipboy96** [comment]
@J0WI Currently the only way to both prevent mixed content and also try to fix it if possible is to enable EASE and disable all MCB. There's also an ugly way of doing something similar by injecting CSP headers into each response with `upgrade-insecure-requests` enabled.

**Comment by zoracon** [comment]
Generally, yes we accept MCB rules. The reason i deleted was due to the many non functional hosts and complex regex applied just to make it work. I'll gladly add this back in myself as a rule since it is a 1k coverage rule and I'll admit I missed that label in my review yesterday. I'll look into this domain and put up a PR later.

**Pull request merged**
