### PR TITLE
Create glitch.me.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**
http://concrete-hardboard.glitch.me/

### CODE REVIEW

**Comment by zoracon** [comment]
I don't normally promote wildcards but in this case where so many use Glitch.me, it fits in here. If you don't mind converting this to support the many `glitch.me` sites I think that would be more beneficial.

**Review by zoracon — CHANGES_REQUESTED** [review]
I don't normally promote wildcards but in this case where so many use Glitch.me, it fits in here. If you don't mind converting this to support the many glitch.me sites I think that would be more beneficial.

**Comment by pipboy96** [comment]
@TotalCaesar659 Use a wildcard! There are way too many domains to redirect individually (more than 1000).

**Review by zoracon — CHANGES_REQUESTED** [review]
Just need to add some tests for the wildcard.

Have a list here from enumerating the domain:
http://spiky-well-vein.glitch.me/
http://pwainstall.glitch.me
http://vyper.glitch.me

**Pull request closed without merging**
