### PR TITLE
Added new ruleset - Leancrew.com

### PR DESCRIPTION
**Pull request by RemakingEden**
Closes https://github.com/EFForg/https-everywhere/issues/17205

### CODE REVIEW

**Comment by RemakingEden** [comment]
I'm unsure exactly what this failure means 

`ERROR src/chrome/content/rules/Leancrew.com.xml: Fetch error: http://www.leancrew.com/ => https://www.leancrew.com/: (51, "SSL: no alternative certificate subject name matches target host name 'www.leancrew.com'")`

The certificate appears valid in my browser.

**Comment by pipboy96** [comment]
@RemakingEden Incomplete certificate chain.

**Comment by pipboy96** [comment]
https://github.com/EFForg/https-everywhere/commit/b73be23ed65a4dfd3bb803760f68e500b89bbdad

**Comment by KOLANICH** [comment]
Thank you.

**Pull request closed without merging**
