### PR TITLE
use Firefox latest stable(v35.0, CI build passed)

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by jsha** [comment]
There's a bug in Firefox 34 that causes a spurious test failure when using the addon-sdk. It's fixed in 35.

**Comment by PeterDaveHello** [comment]
Will test with v35 betas, thanks @jsha.

**Comment by jsha** [comment]
Actually I may have spoken too soon. It is definitely fixed in 37. I just tested 35 and got a failure. Haven't tried 36.

**Comment by PeterDaveHello** [comment]
But there is no 36, right?

**Comment by jsha** [comment]
Aha, I did not know that!

**Comment by PeterDaveHello** [comment]
Passed in v35.0!

**Pull request merged**
