### PR TITLE
nsICookieManager and OriginAttributes: fix issue #4241

### PR DESCRIPTION
**Pull request by bakulf**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Hainish Can you review this one, please?

**Comment by Hainish** [comment]
Reviewing now

**Comment by Hainish** [comment]
@bakulf currently a large portion of our users are on Tor Browser, the current version of which is derived from Firefox ESR (45.4.0esr).  Tor Browser >= 6.0 is using Firefox ESR >= 45.1.1esr.  It looks like the changes [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1259169) have not been backported to ESR, is that correct?

**Comment by Hainish** [comment]
I believe this PR would break for our TB users.

**Comment by bakulf** [comment]
You are right. If we want to be compatible with ESR, we cannot land this patch.
In this case, I suggest to keep the code as it is.
Alternatively we could add checks as: if ("originAttributes" in cookie) { cm.add(..., {});

**Pull request closed without merging**
