### PR TITLE
Use "Onion Service" instead of "Hidden Service"

### PR DESCRIPTION
**Pull request by strugee**
Tor Project upstream changed this terminology a while ago.

### CODE REVIEW

**Comment by strugee** [comment]
So, Travis failures are because I touched files with insufficient test coverage. Not sure if adding tests for onion service redirects makes sense though? They won't be reachable from Travis...

**Comment by J0WI** [comment]
We use a custom Docker container with torsocks installed, so Onion Services can be tested on Travis.

**Comment by pipboy96** [comment]
@zoracon there is some issue with travis not starting Tor correctly it seems. The rest of errors are from clearnet domains.

**Comment by zoracon** [comment]
@pipboy96 The fetch test for some of the domains in the rulesets are the causes
```
ERROR src/chrome/content/rules/Ritter.vg.xml: Fetch error: http://www.ritter.vg/ => https://www.ritter.vg/: (51, "SSL: no alternative certificate subject name matches target host name 'www.ritter.vg'")

ERROR src/chrome/content/rules/CoinPayments.net.xml: Fetch error: http://beta4474.coinpayments.net/ => https://beta4474.coinpayments.net/: (6, 'Could not resolve host: beta4474.coinpayments.net')

ERROR src/chrome/content/rules/CoinPayments.net.xml: Fetch error: http://www.coinpayments.com/ => https://www.coinpayments.com/: (51, "SSL: no alternative certificate subject name matches target host name 'www.coinpayments.com'")

ERROR src/chrome/content/rules/Protonirockerxow.onion.xml: Fetch error: http://protonirockerxow.onion/ => https://protonirockerxow.onion/: (7, 'Failed to receive SOCKS5 connect request ack.')

ERROR src/chrome/content/rules/FacebookCoreWWWi.onion.xml: Fetch error: http://developers.facebookcorewwwi.onion/ => https://developers.facebookcorewwwi.onion/: (7, 'Failed to receive SOCKS5 connect request ack.')
```

**Comment by pipboy96** [comment]
`Failed to receive SOCKS5 connect request ack.` is probably caused by Tor being not fully initialized at that point.

**Comment by zoracon** [comment]
> `Failed to receive SOCKS5 connect request ack.` is probably caused by Tor being not fully initialized at that point.

I'll check on `torsocks` in our Docker image

**Comment by pipboy96** [comment]
There may be more comments like this.

**Comment by cschanaj** [comment]
It seems that torsock is still not working on our docker image ... the same error persisted 

```Failed to receive SOCKS5 connect request ack.```

**Comment by pipboy96** [comment]
@zoracon IMO this is fine to merge even with travis issue since only thing we change is comments, and travis would fail on any .onion ruleset right now.

**Comment by ivysrono** [comment]
> 
> 
> @zoracon IMO this is fine to merge even with travis issue since only thing we change is comments, and travis would fail on any .onion ruleset right now.

+1

**Comment by pipboy96** [comment]
@ivysrono I guess I will make a PR that whitelists every .onion ruleset for now.

**Comment by pipboy96** [comment]
#18483 is needed for tests to pass.

**Comment by pipboy96** [comment]
Some of the rulesets need to also be updated.

**Comment by pipboy96** [comment]
Related: #18486, #18485, #18484.

**Pull request merged**
