### PR TITLE
Add rule for Cox & Kings International.

### PR DESCRIPTION
**Pull request by brainwane**
I had some trouble running the automated tests due to setup issues on my machine -- I think this works regardless.

### CODE REVIEW

**Comment by J0WI** [comment]
Please have a look at our docs to find some useful tips about subdomains:
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by jeremyn** [comment]
@brainwane

- [ ] Please make the ruleset look like this:

```xml
<!--
	Invalid certificate:
		ckgs.us

-->
<ruleset name="Ckgs.us">
	<target host="ckgs.us"/>
	<target host="www.ckgs.us"/>
	<target host="devnic.ckgs.us"/>
		<test url="http://devnic.ckgs.us/robots.txt" />
	<target host="in.ckgs.us"/>
	<target host="passport.in.ckgs.us"/>
	<target host="ta.ckgs.us"/>

	<rule from="^http://ckgs\.us/"
		to="https://www.in.ckgs.us/" />
	<rule from="^http:" to="https:" />
</ruleset>
```

It includes various improvements. Please let me know if you have any questions.

**Comment by jeremyn** [comment]
@brainwane Can we move forward on this one?

**Comment by brainwane** [comment]
Sorry for the wait, @jeremyn -- I'll do that this week.

**Comment by jeremyn** [comment]
@brainwane Can we finish this?

**Comment by brainwane** [comment]
@jeremyn I'm sorry - I was ill a lot of December. I will be working on this tomorrow and, I hope, revising it to be merge-ready!

**Comment by jeremyn** [comment]
@brainwane That's okay, I hope you're feeling better.

Just to be clear, my intention in https://github.com/EFForg/https-everywhere/pull/8174#issuecomment-347023661 was for you to literally replace what you have with what I gave you, so you shouldn't need to do much line-by-line editing. Of course you should feel free to ask any questions about the changes before you implement them, or if you disagree with something.

**Comment by brainwane** [comment]
Thanks @J0WI & @jeremyn -- I've revised the commit, and I've run the tests locally and verified the tests pass. I believe it's ready for re-review. Thanks @jeremyn for ensuring I understood what you meant, and sorry for misunderstanding you earlier!

**Comment by jeremyn** [comment]
@brainwane Thanks, merged.

Also, going forward, please don't check off items in my checklists yourself or otherwise edit other people's comments.

**Comment by brainwane** [comment]
@jeremyn Aha, I see, the checklist wasn't meant for the code submitter to check that off to indicate to you "yes, I've done this"? Thanks for the clarification! I wouldn't dream of editing others' comments but I hadn't played around with checklists-within-comments enough to realize that checklist-checking was a form of editing. Apologies!

**Comment by jeremyn** [comment]
@brainwane Don't worry about it. @wonderchook did the same thing, see https://github.com/EFForg/https-everywhere/pull/14015#issuecomment-352866820.

I make the checklists to make it clear to the contributor what needs to be done, and to give myself a list for what needs to be reviewed going forward. Non-collaborator contributors can't edit other people's comments, and so they can't check the items themselves, so it's usually not a problem.

**Pull request merged**
