### PR TITLE
More subdomains for Unizar.es.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
Great, lgtm.
Just two additional hosts: `maplicada.unizar.es` is also supported. `titulaciones.unizar.es` seems to be quite popular, but https is refused there.

**Comment by davidabian** [comment]
Done, @J0WI. Thanks again.

**Comment by J0WI** [comment]
Please also document `titulaciones.unizar.es`

**Comment by davidabian** [comment]
The problem is that there are too many subdomains like titulaciones which are not supporting HTTPS. Should we document all of them? :cry:

**Comment by J0WI** [comment]
Yes, this is for our atlas and future maintenance.

**Comment by davidabian** [comment]
Partially (but perhaps sufficiently) done.

**Comment by J0WI** [comment]
Awesome, thanks!

**Pull request merged**
