### PR TITLE
[ArXiv] Update ruleset

### PR DESCRIPTION
**Pull request by fuglede**
The entire site appears to work now. I've sent them a query regarding the possibility of re-enabling it by default.

### CODE REVIEW

**Comment by mhl10** [comment]
I can confirm that we enabled SSL site-wide very recently, so it would be OK to accept this pull request (which really we should have created, but you beat us to it ;-)). 

Thanks,
Martin
arXiv.org

**Comment by fuglede** [comment]
Hi Martin; cool that you're here. Even with this pull request, the ruleset is still disabled by default (meaning that users will not actually benefit from the added security unless they happen to notice that the ruleset is available). Would you also be okay with the ruleset being enabled by default again?

**Comment by mhl10** [comment]
Sorry, I overlooked that it was still disabled in the changeset. But yes, I'd be okay with it being enabled by default. Thanks for accelerating the process--it's been on my todo list!

**Comment by fuglede** [comment]
That's great; thanks.

**Comment by J0WI** [comment]
@fuglede could you document the mismatches on (de|fr|xxx)\.arxiv.org?

@mhl10 feel free to implement preloaded HSTS, that would make our rule obsolete :)

**Comment by fuglede** [comment]
@J0WI: Done.

**Pull request merged**
