### PR TITLE
Fix StatusPage.io and reenable by default

### LINKED ISSUE #1224: meta.statuspage.io gives untrusted certificate
StatusPage.io's status page is on Heroku, not their infrastructure. So connecting via TLS gives a certificate name mismatch.

This looks like just an overzealous wildcard. Easy to fix.

### PR DESCRIPTION
**Pull request by strugee**
Fixes #1224, #1226

### CODE REVIEW

**Comment by jsha** [comment]
Thanks for fixing this rule! We've introduced some new testing requirements for all modified rules, so I'd like to ask you for some additional help before merging. The automated tests give these errors:

```
ERROR src/chrome/content/rules/StatusPage.io.xml: Not enough tests (0 vs 1) for <Rule from '^http://blog\.statuspage\.io/' to 'https://status-page-blog.herokuapp.com/'>
ERROR src/chrome/content/rules/StatusPage.io.xml: Not enough tests (0 vs 1) for <Rule from '^http://meta\.statuspage\.io/' to 'https://metastatuspage.com/'>
ERROR src/chrome/content/rules/StatusPage.io.xml: Not enough tests (1 vs 2) for <Rule from '^http://([\w-]+\.)?statuspage\.io/' to 'https://\g<1>statuspage.io/'>
```

Which means you need to add some `<test url=...>` tags, per https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md and https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md.

Thanks,
Jacob

**Comment by strugee** [comment]
> Thanks for fixing this rule! We've introduced some new testing requirements for all modified rules, so I'd like to ask you for some additional help before merging.

Yeah, I saw the logs on Travis CI. I just haven't had the time/energy to fix them yet - but thanks for reaching out!

**Comment by strugee** [comment]
All right, I just pushed commits with tests, plus more URLs. \o/

All tests pass on my machine, so hopefully Travis reports OK.

**Comment by jsha** [comment]
Excellent, thanks for putting in the extra work to bring this rule up to date!

**Pull request merged**
