### PR TITLE
[MIT.xml] fix #14397

### LINKED ISSUE #14397: MIT personal websites are redirected to an incorrect URL
Type: ruleset issue
Domain: mit.edu

The ruleset in MIT.xml says this:

```xml
<rule from="^http://(www\.)?mit\.edu/" to="https://web.mit.edu/" />
```

This translates e.g. http://www.mit.edu/~cpitcla/test (which works) into https://web.mit.edu/~cpitcla/test (404).  Working HTTPS URLs for that page include https://www.mit.edu/~cpitcla/test (no need to rewrite the `www` part into `web`) and https://web.mit.edu/cpitcla/www/test (no `~`, extra `www`).

This is documented here: http://kb.mit.edu/confluence/pages/viewpage.action?pageId=3907090 .

It looks like the issue was introduced by https://github.com/EFForg/https-everywhere/pull/14169 or https://github.com/EFForg/https-everywhere/pull/12002 maybe?

```diff
+	<rule from="^http://(www\.)?mit\.edu/" to="https://web.mit.edu/" />
```

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
I guess you can just wrap the three `test`s in a comment, like this:

```xml
		<!-- should not get secured
		<test url="http://mit.edu/~puzzle/" />
		<test url="http://www.mit.edu/~puzzle/" />
		<test url="http://web.mit.edu/puzzle/www/" />
		-->
```

We don't really have anything like a "negative" test though.

**Comment by jeremyn** [comment]
https://github.com/EFForg/https-everywhere/pull/14417/commits/7c10f9b77c4926bc35b7643db7f69d436b1a468d is fine with me.

**Comment by J0WI** [comment]
Sure, we fixed this in #14290...

**Comment by varenc** [comment]
@J0WI @jeremyn this update seems to introduce a new problem.  Now http://web.mit.edu is rewritten to https://www.mit.edu which will fail for most people.  (but confusingly not for MIT students/staff)

MIT has a rather unique situation where the HTTPS version of its main web domains (web.mit.edu, www.mit.edu) can only be accessed by MIT affiliates with an MIT issued client cert.

Looking at this rule, it really seems like it should only match URLs that that start their path with "/files/" but from the debug logs I can confirm that this new rule is somehow matching `http://web.mit.edu`.  Logs:
image

even so, I think this rule should be deleted entirely because https on www.mit.edu and web.mit.edu is not working at all for the general public.  If you're an MIT affiliate trying to debug this, be sure to delete you client certs before testing.  (they're easy to get again at ca.mit.edu)

**Comment by J0WI** [comment]
Thanks, I've filled #16236

**Pull request merged**
