### PR TITLE
[Hft-leipzig] New ruleset

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by rugk** [comment]
Any news?

**Comment by rugk** [comment]
Any news?

**Comment by J0WI** [comment]
See also:
ilias.hft-leipzig.de
www1.hft-leipzig.de
moodle.hft-leipzig.de
stura.hft-leipzig.de
www.vba.hft-leipzig.de
qis.hft-leipzig.de
bibo.hft-leipzig.de
praktomat.hft-leipzig.de
venus.hft-leipzig.de
www.bpmn.hft-leipzig.de

**Comment by rugk** [comment]
Done

**Comment by J0WI** [comment]
You missed `bibo.hft-leipzig.de` and `www.bpmn.hft-leipzig.de`

**Comment by rugk** [comment]
Ah, yes, because they redirect. Now changed.

**Comment by J0WI** [comment]
Please fix the tests. You may add an exclusion and a valid test url for www1.

**Comment by rugk** [comment]
For now I just removed www1

**Comment by J0WI** [comment]
Okay, I'm fine with that.

**Pull request merged**
