### PR TITLE
add s*.imgs.cc

### PR DESCRIPTION
**Pull request by crackevil**

### CODE REVIEW

**Comment by crackevil** [comment]
need test coverage update

**Comment by jeremyn** [comment]
@crackevil Are you still interested in working on this?

**Comment by crackevil** [comment]
@jeremyn  As I have no more time on this, you can pick it up if you want

**Comment by jeremyn** [comment]
That's fine. I've noted `*.imgs.cc` in issue 3069 so someone else can do it, and I'm closing this pull request. For what it's worth, this pull request looks almost ready.

**Pull request closed without merging**
