### PR TITLE
Update Telegram.org.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
add securecookie for all

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by J0WI** [comment]
(!) This host does not send the preload header.

**Comment by jeremyn** [comment]
My response is [here](https://github.com/EFForg/https-everywhere/pull/7081#issuecomment-249433391).  Going forward I'll check for the `preload` header until we've come to some decision. Feel free to revert this change if you want.

**Comment by gloomy-ghost** [comment]
@J0WI Please be noticed that I did not remove anything in this PR

**Comment by jeremyn** [comment]
I've updated https://github.com/EFForg/https-everywhere/pull/7091#issuecomment-249433475 .

**Pull request merged**
