### PR TITLE
Unused rule MyComputer

### PR DESCRIPTION
**Pull request by jayvdb**
Related issues:  #17965 #12297 

From https://github.com/EFForg/https-everywhere/pull/18938

### CODE REVIEW

**Comment by cschanaj** [comment]
Similar to #19148, please remove the non-capturing group and replace the last rule with a trivial one `<rule from="^http:" to="https:" />`

**Comment by jayvdb** [comment]
@cschanaj, thanks for taking a look.  I've made the simplification enhancement to the rule, and I've used https://github.com/jonluca/Anubis and https://github.com/blark/aiodnsbrute to probe for other hosts, in order to justify not using `*.mycomputer.com`.

**Comment by pipboy96** [comment]
@jayvdb Try https://github.com/OWASP/Amass and https://github.com/aboul3la/Sublist3r.

**Comment by jayvdb** [comment]
Thanks @pipboy96 ; found two more valid hosts.

**Pull request merged**
