### PR TITLE
[ESET] Add subdomains

### PR DESCRIPTION
**Pull request by rugk**
Added subdomain *help.eset.com* and *ela.eset.com* and more...

### CODE REVIEW

**Comment by youdly** [comment]
Seems like Eset has many subdomains, why not simplify them into *.eset.com and then exclude non-functional subdomains.

**Comment by rugk** [comment]
Because you should avoid using wildcards. It's better to include every domain.
See https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by youdly** [comment]
Maintainer seems fine with wildcard though (https://github.com/EFForg/https-everywhere/pull/2279#issuecomment-123026249). Perhaps this ruleset doesn't have too many subdomains.

**Comment by rugk** [comment]
I also think in this case there are more domains which do not support HTTPS than those who do.

**Comment by rugk** [comment]
So is this mergeable now?

**Comment by rugk** [comment]
Anything which speaks against merging?

**Comment by fuglede** [comment]
Looks good to me. As a somewhat minor point: the targets of the original rulesets were ordered alphabetically, which made it a bit easier to navigate.

**Comment by rugk** [comment]
Ah okay. Nice time I'll pay attention to this.

**Pull request merged**
