### PR TITLE
Create telebasel.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by reedy** [comment]
I see some mixed content, are these ok?

**Comment by J0WI** [comment]
player is affected by mixed content.

**Comment by jsha** [comment]
Marking as needswork based on player being affected by mixed content. Let me know if that's incorrect.

**Comment by J0WI** [comment]
There is nothing more we can do here. The player requires resources that are only available over http. So I marked it with ```platform="mixedcontent"```

**Pull request merged**
