### PR TITLE
Create CardsAgainstHumanityStopsTheWall.com.xml

### PR DESCRIPTION
**Pull request by ihave100openPRs**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Add a reference from [`Cards_Against_Humanity.com.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Cards_Against_Humanity.com.xml) back to this ruleset.

**Comment by ihave100openPRs** [comment]
@jeremyn Thanks, added!

**Comment by jeremyn** [comment]
`CardsAgainstHumanityStopsTheWall.com.xml` should come before `HolidayBullshit.com.xml`, alphabetically. Can you fix that? I understand this is very minor.

**Comment by ihave100openPRs** [comment]
@jeremyn Sorry for that error, fixed now!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
