### PR TITLE
Add "block all mixed content" option

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by koops76** [comment]
ping @Hainish @cowlicks.

**Comment by cowlicks** [comment]
Hi @koops76 this pull request looks good! And blocking mixed content is the right thing to do!

However I believe this feature is already enabled by default in both chrome and firefox. So unfortunately, I don't think we should include this. Since it may end up conflicting with the existing browser features. And it adds additional maintenance overhead.

Thank you for working on this! Let me know if I missed anything.

**Comment by koops76** [comment]
@cowlicks This also blocks passive mixed content, Chrome doesn't have such option. Mozilla has it somewhere in about:config.

**Comment by koops76** [comment]
Why would I add a feature that is already implemented in all browsers?

**Comment by koops76** [comment]
@cowlicks Never mind.

**Pull request closed without merging**
