### PR TITLE
Create emailarchivestaskforce.org.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by pipboy96** [comment]
Please also try:

```
autodiscover.emailarchivestaskforce.org
ftp.emailarchivestaskforce.org
imap.emailarchivestaskforce.org
pop.emailarchivestaskforce.org
smtp.emailarchivestaskforce.org
```

**Comment by TotalCaesar659** [comment]
Amass 3.1.6 hasn't showed them to me.

**Comment by pipboy96** [comment]
@TotalCaesar659 Try adding `--active --brute` flags.

**Comment by TotalCaesar659** [comment]
Ah, thanks.

**Pull request merged**
