### PR TITLE
added rule for FrOSCon

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by fuglede** [comment]
Several of those targets serve only self-signed certificates. This includes froscon.de, www.froscon.org, helfer.froscon.org, feedback.froscon.org, feedback.froscon.de, and m.froscon.de.

**Comment by numismatika** [comment]
looks like a configuration problem on their side,
www.froscon.de serves a certificate that is valid for all those domains i mentioned.

**Comment by fuglede** [comment]
Quite possibly. In any case, do you want to update the PR to exclude the problematic domains?

**Comment by numismatika** [comment]
not yet, as their technicians are informed about the issue.

**Comment by numismatika** [comment]
@fuglede try again, it should be fixed now.

**Comment by fuglede** [comment]
Still appears to have a few problems:

	https-everywhere$ ./fetch-test.sh rules/FrOSCon.xml 
	INFO Finished comparing http://www.froscon.de/ -> https://www.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://froscon.de/ -> https://froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://www.froscon.org/ -> https://www.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://programm.froscon.org/ -> https://programm.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://programm.froscon.de/ -> https://programm.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://ruby.froscon.org/ -> https://ruby.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://ruby.froscon.de/ -> https://ruby.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://helfer.froscon.de/ -> https://helfer.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://helfer.froscon.org/ -> https://helfer.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://feedback.froscon.org/ -> https://feedback.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://feedback.froscon.de/ -> https://feedback.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://froglabs.froscon.org/ -> https://froglabs.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://froglabs.froscon.de/ -> https://froglabs.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://kids.froscon.de/ -> https://kids.froscon.de/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://kids.froscon.org/ -> https://kids.froscon.org/. Rulefile: rules/FrOSCon.xml.
	INFO Finished comparing http://m.froscon.de/ -> https://m.froscon.de/. Rulefile: rules/FrOSCon.xml.
	ERROR rules/FrOSCon.xml: Fetch error: http://www.froscon.org/ => https://www.froscon.org/: (60, 'SSL certificate problem: self signed certificate')
	ERROR rules/FrOSCon.xml: Non-2xx HTTP code: http://feedback.froscon.org/ (200) => https://feedback.froscon.org/ (404)
	ERROR rules/FrOSCon.xml: Non-2xx HTTP code: http://feedback.froscon.de/ (200) => https://feedback.froscon.de/ (404)
	INFO Finished in 27.52 seconds. Loaded rulesets: 1, URL pairs: 16.

**Comment by J0WI** [comment]
@numismatika are you still working here?

**Comment by numismatika** [comment]
https://www.froscon.org shows no self-signed cert here.
They didn't get back to me about the 404 on the feedback subdomains yet.

**Comment by fuglede** [comment]
Looks like the self-signed one was fixed indeed; [Travis is also happy with it](https://travis-ci.org/EFForg/https-everywhere/jobs/129580895#L607).

**Comment by numismatika** [comment]
feedback domains were removed, as they were removed from the dns as well.

**Comment by fuglede** [comment]
Thanks, LGTM.

**Pull request merged**
