### PR TITLE
Fix #4684

### LINKED ISSUE #4684: SigmaBeauty rule breaks Add to Bag functionality
http://www.sigmabeauty.com/spa-mat/p/bcm01

SigmaBeauty rule needs to be modified because it's breaking the Add to Bag functionality.

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also update a few other things here?
Our code style requires tabs and removing of non-capturing groups for readability. Forcing a redirect from ^ to www is not needed anyway since both support https.


There are also some more hosts:

Mismatch on:
blog.sigmabeauty.com
enews.sigmabeauty.com

WFM:
help.sigmabeauty.com

**Comment by J0WI** [comment]
Please add comments on the top of the file for the mismatching ones.
This will make maintenance easier.

**Comment by galeksandrp** [comment]
Added.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
