### PR TITLE
Add Ecosia.org rule

### PR DESCRIPTION
**Pull request by donced**
#1803

### CODE REVIEW

**Comment by blobgo** [comment]
This rule doesn't look as if it would exclude https://blog.ecosia.org/ and https://blog.ecosia.org...

**Comment by donced** [comment]
@blobgo exclusion is not necessary in this case because the rule "ecosia.org" "www.ecosia.org" don't apply to blog.ecosia.org. Only "*.ecosia.org" or (obviously) "blog.ecosia.org" would apply.

**Comment by blobgo** [comment]
Ah okay I overlooked this. So now all should be all right.

**Comment by blobgo** [comment]
Anything which speaks against merging this?

**Pull request merged**
