### PR TITLE
Create yash.osdn.jp.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**
https://github.com/EFForg/https-everywhere/issues/15750

### CODE REVIEW

**Comment by pipboy96** [comment]
Can you try making a ruleset that covers the entire `osdn.jp` domain?

**Comment by TotalCaesar659** [comment]
Is it good? It's redirecting to https://osdn.net/.

**Comment by pipboy96** [comment]
@TotalCaesar659 Please wait, I will try to create a ruleset.

**Comment by pipboy96** [comment]
`osdn.jp` has a wildcard DNS record and a wildcard certificate (it only covers `*.osdn.jp`, not `*.*.osdn.jp`).

**Comment by TotalCaesar659** [comment]
Do I need to re-create it or you'll do it?

**Comment by pipboy96** [comment]
@TotalCaesar659 Don't do anything right now.

**Comment by pipboy96** [comment]
There is already an `osdn.net` ruleset, I think these rulesets should be either linked together or merged.

**Comment by pipboy96** [comment]
I'm currently trying to make a list of all subdomains that are not a part of a wildcard record.

**Comment by pipboy96** [comment]
@TotalCaesar659 Don't worry, this should be mergeable as it is, I am currently trying to make a full ruleset though.

**Pull request merged**
