### PR TITLE
Add DPC Frontier.com.xml

### PR DESCRIPTION
**Pull request by gopherit**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please remove `CorneredCat.com.xml` from this pull request.

**Comment by gopherit** [comment]
@jeremyn What's the cleanest way to do this?  (Noob)

**Comment by jeremyn** [comment]
You can just delete `CorneredCat.com.xml` and git commit and push the change. We squash your commits into a single commit when we merge your changes.

**Comment by gopherit** [comment]
@jeremyn Figured out rebase.  Should be ready for you.  Thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
