### PR TITLE
[Island Savings] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks for your contribution! Please:

- [ ] Note `partners.islandsavings.ca` as `Invalid certificate` in a top comment.
- [ ] Add target `dashband.islandsavings.ca`

**Comment by lucaspetter** [comment]
Okay, new target and comment added. Thanks.

`partners.islandsavings.ca` appears valid in Chrome and Firefox, but [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=partners.islandsavings.ca&hideResults=on) reports an incomplete chain issue.

**Comment by gloomy-ghost** [comment]
Oops, then please add it to the top comment.

**Comment by lucaspetter** [comment]
Okay, comment updated.

To be clear, `dashband.islandsavings.ca` has no certificate or chain issues. `partners.islandsavings.ca` has a valid certificate but an incomplete chain.

**Comment by lucaspetter** [comment]
Added new targets found with Sublist3r.

**Comment by gloomy-ghost** [comment]
My fault, I was updating the list on my phone and pasted to a wrong line.

I can't find any test for `keepingitsimple.` but I'll merge it since it has a separated certificate.

**Pull request merged**
