### PR TITLE
Ruleset for SoFun.tw

### PR DESCRIPTION
**Pull request by wonderchook**
Initial creation of a ruleset for SoFun.tw

### CODE REVIEW

**Comment by wonderchook** [comment]
Oops, made a couple of git mistakes be back shortly.

**Comment by jeremyn** [comment]
This is the second `sofun.tw` PR you've created, along with https://github.com/EFForg/https-everywhere/pull/14022. It's best not to keep creating PRs like this, since we have so many already, and also it might confuse people who search the repository for `sofun.tw` in the future.

You shouldn't need to make a new PR to fix git problems. Worst case, you should be able to `git reset --hard` your branch to some commit before things went wrong, and then `git push --force` to the remote branch to reset things back to that commit.

Can you please reopen this PR instead of making a new one if/when you try again?

**Comment by wonderchook** [comment]
Hi @jeremyn sorry about that. Thanks for the git reminder. I am a little rusty. I'll use this one to get things finished up.

**Comment by wonderchook** [comment]
@jeremyn so I cleaned up my git history, though for some reason it is still insisting on adding this commit: https://github.com/EFForg/https-everywhere/commit/4f8a23f6be0744a0fcd04c1262c9bc87efde9f24


This doesn't really make sense to me, though what I should have done originally is create a new branch from master rather than branch from the previous branch where I made the Tripbaa ruleset.

**Comment by jeremyn** [comment]
Looking at your branch, you should be able to reset to an earlier form of master with something like:
```
$ git reset --hard 637d1f6cb7df0ba4a60183f84c62e74258edd669
$ git push --force origin SoFun.tw
```

If you want, I can try to fix it for you and then tell you the specific commands I used. Just check the "Allow edits from maintainers." box to the right.

**Comment by wonderchook** [comment]
@jeremyn thank you for the help. I was conflating two issues and what you suggested fixed both. This is ready for review, but I don't seem to be able to open the PR because of the force push.

**Comment by jeremyn** [comment]
The writer at https://gist.github.com/nikhita/6e4e59ae3c9d307688aff96c6054e5e5 suggests force-pushing the most recent commit you had in the PR before, in this case https://github.com/EFForg/https-everywhere/pull/14171/commits/c546f38afc507212656be26ddb26765bafd2b3ad, reopening the PR, and then force-pushing the new change. You could try that.

**Comment by wonderchook** [comment]
thank you! Learned a Github trick today. Will also not be closing pull requests like I did though.

**Comment by jeremyn** [comment]
Sure!

For your changes:
- [ ] Delete the extra tabs on the first line
- [ ] Delete the `test` for `photo`. We don't really need it because the response for https://photo.sofun.tw is a 200.

**Comment by wonderchook** [comment]
updated. 

So would the `test` only be used in situations where the route was not a 200?

**Comment by jeremyn** [comment]
When tests are needed, and when they aren't, is kind of a mess. In a recent PR at https://github.com/EFForg/https-everywhere/pull/14194#issuecomment-359265537 I asked a contributor to remove a test -- https://cdn.presslabs.com , test http://cdn.presslabs.com/wp-content/themes/presslabs/images/screenshots/dashboard.png -- but then in the next comment at https://github.com/EFForg/https-everywhere/pull/14194#issuecomment-359452711 I pointed out that in PR https://github.com/EFForg/https-everywhere/pull/14359 I merged with a test -- https://img.pornbb.org , test http://img.pornbb.org/images/logo/jan18.png (warning: NSFW) -- in a similar situation, so I let the contributor for PR #14194  decide whether to keep the test. (They kept it.)

So I guess in this case, if you really want to keep the `photos` test, that's fine, you can go ahead and add it back in. Otherwise this is ready to merge as it is.

**Comment by wonderchook** [comment]
I'm okay with it as is.

**Comment by jeremyn** [comment]
Okay thanks, merged.

**Pull request merged**
