### PR TITLE
[Kiva.org] Update and reactivate ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**
I slightly reduced the coverage but I didn't want to keep the over complicated rewrite rules. The removed subdomains are apparently not in use anymore anyways.

I also did not go through a full domain enumeration and rather used subdomains I could find in the source code.

### CODE REVIEW

**Comment by Bisaloo** [comment]
#10843

**Comment by koops76** [comment]
@Bisaloo I ran Sublist3r for you:
```
www.kiva.org
000www.kiva.org
0awww.kiva.org
0build.kiva.org
0www.kiva.org
1.kiva.org
100.kiva.org
11.kiva.org
12www.kiva.org
1ndioswww.kiva.org
1www.kiva.org
2.kiva.org
2012www.kiva.org
222.kiva.org
22www.kiva.org
25252fwww.kiva.org
252fs3-2.kiva.org
252fwww.kiva.org
28.kiva.org
2blog.kiva.org
2build.kiva.org
2fbuild.kiva.org
2fellowsblog.kiva.org
2ffellowsblog.kiva.org
2fl3-1.kiva.org
2fs3-1.kiva.org
2fs3-2.kiva.org
2fwww.kiva.org
2partners.kiva.org
2s3-2.kiva.org
2ww.kiva.org
2www.kiva.org
2zip.kiva.org
333.kiva.org
344fellowsblog.kiva.org
3awww.kiva.org
3dwww.kiva.org
3ewww.kiva.org
3www.kiva.org
4.kiva.org
40volunteers.kiva.org
413.kiva.org
447035909140www.kiva.org
4www.kiva.org
5www.kiva.org
6199050568www.kiva.org
6www.kiva.org
7.kiva.org
7build.kiva.org
7www.kiva.org
9.kiva.org
92www.kiva.org
98.kiva.org
aaa.kiva.org
abcd.kiva.org
about.kiva.org
account.kiva.org
action.kiva.org
admin.kiva.org
adwww.kiva.org
afroginafrica.kiva.org
also.kiva.org
andwww.kiva.org
annualreport.kiva.org
api.kiva.org
app.kiva.org
apps.kiva.org
aspmx.kiva.org
at.kiva.org
aww.kiva.org
awww.kiva.org
better.kiva.org
bit.kiva.org
blog.kiva.org
www.blog.kiva.org
bolstr.kiva.org
borrow.kiva.org
borrow-dev.kiva.org
browse.kiva.org
build.kiva.org
blog.build.kiva.org
bulgaria.kiva.org
business.kiva.org
businesses.kiva.org
cadeauxwww.kiva.org
cambodia.kiva.org
cause.kiva.org
cdn.kiva.org
cdn1.kiva.org
cell-phone.kiva.org
ceremony.kiva.org
certificate.kiva.org
charity.kiva.org
christians.kiva.org
cms.kiva.org
collaborate.kiva.org
talkshoe.com.kiva.org
community.kiva.org
company.kiva.org
irby.comwww.kiva.org
confluence.kiva.org
countries.kiva.org
cpages.kiva.org
credit.kiva.org
credits.kiva.org
cut.kiva.org
day.kiva.org
ddd.kiva.org
dejar.kiva.org
deletedwww.kiva.org
detroit.kiva.org
dev.kiva.org
www.dev.kiva.org
build.dev.kiva.org
blog.build.dev.kiva.org
fellowsblog.dev.kiva.org
kivablog.dev.kiva.org
vertex.dev.kiva.org
dev-vm-01.kiva.org
developer.kiva.org
difference.kiva.org
dinero.kiva.org
dir.kiva.org
discovered.kiva.org
dns.kiva.org
do.kiva.org
docl3-1.kiva.org
domainkey.kiva.org
download.kiva.org
dp1.kiva.org
dpreview-www.kiva.org
duringwww.kiva.org
dww.kiva.org
dwww.kiva.org
easier.kiva.org
eee.kiva.org
egotowww.kiva.org
email.kiva.org
o1.email.kiva.org
emerged.kiva.org
www.en.kiva.org
eww.kiva.org
ewww.kiva.org
ex.kiva.org
exist.kiva.org
existence.kiva.org
experts.kiva.org
familiarpages.kiva.org
fb1.kiva.org
www.fb1.kiva.org
admin.fb1.kiva.org
build.fb1.kiva.org
partners.fb1.kiva.org
fb2.kiva.org
www.fb2.kiva.org
admin.fb2.kiva.org
build.fb2.kiva.org
partners.fb2.kiva.org
featurebranch-qi.kiva.org
feelings.kiva.org
felloqsblog.kiva.org
fellowblog.kiva.org
fellowsblo.kiva.org
fellowsblog.kiva.org
few.kiva.org
file.kiva.org
fish.kiva.org
fr.kiva.org
free.kiva.org
ftp.kiva.org
giftwww.kiva.org
global.kiva.org
globe.kiva.org
go.kiva.org
www.go.kiva.org
hilbert.kiva.org
home.kiva.org
hooked.kiva.org
hrefquothttpwww.kiva.org
htp.kiva.org
htp--www.kiva.org
idsearch2011www.kiva.org
images.kiva.org
in.kiva.org
independence.kiva.org
inpages.kiva.org
internet.kiva.org
investments.kiva.org
jpegwww.kiva.org
kathywww.kiva.org
kiva.kiva.org
www.kiva.kiva.org
p.kiva.kiva.org
kiva--www.kiva.org
kivablog.kiva.org
kivafellowsblog.kiva.org
kivapedia.kiva.org
kokopelliwww.kiva.org
komunitu.kiva.org
l3-1.kiva.org
l3-2.kiva.org
later.kiva.org
launch.kiva.org
lebanon.kiva.org
lenders.kiva.org
lending.kiva.org
level3cdn.kiva.org
life.kiva.org
lifestyle.kiva.org
lifetime.kiva.org
likewww.kiva.org
www.prx.link.kiva.org
www.unblk.link.kiva.org
links.kiva.org
live.kiva.org
lives.kiva.org
liveswww.kiva.org
living.kiva.org
livingwww.kiva.org
loan.kiva.org
loaner.kiva.org
loanswww.kiva.org
lospicapiedra.kiva.org
lwww.kiva.org
media.kiva.org
menu.kiva.org
mmx.kiva.org
mobile.kiva.org
morewww.kiva.org
mx.kiva.org
mxx.kiva.org
my.kiva.org
n.kiva.org
naeema.kiva.org
nbsp.kiva.org
news.kiva.org
newsegpics-www.kiva.org
nolink.kiva.org
non-profits.kiva.org
not.kiva.org
notions.kiva.org
ns1.kiva.org
ns2.kiva.org
ns3.kiva.org
ns40.kiva.org
ns50.kiva.org
ns60.kiva.org
omaa.kiva.org
on.kiva.org
taalla.on.kiva.org
open.kiva.org
organizations.kiva.org
a.orgwww.kiva.org
kiva.orgwww.kiva.org
www.kiva.orgwww.kiva.org
origin.kiva.org
outnhttpswww.kiva.org
p.kiva.org
pages.kiva.org
pagewww.kiva.org
paginawww.kiva.org
panels.kiva.org
partners.kiva.org
partnership.kiva.org
partnerwww.kiva.org
passe.kiva.org
people.kiva.org
picture.kiva.org
piracy.kiva.org
placepages.kiva.org
platform.kiva.org
play.kiva.org
podcast.kiva.org
pop.kiva.org
poverty.kiva.org
premium.kiva.org
presentation.kiva.org
process.kiva.org
programs.kiva.org
qa.kiva.org
build.qa.kiva.org
blog.build.qa.kiva.org
kivablog.qa.kiva.org
qqq.kiva.org
qww.kiva.org
qwww.kiva.org
repaid.kiva.org
report.kiva.org
reports.kiva.org
results.kiva.org
returwww.kiva.org
s.kiva.org
s3.kiva.org
s3-1.kiva.org
s3-2.kiva.org
www.saiful.kiva.org
sblog.kiva.org
scalability.kiva.org
scale.kiva.org
scortsmurciagif.kiva.org
servicewww.kiva.org
site.kiva.org
smtp.kiva.org
sourcezip.kiva.org
speakers.kiva.org
sss.kiva.org
stage.kiva.org
store.kiva.org
secure.store.kiva.org
storywww.kiva.org
streams.kiva.org
styleguide.kiva.org
subdomain.kiva.org
summit.kiva.org
support.kiva.org
supporters.kiva.org
sv2.kiva.org
sv3.kiva.org
sv4.kiva.org
app-03.svc.kiva.org
sww.kiva.org
swww.kiva.org
systems.kiva.org
tarkoitukseen.kiva.org
teamwww.kiva.org
theexampleofwww.kiva.org
thewww.kiva.org
todaywww.kiva.org
towww.kiva.org
track.kiva.org
u00252fl3-1.kiva.org
ualesorientales.kiva.org
unique.kiva.org
us.kiva.org
www.us.kiva.org
use--www.kiva.org
usedpages.kiva.org
uswebsitewww.kiva.org
vewww.kiva.org
vip.kiva.org
visitwww.kiva.org
rate.visitwww.kiva.org
viva.kiva.org
volunteer.kiva.org
volunteerf.kiva.org
volunteerforum.kiva.org
volunteerportal.kiva.org
vvv.kiva.org
vww.kiva.org
vwww.kiva.org
w.kiva.org
ww.w.kiva.org
w2w.kiva.org
w2ww.kiva.org
w3w.kiva.org
w3ww.kiva.org
waw.kiva.org
waww.kiva.org
wdw.kiva.org
wdww.kiva.org
web.kiva.org
web-02.kiva.org
webmail.kiva.org
website.kiva.org
well.kiva.org
wew.kiva.org
weww.kiva.org
why.kiva.org
width.kiva.org
wiki.kiva.org
developers.wiki.kiva.org
wqw.kiva.org
wqww.kiva.org
wsw.kiva.org
wsww.kiva.org
wvw.kiva.org
wvww.kiva.org
ww.kiva.org
ww2.kiva.org
ww2w.kiva.org
ww3.kiva.org
ww3w.kiva.org
wwa.kiva.org
wwaw.kiva.org
wwd.kiva.org
wwdw.kiva.org
wwe.kiva.org
wwew.kiva.org
wwiw.kiva.org
wwq.kiva.org
wwqw.kiva.org
wws.kiva.org
wwsw.kiva.org
wwv.kiva.org
wwvw.kiva.org
www2.kiva.org
www3.kiva.org
wwwa.kiva.org
wwwe.kiva.org
wwwq.kiva.org
wwws.kiva.org
wwwv.kiva.org
www.wwwv.kiva.org
wwww.kiva.org
wwwww.kiva.org
x.kiva.org
x2fwww.kiva.org
x3ewww.kiva.org
xm.kiva.org
www.allows.xyz.kiva.org
you.kiva.org
yourwww.kiva.org
zip.kiva.org
zip-dev.kiva.org
```

**Comment by koops76** [comment]
@Bisaloo I guess it can't be done without wildcards.

**Comment by Bisaloo** [comment]
I know, I ran `Sublist3r` myself but didn't feel like testing all those subdomains given that most of them are probably obsolete.

**Comment by koops76** [comment]
@Bisaloo Check which of them listen on port 443.

**Comment by cschanaj** [comment]
Note that `*.kiva.org` has a wildcard DNS record,  anything like `http://eff-https-everywhere-issue-10232.kiva.org` works. 

https://dns.google.com/query?name=*.kiva.org&type=A&dnssec=true

**Comment by J0WI** [comment]
I think some imported ones should be added anyway:
```
api.kiva.org
blog.kiva.org
build.kiva.org
fellowsblog.kiva.org
go.kiva.org
media.kiva.org
store.kiva.org
us.kiva.org
```

**Comment by J0WI** [comment]
@Bisaloo please have a look at Travis.

**Pull request merged**
