### PR TITLE
Added derpibooru.org and derpicdn.net

### PR DESCRIPTION
**Pull request by BlacklightShining**

### CODE REVIEW

**Comment by jsha** [comment]
Per the new [ruleset testing](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md) requirements and [ruleset style](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) guide, can you change this rule to list specify hosts in the target hosts, rather than wildcards?

Thanks,
Jacob

**Comment by BlacklightShining** [comment]
@jsha There aren't any, besides `*.derpicdn.net`. It seems to me that this one should stay a wildcard, in case more subdomains are added later. As far as I know, Derpibooru has full TLS support (except on its `news.` subdomain, which points to Tumblr servers).

**Comment by jsha** [comment]
Sounds great, thanks!

**Comment by BlacklightShining** [comment]
You're welcome. :)

**Pull request merged**
