### PR TITLE
Create lovebizhi.com.xml qdcdn.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Comment by jeremyn** [comment]
`lovebizhi.com.xml`:

Mark as `Mixed content`:
- [ ] https://open.lovebizhi.com (and remove `target`)

Also:
- [ ] Delete [this](https://github.com/gloomy-ghost/https-everywhere/blob/d29d18ab7f08d0b66b2b367b00a439478278675c/src/chrome/content/rules/lovebizhi.com.xml#L2-L4), or at least make the relationship between these two domain sets more clear.
- [ ] Sort `haoma` correctly

`qdcdn.com.xml`:

- [ ] Order the error categories alphabetically

**Comment by gloomy-ghost** [comment]
https://open.lovebizhi.com sends a HSTS header...

**Comment by jeremyn** [comment]
You're right, it looks like they're forcing HSTS for https://open.lovebizhi.com/ when it doesn't work correctly with HTTPS. Not a good idea.

`open` should be in the ruleset somewhere though, either as a comment or a `target`. Please add it whichever way you think is better.

**Comment by jeremyn** [comment]
@gloomy-ghost What's the status here?

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
