### PR TITLE
[Nicereply.com] Fix securecookie

### PR DESCRIPTION
**Pull request by rugk**
Sorry, did not saw this error in https://github.com/EFForg/https-everywhere/pull/3191

### CODE REVIEW

**Comment by semenko** [comment]
Good call -- we should add this to our test suite.

**Comment by rugk** [comment]
Indeed this would be a good thing especially as I [fixed some rulesets](https://github.com/EFForg/https-everywhere/pull/3188) which contained this mistake recently.

**Comment by semenko** [comment]
Cool -- feel free to submit a PR for a test :smiley_cat:

**Comment by rugk** [comment]
It's better someone else does it who has more knowledge of Travic CI tests and such things. :smiley:

**Pull request merged**
