### PR TITLE
Create new ruleset for AquilaClothing.co.uk

### PR DESCRIPTION
**Pull request by ajhaydock**
Committing on behalf of a friend.

HTTPS fully supported on this newly set-up site.

### CODE REVIEW

**Comment by semenko** [comment]
Thanks! :+1:

**Comment by semenko** [comment]
Oops, looks like the WWW dns is sad :/

**Comment by ajhaydock** [comment]
Thanks for checking. Should be fixed now. :)

Still just a default Wordpress template for the time being, but the site is under development.

**Comment by TheNavigat** [comment]
LGTM

**Pull request merged**
