### PR TITLE
Add Gopro.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Remove entirely:
- [ ] https://dev.gopro.com (not in DNS)
- [ ] https://cbcdn1.staging.gp-static.com (not in DNS)
- [ ] https://cbcdn2.staging.gp-static.com (not in DNS)

Add `target`:
- [ ] https://g.gopro.com (and remove from top comment)
- [ ] https://investor.gopro.com (and remove from top comment)
- [ ] https://thumbnails.gp-static.com (and remove from top comment and add `test` https://thumbnails.gp-static.com/copyright-policy )

Add `test`:
- [ ] https://assets-aem.gopro.com/robots.txt
- [ ] https://cbcdn1.gp-static.com/robots.txt
- [ ] https://cbcdn2.gp-static.com/robots.txt
- [ ] https://cbcdn3.gp-static.com/robots.txt
- [ ] https://cbcdn4.gp-static.com/robots.txt

Also:
- [ ] Fix the sorting, there are some minor problems such as `help.quik.gopro.com` before `investor.gopro.com`, the `*.shop.gopro.com` `target`s after `zh.gopro.com`, and `assets.gp-static.com` after `cbcdn4.gp-static.com`

**Comment by J0WI** [comment]
Done.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9102/commits/7c4c7ac41dd11fcdbb1584e0b140e21e0feab34a.

You added a `test` for http://assets.gp-static.com/robots.txt instead of https://assets-aem.gopro.com/robots.txt . `assets` doesn't need the test because the root URL is a `200`, and in fact `robots.txt` returns a `404`, so please remove that `test`.

**Comment by J0WI** [comment]
That's now fixed.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
