### PR TITLE
removed obsolete VK-ols.xml and add userapi.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
For `userapi.com.xml`, can we just do a left-hand wildcard `<target host="*.userapi.com" />`? I've tried some subdomains like https://foo.userapi.com and they seem to work.

**Comment by J0WI** [comment]
I found some issues on content that is served there, e.g. on cs6183.userapi.com https does not work.

**Comment by J0WI** [comment]
Firefox build is broken because of #6489.
Rule tests passed.

**Comment by jeremyn** [comment]
https://cs[0-9]?.userapi.com all work. https://cs10.userapi.com is unable to connect. https://cs11.userapi.com is a mismatched certificate.

I'm not sure what to recommend. What do you think?

**Comment by J0WI** [comment]
I'm not sure because I didn't found any test domains for them.

**Comment by jeremyn** [comment]
I consider https://cs1.userapi.com/ itself a valid test domain, but let's be cautious and leave them out, especially for a high profile site like this.

**Pull request merged**
