### PR TITLE
Update LinuxTag.org.xml (cacert)

### PR DESCRIPTION
**Pull request by cschanaj**
#9582 
```xml
<!--
	Non-functional hosts
		Couldn't connect to server:
		- hacking.linuxtag.org

		Timeout was reached:
		- eticket.linuxtag.org
		- mailtest.linuxtag.org

		Incomplete certificate chain error:
		- linuxtag.org
		- www.linuxtag.org
		- intern.linuxtag.org
		- mail.linuxtag.org
		- newsletter.linuxtag.org
		- openmusic.linuxtag.org
		- planet.linuxtag.org
		- ssl.linuxtag.org
		- staging.linuxtag.org
		- svn.linuxtag.org
		- vcc.linuxtag.org
		- wiki.linuxtag.org
-->
```

### CODE REVIEW

**Comment by J0WI** [comment]
I think the cert chain has been fixed. Otherwise I would still like to keep it as a `default_off` rule.

**Comment by cschanaj** [comment]
@J0WI I still get the incomplete certificate chain error using `curl`. Let's keep this default off.

**Comment by J0WI** [comment]
I also used curl to test them, but maybe the results are not consistent. Let me make some further tests.

**Comment by J0WI** [comment]
@cschanaj I made some tests, but I was not able to reproduce the chain issue.

**Comment by cschanaj** [comment]
I think the cert chain issues has been fixed. thanks!!

**Pull request merged**
