### PR TITLE
[RealFaviconGenerator.net] New ruleset

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by fuglede** [comment]
Looks good to me. A single piece of JS is being blocked on https://realfavicongenerator.net/donate but that's probably not a huge issue. I noticed that your indentation mixes spaces and tabs; that should be more uniform. Similarly, one rule is broken across two lines while another one is not.

**Comment by rugk** [comment]
I cannot see a JS blocked (anymore?) but yes, I just created this without much care, so here is my clean-up: https://github.com/EFForg/https-everywhere/pull/3081

**Comment by fuglede** [comment]
The blocked JS is http://coinwidget.com/widget/coin.js.

**Comment by rugk** [comment]
Oh yes, this was blocked by some add-ons in my case so I did not saw it.
But as it seems this is a known problem: https://github.com/scottycc/coinwidget.com/issues/10

**Pull request merged**
