### PR TITLE
[Microsoft] next-services.apps, support2, dgps.support

### PR DESCRIPTION
**Pull request by fuzzyroddis**

### CODE REVIEW

**Comment by StevenRoddis** [comment]
I'll assume this is waiting for `<test>`s?

**Comment by jsha** [comment]
Yep!

**Comment by StevenRoddis** [comment]
Not done yet but need help finding tests for:

```xml
	<rule from="^http://([\w-]+)\.sec\.s-msft\.com/"
		to="https://$1.sec.s-msft.com/" />
```
I have only found
download-codeplex.sec.s-msft.com

**Comment by jsha** [comment]
I was also only able to find that one hostname. You can replace that rule with a more specific one. I only checked Google. Sometime Wolfram Alpha is also helpful - there is a subdomains tab if you search for a domain name.

**Comment by StevenRoddis** [comment]
Cool, I'll get back working on this.
I also use Alexa too to help find subdomains.

**Comment by semenko** [comment]
Looks like our tests are failing on this PR -- and it hasn't been updated in a while. I'm going to close this for now, but if you'd like it merged, feel free to re-open. Thanks! :)

**Pull request closed without merging**
