### PR TITLE
Create dudu.ro.xml

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by zoracon** [comment]
These domains are failing:
```
ERROR src/chrome/content/rules/dudu.ro.xml: Fetch error: http://dudu.ro/ => https://dudu.ro/: (28, 'Operation timed out after 30001 milliseconds with 0 bytes received')

ERROR src/chrome/content/rules/dudu.ro.xml: Fetch error: http://www.dudu.ro/ => https://www.dudu.ro/: (28, 'Operation timed out after 30002 milliseconds with 0 bytes received')
```

**Comment by TotalCaesar659** [comment]
Do I need to close this PR? The site had worked when I created it, I guess.

**Comment by pipboy96** [comment]
@TotalCaesar659 You may keep it, the website itself supports HTTPS, but it returns 404 now.

**Comment by TotalCaesar659** [comment]
OK then, If the site doesn't awake in the future, I'll close it.

**Comment by pipboy96** [comment]
Adding `hold` tag to prevent accidental closing.

**Comment by ivysrono** [comment]
Error 522
Awake while the site re-work in the future.

**Pull request closed without merging**
