### PR TITLE
Add Miniclip.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Sublist3r shows a lot more domains than what you have here. Do you want to add some more? Or we could just mark this as `(partial)`.

**Comment by J0WI** [comment]
Are they all still in use?

**Comment by jeremyn** [comment]
I checked one at random, https://payments.miniclip.com , and it seemed okay. I'm not going to check all of them unless it's to review your work.

**Comment by J0WI** [comment]
Okay, let's go for the partial flag.

**Pull request merged**
