### PR TITLE
Create gama-gama.ru.xml

### PR DESCRIPTION
**Pull request by ekaris**

### CODE REVIEW

**Comment by ekaris** [comment]
@J0WI Some help here?

**Comment by jeremyn** [comment]
https://www.gama-gama.ru has what we call an `incomplete certificate chain`. You can see this by creating a new profile in Firefox and loading the HTTPS site there. You should see a `Your connection is not secure` page, and this under Advanced:

>www.gama-gama.ru uses an invalid security certificate.

>The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

>Error code: SEC_ERROR_UNKNOWN_ISSUER

This is a configuration problem for the site admin and not something you or HTTPS Everywhere can or should try to fix. You can't include www.gama-gama.ru as a target.

**Comment by jeremyn** [comment]
Thanks. Please:

Mark as `Certificate mismatch` in the top comment:
- [ ] https://testshop.gama-gama.ru

Mark as `Incomplete certificate chain` in the top comment:
- [ ] https://akella.gama-gama.ru
- [ ] https://cl.gama-gama.ru
- [ ] https://ipb.gama-gama.ru
- [ ] https://vtb.gama-gama.ru
- [ ] https://wtb.gama-gama.ru
- [ ] https://www.gama-gama.ru

Mark as `Timeout` in the top comment:
- [ ] https://ns2.gama-gama.ru

Add `target`:
- [ ] https://s.gama-gama.ru

Also:
- [ ] Remove [this `(www.)` comment](https://github.com/ekaris/https-everywhere/blob/4d7415fc5258697d875b2584bd3eb3c3f5d20e50/src/chrome/content/rules/gama-gama.ru.xml#L3)

(Be sure all additions are in alphabetical order.)

Finally, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means we rewrite your commits in your name. Is that okay with you for this and any other pull requests you submit to us?

**Comment by ekaris** [comment]
Yes, it is ok to squash-and-merge

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
