### PR TITLE
Update QQ.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@Hainish The check error is strange.

**Comment by renyouguo** [comment]
@J0WI @jeremyn @Hainish @fuglede 
Why the check gets strange errors then stop itself?

**Comment by fuglede** [comment]
0xE8 0x85 0xBE 0xE8 is 腾. Can that help explain anything?

**Comment by Hainish** [comment]
It looks like this is happening for http://t9.qlogo.cn/ -> https://t9.qlogo.cn/

I only see a blank page for that currently.  I'll try re-running and see if anything changes.

**Comment by renyouguo** [comment]
@fuglede QQ.com belongs Tencent company, which has the Chinese name: "腾讯".

**Comment by renyouguo** [comment]
@fuglede It gets different errors every time, and pass the check some time : https://travis-ci.org/EFForg/https-everywhere/builds/154747907

**Comment by renyouguo** [comment]
It seems not t9.qlogo.cn cause the error.

**Comment by renyouguo** [comment]
@fuglede @Hainish I have fixed errors. Please review it.

**Comment by renyouguo** [comment]
#6854

**Pull request closed without merging**
