### PR TITLE
Senate of Poland

### PR DESCRIPTION
**Pull request by J0WI**
Thanks to @jwilk  for the previous work

### CODE REVIEW

**Comment by jeremyn** [comment]
Both https://w.senat.gov.pl/ and http://w.senat.gov.pl/ don't connect for me, so that domain should be updated in the comment, but this looks good otherwise.

**Comment by J0WI** [comment]
I also replaced the `_` char in the file name, as our style guide recommends.

**Comment by jeremyn** [comment]
The comment for `ww.senat.gov.pl` was fine, you didn't need to remove it.

**Comment by J0WI** [comment]
oh, sure.

**Comment by jeremyn** [comment]
Thanks.

**Pull request merged**
