### PR TITLE
Create Play-asia.com.xml

### PR DESCRIPTION
**Pull request by cschanaj**
`*.play-asia.com` serves a valid certificate with left-wildcard.

### CODE REVIEW

**Comment by J0WI** [comment]
This rule will redirect everything on *.play-asia.com, including the hosts you listed as non-working.

**Comment by cschanaj** [comment]
It seems to me that those hosts having a certificate problem except `mail1new.play-asia.com` all redirect to `www.play-asia.com` when using a browser despite a HTTP 200 status code. So I guess that those host are not being used anymore. I am fine if the fist commit https://github.com/EFForg/https-everywhere/pull/7922/commits/e0a6f1c5a613c891f8f8772e95601a22c7597568 is merge instead of the current one https://github.com/EFForg/https-everywhere/pull/7922/commits/4c4c3bb35c57439a0c7e638890fc55890e2c96c1.

**Comment by J0WI** [comment]
Could you remove 4c4c3bb from this branch?

**Comment by cschanaj** [comment]
done.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
