### PR TITLE
Add rule for gitea.com

### LINKED ISSUE #19397: Please add gitea.com
Type: new ruleset

Domain: gitea.com

using the Tor-Browser you wont get redirected from http://gitea.com to https://gitea.com

### PR DESCRIPTION
**Pull request by 6543**
close  #19397

### CODE REVIEW

**Comment by 6543** [comment]
@ ivysrono do you have time to look at this?

**Comment by 6543** [comment]
@ivysrono do you have time to look at this?

**Comment by 6543** [comment]
@zoracon do you have time for a look at this?

**Comment by zoracon** [comment]
@6543 Yes, I can take a look today

**Comment by 6543** [comment]
@zoracon `api.gitea.com` is nothin official for now

**Comment by 6543** [comment]
@zoracon added and thanks that you had time to look at!

**Pull request merged**
