### PR TITLE
Rutracker.org recently introduced HTTPS

### PR DESCRIPTION
**Pull request by lemenkov**
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

### CODE REVIEW

**Comment by galeksandrp** [comment]
Version with national domains #4681

**Comment by lemenkov** [comment]
@galeksandrp you forgot about rutracker.net, and about www. sub-domains which should be redirected to domain. Please add and re-submit. I'll close mine pull-request in favor of yours.

**Comment by galeksandrp** [comment]
@lemenkov Done.

**Comment by lemenkov** [comment]
@galeksandrp looks good to me.

Closed in favor of #4681

**Pull request closed without merging**
