### PR TITLE
Delete Browser_Hacker.com.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
Gone from DNS.

#10595

### CODE REVIEW

**Comment by J0WI** [comment]
Can't confirm, WFM over https.

**Comment by Bisaloo** [comment]
@J0WI, strange. It's still gone from DNS for me. Are you talking about `^`, `www` or another subdomain?

**Comment by J0WI** [comment]
@Bisaloo  `$ curl -I https://www.browserhacker.com`

**Comment by Bisaloo** [comment]
Okay, it works with `curl` but no with firefox nor chromium. What does that mean?

This is just out of curiosity. I think it is a sufficient reason to close this PR.

**Pull request closed without merging**
