### PR TITLE
[Champaign County ACLU] New ruleset

### PR DESCRIPTION
**Pull request by galenide**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Remove some extra spaces: one line above and below [here](https://github.com/galenide/https-everywhere/blob/703da6e066576c8a8bb3791e8e312df454e71486/src/chrome/content/rules/Champaign-County-ACLU.xml#L3), and the extra space at the end of [this line](https://github.com/galenide/https-everywhere/blob/703da6e066576c8a8bb3791e8e312df454e71486/src/chrome/content/rules/Champaign-County-ACLU.xml#L7).
- [ ] Add a reference from `ACLU.xml` to the new ruleset.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7602/commits/44bb19e575e1acaa9a3721965bf3f836c87205e9 .

**Comment by galenide** [comment]
The space character after [this line](https://github.com/galenide/https-everywhere/blob/44bb19e575e1acaa9a3721965bf3f836c87205e9/src/chrome/content/rules/Champaign-County-ACLU.xml#L7) has been removed. At the same time, the directive to remove one line above and below [this line](https://github.com/galenide/https-everywhere/blob/44bb19e575e1acaa9a3721965bf3f836c87205e9/src/chrome/content/rules/Champaign-County-ACLU.xml#L3) is not totally clear. Does the directive mean to remove the blank line above [this line](https://github.com/galenide/https-everywhere/blob/44bb19e575e1acaa9a3721965bf3f836c87205e9/src/chrome/content/rules/Champaign-County-ACLU.xml#L3) and also the blank line below [this line](https://github.com/galenide/https-everywhere/blob/44bb19e575e1acaa9a3721965bf3f836c87205e9/src/chrome/content/rules/Champaign-County-ACLU.xml#L3)?

**Comment by jeremyn** [comment]
Part of the problem is that I think I miscounted the number of lines. I've updated the checklist and I'm sorry for the confusion. Please make it look like this:

```xml
<!--

	For other ACLU coverage, see ACLU.xml

	Problematic domains:
	- webmail.aclu-cu.org	(cert mismatch)

-->
```

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
