### PR TITLE
[Rage4] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
Next try of https://github.com/EFForg/https-everywhere/pull/2490
https://github.com/EFForg/https-everywhere/issues/2324

### CODE REVIEW

**Comment by rugk** [comment]
This PR is nearly one month old. :disappointed:

**Comment by fuglede** [comment]
Looks good to me; both domains serve 302 redirects to HTTPS. What's the logic behind removing the rules for royaldns.net though?

**Comment by rugk** [comment]
To put it into a new ruleset as https://royaldns.net/ has nothing to do with Rage4. :smiley:

**Comment by rugk** [comment]
In fact I seem to made a mistake in https://github.com/EFForg/https-everywhere/pull/2491 and added the wrong domain to the ruleset file.

**Comment by fuglede** [comment]
👍

**Pull request merged**
