### PR TITLE
[VCD.org] Disable broken subdomain

### PR DESCRIPTION
**Pull request by fuglede**
In particular, this fixes https://github.com/EFForg/https-everywhere/issues/5302

### CODE REVIEW

**Comment by J0WI** [comment]
Some more working hosts:
fahrradfoerderung.vcd.org
nrw.vcd.org
bw.vcd.org
tempo30.vcd.org
bildungsservice.vcd.org
stadtvonmorgen.vcd.org
aktivenforum.vcd.org

Mismatch:
www.portal.vcd.org

HTTP redirect:
portal.vcd.org

**Comment by Hainish** [comment]
@fuglede I'm doing a release this week hopefully.  If you can add these hosts @J0WI mentioned soon it'll make it into 5.2 https://github.com/EFForg/https-everywhere/issues/5629

**Comment by fuglede** [comment]
Updated.

**Comment by fuglede** [comment]
Whoops, `nrw` added. The subdomain `portal` was there already as a target host.

**Pull request merged**
