### PR TITLE
[Ancestry] Disable a few rules

### PR DESCRIPTION
**Pull request by fuglede**
This should fix the issues mentioned in #4742 -- unfortunately, one of those requires a user login, but based on the input provided in that GH issue, simply taking out the CORS issue-causing domain should do the job.

### CODE REVIEW

**Comment by J0WI** [comment]
Let us get rid of the wildcard.

Mismatches:
blogs.ancestry.com
shoebox.ancestry.com

Refused:
 (*.)?rootsweb.ancestry.com
search.ancestry.com
boards.ancestry.com
trees.ancestry.com
community.ancestry.com
home.ancestry.com

WFM:
support.ancestry.com
help.ancestry.com
health.ancestry.com

HTTP redirect:
corporate.ancestry.com

**Comment by fuglede** [comment]
Updated (along with a few other changes). The Travis failure appears to be negative:

	$ ./fetch-test.sh rules/Custhelp.com.xml 
	INFO Finished comparing http://appsconnect.custhelp.com/ -> https://appsconnect.custhelp.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://ora-fusion-apps.custhelp.com/ -> https://ora-fusion-apps.custhelp.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://www.custhelp.com/ -> https://www.rightnow.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://custhelp.com/foo -> https://www.rightnow.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://www.custhelp.com/foo -> https://www.rightnow.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://motorola-global-community.custhelp.com/ -> https://forums.motorola.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://motorola-global-community.custhelp.com/pages/afe9e9ba5d -> https://forums.motorola.com/pages/afe9e9ba5d. Rulefile: rules/Custhelp.com.xml.
	INFO Finished comparing http://custhelp.com/ -> https://www.rightnow.com/. Rulefile: rules/Custhelp.com.xml.
	INFO Finished in 34.66 seconds. Loaded rulesets: 1, URL pairs: 8.

**Comment by Hainish** [comment]
@fuglede I'm getting the same thing as travis:

```shell
(.venv) legind@EFF-420 ~/workspace/https-everywhere (fuglede-ancestry-patch) $ test/travis-ruleset-fetch.sh 
From https://github.com/EFForg/https-everywhere
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream-for-travis/master
Ruleset database has changed. Testing test URLs in all changed rulesets.
INFO Finished comparing http://secure.ancestry.co.uk/ -> https://secure.ancestry.co.uk/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://health.ancestry.com/ -> https://health.ancestry.com/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://help.ancestry.com/ -> https://help.ancestry.com/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://dna.ancestry.com/ -> https://dna.ancestry.com/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://store.ancestry.com/ -> https://store.ancestry.com/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://appsconnect.custhelp.com/ -> https://appsconnect.custhelp.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://support.ancestry.com/ -> https://support.ancestry.com/. Rulefile: src/chrome/content/rules/Ancestry.xml.
INFO Finished comparing http://ora-fusion-apps.custhelp.com/ -> https://ora-fusion-apps.custhelp.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://www.custhelp.com/ -> https://www.rightnow.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://custhelp.com/foo -> https://www.rightnow.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://www.custhelp.com/foo -> https://www.rightnow.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://motorola-global-community.custhelp.com/ -> https://forums.motorola.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://motorola-global-community.custhelp.com/pages/afe9e9ba5d -> https://forums.motorola.com/pages/afe9e9ba5d. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
INFO Finished comparing http://custhelp.com/ -> https://www.rightnow.com/. Rulefile: src/chrome/content/rules/Custhelp.com.xml.
ERROR src/chrome/content/rules/Custhelp.com.xml: Fetch error: http://www.custhelp.com/ => https://www.rightnow.com/: Too many redirects while fetching 'https://www.rightnow.com/'
ERROR src/chrome/content/rules/Custhelp.com.xml: Fetch error: http://custhelp.com/foo => https://www.rightnow.com/: Too many redirects while fetching 'https://www.rightnow.com/'
ERROR src/chrome/content/rules/Custhelp.com.xml: Fetch error: http://www.custhelp.com/foo => https://www.rightnow.com/: Too many redirects while fetching 'https://www.rightnow.com/'
ERROR src/chrome/content/rules/Custhelp.com.xml: Fetch error: http://custhelp.com/ => https://www.rightnow.com/: Too many redirects while fetching 'https://www.rightnow.com/'
INFO Finished in 13.87 seconds. Loaded rulesets: 2, URL pairs: 14.
Test URL test failed.
```

**Comment by fuglede** [comment]
That's rather odd. But okay, that certainly also is a lot of redirects. I tried to see what happened if we let it go to one of the intermediate paths, but that still causedi ssues, and since the ultimate target of those redirects can not be secured without causing a redirect loop, we weren't really adding much in terms of actual security anyway, so I opted to simply remove the problematic rule.

**Comment by fuglede** [comment]
@J0WI: Why not take this one instead of #4970? This one looks like it contains a strict superset of fixes, is older, and now has a merge conflict.

**Comment by J0WI** [comment]
Oh, sorry. I dind't remember that one and was to fast on #4970. I'm not sure if it's worth to revert, but at least the changes in `Ancestry.xml` are still desirable.

**Comment by fuglede** [comment]
That's fair enough. I'll keep this one in the inbox for merging when I find more than a minute; but also feel free to just do it yourself, if it looks good to you and you have time.

**Comment by J0WI** [comment]
merged in 7af0045

**Comment by fuglede** [comment]
Thanks!

On 29 July 2016 03:10:02 CEST, J0WI <notifications@github.com> wrote:
>merged in 7af0045
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/pull/4747#issuecomment-236069240

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
