### PR TITLE
Update KNET.cn.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@J0WI

**Comment by J0WI** [comment]
There are a lot of hosts, is there any regularity?

WFM:
zdns.knet.cn
ts.knet.cn
yida.knet.cn
gtld.knet.cn

Timeout:
api.q.knet.cn
domain.knet.cn
name.knet.cn
kexin.knet.cn
\d+.waw.q.knet.cn
xingdong.knet.cn
seal.knet.cn
wz.knet.cn
shenqing.knet.cn
zhangshang.knet.cn
ecert.knet.cn
dmp.knet.cn
kx.knet.cn

**Comment by renyouguo** [comment]
BTW, what does WFM mean?

**Comment by J0WI** [comment]
Works For Me

**Comment by renyouguo** [comment]
@J0WI Thanks.
Done.

**Comment by J0WI** [comment]
They don't work for you?
https://www.ssllabs.com/ssltest/analyze.html?d=ts.knet.cn
https://www.ssllabs.com/ssltest/analyze.html?d=yida.knet.cn&latest

**Comment by renyouguo** [comment]
It's my firefox profile's error. I will test again.

**Comment by renyouguo** [comment]
F**k CNNIC Root cert. Delete it, then OK.

**Pull request merged**
