### PR TITLE
The Guardian: add remaining subdomains

### PR DESCRIPTION
**Pull request by numismatika**
The guardian just announced to switch completely to TLS:

https://www.theguardian.com/info/developer-blog/2016/nov/29/the-guardian-has-moved-to-https

Probably needs work on 

- [x] 		- Gu.com.xml
- [x] 		- Guardian.xml
- [x] 		- guardianapps.co.uk.xml
- [x] 		- Guardian_Escapes.com.xml
- [x] 		- Guardian_Offers.co.uk.xml
- [x] 		- Guardian_Subscriptions.co.uk.xml
- [x] 		- Guim.co.uk.xml

as well

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for the work here! Please let us know when this is ready for a review.

**Comment by numismatika** [comment]
It is a beast to work on as the tracis ci tests time out due to the amount of subdomains involved here.

**Comment by J0WI** [comment]
You may use wildcard targets if they really support HTTPS on each subdomain.
Note that some domains are now HSTS preloaded, so you can remove those rulesets.

**Comment by Bisaloo** [comment]
`guardiansubscriptions.co.uk` is for sale.

Also, FYI, `hackertrace{1-4}.internal.nsa.gov.$DOMAIN` are an artifact from `Sublist3r` but not actual working subdomains.

**Comment by numismatika** [comment]
As long as Large pullrequests can't be properly tested because they time out , the entire undertaking becomes moot.

**Comment by cschanaj** [comment]
Please be noted that `hsts-prune` will remove `Guim.co.uk.xml` because in its next run because `*.guim.co.uk` is currently preloaded.

**Comment by J0WI** [comment]
@numismatika would be great if you could rebase these changes. You ca also split this work into multiple PRs to reduce the overhead.

**Comment by numismatika** [comment]
@J0WI i will try it by domain/file
#13266

**Comment by jeremyn** [comment]
@numismatika It would be nice to update our coverage for The Guardian sites. Can we move forward on this?

**Pull request closed without merging**
