### PR TITLE
[Android] Make context menu looks good

### PR DESCRIPTION
**Pull request by paulorb1**

### CODE REVIEW

**Comment by J0WI** [comment]
Looks trivial, maybe @fuglede could review this too?

**Comment by fuglede** [comment]
@fuglede: I'm merely a ruleset librarian, but yeah, I agree with the change.

**Comment by J0WI** [comment]
Okay so @Hainish, @jsha or @cooperq should review that.

**Comment by Hainish** [comment]
lgtm!

**Pull request merged**
