### PR TITLE
[New ruleset] hoccer.com

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by rugk** [comment]
Any news? And BTW: `<securecookie host="." name="." />` is valid and just includes all cookies from this domain, is not it?

**Comment by jeremyn** [comment]
Thanks @rugk.

- [ ] There are various issues with the ruleset, so please change it to look like this:

```xml
<!--
	Invalid certificate:
		api.hoccer.com
		developer.hoccer.com
		stats.hoccer.com
		hoccer-project.com
		www.hoccer-project.com
		stats.hoccer-project.com

-->
<ruleset name="Hoccer">

	<target host="hoccer.com" />
	<target host="www.hoccer.com" />
	<target host="faq.hoccer.com" />
	<target host="invite.hoccer.com" />

	<target host="hoccer-project.com" />
	<target host="www.hoccer-project.com" />

	<securecookie host="^(www|faq|invite)\.hoccer\.com$" name=".+" />

	<rule from="^http://(www.)?hoccer-project\.com/"
		to="https://hoccer.com/" />

	<rule from="^http:"
		to="https:" />

</ruleset>
```
This:
* adds new `target`s and identifies some non-working domains
* changes the ruleset `name` because it now covers both `hoccer.com` and `hoccer-project.com`
* modifies the `securecookie` to be more targeted, given the number of non-working domains. Also following our style guide [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), `.+` is the preferred way of saying "match everything".
* adds rewrite for `(www.)?hoccer-project.com` to `hoccer.com`.

Please let me know if you have any concerns about these changes.
- [ ] Also, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) rulesets, which means we combine and rewrite commits in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by rugk** [comment]
> Also, we like to squash-and-merge rulesets, which means we combine and rewrite commits in your name. Is that all right with you for this and any other pull requests you submit to us?

Yes, that's all right.

**Comment by jeremyn** [comment]
My mistake on the failed tests. In [this line](https://github.com/rugk/https-everywhere/blob/d37cf11740086a4ce25b800ad8f7c2b5e30f4096/src/chrome/content/rules/hoccer.com.xml#L23), change `(www.)` to `(www\.)`. The first way is wrong. I had it the wrong way in https://github.com/EFForg/https-everywhere/pull/6230#issuecomment-263406395 and have now updated it. I'm sorry about that.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
