### PR TITLE
Remove redundant personal site rule (HSTS Preloaded)

### PR DESCRIPTION
**Pull request by ajhaydock**
I operate both sites so if there are any queries with the rules please let me know.

Thanks :)

### CODE REVIEW

**Comment by strugee** [comment]
@ajhaydock I'm not affiliated with HTTPS Everywhere and this probably won't prevent this PR from being merged, but you may want to consider splitting this commit into two (see [atomic commits][1]) and then making both commits have [good commit messages][2] that are under 50 characters :)

Cheers!

 [1]: https://www.freshconsulting.com/atomic-commits/
 [2]: http://chris.beams.io/posts/git-commit/

**Comment by ajhaydock** [comment]
@strugee Thanks for the feedback. :) Not sure if I can go back and split the commit up after attempting this pull request, but I'll definitely bear it in mind for future ones. I have a few more sites to commit later.

**Comment by strugee** [comment]
@ajhaydock if you split it up and force-push to GitHub, the new commits will show up here. That being said I don't know offhand how easy it is to _split_ commits (reordering and squashing aren't _super_difficult, but I don't know about _splitting_). :)

**Comment by J0WI** [comment]
Since both hosts are already HSTS preloaded, we can safely remove them from HTTPS Everywhere.

**Comment by ajhaydock** [comment]
That is true. Hadn't considered that. Would you like me to rework this commit to remove my rule instead?

**Comment by J0WI** [comment]
That would be great!

**Comment by ajhaydock** [comment]
That ought to do it :smile:

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
