### PR TITLE
Framasoft

### PR DESCRIPTION
**Pull request by AtomiKe-FR**

### CODE REVIEW

**Comment by J0WI** [comment]
```*.framapad.org``` requires some test urls

**Comment by J0WI** [comment]
@AtomiKe-FR are you still interested to continue here?

**Comment by Bisaloo** [comment]
I think the fix would be to explicit `*.framapad.org` into 

- quotidien.framapad.org
- hebdo.framapad.org
- mensuel.framapad.org
- bimestriel.framapad.org
- semestriel.framapad.org
- annuel.framapad.org

Should I submit a new PR or can you integrate those changes in the current one?

**Comment by J0WI** [comment]
@Bisaloo you can create a new PR based on this one and I'll merge both or you pick these changes and rebase them (might be easier to review).

**Pull request closed without merging**
