### PR TITLE
Create prohardver.hu

### PR DESCRIPTION
**Pull request by xusenezi**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you please also [search for subdomains](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) and document non functional ones?

**Comment by jeremyn** [comment]
@xusenezi Please:

Note in a top comment as `Mismatch`:
- [ ] https://www.prohardver.hu
- [ ] https://img.prohardver.hu
- [ ] https://karrier.prohardver.hu

Add `target`:
- [ ] https://m.prohardver.hu

**Comment by jeremyn** [comment]
@J0WI I agree with asking @xusenezi to search, but in there case there weren't many missing and I'd like to close this.

**Comment by J0WI** [comment]
I'm closing this because there is no repose from the contributor.

**Pull request closed without merging**
