### PR TITLE
Update QQ.com.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by pipboy96** [comment]
Add these targets too, and remove them from `QQ.com-Problematic.xml`:
```xml
	<target host="3gimg.qq.com" />
	<target host="888.qq.com" />
	<target host="aq.qq.com" />
	<target host="js.aq.qq.com" />
	<target host="act.daoju.qq.com" />
	<target host="js01.daoju.qq.com" />
	<target host="js02.daoju.qq.com" />
	<target host="gamevip.qq.com" />
	<target host="ke.qq.com" />
	<target host="x.l.qq.com" />
	<target host="open.map.qq.com" />
	<target host="s.map.qq.com" />
	<target host="minigame.qq.com" />
	<target host="mxm.qq.com" />
	<target host="s.pc.qq.com" />
	<target host="pr.map.qq.com" />
	<target host="ossweb-img.qq.com" />
	<target host="ssl.ptlogin2.qq.com" />
	<target host="qqgame.qq.com" />
	<target host="open.qqgame.qq.com" />
	<target host="img1.sj.qq.com" />
	<target host="img2.sj.qq.com" />
	<target host="img3.sj.qq.com" />
	<target host="img4.sj.qq.com" />
	<target host="img5.sj.qq.com" />
	<target host="img6.sj.qq.com" />
	<target host="sqimg.qq.com" />
	<target host="cdn.tencentgroup.qq.com" />
	<target host="v.qq.com" />
		<exclusion pattern="^http://v\.qq\.com/vplus/" />
		<test url="http://v.qq.com/vplus/colorsofchina" />
	<target host="tj.video.qq.com" />
	<target host="vip.qq.com" />
	<target host="api.weixin.qq.com" />
	<target host="open.weixin.qq.com" />
	<target host="webpush.weixin.qq.com" />
	<target host="cdn.wetest.qq.com" />
	<target host="f.wetest.qq.com" />
	<target host="wspeed.qq.com" />
	<target host="xx.qq.com" />
	<target host="m.y.qq.com" />
```

**Comment by ivysrono** [comment]
@pipboy96 https://github.com/EFForg/https-everywhere/pull/17177

**Comment by pipboy96** [comment]
@ivysrono ?

**Comment by ivysrono** [comment]
@pipboy96 I can't do as you request because of #17177

**Comment by pipboy96** [comment]
@ivysrono They now all pass fetch test except of `dp3.qq.com`.

**Comment by pipboy96** [comment]
@ivysrono You're ok to keep `dp3.qq.com` in the whitelisted ruleset.

**Comment by ivysrono** [comment]
@pipboy96 Let's do it next time.

**Pull request merged**
