### PR TITLE
[WoolworthsRewards.com.au] New ruleset

### PR DESCRIPTION
**Pull request by youdly**
https://github.com/EFForg/https-everywhere/pull/13338

### CODE REVIEW

**Comment by youdly** [comment]
`everydayrewards.com.au` has been removed from `Woolworths-AU.xml` https://github.com/EFForg/https-everywhere/pull/13338

**Comment by J0WI** [comment]
We have a cycle here: I can't merge this because of the duplicated target and I can't merge #13338 because of the missing reference.

**Comment by youdly** [comment]
I've removed the reference to this ruleset from https://github.com/EFForg/https-everywhere/pull/13338. Once that PR is merged, I'll do a rebase for this branch and add the reference back.

**Comment by J0WI** [comment]
I think #13338 needs to be rebased anyway (see Travis).

**Comment by youdly** [comment]
rebased https://github.com/EFForg/https-everywhere/pull/13338

**Pull request merged**
