### PR TITLE
1prime.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

Mark `Mixed content`:
- [ ] https://bir.1prime.ru because it's blocking `jquery` which is often important, though I don't know what is specifically broken here, if anything

Add target:
- [ ] https://webservice.1prime.ru

Also:
- [ ] Sort subdomains beneath `^` and `www`

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
Thanks. https://disclosure.1prime.ru and https://www.disclosure.1prime.ru should be `incomplete certificate chain`, not `self-signed`, unless I'm missing something. Looks good otherwise.

**Comment by galeksandrp** [comment]
Yes, thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
