### PR TITLE
[ClamAV.net] Add subdomains

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Instead of `No working URL known`, these should be:
- [ ] https://intel.clamav.net is `Time out`
- [ ] https://snapshot.clamav.net is `Invalid certificate`
- [ ] https://stats.clamav.net is `Time out`
- [ ] https://win.clamav.net is not in DNS and can be removed entirely

Also: 
- [ ] Change `Dropped` to `Time out`
- [ ] You can remove ` (partial)` from the `name`

**Comment by Bisaloo** [comment]
I tend to think that no working URL known should always get the precedence compared to other comments.

A given subdomain may be unreachable over `https` due to an invalid certificate but does it matter if this subdomain in not in use anyways and 404/times out/returns a blank page over `http`?

**Comment by jeremyn** [comment]
`No working URL known` means that there's nothing technically wrong with the connection, but we didn't add it because we couldn't find one working 2xx/3xx response at that subdomain using HTTPS, so we're not comfortable rewriting it. So, if that subdomain gets an actual HTTPS error like `Invalid certificate`, then we shouldn't use `No working URL known` because there is actually something wrong with the connection.

I proposed `No working URL known` in issue https://github.com/EFForg/https-everywhere/issues/7662 and you can see a longer discussion there.

**Comment by jeremyn** [comment]
Thanks, merged, original commit messages deleted.

**Comment by Bisaloo** [comment]
@jeremyn, I think it would be useful to have another section for URL that don't work even over `http`. What do you think?

If a ruleset only has subdomains in this category, it means there is nothing wrong with `https` and the domain is fully covered, with all the functioning subdomains.

This is useful because most of the sites have subdomains they don't use anymore but that are still listed by `Sublist3r`. I think we are unnecessarily bloating the top comment with those.

Another option would be to ignore those subdomains completely but it would probably be more confusing when people come back later to update this ruleset.

**Comment by jeremyn** [comment]
I'm not sure what you're asking for. You want add subdomains to the top comment even if they don't work under plain HTTP? I don't want to add more stuff to the top comments if we can avoid it.

**Comment by Bisaloo** [comment]
Okay, let's take for example `snapshot.clamav.net`:

- http://snapshot.clamav.net times out
- https://snapshot.clamav.net is mismatched

Until now, I would add `snapshot.clamav.net` to the list of `No working URL known`. However, you convinced me this is not the purpose of this section.

I am simply wondering what I should do when I encounter this kind of behaviour. Should the subdomain still be listed? Under which section?

**Comment by jeremyn** [comment]
If both HTTPS and plain HTTP are broken, I wouldn't mention the subdomain at all, even if they are broken for different reasons.

**Pull request merged**
