### PR TITLE
add rule for Wintotal.de

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
You should add a redirect from ^ to www.
Mismatch on community.wintotal.de

**Comment by numismatika** [comment]
@J0WI  done that.

**Comment by J0WI** [comment]
Please also add a hint for the mismatch on ^wintotal.de.
LGTM then.

**Comment by J0WI** [comment]
@numismatika are you still working on this?

**Comment by numismatika** [comment]
i'll push that branch later

**Comment by numismatika** [comment]
comment on the mismatch for^ and community as well as the redirect for ^ are in @J0WI

**Comment by J0WI** [comment]
No comment for the mismatch on ^wintotal.de so far...

**Comment by numismatika** [comment]
@J0WI  now it should be there

**Comment by J0WI** [comment]
@numismatika Thanks!
Just some code style: please move comments above the `<ruleset>` tag.
Ping me and I'll merge it then.

**Comment by numismatika** [comment]
@J0WI  now it should be fine.

**Pull request merged**
