### PR TITLE
Remove https-everywhere-checker message

### PR DESCRIPTION
**Pull request by cschanaj**
Source code available at [`remove-checker-message.go`](https://github.com/cschanaj/lambda/blob/master/src/remove-checker-message.go), see [`issue-11274-list.txt`](https://gist.github.com/cschanaj/311344e50158c7c2ee9099510e851711) for a list of 241 files excluded from this PR because of failing tests. 

[`Bitly_branded_short_domains.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Bitly_branded_short_domains.xml) lengthened the Travis build time significantly, excluded it for everyone's sake. (This particular ruleset contains **25% (36k of 120k)** of `target` in the whole code base! 0rz...)

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks @cschanaj . I've haven't followed these bulk-edit projects closely but why are we removing this message? Just for code cleanliness? Does the current version of the checker use these messages?

**Comment by cschanaj** [comment]
@jeremyn A number of `default_off='failed ruleset test'` got re-activated by the _https-everywhere-checker_ automatically in #10538. These comment are already outdated because the respective ruleset are no longer `default_off`, the comments are not removed simply because the checker does not support the removal, see https://github.com/EFForg/https-everywhere/pull/10538#issuecomment-310142160

**Comment by cschanaj** [comment]
@jeremyn Hooray! thanks!!

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by Hainish** [comment]
Thanks for this @cschanaj

**Comment by jeremyn** [comment]
@cschanaj Just FYI, I noticed [`NYDailyNews.xml`](https://github.com/EFForg/https-everywhere/blob/9bf49cbeb4696cdea76df23f685da1d11031f693/src/chrome/content/rules/NYDailyNews.xml) from June 20th has the disabled comment but is not actually disabled, so your script should have caught it and maybe you want to look into the problem.

**Comment by cschanaj** [comment]
@jeremyn This is an expected case because I have manually removed the ruleset which failed `rule-test` or `fetch-test` after the automatic modification. 

In this particular ruleset, [`NYDailyNews.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/NYDailyNews.xml) consists of `exclusion` and complicated `rule` which will require some `test` URL in order to pass the `rules-test`. This file is also listed in [`utils/ruleset-whitelist.csv#L2705`](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-whitelist.csv#L2705)

Out of 225 existing ruleset re-activated by _https-everywhere-checker_ with outdated comments, 204 of them are whitelisted from `rule-test`/ `fetch-test`, see [`checker-reactivated-but-whitelisted.txt`](https://gist.github.com/cschanaj/3387b139f718d764f012b9060ea8160e)

The following 21 ruleset are might have some false positive results on Travis
```
7_Springs.com.xml
Alfa-Media-Partner.xml
Auto_Rims_and_Accessories.xml
BTCZone.xml
Brixwork.com.xml
CBC_Blueprint.xml
Covered-California.xml
Cts-strasbourg.eu.xml
E-Estonia.com.xml
Forsvarsforbundet.se.xml
Laup.xml
Matkahuolto.xml
McClatchy_Interactive.com.xml
Mirror_Bingo.com-falsemixed.xml
Mstar.com.xml
Obedovat.sk.xml
Packetwerk.com.xml
Pan-Islamic_Malaysian_Party.xml
PolarnoPyret.se.xml
Tandlakarforbundet.se.xml
xServers.xml
```

I will try to work on them later. thanks!

**Comment by jeremyn** [comment]
@cschanaj Thanks for your comment but I don't understand. Are you saying you specifically did not remove the comment from activated rulesets because those rulesets were in the whitelist? If so, why not?

**Comment by cschanaj** [comment]
No, I excluded some ruleset because they failed Travis build. These excluded ruleset either failed `rule-test` or `fetch-test` for some reasons. I do not want to modify them manually because I cannot guarantee a reviewer can reproduce the same files (not to mention the heavy workloads). 

Items in  `ruleset-whitelist.csv` by definition always failed Travis without manual modification. I cannot work on these items because they might require whitelisting. It will be even harder to review huge changes like this.

**Comment by jeremyn** [comment]
Are you saying that `https-everywhere-checker` enabled some rulesets that fail testing and aren't whitelisted? That sounds like a bug in the checker program.

If the checker program re-activated rulesets that are in `ruleset-whitelist.csv`, and the only change you want to make is to remove the outdated comment in those rulesets, then you can just update the sha256 hash in the whitelist file.

(By the way, I don't mean to say that you are obligated to make any more changes.)

**Comment by cschanaj** [comment]
> Are you saying that https-everywhere-checker enabled some rulesets that fail testing and aren't whitelisted? That sounds like a bug in the checker program.

@jeremyn I think so, see #11526

**Comment by Hainish** [comment]
@cschanaj this seems not to be the case:

```shell
(.venv)user@https-everywhere ~/workspace/https-everywhere (master) $ git reset --hard 9bf49cbeb4696cdea76df23f685da1d11031f693
HEAD is now at 9bf49cb Disabling rulesets that fail the comprehensive fetch test across multiple locations (Singapore, London, San Francisco) and across the span of a week
(.venv)user@https-everywhere ~/workspace/https-everywhere (master) $ RULESETS_CHANGED="src/chrome/content/rules/NYDailyNews.xml" test/fetch.sh        
INFO Finished comparing http://nydailynews.com/ -> http://nydailynews.com/. Rulefile: src/chrome/content/rules/NYDailyNews.xml.
INFO Finished in 1.22 seconds. Loaded rulesets: 1, URL pairs: 1.
Test URL test succeeded.
```

Remember, the full fetch test only disables rulesets that have failed across all three colocations.

**Pull request merged**
