### PR TITLE
Fixes #2887

### LINKED ISSUE #2887: HTTPS Everywhere breaks Torcache
HTTPS Everywhere breaks torcache.net so that torrent files won't load and pop up in a "save window". Disabling the "Torcache" ruleset fixes this.
Sample: https://torcache.net/torrent/72F242DB89E763B6CE390F25D576195C2169B149.torrent

### PR DESCRIPTION
**Pull request by TheNavigat**

### CODE REVIEW

**Comment by fuglede** [comment]
It [seems to me](https://github.com/EFForg/https-everywhere/issues/2887#issuecomment-142396027) that this exclusion is unnecessary.

**Comment by TheNavigat** [comment]
The file never actually downloads. The URL loads correctly but you can't download the file.

**Comment by fuglede** [comment]
That's peculiar. It works in both Firefox and Chrome here.

**Comment by TheNavigat** [comment]
Weird... I'll double check in a couple hours, maybe they fixed it on their own side.

**Comment by TheNavigat** [comment]
Yep, peculiar. Works here as well. I guess I'll just close the issue.

**Comment by fuglede** [comment]
Great; thanks for checking!

**Pull request closed without merging**
