### PR TITLE
Batch trivialize rulesets with static securecookies

### PR DESCRIPTION
**Pull request by cschanaj**
1. Batch remove targets which are gone from DNS; `log.txt` come from dd2bb1b which is available at https://api.travis-ci.org/v3/job/419433017/log.txt

```bash
user@linux:~/https-everywhere/rules$ grep 'Could not resolve host:' ~/log.txt | sed "s/^.*\/\([^:]*.xml\).*Could not resolve host: \([^']*\).*$/\1 \2/g" | while read FILE HOST; do sed -i "/target.*$HOST/d" $FILE; done
```
2. Remove rulesets which do not contain any target
```bash
grep -L 'target' *.xml | while read FILENAME; do rm $FILENAME; done
```

3. Comment out target which connection refused, `log.txt` from 8a8aa0d which is available at https://api.travis-ci.org/v3/job/419442740/log.txt

```bash
grep 'Connection refused' ~/log.txt  | sed "s/^.*\/\([^:]*.xml\).*Failed to connect to \([^' ]*\).*$/\1 \2/g" | while read FILE HOST; do sed -i -e "/target.*$HOST/ s/</<\!--/" -e "/target.*$HOST/ s/>/-->/" $FILE ; done
```

4. Remove rulesets which do not contain any target
```bash
grep -L '<target' *.xml | while read FILENAME; do rm $FILENAME; done
```

### CODE REVIEW

**Comment by cschanaj** [comment]
ping @Hainish

**Comment by cschanaj** [comment]
@Hainish this PR will trivialize the rulesets with static secure cookies using `utils/trivialize-rules`, please have a look on this when you have the time. Given this PR affects 300+ rulesets, I would like to avoid merge conflicts before they appear. thanks. 

cc @J0WI @jeremyn @Bisaloo

**Comment by Hainish** [comment]
@cschanaj looking now.

**Comment by Hainish** [comment]
Thanks @cschanaj.  This looks mostly okay, but I spotted a few problems:

https://github.com/EFForg/https-everywhere/pull/16378/files#diff-d6996dea1dd5aebe1e89fdf4bde0954d

If you look at `Asahi_Shimbun.xml`, `ajw.asahi.com` is not in the targets list, but the `securecookie` for this subdomain was left intact.  I'm assuming the domain was deleted due to a DNS resolution failure, but I am now seeing it resolve:

```shell
user@https-everywhere ~ $ dig ajw.asahi.com

; <<>> DiG 9.10.3-P4-Debian <<>> ajw.asahi.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45452
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ajw.asahi.com.			IN	A

;; ANSWER SECTION:
ajw.asahi.com.		1799	IN	CNAME	ajw-en-lb-new-734989844.ap-southeast-1.elb.amazonaws.com.

;; AUTHORITY SECTION:
ap-southeast-1.elb.amazonaws.com. 59 IN	SOA	ns-1125.awsdns-12.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60

;; Query time: 137 msec
;; SERVER: 10.139.1.1#53(10.139.1.1)
;; WHEN: Tue Sep 04 16:07:38 PDT 2018
;; MSG SIZE  rcvd: 197
```

We should probably ensure temporary resolution failures don't result in domains being removed, as well as try (if possible) to remove obsoleted `securecookie`s

**Comment by cschanaj** [comment]
> We should probably ensure temporary resolution failures don't result in domains being removed, as well as try (if possible) to remove obsoleted securecookies

I believe it might require some effort to check for the resolution failures in such a huge PR. Should I submit a PR which simply checkout the rulesets which have a fetch-error, and then address those files in a later PR?

**Comment by Hainish** [comment]
Yes I think that's fine.  Thank you, I'll merge this PR now.

**Pull request merged**
