### PR TITLE
Adding indiewebcamp central site.

### PR DESCRIPTION
**Pull request by mapkyca**

### CODE REVIEW

**Comment by J0WI** [comment]
You should also include www.

socialwg and news have no valid cert, could you add a comment for those?

**Comment by J0WI** [comment]
@mapkyca are you still working on this?

**Comment by mapkyca** [comment]
Errp! Sorry, this got buried.

I'll look at it tomorrow!

**Comment by J0WI** [comment]
Thanks!

**Comment by J0WI** [comment]
I just wanted to test this, but it seems like the host is down.
Is this just temporary or has the host been dropped?

**Comment by jeremyn** [comment]
@mapkyca Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
I've submitted pull request https://github.com/EFForg/https-everywhere/pull/7674 , which covers the domains in this pull request, so I'm closing this one as a duplicate.

**Pull request closed without merging**
