### PR TITLE
Create uptodown.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by J0WI** [comment]
There are much more subdomains. At least all language domains are working. See also utdstc.com.

**Comment by renyouguo** [comment]
@J0WI I'm not sure , is wildcard ok?

**Comment by J0WI** [comment]
All app domains seems to be okay, so a wildcard makes sense.
There is a mismatch on ^, blog. and gstatic. For blog you may need a downgrade, because the links from app pages to it are protocol relative.

**Comment by J0WI** [comment]
Downgrade rules have to be listed in `utils/downgrade-whitelist.txt`

**Comment by J0WI** [comment]
You can replace both redirects to https with a simple `<rule from="^http:" to="https:" />`, this will also avoid the current error.

**Comment by J0WI** [comment]
(img|stc)\.utdstc\.com needs to be added as target host

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
