### PR TITLE
Fix static.websimages.com rewrite

### PR DESCRIPTION
**Pull request by RReverser**
Current rewrite was either typo or something changed, anyway test URL below failed.

### CODE REVIEW

**Comment by fuglede** [comment]
Good catch. Seems like the site is down right now so it's hard to verify but from the looks of it, the rule above the one you fixed is also broken.

**Comment by RReverser** [comment]
Maybe. I was just running automatic comparison of results of own rewriter vs rules.js and found this one.

**Comment by fuglede** [comment]
I wasn't actually able to find any links that get rewritten by it but my guess would be that the issue is the same: that there's a capture group missing.

**Comment by fuglede** [comment]
Right, found a useful test URL:
http://images.webs.com/static/global/js/webs/usersites/ie6subnav.js can be rewritten to https://a248.e.akamai.net/f/1129/8333/3m/images.webs.com/static/global/js/webs/usersites/ie6subnav.js

Could you include this one in your PR as well, simply adding the relevant capture rule where it's currently missing?

**Comment by RReverser** [comment]
@fuglede Sure. Can you please also show some example for the "free" part?

**Comment by fuglede** [comment]
http://images.freewebs.com/Members/Generationz/Standard/PrintCSS/print.css

Looks like both 
  https://a248.e.akamai.net/f/1129/8333/3m/images.freewebs.com/Members/Generationz/Standard/PrintCSS/print.css
and
  https://a248.e.akamai.net/f/1129/8333/3m/images.webs.com/Members/Generationz/Standard/PrintCSS/print.css
are working so I'm not sure why the 'free' part has been uncaptured.

**Comment by RReverser** [comment]
Probably just to avoid capture group, dunno.

One more question - are you sure that rewrite was indented to target `https` (I mean in `^https?://(static\.websimages\.com)/`)?

**Comment by fuglede** [comment]
Yes, it looks like that becomes necessary on https://members.webs.com where there's a reference to "//static.websimages.com/vfefa01f/active-static/lib/modernizr.js".

**Comment by RReverser** [comment]
Ah, certificate mismatch. I see.

**Comment by RReverser** [comment]
Done!

**Comment by fuglede** [comment]
Looks good; thanks!

**Pull request merged**
