### PR TITLE
Update whitelist for FierceMarkets.xml

### PR DESCRIPTION
**Pull request by jeremyn**
This updates the whitelist following the change in pull request #6243 .

@fuglede @Hainish @J0WI Please review this soon because this is breaking Travis.

### CODE REVIEW

**Comment by J0WI** [comment]
I wonder why the tests passed in #6243 .

**Comment by jeremyn** [comment]
I'm not totally sure but there were recent changes to how the whitelist is handled in Travis, see pull request #6689 . If you were relying on a test ran last month then the test result may have been outdated.

**Comment by fuglede** [comment]
Sounds weird; do you have a reference for a broken build? https://travis-ci.org/EFForg/https-everywhere/builds looks mostly green.

**Comment by jeremyn** [comment]
@fuglede https://travis-ci.org/EFForg/https-everywhere/builds/159734794

**Comment by fuglede** [comment]
Thanks for the reference. #6689 only concerned fetch testing, so that *should* not be relevant here.

In fact, the job from #6243 correctly caught the failure (see https://travis-ci.org/EFForg/https-everywhere/jobs/152052034) but the `docker` run gave the wrong return value, leading to the false green; I could imagine that this would be fixed now that the test has been split into six different ones -- I guess we'll find out pretty quickly, but maybe @Hainish will also be able to tell immediately?

**Pull request merged**
