### PR TITLE
[Globalclimatemarch.org] New ruleset

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by semenko** [comment]
```

../src/chrome/content/rules/Globalclimatemarch.org.xml:15: element rule: Relax-NG validity error : Element rule failed to validate attributes
../src/chrome/content/rules/Globalclimatemarch.org.xml fails to validate
```

**Comment by rugk** [comment]
What? In line 15 there is just the redirect rule.

**Comment by rugk** [comment]
Does anybody know why the test fails here?

**Comment by semenko** [comment]
You need to escape the from rule. At the bottom of travis:

    failure: Globalclimatemarch.org.xml failed test: The 'from' rule contains unescaped period in regular expression.  Try escaping it with a backslash.

**Comment by rugk** [comment]
Ah thanks. Found it.

**Comment by fuglede** [comment]
You missed the one after www.

**Comment by rugk** [comment]
Thanks. Fixed. And as you somewhere else said I have to add `/` at the end I also did it here.

**Pull request merged**
