### PR TITLE
trivialize securecookie (^0 -> ^9)

### PR DESCRIPTION
**Pull request by cschanaj**
GO script used [`trivialize-secure-cookie.go`](https://github.com/cschanaj/lambda/blob/master/src/trivialize-secure-cookie.go)

Similar to previous massive rewrites, subsequent PRs will be much larger (300+ files PRs), please help to review the script if possible. thanks!

```
(1) exclude files which are 'default_off'
(2) exclude files which contain wildcard 'target'
(3) exclude files with 'exclusion' or complicated 'rule'
(4) IF for each `target`, exist at least one 'securecookie#host' match 'target' 
    and 'securecookie#name' is a wildcard. THEN rewrite.
(5) checkout files failing 'fetch-test'
```

P.S. around 3k files are subjected to modification, 1.3k files are ignored because they are `default_off`.

**To reviewer**: if possible, please merge #11525 before this. Otherwise, there might be some huge number of merge conflicts needed to be resolved in future PRs. Thanks!

### CODE REVIEW

**Comment by J0WI** [comment]
Please also exclude rules with non-trivial redirect rules or exclusions.

**Comment by cschanaj** [comment]
@J0WI I have modified the GO script via https://github.com/cschanaj/lambda/commit/9d8225d6f96eff536cb11394636835a79205917c and rebased this accordingly. If this is okay, I will work submit larger PRs later. thanks!

**Comment by J0WI** [comment]
I'm a bit unsure about securing all cookies in `platform="mixedcontent"` rules. The rule is not enabled by default, but there might be some edge cases where such bulk changes break cookies.

**Comment by cschanaj** [comment]
how about excluding rules with `platform` as well?

**Comment by cschanaj** [comment]
@J0WI I have partially resolved my questions after some Google search. If I am correct, trivializing `securecookie` is not a trivial task by itself. Reasoning as follow: 

According to https://tools.ietf.org/html/rfc6265

> 5.2.3.  The Domain Attribute

and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

> Contrary to earlier specifications, leading dots in domain names are ignored. If a domain is specified, subdomains are always included.

the `leading dot` in `cookie.domain` are ignored (as implemented in [`chromium/rules.js#L390`](https://github.com/EFForg/https-everywhere/blob/master/chromium/rules.js#L390)), the following type of cookie rule (900+ such)
```xml
<securecookie host="^\." name=".+" />
```
actually never apply (and thus safe to be removed). 

From my understanding of the Mozilla doc, it looks like that all `cookie` are shared by subdomain of `cookie.domain`. It is therefore indeed **dangerous** to apply `securecookie` since a working `target` might have some non-functional subdomains, leading to broken sites. 

That is
```xml
<!--
  cert chain error:
  - img.foo.bar
-->
<ruleset name"Foo.bar">
  <target host="foo.bar" />
  <target host="www.foo.bar" />

  <securecookie host="^(www\.)?foo\.bar$" name=".+" />

  <rule from="^http:" name="https:" />
</ruleset>
```
in fact securing cookie which potentially accessed by `img.foo.bar`

@Hainish could you please help to confirm my assertions when you have the time?

**Comment by cschanaj** [comment]
closing this as trivializing `securecookie` is likely to introduce some unexpected problems.

**Pull request closed without merging**
