### PR TITLE
Create sberbank.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
URL with port seems not no be allowed in tests

**Comment by J0WI** [comment]
@jsha is it possible to make rules for a domains running on a different port?

**Comment by jsha** [comment]
I believe it is possible. The target host matching happens purely on hostname though, so you'd want to leave off the port there, and specify what you want in the `<rules>` tags.

**Comment by J0WI** [comment]
updated

**Comment by J0WI** [comment]
Please merge before this conflicts again.

**Comment by TheNavigat** [comment]
Looks good to me. @semenko Ping! :D

**Pull request merged**
