### PR TITLE
Bitly HTTPS Update

### PR DESCRIPTION
**Pull request by jehiah**
This is a periodic update to the list of Branded Short Domains powered by Bitly with current HTTPS support. (The list was last updated in #4505)

It's expected that there is some natural churn on this list due to domains being added or removed from the Bitly platform, or SSL certificates becoming available or unavailable for a given domain.

Summary of changes:

Domains Added: 3705
Domains Removed: 3405
Domains Kept: 32696

Methodology:

This is the list of domains on the Bitly platform that were verified with valid DNS settings that point to Bitly in the last 12 hours, and for which Bitly has a valid SSL certificate with >20 days remaining. (20 days is important as our current threshold for renewing LetsEncrypt certificates is 21 days.)

The ruleset directory was checked for potential duplicates due to this update with https://gist.github.com/jehiah/e565d60fa759a6921c4c3af30f64e922 (one was found).

Note: We are separately working to improve the destination root redirects (i.e. where you get redirected to when you visit `http://domain/`) as #4505 highlighted multiple situations where those user entered redirect destinations dead-end, or go to HTTPS links with invalid SSL configurations. We've identified and resolved a few classes of issues, but we have more work to do there.

cc: @jsha @Hainish

### CODE REVIEW

**Comment by jsha** [comment]
Excellent, thanks @jehiah! Looks like there's still a failing test. @Hainish, can you help get any testing issues sorted and review?

**Comment by jehiah** [comment]
looks like i hit the landmine of old rulesets w/o tests, and i'm not really in a position to appropriately address that for `Yahoo.xml`. Advise? Is there a cost to having a target duplicated in multiple rule files?

```
ERROR src/chrome/content/rules/Yahoo.xml: Not enough tests (1 vs 296)
```

**Comment by jsha** [comment]
I think this is a case where it's okay to whitelist the changes in the Yahoo rule by adding its sha256 to the utils/ruleset-coverage-whitelist.txt.

**Comment by jehiah** [comment]
@jsha update this diff to whitelist the new `Yahoo.xml` file.

**Comment by jsha** [comment]
Drat, looks like the task we have to auto-fetch changed rulesets is taking too long and geting killed by Travis. No surprise there - that's a lot of hosts to check! I'm okay with merging this one in spite of the failed test. The auto-fetch is only done on PRs, not on master, so it won't break the master tests.

It turns out @Hainish is on vacation till next week, and he is the one with the most up-to-date knowledge on cross-checking this ruleset, and also the one who'll do the next release. I'll make sure this diff gets in by the next release. Thanks for your continued help maintaining this ruleset!

**Comment by Hainish** [comment]
Currently running fetchtest.go (just as I had previously in https://github.com/EFForg/https-everywhere/pull/4505) on `us-east-1`, I'll stagger starting the same fetch test and start running on `eu-central-1` in a few hours.

**Comment by Hainish** [comment]
@jehiah it's been a while since this ruleset has been updated.  Care to open another PR?

**Comment by J0WI** [comment]
@jehiah any chance to get another update of this ruleset? :)

**Comment by Hainish** [comment]
Looks like he's out on extended leave until September. Being that it's been a year since the last update, I think it'll be fine for us to punt on this another month.

**Comment by koops76** [comment]
@Hainish Can you check #11637? Please note it still needs work before being merged.

**Pull request merged**
