### PR TITLE
Update Sinaimg.cn.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by pipboy96** [comment]
Are you in Mainland or in HK? We need ruleset reviewers that can test rulesets for Chinese websites from Mainland.

**Comment by ivysrono** [comment]
Mainland

**Comment by pipboy96** [comment]
@ivysrono I recommend you talk with @zoracon and ask for ruleset review privilege. Make sure you mention that you can review Chinese rulesets from Chinese internet connection.

**Comment by ivysrono** [comment]
I am willing. @zoracon 's opinion?

**Comment by zoracon** [comment]
> I am willing. @zoracon 's opinion?

Hi there @ivysrono. Thank you for the many contributions over the years. I can give you access to review at a higher level as a collaborator, after you confirm that you read through the Code of Conduct. 
- [ ] https://www.eff.org/pages/eppcode

**Comment by ivysrono** [comment]
@zoracon Thank you. I have read https://www.eff.org/pages/eppcode word by word.

**Comment by ivysrono** [comment]
@zoracon Thanks, I have accept your invitation.
However, I can't merge PRs?
图片

**Comment by pipboy96** [comment]
why delete the repo?

**Comment by ivysrono** [comment]
My mistake. I have fork again.

**Comment by ivysrono** [comment]
Sorry, I created branch 'sinaimg.cn' directly, my mistake.
I can merge PRs now?

**Comment by pipboy96** [comment]
you need to set source repository again now.

**Comment by ivysrono** [comment]
@pipboy96 https://github.com/EFForg/https-everywhere/pull/17539#issuecomment-493425168
What happened？

**Comment by pipboy96** [comment]
Your PR can't be reopened since it points to a deleted branch.

**Comment by ivysrono** [comment]
I mean why you said 'I currently don't have merge permission to this repo, so I can't merge that. Sorry. You have to wait for another reviewer.'

**Comment by pipboy96** [comment]
I believe @zoracon is the right person to ask, it may be confidential EFF matter though and you won't get any answer.

**Comment by ivysrono** [comment]
ε=ε=ε=┏(゜ロ゜;)┛

**Comment by pipboy96** [comment]
?

**Comment by ivysrono** [comment]
it means run and laugh, just funny.

**Comment by pipboy96** [comment]
Thanks for clarifying.

**Comment by zoracon** [comment]
@ivysrono did you your question resolved?

**Comment by ivysrono** [comment]
@zoracon I still can not merge any PR.

**Comment by pipboy96** [comment]
@ivysrono This PR can't be merged, the branch it is pointing at has been deleted.

**Comment by ivysrono** [comment]
@pipboy96 Not only this PR.
For example: #18398 
图片
`You’re not authorized to merge this pull request. `
@zoracon

**Comment by zoracon** [comment]
@ivysrono Did you ever get an email asking you to accept permissions? While I wait for your answer, I will check out your permissions again. Sorry about that, I'd really like your contributions from the mainland.

**Comment by ivysrono** [comment]
No mail, but now I have permission.
Is it necessary to wait for a period of permission changes to take effect? Not important.
Thank you very much, I will try my best.

**Comment by ivysrono** [comment]
@zoracon @pipboy96 Would you like to add `Chinese` tag? So that I will check them.

**Comment by pipboy96** [comment]
@ivysrono Done.

**Comment by ivysrono** [comment]
@pipboy96 Thanks. I will check some exist pr for chinese sites.

**Pull request closed without merging**
