### PR TITLE
Im-apps.net

### PR DESCRIPTION
**Pull request by luixxiul**
Found on http://goo.ne.jp like #5976 and http://qiita.com

### CODE REVIEW

**Comment by luixxiul** [comment]
@jeremyn please review, thanks

**Comment by jeremyn** [comment]
@luixxiul Thank you for your ruleset contributions but please don't ping me specifically on these.. There are almost 900 open pull requests and we should get through the older ones first.

**Comment by luixxiul** [comment]
@jeremyn oh ok I see, I just felt people here thought my PRs were so trivial that they were not worth reviewing.

**Comment by jeremyn** [comment]
@luixxiul Not at all! It's great that you're contributing. Please keep submitting as many rulesets as you like. There's just a huge number to review. I actually just started on the ruleset review team last week as a volunteer, so with an extra person things should move forward more quickly. Thanks for your patience.

**Pull request closed without merging**
