### PR TITLE
Create AntiRacist.org.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by jeremyn** [comment]
Both `www` and `^` time out for me with both HTTPS and plain HTTP.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn They all work for me (both HTTP and HTTPS)  not sure what the issue may be for you :|

**Comment by Bisaloo** [comment]
@jeremyn, I can confirm it works on Firefox for me. I also tried with TBB and it timed out (US exit node) the first time but worked on the second try (France exit node).

**Comment by jeremyn** [comment]
@Bisaloo I'm oddly getting the reverse with Tor: `ExitNodes {us}` in my `torrc` lets it work, but `ExitNodes {fr}` causes a time out. I'm still get a time out with a non-Tor (US) connection.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@Bisaloo Note that the exit node you see in the Torbutton is not always accurate

**Comment by Bisaloo** [comment]
> @Bisaloo Note that the circuit you see in the Torbutton is not always accurate

Interesting. Do you have a source for that?

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@Bisaloo I noticed it myself more than one time, and if you search you can find similar cases https://tor.stackexchange.com/questions/9460/why-does-torbutton-circuit-view-not-consistently-show-the-correct-exit-node

**Comment by jeremyn** [comment]
I'm still getting time outs for everything as described in my original comment https://github.com/EFForg/https-everywhere/pull/12703#issuecomment-331480024, so I'm not comfortable merging this one, sorry.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn As you like ;)

**Pull request closed without merging**
