### PR TITLE
Create GameCopyWorld.com.xml

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by J0WI** [comment]
Please split this ruleset into multiple files and link them with comments.

**Comment by koops76** [comment]
@J0WI Done.

**Comment by koops76** [comment]
Other domains are CDN buckets.

**Comment by J0WI** [comment]
Separate files are still preferable. Please make the relation clear with comments.

**Comment by koops76** [comment]
@J0WI Done.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
