### PR TITLE
Add anu.edu.au

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for your contribution!

Please have a look at the errors exposed by Travis:
https://travis-ci.org/EFForg/https-everywhere/jobs/556171132#L1063-L1066

**Comment by weyusi** [comment]
I did test locally and those hosts were previously valid, but somehow becomes unresolved when travis tests. I'll do more tests.

**Comment by weyusi** [comment]
Removed more hosts, hopefully pass this time.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
