### PR TITLE
Create TieTuKe.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Refused`:
- [ ] https://tietuku.com
- [ ] https://i7.tietuku.com
- [ ] https://piimg.com
- [ ] https://www.piimg.com

Mark as `Secure connection failed`:
- [ ] https://www.tietuku.com

Mark as `Timeout`:
- [ ] https://i.tietuku.com

Also:
- [ ] Between [`i6.buimg.com` and `i8.buimg.com`](https://github.com/renyouguo/https-everywhere/blob/9c520252a9d575e680257b97771cbfa9967233bf/src/chrome/content/rules/TieTuKe.xml#L35-L36) add a comment like

```
<!-- i7.buimg.com does not exist -->
```
because otherwise people might wonder why it's not there.
- [ ] Do the same for `piimg`.

**Comment by jeremyn** [comment]
I've updated the checklist through your latest commit 144f1d770ed7b34222d5989323973f7114726a9e.

**Comment by renyouguo** [comment]
I have added i7 comments in head.

**Comment by jeremyn** [comment]
You're right, I see that now.

Thanks, merged.

**Pull request merged**
