### PR TITLE
[Badssl.com] Rewrite ruleset

### PR DESCRIPTION
**Pull request by rugk**
Rewritten to:
* add test URLs
* exclude URLs which (potentially) manipulate tests
* convert to spaces

### CODE REVIEW

**Comment by lgarron** [comment]
`badssl.com` maintainer here. If we're excluding any of `[*.]badssl.com`, I'd prefer to exclude all of it.
We're frequently adding and changing tests, and there is no benefit for selectively upgrading subdomains – only potential confusion for developers.

**Comment by rugk** [comment]
So what do you suggest? To disable every subdomain and only upgrade `http://badssl.com`?

**Comment by fuglede** [comment]
Note that the missing tests that Travis is complaining about should match the exclusion pattern; i.e. be mixed.badssl.com, hsts.badssl.com, etc.

**Comment by rugk** [comment]
> Note that the missing tests that Travis is complaining about should match the exclusion pattern; i.e. be mixed.badssl.com, hsts.badssl.com, etc.

Yes, but know I've already used another way. :smiley:

**Comment by rugk** [comment]
It would be nice if it could be merged now, because https://github.com/lgarron/badssl.com/issues/84 depends on this.

**Comment by rugk** [comment]
Does someone want to merge this?

**Comment by rugk** [comment]
Thanks. ☺️

**Pull request merged**
