### PR TITLE
intertelecom.ru.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
cert for ^ has been revoked (also for old.)

**Comment by galeksandrp** [comment]
How you discovered that cert is revoked?

**Comment by J0WI** [comment]
You should always check for a valid OCSP response, which our tests surprisingly don't (#6630).

**Comment by galeksandrp** [comment]
Documented, thanks.

**Comment by J0WI** [comment]
Thanks! Please remember https://github.com/EFForg/https-everywhere/pull/6387#issuecomment-241720415 for you future contributions :)

**Pull request merged**
