### PR TITLE
Forbid the creation of fallback rules

### PR DESCRIPTION
**Pull request by cschanaj**
#14336

### CODE REVIEW

**Comment by jeremyn** [comment]
Was there a clean-up issue where we went through and rewrote all the rules that had fallbacks? I feel like there was an issue like this but I can't find it now.

**Comment by cschanaj** [comment]
I think you are referring to #8833. We don't have any downgrade rules since `5.2.16`, as suggested in https://github.com/EFForg/https-everywhere/issues/9621#issuecomment-299241902.

**Comment by jeremyn** [comment]
@cschanaj Yes, #8833 looks like the right issue, thanks.

**Comment by J0WI** [comment]
@Hainish this change looks trivial, isn't it?

**Comment by Hainish** [comment]
:+1:

**Pull request merged**
