### PR TITLE
Added norge.no

### PR DESCRIPTION
**Pull request by Foorack**
Norway's National Digital Services Portal

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Change `ERR_TIMED_OUT` to `Timeout`
- [ ] Change `ERR_CERT_COMMON_NAME_INVALID` to `Mismatch`
- [ ] Add `.norge.no` to the comment subdomains
- [ ] Move `www2` to the end of the comment list

**Comment by Foorack** [comment]
@jeremyn fixed.

**Comment by jeremyn** [comment]
Thanks. You should remove `www.norge.no` from `Timeout`.

**Comment by Foorack** [comment]
@jeremyn Oops, missed that. Fixed.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
