### PR TITLE
Move armservers.com from WordPress-blogs.xml to its own ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**
Keeping each domain in a separate ruleset in way better for maintaining. Otherwise, we end with half broken rulesets that are so huge and messy that no one wants to update them, as in #10190 or [`Nederland.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Nederland.xml).

### CODE REVIEW

**Comment by Bisaloo** [comment]
Before I keep going, what's your take on this @Hainish, @jeremyn, @J0WI?

Also, it's going to be a big PR. Is that okay or should I somehow try to split it in many smaller PR?

**Comment by jeremyn** [comment]
I agree that we should break this ruleset up into new rulesets grouped by the logical relationships between domains. The fact that they are hosted on WordPress is an irrelevant implementation detail.

I definitely recommend multiple PRs. Each PR should create the new ruleset(s) for a group of related domains and also delete the matching domains from the WordPress ruleset. For example there should be a `Create ARMservers.com.xml` PR that creates the `ARMservers.com.xml` ruleset and deletes the `armservers.com` `target`s from the WordPress ruleset.

**Comment by J0WI** [comment]
I think if there are just multiple identical aliases in one ruleset, like `foo.com`, `foo.net` and `foo.org` it's okay. But in the case here and in the other linked examples it's too much and a pain to maintain.

+1 for separate PRs.

**Comment by Bisaloo** [comment]
Okay, I will add PR one by one then so that I don't have to solve conflicts each time you merge a PR.

**Pull request merged**
