### PR TITLE
Update v2ex.co.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
remove reference
Ref: #6995

### CODE REVIEW

**Comment by jeremyn** [comment]
This deletes `V2ex.xml`, but that file was already deleted in https://github.com/EFForg/https-everywhere/pull/6995 . Please rebase your changes. I'm not sure why GitHub reports `This branch has no conflicts with the base branch`.

**Comment by gloomy-ghost** [comment]
I think the reason might be the commit of deletion is same as #6995 one (a4a88a7)

Rebased

**Comment by jeremyn** [comment]
I'm still a little confused. In #6995 I merged 73d3123e93720381f3e8c2b6a45d50d0a91f75bd (the squash-and-merged a4a88a70314a85bcb3e401e8ea4c1ac7c3123cf8) which deleted `V2ex.xml`. In this pull request, commit 35f099a078bafbb461cab654dd1a8210fa9fba47 also deletes `V2ex.xml`, and I don't know why GitHub isn't reporting that conflict.

Anyway by rebase I meant please rebase these changes onto master so that it only modifies `V2ex.co.xml` and does not try to delete `V2ex.xml`.

**Comment by gloomy-ghost** [comment]
Before I fixup 2 commits into 35f099a, the hash of deletion commit in this PR is also a4a88a7. But after that I  have no idea either.

**Comment by jeremyn** [comment]
The actual hash merged into master is 73d3123e93720381f3e8c2b6a45d50d0a91f75bd due to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/), not a4a88a70314a85bcb3e401e8ea4c1ac7c3123cf8 .

**Pull request merged**
