### PR TITLE
Update Greek-media.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jsha** [comment]
It looks like this rule formerly rewrote all first-level subdomains of antenna.gr, but now only rewrites antenna.gr and www.antenna.gr. Can you add detail about why? I'm also not sure why this would fix #2098.

**Comment by J0WI** [comment]
I removed the wild card to avoid writing test urls. I didn't found any subdomains exept www. I also added ```static.ant1.gr``` which fixes mixed content issues and may be #2098.

**Comment by jsha** [comment]
Shouldn't this be `platform="mixedcontent"` if it requires the `static.ant1.gr` rewrite to work properly?

**Comment by semenko** [comment]
Want to simply remove antenna.gr from this? They have some cert name issues.

**Comment by J0WI** [comment]
Oh, thats new.
I removed the host.

**Pull request merged**
