### PR TITLE
Change "View All Rules" URL to GitHub.

### PR DESCRIPTION
**Pull request by koops76**
HTTPS Everywhere Atlas seems dead.

### CODE REVIEW

**Comment by jsha** [comment]
FYI @Hainish has a TODO item to fix the build script for the Atlas so it will stay up to date again. Was there some other breakage?

**Comment by koops76** [comment]
@jsha @Hainish I would like to make a new Atlas to replace this one. Should I try?

**Comment by Hainish** [comment]
I've fixed the issue with the Atlas (https://github.com/EFForg/https-everywhere/issues/11247).  Seems to be working now, pending cache expiration.  @koops76 what did you have in mind?

**Comment by koops76** [comment]
@Hainish https://github.com/EFForg/https-everywhere-atlas/pull/1

**Comment by koops76** [comment]
@Hainish I guess I will make a simple test version.

**Comment by koops76** [comment]
ping @Hainish @cowlicks.

**Comment by cowlicks** [comment]
Is this still needed now that HE atlas is updating regularly?

**Comment by koops76** [comment]
@cowlicks I prefer GitHub but it's up to you to decide.

**Pull request closed without merging**
