### PR TITLE
JS refactoring

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by Hainish** [comment]
I won't be able to review this until we have the Embedded WebExtensions code working.  See https://github.com/EFForg/https-everywhere/pull/11639#issuecomment-320374803

**Comment by koops76** [comment]
@Hainish Should I rebase this code on WebExtensions branch?

**Comment by Hainish** [comment]
@koops76 yes I think that would be good

**Comment by koops76** [comment]
@Hainish Same with StandardJS/Airbnb/Google style PRs?

**Comment by Hainish** [comment]
yes would be good

**Comment by koops76** [comment]
@Hainish What about https://github.com/Hainish/https-everywhere/pull/2?

**Comment by koops76** [comment]
@Hainish What about Hainish#2?

**Comment by koops76** [comment]
@Hainish What about Hainish#2?

**Comment by koops76** [comment]
@Hainish Also, can you merge #10773 as it is, I will add the checkbox after this will be merged, `popup.js` and `popup.html` code is terrible. I don't want to modify it before refactoring.

**Pull request closed without merging**
