### PR TITLE
Fix 5745

### PR DESCRIPTION
**Pull request by tomwys**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also add a comment about the issue? This will make maintenance easier.

**Comment by J0WI** [comment]
@tomwys are you still interested in fixing this?

**Comment by tomwys** [comment]
Sorry @J0WI. Lot other things on my head now.

**Comment by theotherlinh** [comment]
I'm guessing something changed recently? It looks like it still goes to the same site, but I'm getting 404 not found

**Pull request closed without merging**
