### PR TITLE
[ProtonMail Hidden Service] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**
ProtonMail just launched a Tor hidden service that requires HTTPS.

https://protonmail.com/blog/tor-encrypted-email/
https://techcrunch.com/2017/01/19/protonmail-adds-tor-onion-site-to-fight-risk-of-state-censorship/
http://www.theregister.co.uk/2017/01/19/protonmail_launches_tor_hidden_service/

### CODE REVIEW

**Comment by lucaspetter** [comment]
The Travis build fails due to a fetch error. This ruleset uses `platform="mixedcontent"` in the same way as other hidden service rulesets (eg. [Facebook](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/FacebookCoreWWWi.onion.xml), [Intercept](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Y6xjgkgwj47us5ca.onion.xml)), so isn't the test supposed to not fetch the URL? I don't understand this.

```
INFO Finished comparing http://protonirockerxow.onion/ -> https://protonirockerxow.onion/. Rulefile: src/chrome/content/rules/ProtoniRockerXow.onion.xml.
ERROR src/chrome/content/rules/ProtoniRockerXow.onion.xml: Fetch error: http://protonirockerxow.onion/ => https://protonirockerxow.onion/: (6, 'Could not resolve host: protonirockerxow.onion')
```

**Comment by jeremyn** [comment]
@lucaspetter HTTPS Everywhere tests are known to fail against .onion addresses. See the discussion in issue #3798. The Facebook and Intercept rulesets you link each fail with `fetch-test.sh` locally and I expect would fail with Travis. I assume they were added as special cases, but I'm not sure.

@Hainish Do you think we should add ProtonMail's new .onion URL as a special case? I think we should.

**Comment by lucaspetter** [comment]
@jeremyn Thanks, now I understand.

**Comment by Hainish** [comment]
@jeremyn Since we've already made exceptions for the Intercept and Facebook, I think it's fine to add Protonmail to the list.

**Comment by lucaspetter** [comment]
@jeremyn @Hainish Where does this exception need to get added?

**Comment by Hainish** [comment]
@lucaspetter I think the way you've added it is correct, but I'll leave it up to the digression of the ruleset maintainers.

**Comment by jeremyn** [comment]
@lucaspetter Please make these small changes:

- [ ] Note `*.protonirockerxow.onion` as `Invalid certificate` at the top
- [ ] Change the filename to `Protonirockerxow.onion.xml` and also update the comment in `ProtonMail.com.xml`
- [ ] Remove the `Direct rewrites` comment, we don't need it

**Comment by lucaspetter** [comment]
@jeremyn Okay, I've made the changes.

**Comment by jeremyn** [comment]
Thanks. This looks fine, other than the fetch error, which we have decided to ignore. Merged.

**Comment by lucaspetter** [comment]
Thanks

**Pull request merged**
