### PR TITLE
Create Free-OCR.com.xml

### LINKED ISSUE #15050: Rule for www.free-ocr.com
Type: new ruleset
Domain: www.free-ocr.com

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #15050

### CODE REVIEW

**Comment by Bisaloo** [comment]
I'm not sure why tests aren't passing...

**Comment by jeremyn** [comment]
I'm getting an `Unable to connect` (what we sometimes call `Connection refused`) error at https://www.free-ocr.com/ , which is what the tests report. Are you seeing something different?

**Comment by jeremyn** [comment]
I get the error from my previous comment in both Firefox and curl.

**Comment by Bisaloo** [comment]
Everything is working fine over both HTTP and HTTPS with Firefox or curl. Maybe this is location dependent. Should I close this then?

**Comment by jeremyn** [comment]
The problem could be location-dependent, though that would be unusual.

I think we should close this. I'm not sure what else to do with it.

**Pull request closed without merging**
