### PR TITLE
Update Itc.cn.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by jeremyn** [comment]
Can you please provide examples for `d1.biz.itc.cn`, `s1.biz.itc.cn`, and `s1.rr.itc.cn` that don't get a 403, along with other examples for `[2-4]` if needed?

**Comment by jeremyn** [comment]
Thanks.

There is no mixed content blocking for either of the `s[1-9]` URLs. Can you give a URL that has a mixed content problem?

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by ivysrono** [comment]
@jeremyn 
https://github.com/EFForg/https-everywhere/pulls/ivysrono
There are several PRs more than one month.

**Pull request merged**
