### PR TITLE
Update Arch.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
- Add new subdomains
- Follow new style guidelines

### CODE REVIEW

**Comment by Bisaloo** [comment]
I edited from a branch that wasn't up-to-date. What can I do to solve this conflict?

**Comment by J0WI** [comment]
You can use `git rebase` to solve conflicts.

**Comment by jeremyn** [comment]
@Bisaloo Are you still interested in working on this?

**Comment by Bisaloo** [comment]
@jeremyn it can be merged now (unless you have suggestions).

I am just unsure what should be done about private subdomains like https://repos.archlinux.org

**Comment by jeremyn** [comment]
Thanks. Please make the following changes:

- [ ] Add a top comment like I have below. For another example of a top comment, see [here](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71). For more information on the `No working URL known` comment, see [here](https://github.com/EFForg/https-everywhere/issues/7662).
```xml
<!--
	Invalid certificate:
		alberich.archlinux.org
		aur-dev.archlinux.org
		aur4.archlinux.org
		gudrun.archlinux.org
		rsync.archlinux.org
		static.archlinux.org
		tracker.archlinux.org

	No working URL known:
		repos.archlinux.org (403)

-->
```
- [ ] Clean up the whitespace, for example remove the extra tab [here](https://github.com/Bisaloo/https-everywhere/blob/8636818b70cd74a512c03fd9eb7dac36351bf8e2/src/chrome/content/rules/Arch.xml#L27) and remove the spaces before `to` [here](https://github.com/Bisaloo/https-everywhere/blob/8636818b70cd74a512c03fd9eb7dac36351bf8e2/src/chrome/content/rules/Arch.xml#L41). Note that we prefer tab indents, following our [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md).
- [ ] Change the `ruleset` `name` to `archlinux.org`
- [ ] Change the filename to `Archlinux.org.xml` (do this in a separate commit by itself, please, to make it easier to see the diff)
- [ ] Remove [these](https://github.com/Bisaloo/https-everywhere/blob/8636818b70cd74a512c03fd9eb7dac36351bf8e2/src/chrome/content/rules/Arch.xml#L28-L37) lines
- [ ] Add `tracker` to the `aur-dev` `rule` like what I have below, and delete the `tracker` rule:
```xml
	<rule from="^http://(aur-dev|tracker)\.archlinux\.org/"
		to="https://bbs.archlinux.org/" />
```
- [ ] We like to sort subdomains in alphabetical order starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group. For example:

```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```

In this specific ruleset, please move the `archlinux.org` and `www.archlinux.org` `target`s to the top.
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?
- [ ] For this pull request, do you mind if I delete your commit messages when I squash-and-merge?

**Comment by Bisaloo** [comment]
I think that's it. Thank you for your help!

I haven't included in the comment URLs found by `sublist3r` if they lead to a 404 error and can't be found on google.

Regarding your last two points, yes, it's fine by me.

**Comment by jeremyn** [comment]
Thanks @Bisaloo.

Can you please however move the top comment outside of the `ruleset` tag, to the very top, like we have [here](https://github.com/EFForg/https-everywhere/blob/84fa856208af9af978c916ec4ac9b1a94789a053/src/chrome/content/rules/glavbukh.ru.xml#L1-L71)?

Also, for

>I haven't included in the comment URLs found by sublist3r if they lead to a 404 error and can't be found on google.

I'm not sure what you mean. Can you give an example?

**Comment by Bisaloo** [comment]
Should I add `nymeria.archlinux.org` in the comment?
```
<!--
	Invalid certificate:
		alberich.archlinux.org
		aur-dev.archlinux.org
		aur4.archlinux.org
		gudrun.archlinux.org
		rsync.archlinux.org
		static.archlinux.org
		tracker.archlinux.org

	No working URL known:
		repos.archlinux.org (403)

	Refused:
		nymeria.archlinux.org

-->
```

`orion.archlinux.org` returns `404`

Otherwise, it's not actually a 404 but I don't know what to do with domains found by sublist3r like
- `celestia.archlinux.org`
- `dom0.archlinux.org` 
- `dragon.archlinux.org`
- `gerolde.archlinux.org`
- `sigurd.archlinux.org`
- `vostok.archlinux.org`

**Comment by jeremyn** [comment]
I see what you mean. There's some judgment involved here.

I don't want to mention subdomains that refuse to connect even with plain HTTP like http://celestia.archlinux.org or http://dom0.archlinux.org.

Also there's a sort of a sequence of potential errors, and if both HTTPS and plain HTTP error but HTTPS errors earlier in the sequence, then you might mention that. For example http://mail.archlinux.org gets a `401` but https://mail.archlinux.org gets `Refused`, and `Refused` is earlier than `401`, so we can mention `mail` as `Refused`. Similarly http://apollo.archlinux.org gets a `404` but https://apollo.archlinux.org gets an `Invalid certificate`, and `Invalid certificate` is before `404` so we can mention `apollo`.

The main reason, in my opinion, that we even list nonworking subdomains is to give information to the next person that looks at the ruleset. They may have a list of subdomains in mind and we want them to know what we've already considered and why some didn't get made into `target`s. On the other hand they are less likely to care about subdomains that appear entirely or almost entirely nonworking, so we leave those off to decrease clutter.

Anyway I've updated the top comment in the checklist with some new subdomains, so please feel free to drop that in, or ask me if you have questions.

**Comment by Bisaloo** [comment]
I agree with you about adding as much as possible in the comment in order to help the next person looking at the ruleset.

I trust your judgment on this and I updated the top comment according to your recommendation.

**Comment by jeremyn** [comment]
Thanks for catching that I left out `apollo` in the modified comment in the checklist. I've updated the comment in the checklist to include `apollo`.

I've also added one new item to the checklist about the `securecookie` tag, along with an explanation.

**Comment by Bisaloo** [comment]
> I've also added one new item to the checklist about the securecookie tag, along with an explanation.

I wouldn't have thought about that but that makes perfect sense.

**Comment by jeremyn** [comment]
Thanks. Can you please also remove the extra tab from the beginning of [this line](https://github.com/Bisaloo/https-everywhere/blob/395de3adc9ff7a6da9319c2f4b3ff073e135ca41/src/chrome/content/rules/Archlinux.org.xml#L54)?

**Comment by jeremyn** [comment]
Thanks again, merged.

**Pull request merged**
