### PR TITLE
Create Wizchan.org.xml

### PR DESCRIPTION
**Pull request by makepost**

### CODE REVIEW

**Comment by jeremyn** [comment]
@makepost Are you still interested in working on this pull request?

**Comment by makepost** [comment]
@jeremyn Yes. Please remind what I need to fix. No feedback here for a long time.

**Comment by jeremyn** [comment]
- [ ] Please make your ruleset look like this:
```xml
<ruleset name="Wizchan.org">
    <target host="wizchan.org" />
    <target host="www.wizchan.org" />
    <target host="lore.wizchan.org" />
    <target host="text.wizchan.org" />
  
    <rule from="^http:"
        to="https:" />
</ruleset>
```
See our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md) for more information or if you plan to submit more pull requests in the future.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
