### PR TITLE
Added th-nuernberg.de (Fixes #5143)

### LINKED ISSUE #5143: [Applied University of Nuremberg] add www.th-nuernberg.de
Please add this https://www.th-nuernberg.de
They don't redirect to https themselves..

### PR DESCRIPTION
**Pull request by Foorack**
Fixes #5143

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

Comment as `mismatch`:
- [ ] https://fh-nuernberg.eu
- [ ] https://www.fh-nuernberg.eu
- [ ] https://th-nuernberg.eu
- [ ] https://www.th-nuernberg.eu

Comment as `self signed`:
- [ ] https://studiengangstest.th-nuernberg.de

Add target:
- [ ] https://studiengangstest.de
- [ ] https://www.studiengangstest.de
- [ ] https://www.efi.th-nuernberg.de
- [ ] https://me.efi.th-nuernberg.de
- [ ] https://medinf.efi.th-nuernberg.de
- [ ] https://fachschaft.in.th-nuernberg.de (and remove from top comment)

Add these where appropriate:
- [ ] https://fh-nuernberg.de
- [ ] https://www.fh-nuernberg.de
- [ ] https://hfmbib.ads1.fh-nuernberg.de
- [ ] https://quadra.ar.fh-nuernberg.de
- [ ] https://bwc188113.bw.fh-nuernberg.de
- [ ] https://vpnssl3.cs.fh-nuernberg.de
- [ ] https://www.efi.fh-nuernberg.de
- [ ] https://db0fhn.efi.fh-nuernberg.de
- [ ] https://schorsch.efi.fh-nuernberg.de
- [ ] https://zuse1.efi.fh-nuernberg.de
- [ ] https://fachschaften.fh-nuernberg.de
- [ ] https://jobboerse.fh-nuernberg.de
- [ ] https://informatik.fh-nuernberg.de
- [ ] https://www.informatik.fh-nuernberg.de
- [ ] https://cryptography.informatik.fh-nuernberg.de
- [ ] https://fachschaft.informatik.fh-nuernberg.de
- [ ] https://fbi.informatik.fh-nuernberg.de
- [ ] https://git.informatik.fh-nuernberg.de
- [ ] https://jobboerse.informatik.fh-nuernberg.de
- [ ] https://oso.informatik.fh-nuernberg.de
- [ ] https://seeyou.informatik.fh-nuernberg.de
- [ ] https://webradio.informatik.fh-nuernberg.de

Also:
- [ ] Add subdomains to all the entries in the top comment, for example `jobboerse.th-nuernberg.de` instead of `jobboerse`
- [ ] In every list of subdomains, sort from the top-level domain reading to the left, with `^` and `www` moved to the top. See my above lists for examples.
- [ ] Change the ruleset name to `TH Nürnberg` (see [this Wikipedia article](https://en.wikipedia.org/wiki/Technische_Hochschule_N%C3%BCrnberg)).

**Comment by Foorack** [comment]
Why did you close the other one?  If anything this is the version that should closed.

**Comment by jeremyn** [comment]
I didn't close the other one, you did: `Foorack closed this 2 days ago`.

**Comment by Foorack** [comment]
Nvm, I saw wrong. This is the new correct one.

I seem to have deleted my fork a few days ago which caused me to loose write accesss to my previous non-merged pull requests.

**Comment by Foorack** [comment]
@jeremyn Does the domain fh-nuernberg also belong to TH Nürnberg?

**Comment by Foorack** [comment]
@jeremyn Updated. Fixed 1 and 3. Didn't understand the sorting but tried to sort it somewhat.

**Comment by jeremyn** [comment]
I've updated the checklist through commit 2377021ecb613152a2223cb035f516bf79fc8cc7. I've also edited the list to be more specific about how to classify some of the URLs.

For sorting, the URLs in the checklist are sorted in the correct way. You can use that as an example.

**Comment by jeremyn** [comment]
I've added https://www.in.th-nuernberg.de to the list under `Add target`.

**Comment by Foorack** [comment]
@jeremyn Updated. Added all domains and sorted them after your list. Sorry for the extra work. I will try to improve next time I submit a new ruleset.

**Comment by jeremyn** [comment]
Thanks again. We're close to being done, just a couple more things:

* `hfmbib.ads1.fh-nuernberg.de` and `db0fhn.efi.fh-nuernberg.de` are under both `Refused` and `Timeout`, but they should just be under `Refused`
* The sorting is still a little off: `fh-nuernberg` should be at the top of `Timeout`; `asta` should be at the top of `Invalid-certificate chain`; the `target`s should be all the `fh-nuernberg`, all the `studiengangstest`, then all the `th-nuernberg`.

**Comment by jeremyn** [comment]
Also, are you okay with how we [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) pull requests? It involves us rewriting commits in your name so I like to check.

**Comment by Foorack** [comment]
@jeremyn Fixed. And yes, I am fine with that.

**Comment by jeremyn** [comment]
Thanks. Looking over the list I notice we're still missing  https://www.efi.th-nuernberg.de as a target. You have it in there as `Other HTTPS failure`. It works for me, does it fail for you or is that a mistake?

**Comment by Foorack** [comment]
@jeremyn https://www.efi.th-nuernberg.de/ has a incomplete chain. https://www.ssllabs.com/ssltest/analyze.html?d=www.efi.th-nuernberg.de&latest Updated to move it to `Invalid-certificate chain`.

**Comment by jeremyn** [comment]
You're right, thanks for seeing that. Apparently to reproduce that error in Firefox I need to both [delete `cert8.db`](https://support.mozilla.org/en-US/questions/878694) and clear my history, or alternately test in a new profile.

Merged.

**Pull request merged**
