### PR TITLE
Make HTTPS Everywhere compatible with e10s (multiprocess firefox)

### LINKED ISSUE #447: HTTPS Everywhere is not e10s compatible
Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1014986

### PR DESCRIPTION
**Pull request by diracdeltas**
Work in progress. As of now, rewrites work and the basic UI features work.

fixes #447 #510 

TODO:
- check for backwards compatibility

### CODE REVIEW

**Comment by jsha** [comment]
@strugee This pull was merged a month and a half ago into master, and is available through the development release. When we are confident in the quality of the development release we will promote it to stable, probably in the next few weeks. In the meantime if you are talking to Firefox Nightly users who are having issues with HTTPS Everywhere, please encourage them to install the development version from https://www.eff.org/https-everywhere and help us test.

Thanks,
Jacob

**Comment by jsha** [comment]
Yes, I fixed the regression in #753, which is included in the development release. Thanks!

**Comment by diracdeltas** [comment]
Is this actually fixed in the stable release? Just checking in based on https://bugzilla.mozilla.org/show_bug.cgi?id=997808 still being open.

**Comment by jsha** [comment]
Not yet fixed in stable. I'm trying to promote 5.0 to stable, which is going slower than expected.

**Pull request merged**
