### PR TITLE
Create 127.net.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
先把注释拆一下吧…其他的明天有空再看

**Comment by gloomy-ghost** [comment]
https://lovepicture.nosdn.127.net/2234303933346505348
https://mail-userthumb.nosdn.127.net/f67aa1965c10333f78d75e98833c54d3_s.jpg
https://onegoods.nosdn.127.net/goods/2491/d0f896aac597931a5429d32d57267793.jpg
https://open-image.nosdn.127.net/b16f89fd2e31407ab4dbf249243ce550.jpg
https://haitao.nosdn1.127.net/onlineipfe50u411092.jpg
https://haitao.nosdn2.127.net/onlineipfe50u411092.jpg
https://haitao.nosdn3.127.net/onlineipfe50u411092.jpg
https://haitao.nosdn4.127.net/onlineipfe50u411092.jpg
https://haitao.nosdn5.127.net/onlineipfe50u411092.jpg

Also:
- [ ] Remove [this test](https://github.com/EFForg/https-everywhere/pull/7653/files#diff-c8672c8f2915177479182048697941ceR20) since it is in a group and there is already a test for the group.

**Comment by gloomy-ghost** [comment]
顺便吐槽下网易的图床我都不敢在学校图书馆打开……

**Comment by ivysrono** [comment]
黄易岂是白叫的

**Comment by gloomy-ghost** [comment]
速度太慢没传完超时了……用 https://open-image.nosdn.127.net/ae2c24368fcd44be82a5ece2510531cf.jpg 观海照片镇一镇那几台思科（逃

我的意思是一组功能相近的域名带一个`test`就行，比如：
<details><summary>Click to expand</summary>

```
	<target host="haitao.nosdn1.127.net" />
	<target host="haitao.nosdn2.127.net" />
	<target host="haitao.nosdn3.127.net" />
	<target host="haitao.nosdn4.127.net" />
	<target host="haitao.nosdn5.127.net" />
		<test url="http://haitao.nosdn5.127.net/onlineipfe50u411092.jpg" />
```
</details>

**Comment by ivysrono** [comment]
<target host="imglf.nosdn.127.net" />
<target host="imglf0.nosdn.127.net" />
<target host="imglf1.nosdn.127.net" />
<target host="imglf2.nosdn.127.net" />
试了下这组还不能互换，所以还是一个一个找了test

**Comment by gloomy-ghost** [comment]
如果这次测试不过的话把`test`和`target`对应起来

过了的话就算了（逃

**Comment by ivysrono** [comment]
还是空一行吧，混在一起看的都眼花了。
老了，不中用了。

**Comment by gloomy-ghost** [comment]
…一想到以后的未来是我们这群孙子的我就好方（00后孤寡老人路过

merged

**Pull request merged**
