### PR TITLE
Updated jenkins.io ruleset.

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] For https://rating.jenkins.io , change `Forbidden` to `No working URL known`. `Forbidden` implies that it works with plain HTTP and only fails with HTTPS, but actually it fails for both. See issue https://github.com/EFForg/https-everywhere/issues/7662 for a discussion on `No working URL known`.

**Comment by Jochen-A-Fuerbacher** [comment]
I actually noticed, that there are working URLs for `rating.jenkins.io`, e.g.: `https://rating.jenkins.io/rate/result.php`

**Comment by jeremyn** [comment]
Good find. Could you please add a `test` for that URL? I've updated the checklist in https://github.com/EFForg/https-everywhere/pull/9109#issuecomment-287412102.

**Comment by Jochen-A-Fuerbacher** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged, original commit messages deleted.

**Pull request merged**
