### PR TITLE
[Calendars] Fix typo

### PR DESCRIPTION
**Pull request by fuglede**
This fixes a typo in a rule which broke most site resources. In particular, this fixes https://github.com/EFForg/https-everywhere/issues/3523.

### CODE REVIEW

**Comment by fuglede** [comment]
The ruleset test coverage test fails with the message

    ERROR src/chrome/content/rules/Calendars.com.xml: No rule or exclusion applies to test URL http://calendars.com/

    ERROR src/chrome/content/rules/Calendars.com.xml: No rule or exclusion applies to test URL http://www.calendars.com/

yet none of the listed URLs are actually test URLs in the ruleset. What gives?

**Comment by donced** [comment]
The test coverage reminds me of [Mobile01.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Mobile01.com.xml) whereby only a single page supports HTTPS. I used reverse exclusion (line 9). This is what I come up with:
```
<!--
	Nonfunctional subdomains:

		- app		(404, mismatched, CN: *.e-dialog.com)
		- reviews	(mismatched, CN: *.ugc.bazaarvoice.com)


	Some (most?) pages redirect to http

-->
<ruleset name="Calendars.com (partial)">

	<target host="calendars.com" />
	<target host="www.calendars.com" />

  	<exclusion pattern="^http://(www\.)?calendars\.com/(?!(css/|img/|js/|user/))" />

		<test url="http://calendars.com/" />
		<test url="http://www.calendars.com/" />
		<test url="http://www.calendars.com/Baby-Animals/cat00172/" />
		<test url="http://www.calendars.com/Bears/cat00173/" />
		<test url="http://www.calendars.com/Big-Cats/cat00174/" />
		<test url="http://www.calendars.com/Jigsaw-Puzzles/" />

	<rule from="^http:"
		to="https:" />

		<test url="http://www.calendars.com/css/common.css" />
		<test url="http://www.calendars.com/img/common/calendarsLogo.gif" />
		<test url="http://www.calendars.com/js/jquery.timer.js" />
		<test url="http://www.calendars.com/user/login.jsp" />
</ruleset>
```

**Comment by J0WI** [comment]
@fuglede still interested in fixing this? Page looks weird atm.

**Comment by fuglede** [comment]
@J0WI: Hm, yeah, my plan was to trace down whatever part of the test coverage checker that was causing this particular behaviour, rather than pushing a workaround. Since I'm a bit low on time these days, having a workaround would provide more value than nothing though.

**Comment by J0WI** [comment]
As far as I can see you just need to add 3 more tests. css, img and user each with and without www. And you should do the same with /js.
You need to exclude both hosts on /$.

There are two more mismatches on link and topcat.
There is some mixed content on blog.

**Comment by fuglede** [comment]
Yeah, the test checker complains because of the lack of tests for <code>/$</code>, but it makes no sense that we require those as the URLs appear in no rules.

**Comment by suryapatt** [comment]
Hi,

I am leading the development team that works for Calendars.com site. Seems the issue is not yet fixed. Calendars.com  still breaks.

**Comment by fuglede** [comment]
Closing as the fix itself was made redundant by #4662 (but it would still be nice to have the test checker fixed).

**Pull request closed without merging**
