### PR TITLE
Greek-travel.xml: Remove outdated tests and rules

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/EFForg/https-everywhere/issues/18893

Note: I am not 100% confident that these fixes are the most appropriate way to solve the problems.

### CODE REVIEW

**Comment by pipboy96** [comment]
If possible, please split this PR into 3 separate PRs, one for each file.

**Comment by jayvdb** [comment]
Moved change which passes CI to https://github.com/EFForg/https-everywhere/pull/18919

Now looking at CI results for the other two.

**Comment by jayvdb** [comment]
(Rebased and added "Update ruleset-whitelist.csv" commit; no other changes)

**Comment by jayvdb** [comment]
https://travis-ci.org/EFForg/https-everywhere/jobs/660131809

> ERROR src/chrome/content/rules/Indymedia.xml: Fetch error: http://athens.indymedia.org/ => https://athens.indymedia.org/: (6, 'Could not resolve host: athens.indymedia.org')

Again I cant reproduce this locally.  It is the only error.

**Comment by jayvdb** [comment]
ping @zoracon .  Not sure why you marked this invalid.

**Comment by pipboy96** [comment]
@jayvdb I see no issues with this PR.

**Review by pipboy96 — APPROVED** [review]

**Pull request merged**
