### PR TITLE
Create ChangeAView.com.xml

### PR DESCRIPTION
**Pull request by Giltyhub**

### CODE REVIEW

**Comment by pipboy96** [comment]
Duplicate?

**Comment by pipboy96** [comment]
LGTM!

**Comment by Giltyhub** [comment]
thanks for spotting that domain, as usual i freaking love your work on this project @pipboy96

**Comment by pipboy96** [comment]
@Giltyhub You can enable `subbrute` using <kbd>-b</kbd> switch for Sublist3r. It will take a lot of time but may spot more domains.

**Pull request merged**
