### PR TITLE
add Vrr.de.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Connection refused`:
- [ ] https://efa3.vrr.de
- [ ] https://wap.vrr.de

Mark as `Invalid certificate`:
- [ ] https://erhebung2017.vrr.de
- [ ] https://schnupperabo.vrr.de
- [ ] https://weihnachtsmaerkte.vrr.de
- [ ] https://zerp.vrr.de

Mark as `Redirect to HTTP`:
- [ ] https://blog.vrr.de

Mark as `Secure connection failed`:
- [ ] https://aiv.vrr.de (and remove from `refused`)

Mark as `Time out`:
- [ ] https://event.vrr.de

Add `target`:
- [ ] https://anzeiger.vrr.de
- [ ] https://campus.vrr.de
- [ ] https://rheinbahn.vrr.de (with a `test`)

**Comment by J0WI** [comment]
Done, but I was not able to reproduce a HTTP redirect on `blog.vrr.de`

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9386/commits/35b77a3bf8c9325b671ef015419dd026541e02f9.

**Comment by J0WI** [comment]
done

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
