### PR TITLE
remove flattr.net

### PR DESCRIPTION
**Pull request by luciancor**

### CODE REVIEW

**Comment by J0WI** [comment]
This works as expected for me, why has it been removed?

**Comment by jeremyn** [comment]
Thanks for the update.

https://static.flattr.net has valid HTTPS so I don't think `flattr.net` should be removed entirely.

Did Flattr document that they are shutting down their `.net` domains?

**Comment by luciancor** [comment]
thanks for the update guys! 
so should we only remove : 	<target host="flattr.net" />	and <target host="www.flattr.net" />
in such cases? those have invalid certificates

**Comment by J0WI** [comment]
```
	<rule from="^http://(?:www\.)?flattr\.net/"
		to="https://flattr.com/" />
```
They get redirected to .com, so everything works fine here.

**Comment by luciancor** [comment]
got it - closing this. Thanks for the feedback!

**Pull request closed without merging**
