### PR TITLE
tuxfamily.org

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
I would prefer to avoid wildcard targets when not all subdomains are covered.
Please also remove non-capturing (`?:`) groups.

**Comment by galeksandrp** [comment]
Improved.

**Comment by J0WI** [comment]
The following hotst has mixed content issues:
blenderclan.tuxfamily.org
scoretarot.tuxfamily.org
geotux.tuxfamily.org
stickyvibe.tuxfamily.org
miniupnp.tuxfamily.org

What's the relation between tuxfamily.org, anwiki.com, glx-dock.org, glx-dock.org and vhffs.org?

**Comment by galeksandrp** [comment]
They are noted in original ruleset and looks like they are projects of TuxFamily.

Should I split it to different rulesets?

**Comment by J0WI** [comment]
Yes, it's easier when they are spitted in to smaller rules.

**Comment by galeksandrp** [comment]
anwiki.com #6728
glx-dock.org #6729
vhffs.org #6730

**Comment by J0WI** [comment]
Thank you!

**Comment by J0WI** [comment]
I fear you need to rebase the other PR's now.

**Pull request merged**
