### PR TITLE
Add ruleset for CerberusApp.com

### PR DESCRIPTION
**Pull request by TonyZTan**

### CODE REVIEW

**Comment by reedy** [comment]
Site seems to force HTTPS. @jsha Is there any use of having rules for sites that already force to HTTPS?

**Comment by TonyZTan** [comment]
@reedy Yes, including sites that already force HTTPS can prevent SSL striping attacks, in which the MITM attacker prevents the 301/302 redirect to HTTPS from reaching the user. In this case, the protection offered by HTTPS-Everywhere is similar to HSTS, except for the fact that many site owners (including this one) fail to send HSTS headers for both the domain with "www" and without. Please see: https://www.eff.org/https-everywhere/faq#faq-Why-does-HTTPS-Everywhere-include-rules-for-sites-like-PayPal-that-already-require-HTTPS-on-all-their-pages?

**Comment by TonyZTan** [comment]
@reedy (Off-topic) Are you also https://en.wikipedia.org/wiki/User:Reedy? That's cool. I am https://en.wikipedia.org/wiki/User:Tony_Tan. I thought your name was familiar but did not realize where I saw it until now. ;)

**Comment by reedy** [comment]
Yup, that'd be me ;)

**Comment by jsha** [comment]
@reedy: Yep, Tony's got it right. Eventually I'd like to be able to delete rules that are truly 100% redundant, i.e. those that overlap with preloaded HSTS rules. But the sslstrip attacks are real, so in the meantime we accept rulesets even for sites that do a 301 redirect to HTTPS.

**Pull request merged**
