### PR TITLE
Update Inspectlet.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by fuglede** [comment]
Thanks for the PR! It looks like the comment on this one is outdated, as inspectlet.com no longer serves a mismatched certificate. If this is indeed the case, could you update that part of it as well?

**Comment by J0WI** [comment]
@renyouguo Could you also add a comment for non-working apidocs.inspectlet.com and blog.inspectlet.com?

**Comment by J0WI** [comment]
@renyouguo are you still interested in working on this?

**Comment by renyouguo** [comment]
@J0WI It is too hard for me to understand^

**Comment by J0WI** [comment]
@renyouguo Just add the following on the top:
```
<!--
    Mismatched:
        - apidocs.inspectlet.com

    Mixed Content:
        - blog.inspectlet.com
-->
```
But use tabs instead of spaces.

**Comment by renyouguo** [comment]
#4575

**Pull request closed without merging**
