### PR TITLE
adv.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset! Please:

* Organize the top comment like our other rulesets ([examples](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=problematic+domains))
* Remove http://audicenter.s.adv.ru because it doesn't exist
* Note webmail.adv.ru as a mismatch

**Comment by galeksandrp** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks. Also:

- [ ] Remove the duplicates for `arezka.us.groups.adv.ru` , `www.kr-pro.us.groups.adv.ru` , `rassvet-loft.us.groups.adv.ru` , `www.loko.us.groups.adv.ru` , and `shop.loko-copy.us.groups.adv.ru` in the top comment

**Comment by galeksandrp** [comment]
Removed, thanks!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
