### PR TITLE
[Valley First Credit Union] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

- [ ] Note `dashband.valleyfirst.com` as `Incomplete certificate chain`

Add targets:
- [ ] autodiscover.valleyfirst.com
- [ ] keepingitsimple.valleyfirst.com
- [ ] insurance.valleyfirst.com
- [ ] lyncdiscover.valleyfirst.com
- [ ] webmail.valleyfirst.com

**Comment by lucaspetter** [comment]
Okay, new targets and note added.

**Comment by lucaspetter** [comment]
Added new target found with Sublist3r.

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Pull request merged**
