### PR TITLE
Update Washington_Free_Beacon.xml

### LINKED ISSUE #3053: [broken ruleset] Washington Free Beacon (partial)
Breaks the 'stylesheet'

http://freebeacon.com/politics/leaked-audio-clinton-says-supreme-court-is-wrong-on-second-amendment/

### PR DESCRIPTION
**Pull request by terrorist96**
Fixes #3053

### CODE REVIEW

**Comment by fuglede** [comment]
Added a comment at https://github.com/EFForg/https-everywhere/issues/3053#issuecomment-148937474.

**Comment by fuglede** [comment]
Thanks for the update; and yep, this is functional.  However, the comment in <code>Washington_Free_Beacon.xml</code> is actually incorrect now. You could update it to reflect what's wrong with the rules (so that future ruleset editors can save a bit of time).

**Comment by terrorist96** [comment]
The comments? The "breaks site" note? What do you want it to say? Breaks stylesheet?

**Comment by fuglede** [comment]
Ah, nah, sorry, I was thinking, for instance, about the part that says that "For problematic rules, see Washington_Free_Beacon-problematic.xml", or the one that states that <code>s[1-4]</code> works.

**Comment by terrorist96** [comment]
And now?

**Comment by terrorist96** [comment]
Want me to add anything specific in order to get it merged?

**Comment by fuglede** [comment]
Looks good to me; thanks. As one minor note, the host <code>www.freebeacon.com</code> is actually covered twice in the ruleset; by its own target as well as by the wildcard one. Maybe this is something that the tests should look for.

**Pull request merged**
