### PR TITLE
reenable usrportage.de.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] The only blocked mixed content is a GitHub follow button, so I don't think this needs to be `platform="mixedcontent"`,

**Comment by J0WI** [comment]
platform removed.

**Comment by jeremyn** [comment]
What does `secured by us.` mean in the comment?

**Comment by J0WI** [comment]
We have a `Ghbtns.com.xml` rule, so even if the user allows mixed content it will be secured.

**Comment by jeremyn** [comment]
Okay, thanks. Merged.

**Pull request merged**
