### PR TITLE
Update Deezer.xml (#4768)

### PR DESCRIPTION
**Pull request by jwatt**
Disable ruleset since the navigation bar is broken.

### CODE REVIEW

**Comment by jwatt** [comment]
Note that the comments added in the commit explain why HTTPS Everywhere doesn't work with deezer.com.

**Comment by J0WI** [comment]
Thanks for debugging this!
What about static resources from `e-cdns-files.dzcdn.net`? Do we run in any problems if we only redirect them?

**Comment by jwatt** [comment]
Sure thing!
I don't see any requests to `e-cdns-files.dzcdn.net` while navigating around deezer.com. I do see requests to `cdn-images.deezer.com` and `e-cdn-files.deezer.com` which I added commented out to Deezer.xml (the comment explains why).

**Comment by J0WI** [comment]
I have such requests on `https://www.deezer.com/us/` without being logged in.

**Comment by jwatt** [comment]
It seems when you're NOT logged in, `deezer.com` uses HTTP*S*. It's only after you're logged in that it redirects everything to plain-http. So I think all the sub-resources you're seeing load when loading `https://www.deezer.com/us/` will be made via HTTP*S*, including those from `e-cdns-files.dzcdn.net`. In fact it seems that `e-cdns-files.dzcdn.net` **only** serves content over HTTP*S*. For example, [this CSS file](https://e-cdns-files.dzcdn.net/cache/css/bootstrap-a66521b84dab22cf9d1ac7a7fc40cc10.css) will not load (404) if you change the URL scheme to plain-'http'.

**Comment by J0WI** [comment]
So maybe we could rewrite some resources to this host but since this host behaves very bad on https I'm fine with disabling it.

**Pull request merged**
