### PR TITLE
add ruleset for Wien-IT

### PR DESCRIPTION
**Pull request by numismatika**
adds a rule to cover most of the domains administrated by the it department of the austrian capital city

### CODE REVIEW

**Comment by semenko** [comment]
Hm, looks like there are some invalid cert names in here, e.g. mobile.buergersolarkraftwerk.at

**Comment by numismatika** [comment]
The data was ripped from the alternative names on the main certificate, which seems to have changed a little meanwhile.

**Comment by numismatika** [comment]
@semenko 
I removed the mobile page now and added a few other domains.
Anything else that needs attention before merging?

**Comment by semenko** [comment]
Awesome -- thanks! :+1:

**Pull request merged**
