### PR TITLE
Update Upaiyun.com.xml

### PR DESCRIPTION
**Pull request by renyouguo**
I do not know how to disable the mgpyh.b0.upaiyun.com

### CODE REVIEW

**Comment by J0WI** [comment]
You should make an exclusion.
Please see https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by renyouguo** [comment]
@J0WI Would you merge this?

**Comment by J0WI** [comment]
Please add a comment why this exclusion is needed.

**Comment by renyouguo** [comment]
@J0WI Done.
I have 70+ PRs lgtm. https://github.com/EFForg/https-everywhere/pulls/renyouguo
Would you please check them?

**Comment by J0WI** [comment]
This conflicts, please rebase your branch.

**Comment by renyouguo** [comment]
#5163

**Pull request closed without merging**
