### PR TITLE
Add mangagamer.com

### PR DESCRIPTION
**Pull request by nixxquality**

### CODE REVIEW

**Comment by nixxquality** [comment]
This website is a web store so you should treat it with higher priority.

**Comment by J0WI** [comment]
Could you please do the steps described here?
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains

**Comment by nixxquality** [comment]
There's a slight problem with that; it seems MangaGamer have a wildcard DNS record but only mangagamer.com and www.mangagamer.com are recognized in the SSL certificate.
Also, all the subdomains just point to the same front page.
What do you want me to do?

**Comment by J0WI** [comment]
Okay, therefore I'm already happy when you document this behavior with a comment.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
