### PR TITLE
slack.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
This host is HSTS preloaded by browsers anyway, so it don't need to be in HTTPS Everywhere.
But you can secure the following hosts:
```
a.slack-edge.com
downloads.slack-edge.com
platform.slack-edge.com
(www and ^ do not exist)

slackhq.com
www.slackhq.com

slackatwork.com
www.slackatwork.com
```

**Comment by galeksandrp** [comment]
Done.

**Comment by J0WI** [comment]
Thanks!

**Comment by J0WI** [comment]
Just realized that you missed `downloads.slack-edge.com`.
See https://slack.com/downloads for usage (bins live there).

**Comment by galeksandrp** [comment]
Added, thanks!

**Pull request merged**
