### PR TITLE
Add Ubook.com

### PR DESCRIPTION
**Pull request by eduardoklosowski**

### CODE REVIEW

**Comment by J0WI** [comment]
There is a bunch of subdomains for this domain.
Please have a look at our [guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) about how to find them.

It's important for future maintenance to document all working and broken subdomains.

**Comment by eduardoklosowski** [comment]
I identify and add ads.ubook.com.

**Comment by J0WI** [comment]
@eduardoklosowski there are much more

**Comment by eduardoklosowski** [comment]
No, unfortunately I could not identify the other domains and I not have free time now for do it.

**Comment by jeremyn** [comment]
Okay, thanks @eduardoklosowski . I'm closing this pull request, but please feel free to reopen it with a comment or create a new pull request later when you're able to work on this some more.

**Pull request closed without merging**
