### PR TITLE
[automattic.com] New ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by J0WI** [comment]
This domain was added in 73b763ffb70fe06e5ab4514c6eb3badc53a0aada and removed in 143128b3f9b647c3a07aa3063239e42f6a3e055f

How do we handle this?
@fuglede @semenko @jsha

**Comment by semenko** [comment]
We don't have a great way of handling this :(

We might want to rethink our mechanism for storing rules, especially as TLS adoption expands. Our current "throw a bunch of .xml files in a folder" strategy could definitely be improved.

**Comment by fuglede** [comment]
To make sure I understand: what is the issue exactly? That one is not automatically exposed to the information about the ruleset having existed previously, or something more concrete than that?

**Comment by semenko** [comment]
I think that's correct. Pondering some other rule storage options that might address this.

**Comment by fuglede** [comment]
I don't necessarily think that that's a big issue, but one simple way out of it -- if we were better at keeping disabled rulesets out of memory at least -- would be to only ever default_off ruleset files instead of deleting them.

**Comment by semenko** [comment]
Agreed -- though I do think we should ponder reorganizing our ruleset chaos. I'll make an issue at some point...

**Comment by J0WI** [comment]
My question was about how we handle such scenarios:
Reverting the remove or just merging the new one?

**Pull request merged**
