### PR TITLE
Spring cleaning 2016

### PR DESCRIPTION
**Pull request by RReverser**
First and foremost – apologies for the amount of changes here. I can understand if you won't want to merge that many at once, but I believe that such clean up is long awaited and would benefit all of us.

---

This replaces all the rulesets that have only rules in the form of
```xml
<rule from="^http://(A\.|B\.|C\.|...)?domain\.com/" to="https://$1domain.com/" />
```
to match the [Ruleset Style Guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) by generating list of explicit target domains + trivial
```xml
<rule from="^http:" to="https:" />
```
rule which is also better optimizable by replacer engine.

Those changes were auto-generated and re-checked to be at least valid XML.

During the generation, following rule mistakes were automatically found:
```javascript
[ 'www.ao2.it'; ] 'ao2.it' '^http://(www\\.)?ao2\\.it/'
[ 'cityemail.com', 'www.cityemail.com'; ] 'citymail.com' '^http://(www\\.)?citymail\\.com/'
[ 'cityemail.com', 'www.cityemail.com'; ] 'www.citymail.com'; '^http://(www\\.)?citymail\\.com/'
[ 'claws-mail.org', 'www.claws-mail.org'; ] 'git.claws-mail.org' '^http://(git\\.|www\\.)?claws-mail\\.org/'
[ '*.hohndel.org' ] 'hohndel.org' '^http://(subsurface\\.|trac\\.)?hohndel\\.org/'
[ 'consortiumlibrary.org', 'www.consortiumlibrary.org'; ] 'consortiumlibrary.com' '^http://(www\\.)?consortiumlibrary\\.com/'
[ 'consortiumlibrary.org', 'www.consortiumlibrary.org'; ] 'www.consortiumlibrary.com'; '^http://(www\\.)?consortiumlibrary\\.com/'
[ 'eltatar.com', '*.eltatar.com' ] 'eltartar.com' '^http://(www\\.)?eltartar\\.com/'
[ 'eltatar.com', '*.eltatar.com' ] 'www.eltartar.com'; '^http://(www\\.)?eltartar\\.com/'
[ 'gleam.io' ] 'js.gleam.io' '^http://(js\\.)?gleam\\.io/'
[ 'marshut.net', 'www.marshut.net'; ] 'marsnet.net' '^http://(www\\.)?marsnet\\.net/'
[ 'marshut.net', 'www.marshut.net'; ] 'www.marsnet.net'; '^http://(www\\.)?marsnet\\.net/'
[ 'nexway.com', '*.nexway.com' ] 'nexaway.com' '^http://(www\\.)?nexaway\\.com/'
[ 'nexway.com', '*.nexway.com' ] 'www.nexaway.com'; '^http://(www\\.)?nexaway\\.com/'
[ 'orionmagazine.org', 'www.orionmagazine.org'; ] 'orionmagazine.com' '^http://(www\\.)?orionmagazine\\.com/'
[ 'orionmagazine.org', 'www.orionmagazine.org'; ] 'www.orionmagazine.com'; '^http://(www\\.)?orionmagazine\\.com/'
[ '*.peer1.com' ] 'partners.peer1.ca' '^http://(www\\.)?partners\\.peer1\\.ca/'
[ '*.peer1.com' ] 'www.partners.peer1.ca'; '^http://(www\\.)?partners\\.peer1\\.ca/'
[ 'redferret.net', '*.redferret.net' ] 'theferret.net' '^http://(www\\.)?theferret\\.net/'
[ 'redferret.net', '*.redferret.net' ] 'www.theferret.net'; '^http://(www\\.)?theferret\\.net/'
[ 'scripps.edu', 'www.scripps.edu'; ] 'admissions.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
[ 'scripps.edu', 'www.scripps.edu'; ] 'education.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
[ 'scripps.edu', 'www.scripps.edu'; ] 'vpn.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
[ 'sirportly.com', 'www.sirportly.com'; ] 'app.sirportly.com' '^http://(app\\.|www\\.)?sirportly\\.com/'
[ 'space2u.com', 'www.space2u.com'; ] 'owa.space2u.com' '^http://(owa\\.|webmail2\\.|www\\.)?space2u\\.com/'
[ 'space2u.com', 'www.space2u.com'; ] 'webmail2.space2u.com' '^http://(owa\\.|webmail2\\.|www\\.)?space2u\\.com/'
[ 'subeta.net', 'www.subeta.net'; ] 'avatar.subeta.net' '^http://(avatar\\.|images\\.|www\\.)?subeta\\.net/'
[ 'subeta.net', 'www.subeta.net'; ] 'images.subeta.net' '^http://(avatar\\.|images\\.|www\\.)?subeta\\.net/'
[ 'twinings.co.uk', 'www.twinings.co.uk'; ] 'shop.twinings.co.uk' '^http://(shop\\.|www\\.)?twinings\\.co\\.uk/'
[ 'webstaurantstore.com', 'www.webstaurantstore.com'; ] 'cdn.webstaurantstore.com' '^http://(cdn\\.|cdnimg\\.|www\\.)?webstaurantstore\\.com/'
[ 'webstaurantstore.com', 'www.webstaurantstore.com'; ] 'cdnimg.webstaurantstore.com' '^http://(cdn\\.|cdnimg\\.|www\\.)?webstaurantstore\\.com/'
[ 'b-linked.bbyo.org' ] 'www.b-linked.bbyo.org'; '^http://(www\\.)?b-linked\\.bbyo\\.org/'
[ 'shopstyle.*',
  'www.shopstyle.*',
  'shopstyle.co.*',
  '*.shopstyle.co.jp',
  '*.shopstyle.co.uk',
  '*.shopstyle.com',
  'shopstyle.com.au',
  '*.shopstyle.com.au',
  '*.shopstyle.de',
  '*.shopstyle.fr' ] 'shopsense.co.jp' '^http://(www\\.)?shopsense\\.co\\.jp/'
[ 'shopstyle.*',
  'www.shopstyle.*',
  'shopstyle.co.*',
  '*.shopstyle.co.jp',
  '*.shopstyle.co.uk',
  '*.shopstyle.com',
  'shopstyle.com.au',
  '*.shopstyle.com.au',
  '*.shopstyle.de',
  '*.shopstyle.fr' ] 'www.shopsense.co.jp' '^http://(www\\.)?shopsense\\.co\\.jp/'
```
where each line is in form of `[...targets], mismatchHost, rule.from`.

Those mistakes point to mismatched domains that are matched by regexp (auto-generated from it), but do not match any of the `<target host />` items in the ruleset. As you can see, in most cases such mismatches mean either invalid regexp or `<target host />` or pure mistypes - in any case, rule becomes invalid, but I didn't change those as it needs manual fixes one by one, and decided to leave that out of scope of this PR.

Then, some more potential errors were caught where rule.from matches our expected pattern but rule.to changes the base domain:
```
^http://(www\.)?stowesports\.com/ https://$1[stowesports.com/
^http://(my\.|www\.)?atlanticmetro\.net/ https://$1my.atlanticmetro.net/
^http://(www\.)?codehs\.com/ https://$1codehs/
^http://(www\.)?hiawatha-webserver\.org/ https://$1hiawatah-webserver.org/
^http://(www\.)?juniperresearch\.com/ https://$1junipersearch.com/
^http://(www\.)?portmorgan\.com/ https://$1portmorgan.com//
^http://(www\.)?rylwarfare\.net/ https://$1rylwarefare.net/
^http://(www\.)?as\.au\.edu/ https://$1as.eu.edu/
^http://(www\.)?vkontakte\.ru/ https://$1vk.com/
```

Some of those might be proper origin changes, but it's apparent that most are actually mistypes and thus incorrect (again, needs manual fix - didn't perform as part of this PR, but decided to report).

### CODE REVIEW

**Comment by jsha** [comment]
Thanks for doing this! Before diving in to review all the changes, could you submit a separate PR with just the script you used to find and implement these changes? We can then review that script for correctness, which will probably be more efficient than trying to check all of these by hand. We would still, of course, want to spot check things after running it.

**Comment by RReverser** [comment]
@jsha Sure, let me decouple it from some of our internal code and I'll post as a gist (I still need to warn that it might be rather ugly as I wrote it just for a one-off execution :) ).

**Comment by RReverser** [comment]
Alright, updated script to include different stages that I initially included by modifying script + sending separate commits.

Now it can do all of the stages, and also preserves existing formatting more aggressively for cleaner diffs.

Rebased & pushed.

Script itself is available here: https://gist.github.com/RReverser/e90ddc939febb1b976a6

I know that it might be not very clear (as I said, was meant for one-off execution and removal), so please let me know should you have any questions.

**Comment by RReverser** [comment]
Oh, and just in case - some updated logs:
```
^http://(www\.)?0xbadc0de\.be/ https://blog.0xbadc0de.be/
^http://(www\.)?1cart\.co\.nz/ https://1cart.com/
^http://(www\.)?511tactical\.com/ https://www.511tactical.com/
^http://(www\.)?stowesports\.com/ https://$1[stowesports.com/
^http://(www\.)?aarhus\.dk/ https://www.aarhus.dk/
^http://(www\.)?adagio\.com/ https://www.adagio.com/
^http://(www\.)?alltubedownload\.net/ https://alltube.herokuapp.com/
^http://(www\.)?amoena\.com/ https://www.amoena.com/
^http://(www\.)?andrewmunsell\.com/ https://www.andrewmunsell.com/
^http://(www\.)?anidb\.net/ https://anidb.net/
^http://(www\.)?antiphishing\.org/ https://$1apwg.org/
^http://(www\.)?ao2\.it/ https://$1.ao2.it/
^http://(my\.|www\.)?atlanticmetro\.net/ https://$1my.atlanticmetro.net/
^http://(www\.)?avonandsomerset\.police\.uk/ https://www.avonandsomerset.police.uk/
^http://(www\.)?ballerup\.dk/ https://www.ballerup.dk/
^http://(jobs\.)?barclays\.co\.uk/ https://www.$1barclays.co.uk/
^http://(www\.)?bart\.gov/ https://www.bart.gov/
^http://(www\.)?bike24\.de/ https://www.bike24.de/
^http://(www\.)?billetten\.dk/ https://www.billetten.dk/
^http://(www\.)?boligejer\.dk/ https://boligejer.dk/
^http://(www\.)?bortarsasag\.hu/ https://www.bortarsasag.hu/
^http://(www\.)?brashear\.me/ https://brashear.me/
^http://(www\.)?bruteforce\.gr/ https://bruteforce.gr/
^http://(www\.)?btp\.police\.uk/ https://www.btp.police.uk/
^http://(www\.)?bussgods\.se/ https://www.bussgods.se/
^http://(www\.)?calispora\.org/ https://calispora.org/
^http://(www\.)?careers\.fi/ https://careers.fi/
^http://(www\.)?changeip\.com/ https://www.changeip.com/
^http://(www\.)?chitika\.net/ https://$1chitika.com/
[ 'cityemail.com', 'www.cityemail.com' ] 'www.citymail.com' '^http://(www\\.)?citymail\\.com/'
[ 'claws-mail.org', 'www.claws-mail.org' ] 'git.claws-mail.org' '^http://(git\\.|www\\.)?claws-mail\\.org/'
^http://(www\.)?codehs\.com/ https://$1codehs/
^http://(www\.)?comingolstadt\.de/ https://comingolstadt.de/
^http://(www\.)?commonplacebooks\.com/ https://commonplacebooks.squarespace.com/
[ 'consortiumlibrary.org', 'www.consortiumlibrary.org' ] 'www.consortiumlibrary.com' '^http://(www\\.)?consortiumlibrary\\.com/'
^http://(www\.)?cryptome\.info/ https://cryptome.org/
^http://(www\.)?broadbandreports\.com/ https://www.dslreports.com/
^http://(www\.)?dailyinfo\.co\.uk/ https://www.dailyinfo.co.uk/
^http://(www\.)?deichmann\.com/ https://www.deichmann.com/
^http://(www\.)?dennikn\.sk/ https://dennikn.sk/
^http://(www\.)?dispenser\.tf/ https://dispenser.tf/
^http://(www\.)?dmjx\.dk/ https://www.dmjx.dk/
^http://(www\.)?db\.tt/ https://db.tt/
^http://(www\.)?dynu\.com/ https://www.dynu.com/
^http://(dl\.)?ed\.gov/ https://www.$1ed.gov/
[ 'eltatar.com', '*.eltatar.com' ] 'www.eltartar.com' '^http://(www\\.)?eltartar\\.com/'
^http://(www\.)?ems-ph\.org/ https://www.ems-ph.org/
^http://(www\.)?essex\.police\.uk/ https://www.essex.police.uk/
^http://(www\.)?evm\.dk/ https://www.evm.dk/
^http://(www\.)?fewo-mehrtens\.de/ https://www.fewo-mehrtens.de/
^http://(www\.)?fileformat\.info/ https://www.fileformat.info/
^http://(www\.)?flybuys\.com\.au/ https://www.flybuys.com.au/
^http://(www\.)?foodler\.com/ https://www.foodler.com/
^http://(www\.)?forevernew\.com\.au/ https://www.forevernew.com.au/
^http://(www\.)?fosscon\.us/ https://fosscon.us/
^http://(www\.)?frederikssund\.dk/ https://www.frederikssund.dk/
^http://(www\.)?fusion-lifestyle\.com/ https://www.fusion-lifestyle.com/
^http://(www\.)?givekidstheworld\.org/ https://$1gktw.org/
^http://(www\.)?givskudzoo\.dk/ https://www.givskudzoo.dk/
[ 'gleam.io' ] 'js.gleam.io' '^http://(js\\.)?gleam\\.io/'
^http://(www\.)?gwent\.police\.uk/ https://www.gwent.police.uk/
^http://(www\.)?binera\.de/ https://www.hartwork.org/
^http://(www\.)?hastexo\.com/ https://www.hastexo.com/
^http://(www\.)?heino-cykler\.dk/ https://www.heino-cykler.dk/
^http://(www\.)?helsingor\.dk/ https://www.helsingor.dk/
^http://(www\.)?herts\.police\.uk/ https://www.herts.police.uk/
^http://(www\.)?hiawatha-webserver\.org/ https://$1hiawatah-webserver.org/
^http://(www\.)?hoeringsportalen\.dk/ https://hoeringsportalen.dk/
^http://(www\.)?hoodline\.com/ https://www.hoodline.com/
^http://(research\.)?ibm\.com/ https://www.$1ibm.com/
^http://(www\.)?jammerbugt\.dk/ https://www.jammerbugt.dk/
^http://(www\.)?jobfinder\.dk/ https://www.jobfinder.dk/
^http://(www\.)?jobzonen\.dk/ https://www.jobzonen.dk/
^http://(www\.)?journalistforbundet\.dk/ https://journalistforbundet.dk/
^http://(www\.)?juniperresearch\.com/ https://$1junipersearch.com/
^http://(borgerservice\.|www\.)?kk\.dk/ https://www.kk.dk/
^http://(www\.)?kabeldeutschland\.de/ https://www.kabeldeutschland.de/
^http://(www\.)?kommaer\.dk/ https://kommaer.dk/
^http://(www\.)?korruption\.dk/ https://korruption.dk/
^http://(es\.|fr\.|it\.)?lastminute\.com/ https://www.$1lastminute.com/
^http://(www\.)?marketwatch\.com/ https://secure.marketwatch.com/
^http://(www\.)?marsnet\.net/ https://$1marshut.net/
^http://(www\.)?mathjobs\.org/ https://www.mathjobs.org/
^http://(www\.)?mentalhealth\.asn\.au/ https://www.mentalhealth.asn.au/
^http://(www\.)?moverall\.com/ https://www.moverall.com/
[ 'nexway.com', '*.nexway.com' ] 'www.nexaway.com' '^http://(www\\.)?nexaway\\.com/'
^http://(www\.)?opal\.com\.au/ https://www.opal.com.au/
^http://(www\.)?openmpt\.org/ https://openmpt.org/
[ 'orionmagazine.org', 'www.orionmagazine.org' ] 'www.orionmagazine.com' '^http://(www\\.)?orionmagazine\\.com/'
[ '*.peer1.com' ] 'www.partners.peer1.ca' '^http://(www\\.)?partners\\.peer1\\.ca/'
^http://(www\.)?police\.uk/ https://www.police.uk/
^http://(www\.)?portmorgan\.com/ https://$1portmorgan.com//
^http://(www\.)?instaradio\.com/ https://$1raur.co/
^http://(www\.)?rylwarfare\.net/ https://$1rylwarefare.net/
^http://(www\.)?rasende\.dk/ https://rasende.dk/
[ 'redferret.net', '*.redferret.net' ] 'www.theferret.net' '^http://(www\\.)?theferret\\.net/'
^http://(www\.)?reethus-adeline\.de/ https://www.reethus-adeline.de/
^http://(www\.)?rettighedsalliancen\.dk/ https://www.rettighedsalliancen.dk/
^http://(img\.|pub\.)?content\.samsumg\.cn/ https://$1content.samsung.cn/
[ 'scripps.edu', 'www.scripps.edu' ] 'admissions.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
[ 'scripps.edu', 'www.scripps.edu' ] 'education.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
[ 'scripps.edu', 'www.scripps.edu' ] 'vpn.scripps.edu' '^http://(admissions\\.|education\\.|vpn\\.|www\\.)?scripps\\.edu/'
^http://(www\.)?shoeshow\.com\.au/ https://www.shoeshow.com.au/
[ 'shopstyle.*',
  'www.shopstyle.*',
  'shopstyle.co.*',
  '*.shopstyle.co.jp',
  '*.shopstyle.co.uk',
  '*.shopstyle.com',
  'shopstyle.com.au',
  '*.shopstyle.com.au',
  '*.shopstyle.de',
  '*.shopstyle.fr' ] 'www.shopsense.co.jp' '^http://(www\\.)?shopsense\\.co\\.jp/'
[ 'sirportly.com', 'www.sirportly.com' ] 'app.sirportly.com' '^http://(app\\.|www\\.)?sirportly\\.com/'
^http://(www\.)?allerderm\.com/ https://allerderm.com/
^http://(www\.)?snoonet\.org/ https://www.snoonet.org/
[ 'space2u.com', 'www.space2u.com' ] 'owa.space2u.com' '^http://(owa\\.|webmail2\\.|www\\.)?space2u\\.com/'
[ 'space2u.com', 'www.space2u.com' ] 'webmail2.space2u.com' '^http://(owa\\.|webmail2\\.|www\\.)?space2u\\.com/'
^http://(www\.)?strasbourg\.eu/ https://www.strasbourg.eu/
[ 'subeta.net', 'www.subeta.net' ] 'avatar.subeta.net' '^http://(avatar\\.|images\\.|www\\.)?subeta\\.net/'
[ 'subeta.net', 'www.subeta.net' ] 'images.subeta.net' '^http://(avatar\\.|images\\.|www\\.)?subeta\\.net/'
^http://(www\.)?synchronicer\.dk/ https://www.synchronicer.dk/
^http://(space\.)?dtu\.dk/ https://www.$1dtu.dk/
^http://(www\.)?tpfrb\.dk/ https://tpfrb.dk/
^http://(www\.)?trakehner-nord-west\.de/ https://www.trakehner-nord-west.de/
[ 'twinings.co.uk', 'www.twinings.co.uk' ] 'shop.twinings.co.uk' '^http://(shop\\.|www\\.)?twinings\\.co\\.uk/'
^http://(www\.)?as\.au\.edu/ https://$1as.eu.edu/
^http://(conferences\.|ogr\.)?uillinois\.edu/ https://www.$1uillinois.edu/
^http://(ci\.|proxy\.)?uchicago\.edu/ https://www.$1uchicago.edu/
^http://(www\.)?noc\.ac\.uk/ https://noc.ac.uk/
^http://(hpi\.)?uni-potsdam\.de/ https://www.$1uni-potsdam.de/
^http://(www\.)?urbanartcloud\.com/ https://urbanartcloud.com/
[ 'vce.com', 'www.vce.com' ] 'static.vce.com' '^http://(static\\.|www\\.)?vce\\.com/'
^http://(www\.)?vkontakte\.ru/ https://$1vk.com/
^http://(bioinformatics\.|vbi\.)?vt\.edu/ https://www.$1vt.edu/
^http://(www\.)?wageworks\.com/ https://www.wageworks.com/
^http://(www\.)?wanikani\.com/ https://www.wanikani.com/
[ 'webstaurantstore.com', 'www.webstaurantstore.com' ] 'cdn.webstaurantstore.com' '^http://(cdn\\.|cdnimg\\.|www\\.)?webstaurantstore\\.com/'
[ 'webstaurantstore.com', 'www.webstaurantstore.com' ] 'cdnimg.webstaurantstore.com' '^http://(cdn\\.|cdnimg\\.|www\\.)?webstaurantstore\\.com/'
^http://(www\.)?west-midlands\.police\.uk/ https://www.west-midlands.police.uk/
[ 'wizards.com',
  'images.community.wizards.com',
  'www.wizards.com' ] 'accounts.wizards.com' '^http://(accounts\\.|www\\.)?wizards\\.com/'
^http://(www\.)?wurfljs\.com/ https://wurfljs.com/
^http://(www\.)?ysu\.edu/ https://swww.ysu.edu/
^http://(www\.)?b-linked\.bbyo\.org/ https://b-linked.bbyo.org/
^http://(www\.)?donmai\.us/ https://danbooru.donmai.us/
^http://(consultation\.|eforms\.)?rbkc\.gov\.uk/ https://www.$1rbkc.gov.uk/
^http://(www\.)?slimerjs\.org/ https://slimerjs.org/
^http://(www\.)?smart\-dsl\.net/ https://www.smartone.de/
^http://(www\.)?spamcop\.net/ https://www.spamcop.net/
^http://(www\.)?utbm\.fr/ https://www.utbm.fr/
^http://(www\.)?vitrinepix\.com\.br/ https://www.vitrinepix.com.br/
^http://(www\.|m\.)?xkcd\.org/ https://$1xkcd.com/
^http://(www\.)?yplanapp\.com/ https://yplanapp.com/
```

**Comment by RReverser** [comment]
Updated script with a more human-readable version by using https://github.com/VerbalExpressions/JSVerbalExpressions instead of manually written regexp for matching other regexps.

**Comment by RReverser** [comment]
@jsha Any thoughts / updates on this? There is much more new changes coming in parallel, and this PR starts getting conflicts. Would be nice to know whether you are interested and thus whether it makes sense to try to keep it up-to-date and fix those conflicts.

**Comment by jsha** [comment]
I am definitely interested in this. However, it's a huge programmatic change, so I want to be really sure we get the program right before we pull the trigger. So I need to take some time and review your script carefully, and do some thorough spot checking. I assume once it's fully reviewed, it will be relatively easy to re-run?

Also, one thing that would be helpful in evaluating the output of broken rules for manual review: Can you exclude rulesets that have a non-empty default_off? Also, if you wind up having the time or inclination, the check for broken rules would be very useful to have in our ongoing unittests. Ideally it would fit in with the existing Python code for https-everywhere-checker, but if Node is your preference, that would still be very useful.

**Comment by fuglede** [comment]
I noticed (since it was mentioned on IRC) that this also covers all rules of the form 

    <rule from="^http://(www\.)?example\.com/" to="https://example.com/">

and

    <rule from="^http://(www\.)?example\.com/" to="https://www.example.com/">.

Is this intended? The ruleset style guide as of right now does not really care about those; in fact, <code>(www\\.)?</code> is even mentioned as an example of a group that one might use, and in these cases, the readability benefit seems negligible.

**Comment by RReverser** [comment]
> I assume once it's fully reviewed, it will be relatively easy to re-run?

Yeah, sure. For now, in order not to be blocked, I just included the optimization pass to our build process and looks like all 180K URLs we're testing against match rewrites produced by HTTPS Everywhere built-in rewriter.

> Can you exclude rulesets that have a non-empty default_off? 

Yeah, that's trivial to do.

> the check for broken rules would be very useful to have in our ongoing unittests

This is harder to promise as I'm pretty loaded at work at the moment, but happy to do when finished (if you don't do that earlier).

**Comment by RReverser** [comment]
> Is this intended? The ruleset style guide as of right now does not really care about those; in fact,  (www\.)?  is even mentioned as an example of a group that one might use, and in these cases, the readability benefit seems negligible.

Definitely intended for our use-cases (optimization) as adding other couple of hosts to "trivial rule" (^http: -> https:) in our implementation is cheaper than separate regexps (actually, I believe, same applies to your implementation). However, if you wish,  feel free to exclude those.

**Comment by fuglede** [comment]
Hm, is that obvious? I honestly don't know the JS rewrite engine very well, but I would have assumed it to be optimised well enough that having one more-or-less trivial rule would beat having two trivial rules in this case.

**Comment by RReverser** [comment]
@fuglede By "trivial" I mean actual "trivial rule" as it's named in the `rules.js` code https://github.com/EFForg/https-everywhere/blob/master/chromium/rules.js#L10-L12

> I honestly don't know the JS rewrite engine very well

Well, yeah, me too, that's why I said "I assume" as I didn't dig into benchmarking of JS rewriter, too.

**Comment by jsha** [comment]
For

```
<rule from="^http://(www\.)?example.com/"
		to="https://$1example.com/" />
```

I think that makes sense to rewrite to a single trivial rule. However, for

```
<rule from="^http://(www\.)?example.com/"
		to="https://example.com/" />
```

Since that would turn into two rules, one trivial and one not, I think it doesn't make sense to transform the ruleset at this time. I haven't seen any examples of the latter in spot-checking yet, have you @fuglede?

I think there's a separate question of how to better express the very common "add www" or "drop www" rules, but that's outside the scope of this PR. :-)

**Comment by fuglede** [comment]
I could have probably been clearer about that, but for the <code>(www\\.)?</code> ones, I was thinking about those that were mentioned in https://github.com/EFForg/https-everywhere/pull/4311#issuecomment-194513879 -- I didn't see any of those in the commit itself either.

**Comment by Hainish** [comment]
@RReverser I'm trying to run the node script myself, keep getting:

```
$ node httpse-refactor.js 
/home/legind/workspace/httpse-refactor.js:84
        .map(([ { ruleset, err }, name ]) => {
              ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by Hainish** [comment]
@J0WI careful.. those PRs are auto-closing this PR via https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by RReverser** [comment]
@Hainish That's because latest version of Node doesn't enable destructuring support by default yet (I believe they are cleaning up its edge cases). You need to use `node --harmony_destructuring` flag.

**Comment by RReverser** [comment]
Btw, as for the conflicts - I'll update the PR as soon as you review the script by re-running on the latest DB.

**Comment by RReverser** [comment]
@J0WI This got closed again :(

**Comment by J0WI** [comment]
Sorry, GitHub closes this issue every time I merge a PR if the description matches 'fixes #4311'.

**Comment by RReverser** [comment]
@J0WI Yeah I know. Just as an option - you can try to edit the PR description before merging (I assume you have edit rights).

**Comment by RReverser** [comment]
@Hainish @jsha That happened again, but now with your PR :) Please re-open.

**Comment by Hainish** [comment]
Hmm I can't.  Reopen is greyed out and it says `The spring-cleaning-2016 branch was force-pushed or recreated`

**Comment by RReverser** [comment]
@Hainish :( Well, yeah, I rebased my changes after running script. Probably will need to open as new PR then.

**Pull request closed without merging**
