### PR TITLE
[LackName.org] Reactivate ruleset 

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Fix the indentation

**Comment by Bisaloo** [comment]
No idea. I noticed that as well. 

I found the owner of this page on GitHub, should we ping them?

**Comment by jeremyn** [comment]
Sure.

@mytchel We're trying to update the ruleset for your lackname.org site, but it has recently started timing out. Is that something you plan on fixing soon?

**Comment by mytchel** [comment]
Sorry, credit card expired and hosting went down. It's back up now.

**Comment by jeremyn** [comment]
Thanks @Bisaloo and @mytchel .

@mytchel By the way, we generally suggest that site owners add themselves to the HSTS preload list at https://hstspreload.org if possible, rather than us maintaining a ruleset in HTTPS Everywhere. See the FAQ at https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere .

**Pull request merged**
