### PR TITLE
* Certificate chain for maths has been fixed, removed comment, and ad…

### PR DESCRIPTION
**Pull request by zafos**
…ded www2 back to rules

* Added maths.ox.ac.uk subdomains that support https

### CODE REVIEW

**Comment by J0WI** [comment]
This ruleset is still `default_off` because of the errors listed on top.

**Comment by zafos** [comment]
Is it worth removing the urls that fail from the ruleset for now, in order to have at least a working one?

**Comment by J0WI** [comment]
They need to be checked again and moved to the list of nonfunctional hosts if they still fail (and exist).

**Comment by J0WI** [comment]
@zafos would you like to continue here?

**Comment by zafos** [comment]
Hello,

I will pick it up at some point but not in the near future.

Thanks

**Pull request merged**
