### PR TITLE
[Memberdirect.net] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

- [ ] Sort subdomains correctly.
- [ ] Move tests under targets.

Note as `Invalid certificate`:
- [ ] onlinebanking.memberdirect.net

Add targets:
- [ ] cms.memberdirect.net
- [ ] epostctfs.memberdirect.net
- [ ] monitor-internet.memberdirect.net
- [ ] monitor-lb.memberdirect.net
- [ ] finapp.pfm.memberdirect.net
- [ ] finapp.pfm-dev.memberdirect.net
- [ ] training.memberdirect.net
- [ ] vancity-test.memberdirect.net
- [ ] monitor.www6.memberdirect.net

**Comment by lucaspetter** [comment]
@gloomy-ghost Okay, I added the new targets and made the other changes. I sorted them alphabetically, is that correct? Thanks.

**Comment by gloomy-ghost** [comment]
Thanks, but we would like to sort domains in alphabetical order starting from the top level domain at the right reading left, moving ^ and www to the top of their group. For example:

```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```

**Comment by lucaspetter** [comment]
Okay, it's been re-sorted. There's no `www` subdomain here, but I moved the `www6`, `www6p1`, and `www6vdc` subdomains to the top.

**Comment by gloomy-ghost** [comment]
Well, if there isn't `www` then just left that rule behind. Let's make it simple, I've sorted a list below:

<details><summary>Subdomains list</summary>

```
['ac1.memberdirect.net',
 'bua.memberdirect.net',
 'bua-qa.memberdirect.net',
 'business.memberdirect.net',
 'business-qa.memberdirect.net',
 'cms.memberdirect.net',
 'epostctfs.memberdirect.net',
 'monitor-internet.memberdirect.net',
 'monitor-lb.memberdirect.net',
 'finapp.pfm.memberdirect.net',
 'finapp.pfm-dev.memberdirect.net',
 'sys-prod.memberdirect.net',
 'training.memberdirect.net',
 'vancity-test.memberdirect.net',
 'www6.memberdirect.net',
 'monitor.www6.memberdirect.net',
 'www6p1.memberdirect.net',
 'www6vdc.memberdirect.net']
```

</details>

HTH

**Comment by lucaspetter** [comment]
Okay, they've been re-sorted according to your list. Thanks for explaining how sorting should be done.

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Pull request merged**
