### PR TITLE
Create rules for Element14.com, related #9411

### PR DESCRIPTION
**Pull request by cschanaj**
Related: #9411

### CODE REVIEW

**Comment by cschanaj** [comment]
@J0WI It looks like that whatever the first target is will render the Travis build fail even if working test URLs are supplied. Any suggestion?

**Comment by J0WI** [comment]
uhm thats sad.
Maybe we can use a wildcard target and a rule that ony redirects those language subdomains. Then we can add this file to  the `ruleset-coverage-whitelist.txt` to make Travis happy. (without having tested this myself)

**Comment by cschanaj** [comment]
The ruleset 'passes' Travis test now, this should close #9411 if it also pass the review. thanks!

P.S. I notice that  `ruleset-coverage-whitelist.txt` is not sorted correctly, is this expected?

**Comment by J0WI** [comment]
I think initially they were sorted by the second col (ruleset names).
If you want to sort them correctly, you can contribute to `utils/ruleset-coverage-whitelist-cleanup.sh`

**Pull request merged**
