### PR TITLE
Add zipcar.co.uk

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by J0WI** [comment]
This host is still working for me

**Comment by J0WI** [comment]
Please see also `businesscalculator.zipcar.co.uk` and `members.zipcar.co.uk`.

**Comment by illicitonion** [comment]
I tried `curl https://zipcar.co.uk` from three separate hosts on independent networks, and all three curls hung for over a minute with no response...

**Comment by J0WI** [comment]
Ah sorry, I was unsure about the meaning of "Dropped". Could you please complete the rule with `businesscalculator.zipcar.co.uk` and `members.zipcar.co.uk`?

**Comment by J0WI** [comment]
ping @illicitonion

**Comment by illicitonion** [comment]
@J0WI Fixed :) Sorry for the delay!

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
