### PR TITLE
[Deutsche Post AG] add internetmarke, portokasse, epost

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Comment by J0WI** [comment]
looks good so far.

Could you also add:
blog.deutschepost.de
onlinemitteilung.deutschepost.de
auftragsmanagement.deutschepost.de
portal.postdirekt.de
service.postdirekt.de
plz1.postdirekt.de
plz2.postdirekt.de
adresszugang.postdirekt.de
partner.epost.de
checkout.postpay.de
packet.deutschepost.com
www.packet.deutschepost.com

And some comments that those are not working:
keyserver.deutschepost.de (refused)
info.deutschepost.de (mismatch)
(www.)epost.de (redirect)
(www.)postpay.de (redirect)

**Comment by J0WI** [comment]
Thanks for updating!
Rule looks good so far, but please follow our code style (tabs, no spaces in targets, comments on the top).

**Comment by J0WI** [comment]
ping @julianladisch

**Comment by jeremyn** [comment]
I'm closing this due to no response from @julianladisch . Also, this ruleset should be split into several smaller rulesets that reference each other if needed, for example see [`ACLU.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/ACLU.xml) and [`ACLU-of-Arizona.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/ACLU-of-Arizona.xml).

**Pull request closed without merging**
