### PR TITLE
Added website, Updated Hidden services for Travis

### PR DESCRIPTION
**Pull request by stylersnico**

### CODE REVIEW

**Comment by stylersnico** [comment]
We really can't add .onion to this project because of Travis?

**Comment by galeksandrp** [comment]
See #5085

**Comment by koops76** [comment]
@Hainish Close please.

**Comment by Hainish** [comment]
@koops76 that's up to @jeremyn or @J0WI.  It looks like there are still relevant targets here.

**Comment by koops76** [comment]
@Hainish Yes, there are two: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-325061678.

**Comment by koops76** [comment]
@Hainish See also #12095.

**Comment by J0WI** [comment]
`.onion` hosts are now supported. Let's ask @stylersnico for an update on this PR.

**Comment by jeremyn** [comment]
I'm closing this due to lack of response from @stylersnico .

**Pull request closed without merging**
