### PR TITLE
[Mastodon.social] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**
Site serves HSTS header with 1 year `max-age` and `includeSubdomains`, but no `preload`.

### CODE REVIEW

**Comment by J0WI** [comment]
We require at least 3 test urls for wildcards.

**Comment by lucaspetter** [comment]
I've added 2 more test urls.

**Comment by J0WI** [comment]
Okay, that's valid now. But I was more thinking about three different subdomains as test urls.

**Comment by lucaspetter** [comment]
I was going by how the site serves HSTS with `includeSubdomains`, therefore we might as well have a wildcard target because all subdomains will be covered anyway.

It looks like the site has only 2 host names: `mastodon.social` and `assets.mastodon.social`. Do you think I should just replace the wildcard with `assets.mastodon.social`?

**Comment by J0WI** [comment]
e.g. `www.mastodon.social` WFM.

Could you add a comment about the HSTS with includeSubdomains into the ruleset?

**Comment by lucaspetter** [comment]
Okay, but are you saying I should keep the wildcard and add a test URL for `www.`? Or remove the wildcard and add targets for `www.` and `assets.`?

**Comment by J0WI** [comment]
I think both variants are valid, but personally I prefer the variant without a wildcard.

**Comment by lucaspetter** [comment]
Thanks for clarifying. Based on the docs, and due to the site's HSTS `includeSubdomains`, I've kept the wildcard and added a test URL for `www.mastodon.social` as well as a comment about the HSTS.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
