### PR TITLE
Infrastructure to send Rule errors to a central server. Server URL is…

### PR DESCRIPTION
**Pull request by Thorsten-Sick**
… only temporary, but there is a small test server included.

https://github.com/EFForg/https-everywhere/issues/1888

Missing are:
- A proper server
- A good looking GUI
- Maybe an icon that indicates that errors got collected.

### CODE REVIEW

**Comment by TheNavigat** [comment]
@semenko @jsha Ping, I'm not exactly sure what does this PR need.

**Comment by Thorsten-Sick** [comment]
If you have any questions, just ask, maybe I can help (at least from my perspective, I do not know the EFF infrastructure)

**Comment by J0WI** [comment]
Ping @semenko and @jsha again :)

**Comment by J0WI** [comment]
Let's also ping @Hainish to bring this idea up again... (see also ##1888)

**Comment by Hainish** [comment]
Thanks @J0WI.  @Thorsten-Sick, I'd love to see this in action - can you rebase from master and I can take a look? Thanks.

**Comment by cowlicks** [comment]
@Thorsten-Sick I'm closing this since its pretty stale. Ping me if you'd like to re-visit it.

**Pull request closed without merging**
