### PR TITLE
[keycdn.com] New ruleset

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by fuglede** [comment]
Hey @PeterDaveHello. You do not actually need to add those test URLs; the test engine will figure those out automatically from the target hosts. Other than that, LGTM: the domain is already HSTS preloaded.

**Comment by PeterDaveHello** [comment]
So should I remove them? Thanks.

**Comment by PeterDaveHello** [comment]
Hello ~~~

**Comment by PeterDaveHello** [comment]
I removed it.

**Comment by J0WI** [comment]
This domain is already in the HSTS preload list of browsers: https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsSTSPreloadList.inc#2135
This means the browser is forcing https and refuses any connection over http.

So there is no need for a ruleset.
Thanks anyway!

**Comment by fuglede** [comment]
@J0WI: While certainly less useful than many other rulesets at the moment, they are not completely without value. https://github.com/EFForg/https-everywhere/issues/3721#issuecomment-168814096 and https://github.com/EFForg/https-everywhere/pull/3454 are relevant here.

**Comment by J0WI** [comment]
I already tried to clean them up in https://github.com/EFForg/https-everywhere/pull/2163 refering to the discussion in https://lists.eff.org/pipermail/https-everywhere/2015-May/002525.html

Would be great to have a list of the affected ruleset somewhere instead of just stats to finish this task.

**Comment by fuglede** [comment]
Thanks for the reference; I [ran some stats](https://lists.eff.org/pipermail/https-everywhere/2015-October/002639.html) back in October and noticed an overlap with the preload list as well (but took the opposite angle of trying to find new preloadables among the target hosts). It would be nice with an overview of exactly how slow various browsers are at pulling in HSTS preload lists (and I suppose any decision on what browser versions to support (\*cough\*https://github.com/EFForg/https-everywhere/pull/3876#issuecomment-172965331) would be relevant here as well).

**Comment by J0WI** [comment]
Referring to the [commit log] (https://hg.mozilla.org/mozilla-central/filelog/aa90f482e16db77cdb7dea84564ea1cbd8f7f6b3/security/manager/ssl/nsSTSPreloadList.inc), Mozilla updates it's list each week (7 days).
The SSL Labs API does also [provide] (https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#endpointdetails) information about the preloaded state of a host in each browser, even for Tor.

**Comment by fuglede** [comment]
Hm, just checked with my own site, which I submitted to the preload list ages ago; according to SSL Labs, that one is not in Tor's list. It's a bit unfortunately that the SSL Labs list does not appear to cover older browser versions in general.

**Comment by J0WI** [comment]
Tor uses Firefox ESR, that uses a different release cycle.
Firefox ESR Release Overview

**Comment by fuglede** [comment]
Ah, good to know. Any other notable release cycles that one should be aware of/take into account for compatibility considerations?

**Pull request closed without merging**
