### PR TITLE
[B-static.net] Simplify and reactivate ruleset 

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by jeremyn** [comment]
https://boards.ie seems okay. I think we can move `b-static.net` and its subdomains to a new ruleset and remove it from `Boards.ie.xml`, but otherwise keep `Boards.ie.xml`. What do you think?

**Comment by Bisaloo** [comment]
It's hidden in my commit message but `boards.ie` is preloaded.

**Comment by jeremyn** [comment]
Oh okay, that's fine then. In that case:

- [ ] https://b-static.net returns an HTTP 200 so you can make it a `target` and remove it from the top comment.
- [ ] Change the `ruleset` `name` to `B-static.net` to match the filename.
- [ ] https://avatar.b-static.net returns an HTTP 301 so the extra `test` isn't needed. (Also from the URL is looks like this might be a particular person's avatar image, which is also not good for a `test`.)

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
