### PR TITLE
Remove blank lines from chromium test script

### PR DESCRIPTION
**Pull request by Tenzer**
Since #2903 was merged before I got around to add the change, there's a separate pull request for @TheNavigat's comment on removing some blank lines.

### CODE REVIEW

**Comment by TheNavigat** [comment]
Yep, LGTM :D

**Comment by Tenzer** [comment]
I guess this is good for my GitHub stats, if there's some statistics on who got most PRs merged ;)

**Comment by TheNavigat** [comment]
https://github.com/EFForg/https-everywhere/graphs/contributors ;)

**Comment by Tenzer** [comment]
I was just thinking one merged PR would be worth more than one merged commit - but never mind :)

**Pull request merged**
