### PR TITLE
e.snmc.io.xml

### PR DESCRIPTION
**Pull request by afarrow**

### CODE REVIEW

**Comment by jeremyn** [comment]
@afarrow Are you still interested in working on this pull request?

**Comment by afarrow** [comment]
@jeremyn The rule is complete for this domain. If you go to https://snmc.io/ you can see the certificate is only valid for the e. subdomain. What extra work does this need?

**Comment by jeremyn** [comment]
Please:

- [ ] Change the top comment to this:
```xml
<!--
    Invalid certificate:
        snmc.io
        www.snmc.io

-->
```
- [ ] Change the `ruleset` `name` to `snmc.io`
- [ ] Change the filename to `Snmc.io.xml`

**Comment by afarrow** [comment]
Ok, updated. I left the comment in there saying what the site is used for because I felt it might be useful for future contributors. Let me know if you disagree and I'll remove it.

**Comment by jeremyn** [comment]
I don't think the CDN comment is really useful for contributors, also it can get out of date and requires future maintenance. Please remove it.

**Comment by afarrow** [comment]
Done

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
