### PR TITLE
 	Re-activate and Update Avropa.se.xml 

### PR DESCRIPTION
**Pull request by cschanaj**
#9906

### CODE REVIEW

**Comment by jeremyn** [comment]
This one works for me. What's wrong with it?

**Comment by cschanaj** [comment]
I was testing a newly created script to identify `default_off` rulesets which all `target` are not working over HTTPS. `^` and `www` are `reset` over HTTPS with my script. 

However, it seems to be a false-positive case. `curl` does not show any type of errors on both `^` and `www`. I should be double checked before submitting this PR. 

Rebase this PR to re-activate the ruleset. thanks!!

**Comment by jeremyn** [comment]
- [ ] Please delete the [empty line](https://github.com/cschanaj/https-everywhere/blob/7e4d89b3afbc72b2f2cc79cb1eccc4c6fbd9c0be/src/chrome/content/rules/Avropa.se.xml#L7) at the end

**Comment by cschanaj** [comment]
@jeremyn done. thanks!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
