### PR TITLE
5ch.net

### PR DESCRIPTION
**Pull request by Ohbi3urao8**
5ch.net list

### CODE REVIEW

**Comment by Ohbi3urao8** [comment]
why canceled ?

**Comment by pipboy96** [comment]
Do not use `*`, enumerate subdomains using [Amass](https://github.com/OWASP/Amass).

**Comment by zoracon** [comment]
You can also use [Sublist3r](https://github.com/aboul3la/Sublist3r) as well for enumerating a full set of subdomains.

**Comment by pipboy96** [comment]
@zoracon Amass is a bit faster, especially in brute mode.

**Comment by pipboy96** [comment]
Closed in favor of #19126.

**Pull request closed without merging**
