### PR TITLE
Create 95516.com.xml UnionPay.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Comment by jeremyn** [comment]
Most or all of those `test`s are unnecessary and distracting, please remove them.

**Comment by jeremyn** [comment]
Thanks. Please:

`95516.com.xml`:

- [ ] Add full domain to items in top comment.
- [ ] Remove general `securecookie`.
- [ ] Change `Dismatch` to `Mismatch`.
- [ ] Sort `nmg` correctly.
- [ ] Remove `(partial)`.

`UnionPay.com.xml`:

Mark as `Mismatch`:
- [ ] https://upstudy.unionpay.com

Mark as `Time out`:
- [ ] https://product.unionpay.com
- [ ] https://supplier.unionpay.com
- [ ] https://unionpayintl.com
- [ ] https://www.unionpayintl.com
- [ ] https://goldenweek.unionpayintl.com
- [ ] https://m.unionpayintl.com

Add `target`:
- [ ] https://95516.unionpay.com
- [ ] https://billcloud.unionpay.com with test http://billcloud.unionpay.com/ccfront
- [ ] https://ebpp.unionpay.com
- [ ] https://mail.unionpay.com
- [ ] https://member.unionpay.com
- [ ] https://merchant.unionpay.com
- [ ] https://minipay.unionpay.com
- [ ] https://oaweixin.unionpay.com with test http://oaweixin.unionpay.com/cup_weixin/amcc.html
- [ ] https://online.unionpay.com
- [ ] https://portal.unionpay.com
- [ ] https://bonus.unionpayintl.com

Also:
- [ ] Add full domain to items in top comment.
- [ ] Remove the general `securecookie`.
- [ ] Change `Dismatch` to `Mismatch`.
- [ ] Remove the special rule for `(www\.)unionpay.com`. This is for two reasons: HTTPS seems to work without the special rule, and the language redirect is not always to `cn`. For example, for me it is to `en`.
- [ ] https://fr.unionpay.com is fine for me other than harmless mixed content, so you can add a target and remove it from the top comment.
- [ ] Same for https://kr.unionpay.com .
- [ ] https://m.haigou.unionpay.com redirects to http://haigou.unionpay.com , but the HTTPS at https://m.haigou.unionpay.com is fine so you can add a target and remove it from the top comment.
- [ ] I can't reproduce the incomplete certificate chain problem with https://ums.unionpaysecure.com .

**Comment by jeremyn** [comment]
Also, I won't ask you do it now, but `*.95516.net` looks related to `95516.com` if you want to get those too.

**Comment by gloomy-ghost** [comment]
Could you explain what do you meant by "Add full domain to items in top comment"?

**Comment by jeremyn** [comment]
I confirm that https://portal.unionpay.com is `Incomplete certificate chain`, and I've updated the checklist and checked that item off.

Delete the extra `+` [here](https://github.com/gloomy-ghost/https-everywhere/blob/8cc206a845307290a8135a97cf5785d1459f10a8/src/chrome/content/rules/UnionPay.com.xml#L12).

Fix indentation [here](https://github.com/gloomy-ghost/https-everywhere/blob/8cc206a845307290a8135a97cf5785d1459f10a8/src/chrome/content/rules/UnionPay.com.xml#L48).

Your latest commit message says `35516.com.xml` instead of `95516.com.xml`. You don't need to rebase it, but with your permission I'll change it to `95516.com.xml` in the squashed commit message. Is that all right?

**Comment by gloomy-ghost** [comment]
Sure, thanks 😃

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
