### PR TITLE
Added bewelcome.org with additional tests based on https://github.com…

### PR DESCRIPTION
**Pull request by thisismeonmounteverest**
Added tests mentioned in https://github.com/EFForg/https-everywhere/pull/4261.

### CODE REVIEW

**Comment by simison** [comment]
Git squashing would make this a bit prettier:
image

**Comment by J0WI** [comment]
There are also:
alpha.bewelcome.org
test.bewelcome.org
trac.bewelcome.org (refused)
fox.bewelcome.org (refused)
downloads.bewelcome.org (mismatched)
www.bewelco.me (mismatched)

The content on (www.)bewelco.me differs from bewelcome.org.


Please use comments to document all problematic domains on the top of the rule.
Our style guide requires tabs instead of spaces.

**Comment by J0WI** [comment]
@thisismeonmounteverest would you like to finish this?
Don't worry about squashing commits, we do this during merge.

**Comment by jeremyn** [comment]
@thisismeonmounteverest Are you still interested in working on this?

**Comment by thisismeonmounteverest** [comment]
If I don't have to do anything for it, yes. Otherwise drop it. 

The process to get something in was way to complicated.

**Comment by jeremyn** [comment]
Unfortunately, this ruleset would need more changes before we merge it. I'm closing the pull request based on your last comment, but I've noted the domains in issue #3069 in case anyone else wants to include them.

**Pull request closed without merging**
