### PR TITLE
Add more subdomains for serveriai.lt

### PR DESCRIPTION
**Pull request by Liudvikam**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for figuring them out!
You may also add https://roundcube.serveriai.lt/

Sadly it seems that every customer/server gets a subdomain too, but without a valid cert. Could you document this in a comment for future contributors?

**Comment by Liudvikam** [comment]
> You may also add https://roundcube.serveriai.lt/

The server seems to redirect to HTTPS on that subdomain all by itself.

> Sadly it seems that every customer/server gets a subdomain too, but without a valid cert. Could you document this in a comment for future contributors?

Every customer that decides not to buy a domain gets a subdomain. It also seems that they get a subdomain on puslapiai.lt, not serveriai.lt.

**Comment by J0WI** [comment]
>>You may also add https://roundcube.serveriai.lt/

>The server seems to redirect to HTTPS on that subdomain all by itself.

As long as they don't provide preloaded HSTS we should include this domain, because the first request is over insecure http and cloud be compromised.

>>Sadly it seems that every customer/server gets a subdomain too, but without a valid cert. Could you document this in a comment for future contributors?

>Every customer that decides not to buy a domain gets a subdomain. It also seems that they get a subdomain on puslapiai.lt, not serveriai.lt.


e.g. http://laidara.lt.povas.serveriai.lt/

**Comment by Liudvikam** [comment]
>>> You may also add https://roundcube.serveriai.lt/

>> The server seems to redirect to HTTPS on that subdomain all by itself.

> As long as they don't provide preloaded HSTS we should include this domain, because the first request is over insecure http and cloud be compromised.

Ah, that's right. I'll add that subdomain, then.



>>> Sadly it seems that every customer/server gets a subdomain too, but without a valid cert. Could you document this in a comment for future contributors?

>> Every customer that decides not to buy a domain gets a subdomain. It also seems that they get a subdomain on puslapiai.lt, not serveriai.lt.

> e.g. http://laidara.lt.povas.serveriai.lt/

I see. I'll go ahead and add that comment.

**Comment by J0WI** [comment]
Great, thank you!

**Pull request merged**
