### PR TITLE
Create tnstimes.org.xml

### PR DESCRIPTION
**Pull request by katzrkool**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for your contribution! The rule LGTM, but our code style requires to use tabs to indent lines. Could you please change this?

**Comment by katzrkool** [comment]
Should be fixed now!

**Comment by J0WI** [comment]
Nope, now you are using two spaces.

**Comment by katzrkool** [comment]
I think I finally got it, my text editor was being weird and not doing indentations right. But this should work.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
