### PR TITLE
[US-government] Delete ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**
The dead links are caused by `hsts-prune`.

### CODE REVIEW

**Comment by jeremyn** [comment]
This entire ruleset is an anti-pattern. US government agencies/IT services can be as independent from one another as two different corporations, especially across federal/state/city lines. If someone needs a list of all US federal websites, they can look at for example https://pulse.cio.gov/https/domains/ .

This ruleset should be deleted and existing groups moved into independent rulesets such as `Census.gov.xml`. 

(I've also commented on this in PR https://github.com/EFForg/https-everywhere/pull/10468.)

**Comment by cschanaj** [comment]
Linking #11348

**Comment by Bisaloo** [comment]
I'm totally fine with splitting it as well. I agree that we should use different rulesets for different domains.

I don't really care about what happens to the top comment. I have never really been convinced of its usefulness anyways.

@cschanaj, do you want to do it?

**Comment by cschanaj** [comment]
I would like to continue my work on removing the outdated _https-everywhere-checker_ comment, please feel free to do anything you want. I will close #11348. thanks!

**Comment by Bisaloo** [comment]
I left one target because I think comments can still be useful. So we should probably keep this ruleset until all comments are moved to relevant distinct rulesets.

@cschanaj also found many more working targets but they should be added in separate rulesets in later PR otherwise this will become too painful to review.

@jeremyn, thoughts?

**Comment by Bisaloo** [comment]
I know `NASA.gov.xml` is still `default_off` but this work should be done in another PR IMO.

**Comment by jeremyn** [comment]
I disagree with keeping the list of nonfunctional domains for the same reasons I gave in PR https://github.com/EFForg/https-everywhere/pull/10468#issuecomment-318770707:

> I'm saying the canton rulesets/domains aren't related to the federal ruleset, so they shouldn't be linked to the federal ruleset, and that list shouldn't be there. Where that list should be is unrelated. There are thousands/millions of other unrelated domains that also don't support HTTPS, and I wouldn't put them in `swissgov.xml` either.

**Comment by Bisaloo** [comment]
@jeremyn, I agree with you. At some point, the `US-government.xml` should be entirely removed. 

But, for the time being, it contains valuable information, that is not stored anywhere else. If I remove it now, we lose that information (or we need to dig through git history).

This is what I meant. So it's probably a good idea to wait until that info has been migrated before deleting it.

Do you see what I mean? Do you still think it should be removed now?

**Comment by Bisaloo** [comment]
Actually, I had a look at the comments and they weren't that useful. So I went ahead and removed `US-government.xml`. Should I also remove the comments pointing to it in that PR?

**Comment by jeremyn** [comment]
Which comments/PR?

**Comment by Bisaloo** [comment]
Should I remove the comments from other rulesets linking to `US-government.xml` ([for example](https://github.com/EFForg/https-everywhere/blob/release/src/chrome/content/rules/NASA.gov.xml#L19)) here, in this PR? Or should I do it in a new PR?

**Comment by jeremyn** [comment]
Yes, please delete references to `US-government.xml` from other files in this PR.

**Comment by Bisaloo** [comment]
(Reminder to myself to solve conflicts [here](https://github.com/EFForg/https-everywhere/pull/11513/files)) when this PR is merged.)

**Comment by Bisaloo** [comment]
Is it okay if I whitelist all rulesets failing coverage test?

**Comment by jeremyn** [comment]
Let's just not edit those files -- that is, let's leave in the dangling references to `US-government.xml`. The references can be removed the next time someone looks at those files. 

The alphabetically sorted list of failing rulesets from Travis is:

* `Argonne-National-Laboratory.xml`
* `Bonneville_Power_Administration.xml`
* `City-of-Chicago.xml`
* `City-of-Sedona.xml`
* `City_of_Seattle.xml`
* `Federal-Communications-Commission.xml`
* `NCRIC.xml`
* `National-Renewable-Energy-Laboratory.xml`
* `Pay.gov.xml`
* `State_of_Alaska.xml`
* `US_Citizenship_and_Immigration_Services.xml`
* `US_Patent_and_Trademark_Office.xml`
* `United-States-Department-of-Energy.xml`

**Comment by Bisaloo** [comment]
Thank you for the list. For future reference, I also had to remove:

- `DHS.gov.xml`
- `State_of_Oregon.xml`

**Comment by Bisaloo** [comment]
https://m.hivtest.cdc.gov/ WFM

**Comment by jeremyn** [comment]
I don't see https://m.hivtest.cdc.gov failing Travis anywhere.

**Comment by Bisaloo** [comment]
> I don't see m.hivtest.cdc.gov failing Travis anywhere.

It was timing out before I restarted the tests.

List of all excluded files:

- Argonne-National-Laboratory.xml
- Bonneville_Power_Administration.xml
- City-of-Chicago.xml
- City-of-Sedona.xml
- City_of_Seattle.xml
- Consumer_Finance.gov.xml
- DHS.gov.xml
- Federal-Communications-Commission.xml
- Federal_Reserve.org.xml
- NCRIC.xml
- National-Renewable-Energy-Laboratory.xml
- Pay.gov.xml
- State_of_Alaska.xml
- State_of_Oregon.xml
- US_Citizenship_and_Immigration_Services.xml
- US_Patent_and_Trademark_Office.xml
- United-States-Department-of-Energy.xml
- bbg.gov.xml

**Comment by jeremyn** [comment]
There are a small number of problems with the changes, however I merged anyway. It would be nice if you could make new PRs (and ping me) for these problems:

* Add `(partial)` to the `name` in `House.gov.xml`
* Fill out `Export.gov.xml` with more domains, because we removed a wildcard entry for it from `US-government.xml`.

**Pull request merged**
