### PR TITLE
Delete simple.py

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by cowlicks** [comment]
Do you think it is possible that we should still be using this for rule validation? Would you mind figuring out the last place this was used, and why we stopped using it? This might require some spelunking with git.

**Comment by koops76** [comment]
ping @Hainish @cowlicks.

**Comment by cowlicks** [comment]
@koops76 I've looked at the PR. But would you mind responding to https://github.com/EFForg/https-everywhere/pull/12910#issuecomment-334554947 so I know I can merge safely?

**Comment by koops76** [comment]
@cowlicks I'm not sure.

**Comment by Hainish** [comment]
Looks good, thanks @koops76

**Pull request merged**
