### PR TITLE
Create Snopes.com.xml, Fix #14001

### LINKED ISSUE #14001: Snopes.com supports HTTPS
Type: new ruleset

In case anyone is interested, the fact-checking site Snopes.com has HTTPS support for some of the site, particularly article pages.

Domain: snopes.com
Domain: www.snopes.com

Both the snopes.com and www.snopes.com domains support HTTPS, at least with regard to article pages.

Domain: message.snopes.com
This domain gives an error about SSL_ERROR_RX_RECORD_TOO_LONG when accessed via HTTPS.
Domain: msgboard.snopes.com
It appears that a browser cannot connect to the server when attempting to access this domain via HTTPS.
Domain: zeus-origin.snopes.com
This domain gives an error about a self-signed certificate when accessed via HTTPS.

### PR DESCRIPTION
**Pull request by cschanaj**

### CODE REVIEW

**Comment by jeremyn** [comment]
@Hainish This PR should have been marked `top-10k`, but it wasn't.

**Comment by cschanaj** [comment]
@jeremyn I'm sorry I have placed the ruleset in the wrong directory. Fix in 90b1c2a. Thanks! @Hainish This is NOT a bug of the labeler. Sorry!!

**Comment by jeremyn** [comment]
Oops, good catch though!

As I suggested a couple weeks ago in https://github.com/EFForg/https-everywhere/pull/13844#issuecomment-348794745:

> We should have some kind of automated test to detect ruleset files outside of the rules directory.

**Comment by cschanaj** [comment]
Since this is a common mistake which can be easily ignored by contributors (even the experienced ones), I have submitted a PR at #14016.

**Pull request merged**
