### PR TITLE
added subdomains of cs.byu.edu that should be https only

### PR DESCRIPTION
**Pull request by bryceml**

### CODE REVIEW

**Comment by J0WI** [comment]
@bryceml please have a look at the failing tests.

**Comment by bryceml** [comment]
It doesn't appear that any of the sites I added caused the failing tests.  I can try to get around to fixing existing ones if you want, but it might be a while to get around to it.

**Comment by J0WI** [comment]
Yes, please fix them.

**Comment by bryceml** [comment]
All fixed.  There are probably more in the comments that work now that could be moved to the effective rules though.

**Comment by J0WI** [comment]
LGTM, Thanks!

**Pull request merged**
