### PR TITLE
Create libre.fm.xml

### PR DESCRIPTION
**Pull request by svbeon**

### CODE REVIEW

**Comment by strugee** [comment]
FYI I just pinged the libre.fm people asking them to serve HSTS headers and add libre.fm to the preload list, so this ruleset may be unnecessary soon. Ref https://git.gnu.io/gnu/gnu-fm/issues/10

**Comment by svbeon** [comment]
Great

**Comment by J0WI** [comment]
Please also add:
alpha.libre.fm
turtle.libre.fm
www.libre.fm

**Comment by svbeon** [comment]
@J0WI added, hope this is the correct format for that

**Comment by J0WI** [comment]
Multiple `ruleset` tags in one file are not allowed, please just add the targets inside the existing `ruleset`.
If a host is not HTTPS compatible, like turtle.libre.fm, we use to document the issue with a comment. Please have a look at our docs or other rulesets for examples.

**Comment by svbeon** [comment]
@J0WI like this? and is it sufficient to comment this issue with "turtle.libre.fm is not https compatible"?

**Comment by J0WI** [comment]
You may have a look at the tool referred in our [CONTRIBUTING.md](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md). This is the currently preferred ruleset style.

**Comment by svbeon** [comment]
Well, nevermind it then, they've added hsts anyways. I'm not a big fan of cloning a complete repo and run  one script to make a one-time contribution when the script's functionality could easily be a web tool whose output you could contribute via githubs web interface

**Comment by strugee** [comment]
@svbeon the ticket I referenced is still open.

**Comment by J0WI** [comment]
@svbeon btw, you can also just download one file from GitHub and copy the output of your terminal.

**Pull request closed without merging**
