### PR TITLE
Switchads.com:

### PR DESCRIPTION
**Pull request by numismatika**
- fix style

### CODE REVIEW

**Comment by J0WI** [comment]
Could you add comments that all other domains are refused?
switchads.com
www.switchads.com
dev.switchads.com
w.switchads.com
switchconcepts.com
www.switchconcepts.com

You may also add a redirect for support.switchconcepts.com

**Comment by numismatika** [comment]
We should probably merge Switchads.com.xml and Switch_Adserver.xml

**Comment by J0WI** [comment]
At least it should be mentioned that they are related.

**Comment by numismatika** [comment]
I merged them , added the broken domains and renamed the file.
I guess there are more domains (a-z probably), but i haven't checked their existence.
There is a catch-all dns entry for stuff like testgarbage.switchadhub.com as well (which doesn't serve a valid cert)

**Comment by J0WI** [comment]
I got `proxy` up to `proxy6` and the letters up to `h`.
Please put all the comments on the top of the file.

**Comment by J0WI** [comment]
There was something wrong with the test server. Let me reopen.

**Pull request merged**
