### PR TITLE
[VEVO] Add several more hosts

### PR DESCRIPTION
**Pull request by mnordhoff**
Add `apiv2`, `aws-cache`, `fw`, `h264-aws`, `s` (all `.vevo.com`) and `aws-cache.vevocdn.com`.

Also, move some of the tests around.

Unlike my last VEVO pull request, none of this is super critical, but it helps complete things (HTTPS video streaming!), and probably fixes a few broken images.

### CODE REVIEW

**Comment by J0WI** [comment]
This shouldn't break anything, but let me rerun the tests before merge.

**Comment by J0WI** [comment]
@mnordhoff could you have a look at failed tests?

**Comment by mnordhoff** [comment]
@J0WI Fixed. They added a good certificate for one subdomain and broke my yucky hack. :-)

**Comment by J0WI** [comment]
Thanks for updating!

**Pull request merged**
