### PR TITLE
Testing only rulesets from commit

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
@Hainish can you have a look here?
lgtm

**Comment by Hainish** [comment]
This is great, thanks for the patch!

**Comment by J0WI** [comment]
I had this again in https://travis-ci.org/EFForg/https-everywhere/jobs/146865542

**Comment by galeksandrp** [comment]
#5789. For successful PR's even with broken master.

**Pull request merged**
