### PR TITLE
add rule for TZ.de

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by J0WI** [comment]
There is some mixed content on articles, that breaks videos.
Mismatch on markt.tz.de

**Comment by numismatika** [comment]
@J0WI do you have an example for such a broken video in an article?
The only ones i found so far come from snacktv and work.

**Comment by J0WI** [comment]
I got mixed content from "http://www.video.oms.eu/ada/cloud/omsv_container_151.js", but it seems that most videos are included from YouTube or snacktv.

Could you add comments for mismatching subdomains?

**Comment by numismatika** [comment]
i created  #4171 for this advertising company as well

**Pull request merged**
