### PR TITLE
[Cloudfront] Attempt to fix rotten tomatoes video playback

### PR DESCRIPTION
**Pull request by funkydude**
Broken trailer (video) on http://www.rottentomatoes.com/m/the_revenant_2015/
The source `d3biamo577v4eu.cloudfront.net` seems to support HTTPS just fine but I believe rotten tomatos is trying to force it over HTTP (I couldn't locate the actual source), so I'm excluding this rule in an attempt to resolve it.

Did a search and this was actually reported last year: https://github.com/EFForg/https-everywhere/issues/2742

### CODE REVIEW

**Comment by funkydude** [comment]
I'm not sure why Travis is skipping this.

**Comment by J0WI** [comment]
That's because it's in utils/ruleset-coverage-whitelist.txt

**Comment by J0WI** [comment]
@funkydude could you remove it from this list since we have enough hosts to test?
Rule LGTM.

**Comment by J0WI** [comment]
@funkydude are you still working on this?

**Comment by funkydude** [comment]
@J0WI As far as I'm concerned it was finished when I posted it, so I guess the answer is no.

**Comment by J0WI** [comment]
> Could you remove it from this list since we have enough hosts to test?

@funkydude would you like to fix this that I can merge it?

**Comment by J0WI** [comment]
Rerun tests after #4830 has been merged.

**Comment by J0WI** [comment]
All tests passed.

**Pull request merged**
