### PR TITLE
[tigerair.com.au] New ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by fuglede** [comment]
Mostly LGTM; all covered target hosts except from booking.tigerair.com.au and cars.tigerair.com already redirect to HTTPS. However, booking.tigerair.com.au works on neither HTTP nor HTTPS;

    $ curl -I booking.tigerair.com.au
    curl: (7) Failed to connect to booking.tigerair.com.au port 80: No route to host
    $ curl -I https://booking.tigerair.com.au
    curl: (60) SSL certificate problem: unable to get local issuer certificate

It should probably not be included given the different (and in any case faulty) behaviour, but maybe it is used in such a way that warrants inclusion?

**Comment by youdly** [comment]
The 'main' page of https://booking.tigerair.com.au would serve invalid cert. When one searching for ticket, user is redirected to https://booking.tigerair.com.au/TigerAirIBE/Booking/Select. Without any parameters/cookies, that page would return with invalid cert. Invalid pages would serve invalid cert.

**Comment by J0WI** [comment]
WFM
www.tigerair.com
webcheck.tigerair.com.au
m.tigerair.com
groups.tigerair.com
intranet.tigerair.com

Timeout
crewnet.tigerair.com.au
crewnet.tigerair.com
gethelp.tigerair.com
notify.tigerair.com

Mismatch:
packages.tigerair.com
holidays.tigerair.com
tigertours.tigerair.com
hotels.tigerair.com

Handshake failure:
crs.tigerair.com

**Comment by youdly** [comment]
Updated subdomains and comment. www.tigerair.com still redirects to HTTP.

**Comment by J0WI** [comment]
I get a mismatch on ^tigerair.com. m.tigerair.com works, but the host has different paths than the regular site.

**Comment by youdly** [comment]
Added m.tigerair.com, `curl` got 404 respond, but web browser works fine. Updated comment on tigerair.com

**Comment by J0WI** [comment]
strange server config...
Thanks for the updates!

**Pull request merged**
