### PR TITLE
New ruleset for wordreference.com

### PR DESCRIPTION
**Pull request by Harest**

### CODE REVIEW

**Comment by Bisaloo** [comment]
See also:

cdn77f.wordreference.com
forum.wordreference.com
daily.wordreference.com
lists.wordreference.com
www2.wordreference.com

**Comment by Harest** [comment]
The test already failed with just the default domain name, i don't know exactly why. If you want to edit it, feel free to do so. I guess there's still some redirects issues in their server config.

**Comment by Bisaloo** [comment]
The test failures are unrelated to your changes. You can safely continue here.

**Comment by Bisaloo** [comment]
Please sort the targets according to our [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#target-ordering).

**Comment by Bisaloo** [comment]
Please also add a target for `wordreference.com` with a rule that redirects it to `https://www.wordreference.com/` (as well as a top comment marking `wordreference.com` as `refused`).

**Comment by Harest** [comment]
God dammit, sorry i forgot. Fixing it.

**Pull request merged**
