### PR TITLE
[cimb.com] Add subdomains and rename ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by youdly** [comment]
- [ ] CIMBBank.com.my.xml
- [ ] CIMBClicks.com.my.xml
- [ ] CIMBIslamic.com.xml
- [ ] CIMBPreferred.com.xml
- [ ] CIMB-Principal.com.my.xml
- [ ] CIMBSecurities.com.xml
- [ ] CIMB-Cambodia.xml
- [ ] CIMB-Indonesia.xml
- [ ] CIMB-Singapore.xml
- [ ] CIMB-Thailand.xml
- [ ] iTradeCIMB.com.my.xml
- [ ] eIPOCIMB.com.xml

**Comment by youdly** [comment]
Temporarily remove `eIPOCIMB.com.xml` reference to resolve conflict with https://github.com/EFForg/https-everywhere/pull/14056

**Comment by youdly** [comment]
Currently depends on https://github.com/EFForg/https-everywhere/pull/13946 (merged) and https://github.com/EFForg/https-everywhere/pull/13949

**Comment by J0WI** [comment]
@youdly #13949 needs some more work.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
