### PR TITLE
rm Strugee.net.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded
[Chromium](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json#4762), [Firefox](https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#8278), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n10631)

HTTPS Header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by jeremyn** [comment]
@strugee FYI this issue.

**Comment by strugee** [comment]
Is removing preloaded sites standard practice in HTTPS Everywhere? Not that I have an issue with it since (as @gloomy-ghost aptly pointed out) my site's preloaded. I'm just curious - particularly since it affects a project of mine, strugee/HTTPSize.

In any case it was nice of you to ping me, thanks.

**Comment by jeremyn** [comment]
There's an active discussion about removing HSTS preloaded sites in #7126 . As a reviewer my current approach is to process deletion requests as they come in.

**Pull request merged**
