### PR TITLE
Updatad taboola.com

### PR DESCRIPTION
**Pull request by luixxiul**
#6470

### CODE REVIEW

**Comment by luixxiul** [comment]
As the redirection of ``signup.taboola.com`` sometimes causes an 400 error and the the redirection seems to be configured properly by their side, I commented it out.

**Comment by J0WI** [comment]
I was able to reproduce both, a 200 and 403 with https://signup.taboola.com/styles/assets/favicon.png and curl.
It turns out, that they use Round-robin DNS and one of their backend servers doesn't handle the request well.

**Comment by luixxiul** [comment]
Would you please tell me whether I should stop commenting it out? /cc; @Hainish and @fuglede

**Comment by J0WI** [comment]
Since this host seems quite frequent used, I would go for the exclusion, but you should update the comment to be more accurate.

**Pull request closed without merging**
