### PR TITLE
[Peytz.dk] New ruleset

### PR DESCRIPTION
**Pull request by fuglede**

### CODE REVIEW

**Comment by reedy** [comment]
I get a 404 for this...

**Comment by fuglede** [comment]
@reedy: Yeah, the root gives a 404 on port 80 as well. It's an analytics company and some medias refer to scripts on this domain -- one concrete that I came across is https://opinion.peytz.dk/decide2.js.

**Comment by reedy** [comment]
Aha, maybe add that as a test url? :)

**Comment by fuglede** [comment]
Can do. (Although I'm not completely sure I understand which purpose adding that one in particular could serve?)

**Comment by fuglede** [comment]
Guess that makes sense; I could also add a few words on the intent in a comment if that's better.

**Pull request merged**
