### PR TITLE
Create Skyscanner.net.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by jeremyn** [comment]
@davidabian Are you still interested in working on this one?

**Comment by davidabian** [comment]
@jeremyn Should I fix something?

**Comment by jeremyn** [comment]
Not necessarily, I was asking to make sure you were still around and interested before spending time reviewing it. But I'll review it and let you know what needs to be changed, if anything.

**Comment by jeremyn** [comment]
It looks like there is a lot to do for this one. Please make the following changes. For the `Mark as` problems, please add them to the top comment so the top comment looks something like [this](https://github.com/EFForg/https-everywhere/blob/8fa39b32bbf1657df75975111f7ebdd1df2f8c4d/src/chrome/content/rules/glavbukh.ru.xml#L1-L71).

Mark as `Invalid certificate`:
- [ ] https://cn.skyscanner.net `(incomplete certificate chain)`
- [ ] https://deals.skyscanner.net
- [ ] https://dk.skyscanner.net `(incomplete certificate chain)`
- [ ] https://eu1-origin.skyscanner.net `(incomplete certificate chain)`
- [ ] https://eu2-origin.skyscanner.net `(incomplete certificate chain)`
- [ ] https://eu3-origin.skyscanner.net `(incomplete certificate chain)`
- [ ] https://kr.skyscanner.net `(incomplete certificate chain)`
- [ ] https://no.skyscanner.net `(incomplete certificate chain)`
- [ ] https://partners.api.skyscanner.net
- [ ] https://pt.skyscanner.net `(incomplete certificate chain)`
- [ ] https://ro.skyscanner.net `(incomplete certificate chain)`
- [ ] https://se.skyscanner.net `(incomplete certificate chain)`
- [ ] https://static.skyscanner.net `(incomplete certificate chain)`
- [ ] https://tr.skyscanner.net `(incomplete certificate chain)`

Mark as `Refused`:
- [ ] https://news.skyscanner.net

Mark as `Time out`:
- [ ] https://skyscanner.net
- [ ] https://holidays.skyscanner.net
- [ ] https://hotels.skyscanner.net
- [ ] https://m.skyscanner.net
- [ ] https://mobile.skyscanner.net
- [ ] https://redirect.skyscanner.net

Add `target`. For `test`s, add a `test` tag directly below the `target` with an extra indent.
- [ ] https://analytics.skyscanner.net
- [ ] https://beta-apps.skyscanner.net
- [ ] https://www.brandportal.skyscanner.net
- [ ] https://en.business.skyscanner.net
- [ ] https://portal.business.skyscanner.net
- [ ] https://support.business.skyscanner.net
- [ ] https://ww2.business.skyscanner.net
- [ ] https://carhirehelp.skyscanner.net
- [ ] https://mobile.ds.skyscanner.net
- [ ] https://facescanner.skyscanner.net
- [ ] https://www.facescanner.skyscanner.net
- [ ] https://gateway.skyscanner.net (test: https://gateway.skyscanner.net/article-signup)
- [ ] https://gojira.skyscanner.net
- [ ] https://gr.skyscanner.net (test: https://gateway.skyscanner.net/article-signup)
- [ ] https://hotelshelp.skyscanner.net
- [ ] https://ksa.skyscanner.net
- [ ] https://ksaen.skyscanner.net
- [ ] https://partners.skyscanner.net
- [ ] https://travelpro.skyscanner.net
- [ ] https://whitelabel.skyscanner.net
- [ ] https://whitelabeldemo.skyscanner.net
- [ ] https://widgets.skyscanner.net (test: https://widgets.skyscanner.net/widget-server/v1.0/en-GB/widgets/LocationWidget/refer?destinationId=CUN&whitelabeldomain=flights.travelandleisure.com&keyword=Cancun)

Also:
- [ ] Please make sure everything is sorted as we've discussed before.

There are several other subdomain groups that should be added, at least some of which I've listed below. Once you've made the changes I've already described, we can figure the best way to add these:

```
*.skyscanneraffiliate.net
*.skyscnr.com
*.skyscanner.dk
*.skyscanner.com
*.skyscanner.ca
*.skyscanner.co.kr
*.skyscanner.no
*.skyscanner.pt
*.skyscanner.ro
*.skyscanner.se
```

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/5850/commits/03df0d76a9d416953c46c36f41e7c5a8e1ce9d3a.

I can confirm that `portal`, `gr`, and `ww2` fail in the browser. Please add `(incomplete certificate chain)` to them as noted in the checklist. By the way, `(incomplete certificate chain)` means that, in Firefox, the site gets a "Your connection is not secure" message with the following additional text:

>The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

Sometimes a particular user's browser might have already imported an intermediate certificate when visiting another site, which means that user (or tester) might not get the invalid certificate warning. So, I like to add `(incomplete certificate chain)` as a hint.

`api` and `business` really should work. Please add them back as `target`s. If Travis fails again, we'll look into the tests.

Also, the subdomains aren't sorted quite right. I've clarified the sort logic in the checklist. Subdomains should be grouped such that, for example, all the `.business.skyscanner.net` subdomains are near each other, with `^` and `www` at the top of their group and the rest sorted alphabetically.

**Comment by davidabian** [comment]
Thanks for your explanations, @jeremyn, they'll be really useful for future contributions. I hope that these changes are now correct.

**Comment by davidabian** [comment]
Concerning the other domains, apart from listed above, I've found:
```
*.skyscanner.at
*.skyscanner.ch
*.skyscanner.co.in
*.skyscanner.com.au
*.skyscanner.de
*.skyscanner.es
*.skyscanner.fr
*.skyscanner.ie
*.skyscanner.it
*.skyscanner.jp
*.skyscanner.nl
*.skyscanner.ru
```

**Comment by jeremyn** [comment]
Thanks.

I think the break lines you put into the ruleset like [this](https://github.com/davidabian/https-everywhere/blob/44c7c43f49e86fd2d787d5367073388a625940d7/src/chrome/content/rules/Skyscanner.net.xml#L47) are unnecessary and a little distracting, but we can keep them if you want.

Do you want to start figuring out the domains for the wildcards? The way I would organize it is that the wildcard groups that only have a small number of domains, like `*.skyscanner.at`, should go in `Skyscanner.net.xml`, and wildcard groups with a lot of domains, like `*.skyscanner.com`, should go in a new file like `Skyscanner.com.xml`. The two files should refer to each other, with the `.net` file as primary. See [`ACLU.xml`](https://github.com/EFForg/https-everywhere/blob/8fa39b32bbf1657df75975111f7ebdd1df2f8c4d/src/chrome/content/rules/ACLU.xml) for an example of this.

I recommend using Sublist3r to find the domains. See the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) for instructions on using it. Sublist3r can report a lot of what I might call "junk" domains that in my opinion you don't need to check or include, for example with `skyscanner.com` I wouldn't check `drupal-admin.skyscanner.com` or `wwww.skyscanner.com` or `www.miami.skyscanner.com`, but I would include `miami.skyscanner.com`. If you're not sure, include it.

**Comment by davidabian** [comment]
I've randomly checked out some domains `skyscanner.*`, and any of them (and any of their subdomains) supports HTTPS.

**Comment by jeremyn** [comment]
They need to be listed individually, though.

**Comment by jeremyn** [comment]
So there's no confusion, I'm currently waiting on you to update the pull request with individual `target`s for the wildcard subdomains.

**Comment by davidabian** [comment]
I'll be searching for all subdomains.

To investigate:
- [X] skyscanner.at (HTTPS unavailable)
m.skyscanner.at
skyscanner.at
w.skyscanner.at
ww.skyscanner.at
wwww.skyscanner.at
- [ ] skyscanner.ca
- [ ] skyscanner.ch
- [ ] skyscanner.co.in
- [ ] skyscanner.co.kr
- [ ] skyscanner.com
- [ ] skyscanner.com.au
- [ ] skyscanner.de
- [ ] skyscanner.dk
- [ ] skyscanner.es
- [ ] skyscanner.fr
- [ ] skyscanner.ie
- [ ] skyscanner.it
- [ ] skyscanner.jp
- [ ] skyscanner.nl
- [ ] skyscanner.no
- [ ] skyscanner.pt
- [ ] skyscanner.ro
- [ ] skyscanner.ru
- [ ] skyscanner.se
- [ ] skyscanneraffiliate.net
- [ ] *.skyscnr.com

**Comment by davidabian** [comment]
How should I order all these subdomains that aren't supporting HTTPS?

**Comment by jeremyn** [comment]
Thanks for researching that. They should go in a top comment with headings like `Invalid certificate`, `Time out` and so on. The headings should be in alphabetical order, and under each heading the subdomains should be in the same sort order we prefer for `target`s. [`glavbukh.ru.xml`](https://github.com/EFForg/https-everywhere/blob/33b1705128793ea25f926efab201249de32c6786/src/chrome/content/rules/glavbukh.ru.xml) is an example.

**Comment by jeremyn** [comment]
I've updated the checklist in https://github.com/EFForg/https-everywhere/pull/5850#issuecomment-264661113 through the latest commit https://github.com/EFForg/https-everywhere/pull/5850/commits/99e06ebaae1965a752d32e5670f8a970e5e2db56, including adding new items based on your changes.

**Comment by jeremyn** [comment]
I've modified the checklist in https://github.com/EFForg/https-everywhere/pull/5850#issuecomment-264661113 and pushed my own changes.

@gloomy-ghost @J0WI Can one of you please review my changes and merge this pull request?

**Pull request merged**
