### PR TITLE
tuquito.org.ar

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks.

- [ ] https://blog.tuquito.org.ar and https://fundacion.tuquito.org.ar have active mixed-content blocking. Please move those to a top comment and note the mixed-content blocking.

**Comment by galeksandrp** [comment]
Documented.

**Comment by jeremyn** [comment]
Thanks.

Why did you add `universo` and `urbano` to the comment? These don't exist at all, not even in DNS.

Also, for this and other pull requests, please don't squash your commits after each change. That makes it more difficult for me to review the changes. At the end I can [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) your commits to simplify the history if that's all right with you.

**Comment by galeksandrp** [comment]
Removed.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
