### PR TITLE
Update 3FM.xml

### PR DESCRIPTION
**Pull request by ihave100openPRs**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please split this into two ruleset files, one for `3fm.nl` and another for `npo3fm.nl`, and add some more subdomains for each, and I'll review this more closely.

**Comment by ihave100openPRs** [comment]
I think this should be ready.

**Comment by jeremyn** [comment]
Let's add those domains anyway.

`3FM.nl.xml`:
  
Mark as `Invalid certificate`:
- [ ] https://actie.3fm.nl
- [ ] https://go.3fm.nl
- [ ] https://kxradio.3fm.nl
- [ ] https://m.3fm.nl
- [ ] https://megatop50.3fm.nl
- [ ] https://metmichiel.3fm.nl
- [ ] https://michiel.3fm.nl
- [ ] https://now.3fm.nl
- [ ] https://radiomanager.3fm.nl
- [ ] https://seriousrequest.3fm.nl and add `(incomplete certificate chain)`
- [ ] https://stemmen.3fm.nl
 
`NPO3FM.nl.xml`:

No changes needed.

**Comment by ihave100openPRs** [comment]
@jeremyn Thanks, added!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
