### PR TITLE
Create mtlbss.com.xml

### PR DESCRIPTION
**Pull request by stlwvikx**

### CODE REVIEW

**Comment by stlwvikx** [comment]
@Hainish @jeremyn @J0WI @gloomy-ghost @ivysrono 
Three months later, could you review?

**Comment by jeremyn** [comment]
Thanks for your contribution, however please don't ping specific people to review specific pull requests unless they are already involved with it.

**Comment by jeremyn** [comment]
@stlwvikx Are you still interested in working on this?

**Comment by jeremyn** [comment]
The casing of the `ruleset` `name` and filename aren't exactly what we prefer, but since the ruleset is otherwise okay and @stlwvikx is unresponsive, I've merged this as it is.

**Pull request merged**
