### PR TITLE
Update QQ.xml QQ.com-mixedcontent.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Remove commented target in QQ.xml that also exists in mixedcontent
Enable connect, imgcache, jsqmt in QQ.xml
Move kf, pay to mixedcontent
service has been suspended

### CODE REVIEW

**Comment by J0WI** [comment]
This branch conflicts, could you rebase it?

**Comment by gloomy-ghost** [comment]
Done

**Comment by gloomy-ghost** [comment]
Sorry, not good at merging, will sort it out later...

**Comment by gloomy-ghost** [comment]
> [L208](https://travis-ci.org/EFForg/https-everywhere/jobs/162099778#L208)
> INFO Finished comparing http://service.qq.com/product/QQ.html -> https://kf.qq.com/product/QQ.html. Rulefile: src/chrome/content/rules/QQ.com-mixedcontent.xml.
> encoding error : input conversion failed due to input error, bytes 0xE6 0x9C 0x89 0xE6

> [L242](https://travis-ci.org/EFForg/https-everywhere/jobs/162099778#L242)
> INFO Finished comparing http://exmail.qq.com/ -> https://exmail.qq.com/. Rulefile: src/chrome/content/rules/QQ.xml.
> encoding error : input conversion failed due to input error, bytes 0xE8 0x85 0xBE 0xE8

What are these encoding?

**Comment by gloomy-ghost** [comment]
I have a guess, maybe someone who is good at coding can check the auto-check script to confirm it.

First, take a look at the UTF-8 of 腾讯, the company who owns qq.com.
`0xE8 0x85 0xBE` ----> 腾
`0xE8 0xAE 0xAF` ----> 讯

And the [L243](https://travis-ci.org/EFForg/https-everywhere/jobs/162099778#L243) error says: `0xE8 0x85 0xBE 0xE8`
So it is possible to be a part of UTF-8 encoding, but why there is an error? This is an interesting point. 

Here is the header of `en.exmail.qq.com`, which is the target behind `exmail.qq.com`:
```
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Fri, 23 Sep 2016 05:45:55 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 9307
Connection: keep-alive
Set-Cookie: ssl_edition=e1.exmail.qq.com; Domain=.exmail.qq.com; Path=/
Content-Encoding: gzip
```

Nothing wrong, right? Then check what is in HTML:
```
<!DOCTYPE html><html><head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="save" content="history"/>
        <link rel="shortcut icon" href="/favicon.ico"/>
        <title>腾讯企业邮箱 - 英文版</title>
        <meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
```
Well (*Φ皿Φ*)

CC: @renyouguo

**Comment by renyouguo** [comment]
So , I +1 the #6749

**Comment by gloomy-ghost** [comment]
I am getting a bunch of `Not enough tests` error when I try to run `fetch-test.sh` locally. Did I misread any manuals?

**Comment by jeremyn** [comment]
Is this ready for review?

**Comment by gloomy-ghost** [comment]
I think so...

**Comment by ivysrono** [comment]
https://wp.qiye.qq.com/qidian/2852065596/9117acda68f7ee9490b2746dcd39fd00
https://wj.qq.com/

**Comment by ivysrono** [comment]
https://img1.write.qq.com/upload/cover/2016-09-26/cs_57e8da4a552c6.jpg
https://jqmt.qq.com/cdn_dianjiliu.js
https://ossweb-img.qq.com/images/js/mms/account.book.qq.com.js

位置要上移：
https://jsqmt.qq.com/cdn_djl.js

**Comment by ivysrono** [comment]
还有好多相应注释需要删除修改…

**Comment by gloomy-ghost** [comment]
话说这些网站的注释真是维护的负担……这都还没列全呢（

完全不知道列这些子域名的有什么用，#6863 之类的讨论有空的时候可以推动一下

**Comment by gloomy-ghost** [comment]
@jeremyn When is the next release? I wish to finish this before the due.

**Comment by ivysrono** [comment]
MCB:
https://igame.qq.com/login.php

**Comment by ivysrono** [comment]
https://dldir1.qq.com/invc/tt/QQBrowser_Setup_9.5.9507.400.exe

**Comment by gloomy-ghost** [comment]
image

**Comment by ivysrono** [comment]
[【10月28日更新】QQ浏览器9.5.1正式版发布了 - QQ浏览器论坛](http://bbs.browser.qq.com/thread-221045-1-1.html)
（P.S. 如果以上链接下载到旧版安装包的童鞋，可以把链接中的http改成https再下载试试，没错，为了防止被劫持我们已经默默地开启了https模式/害羞）

**Comment by ivysrono** [comment]
https://shp.qlogo.cn/ttsing/40297318/40297318
https://wx.qlogo.cn/mmopen/PiajxSqBRaEJmzddrgRDEwqtNgZl6F4wKLR00a7FM21ZCwiciaAjChmWBmK9Sv3CAQCZyn0icNdaImAsBliaj723sow/0

**Comment by gloomy-ghost** [comment]
这两个用百度不加site指令就能找到

**Comment by ivysrono** [comment]
https://weread.qq.com/

**Comment by gloomy-ghost** [comment]
Holy crab. I think we are making this PR too big and no one is going to review it.

**Comment by ivysrono** [comment]
https://q.qlogo.cn/qqapp/100273305/ABBFF08D10BB88D4628A11925D7AB428/100

要不开个新的，看起来清楚些？

**Comment by ivysrono** [comment]
https://im.qq.com/
https://sqimg.qq.com/qq_product_operations/im/2015/newicon.png

**Comment by gloomy-ghost** [comment]
@ivysrono 你不介意的话我把commits都理一遍

**Comment by ivysrono** [comment]
当然不介意，理清楚了好。
growth.video.qq.com 不会又是 ChinaOnly 吧。

**Comment by gloomy-ghost** [comment]
@ivysrono 我这边也是证书错误……另外合并了几个commits

<details><summary>Before/After</summary>
image
image
</details>

**Comment by gloomy-ghost** [comment]
@jeremyn I know this PR is quite tricky, but could you have a look? It updated an alexa top-10 site with its CDNs.

**Comment by jeremyn** [comment]
Is there any way you can break this up into multiple, smaller pull requests? We can do them one at a time.

**Comment by gloomy-ghost** [comment]
@jeremyn The updates of `Qlogo.cn.xml` is at #7586

**Comment by ivysrono** [comment]
@gloomy-ghost 要更新呢……

**Comment by gloomy-ghost** [comment]
Rebased

**Comment by ivysrono** [comment]
https://vv.video.qq.com/crossdomain.xml

**Comment by gloomy-ghost** [comment]
@jeremyn I'm trying to split the diffs into small steps, start from #8202

**Comment by gloomy-ghost** [comment]
```
ERROR src/chrome/content/rules/QQ.xml: Fetch error: http://lmbsy.qq.com/ => https://lmbsy.qq.com/: (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
ERROR src/chrome/content/rules/QQ.xml: Fetch error: http://r.qq.com/ => https://r.qq.com/: (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
ERROR src/chrome/content/rules/QQ.xml: Fetch error: http://reader.qq.com/ => https://reader.qq.com/: (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
ERROR src/chrome/content/rules/QQ.xml: Fetch error: http://ugcbsy.qq.com/ => https://ugcbsy.qq.com/: (35, 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure')
```

@Hainish Either ssllabs or me can reproduce the issue travis-ci reported, can you have a look?

**Comment by Hainish** [comment]
@gloomy-ghost this may be just an intermittent TLS error.  Re-running locally to see if I can reproduce the error.

**Comment by jeremyn** [comment]
For the handshake problem, see also https://github.com/EFForg/https-everywhere/pull/8614#issuecomment-282105007 and https://github.com/EFForg/https-everywhere/pull/8640#issuecomment-282105814.

**Comment by Hainish** [comment]
This should be fixed by https://github.com/EFForg/https-everywhere/commit/403c46296f54b9e9e402c82ac0b6ca71c24dbcc2

Rerunning tests

**Comment by Hainish** [comment]
@gloomy-ghost have you had a chance to look at the `rules` test here?

**Comment by Hainish** [comment]
@gloomy-ghost ping

**Comment by ivysrono** [comment]
@Hainish Would this be merged to 5.2.16?

**Comment by ivysrono** [comment]
@Hainish Would this be merged to 5.2.16?

**Comment by ivysrono** [comment]
@J0WI @Hainish ping

@gloomy-ghost and I are very busy recently, no much time to submit new rules. QQ is the most important site for Chinese people , please review and merge this PR as soon as possible.

**Comment by J0WI** [comment]
Travis still reports various errors.

**Comment by Hainish** [comment]
This appears to be a ruleset error rather than a travis error: https://travis-ci.org/EFForg/https-everywhere/jobs/228812012
I get a certificate warning for `wpa.b.qq.com` as well.

**Comment by ivysrono** [comment]
https://wpa.b.qq.com/
Only avaiable in China......

**Comment by gloomy-ghost** [comment]
`wpa.b.qq.com` looks good to me:

<details><summary>Certificate</summary>

```
-----BEGIN CERTIFICATE-----
MIIG8jCCBdqgAwIBAgIQELXw7hOW6rSQ6H24+1W2cjANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE2MDMyMzAwMDAwMFoX
DTE5MDMyMzIzNTk1OVowgY8xCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlHdWFuZ2Rv
bmcxETAPBgNVBAcUCFNoZW56aGVuMTYwNAYDVQQKFC1UZW5jZW50IFRlY2hub2xv
Z3kgKFNoZW56aGVuKSBDb21wYW55IExpbWl0ZWQxDDAKBgNVBAsUA1ImRDETMBEG
A1UEAxQKKi5iLnFxLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AKOsBquNqF/l/pXJUzM6onrGzUhPm2YaotDc8rWqs5dCGD2vwlvF+QDu5tbe06Wn
DWAlBqcjkQCFZwXWMjSl+o5zLSGvaxuXUUr+O7HGbdXQBIoJTqAa3mftSIlvRBI2
Upnu2T39miZnOv28dMdo4FqRxtoPKqsDXC8dgA6+DYXCxOu6Km78AuGOZtsbsugN
7NAPtCsWkoWNefFkklAwH2rxQ4lCQV8yn+VIO8VOdV27kZ+WcT1pwbCTj07F7cB1
Wr42WLTfSny5clcp0b3KcOyeGVdAmMVeVIWRh8GIc2JPucvIqkGfIWmGat/X0cki
71v2ggTMVjws51iUFwGLO/kCAwEAAaOCA1gwggNUMBUGA1UdEQQOMAyCCiouYi5x
cS5jb20wCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwKwYDVR0fBCQwIjAgoB6g
HIYaaHR0cDovL3NzLnN5bWNiLmNvbS9zcy5jcmwwYQYDVR0gBFowWDBWBgZngQwB
AgIwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYB
BQUHAgIwGQwXaHR0cHM6Ly9kLnN5bWNiLmNvbS9ycGEwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFF9gz2GQVd+EQxSKYCqy9Xr0Qxjv
MFcGCCsGAQUFBwEBBEswSTAfBggrBgEFBQcwAYYTaHR0cDovL3NzLnN5bWNkLmNv
bTAmBggrBgEFBQcwAoYaaHR0cDovL3NzLnN5bWNiLmNvbS9zcy5jcnQwggH1Bgor
BgEEAdZ5AgQCBIIB5QSCAeEB3wB1AN3rHSt6DU+mIIuBrYFocH4ujp0B1VyIjT0R
xM227L7MAAABU6K9FEIAAAQDAEYwRAIgWaGAzRkof9wXZO8L1dPdDHCSgLJsBXE5
MRiWxSSOS7UCIDrOa+ZTN0Qu7pNsZvHiaqyELz/wi5xtjAFptF4W167BAHYApLkJ
kLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFTor0UdwAABAMARzBFAiAF
I5wXXYm0v5U+du8sqMLMDVz5HyAEZJKtXwU+y9ZXzgIhAMVqv8Rywb0ztxLePD3m
LKx0+HjCzKr+7hPOw7l0jxImAHYAaPaY+B9kgr46jO65KB1M/HFRXWeT1ETRCmes
u09P+8QAAAFTor0UYQAABAMARzBFAiEAkq/VfGCknzpIgglsb6LH9HF3RkofAd7V
x0waqkUlf+YCIAq8Vl6PbA9zJIYcTkGUc/GlkOJAFG+AE3p7NOlDM1/YAHYA7ku9
t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFTor0WNwAABAMARzBFAiEA
zABpOY/4BQ7y9jZBnP2XjJYSKEsen8zchTVpTO0OamUCIBWM4A9veasIZ6RecyPp
l8p9Egf/lNery2q4PMs1bK+SMA0GCSqGSIb3DQEBCwUAA4IBAQAZUo0E8oIKWfGv
bUldMa4K8JufF2MxmbMuc5nh/4QchUR1owWaCi017qrlnpC/oQ9QocRhXKQ4u6G8
3QSl4+NFvXc938N1+8VOezFwLkcbaLT2SuVKSKsxBYo0Dk/4ps6A2bCqbAU5amdJ
uMkqZa48Ar6OMrA6K/blgXgrMysTDysGp0OhY4tr+SWvrmFiaxcIS3m2beMks7u6
R2HBJL2h8mh3kSp21yNECDrcWSnZlcjZxY1dhpMVHzjKIe9g8pDGF6LKsaY/8VhO
v4dlULP3NWMbNUWZGSfOskpFxWQbWQINExqXlBLkrzFZ5Al4XbBIEygsl6SiION2
OJh8ntd7
-----END CERTIFICATE-----
```

</details>

**Comment by ivysrono** [comment]
Oh，I get mismatched and expired on https://wpa.b.qq.com/$ now, however, ok on https://wpa.b.qq.com/cgi/wpa.php

**Pull request merged**
