### PR TITLE
Create ruleset: Blog.ir

### LINKED ISSUE #15446: blog.ir redirect
Type: new ruleset

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: blog.ir

Someone reached out to us via email:

> Hello.Thanks for HTTPS Everywhere extension.
> I want to add redirect support from http://*.blog.ir domains to secure https://*.blog.ir. thanks.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

### PR DESCRIPTION
**Pull request by injust**
Fixes #15446

### CODE REVIEW

**Comment by injust** [comment]
I don't understand why the 3 test URLs consistently fail the fetch tests. I can't reproduce the connection timed out errors.

**Comment by Bisaloo** [comment]
HTTPS does not seem to work for 4th level subdomains. See for example http://uniquemdf.ir.domains.blog.ir/post/%D9%86%D8%AA%D9%86

**Comment by Bisaloo** [comment]
@J0WI, can you confirm this works for you as well? I'm not sure why travis failed.

**Comment by J0WI** [comment]
Yes, they WFM. Travis might be blocked by the host.

**Pull request merged**
