### PR TITLE
Dockerize ESLint

### PR DESCRIPTION
**Pull request by koops76**
ping @Hainish @cowlicks.

### CODE REVIEW

**Comment by koops76** [comment]
We mount `/opt` to be `/chromium`. Should probably make it more obvious.

**Comment by koops76** [comment]
@cowlicks @Hainish Review please.

**Comment by cowlicks** [comment]
@koops76 sorry if my question was unclear. I'd like to know *why* we should dockerize this test? It seems like it adds an unnecessary layer of abstraction.

**Comment by koops76** [comment]
@cowlicks Speeds up the test, since we already have node dockerized, but we have to install ESLint each time.

**Comment by cowlicks** [comment]
@koops76 I'm working on a PR that will run eslint as an independent test in travis. So it won't run for every test in travis #12624

**Comment by koops76** [comment]
@cowlicks Closing until you finish.

**Comment by koops76** [comment]
Closing in favor of #12624.

**Pull request closed without merging**
