### PR TITLE
Simplify code and consider xmlhttprequest and sub_frame active content, identical to current Chrome version.

### PR DESCRIPTION
**Pull request by koops76**
ping @Hainish @cowlicks.

### CODE REVIEW

**Comment by koops76** [comment]
@cowlicks Review please.

**Comment by Hainish** [comment]
This breaks the enumeration of the number of passive & active resources under each of the 2 headers,

```Unrewritten HTTP resources loaded from this tab (enable HTTPS on these domains and add them to HTTPS Everywhere):```

and

```Resources rewritten successfully from this tab (update these in your source code):```

For instance, if I went to https://www.boingboing.net/, it would show me under unrewritten:

```boingboing.net: 1 passive```

Now it shows:

```boingboing.net:```

**Comment by koops76** [comment]
@Hainish Try now.

**Comment by Hainish** [comment]
LGTM

**Comment by Hainish** [comment]
Since you're signing commits, do you want to squash & sign or are you okay with me squashing, which will lose your signature?

**Comment by koops76** [comment]
@Hainish Squash please, the signature is added by GitHub.

**Pull request merged**
