### PR TITLE
Update default_off="regional" rulesets

### PR DESCRIPTION
**Pull request by cschanaj**
#9906

### CODE REVIEW

**Comment by jeremyn** [comment]
Problems with rulesets for sites in China can be more complicated than `This ruleset contains hosts that available in China ONLY.` For example in some cases I've seen where we get different behavior because a different CDN is used inside China vs outside it and the HTTPS certificates are only configured correctly for one of the CDNs.

@gloomy-ghost and @ivysrono , it would be good to get your feedback on this pull request when you have the time.

**Comment by ivysrono** [comment]
I don't think we should add too much complicate comments, they are too hard to maintain and update.

BTW, all "Only avaiable in China" use *_CN.xml
Should you update them to *regional.xml ?

**Comment by ivysrono** [comment]
There is only one ruleset now: Baidu_CN.xml

**Comment by cschanaj** [comment]
Closing this, discussion will be continued in #9906

**Pull request closed without merging**
