### PR TITLE
Update schema.xml

### PR DESCRIPTION
**Pull request by pipboy96**
Follow-up to #17909.

### CODE REVIEW

**Comment by Bisaloo** [comment]
What's the reasoning behind disallowing non-ASCII characters? Are they causing any issue?

**Comment by pipboy96** [comment]
The last target that wasn't converted to Punycode was fixed. Also, I believe any target with these characters would be no-op, since HTTPS Everywhere doesn't decode Punycode.

**Comment by cschanaj** [comment]
> The last target that wasn't converted to Punycode was fixed. Also, I believe any target with these characters would be no-op, since HTTPS Everywhere doesn't decode Punycode.

I got the following extension log by pasting akademikerförsäkring.se into Chrome. It seems that the URL is Punycoded automatically before being passed to the extension. So I think they are not no-op. 

```
Ruleset cache hit for www.xn--akademikerfrskring-xtb17a.se items:0
util.js:26 onBeforeRequest returning shouldCancel: false
util.js:26 Ruleset cache hit for www.akademikerforsakring.se items:1
util.js:26 onBeforeRequest returning shouldCancel: false
util.js:26 Ruleset cache hit for cdn.optimizely.com items:1
util.js:26 onBeforeRequest returning shouldCancel: false
util.js:26 Ruleset cache hit for www.akademikerforsakring.se items:1
util.js:26 onBeforeRequest returning shouldCancel: false
util.js:26 Ruleset cache hit for www.akademikerforsakring.se items:1
util.js:26 onBeforeRequest returning shouldCancel: false
```

**Comment by cschanaj** [comment]
> The last target that wasn't converted to Punycode was fixed. Also, I believe any target with these characters would be no-op, since HTTPS Everywhere doesn't decode Punycode.

It seems that they are in fact no-op :thinking:

**Comment by Hainish** [comment]
Thanks!

**Pull request merged**
