### PR TITLE
WIP: Reorganize Options UI with Dark Mode (#17882)

### PR DESCRIPTION
**Pull request by bershanskiy**
# WORK IN PROGRESS! DO NOT MERGE!

This implements some ideas described in #17882, please see that issue for explanation of motivations for this change.

## Proposal
 - Make all tabs have the same height by making the UI fill all vertical space. (WIP)
 - Make the tab buttons smaller and fixed to the top of the page. (WIP)
 - Move "HTTPS Everywhere Sites Disabled" list and "User rules" form "General Settings" into separate tabs. (done)
 - Move all check boxes from "General Settings" and "Advanced Settings" onto the same tab called just "General Settings" or similar. (done)
 - May be, for each checkbox item add a small explainer about what exactly it does (to clarify the impact of the setting and to fill up the extra vertical space).

## Result (work in progress)
The resulting tabs are:
 - "General Settings"
    - checkbox "Show Counter" (if not removed)
    - checkbox "Dark Mode" (if not removed when media query [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) land in stable releases.)
    - checkbox "Auto-update rulesets"
    - checkbox "Enable mixed content rulesets"
    - checkbox "Show Devtools tab"
 - "Sites Disabled"
 - "Custom Rulesets"
 - "Update Channels" (left intact)

## Screenshots
This is already implemented and works as expected. Screenshots are taken in Chrome because Firefox does not support dark mode on Extension pages yet.

Edit: updated screenshot to remove "show counter"
light

dark

eff

### CODE REVIEW

**Comment by zoracon** [comment]
Hello, Thank you for this work! There have been a patch made since then to remove the now deprecated "show counter". I plan on doing one more patch that shouldn't effect this branch, but once I do that Monday, I'll pull this down afterwards to my fork and review as soon as I can.

**Comment by zoracon** [comment]
Also, are these dark mode changes also applicable in Chrome/Chromium?

**Comment by bershanskiy** [comment]
@zoracon Thanks for your response.

I'll bring this branch up to date before Monday (e.g., remove the "show counter").

> Also, are these dark mode changes also applicable in Chrome/Chromium?

The patch does not make any distinctions between Chromium and Firefox, it just has the "Dark Mode" toggle so that anyone with current browser can test it. Ideally, this patch should use the [prefers-color-scheme media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but this media query is not widely supported yet: desktop and Android Firefox 67 (see MDN), macOS Safari 12.1 (see MDN), Chrome/Chromium 76 [(source)](https://www.chromestatus.com/feature/5109758977638400). FYI, Firefox "resist fingerprinting" forces media query to always match for "light" option.

I'm not sure what is the best way forward on this, options are:
1. use only media query, no toggle, and support dark mode only on newer browsers (low maintenance cost, no JS code).
2. use manual toggle even if media query is supported, as I do currently (low maintenance cost, but poor user experience)
3. detect whether media query is supported with JS API and if supported rely on it, otherwise present the manual toggle (higher maintenance cost, but good user experience).

I would very much prefer option 3 (because it has the best UX), but it does have a few edge cases to test.

**Comment by bershanskiy** [comment]
Update: I just force-pushed after `git pull upstream master --rebase` to simplify the review of the commit.

**Comment by pipboy96** [comment]
Can you fix merge conflicts?

**Comment by bershanskiy** [comment]
@pipboy96 I resolved conflicts via the GitHub online interface, but I'll also test it for real as well. I'll comment when I'm done.

**Comment by bershanskiy** [comment]
Update: so something between Git and GitHub was weird and it didn't allow me to push normally, so I force-pushed. The old branch up to this point can be found on `17882-old`.

**Comment by pipboy96** [comment]
@bershanskiy Do you have any plans to continue work on this?

**Comment by bershanskiy** [comment]
@pipboy96 Yes, I do. I just got swamped with other stuff.

**Comment by pipboy96** [comment]
Related PR: #18992.

**Comment by pipboy96** [comment]
@bershanskiy If you want to continue work on this, feel free to ask for this PR to be reopened.

**Pull request closed without merging**
