### PR TITLE
add Vrsinfo.de.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Delete entirely:
- [ ] https://16test.vrsinfo.de (not in DNS)
- [ ] https://piwik.vrsinfo.de (`403` and it's internal)
  
Mark as `Invalid certificate`:
- [ ] https://auskunft1.vrsinfo.de (and remove `target`)
- [ ] https://m.vrsinfo.de

Mark as `Time out`:
- [ ] https://android.vrsinfo.de
- [ ] https://ekapwebcache.vrsinfo.de
  
Add `target`:
- [ ] https://download.vrsinfo.de
- [ ] https://festival.vrsinfo.de
- [ ] https://gewinnspiele.vrsinfo.de
- [ ] https://handyticket.vrsinfo.de
- [ ] https://static.vrsinfo.de
- [ ] https://test.vrsinfo.de
- [ ] https://umfrage.vrsinfo.de (and remove from comment)

**Comment by J0WI** [comment]
rebased & fixed

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9388/commits/dda0a354023cc7b631689ffc4d9ae8bb21753f5b and added two "Also" items.

Do you want to keep `piwik`?

**Comment by J0WI** [comment]
Done. piwik is already removed from the list of targets.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9388/commits/a5f2a2b3223724d8eb85d7dd1bbc9d5566bfe64c.

I meant we could remove `piwik` entirely from the ruleset, without even a comment, because it gets a `403` with both HTTPS and plain HTTP and it is likely entirely internal anyway.  We can include it as a comment if you want, I just want you to confirm.

**Comment by J0WI** [comment]
Confirm that I want to keep the comment for `piwik`.

**Comment by jeremyn** [comment]
Merged, thanks.

**Pull request merged**
