### PR TITLE
Update Akamai.xml

### LINKED ISSUE #6007: a248.e.akamai.net
This is likely to be a new pattern: 
https://a248.e.akamai.net/f/248/45380/10m/dac1.download.akamai.com/45379/rsi/ut/a_62_780.js

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Add a248.e.akamai.net
  Close #6007

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
It's hard to refactor this ruleset since lots of subdomains are invisible for search engines.

**Comment by jeremyn** [comment]
I'm concerned about you removing the bug-fix exclusions like [`<exclusion pattern="^http://zynga\d-a.akamaihd\.net/" />`](https://github.com/EFForg/https-everywhere/pull/7281/files#diff-4df3d62377e73ff22cb402ab7d053fd1L79). According to the Tor project link there, it was added to fix a bug related to a game called "Slingo". Have you tested that, for example, Slingo still works?

**Comment by gloomy-ghost** [comment]
I didn't mean to remove it, but it didn't have a testing URL when I was editing the ruleset. I got a testing URL http://zynga1-a.akamaihd.net/castleville/67866/gameSettings.xml via Google, and found that it supports https.

I'm unable to register an account on Slingo (the server always responds 400 for unknown reasons), however It would be great if you could try to test it.

**Comment by jeremyn** [comment]
I'm similarly concerned about removing the other bug-fix exclusion related to https://lists.eff.org/pipermail/https-everywhere-rules/2012-October/001322.html .

Can you reduce your changes to only the things you want to change? The tests might fail but at least we can see what you really want to do. Maybe we can figure something else out.

**Comment by gloomy-ghost** [comment]
```
ERROR src/chrome/content/rules/Akamai.xml: Not enough tests (5 vs 6) for <Exclusion pattern '^http://[\w_-]+-(?:f|i|s|lh|vh)\.akamaihd\.net/'>
ERROR src/chrome/content/rules/Akamai.xml: Not enough tests (0 vs 1) for <Exclusion pattern '^http://zynga\d-a.akamaihd\.net/'>
```

Before we start finding more tests, notice that the tests are all accessible in https since the certificate has `CN=*.akamaihd.net`

**Comment by J0WI** [comment]
@gloomy-ghost if it's impossible to find enough test urls this can be added to this whitelist:
https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-coverage-whitelist.txt

**Pull request closed without merging**
