### PR TITLE
New rules for KH Bank (Hungary)

### PR DESCRIPTION
**Pull request by hzsolt94**
Created and tested as a netbank user.

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks for your ruleset!

Please do the following changes:

Comments update:
- [ ] [00README](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/00README) already mentioned that rulesets are contributed by users so you don't need to repeat it in comment.
- [ ] Also you don't need to indicate the status of HSTS.

Note as `Invalid Certificate`:
- [ ] mi-sentry-test.kh.hu
- [ ] edma.khb.hu

`PROTOCOL_ERROR`:
- [ ] karrierutak.kh.hu

`Reset`:
- [ ] im.kh.hu

`Timeout`:
- [ ] aliases.kh.hu
- [ ] rtitest.kh.hu
- [ ] www.szepkartya.kh.hu
- [ ] alapok.khb.hu
- [ ] www.enkartya.khb.hu
- [ ] job.khb.hu

Add targets:
- [ ] biztosnetws.kh.hu
- [ ] biztosnetwsact.kh.hu
- [ ] cawo.kh.hu
- [ ] cawo-uat.kh.hu
- [ ] engedmenyes.kh.hu
- [ ] faktor.kh.hu
- [ ] www.flexims.kh.hu
- [ ] jeti.kh.hu
- [ ] karrier.kh.hu
- [ ] kbcrtu.kh.hu
- [ ] kbcrtulra.kh.hu
- [ ] lyncdiscover.kh.hu
- [ ] mi-vsp.kh.hu
- [ ] mi-vsp2.kh.hu
- [ ] mobilebank.kh.hu
- [ ] partner.kh.hu
- [ ] partnerws.kh.hu
- [ ] partnerwsact.kh.hu
- [ ] portal.kh.hu
- [ ] szepkartya.kh.hu
- [ ] www.enkartya.tervezes.kh.hu
- [ ] www.beszerzes.khb.hu
- [ ] www.ebank.khb.hu

Also:
- [ ] In all cases where there is a list of domains, sort them in alphabetical order starting from the top level domain at the right reading left, moving ^ and www to the top of their group.
- [ ] Add a `securecookie` if you want.

**Comment by hzsolt94** [comment]
Hand-tested all the domains you mentioned and updated the file:
 - Added all of the working https subdomains
 - Noted all all broken https sites, where http is working
 - Made redirects to fix broken https where possible
 - Ordered all the domain names

However, I refuse to add most of the domains because:
 - they aren't working under http either, or
 - they aren't offering web services neither under http or https.

Please review and accept.

**Comment by hzsolt94** [comment]
Added technical and broken domains, updated redirects. Is that OK?

**Comment by gloomy-ghost** [comment]
Thanks, I've updated the checklist through 1e760cb.

The last thing is about ruleset style, you can find a full explanation at [ruleset-style.md](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md)

**Comment by hzsolt94** [comment]
At the moment of creating 1e760cb the www.khb.hu domain was broken. Now it's working again. The ebank uses the securecookie flag correctly, so the securecookie tag is not needed.

Refactored the whole file according to the style guides, into single commit 5bc11c7. I hope that's OK now.

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Pull request merged**
