### PR TITLE
Add SMWCentral rule

### PR DESCRIPTION
**Pull request by smw-koops**
Added SMWCentral rule.

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please list subdomains as targets instead of using wildcard.
And also add `misc.smwcentral.net` as a target.

Please note dev.smwcentral.net as `Invalid certificate` in a top comment.

**Comment by smw-koops** [comment]
@gloomy-ghost I used a wildcard because SMWCentral may get additional subdomains in the future that will not be covered by the rule. Also how can I get a list of all subdomains? DNS records just point to gratisdns.dk NS.

**Comment by gloomy-ghost** [comment]
See https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

It's just a trade-off made by the project team, which I can't say it's perfect, but it is the rule.

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of #7552 .

**Pull request closed without merging**
