### PR TITLE
[Instagram.xml] add more subdomains

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
I haven't reviewed the whole change but I'm getting strange behavior on https://business.instagram.com . If I click "Watch the video" with the ruleset changes, it plays for a couple seconds and then stops. It works when I try it again. If I disable HTTPS Everywhere, it plays the first time without stopping. Does that happen for you too?

**Comment by J0WI** [comment]
The video loads fine for me.

**Comment by jeremyn** [comment]
Video works for me too now.

**Comment by jeremyn** [comment]
- [ ] Add target for https://instagrampartners.com
- [ ] Move target for `partners.business.instagram.com` directly under target for `business.instagram.com`

**Comment by J0WI** [comment]
added.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
