### PR TITLE
Updated kachelmannwetter.com

### PR DESCRIPTION
**Pull request by Jochen-A-Fuerbacher**

### CODE REVIEW

**Comment by J0WI** [comment]
I still have major mixed content issues on `wetterkanal.kachelmannwetter.com`.

**Comment by Jochen-A-Fuerbacher** [comment]
The mixed content issues come from included content from `http://wetterkanal.kachelmannwetter.com` that get redirected to https by this ruleset. So there souldn't be any mixed content issues on this website when using HTTPS Everywhere.

**Comment by J0WI** [comment]
The mixed content blocker is triggered before we can rewrite requests. So users will run into issues when browsing to this site.

**Comment by Jochen-A-Fuerbacher** [comment]
Thanks for this information. So I close this PR.

**Pull request closed without merging**
