### PR TITLE
Change single quote to double quote in automatically added default_off attribute.

### PR DESCRIPTION
**Pull request by pipboy96**

### CODE REVIEW

**Comment by cschanaj** [comment]
This change looks good to me :+1: , but I guess you should avoid creating your person branch on EFF's repo.

**Comment by pipboy96** [comment]
@cschanaj It was created in EFF repo since I used GitHub web interface.

**Comment by zoracon** [comment]
@pipboy96 you can create a branch on your repo and push to your repo. And in the web interface it normally picks up your new branch and has a prompt where you can create a PR to compare to the EFF repo.
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by pipboy96** [comment]
@zoracon The branch is usually outdated if created in that way.

**Comment by zoracon** [comment]
> @zoracon The branch is usually outdated if created in that way.

You can merge in EFF master upstream to keep your local fork up to date. I normally have multiple remotes and I do something like `git pull EFF master` to sync it up before making a branch to work on.

**Comment by pipboy96** [comment]
I use a different command:

    git checkout -b newbranch upstream/master

**Comment by zoracon** [comment]
> I use a different command:
> 
> ```
> git checkout -b newbranch upstream/master
> ```
Right, the command I mentioned would be the step you'd take prior to making a new branch, to make sure your repo is synced

**Pull request merged**
