### PR TITLE
Delete CERT.se.xml because HSTS-preload

### PR DESCRIPTION
**Pull request by hstseverywhere**
https://hstspreload.org/?domain=cert.se
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#hsts-preloaded-rules

### CODE REVIEW

**Comment by pipboy96** [comment]
Please make sure to set base branch to `master`, not `release` in the future.

**Comment by cschanaj** [comment]
@hstseverywhere We are using a script call `hsts-prune` to remove preloaded domains, usually when there is a new release.it is not needed to perform the removal manually.

**Comment by J0WI** [comment]
Closing for now due https://github.com/EFForg/https-everywhere/pull/17809#issuecomment-485389064

**Comment by hstseverywhere** [comment]
@cschanaj, if you agree that the hsts-prune utility does not cover all cases, how would you explain that manual removal is not needed? (Question relevant for documentation, I think)

https://github.com/EFForg/https-everywhere/issues/17820#issuecomment-486688092
https://github.com/EFForg/https-everywhere/issues/13682
https://github.com/EFForg/https-everywhere/pull/17805#issuecomment-486867281

**Comment by pipboy96** [comment]
@hstseverywhere It's mostly the fact that the tool itself needs to be fixed, instead of manual removal of preloaded targets.

**Pull request closed without merging**
