### PR TITLE
Akvorrat.at

### PR DESCRIPTION
**Pull request by MilanKral**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

Add `target`:
- [ ] https://lists.akvorrat.at
- [ ] https://montag.akvorrat.at
- [ ] https://obrien.akvorrat.at
- [ ] https://piwik.akvorrat.at
- [ ] https://soma.akvorrat.at
- [ ] https://spenden.akvorrat.at
- [ ] https://test.akvorrat.at
- [ ] https://timeline.akvorrat.at
- [ ] https://wiki.akvorrat.at

Also:
- [ ] Add a general `securecookie` like: `<securecookie host=.+" name=".+" />` between the `target`s and `rule`. See [here](https://www.eff.org/https-everywhere/rulesets#secure-cookies) for more information.
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) pull requests, which mean we combine and rewrite commits in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/7491/commits/ebc45be4533a27f055cd3b31c9692fe2320e851c , thanks for making the changes. Please just answer the squash-and-merge question and that should be all.

**Comment by MilanKral** [comment]
You can squash-and-merge all my commits.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
