### PR TITLE
[Drugcom.de] New ruleset

### PR DESCRIPTION
**Pull request by cypherpunk**

### CODE REVIEW

**Comment by fuglede** [comment]
Hi @cypherpunk. You actually want '.' instead of '\.' in your 'to'-attribute. The test fails because you should have trailing slashes in both 'to' and 'from' (so that 'drugcom.de' becomes 'drugcom.de/').

**Comment by cypherpunk** [comment]
Thanks. Done.

**Comment by TheNavigat** [comment]
LGTM. @fuglede Ping!

**Comment by fuglede** [comment]
Thanks for the fix. This ruleset is actually not entirely good: the site does not serve a complete certificate chain which means that the user will be presented with a warning unless she has obtained the intermediate certificate via some other website (in which case the intermediate certificate might be stored). The [SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=drugcom.de&latest) shows this error by indicating that the intermediate certificate is an "Extra download".

**Comment by semenko** [comment]
wfm now, merging

**Comment by fuglede** [comment]
@semenko: It's still broken:

    $ curl -I https://www.drugcom.de
    curl: (60) SSL certificate problem: unable to get local issuer certificate

**Pull request merged**
