### PR TITLE
Added a web.archive.org link

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes #(issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by KOLANICH** [comment]
Why was it just closed?

**Comment by zoracon** [comment]
@KOLANICH We are in the process of sunsetting the extension for January 2023. Announcement and details are here: https://github.com/EFForg/https-everywhere/discussions/20213

**Comment by KOLANICH** [comment]
I know you are "sunsetting" the extension. But I don't think it justifies closing the PR without testing and merging it.

**Comment by zoracon** [comment]
@KOLANICH We do not plan to do another release, so testing and merging a feature that will not be used is redundant. Apologies for the work that was put in to this and not merged in. It seemed like a cool feature. You are welcome to reuse the work you put into this extension to build a new one store that fulfills this purpose.

**Pull request closed without merging**
