### PR TITLE
add script to generate rulesets

### PR DESCRIPTION
**Pull request by pgerber**
Script to generate rulesets. It still needs some more tweaking but it is already useful for day-to-day use.

# Features
- read host from
  - textfile containing one host per line
  - DNS zone files
  - already existing ruleset
    - extract host names from comments
- write
  - list of host names (one per line)
  - write ruleset
    - detect errors and add comment to ruleset
    - write targets
    - add host to existing ruleset
- deterministic sorting of hosts

# Usage
```
$ ./utils/generate-ruleset.py --help
usage: generate-ruleset.py [-h] [-i INPUT] [-o OUTPUT] [-u]
                           [--line-parser | --zone-file-parser | --ruleset-parser]
                           [--rule-writer | --line-writer] [--threads THREADS]
                           [--http-status-codes HTTP_STATUS_CODES]

Generate and update rulesets for use with HTTPSEverywhere.

The ruleset written is formatted like this:
    <!--
        Non-functional hosts:
            Certificate mismatch:
                    - wrongcert.example.com
            Connection refused:
                    - host.example.com
                    - host2.example.com
    -->
    <ruleset "Example.com">
        <target host="example.com" />
        <target host="www.example.com" />
        <target host="a.example.com" />
        <target host="b.example.com" />

        <securecookie host=".+" name=".+" />

        <rule from="^http:" to="https:" />
    </ruleset>

This script attempt to detect errors and move host to the right
section in the header.

The following errors are currently detected:
• certificate mismatch
• connection refused
• http redirect
• self-signed certificate
• timeout on https
• unexpected http status code

optional arguments:
  -h, --help            show this help message and exit

input and output:
  -i INPUT, --input INPUT
                        File to write rules to. If omitted, output is written
                        to stdout.
  -o OUTPUT, --output OUTPUT
                        File to read host names from. If omitted, input is
                        read from stdin.
  -u, --update          Scan OUTPUT file for host names before overwriting it.
                        Host names are added to the host names found in INPUT
                        or on stdin.

available parsers:
  --line-parser         Input contains one host name per line. Empty lines are
                        ignored, comments start with # and whitespace is
                        stripped. This is the default parser.
  --zone-file-parser    Input is a DNS zone file.
  --ruleset-parser      Input is a HTTPSEverywhere ruleset file. Extracts all
                        host names in <target>s and attempts to extract host
                        names found in initial comment.

available writers:
  --rule-writer         Write a rule file. (default)
  --line-writer         Write host names line separated

misc.:
  --threads THREADS     Number of threads to use. Defaults to 25.
  --http-status-codes HTTP_STATUS_CODES
                        Comma separated list of http status codes that need to
                        be returned for http:// and https:// requests. Request
                        that return any other codes are moved to the
                        'unexpected http status code' section. Defaults to
                        '200,401'

examples:
    use host names provided by sublist3er [1]:
        $ sublist3r -d example.com -o hostlist.txt
        $ ./utils/generate-ruleset.py -i hostlist.txt -o rules/Example.com.xml

        [1]: https://github.com/aboul3la/Sublist3r

    update existing ruleset, add hosts in hostlist.txt:
        $ ./utils/generate-ruleset.py -i hostlist -u -o rules/Example.com.xml

    print hosts found in ruleset on stdout:
        $ ./utils/generate-ruleset.py -i rules.Example.com.xml --ruleset-parser --line-writer

```

# Real World Example

```
$ cat arbitrary.ch.list
may.arbitrary.ch
mx1.arbitrary.ch
ns1.arbitrary.ch
www.arbitrary.ch
test.arbitrary.ch
tor-relay1.arbitrary.ch
zoe.arbitrary.ch
arbitrary.ch
invalid.arbitrary.ch

$ ./utils/generate-ruleset.py -i arbitrary.ch.list -o rules/Arbitrary.ch.xml
host invalid.arbitrary.ch:
    • WARN:  skipping host, failed to fetch A/AAAA DNS entry
host may.arbitrary.ch:
    • ERROR: 'certificate mismatch': SSL connection failed for 'may.arbitrary.ch': hostname 'may.arbitrary.ch' doesn't match either of 'www.arbitrary.ch', 'arbitrary.ch'
host mx1.arbitrary.ch:
    • ERROR: 'certificate mismatch': SSL connection failed for 'mx1.arbitrary.ch': hostname 'mx1.arbitrary.ch' doesn't match either of 'www.arbitrary.ch', 'arbitrary.ch'
host ns1.arbitrary.ch:
    • ERROR: 'timeout on https': Connection timed-out for 'ns1.arbitrary.ch': HTTPSConnectionPool(host='ns1.arbitrary.ch', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd499a44208>, 'Connection to ns1.arbitrary.ch timed out. (connect timeout=30)'))
host test.arbitrary.ch:
    • WARN:  https:// url redirects to http://: https://test.arbitrary.ch/ → http://test.tocco.ch/ → https://test.tocco.ch/
host tor-relay1.arbitrary.ch:
    • ERROR: 'self-signed certificate': Self-signed certificate encountered for host 'tor-relay1.arbitrary.ch': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
host zoe.arbitrary.ch:
    • ERROR: 'timeout on https': Connection timed-out for 'zoe.arbitrary.ch': HTTPSConnectionPool(host='zoe.arbitrary.ch', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd499a4c518>, 'Connection to zoe.arbitrary.ch timed out. (connect timeout=30)'))

$ cat rules/Arbitrary.ch.xml
<!--
        Non-functional hosts:
                Certificate mismatch:
                        - may.arbitrary.ch
                        - mx1.arbitrary.ch
                Self-signed certificate:
                        - tor-relay1.arbitrary.ch
                Timeout on https:
                        - ns1.arbitrary.ch
                        - zoe.arbitrary.ch
-->
<ruleset name="rules/Arbitrary.ch">
        <target host="arbitrary.ch" />
        <target host="www.arbitrary.ch" />
        <target host="test.arbitrary.ch" />

        <securecookie host=".+" name=".+" />

        <rule from="^http:" to="https:" />
</ruleset>
```

### CODE REVIEW

**Comment by jeremyn** [comment]
@pgerber Thanks for this. While having an automated ruleset creator is a very important goal, you are the fourth person I know of who is separately working on this. I strongly encourage you to participate in the discussion in issue https://github.com/EFForg/https-everywhere/issues/7691 so we can get everyone working together. This is absolutely not to say that your code is deprecated, rather that it's important for consistency that we only have one automated process. I like that your code is in Python and it might make a solid base.

**Comment by galeksandrp** [comment]
@pgerber 
```bash
git clone -b generate_ruleset https://github.com/pgerber/https-everywhere.git
docker run --rm -ti -v $(pwd):/opt -w /opt electronicfrontierfoundation/https-everywhere-docker-base
apt-get update
apt-get install -y python3-dnspython python3-requests
./utils/generate-ruleset.py --help
```
```bash
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 1057: ordinal not in range(128)
```
[`electronicfrontierfoundation/https-everywhere-docker-base`](https://hub.docker.com/r/electronicfrontierfoundation/https-everywhere-docker-base/) [](https://microbadger.com/images/electronicfrontierfoundation/https-everywhere-docker-base "Get your own image badge on microbadger.com") is official `@EFForg` docker box on which Travis CI tests executed.
```bash
root@3b13a6634ff1:/opt# python3 --version
Python 3.5.2
root@3b13a6634ff1:/opt# lsb_release -a    
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```
Seems that python3 is somewhat old.

**Comment by pgerber** [comment]
The issue is caused by the locale:

```bash
root@fb7a4ab0c596:/opt# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

The help text contains Unicode characters that can't be represented by ASCII.

This works:
```bash
locale-gen en_US.UTF-8
LC_ALL=en_US.UTF-8  utils/generate-ruleset.py --help
```

I'd say on Linux it's reasonable to assume that Unicode characters are supported. Don't know how other platforms handle it.

**Comment by cowlicks** [comment]
@pgerber what is the status of this?

**Comment by jeremyn** [comment]
@cowlicks There are several competing implementations of ruleset generators as @galeksandrp describes in https://github.com/EFForg/https-everywhere/issues/7691#issuecomment-290367061. I more or less agree with @Foorack 's suggested approach at https://github.com/EFForg/https-everywhere/issues/7691#issuecomment-290392594:

> It is in my opinion that a working group on the issue should be set-up (either by EFF or community based). The working group should discuss the best implementation and document the different scenarios that should be taken into consideration when generating rules. This should be a public discussion. (example:  [Chrome 301 header truncation error](https://github.com/Foorack/httpse-ruleset-generator/blob/e168d5ee0b9327832ac33f3333b87c1b91961baf/old-ruleset-generator.py#L193) We should then work together and implement it in a single repository to prevent code and efforts duplication. It would be up to the EFF if they want to create a separate repository, if the group of people coding it should create the project or if it should be added into the HTTPSE repository like the other scripts.

except that, since the EFF appears to prefer tight ownership of the overall project and doesn't have a general path to incorporate larger user-driven subprojects (see https://github.com/EFForg/https-everywhere/issues/9111#issuecomment-320453076), the burden is on the EFF to step up and lead this effort. In other words the EFF needs to convincingly show that it really wants this to happen and will give it first-class support indefinitely, before it expects volunteers to put more work into it.

On the other hand, a working and well-maintained generator would be a big help for contributors and maintainers. Maybe @brainwane or @wonderchook will want to look into this.

**Comment by brainwane** [comment]
@jeremyn Thanks for drawing my attention to this issue and to the larger governance questions you see -- I'm looking into both. Sorry for the wait.

**Comment by zoracon** [comment]
We now have a "trivial ruleset" script in place. Closing out

**Pull request closed without merging**
