### PR TITLE
Add VGChartz.com.xml

### PR DESCRIPTION
**Pull request by pipboy96**

### CODE REVIEW

**Comment by J0WI** [comment]
> Blocked loading mixed active content "http://code.jquery.com/jquery-migrate-1.2.1.js"

**Comment by pipboy96** [comment]
@J0WI On which URL?

**Comment by J0WI** [comment]
On `https://www.vgchartz.com/`. `https://gamrconnect.vgchartz.com/newuser.php` is even worse.

**Comment by J0WI** [comment]
You can just add the `platform="mixedcontent"` attribute.

**Comment by pipboy96** [comment]
@J0WI Not much sense in that, since MCB is on in all browsers incl. Tor.

**Pull request closed without merging**
