### PR TITLE
[Sachsen.de] New ruleset

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by rugk** [comment]
Any news? Anything I should change?

**Comment by J0WI** [comment]
It's a huge list of domains, that requires much time to test.

**Comment by J0WI** [comment]
I get a timeout on landwirtschaft.sachsen.de

**Comment by rugk** [comment]
With NoScript I get a ABE error... :confounded: 

Using curl I get a 301 to a local (!) IP (over HTTPS) - This also explains the NoScript blocking:
`curl -I landwirtschaft.sachsen.de
HTTP/1.1 301 MOVED PERMANENTLY
Date: Tue, 10 May 2016 19:14:20 GMT
Server: Apache
Location: https://172.22.14.11/
Content-Type: text/plain
`

However when I created the ruleset I'm quite sure the domain was accessible.

**Pull request merged**
