### PR TITLE
added rule for Nordkurier

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by fuglede** [comment]
Came across a few issues while looking at scattered parts of this one:

* https://www.nordkurier.de/kleinanzeigen/kfz.php and https://www.nordkurier.de/kleinanzeigen/sms.php have some mixed content issues
* https://www.nordkurier.de/sap%28cz1TSUQlM2FBTk9OJTNhc2FwZGIxX05LUF8wMCUzYXNmYm9mSjlqRWVSYkdkeWpBRFZjRVVVMW9rS2RJVVZaQmZmVmc0cjYtQVRU%29/bc/gui/sap/its/zeviva (found [here](https://www.nordkurier.de/sap%28cz1TSUQlM2FBTk9OJTNhc2FwZGIxX05LUF8wMCUzYXNmYm9RVlNudUY1WXEybTlBUFRmYURIUE9VS2RJWXhaZi1ldjlUX0gtQVRU%29/bc/gui/sap/its/zeviva)) causes some kind of redirection-to-self issue

**Comment by J0WI** [comment]
@numismatika see also:
partnersuche.nordkurier.de
abo.nordkurier.de
magazine.nordkurier.de
test08.nordkurier.de

**Comment by numismatika** [comment]
@J0WI , added them

**Comment by J0WI** [comment]
@numismatika what do you think about the mixed content issues?

**Comment by numismatika** [comment]
@J0WI most of the warnings are about passive mixed content like pictures which for me is acceptable until firefox fixes those false positives.
Regarding the active mixed content that is blocked google fonts shouldn't break the page.
Also blocked for being active mixed content so far is the brightcove media player, but i haven't found a page yet where they use sound or video so i can't yet say if it is a deal breaker or not.

**Comment by J0WI** [comment]
@numismatika I was referring to https://github.com/EFForg/https-everywhere/pull/4289#issuecomment-195464559 where you fond an example of blocked css and also a server error.

**Comment by J0WI** [comment]
@numismatika it would be great if we could finish this one :)

**Comment by numismatika** [comment]
@J0WI they are quite stubborn at ignoring mails. I'll have to try exceptions.

**Comment by jeremyn** [comment]
@numismatika Do you want me to review this?

**Comment by numismatika** [comment]
@jeremyn go for the others for now, they have more impact.

**Comment by jeremyn** [comment]
@numismatika We don't necessarily go in order by impact. The question is whether you personally have the time and interest to respond to a review. This looks like a pretty simple ruleset so it wouldn't take much time on my part to review it.

**Pull request closed without merging**
