### PR TITLE
[Openstreetmap.fr] New ruleset

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by J0WI** [comment]
You may add a hint to the main OSM ruleset.

There are some more domains:
trac.openstreetmap.fr
listes.openstreetmap.fr
forum.openstreetmap.fr
adherents.openstreetmap.fr
export.openstreetmap.fr
bano.openstreetmap.fr
cadastre.openstreetmap.fr
osm13.openstreetmap.fr
suivi.openstreetmap.fr
munin.openstreetmap.fr
nomino.openstreetmap.fr


404/Wrong content:
analyser.openstreetmap.fr
garmin.openstreetmap.fr
download.openstreetmap.fr
osmose.openstreetmap.fr
polygons.openstreetmap.fr
live.openstreetmap.fr
comcommaker.openstreetmap.fr

Mismatch:
tms.cadastre.openstreetmap.fr

Refused:
taginfo.openstreetmap.fr

**Comment by rugk** [comment]
😮 Okay, I'll do. Did not checked it that carefully...

**Comment by rugk** [comment]
Why does not the unit tests run?

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
