### PR TITLE
Delete Baidu.com-problematic.xml

### PR DESCRIPTION
**Pull request by renyouguo**
pan.baidu.com & yun.baidu.com support https well now.

### CODE REVIEW

**Comment by renyouguo** [comment]
However,there is another bug:

Break in firefox，ok in chrome · Issue #4516 · EFForg/https-everywhere
https://github.com/EFForg/https-everywhere/issues/4516

**Comment by J0WI** [comment]
See comments in #4584, this needs to be merged in a single PR.

**Comment by renyouguo** [comment]
@J0WI You can merge this first,then #4584 will be ok.

**Comment by J0WI** [comment]
That's a bad workflow, but I'll make an exception.
Please use a single commit when just transferring a host to another file next time.

**Pull request merged**
