### PR TITLE
Update MIUI.com.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by ivysrono** [comment]
Where?

**Comment by J0WI** [comment]
On all three targets that have been added.

**Comment by ivysrono** [comment]
I have test https://api.bbs.miui.com/ and https://www.miui.com/ by IE11, both OK.

**Comment by J0WI** [comment]
```
Blocked loading mixed active content "http://static.bbs.miui.com/static/index7/js/jquery.mousewheel.js"
Blocked loading mixed active content "http://static.bbs.miui.com/static/index7/styles/index.css"
Blocked loading mixed active content "http://static.bbs.miui.com/static/index7/js/jquery.1.7.1.min.js"
Blocked loading mixed active content "http://static.bbs.miui.com/static/index7/js/jquery.mousewheel.js"
Blocked loading mixed active content "http://static.bbs.miui.com/static/index7/js/common.js"
```

**Pull request closed without merging**
