### PR TITLE
[County of Santa Clara, California] New partial ruleset

### PR DESCRIPTION
**Pull request by galenide**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset! Some issues:

* I understand why you grouped sccassessor and sccgov together but please split them into two files. Like  with some other government ruleset groups, you can list the various SCC rulesets in the sccgov ruleset, and refer to the sccgov ruleset in the sccassessor ruleset.
* Split the securecookie tags to simplify the regexes in accordance with the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md).
* It looks like the SCC government has a lot of inconsistently named other sites that you didn't mention that redirect to sccgov, like http://www.alertscc.com , http://www.cepascc.org , http://www.sccsheriff.org , http://www.sccemsagency.org , http://www.sccvote.org , http://www.parkhere.org . Is that why you marked this ruleset `(partial)`?

**Comment by galenide** [comment]
@jeremyn The Santa Clara County Assessor rules have been moved into a separate ruleset. In addition, certain additional mentioned sites such as http://www.alertscc.com/ have had redirects added. (It appears that the additional sites (such as http://www.cepascc.org/) do not support HTTPS, but it should be useful if the ruleset can redirect these sites to the HTTPS pages that the sites would normally redirect to.)

**Comment by jeremyn** [comment]
Thanks. Please:


`County-of-Santa-Clara-California.xml`:

Add `target`:
- [ ] https://archives.sccgov.org
- [ ] https://dvc.sccgov.org
- [ ] https://frontcounter.sccgov.org
- [ ] https://hhslink.sccgov.org
- [ ] https://iveserver.sccgov.org
- [ ] https://owp.sccgov.org
- [ ] https://volunteer.sccgov.org
- [ ] https://webmail.sccgov.org
- [ ] https://weights.sccgov.org

Also:
- [ ] Remote the [special `rule` for `sccgov.org`](https://github.com/galenide/https-everywhere/blob/2a8d10af2afe0ddb5e192e3bb878cec54e132abc/src/chrome/content/rules/County-of-Santa-Clara-California.xml#L55-L56), because https://sccgov.org works fine without it.
- [ ] Sort everything as shown below at [1]
- [ ] Change `securecookie` `host` to `^((eservices|frontcounter|hhslink|iveserver|myhealthonline|payments|scvhhsauth|scvhhsrap|services|sts|volunteer|www)\.)?sccgov\.org$` . Please double check this one carefully for me. Note that all of the new targets aren't included, because the ones that aren't seem to just redirect to another subdomain that is included.
- [ ] Change ruleset name to `Sccgov.org`
- [ ] Related, change filename to `Sccgov.org.xml` (don't forget to change the name in the top comment in the other ruleset)

`County-Assessor-County-of-Santa-Clara-California.xml`:
- [ ] Add `rule` redirecting `rp.sccassessor.org` to `www.sccassessor.org`
- [ ] Note `rp.sccassessor.org` as `Invalid certificate` in the top comment
- [ ] Use a general `.+`/`.+` `securecookie`
- [ ] Sort everything as shown below at [1]
- [ ] Change the ruleset `name` to `sccassessor.org`, because `County Assessor, County of Santa Clara, California` is too long
- [ ] Related, change the filename to `Sccassessor.org.xml` (don't forget to change the name in the top comment in the other ruleset)

[1] Your sorting was mostly what we prefer except we like to move `www` to the top of its group, beneath `^` but above everything else. See:
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```

Also, is squash and merge okay like we discussed before?

**Comment by jeremyn** [comment]
I've updated the checklist regarding https://iveserver.sccgov.org , which should fix the failing test. I'm sorry about that.

**Comment by galenide** [comment]
@jeremyn The situation where a ruleset fails testing because of one or more domains having incomplete certificate chains is something that I have come across before. Of note, the page at https://services.sccgov.org/rdalivetraffic/ appears to have a mixed content issue wherein the page has mixed active content. At the same time, trying to access the page via HTTP gives an error indicating that the connection to the server was reset and a [Google search](https://www.google.com/#q=site:services.sccgov.org%2Frdalivetraffic) gives an HTTPS link in the results.

For this pull request, it should be OK to do a squash and merge.

**Comment by jeremyn** [comment]
Travis catches incomplete certificate chains, but when I review I usually don't use Travis to check my feedback and it's too tedious to check new domains for that problem manually.

I can confirm your results for https://services.sccgov.org/rdalivetraffic/ but as you've noted, the page fails entirely with HTTP. At least we're not making the problem worse.

Thanks for making the updates. Merged.

**Pull request merged**
