### PR TITLE
iis.net and asp.net

### PR DESCRIPTION
**Pull request by galeksandrp**
- Add
	- forums.iis.net
	- blogs.iis.net
	- www.asp.net
	- asp.net
	- get.asp.net
	- docs.asp.net
	- hosting.asp.net
	- weblogs.asp.net
	- forums.asp.net
	- live.asp.net
	- samples.asp.net
	- quickstarts.asp.net
	- ajax.asp.net
- Remove
	- learn.iis.net

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also add a comment for broken php.iis.net?

**Comment by J0WI** [comment]
I just found:
samples.asp.net
quickstarts.asp.net
ajax.asp.net

Just ping me when this is done, that I can merge it as soon as it's ready.

**Comment by galeksandrp** [comment]
@J0WI added.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
