### PR TITLE
Additional domains for mBank

### PR DESCRIPTION
**Pull request by MilanKral**

### CODE REVIEW

**Comment by J0WI** [comment]
Could you also add the subdomains of `mbank.cz` and `mbank.sk`?

**Comment by MilanKral** [comment]
please suggest the additional subdomains for mbank.sk, mbank.cz

**Comment by J0WI** [comment]
Please have a look at our [docs](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md). We describe some handy tools for finding subdomains there.

**Comment by MilanKral** [comment]
The link
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
can't be opened.

**Comment by J0WI** [comment]
Yep, they are now living here:
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md

**Comment by J0WI** [comment]
Please list non-working comments sorted by their issue in a  comment block on the top.

**Pull request merged**
