### PR TITLE
Exclude non-default ports.

### PR DESCRIPTION
**Pull request by dbaxa**
Signed-off-by: David Black <dblack@atlassian.com>

### CODE REVIEW

**Comment by dbaxa** [comment]
cc @Hainish

**Comment by J0WI** [comment]
I don't think that removing the trailing slash is a good practice, @fuglede?

Note that your commits are not signed as [expected](https://help.github.com/articles/signing-commits-using-gpg/).

**Comment by dbaxa** [comment]
@J0WI do commits need to be signed now?

**Comment by J0WI** [comment]
No no, I's just a bit irritating because of the "Signed-off-by" part in the commit message.

**Comment by fuglede** [comment]
@J0WI: I don't have any very strong opinions on the matter (but I don't quite see why it was removed here).  But yeah, now that particular exclusion excludes any connection to

     http://go.atlassian.com.some.unrelated.subdomain.atlassian.com

even if that is probably not intended. In any case, exclusions only come into effect for a ruleset if a target host matches.

**Comment by dbaxa** [comment]
@fuglede it was removed because we want internal sites that run on ports other than 80 to not be sent to https:// . I was considering updating the regex to accept any port followed by `/` but when I looked I didn't see other examples of doing that but I did see rules that seemed to not end with `/`.

**Comment by fuglede** [comment]
Thanks for the explanation @dbaxa; that certainly makes sense. Can you confirm that non-default ports were not excluded before? I'm wondering as I seem to remember that HTTPS-E did not work properly with non-default ports in the first place (so that excluding them should not actually be necessary).

**Comment by dbaxa** [comment]
@fuglede I can confirm that with non-default ports in chrome HTTPS-E changes an access to `http://eg.internal.atlassian.com:81/` into `https://eg.internal.atlassian.com`.

**Comment by fuglede** [comment]
Thanks for elaborating. This looks good to me then; we could avoid the super edgy edge cases, but the added complexity to the pattern is probably not worth it.

**Comment by dbaxa** [comment]
@fuglede thank you for merging my pull request.

**Pull request merged**
