### PR TITLE
TheHouseOrgan.xyz rule

### PR DESCRIPTION
**Pull request by mroystonward**
TheHouseOrgan.xyz rule

### CODE REVIEW

**Comment by jeremyn** [comment]
It looks like you're the site owner for https://thehouseorgan.xyz . We recommend site owners add their site to the HSTS preload list if possible, instead of creating a ruleset for HTTPS Everywhere. See the FAQ at https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere . Is that something you can do here?

**Comment by mroystonward** [comment]
Hi, thanks,

Admittedly I didn't really know about HSTS before submitting the HTTPSE ruleset.

Unfortunately it doesn't seem to be a possibility for me. The site is hosted via gitlab pages (not self hosted gitlab) so I can at least add HTTPS certificate to a custom domain site - unlike github pages - but I can't redirect HTTPS as outlined in the EFF article.

Whilst I can't enforce HTTPS I was hoping to at least ensure visitors with HTTPSE plugin are redirected with this ruleset.

**Comment by jeremyn** [comment]
Sure, that's fine. In that case please:

- [ ] Mark https://www.thehouseorgan.xyz as `Time out` in a top comment. For example:
```xml
<!--
	Time out:
		www.thehouseorgan.xyz
  
--> 
<ruleset name="TheHouseOrgan.xyz">
...
</ruleset>
```
- [ ] Remove the extra tab at the beginning of the line in the middle of the ruleset [here](https://github.com/mroystonward/https-everywhere/blob/d2173bafa401e191136777d8310fb8bcafc2ade7/src/chrome/content/rules/TheHouseOrgan.xyz.xml#L4)

**Comment by mroystonward** [comment]
Waiting for build to pass but:
- [x] Mark https://www.thehouseorgan.xyz as Time out in a top comment
- [x] Remove the extra tab at the beginning of the line in the middle of the ruleset

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
