### PR TITLE
Update Github-Pages.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**
@jeremyn I found that the earlier issues were no longer present with this ruleset update, please double check!

### CODE REVIEW

**Comment by jeremyn** [comment]
I'm not sure what you mean or why you tagged me.

**Comment by koops76** [comment]
@jeremyn Well, because you're a ruleset maintainer maybe.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn Since you're the one who added (some of) those exceptions like this https://github.com/EFForg/https-everywhere/pull/6747

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@J0WI Added

**Pull request merged**
