### PR TITLE
Add code.fairphone.com to Fairphone ruleset

### PR DESCRIPTION
**Pull request by jannispinter**
I've added the code.fairphone.com page to the existing Fairphone ruleset.

### CODE REVIEW

**Comment by J0WI** [comment]
This ruleset needs to be rewritten to match our new style guide.

**Comment by J0WI** [comment]
@jannispinter are you still working on this?

**Comment by jannispinter** [comment]
Thanks for the reminder. I will look into this today, if I haven't submitted code till tomorrow, consider this as closed.

**Comment by jannispinter** [comment]
Will open up a new pull request

**Pull request closed without merging**
