### PR TITLE
Add Piwigo.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Unfortunately, this should probably have a `mixedcontent` `platform`. See for example https://historicalzg.piwigo.com/

**Comment by J0WI** [comment]
Aren't these just blocked trackers?

**Comment by Bisaloo** [comment]
In this case, yeah. However, I assumed that it meant users could add `http` resources on their pages. But maybe I'm wrong. Do you know more about this?

**Comment by J0WI** [comment]
Let me consider a few more examples.

**Comment by J0WI** [comment]
I checked now some more sites and only a minority of them have issues. None of them seemed to be critical, some of them are even enforcing HTTPS.

I think it's worth to enable this by default.

**Pull request merged**
