### PR TITLE
Delete Cashback.co.uk.xml

### PR DESCRIPTION
**Pull request by koops76**
#10843, redirects to HTTP.

### CODE REVIEW

**Comment by koops76** [comment]
@J0WI Request review.

**Comment by J0WI** [comment]
I prefer `default_off` for such issues.

**Comment by koops76** [comment]
@J0WI It redirects to HTTP.

**Comment by J0WI** [comment]
They'll hopefully fix this

**Comment by koops76** [comment]
@J0WI #12592.

**Pull request closed without merging**
