### PR TITLE
Create Baidu_CN.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
#4810 
@J0WI 
Very fast in China.

**Comment by J0WI** [comment]
This times out here as well. Maybe a firewall block us on https?

**Comment by renyouguo** [comment]
@J0WI I try to visit them by lantern proxy, very fast.

**Comment by renyouguo** [comment]
@J0WI Same strange issue at #5041

**Comment by renyouguo** [comment]
@J0WI I have test these errors again by Tor.
Ok by http and Unable to connect to https.
It might be blocked by firewall.

**Pull request merged**
