### PR TITLE
Update Appinn.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by J0WI** [comment]
Some of them are serving a mismatching cert, so they are broken anyway.
I was not able to test them in the Tor Browser, because the hosts timed out. It this what 'broken' means?

**Comment by ivysrono** [comment]
https://cloud.githubusercontent.com/assets/13086421/18807452/862a9c34-829b-11e6-8f88-d8d3e3b28cd9.png

**Comment by J0WI** [comment]
For `www.appinn.com` I have the same issue with normal browsers and curl:
```
$ curl -I https://www.appinn.com
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
```
But [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=www.appinn.com) seems to work.

**Comment by ivysrono** [comment]
It is very strange. Ok in my normal browsers and pass the travis check, but broken in Tor browser.

**Comment by J0WI** [comment]
@fuglede @jeremyn do you have the same issues with this host?

**Comment by jeremyn** [comment]
I'm getting what @ivysrono is getting: works in Firefox and Chrome, mismatch in Tor. It looks like totally different certificates: different common name, different issuer, different validity dates. Very strange.

**Comment by ivysrono** [comment]
I have found that we need to merge this PR , the comment is broken now.

**Comment by Hainish** [comment]
With `curl` and the normal browsers I'm able to access the site. With Tor Browser, I get the following error:

```
www.appinn.com uses an invalid security certificate.

The certificate is only valid for the following names: rsc.cdn77.org, www.secure.nsw.gov.au, www.cdn77.com, info.gossipslots.eu, cdn.medio.com, static.netverify.com, static.popads.net, c1.popads.net, cdn77.clickfun.com, content.thunderkick.com, cdn.xsolla.com, cdns.kinguin.net, cdn.ometria.com, cdn77.clickfuncasino.com, assets.victorinox.com, cache.graphicslib.viator.com, cache.vtrcdn.com, m.vtrcdn.com, partner.vtrcdn.com, i.gocollette.com, cdn.ctnsnet.com, videos.kinkylove.com, images.kinkylove.com, cdn3.merchenta.com, cdn.sscontent.com, cnt.booming.de, cdn.exactag.com, cdn.garantibil.se, cloud.majestic.co.uk, cdn.eprofessional.de, cdn.webstaurantstore.com, cdn.darkstarrisen.com, static-vid.ibotta.com, cdn.contentdn.net, cdn.nailsuperstore.com, info.drakecasino.eu, media.lingeriestyling.com, info.gtbets.eu, cdn.levenhuk.com, cdn.axonify.com, cdn.propellant.dk, static.scania.com, cdn.majestic.co.uk, cdn.professionalthemes.nyc, s.ato.mx, cdn.sales-sandiegohills.com, download.poikosoft.com, videos.universidadedoingles.com.br, cdn.as43289.net, cdn.unlimitedgamestore.com, cdn.loginvsi.com, cdn.sso.bdswiss.com, a.tpb.lc, cdn.ugsconsultoria.es, static.bandisoft.com, static.bandicam.com, download.ifortuna.cz, alt.cdn.scarabresearch.com, a.desu.sh, download.g5e.com, *.rsc.cdn77.org, *.cdn77-ssl.net, *.c.cdn77.org, s1.abocdn.com, i1.abocdn.com, static.myevansville.net, resources.gocollette.com, download.efortuna.pl, download.ifortuna.sk, static.btnwrkscnd.com, cdn.fashiola.de, cdn.casarenodirect.com, p.redlights.de, p.redlights.nl, p.quartier-rouge.be, images.rigbyandpellershop.com, cdn.justuno.com, cdn.assets.newmarketholidays.co.uk

Error code: SSL_ERROR_BAD_CERT_DOMAIN```

**Comment by Hainish** [comment]
Wow, this is really interesting.  This seems to be differential SNI responses specifically for Tor IPs.  You can test this by doing the following:

1. In Tor Browser, go to https://www.appinn.com/

You'll see the error.  Now,

2. Navigate to `about:config` within Tor Browser, click through the warning.
3. Search for `network.proxy.socks` and set it to a blank string.
4. Search for `network.proxy.socks_port` and set it to `0`.
5. Search for `network.proxy.socks_remote_dns` and set it to `false`.

This disables using the Tor proxy within Tor Browser.  Now,

6. Refresh https://www.appinn.com/ - the page loads!

This points to differential treatment for Tor users on the server side.

**Comment by Hainish** [comment]
Easier way to verify:

```
(.venv)user@personal:~$ curl -I https://www.appinn.com/
HTTP/1.1 200 OK
Server: nginx/1.9.12
Date: Tue, 18 Oct 2016 18:33:57 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=6l7i2efn6qgnn5j0ihp6pmu3b6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: pubilc
Pragma: cache
Set-Cookie: multi-device-switcher=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Link: <http://www.appinn.com/wp-json/>; rel="https://api.w.org/"

(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
```

**Comment by Hainish** [comment]
Thinking about it some more: this may not be based on if it's a Tor IP or not, but based on the location of the exit node.

**Comment by Hainish** [comment]
Seems that we get an invalid SNI for the majority of exit nodes.

```shell
(.venv)user@personal:~$ torsocks curl ifconfig.io
77.247.181.162
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
(.venv)user@personal:~$ sudo kill -HUP `pidof tor`
(.venv)user@personal:~$ torsocks curl ifconfig.io
46.233.0.70
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
(.venv)user@personal:~$ sudo kill -HUP `pidof tor`
(.venv)user@personal:~$ torsocks curl ifconfig.io
46.165.230.5
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
HTTP/1.1 200 OK
Server: nginx/1.9.12
Date: Tue, 18 Oct 2016 19:10:46 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=p48ge2ssvflvlnuduloheu1i45; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: pubilc
Pragma: cache
Set-Cookie: multi-device-switcher=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Link: <http://www.appinn.com/wp-json/>; rel="https://api.w.org/"

(.venv)user@personal:~$ sudo kill -HUP `pidof tor`
(.venv)user@personal:~$ torsocks curl ifconfig.io
171.25.193.20
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
(.venv)user@personal:~$ sudo kill -HUP `pidof tor`
(.venv)user@personal:~$ torsocks curl ifconfig.io
171.25.193.131
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
(.venv)user@personal:~$ sudo kill -HUP `pidof tor`
(.venv)user@personal:~$ torsocks curl ifconfig.io
155.4.214.218
(.venv)user@personal:~$ torsocks curl -I https://www.appinn.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.appinn.com'
```

I've used a VPN with geographically diverse endpoints, and none of these result in an invalid SNI response.  This seems to indicate that Tor specifically is getting differential treatment.

**Comment by Hainish** [comment]
@ivysrono with `www.appinn.com` I can see why you would remove it to make the site accessible for Tor users.

For the other targets with Tor, I see them timing out, which happens for http as well.  
Without Tor, these targets seem to work properly.
So why remove them?

**Comment by Hainish** [comment]
@ivysrono I see you've addressed the `faxian` subdomain, let me know when you've addressed the others.

**Comment by ivysrono** [comment]
I have moved the others to MCB tag.

**Comment by Hainish** [comment]
Thanks!

**Pull request merged**
