### PR TITLE
Re-activate, Rename and Update WebType.com.xml

### PR DESCRIPTION
**Pull request by cschanaj**
#9906

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Different HTTP/HTTPS content`:
- [ ] https://status.webtype.com
 
Mark as `Invalid certificate`:
- [ ] https://tickandtock.webtype.com
 
Mark as `Mixed content`
- [ ] https://blog.webtype.com
 
Mark as `No working URL known`:
- [ ] https://wcloud.webtype.com
 
Remove these, they are probably some kind of mistake:
- [ ] https://pls.webtype.compls.webtype.com
- [ ] https://cloud.webtype.comcloud.webtype.com
 
Add `target`:
- [ ] https://www.webtype.com
- [ ] https://demo.webtype.com
- [ ] https://gallery.webtype.com (and remove from `Status code mismatch`)

Also:
- [ ] Rename `SSL peer certificate was not OK` to `Invalid certificate`

**Comment by cschanaj** [comment]
I just noticed that `*.webtype.com` has a wildcard DNS record, i.e. https://anything.webtype.com or https://https-everywhere-10307.webtype.com works while giving 404 pages. I removed `wcloud` from the comment because it might not be used at all.

**Comment by jeremyn** [comment]
Thanks. I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/10307/commits/551ad41a729a317f0d90a001bce4c6423f504602.

**Comment by cschanaj** [comment]
done. thanks!

**Comment by jeremyn** [comment]
Thanks. You misspelled "triggered", though.

**Comment by cschanaj** [comment]
fixed. really sorry about this.

**Comment by jeremyn** [comment]
It's fine, don't worry about it. Merged.

**Comment by cschanaj** [comment]
Also fixed via https://github.com/cschanaj/xhttpse2/commit/5a02b929d085bd0a47149daa5e82437cec160dae for future ruleset. Thanks a lot!

**Comment by jeremyn** [comment]
Great, thanks.

**Pull request merged**
