### PR TITLE
created rule for dji.com

### PR DESCRIPTION
**Pull request by schmiedecker**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. This is a big site, and there's a lot more than what you included in https://github.com/EFForg/https-everywhere/pull/7358/commits/f29563c9bc80cf0a7771b59171ba54ab99d9bf9b. Please make the following changes. For the various "Mark as" items, I mean add a comment to the top like you see in [this example](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Juno.com.xml). Please let me know if you have any questions, I want to make sure you understand every change you're making.

Mark as `Incomplete certificate chain`:
- [ ] https://support.dji.com

Mark as `Invalid certificate`:
- [ ] https://dji.com
- [ ] https://link.dji.com
- [ ] https://live.dji.com
- [ ] https://static.dji.com
- [ ] https://bbs.djicdn.com
- [ ] https://bbs11.djicdn.com
- [ ] https://bbs22.djicdn.com
- [ ] https://event-live.djicdn.com
- [ ] https://events1.djicdn.com
- [ ] https://events2.djicdn.com
- [ ] https://events3.djicdn.com
- [ ] https://forum.djicdn.com
- [ ] https://www.dji.net
- [ ] https://bbs.dji.net
- [ ] https://dsevents.dji.net
- [ ] https://flysafe.dji.net
- [ ] https://m.dji.net
- [ ] https://show.dji.net
- [ ] https://store.dji.net
- [ ] https://videos.dji.net
- [ ] https://img.videos.dji.net

Mark as `Mixed content`:
- [ ] https://bbs1.djicdn.com

Mark as `Refused`:
- [ ] https://event.dji.com

Mark as `Secure connection failed`:
- [ ] https://x.dji.com

Mark as `Time out`:
- [ ] https://api.dji.com
- [ ] https://edm.dji.com
- [ ] https://forum.dev.dji.com
- [ ] https://live-usa.djicdn.com

Mark as `Unable to connect`:
- [ ] https://press.dji.com
- [ ] https://wiki.dji.com

Add `target`:
- [ ] https://account.dji.com
- [ ] https://accounts.dji.com
- [ ] https://active.dji.com
- [ ] https://aftersale.dji.com
- [ ] https://bbs.dji.com
- [ ] https://campaign.dji.com
- [ ] https://citizenship.dji.com
- [ ] https://click.dji.com
- [ ] https://coupon.dji.com
- [ ] https://dds.dji.com
- [ ] https://dev.dji.com
- [ ] https://edu.dji.com
- [ ] https://enterprise.dji.com
- [ ] https://events.dji.com
- [ ] https://flysafe.dji.com
- [ ] https://flysafe-admin.dji.com
- [ ] https://flysafe-api.dji.com
- [ ] https://forum.dji.com
- [ ] https://m.dji.com
- [ ] https://miy.dji.com
- [ ] https://mydjiflight.dji.com
- [ ] https://plus.dji.com
- [ ] https://repair.dji.com
- [ ] https://reserve.dji.com
- [ ] https://reserve-backend.dji.com
- [ ] https://responsibility.dji.com
- [ ] https://show.dji.com
- [ ] https://studiochina.dji.com
- [ ] https://translator.dji.com
- [ ] https://we.dji.com
- [ ] https://www-dji-china.dji.com
- [ ] https://www.djicdn.com
- [ ] https://asset1.djicdn.com
- [ ] https://asset2.djicdn.com
- [ ] https://asset3.djicdn.com
- [ ] https://asset4.djicdn.com
- [ ] https://asset5.djicdn.com
- [ ] https://dev1.djicdn.com
- [ ] https://devcn.djicdn.com
- [ ] https://devusa.djicdn.com
- [ ] https://dl.djicdn.com
- [ ] https://forum1.djicdn.com
- [ ] https://forum2.djicdn.com
- [ ] https://forum3.djicdn.com
- [ ] https://forum4.djicdn.com
- [ ] https://forum5.djicdn.com
- [ ] https://miy-cn.djicdn.com
- [ ] https://miy-us.djicdn.com
- [ ] https://plus.djicdn.com
- [ ] https://product1.djicdn.com
- [ ] https://u.djicdn.com
- [ ] https://videocaption.djicdn.com
- [ ] https://we1.djicdn.com
- [ ] https://we2.djicdn.com
- [ ] https://we3.djicdn.com
- [ ] https://we4.djicdn.com
- [ ] https://we5.djicdn.com
- [ ] https://www-optimized.djicdn.com
- [ ] https://www1.djicdn.com
- [ ] https://www2.djicdn.com
- [ ] https://www3.djicdn.com
- [ ] https://www4.djicdn.com
- [ ] https://www5.djicdn.com

Also:
- [ ] Change the filename `Dji.com.xml` to `DJI.xml`
- [ ] Change the ruleset `name` from `DJI.xml` to `DJI`
- [ ] Add the following to [`Qbox.me.xml`](https://github.com/EFForg/https-everywhere/blob/ec05004c0ed2fe3306913f638a59f3ae44116b1b/src/chrome/content/rules/Qbox.me.xml):
```xml
	<target host="dn-dji-videos.qbox.me" />
		<!-- Loaded by https://we.dji.com -->
		<test url="http://dn-dji-videos.qbox.me/cloud/0a2370e7e2e3e65aac7006322918eaaa/720.mp4" />
```
</details>
- [ ] In all cases where there is a list of domains, sort them in alphabetical order starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group. For example:

<details><summary>Click to expand sort order example</summary>
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```
</details>
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits from contributors, which means we combine commits and rewrite them in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by jeremyn** [comment]
@schmiedecker There's been no progress on this since my last comment. If for any reason you don't want to, or can't, make the requested changes yourself, please feel free to select the "Allow edits from maintainers" option and I'll make the changes myself.

**Comment by schmiedecker** [comment]
woah - sure thing, change your way. I'd be happy to allow edits from maintainers, and the checkmark is set.

Can you maybe point me to ressources / comment on how to 1) identify all those subdomains, 2) verify that they have the same content and 3) somewhat build the ruleset semi-automatically? I found the domain and some generic domains using random surfing, I'm sure there are better ways ...

**Comment by jeremyn** [comment]
Thanks.

For your questions, see https://github.com/EFForg/https-everywhere/pull/6681#issuecomment-247343140 , https://github.com/EFForg/https-everywhere/issues/6912 , and https://github.com/EFForg/https-everywhere/issues/7277 . Unfortunately some manual review is still needed.

**Comment by jeremyn** [comment]
@fuglede @Hainish @J0WI I've made my own changes to this pull request, so could one of you please review this? Also, because there are multiple contributors, please don't squash-and-merge.

**Comment by jeremyn** [comment]
Pinging @gloomy-ghost for the previous comment too.

**Comment by Hainish** [comment]
Checking on this now

**Comment by Hainish** [comment]
lgtm

**Comment by Hainish** [comment]
superseded by https://github.com/EFForg/https-everywhere/pull/8217

**Pull request closed without merging**
