### PR TITLE
Update Criteo.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by renyouguo** [comment]
@jeremyn

**Comment by renyouguo** [comment]
@jeremyn Would you please to review this?

**Comment by jeremyn** [comment]
Mark as `Invalid cert`:
- [ ] https://images.criteo.net (and remove from `Time out`)
- [ ] https://peering.criteo.net (and remove from `404`)

Delete these because they don't exist in DNS:
- [ ] https://criteo.net (and remove from `502` and `Time out`)
- [ ] https://www.criteo.net (and remove from `502` and `Time out`)
- [ ] https://images.fr.criteo.net (and remove from `Invalid cert`)

Also:
- [ ] Remove the unneeded `<!-- com -->` and `<!-- net -->` comments
- [ ] Remove the unneeded `static.criteo.net` test [here](https://github.com/renyouguo/https-everywhere/blob/e2031c5b5a50a35aad41a7809c547baa5e59cc8c/src/chrome/content/rules/Criteo.xml#L45)
- [ ] Change the `securecookie `from `.`/`.` to `.+`/`.+`.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
