### PR TITLE
Update jobs.cam.ac.uk and add talks.cam.ac.uk

### PR DESCRIPTION
**Pull request by sampablokuper**

### CODE REVIEW

**Comment by sampablokuper** [comment]
Note: the CI fails, but this is due to existing rules. It is not due to my commits above.

**Comment by jeremyn** [comment]
@sampablokuper Are you still interested in working on this?

**Comment by sampablokuper** [comment]
@jeremyn , yes in principle, but I'm afraid I can't spare time at the moment. Anyone interested should feel free to work on it.

**Comment by sampablokuper** [comment]
Both of the hosts in this PR have been addressed in the meantime.

**Pull request closed without merging**
