### PR TITLE
New ruleset for Board Game Arena.

### PR DESCRIPTION
**Pull request by mavit**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. Before we look at this in more detail, please note that we discourage wildcard targets. Instead, list each subdomain as a target. See [the style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) for that and other information.

**Comment by jeremyn** [comment]
Thanks. Please do the following. For the first three groups, add them to a comment at the top like you see [here](https://github.com/jeremyn/https-everywhere/blob/245f2f8812d56a7c16d4982bf59b97252cfac0b1/src/chrome/content/rules/Juno.com.xml).  

Mark as `Mismatch`:
- [ ] https://boardgamearena.net
- [ ] https://www.boardgamearena.net

Mark as `Refused`:
- [ ] https://comet.boardgamearena.net

Mark as `Timeout`. You can list them as I've given below, you don't need to name them individually:
- [ ] `(.+)?doc.boardgamearena.com` , example: `en.doc.boardgamearena.com`
- [ ] `(.+)?studio.boardgamearena.com` , example: `en.studio.boardgamearena.com`

Add `target`, list each target individually:
- [ ] `https://(.+)?3.boardgamearena.com`
- [ ] `https://(.+)?4.boardgamearena.com`
- [ ] https://c.boardgamearena.net

Also:
- [ ] Sort the subdomains. They should be grouped alphabetically starting at the top level domain at the right and reading left, with `^` and `www` moved to the top of their group. For example:
```
example.com
www.example.com
a.example.com
www.a.example.com
b.a.example.com
b.example.com
example.net
www.example.net
a.example.net
```
- [ ] Remove the two "where the target came from" comments
- [ ] Move `securecookie` between the `target`s and the `rule`

**Comment by mavit** [comment]
This website has recently started doing its own HTTP -> HTTPS redirections.  I'll hold off for now to see whether they enable HSTS soon.

**Comment by jeremyn** [comment]
I assume you mean the HSTS preload list, such as we're discussing in #7126 . Even if they do add all of their domains to the preload list, it will take some time for them to propagate far enough for us to consider them invalid HTTPS Everywhere targets.

I don't want to keep this pull request open indefinitely. The changes I asked for should be easy to do. Can you just do them, or else, can you enable "edits from maintainers" on this pull request and let me do them?

**Comment by mavit** [comment]
I have made the suggested changes.

Are these additional guidelines documented anywhere?  I don't see them at https://www.eff.org/https-everywhere/rulesets nor https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md.  I must admit that I feel like I'm trying to hit a moving target.

**Comment by jeremyn** [comment]
The tests are failing because [these `target`s](https://github.com/mavit/https-everywhere/blob/41d63fd1a131546f0561956297e2816715cd4624/src/chrome/content/rules/Board-Game-Arena.xml#L17-L18) are invalid, specifically you can't put regexes in them like that. You need to list the targets out, which is what I meant by "list each target individually". On reread though this even confused me, so I've added some examples to the checklist that I hope make it more clear.

I agree the documentation can be improved. We're discussing a new [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/pull/7255), please feel free to add any comments you like to the linked pull request. I also understand your worry about a moving target. What's in the checklist should be it, unless there is some major new problem.

Also, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) pull requests, which means that we combine and rewrite your commits in your name. Are you okay with that for this and any other pull requests you submit to us?

**Comment by mavit** [comment]
Squashed commits are fine by me.

**Comment by jeremyn** [comment]
Please remove the `https://` from the URLs in the top comment so that they have the same format that you see [here](https://github.com/EFForg/https-everywhere/blob/03e4d70af7cdaee89acc803f6d65c46ab2d0d103/src/chrome/content/rules/Juno.com.xml).

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
