### PR TITLE
Release 5.1.4

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by funkydude** [comment]
Would be nice to get a few more rule updates thrown into 5.1.4

**Comment by J0WI** [comment]
I think that was done in 5.1.3. This version just fixes some regressions.

**Comment by Hainish** [comment]
ping @jsha

**Comment by Hainish** [comment]
or @cooperq

**Comment by cooperq** [comment]
lgtm I think it's generally okay to just merge this sort of stuff.

**Pull request merged**
