### PR TITLE
Adding a simple rule for antiwar.com

### PR DESCRIPTION
**Pull request by jgillula**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Change the [top comment](https://github.com/jgillula/https-everywhere/blob/6c5fb13bf0b131b8759a866a2350acc4d4c4a40b/src/chrome/content/rules/Antiwar.com.xml#L1-L9) to this:
```xml
<!--
	Refused:
		- news.antiwar.com
		- original.antiwar.com

-->
```
- [ ] We like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) pull requests, which means we combine and rewrite pull requests in your name. Is that all right with you for this and any other pull requests you submit to us?

**Comment by jgillula** [comment]
Yep, squash-and-merge is A-OK by me!

**Comment by jeremyn** [comment]
Great! `antiwar.com` looks ready to merge.

Please remove the extra rulesets that you merged in for `fff.org` etc, so we just have `antiwar.com`. (In the future you may find it easier to submit pull requests using non-master branches.)

Also, I want to delete your commit messages when I squash-and-merge in this pull request to reduce clutter in the log. Is that all right with you?

**Comment by jgillula** [comment]
Yep, that's OK by me too!

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
