### PR TITLE
Create IgnitionDeck.xml

### PR DESCRIPTION
**Pull request by J0WI**
Merry Christmas.

### CODE REVIEW

**Comment by fuglede** [comment]
Maybe it's on purpose, but the ruleset name looks like a mistake?

**Comment by J0WI** [comment]
Uhm, Why?

**Comment by fuglede** [comment]
I didn't find any reference to 'cede' on the site.

**Comment by J0WI** [comment]
Oh, well...
But what is going on with the tests?

**Comment by fuglede** [comment]
Looks like the build was broken by 6b51a6a6277608c9353017908d58d6df75083b67/ 2a59b8b594d65f082db3c448f07ebea030be9012 and  04d27db7e6069f7b0afc2e5fe5f817ea8514397c.

**Pull request merged**
