### PR TITLE
Removed ruleset - T3Blog.com.xml

### PR DESCRIPTION
**Pull request by RemakingEden**
nxdomain

### CODE REVIEW

**Comment by RemakingEden** [comment]
Can anyone who originally saw this domain confirm if this is the same blog? https://t3-blog.com/ 

If it is i will change the ruleset rather than deleting.

**Comment by pipboy96** [comment]
domain still resolves but broken.

**Comment by pipboy96** [comment]
@RemakingEden 
They are not.
https://web.archive.org/web/20170720051946/https://www.t3blog.com/

**Comment by RemakingEden** [comment]
> domain still resolves but broken.

What do we do in this case? Do we usually remove or is there other things we check for? 

Thanks for clarifying the difference between all of these, it's good to know.

**Comment by pipboy96** [comment]
@RemakingEden We may delete.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
