### PR TITLE
Added dy.fi

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks for adding this rule. Sadly the certificate of this host expired recently.
When they fixed their cert, please also have a look at our [guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) about finding the subdomains of a host.

**Comment by theel0ja** [comment]
Now they have Let's Encrypt enabled, so they have now a valid cert.

**Comment by J0WI** [comment]
It seems that customers get their own subdomain, but without HTTPS support. Could you add a comment about this behavior?

**Comment by theel0ja** [comment]
@J0WI Yes, they will not have HTTPS, but the main domain does (login pages etc)

**Comment by J0WI** [comment]
@theel0ja
Sure. Please document this behavior with a comment in the ruleset for future maintenance.
The rule itself lgtm.

**Comment by theel0ja** [comment]
@J0WI Is `<!-- Customers get their own subdomain, but they don't have SSL -->` good?

**Comment by J0WI** [comment]
That's fine for me.

**Comment by theel0ja** [comment]
Fixed.

**Pull request merged**
