### PR TITLE
Expired Certificate

### PR DESCRIPTION
**Pull request by tamoor-cliqz**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
```
../src/chrome/content/rules/Grupfoni.xml:1: element ruleset: Relax-NG validity error : Expecting an element test, got nothing
../src/chrome/content/rules/Grupfoni.xml:1: element ruleset: Relax-NG validity error : Expecting an element target, got nothing
../src/chrome/content/rules/Grupfoni.xml:1: element ruleset: Relax-NG validity error : Invalid sequence in interleave
../src/chrome/content/rules/Grupfoni.xml:1: element ruleset: Relax-NG validity error : Element ruleset failed to validate content
../src/chrome/content/rules/Grupfoni.xml fails to validate
ERROR: Validation of rulesets against relaxng.xml failed.
```

Just use `default_off="Expired"`

**Comment by J0WI** [comment]
cc @luciancor

**Comment by luciancor** [comment]
@J0WI fixed

**Comment by J0WI** [comment]
Sorry, I just checked the site again. They renewed their cert, so we can keep this rule.

**Pull request closed without merging**
