### PR TITLE
add rule for mertailor

### PR DESCRIPTION
**Pull request by fabianfrz**
probably low priority

### CODE REVIEW

**Comment by fabianfrz** [comment]
This site needs HTTPS Everywhere support as it links all product pages to HTTP and works flawlessly with HTTPS.

**Comment by jeremyn** [comment]
@fabianfrz Are you still interested in working on this pull request?

**Comment by fabianfrz** [comment]
Isn't that one ready?

**Comment by jeremyn** [comment]
- [ ] Add this comment at the top:
```xml
<!--
	Mixed content blocking:
		magento2.themertailor.com

-->
```

**Comment by fabianfrz** [comment]
@jeremyn I cannot find the request to this domain which is blocked but I will add the domain. In mean time I found a monero mining script on the website which made me think that the page might be infected by malware. I have reported that to them in the hope that they'll remove it if this was not added by them. From my point of view the page is using an infected template.

Please be careful while testing.

**Comment by jeremyn** [comment]
Thanks for the warning about the mining script.

The ruleset looks ready to merge, but before I do, what did you mean by "cannot find the request to this domain"? Do you mean links to this domain from the main page? I see links to this domain if I do a Google search for `site:*.themertailor.com -site:www.themertailor.com`.

**Comment by jeremyn** [comment]
It doesn't need to be requested from `^` or `www` to make it a `target`. The subdomain just has to exist, and it does exist because as I said, you can find it through Google, and you can go to https://magento2.themertailor.com directly in a browser to verify the mixed content blocking.

**Comment by fabianfrz** [comment]
Or missing assets:
screenshot_20171210_174150

I have tried some but they are missing on HTTP as well.

**Comment by jeremyn** [comment]
I'm still not sure what you are arguing for or suggesting we do, exactly, sorry.

Are you okay for me to merge the pull request?

**Comment by fabianfrz** [comment]
yes

**Comment by jeremyn** [comment]
Okay thanks, merged.

**Pull request merged**
