### PR TITLE
Remove https-everywhere-checker message (3rd run)

### PR DESCRIPTION
**Pull request by cschanaj**
As per #11854, related #11274 and #11525 

~I would expect the result from `fetch-test` is chaotic ...~ Not really :smiley:

### CODE REVIEW

**Comment by cschanaj** [comment]
@J0WI can you help merging this?

**Comment by J0WI** [comment]
See https://github.com/EFForg/https-everywhere/pull/11525#issuecomment-319751290
Isn't this exactly the same?

**Comment by cschanaj** [comment]
I have only whitelisted the files failing `rules-test` this time. Many of them failed `rules-test` because of the lack of `test` url. Files failing `fetch-test` are excluded.

**Comment by J0WI** [comment]
Oh okay, I was just confused because of the weird diff. Thanks for filling #11942.

**Comment by cschanaj** [comment]
Just to note that I am going to rebase this after #11942 is merged, for a better diff 😄 Closing this for the time being.

**Pull request closed without merging**
