### PR TITLE
Rules for Iron Realms mud games

### PR DESCRIPTION
**Pull request by titeuf87**

### CODE REVIEW

**Comment by semenko** [comment]
Awesome! Could you please make these "simple" rules instead?
e.g.
```
        <rule from="^http:"
                to="https:" />
```
See: https://www.eff.org/https-everywhere/rulesets

Thanks!

**Comment by titeuf87** [comment]
Yes, I am going to change that. Though it will have to wait two weeks till
I get back home first.

On Thu, Dec 17, 2015 at 6:46 AM, Nick Semenkovich <notifications@github.com>
wrote:

> Awesome! Could you please make these "simple" rules instead?
> e.g.
>
>         <rule from="^http:"
>                 to="https:" />
>
> See: https://www.eff.org/https-everywhere/rulesets
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/https-everywhere/pull/3363#issuecomment-165470131>
> .
>



-- 
Simon Vermeersch

**Comment by titeuf87** [comment]
I've made those changes, let me know if anything else is stil needed!

**Comment by semenko** [comment]
awesome -- thanks!

**Pull request merged**
