### PR TITLE
[Telstra.com.au] New rulesets

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by youdly** [comment]
Rebase and update comment

**Comment by youdly** [comment]
Moved `Telstra.com.xml` to separate PR https://github.com/EFForg/https-everywhere/pull/14006

**Comment by youdly** [comment]
Rebased

**Comment by J0WI** [comment]
Looks like there is a deadlock in our tests ;)
Could you wait with the references unit one of the is merged?

**Comment by youdly** [comment]
https://github.com/EFForg/https-everywhere/pull/14006 has dangling reference error, while this has not. I've removed a subdomain and rebased. Let's see if this has the same error.

**Comment by youdly** [comment]
Removed non-functional hosts and rebased.

**Comment by youdly** [comment]
Failed `preloaded` test of travis.
`Unable to find image 'node:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/node/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fnode%3Apull&service=registry.docker.io: EOF`

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
