### PR TITLE
BR: add story subdomain

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by fuglede** [comment]
The server is currently misconfigured:

	$ curl -I https://story.br.de
	curl: (60) SSL certificate problem: unable to get local issuer certificate

If you don't see the issue, it is likely because your browser has cached the relevant intermediate certificates. Going to https://story.br.de on a fresh Firefox profile, for instance, will show you the problem.

**Comment by numismatika** [comment]
Yea big time, they are offering SSL3 which is vulnerable to poodle and use other bad things like a sha1 cert , i wrote them a mail telling that there are problems with their site,

**Comment by fuglede** [comment]
In any case, the hostname shouldn't be added as a target host to HTTPS Everywhere before that mistake is fixed.

**Comment by semenko** [comment]
WFM now as a 301, so merging:
```
~ $ curl -Iv https://story.br.de
* Rebuilt URL to: https://story.br.de/
*   Trying 194.187.162.152...
* Connected to story.br.de (194.187.162.152) port 443 (#0)
* found 187 certificates in /etc/ssl/certs/ca-certificates.crt
* found 758 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.br.de (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=DE,ST=Bayern,L=Muenchen,O=Bayerischer Rundfunk,CN=*.br.de
* 	 start date: Mon, 30 Nov 2015 00:00:00 GMT
* 	 expire date: Sun, 20 Nov 2016 23:59:59 GMT
* 	 issuer: C=US,O=GeoTrust Inc.,CN=GeoTrust SHA256 SSL CA
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> HEAD / HTTP/1.1
> Host: story.br.de
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer: 
> 
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
```

**Pull request merged**
