### PR TITLE
added Zattoo.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Fix misspelling [here](https://github.com/J0WI/https-everywhere/blob/91266ad8e84ac73db996ccb81a5fa7490a7503d4/src/chrome/content/rules/Zattoo.com.xml#L8)
- [ ] Mark as `400 bad request`: https://download.zattoo.com

**Comment by J0WI** [comment]
Can you give me a hint what I spelled wrong?

**Comment by jeremyn** [comment]
`embed-zatoo.com` should probably be `embed-zattoo.com`, although https://partner.zattoo.com doesn't redirect at all for me.

**Comment by J0WI** [comment]
Indeed, I fixed that.
`partner.zattoo.com/$` has no content, but existing paths are redirecting.

**Comment by jeremyn** [comment]
Okay I see that http://partner.zattoo.com/partner/searchCH/mini/SF2 redirects to http://http://embed-zattoo.com/sf-2/ .

**Pull request merged**
