### PR TITLE
Add Chocolate-Doom.org rule

### PR DESCRIPTION
**Pull request by chungy**

### CODE REVIEW

**Comment by julianladisch** [comment]
Thank you, please also add host chocolate-doom.org. See https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/PyWeek.org.xml how to rewrite non-www to www.

**Comment by chungy** [comment]
I've done so, thanks.

**Comment by J0WI** [comment]
Please document that https on non-www is refused.
Please also document the mismatching cert on master.chocolate-doom.org and new.chocolate-doom.org

**Comment by J0WI** [comment]
And please use tabs instead of space to follow our code style.

**Comment by chungy** [comment]
I've made those changes, thanks for the comments

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
