### PR TITLE
openweathermap.org

### PR DESCRIPTION
**Pull request by theel0ja**

### CODE REVIEW

**Comment by J0WI** [comment]
@pipboy96 Could you please give others the chance to review you changes? Usually we don't merge our own changes to follow the four eyes principle.
Thanks anyway for finishing this PR!

**Comment by pipboy96** [comment]
@J0WI Are changes needed to make the PR pass tests fine (the author is inactive it seems and often abandons their PRs)? BTW we probably need to make changing the PR automatically disqualify you from approving it if no merging changed PRs is allowed. I just don't know if it can be done by us or should be implemented by MS/GitHub staff.

**Comment by pipboy96** [comment]
I also don't quite like that it's enough to register another GitHub account to fool the system into allowing you to merge your own PR. I think if we want to stay true to this principle, we need to require two reviews, not one. Then preventing approval of one's own PR would be unnecessary, since it would still need two people with write access to merge.

**Comment by J0WI** [comment]
> BTW we probably need to make changing the PR automatically disqualify you from approving it if no merging changed PRs is allowed.

Unfortunately this is not possible. 

> I also don't quite like that it's enough to register another GitHub account to fool the system into allowing you to merge your own PR.

Why would you do that? I assume that the EFF does only give permissions to trustworthy persons. We should do our best to follow good practices and guidelines and not trying to abuse them.
We already had many discussions about our workflow (you be be interested in #7242). Fell free to propose enhancements :smiley:

> I think if we want to stay true to this principle, we need to require two reviews, not one. 

That's true, but then it would be even harder to get things merged.

**Comment by pipboy96** [comment]
I see that currently merging is only possible by some non-public list of people I am not in. I would like to know what exactly happened to the repo and who is allowed to merge now.

**Comment by pipboy96** [comment]
@J0WI 
>Why would you do that? I assume that the EFF does only give permissions to trustworthy persons. We should do our best to follow good practices and guidelines and not trying to abuse them.
>We already had many discussions about our workflow (you be be interested in #7242). Fell free to propose enhancements :smiley:

Of course I would not. However it's definitely possible that user account may be compromised.

**Comment by pipboy96** [comment]
I'm also concerned that at some point of time in past we merged broken code and did not notice that, and also that the only place for discussing this project is GitHub issues.

**Comment by pipboy96** [comment]
Also, I know this is unrelated, but at some point in the past there were plans of independent audit of HTTPS Everywhere's code and possibly rulesets. What happened with these plans?

**Comment by J0WI** [comment]
I suggest you try https://lists.eff.org/mailman/listinfo/https-everywhere :wink:

**Comment by pipboy96** [comment]
@J0WI Last post was November 2018.

**Comment by pipboy96** [comment]
@J0WI Found: https://lists.eff.org/pipermail/https-everywhere/2018-January/002763.html

**Pull request merged**
