### PR TITLE
Moving https-everywhere-checker to test/rules

### PR DESCRIPTION
**Pull request by TheNavigat**
Please don't merge this right away, I made this PR because I want to see how tolerant Travis CI would be before we can merge.

### CODE REVIEW

**Comment by TheNavigat** [comment]
I finally got it to work, however, the following PR has to be merged first, https://github.com/TheNavigat/https-everywhere-checker/pull/1, and then I should update the commit version in this PR for test/rules, and then it'll work.

**Comment by TheNavigat** [comment]
It's ready!

**Comment by semenko** [comment]
LGTM -- and 2dcf83b24eadbc7d29c3e5e89d48c9ea9d9e29b0 matches @jsha's repo. Merging.

**Comment by kaistian** [comment]
This PR breaks [fetch-test.sh](https://github.com/EFForg/https-everywhere/blob/master/fetch-test.sh) since it points to https-everywhere-checker

**Comment by TheNavigat** [comment]
Here. https://github.com/EFForg/https-everywhere/pull/2947. Sorry about that.

**Comment by kaistian** [comment]
Unfortunately this PR also breaks the test. In https-everywhere-checker the file [manual.checker.config](https://github.com/jsha/https-everywhere-checker/blob/2dcf83b24eadbc7d29c3e5e89d48c9ea9d9e29b0/manual.checker.config) contains
```
[certificates]
# Certificate trust anchors for checking chains in HTTPS connections
basedir = https-everywhere-checker/platform_certs
```

**Comment by TheNavigat** [comment]
I feel ashamed. You're right. I'm very sorry, I should've tested those more intensely.

Here's a PR that fixes that problem. https://github.com/jsha/https-everywhere-checker/pull/3

```fetch-test.sh``` should run correctly now, unless I missed something else.

**Comment by TheNavigat** [comment]
Would it annoy anyone if I cloned https-everywhere-checker and changed the submodule's feed to the cloned repo?

**Comment by TheNavigat** [comment]
Follow up PR, https://github.com/EFForg/https-everywhere/pull/3022

**Pull request merged**
