### PR TITLE
rm JustPaste.it.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded

[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=14427), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#5288), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n5855)

### CODE REVIEW

**Comment by jeremyn** [comment]
This looks fine except `justpaste.it` doesn't actually seem to be in the released versions yet, for example check `chrome://net-internals/#hsts` in Chrome.

**Comment by gloomy-ghost** [comment]
Update: It is in `Chrome 54.0.2840.59` and `mozilla-central`, but not `mozilla-release` yet

**Comment by gloomy-ghost** [comment]
Update: It is in https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#5297

**Comment by jeremyn** [comment]
`justpaste.it` still isn't preloaded in Firefox 49.0.2, at least it's not when I test it on my system. According to https://wiki.mozilla.org/RapidRelease/Calendar , Firefox 50 will be generally released on November 15th, so I suppose that's when we'll see this included.

**Comment by gloomy-ghost** [comment]
Firefox 50 is released, but I'm not sure how to test the preloading status in Firefox, can you have a look?

**Comment by jeremyn** [comment]
Checklist

- [ ] [Firefox ESR](https://hg.mozilla.org/releases/mozilla-esr45/file/f2792b829193/security/manager/ssl/nsSTSPreloadList.inc#l7219)
- [ ] [Firefox Stable](https://hg.mozilla.org/releases/mozilla-release/file/cc272f7d48d3/security/manager/ssl/nsSTSPreloadList.inc#l5297)
- [ ] [Chromium 53.0.2785.143](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json)
- [ ] [Tor 45.5.1esr-6.0-1](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.5.1esr-6.0-1#n7219)

**Comment by jeremyn** [comment]
This domain missing from the Chromium list is frustrating because I can check in chrome://net-internals/#hsts in that version of Chromium and see that 'justpaste.it' is included, but it's not in the list itself.

**Comment by gloomy-ghost** [comment]
Chrome 54 has been released for a while...

**Comment by jeremyn** [comment]
I'm using Ubuntu 16.04, and the current version of Chromium from the universe repository is 53.0.2785.143 (see http://packages.ubuntu.com/xenial/chromium-browser) . Since we should err on the side of caution when deleting preloaded rulesets, I think it's valid to require that it's preloaded in that version.

The weird thing is though that when I check in the actual browser, it's there. It's just not in the list that is supposed to match the browser.

**Comment by jeremyn** [comment]
I also followed the instructions in https://www.chromium.org/hsts , which led me to https://chromium.googlesource.com/chromium/src/+/12ae4ebf489873fc4aad9efc231b9151b330a938/net/http/transport_security_state_static.json for 53.0.2785.143, and `justpaste.it` isn't in that file either.

**Comment by jeremyn** [comment]
The current version of Chromium on Ubuntu 16.04 is now 55.0.2883.87, which contains `justpaste.it` in the preload file. I've updated the checklist and merged the pull request.

**Pull request merged**
