### PR TITLE
[VSHosting] Added ruleset

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by J0WI** [comment]
Sadly, it seems that every customer gets his own subdomain. This results in a bunch of subdomains, that doesn't work with https.

Could you document this behaviour?

**Comment by J0WI** [comment]
@Roman3349 are you still working on this?

**Comment by Roman3349** [comment]
@J0WI Added comments about non-functional subdomains.

**Comment by J0WI** [comment]
Great!

**Pull request merged**
