### PR TITLE
Add AniList.co

### PR DESCRIPTION
**Pull request by eduardoklosowski**

### CODE REVIEW

**Comment by J0WI** [comment]
Thanks!
Could you add a comment for the mismatch on nginx.anilist.co?

**Comment by eduardoklosowski** [comment]
I add this host in comment, and rewrite file like example in https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md.

But I don't know this failed in travis, in my pc ./test.sh and ./test/travis-ruleset-fetch.sh return success. Exists any error in my commit?

**Comment by J0WI** [comment]
See #4645

**Comment by eduardoklosowski** [comment]
I rebase my branch to master with ./test/travis-ruleset-fetch.sh commented in travis config

**Pull request merged**
