### PR TITLE
Add rule for bite.lt

### PR DESCRIPTION
**Pull request by Liudvikam**

### CODE REVIEW

**Comment by J0WI** [comment]
I found some more subdomains:
bicademy.bite.lt
cs.bite.lt

Mismatch:
ivr.bite.lt
sms.bite.lt

Refused:
soap.bite.lt
wap.bite.lt

Could you add them as well and comments for the non-working ones?

**Comment by Liudvikam** [comment]
Sure thing. By the way, could you let me know how you go about finding subdomains, just so I can put more of them in any future rulesets I create?

**Comment by J0WI** [comment]
This is described here: https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by Liudvikam** [comment]
Thanks!

**Pull request merged**
