### PR TITLE
[Maps.me] New ruleset, [My.com] Rewritten

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by J0WI** [comment]
Got 403 on fb.maps.me
The embedded Video on the main site is blocked.

It seems that every product/app/whatever have a subdomain on my.com. So you may consider to keep the wildcard and just adding test urls.

**Comment by rugk** [comment]
Oh okay. How do you always get all this subdomains?

**Comment by rugk** [comment]
> Got 403 on fb.maps.me

Yeah, but this seems to be okay. I think this is intended. (`fb` = `facebook`)

**Comment by rugk** [comment]
> The embedded Video on the main site is blocked.

Which video?

**Comment by J0WI** [comment]
> Yeah, but this seems to be okay. I think this is intended. (fb = facebook)

Yes, but it's an insecure redirect.

> Oh okay. How do you always get all this subdomains?

See https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

> Which video?

On the bottom of maps.me

**Comment by rugk** [comment]
> Yes, but it's an insecure redirect.

Okay, but the Facebook ruleset should catch it. And I also think Facebook is even preloaded.

> See https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

Ah thanks. Need to look how to do that with DuckDuckGo.

> On the bottom of maps.me

Ah it is not there. That's why I don't see it. :laughing: 

/cc @mapsme @deathbaba
Could you fix this HTTP URL of the YouTube video, whcih is embedded on Maps.me? YouTube supports and uses HTTPS by default.

**Comment by J0WI** [comment]
> Okay, but the Facebook ruleset should catch it.

Yes, but with plain http you could still hijack the redirect, that it points to something evil.

> Thanks. Need to look how to do that with DuckDuckGo.

Sadly DDG doesn't support wildcards on site parameters. I think I reported it somewhere long time ago.

**Comment by rugk** [comment]
> Yes, but with plain http you could still hijack the redirect, that it points to something evil.

That's why it is in the rule... wait. It is not there. Why did not you said this? :smile: 
I puzzling what your comment means here and then it is simple another missing subdomain. I though something with the redirect would be wrong...

**Comment by J0WI** [comment]
Sorry, your right. I lost the content of previous comments a bit. There is something wrong:
> Got 403 on fb.maps.me

So this should be commented or redirected directly to the target on Facebook.

**Comment by rugk** [comment]
> So this should be commented or redirected directly to the target on Facebook.

Why? Especially why deactivate ruleset?
And if the Facebook account URL changes this is not good either.

But of course I can make the change.

**Comment by deathbaba** [comment]
http redirect of fb.maps.me <http://fb.maps.me/> works correctly.

**Comment by rugk** [comment]
Okay, so no slash?

**Comment by rugk** [comment]
So...

**Comment by deathbaba** [comment]
?

**Comment by J0WI** [comment]
The slash in the from pattern is the important one, but LGTM anyway.

**Pull request merged**
