### PR TITLE
Add subdomains to vgtrk.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Add `target`:
- [ ] https://old.vgtrk.com (it just redirects to `tech`) 
- [ ] https://tech.vgtrk.com

Also:
- [ ] Sort the `Nonfunctional hosts` in the top comment
- [ ] https://mobile.vgtrk.com should be `certificate mismatch`, not `self-signed certificate`
- [ ] Add `test` for http://files.vgtrk.com/022.pdf

**Comment by J0WI** [comment]
done

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/8896/commits/6e9982fd603602dab6eafef4fbaaf0a1297e95d4.

`www.chorus.vgtrk.com` should be sorted immediately after `cable.vgtrk.com`.

I don't get a mismatch error for https://old.vgtrk.com , so we don't need a special rewrite `rule` for it.

Please move the `files` `test` directly after the `files` `target`, with an single indent.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
