### PR TITLE
[Radware.com] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
Followup of https://github.com/EFForg/https-everywhere/pull/3183

### CODE REVIEW

**Comment by fuglede** [comment]
More or less looks good to me. Only problem would appear to be that https://radware.com times out (so it should probably just be redirected to www.radware.com instead).

**Comment by rugk** [comment]
> Only problem would appear to be that https://radware.com times out (so it should probably just be redirected to www.radware.com instead) 

Would be possible, for sure.

However to fix that
> http://portals.radware.com/Not-Logged-In/Login/ triggers a redirect loop

I think it would be much more better if this is fixed by Radware itself. Especially as this is a login page and they are a company in the security area...
[I've notified them](https://twitter.com/rugkme/status/668881978306011137).

What's worse is that some of their servers used do not support HTTPS at all [according to SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=radware.com).

**Comment by rugk** [comment]
They seem to have fixed http://portals.radware.com/Not-Logged-In/Login/ and I now also added the redirection to www.

**Comment by fuglede** [comment]
Thanks for the update; you need to add trailing slashes to the <code>to</code> and <code>from</code> attributes in the rule (in order to not have the rule trigger on a different hypothetical host that happens to also being with <code>radware.com</code>).

**Comment by semenko** [comment]
@rugk I'd love to merge this -- would you please escape those special characters to fix the build error? Thanks! :+1:

**Comment by rugk** [comment]
> Missing caret (^) in 'from' attribute: it should be "^http:" and not "http:".

That's not true. There is a caret in both.

> Missing trailing slashes in 'from' or 'to' when specifying full hostnames

Also not true.

There is a validation error, but I still do not know why it fails here.

**Comment by fuglede** [comment]
It fails because of the backslashes in the <code>to</code>-attribute.

**Comment by rugk** [comment]
This syntax is quite confusing. You have to use RegExp (escaping) in the `from` part but *must not* use it in the `to`part...

**Comment by fuglede** [comment]
I don't disagree; it might be worth adding as one of the 'common reasons' for failure.

**Comment by semenko** [comment]
Yeah, it's pretty silly. We should probably rethink rulesets as we move forward.

I'd also like to make the "name" attribute of cookie rules optional (most are .* or .+)

**Comment by rugk** [comment]
Okay, so back to this ruleset: The tests seem to succeed.

**Pull request merged**
