### PR TITLE
Add website https://www.zakonyprolidi.cz/

### PR DESCRIPTION
**Pull request by jakubboucek**
In Czech republic is this website one of the best source for law documents. I mean its important to keep privacy.

### CODE REVIEW

**Comment by J0WI** [comment]
Sadly the cert doesn't match m.zakonyprolidi.cz
Could you add a comment for that?

**Comment by jakubboucek** [comment]
Yes, you right. The rule has not affected this subdomain of the website (or it is?). I will contact the owner to add it, thank you for notice.

**Comment by jakubboucek** [comment]
Hi, I have the answer from website owner: mobile website (m.zakonyprolidi.cz) is currently deprecated and will be shut down.

**Comment by J0WI** [comment]
Thanks for clarify!
Could you document this with a comment anyway for future maintenance?

**Comment by jakubboucek** [comment]
I'll try, I am using this website every day.

**Comment by J0WI** [comment]
@jakubboucek the host is still up. Would you like to put the comment, that I can merge your ruleset?

**Comment by jakubboucek** [comment]
Hi, as i say later, `m.` subdomain is deprecated and will be terminated. Because now is not more developed and already is outdated, i thinking you can merge it. I have this ruleset activated locally, i am using this website daily on https without problem.

**Comment by J0WI** [comment]
Yes, but you should add a comment for this in the ruleset, that nobody else will accidentally add in in future.

**Comment by J0WI** [comment]
@jakubboucek the mobile website is still up, could you reconsider adding it?

**Comment by jakubboucek** [comment]
Hi, I am now updated file. Now is added comment.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
