### PR TITLE
Externals 13.07.2015

### PR DESCRIPTION
**Pull request by numismatika**
This adds a couple of Subdomains to ad- and tracking networks as well as adds rules for new ones.

### CODE REVIEW

**Comment by jsha** [comment]
Considering this blocked on the redirect to HTTP. @numismatika, can you run the fetch test on this branch and make sure everything succeeds?

```
git diff master --name-only | xargs ./fetch-test.sh 
```

**Comment by jsha** [comment]
@numismatika: I saw your comments on IRC but I think you're not currently logged in. I'm not sure what's going wrong with the command I suggested. But the goal is to pass each XML file modified in this branch into fetch-test.sh. So you can also do it manually:

```
./fetch-test.sh file1 file2 etc
```

**Comment by mnordhoff** [comment]
At the moment, it ought to be:

    ./fetch-test.sh src/chrome/content/rules/Adility.xml src/chrome/content/rules/Adobetag.com.xml src/chrome/content/rules/Adrolays.xml src/chrome/content/rules/BoomAds.xml src/chrome/content/rules/Criteo.xml src/chrome/content/rules/Exponential.com.xml src/chrome/content/rules/I12.de.xml src/chrome/content/rules/IQ-Media-Marketing.xml src/chrome/content/rules/KrxD.net.xml src/chrome/content/rules/Moat.xml src/chrome/content/rules/Moat_ads.com.xml src/chrome/content/rules/Nugg.ad.xml src/chrome/content/rules/Nurago.xml src/chrome/content/rules/Outbrain.xml src/chrome/content/rules/RevSci.net.xml src/chrome/content/rules/SevenOneMedia.xml src/chrome/content/rules/Teads.tv.xml src/chrome/content/rules/Urbanartcloud.com.xml src/chrome/content/rules/Xplosion_interactive.xml

I got that with:

    git diff 8a48495^.. --name-only | xargs

Your diff command also included extraneous changes made in `master`, but that could be an artifact of my setup.

**Comment by mnordhoff** [comment]
Correction: `Moad_ads.xml` was deleted, so it should be left out.

    ./fetch-test.sh src/chrome/content/rules/Adility.xml src/chrome/content/rules/Adobetag.com.xml src/chrome/content/rules/Adrolays.xml src/chrome/content/rules/BoomAds.xml src/chrome/content/rules/Criteo.xml src/chrome/content/rules/Exponential.com.xml src/chrome/content/rules/I12.de.xml src/chrome/content/rules/IQ-Media-Marketing.xml src/chrome/content/rules/KrxD.net.xml src/chrome/content/rules/Moat.xml src/chrome/content/rules/Nugg.ad.xml src/chrome/content/rules/Nurago.xml src/chrome/content/rules/Outbrain.xml src/chrome/content/rules/RevSci.net.xml src/chrome/content/rules/SevenOneMedia.xml src/chrome/content/rules/Teads.tv.xml src/chrome/content/rules/Urbanartcloud.com.xml src/chrome/content/rules/Xplosion_interactive.xm

**Comment by numismatika** [comment]
i don't want to turn this into a python support topic, but pip install -r requirements ends up with some weird python issues, pip3 works but python3 can't execute the test scripts.
It will take some more significant effort to get this testing done. I'm sorry

**Comment by numismatika** [comment]
I removed Nugg.ad for now to avoid merge conflicts.
Of course gwp is still a valid target for a tls-rewrite.

**Comment by jsha** [comment]
I pulled this branch and ran fetch-test.sh, and got just one error:

```
ERROR src/chrome/content/rules/Criteo.xml: Fetch error: http://labs.criteo.com/ => https://labs.criteo.com/: (7, 'Failed to connect to labs.criteo.com port 443: Connection refused')
```

**Comment by numismatika** [comment]
@jsha  i removed the subdomain from the Criteo rule now.
The host doesn't resolve to an ip.

**Comment by numismatika** [comment]
@semenko Is it still small enough to be merged?

**Comment by numismatika** [comment]
So i rebased the stuff on top of the current master.
The merge conflict on revsci.net should be gone now

**Comment by numismatika** [comment]
rebased again to avoid merge conflict

**Comment by semenko** [comment]
Great, thanks!

**Pull request merged**
