### PR TITLE
[ebay.com.my] New ruleset

### PR DESCRIPTION
**Pull request by youdly**
https://github.com/EFForg/https-everywhere/issues/13603

### CODE REVIEW

**Comment by youdly** [comment]
`test/selenium/test_options.py::OptionsTest::test_show_counter FAILED` in chrome beta

**Comment by youdly** [comment]
Build timeout in Firefox

**Comment by J0WI** [comment]
There are some issues in the fetch test.

**Comment by youdly** [comment]
Removed problematic subdomains

**Pull request merged**
