### PR TITLE
[Coverity.com] Update ruleset

### PR DESCRIPTION
**Pull request by youdly**
Re-open previous PR https://github.com/EFForg/https-everywhere/pull/3231.
Ruleset previously disabled by https://github.com/EFForg/https-everywhere/commit/b69a6d7a7baa0ec7842e7a1375d39a29b9192df7 
Update subdomains and simplify ruleset.

### CODE REVIEW

**Comment by fuglede** [comment]
The site still supplies an incomplete chain:

    $ curl -I https://coverity.com
    curl: (60) SSL certificate problem: unable to get local issuer certificate

If it works for you, that might be because you have cached the intermediate certificate through some third party.

**Comment by youdly** [comment]
I didn't add the intermediate cert to `/etc/ssl/certs/ca-certificates.crt`, but I don't encounter any error running the `curl` command. Browsers also show no error. Might be relevant, https://github.com/EFForg/https-everywhere/issues/1862

**Comment by fuglede** [comment]
Sounds weird with the no <code>curl</code> error. If browsers let you through, that could be due to caching of the intermediate certificates. Certainly Firefox gives a warning here. OpenSSL also gets only an insufficient chain:

	$ openssl s_client -connect coverity.com:443 -showcerts
	CONNECTED(00000003)
	depth=0 C = US, ST = California, L = San Francisco, O = "Coverity, Inc.", CN = *.coverity.com
	verify error:num=20:unable to get local issuer certificate
	verify return:1
	depth=0 C = US, ST = California, L = San Francisco, O = "Coverity, Inc.", CN = *.coverity.com
	verify error:num=27:certificate not trusted
	verify return:1
	depth=0 C = US, ST = California, L = San Francisco, O = "Coverity, Inc.", CN = *.coverity.com
	verify error:num=21:unable to verify the first certificate
	verify return:1
	---
	Certificate chain
	 0 s:/C=US/ST=California/L=San Francisco/O=Coverity, Inc./CN=*.coverity.com
	   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certificates.godaddy.com/repository/CN=Go Daddy Secure Certification Authority/serialNumber=07969287
	-----BEGIN CERTIFICATE-----
	MIIFcjCCBFqgAwIBAgIId7m4dv69OWwwDQYJKoZIhvcNAQEFBQAwgcoxCzAJBgNV
	BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
	GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEzMDEGA1UECxMqaHR0cDovL2NlcnRp
	ZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5MTAwLgYDVQQDEydHbyBEYWRk
	eSBTZWN1cmUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxETAPBgNVBAUTCDA3OTY5
	Mjg3MB4XDTE1MDUwMTE5NDU0MFoXDTE2MDYwMzIxMzkxNVowbDELMAkGA1UEBhMC
	VVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28x
	FzAVBgNVBAoTDkNvdmVyaXR5LCBJbmMuMRcwFQYDVQQDDA4qLmNvdmVyaXR5LmNv
	bTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALEo+Dvt93ODdEb44WGW
	W+FIC+JSP/K9Dj4WvI8YjeOCaBg5Ktcjb++lFNnT8Kn9eDDxGUUHoOjGOBh/WW7r
	Zm/ZtnjOmVMyJMIqLUL4FWPu+c3/etWjJUDrqIbi9GfU5qAGKk1ZeAx1qtx35e+H
	bx0lJf9l+i6W/QyOuEhl0m/XAylfg9LjP9KGr9DiJEbIZydOrlJ1plF1YtUSTSKN
	qmO7Ef3iM6mdEF2jhSxmhiBrZhHN4PaU6ooHll9574dKPUj2pOP7/CGheHm6e7uS
	kLioLqnAEx5ShD5lkWlGBjWV78k7CTFy57DvxqzxYduRIf/F33I7LLcnnkvuavwW
	Ti8CAwEAAaOCAbcwggGzMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUH
	AwEGCCsGAQUFBwMCMA4GA1UdDwEB/wQEAwIFoDAzBgNVHR8ELDAqMCigJqAkhiJo
	dHRwOi8vY3JsLmdvZGFkZHkuY29tL2dkczItMTcuY3JsMFMGA1UdIARMMEowSAYL
	YIZIAYb9bQEHFwIwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5n
	b2RhZGR5LmNvbS9yZXBvc2l0b3J5LzCBgAYIKwYBBQUHAQEEdDByMCQGCCsGAQUF
	BzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wSgYIKwYBBQUHMAKGPmh0dHA6
	Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZF9pbnRlcm1l
	ZGlhdGUuY3J0MB8GA1UdIwQYMBaAFP2sYTKTbEXW4u6FX5q653aZaMznMCcGA1Ud
	EQQgMB6CDiouY292ZXJpdHkuY29tggxjb3Zlcml0eS5jb20wHQYDVR0OBBYEFPDE
	rCPamR0Q54cQiiyOhZdRgzIVMA0GCSqGSIb3DQEBBQUAA4IBAQCD14XbqwE2RYCN
	vYgNR++D2wcCAz2O+RVi8bIF1I5M2pDmvA3eV5EHD5EVwGt4i4AJ4s6/2xNa7Zwf
	1EltSA0OJ+yjmiEsis39FxwZZyEk14ccjqQAZXt9Y+KivCJCtFxGwTxGMeNqdbWM
	woUVeiiDmTuiNWNJqDveBwl2AUGWG5dFrJuw+fwpyIdvEiHk9Rdtf+SAZ6+7WyWk
	tMoGwm01oXnWFrWgmYigV0YTHmV6ujfx0KY35t2qPDqKuQH/pNgyzZV+pz1EfGp2
	bHWWJe2LC2OBi+3MtG+QR+Q+Mv4hta9fYu2IK42QghuAnEEU57+97yBkU/ypAbgy
	s09RW2M1
	-----END CERTIFICATE-----
	---
	Server certificate
	subject=/C=US/ST=California/L=San Francisco/O=Coverity, Inc./CN=*.coverity.com
	issuer=/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certificates.godaddy.com/repository/CN=Go Daddy Secure Certification Authority/serialNumber=07969287
	---
	No client certificate CA names sent
	---
	SSL handshake has read 2276 bytes and written 493 bytes
	---
	New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
	Server public key is 2048 bit
	Secure Renegotiation IS supported
	Compression: NONE
	Expansion: NONE
	SSL-Session:
	    Protocol  : TLSv1
	    Cipher    : DHE-RSA-AES256-SHA
	    Session-ID: B05C929F8AACA49D82A1BF27B38E635980A1272BC520905D106EBF4B03D8D3A0
	    Session-ID-ctx: 
	    Master-Key: CD960B137144CF33D71799AA98B700FF6DD68B148264823C3AC3E8FF557C4C83B4558FF5725BF8A303F9402C3388B723
	    Key-Arg   : None
	    PSK identity: None
	    PSK identity hint: None
	    SRP username: None
	    TLS session ticket:
	    0000 - 8a 1a 4f ff a0 47 27 60-ac 1b f7 7c 6c 92 ea 69   ..O..G'`...|l..i
	    0010 - 75 66 57 cf 31 4d 7e ff-3c d1 c2 99 94 77 0e 8e   ufW.1M~.<....w..
	    0020 - d6 94 7d b4 a5 48 80 c2-69 6b 95 ae a6 43 09 8a   ..}..H..ik...C..
	    0030 - bb 05 e4 16 28 e4 12 1e-2d a4 ac e0 05 b0 59 1b   ....(...-.....Y.
	    0040 - b2 be c4 92 0c 35 05 b8-14 b8 c5 bf 15 0c 8b cb   .....5..........
	    0050 - e9 0c 74 54 42 f2 52 5a-2d 23 fa 9d b0 3e e5 4b   ..tTB.RZ-#...>.K
	    0060 - 3d 54 c9 a2 9b 47 cc ae-6b 7c 5f 6e 81 35 d6 ed   =T...G..k|_n.5..
	    0070 - 08 a4 38 34 bc 86 e2 e2-e2 de f8 4d 06 c0 03 a9   ..84.......M....
	    0080 - 0d aa 46 f6 35 04 a1 15-0b 0d 54 d3 6f 35 b2 5e   ..F.5.....T.o5.^
	    0090 - bd 1d 61 15 27 c7 a9 04-09 3d bd 4c 0f 15 3d 1e   ..a.'....=.L..=.
	    00a0 - 3b d3 91 e6 f7 76 eb a9-89 83 45 99 d5 12 c8 75   ;....v....E....u
	    00b0 - 79 ce aa 0a 9d a4 8b 3a-1a 28 63 c5 ba 0c 17 9b   y......:.(c.....

	    Start Time: 1448388877
	    Timeout   : 300 (sec)
	    Verify return code: 21 (unable to verify the first certificate)
	---

**Comment by youdly** [comment]
I tested again with fresh ubuntu wily VM. `curl` (7.43.0-1ubuntu2) and `openssl` (1.0.2d-0ubuntu1) showed no error, but firefox (41.0.2) did encounter cert error.

**Comment by fuglede** [comment]
Actually, I only now noticed that the problem only arises for coverity.com and not www.coverity.com; sorry about that. Did you notice any problems for the www one as well, since you mention that in your last post?

**Comment by youdly** [comment]
No issue on www, only coverity.com, hence the redirect rule (I mislabel it as exclusion pattern). Unfortunately I'm unable to squash the commits (git simply refuse to `rebase`), so I created another PR https://github.com/EFForg/https-everywhere/pull/3296.

**Comment by youdly** [comment]
No issue on www, only coverity.com, hence the redirect rule (I mislabel it as exclusion pattern). Unfortunately I'm unable to squash the commits (git simply refuse to `rebase`), so I created another PR https://github.com/EFForg/https-everywhere/pull/3296.

**Pull request closed without merging**
