### PR TITLE
[WIP][Ticketmaster] Split ruleset and remove right wildcards

### LINKED ISSUE #1953: Ticketmaster rule causes pages to break
http://www.ticketmaster.com/WWE-Live-SummerSlam-Heatwave-Tour-tickets/artist/1989737

Tour Tickets and Event Dates will just spin on loading for a while before going to a failure page.  Disabling the Ticketmaster (partial) rule resolves the issue.

Using Firefox 38.0.5 on Windows 7 with HTTPSE 5.0.5

### LINKED ISSUE #9427: Bug in div/tbody never loads (subsidiary information) just spinwaits.
Blocks on loading the info in the "Event Viewer" section of code.  Since I don't see what it's referencing ,  I have attached the URL and the sources and snap info (differences in generation that I *can* find.
Note that I tested with https-everywhere enabled and disabled.  (incognito mode was just easier to screenshot)

Hope it helps.
[working with HTTPS disabled.txt](https://github.com/EFForg/https-everywhere/files/894524/working.with.HTTPS.disabled.txt)
[CODE ONLY NOT WORKING with HTTPS Enabled.txt](https://github.com/EFForg/https-everywhere/files/894522/CODE.ONLY.NOT.WORKING.with.HTTPS.Enabled.txt)
[CODE ONLY working with HTTPS disabled.txt](https://github.com/EFForg/https-everywhere/files/894523/CODE.ONLY.working.with.HTTPS.disabled.txt)
[Web page source before populate.txt](https://github.com/EFForg/https-everywhere/files/894525/Web.page.source.before.populate.txt)
non working and working in incognito

### PR DESCRIPTION
**Pull request by Bisaloo**
#11203 

- [x] Fix #1953
- [x] Fix #9427
- [ ] Address https://trac.torproject.org/projects/tor/ticket/13347

### CODE REVIEW

**Comment by epicminecrafting** [comment]
@Bisaloo Can I continue work on this PR?

**Comment by pipboy96** [comment]
@Bisaloo Is this PR going to be updated?

**Comment by zoracon** [comment]
Closing for now due to conflicts in build and outdated PR, can reopen if interest is there.

**Comment by pipboy96** [comment]
@zoracon What is the current policy on closing outdated PRs?

**Comment by zoracon** [comment]
@pipboy96 There is no stated and explicit policy. I have been combing through outdated PRs going back to 2015 and just really making a call on a case by case basis.

The following scenarios where I close are:
 If it's been over a year and
* No revisions done from previous comments
* Conflicts and no revisions
* A reminder with no response

However I left others opened where the ruleset was fine at the time, but now due to length of time passed and host changes there are errors.

**Pull request closed without merging**
