### PR TITLE
Updated Stack-Exchange.xml

### PR DESCRIPTION
**Pull request by guiweber**
Removed meta.*.stackexchange.com as the certificate is not valid for this pattern

### CODE REVIEW

**Comment by jsha** [comment]
Looks good. Keep in mind this ruleset is currently disabled, and will need updates to the ruleset test in order to re-enable it.

**Comment by guiweber** [comment]
Right, I had not seen that. It is still enabled in 5.0 development 2. I'll work on it when I have time.

**Comment by jsha** [comment]
Great, thanks. BTW, please try installing the latest 5.0development.3:
https://www.eff.org/https-everywhere#install-development. Your dev2
install won't auto-update due to a packaging mistake, and we could use
all the testing help we can get.

**Comment by guiweber** [comment]
I have a new rule almost ready to go, but I was thinking of merging the following files into this one. Is this ok with you?
- Ask_Ubuntu.com.xml
- MathOverflow.net.xml
- Server_Fault.com.xml

Also, do you know if issue #58 got resolved? I removed the exclusion and I can login just fine on stackoverflow through openID using my google credentials on firefox.

**Comment by jsha** [comment]
Yes, it's fine to merge those files into it.

Regarding #58: It's entirely possible and likely that something changed on their site so the exclusion is no longer necessary. If you've tested thoroughly and it works, go ahead and remove the exclusion.

**Pull request merged**
