### PR TITLE
[ACLU of Maine] New ruleset

### PR DESCRIPTION
**Pull request by galenide**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Add a reference to this ruleset pointing to [`ACLU.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/ACLU.xml), and from `ACLU.xml` to this ruleset ([example](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/ACLU_of_Massachusetts.xml#L1-L6))

Optionally, some of the other ACLU rulesets also don't point to `ACLU.xml` and vice versa, such as [`ACLU-of-Texas.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/ACLU-of-Texas.xml). It would be nice if you could add some of the missing references.

Is squash-and-merge okay?

**Comment by jeremyn** [comment]
Regarding https://github.com/EFForg/https-everywhere/pull/7487/commits/89026dad915af2c4f88ada5e43aec101d58660d8 : please add a reference from `ACLU.xml` back to this ruleset as well.

**Comment by galenide** [comment]
On adding a reference to this ruleset in `ACLU.xml`, pull request #7498 is relevant.

Squash and merge should be okay for this pull request.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
