### PR TITLE
Updated Virgin Media rules

### PR DESCRIPTION
**Pull request by ukaccount123**
Tidied up and fixed rules for virginmedia.com

### CODE REVIEW

**Comment by J0WI** [comment]
I didn't check all the rules yet, but the following hosts are known to be RC4 only (#3627):
identity.virginmedia.com
national.virginmedia.com

**Comment by ukaccount123** [comment]
Yep I've marked them as such in the rules - should I disable those two for now?

identity.virginmedia.com is used by all customers to sign in to their accounts (via a redirect from the "My Virgin Media" Sign In link in the top right at http://www.virginmedia.com) so I presume this will be very quickly fixed once nobody can login.

national.virginmedia.com I'm not so hopeful about.

**Comment by J0WI** [comment]
I would disable them for now, because this result in a broken site and users have to use http anyway.
So it's better to have a working ruleset than disabling the whole ruleset.

An alternative would be to have a separate ruleset for problematic domains, that is disabled by default. But most users won't notice that.


Other meanings? (see also #3627)
cc @semenko @fuglede @jsha

**Comment by jsha** [comment]
Yep, I agree on disabling the specific hosts that have problems. Thanks!

**Comment by ukaccount123** [comment]
I've commented out the affected subdomains

**Pull request merged**
