### PR TITLE
Create Ulpgc.es.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
These hosts have chain issues:
biblioteca.ulpgc.es
preproduccionbu.ulpgc.es
www.centros.ulpgc.es

**Comment by davidabian** [comment]
@J0WI, what do you mean by chain issues? Should I simply comment those three subdomains?

**Comment by J0WI** [comment]
Yes , you have to exclude them. See https://github.com/EFForg/https-everywhere/pull/2668#issuecomment-134683296

**Comment by davidabian** [comment]
Done. Thanks, @J0WI.

**Comment by J0WI** [comment]
Thanks a lot for this huge contribution!

**Pull request merged**
