### PR TITLE
Ooyala:

### PR DESCRIPTION
**Pull request by numismatika**
- add opf & player subdomain
- ^ serves a valid cert

### CODE REVIEW

**Comment by J0WI** [comment]
Could you reconsider the mixed content problems?

**Comment by numismatika** [comment]
You mean removing that platform-tag?

**Comment by J0WI** [comment]
yes

**Comment by numismatika** [comment]
I only checked one website where it is used so i can't safely say it is fine to remove that tag.
We should find more sites with ooyala and check there before we remove it.

**Comment by J0WI** [comment]
The comment says it's just on www and only fonts and ads.
Those are both trivial I think.

**Comment by numismatika** [comment]
Yea but the reference to #1421 worries me.

**Comment by J0WI** [comment]
That's likely CORS, but I also don't want to break anything, so LGTM.
Thanks for updating!

**Pull request merged**
