### PR TITLE
Add mannheim.de

### PR DESCRIPTION
**Pull request by DavidLiedke**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:
- [ ] Add a `target` for https://mannheim.de
- [ ] Add a `test` for https://web2.mannheim.de directly under the `web2` `target`, with an extra indent, `url` http://web2.mannheim.de/wahlatlas/ . The root URL https://web2.mannheim.de is technically fine since it returns a 200, but it has an endless redirect loop using `http-equiv="Refresh"`, so let's add this extra `test`.
- [ ] Remove the `securecookie` tag or restrict it to the non-`^` `target`s
- [ ] Sort the domains in the top comment and the `target`s using our preferred ordering [here](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md#target-ordering). For example, the `target`s should be `^`, `www`, `katalog`, `opendata`, and `stadtarchiv`.
- [ ] Add a newline (but not a new line) at the end of the file to remove the red circle
- [ ] Change the `ruleset` `name` to `Mannheim.de (partial)`
- [ ] Change the filename to `Mannheim.de.xml`

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/14348/commits/a97c06ca5396faac4cd505e7e190afa3fa61d13e.

**Comment by DavidLiedke** [comment]
@jeremyn 
> Sort the domains in the top comment and the targets using our preferred ordering here. For example, the targets should be ^, www, katalog, opendata, and stadtarchiv.

I think i ordered the targets correctly. Can you explaine me the mistake ?

**Comment by jeremyn** [comment]
The domains under `Invalid Certificate` in https://github.com/EFForg/https-everywhere/pull/14348/commits/08e77144b34ea5e8062610e2bc3e47252a61f240 are sorted incorrectly. They should be:

```
<!--
	Invalid Certificate:
		beteiligungshaushalt.mannheim.de
		konversion.mannheim.de
		waehlenab18.mannheim.de
-->
```

Also I notice you have some extra whitespace [after `-->`](https://github.com/EFForg/https-everywhere/blob/08e77144b34ea5e8062610e2bc3e47252a61f240/src/chrome/content/rules/Mannheim.de.xml#L6), please remove that. (I've removed it here.)

**Comment by DavidLiedke** [comment]
@jeremyn 
Sorry :( 
I only controlled the target domains.

**Comment by jeremyn** [comment]
That's fine, thanks. Merged.

**Pull request merged**
