### PR TITLE
Added A8.net

### PR DESCRIPTION
**Pull request by luixxiul**

### CODE REVIEW

**Comment by J0WI** [comment]
rule LGTM, but why is it partial?

**Comment by luixxiul** [comment]
Because this is an affiliate service site. There would be other subdomains on which it serves resources like beacons (see the list of the observed domains https://www.virustotal.com/en/domain/a8.net/information/). Still, if we call it incomplete, which is normal, rather than partial, I will remove it from the name.

**Comment by J0WI** [comment]
`(partial)` is used when not all resources on a page can be secured (e.g. just static content). But we have no strong guideline about that.

**Comment by luixxiul** [comment]
Updated with including other domains.

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
