### PR TITLE
New ruleset for arte sites

### PR DESCRIPTION
**Pull request by LoHub**

### CODE REVIEW

**Comment by J0WI** [comment]
You may move the comments on the top

**Comment by semenko** [comment]
Looks like mixed content breaks a lot of arte.tv

**Comment by LoHub** [comment]
What can I do to resolve this problem ?

**Comment by LoHub** [comment]
What can I do to resolve this problem ?

**Comment by J0WI** [comment]
You can split up the ruleset in a normal and a mixed-content one, that contains ```platform="mixedcontent"```.
You may also contact someone to fix the hardcoded http links.

**Pull request closed without merging**
