### PR TITLE
added ruleset for juwelo.de

### PR DESCRIPTION
**Pull request by AykutCevik**
Tested with FirefoxDeveloperEdition on Mac since Firefox is disabling unsigned extensions.

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

Note as `Refused`:
- [ ] bietagent.juwelo.de
- [ ] welt-der-edelsteine.juwelo.de

`Timeout`:
- [ ] magento.test.juwelo.de

`Invalid Certificate`:
- [ ] info.juwelo.de
- [ ] wwww.juwelo.de (=> `www`)

Add targets:
- [ ] api.juwelo.de
- [ ] media.juwelo.de
- [ ] www.welt-der-edelsteine.juwelo.de

**Comment by jeremyn** [comment]
@AykutCevik Are you still interested in working on this?

**Comment by AykutCevik** [comment]
Hey @jeremyn , sorry for the late reply, I'm not interested anymore and we can reject this.

**Comment by jeremyn** [comment]
Thanks @AykutCevik , in that case I'm closing this pull request.

**Pull request closed without merging**
