### PR TITLE
Add bash.im ruleset

### PR DESCRIPTION
**Pull request by VoidPhantom**
Sublist3r also listed the `s.bash.im` domain name, but it does not seem to resolve to an IP address.

### CODE REVIEW

**Comment by epicminecrafting** [comment]
You need to add this line:
```xml
<securecookie host=".+" name=".+" />
```

**Comment by VoidPhantom** [comment]
Are you saying that I should add this line simply because it is a good idea, or because it has something to do with the reason why the test is failing?

I didn’t add a `securecookie` line after reading the discussion in #13762, which seems to suggest that:
> `securecookie` tags should only be used in targeted situations where we are trying to fix a identified vulnerability, instead of used as a default catch-all

Should I instead add a `securecookie`, just in case?

If you are saying that this is the reason why the test failed, why is that? If not, what is causing this test to fail? (I can’t seem to figure this out…)

**Comment by epicminecrafting** [comment]
@VoidPhantom The current project policy is to use `securecookie` unless it causes issues. `securecookie` is not required to pass tests.

**Comment by VoidPhantom** [comment]
OK, I added the `securecookie` line.

**Pull request merged**
