### PR TITLE
The tv.jobindex.dk certificate has been fixed

### PR DESCRIPTION
**Pull request by Eckankar**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the update. Since we're activating a ruleset, let's clean it up a little. It has a bunch of problems:

* [These targets](https://github.com/Eckankar/https-everywhere/blob/d447f00696e0cb56c82b2d54aceb88d746d7eed3/src/chrome/content/rules/Jobindex.dk.xml#L4-L6) are unsorted
* It's missing https://ca.jobindex.dk
* https://jobindex.dk works fine so [this complex rule](https://github.com/Eckankar/https-everywhere/blob/d447f00696e0cb56c82b2d54aceb88d746d7eed3/src/chrome/content/rules/Jobindex.dk.xml#L8) isn't needed
* [These per-target rules](https://github.com/Eckankar/https-everywhere/blob/d447f00696e0cb56c82b2d54aceb88d746d7eed3/src/chrome/content/rules/Jobindex.dk.xml#L9-L11) aren't needed.

So, please:

- [ ] Fix all of these problems by updating the ruleset to be this:

```xml
<ruleset name="Jobindex.dk">
  <target host="jobindex.dk" />
  <target host="www.jobindex.dk" />
  <target host="ca.jobindex.dk" />
  <target host="it.jobindex.dk" />
  <target host="tech.jobindex.dk" />
  <target host="tv.jobindex.dk" />

  <rule from="^http:" to="https:" />
</ruleset>
```

Also, we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits, which means rewriting commits in your name. Is that all right with you for this pull requests and other pull requests you might submit to us?

**Comment by Eckankar** [comment]
Thank you for the feedback. I have updated the rule to reflect your feedback.

**Comment by Eckankar** [comment]
Also, yes, I am okay with squash-and-merge.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
