### PR TITLE
[NaughtyDog.com] Update and reactivate ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**
#9842

### CODE REVIEW

**Comment by jeremyn** [comment]
Mark as `Invalid certificate`:
- [ ] https://feedback.naughtydog.com
- [ ] https://forums.naughtydog.com

Also:
- [ ] Add `target` for `naughtydog.com` and a `rule` to rewrite it to `www`

**Comment by jeremyn** [comment]
Thanks, however `naughtydog.com` should still be in the top comment, otherwise it's not clear why the special `rule` is needed.

**Comment by Bisaloo** [comment]
I wasn't sure how to explain it. Let me know if you would prefer something different.

**Comment by jeremyn** [comment]
I prefer your original text of `Different content http/https:`.

**Comment by Bisaloo** [comment]
I think we should be a bit more verbose for this case because we don't usually add rules when content differs between `http` and `https`.

**Comment by jeremyn** [comment]
Okay. I think your description is a little wordy. How about:

```
	Different HTTP/HTTPS content:
		naughtydog.com (503 status for HTTPS, 301 to www.naughtydog.com for HTTP)
```

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
