### PR TITLE
Update Python.org.xml

### PR DESCRIPTION
**Pull request by davidabian**

### CODE REVIEW

**Comment by J0WI** [comment]
WFM:
pypi.python.org
planet.python.org

**Comment by davidabian** [comment]
@J0WI: It seems that pypi is already [here](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Pypi.xml).
Should we join both files together?

**Comment by J0WI** [comment]
Yes, could you do that?

**Comment by J0WI** [comment]
@davidabian would be great to have this fixed :)

**Comment by jeremyn** [comment]
@davidabian Are you still interested in working on this one?

**Comment by jeremyn** [comment]
`pypi.python.org` is already in a different ruleset, [Pypi.xml](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Pypi.xml). It looks like that ruleset is included in the updates in this pull request, so you can delete that ruleset in this pull request.

**Comment by jeremyn** [comment]
Please:

Remove from top comment:
- [ ] https://ns1.pl.python.org , because this is too internal to list

Mark as `Invalid certificate`:
- [ ] https://es.python.org
- [ ] https://calendario.es.python.org
- [ ] https://documentos-asociacion.es.python.org
- [ ] https://empleo.es.python.org
- [ ] https://forum.pl.python.org
- [ ] https://mail.pl.python.org
- [ ] https://redesign.python.org

Mark as `No working URL known`:
- [ ] https://front.python.org

Mark as `Refused`:
- [ ] https://buildbot.python.org
- [ ] https://dinsdale.python.org
- [ ] https://www.es.python.org
- [ ] https://ftp.python.org
- [ ] https://legacy.python.org

Mark as `Secure connection failed`:
- [ ] https://blog.python.org
- [ ] https://blog-cn.python.org
- [ ] https://blog-de.python.org
- [ ] https://blog-es.python.org
- [ ] https://blog-fr.python.org
- [ ] https://blog-ja.python.org
- [ ] https://blog-ko.python.org
- [ ] https://blog-pt.python.org
- [ ] https://blog-ro.python.org
- [ ] https://blog-ru.python.org
- [ ] https://blog-tw.python.org

Add `target`:
- [ ] https://cheeseshop.python.org
- [ ] https://console.python.org and add `<test url="http://console.python.org/python-dot-org-live-consoles-status" />`
- [ ] https://discuss.python.org
- [ ] https://doc.python.org
- [ ] https://hg.es.python.org
- [ ] https://lists.es.python.org and remove from top comment
- [ ] https://speed.python.org
- [ ] https://staging2.python.org
- [ ] https://svn.python.org , add `<test url="http://svn.python.org/projects/sftools/" />` , and remove from top comment
- [ ] https://vote.python.org
- [ ] https://warehouse-staging.python.org

Also:
- [ ] Delete [the `altnames` comment](https://github.com/davidabian/https-everywhere/blob/00c2aaff4d9f7d79fedcd876bb1e32ee97e0533f/src/chrome/content/rules/Python.org.xml#L2-L5), we don't need it
- [ ] Delete [the `Direct rewrites` comment](https://github.com/davidabian/https-everywhere/blob/00c2aaff4d9f7d79fedcd876bb1e32ee97e0533f/src/chrome/content/rules/Python.org.xml#L21-L22), we don't need it
- [ ] Combine the `securecookie` tags and add more subdomains to it

**Comment by jeremyn** [comment]
@davidabian I'm checking in on this pull request. Are you planning on making the changes I requested?

**Comment by davidabian** [comment]
@jeremyn Yes, I am.

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/5109/commits/c9b696a749a85054a3ecff5aa8628d02bf9263dc.

For the `securecookie`, you added:
```xml
<securecookie host="^(?:[^@:/]+\.)python\.org$" name=".*" />
```

Looking at the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), I think a better fit with the same effect is:

```xml
<securecookie host="^[\w.-]+\.python\.org$" name=".+" />
```

but please double-check that. I originally had something more explicit like [this](https://github.com/EFForg/https-everywhere/blob/fc3e2b0c0e9f567dea056108f72d2e317e437ff6/src/chrome/content/rules/Microsoft.xml#L614) in mind, and that would be okay too.

For the merge conflicts, that was caused by https://github.com/EFForg/https-everywhere/pull/8128 which removed `docs.python.org` and `hg.python.org`. So, just remove those two subdomains and then merge or rebase.

Because of all the commits, is it all right with you if I remove the commit messages when I squash-and-merge at the end?

**Comment by davidabian** [comment]
Thanks, @jeremyn. Yes, please, feel free to remove these commit messages.

**Comment by jeremyn** [comment]
Thanks, looks good. Can you fix the conflict yourself? The problem is that if I do it for you, then I'm supposed to get another reviewer to look at my changes, and that might take a while.

Also, can you please move the `openbadges.es` target between `lists.es` and `jobs`? The goal is to have the subdomains grouped together in sub-subdomain order. You can also combine the `es` subdomains in the `securecookie` like `(hs|lists|openbadges)\.es` .

**Comment by davidabian** [comment]
Some certificates have expired since this pull request was opened. Should we wait until they are renewed?

**Comment by Hainish** [comment]
It looks like this PR contains some domains that are HSTS preloaded: https://chromium.googlesource.com/chromium/src/net/+/refs/heads/master/http/transport_security_state_static.json
Looking now: `wiki.python.org`, `www.python.org`, `pypi.python.org`, `doc.python.org`, and `console.python.org`

Since these are rewritten to HTTPS by the browser itself, there is no need to include them in this ruleset.  Removing them will cause the `preload` test to pass.

Thanks for contributing this! It's a big improvement.

**Comment by jeremyn** [comment]
@davidabian I updated the checklist through https://github.com/EFForg/https-everywhere/pull/5109/commits/13eaa5f72d068910596924398fbd874fae042c06 and emailed the Python.org webmaster about their certificate. Let's give them a few days on that problem.

**Comment by jeremyn** [comment]
I've also added the HSTS preloaded domains that were mentioned in https://github.com/EFForg/https-everywhere/pull/5109#issuecomment-275574332 to the checklist.

**Comment by jeremyn** [comment]
The Python.org team has renewed their certificate for https://svn.python.org, so that's not a problem anymore.

**Comment by jeremyn** [comment]
@gloomy-ghost @J0WI Can one of you please review the small changes I made and then merge this?

**Pull request merged**
