### PR TITLE
Update DHgate.com.xml (fix #4508)

### LINKED ISSUE #4508: dhgate.com - too many redirects
To reproduce error:
1. Use Chrome and turn on https everywhere
2. Visit online shop http://www.dhgate.com/
3. Search for something there, e.g. "jackets"

Expected behaviour is that I see search results. Instead I'm getting a Chrome error `ERR_TOO_MANY_REDIRECTS`. Also many parts of the site regarding articles are broken with https everywhere.

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
This PR looks out of date, for example `^` and `www` now appear to work.

Also, please add a legend or otherwise clarify the error causes in the top comment. `(r)` could be `Refused` or `Redirect`, for example, so it's unclear if https://seller.dhgate.com , which redirects and is marked with an `(r)`, is correctly described.

It would also be nice if the subdomains in the top comment were fully named, for example `seller.dhgate.com` instead of `seller`.

**Comment by J0WI** [comment]
@jeremyn I updated all comments, targets and tests.

**Comment by jeremyn** [comment]
Mark as `Expired` (or `Invalid certificate`), not `Mismatch`:
- [ ] https://e.dhgate.com
  
Mark as `Mixed content`:
- [ ] https://promo.dhgate.com
  
Mark as `Refused`:
- [ ] https://bbs.dhgate.com
  
Add `target`:
- [ ] https://au.dhgate.com
- [ ] https://m.au.dhgate.com
- [ ] https://ca.dhgate.com
- [ ] https://m.ca.dhgate.com
- [ ] https://nz.dhgate.com
- [ ] https://m.nz.dhgate.com
- [ ] https://o2o.dhgate.com
 
Add `test` or move to `No working URL known`:
- [ ] https://payment.dhgate.com
- [ ] https://shoppingcart.dhgate.com
 
Also:
- [ ] Add `.dhgate.com` to `secure` and `seller` in the top comment
- [ ] I don't see any CORS issues at `secure`. Can we remove the `CORS` part of the top comment?
- [ ] The `m.dhgate.com` `target` is not sorted correctly
- [ ] The root URL for https://css.dhresource.com has mixed content blocking, so add an `exclusion` (and a comment) for `/$`

**Comment by J0WI** [comment]
I've added another bunch of new hosts

**Comment by jeremyn** [comment]
I think we can remove https://factory.dhgate.com because it times out with both HTTPS and plain HTTP.

The domains in the top comment are now sorted incorrectly, please fix that.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
