### PR TITLE
Update Recode.net.xml

### PR DESCRIPTION
**Pull request by J0WI**
See also #7344

### CODE REVIEW

**Comment by jeremyn** [comment]
@J0WI Is this new PR because Recode.net has improved their HTTPS coverage and now we don't need all those exclusions in my older PR?

**Comment by J0WI** [comment]
Exactly. And I also added `events.recode.net`.

**Comment by jeremyn** [comment]
A person from Vox Media (which controls Recode.net) recently created PR https://github.com/EFForg/https-everywhere/pull/9700 for Vox domains. I think you and I should close our Recode PRs in favor of #9700 . What do you think?

**Comment by iamcarrico** [comment]
Sorry, I didn't see this PR— I just went through all our properties that are defaulting to HTTPS now.

**Comment by J0WI** [comment]
@iamcarrico could you increase the coverage of targets in your pending PR?
E.g. here I also added `events.recode.net`. If a host doesn't support HTTPS we use to list them in comments for future maintenance.

**Comment by iamcarrico** [comment]
I am doing a full audit of our subdomains and will add that in. 

Note: I am moving cross country this week— so implementation will be slightly delayed.

**Comment by jeremyn** [comment]
@J0WI What do you want to do with this PR?

**Comment by J0WI** [comment]
Since there is no progress in #9700 I would love to see this merged.

**Comment by jeremyn** [comment]
Mark as `Invalid certificate` or similar:
- [ ] https://photos.recode.net

Add `target`:
- [ ] https://live.recode.net
- [ ] https://on.recode.net

Also:
- [ ] Remove the `securecookie` tag or make it more specific (because we have a failing subdomain)

**Comment by iamcarrico** [comment]
Sorry y'all— I have not been able to get back to this. The structure is unfamiliar, and every time I tried I kept getting bogged down. I can say for certain that all of our sites are 100% HTTPS as of now though.

**Comment by jeremyn** [comment]
@iamcarrico That's fine, thanks for following up. If you are going to step back from making Vox rulesets indefinitely, please put a note in your PR #9700 and close it.

Also, just FYI, for HTTPS Everywhere we consider domains rather than sites, so for example https://photos.recode.net has an invalid certificate and so we won't include it in our rulesets. From the certificate error it looks like you are relabeling a SmugMug site under `recode.net`, so I can understand if you don't consider it one of your sites, but for us, it is. The best way to signal that all of your sites are covered by HTTPS is to add them to the HSTS preload list. When that happens, the domains should eventually be removed from HTTPS Everywhere.

**Comment by iamcarrico** [comment]
I'll make a ticket to remove that domain— I think it is just legacy gunk. Thank you.

**Comment by J0WI** [comment]
`on.recode.net` is already handled by `Bitly_branded_short_domains.xml`

**Comment by jeremyn** [comment]
I've updated the checklist through https://github.com/EFForg/https-everywhere/pull/9583/commits/0a6f921bba21b30cde8f7cbf711cba53d06e4be3.

There are other cookies at https://www.recode.net besides `^_chorus_geoip_continent$` that are secure: false. You can just use a `.+` for the `securecookie` `name`.

**Comment by J0WI** [comment]
Done.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
