### PR TITLE
Re-activate and Update respekt.cz.xml

### PR DESCRIPTION
**Pull request by cschanaj**
#9906 no sub-domain enumeration is performed.

### CODE REVIEW

**Comment by jeremyn** [comment]
The `default_off` message is `Broken login form, may work seamlessly with platform='mixedcontent'`. Did you test logging in?

**Comment by cschanaj** [comment]
I did not test logging in since I do not have an account. `www` redirects to HTTPS with `301`, so I assume it should works well over HTTPS. Should I add a `mixedcontent` attribute?

**Comment by cschanaj** [comment]
@jeremyn `^` redirects (302) to `www` while `www` redirects (301) to HTTPS. So I guess the site it moving to and encouraging HTTPS. IMHO, It should be safe to merge.

**Comment by jeremyn** [comment]
Merged.

**Comment by cschanaj** [comment]
thanks a lot!

**Pull request merged**
