### PR TITLE
added ruleset for computerwerk.org

### PR DESCRIPTION
**Pull request by moonlies**
Wildcard ruleset with two testing urls.

### CODE REVIEW

**Comment by J0WI** [comment]
It seems that wiki.computerwerk.org moved to computerwerk.org/wiki
You should also add a redirect for ^ to www.

Is there a reason to keep the wildcard rule when there is only one working domain?

**Comment by moonlies** [comment]
Since we are not planing to publish websites without a valid certificate, we would not have to update the rulesets.

**Comment by J0WI** [comment]
But this would still break the wiki subdomain and doesn't fix the insecure redirect from ^ to www.

**Comment by J0WI** [comment]
@moonlies are you still working on this?
Please also fix the code style.

**Comment by moonlies** [comment]
I will rewrite them and make another pull request someday.

**Pull request closed without merging**
