### PR TITLE
[Wj32.org] New ruleset

### PR DESCRIPTION
**Pull request by rugk**
Some notes for the web admin @wj32:
* Pretty bad SSL config (already submitted you some more information)
* On https://wj32.org/wp/ there is some mixed content. You can easily fix it as it as it is just on your own site.

### CODE REVIEW

**Comment by J0WI** [comment]
You should add the mixed content platform attribute.

**Comment by rugk** [comment]
The mixed content does not break the site. On https://wj32.org/wp/ it is just the ico file.

**Comment by J0WI** [comment]
At least [here](https://wj32.org/wp/about/) we have mixed display content in articles.
But I can live with that since the site sends a HSTS header. It's a bit weird but it works.

**Comment by rugk** [comment]
Yeah, possibly @wj32 notices this issue and can fix it.

**Pull request merged**
