### PR TITLE
add rule for Kairo.at

### PR DESCRIPTION
**Pull request by numismatika**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks, but please update [`KaiRo.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/KaiRo.xml) instead of making a new ruleset. You can use the same pull request.

**Comment by numismatika** [comment]
switched it.

**Comment by gloomy-ghost** [comment]
Please:

- [ ] Sort subdomains in alphabetical order, starting from the top level domain at the right reading left, moving `^` and `www` to the top of their group.
- [ ] Either remove cbsm.at or add a comment explaining how is it related to Kairo.at

**Comment by numismatika** [comment]
cbsm is a software sold by Kairo.

**Comment by J0WI** [comment]
@gloomy-ghost @jeremyn is there anything else preventing this from merge?

**Comment by gloomy-ghost** [comment]
Weird, it's the first notification I've received from this thread...

**Pull request merged**
