### PR TITLE
add dogechain.info

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by fuglede** [comment]
Site serves a broken certificate chain.

    $ curl -I https://dogechain.info
    curl: (60) SSL certificate problem: unable to get local issuer certificate

Probably another false test positive due to #6569.

**Comment by J0WI** [comment]
I just realized, that we may rather define a platform for this problematic than just disabling all this rules.

**Comment by fuglede** [comment]
Not a bad idea. There's quite a few of them by now.

    https-everywhere/rules$ grep 'chain' * | wc -l
    767

**Comment by jeremyn** [comment]
Note: this is one of the URLS requested in issue #3069.

**Comment by fuglede** [comment]
For the record, I wrote them about the missing intermediate.

**Comment by jeremyn** [comment]
- [ ] I don't get the incomplete certificate chain problem, so you can remove `default_off`.
- [ ] Note https://ws.dogechain.info as `Secure connection failed`.

**Comment by J0WI** [comment]
There is no HTTP connection to ws.dogechain.info possible at all, so I think it's not worth to mention.

**Comment by jeremyn** [comment]
That's fine. Merged. I've already removed the intermediate commit messages.

**Pull request merged**
