### PR TITLE
update GoogleImages.xml

### PR DESCRIPTION
**Pull request by luciancor**

### CODE REVIEW

**Comment by Jochen-A-Fuerbacher** [comment]
images.google.de works for me over HTTPS.

**Comment by luciancor** [comment]
it breaks when clicking on "Full-size image" / "Originalgröße"

Please give it a try - eg: http://images.google.de/imgres?imgurl=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2014%2F03%2F29%2F09%2F17%2Fcat-300572_960_720.jpg&imgrefurl=https%3A%2F%2Fpixabay.com%2Fen%2Fphotos%2Fcat%2F&h=720&w=858&tbnid=HR3uWxjt9lIc-M%3A&vet=1&docid=GNgiwtR-iQNmZM&ei=yMOBWIn-HMnqUpj_paAN&tbm=isch&client=firefox-b-ab&iact=rc&uact=3&dur=347&page=0&start=0&ndsp=34&ved=0ahUKEwiJgqftoNDRAhVJtRQKHZh_CdQQMwgxKAAwAA&bih=1042&biw=1620

**Comment by Jochen-A-Fuerbacher** [comment]
Ok, thank you. I agree.

**Comment by J0WI** [comment]
Does this does only affect the .de TLD?

**Comment by luciancor** [comment]
@J0WI from our tests: yes

**Comment by J0WI** [comment]
I cannot reproduce the issue here. How can I find this Link "Full-size image" / "Originalgröße"?

**Comment by luciancor** [comment]
@J0WI I cannot reproduce it either at this moment but please keep this PR open for a week or so to double check it while I am in Germany. I am currently abroad and it might be some geo issue as a lot of our users were complaining about this before we had this fix.

**Comment by luciancor** [comment]
Cannot reproduce it anymore even in Germany. Probably Google changed something. Thanks for keeping this up!

**Pull request closed without merging**
