### PR TITLE
add ix.br.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please add `target`s for:

- [ ] https://kb.internal.ix.br
- [ ] https://quarentena.internal.ix.br
- [ ] https://my.ix.br

**Comment by J0WI** [comment]
done

**Comment by jeremyn** [comment]
`quarentena.internal` should go directly under `kb.internal`.

**Comment by J0WI** [comment]
done

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
