### PR TITLE
Add section #pull-requests-from-deleted-accounts

### PR DESCRIPTION
**Pull request by jeremyn**
Ping @brainwane @gloomy-ghost @Hainish @J0WI @wonderchook .

### CODE REVIEW

**Comment by J0WI** [comment]
I think we don't really need a section just for "Deleted Accounts". Most of the points affect all PRs/Accounts.

**Comment by jeremyn** [comment]
@J0WI I'm not sure what you mean. Most of the modified text is specifically about deleted accounts.

**Comment by J0WI** [comment]
I mean it doesn't matter if you delete your account, be inactive or just not willing to address/discuss the feedback from maintainers.
I expect this as a common requirement in Open Source communities.

**Comment by jeremyn** [comment]
The @ghost situation is different from a contributor who just doesn't respond because the @ghost contributor deliberates puts their PR into the @ghost state. It is as if they put a comment in their PR "I'm not going to respond to requests about this, so take it or leave it". What I'm trying to say in the new text is that we're probably going to "leave it" and would prefer you did not submit it at all.

**Comment by Hainish** [comment]
This seems like an extreme edge case, and likely to not be followed.  I don't think it's necessary to add this section to an already large document for the few cases that this happens in - it just adds another thing for most contributors to glance over.  Also, we can deal with this edge case when it comes up via the GitHub API, as we've done before when @luixxiul deleted their HTTPS Everywhere branch.  Not an exact equivalent situation, but I'm sure it's easy enough to implement the removal of PRs from a @ghost account via the API.

**Comment by jeremyn** [comment]
@Hainish We get @ghost PRs regularly enough. Not long ago I went through and closed some. We also recently had a high-volume contributor delete their account so there are quite a few @ghost PRs in the backlog now.

Also my intent is not just to discourage people from doing this but also to have documentation that I can refer people to if they get upset if I "close @ghost pull requests without any comment."

If you think my text is too long, that's fine, we can edit it. But @ghost PRs are definitely things that exist.

**Comment by jeremyn** [comment]
@Hainish Will you merge this is if I make it less wordy? The wordiness might help people understand why it's annoying and stop making @ghost PRs, but I get that `CONTRIBUTING.md` is long already.

**Comment by Hainish** [comment]
@jeremyn could this text also apply to those that have deleted their HTTPS Everywhere fork, but haven't deleted their accounts (like @luixxiul)?  If so, perhaps we can generalize the language a bit.

I'm also not sure if this warrants such a prominent place, right under the "Welcome" section.  It might give people the wrong impression if we're warning them about deleting their account right as they're ready to get their hands dirty with PRs.

**Comment by jeremyn** [comment]
@Hainish This could also apply to the case when contributors delete their fork but not their account, though that is less common.

I agree with your concern about prominence, but the other three sections in the document are specific to rulesets, code, and translations. The @ghost problem applies to all three. What do you suggest?

**Comment by wonderchook** [comment]
Could it be added at the bottom instead below Contributing Translations? Doesn't seem quite ideal but I don't see another option that isn't at the top.

**Comment by jeremyn** [comment]
The problem with the length and organization of `CONTRIBUTING.md` is that there really is a lot of complexity involved in making rulesets and working with the project. Everything in there does, or should, represent some pain point being fixed or the outcome of some discussion by regular participants. The fact that the guide is so long isn't just bad document structure but instead is a symptom of underlying, maybe irreducible complexity. Omitting stuff or shuffling things around doesn't solve that problem.

That said, I can move this change to the bottom as @wonderchook suggests if that's what it takes to get this merged.

**Comment by Hainish** [comment]
@jeremyn

> Also my intent is not just to discourage people from doing this but also to have documentation that I can refer people to if they get upset if I "close @ghost pull requests without any comment."

Contributors will complain. I don't think documentation will help with this, and just adds to the complexity of the document.

> The problem with the length and organization of CONTRIBUTING.md is that there really is a lot of complexity involved in making rulesets and working with the project. Everything in there does, or should, represent some pain point being fixed or the outcome of some discussion by regular participants. The fact that the guide is so long isn't just bad document structure but instead is a symptom of underlying, maybe irreducible complexity. Omitting stuff or shuffling things around doesn't solve that problem.

I don't think it's useful to address edge cases _ad infinitum_ when suggestions are most likely not going to be followed.  I doubt even the utility of a short note, but I'm willing to cede the point if it serves you as a useful referent in discussions.

**Comment by jeremyn** [comment]
@Hainish The idea here and for some of my other suggestions is to standardize and document our processes to remove discretion from the maintainer. @sampablokuper at https://github.com/EFForg/https-everywhere/issues/14467#issuecomment-361755567 accurately described the goal as making it so contributors "file PRs against" the process, instead of "complaining" (as you say) to the contributor. There are about fifty @ghost PRs at the moment, any one of which might become some heated argument if some later commenter thinks a maintainer closed it arbitrarily.

 I don't care much where we document it or the fine points of the process, only that there is broad agreement and that it's documented somewhere.

**Comment by jeremyn** [comment]
Or, not even necessarily a heated/angry argument, but some time-consuming discussion where a commenter wants me to justify my decision, possibly months later.

**Comment by jeremyn** [comment]
@Hainish Please tell me what specific changes to make, or close this pull request.

**Comment by Hainish** [comment]
How about the following wording in the place @wonderchook has suggested:

```markdown
Sometimes a contributor will [delete their GitHub account](https://help.github.com/articles/deleting-your-user-account/) after submitting a pull request, resulting in the pull request being re-associated with the [Ghost user (@ghost)](https://github.com/ghost).  These @ghost pull requests can cause problems for HTTPS Everywhere maintainers, leaving questions unanswered and closing off the possibility of receiving contributor feedback to solicit clarification or request changes.  

We ask that if you want to delete your GitHub account, you either close your HTTPS Everywhere pull requests before you delete your account, or wait to delete your account until we merge your pull requests. Otherwise, maintainers are free to close @ghost pull requests without any comment.
```

**Comment by jeremyn** [comment]
@Hainish Your text looks fine to me, except for some minor issues: I would say "associated with" instead of "re-associated with", and in the last sentence of the first paragraph you probably meant "maintainer feedback" and not "contributor feedback". I'm also not sure how it should integrated with the table of contents, if at all. 

This issue is related to issues https://github.com/EFForg/https-everywhere/issues/13859 'New label: "pending closure"' and https://github.com/EFForg/https-everywhere/issues/13890 'Handling old issues' in that it's a way of trying to control the backlog. Also in this issue, like in those, there is maybe a lack of clarity and general support for the idea.

In any case I don't really feel like pushing this forward anymore. I'm closing this PR but if someone else wants to make a new version of it with their own changes, they should feel free, at least as far as I'm concerned.

**Comment by sampablokuper** [comment]
@jeremyn [wrote](https://github.com/EFForg/https-everywhere/pull/13887#issuecomment-364239612):
> [...] I don't really feel like pushing this forward anymore. I'm closing this PR but if someone else wants to make a new version of it with their own changes, they should feel free, at least as far as I'm concerned.

[Done](https://github.com/EFForg/https-everywhere/pull/14580) :)

**Pull request closed without merging**
