### PR TITLE
Dockerize travis test

### PR DESCRIPTION
**Pull request by Hainish**
@cooperq ready for review

### CODE REVIEW

**Comment by cooperq** [comment]
looks good to me! :+1:

**Comment by fuglede** [comment]
Purely out of interest: What are the benefits/downsides of doing it through `docker`?

**Comment by Hainish** [comment]
@fuglede for the history of this issue, see https://github.com/EFForg/https-everywhere/issues/4762  Even despite the longer test times, the advantage of being able to do IPv6 tests and having a locally-reproducible test environment is in my estimation worth the trade-off.  If we continue to see errors like the above, we might have to reevaluate that trade-off.

**Comment by fuglede** [comment]
Makes sense; thanks!

**Pull request merged**
