### PR TITLE
[you.163.com] Add rule for 163.com

### PR DESCRIPTION
**Pull request by sorz**
Add `you.163.com` to 163.com ruleset.

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your pull request. It looks like there are several subdomains for `you.163.com` that you can find on Google, and you can see our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md#enumerating-subdomains) for instructions. For example I see https://open.you.163.com and https://m.you.163.com and others.

Do you want to work on adding these subdomains too? You don't have to, and your pull request is ready to merge as it is. Please let me know.

**Comment by sorz** [comment]
Thanks for your help. I just add some subdomains that look fine with HTTPS in my browser.

**Comment by jeremyn** [comment]
Delete these, the responses have a `404` status:
- [ ] https://cashier.you.163.com
- [ ] https://pay.you.163.com

Also:
- [ ] Add a `target` for https://cps.you.163.com

**Comment by sorz** [comment]
Updated.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
