### PR TITLE
[EZ-Web-Hosting] Update ruleset

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by J0WI** [comment]
church.ez-web-hosting.com also works for me.

Sadly, it seems that every user gets a domain on ez\d+.ez-web-hosting.com/~user. This results in many cert or mixed content failures. Could you document this behaviour?

**Comment by Roman3349** [comment]
Done

**Comment by J0WI** [comment]
Rule LGTM, but conflicts with previous change.

**Comment by Roman3349** [comment]
@J0WI Done

**Pull request merged**
