### PR TITLE
[Khalsa Credit Union] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by jeremyn** [comment]
Please:

- [ ] Delete the `test` from [here](https://github.com/lucaspetter/https-everywhere/blob/3ea5fb7c688d0825642b2226a40405f97f368ea1/src/chrome/content/rules/Khalsa-Credit-Union.xml#L10) and move it below the relevant `rule` [here](https://github.com/lucaspetter/https-everywhere/blob/3ea5fb7c688d0825642b2226a40405f97f368ea1/src/chrome/content/rules/Khalsa-Credit-Union.xml#L14) so it looks like

```xml
	<rule from="^https?://khalsacreditunion\.ca/" to="https://www.khalsacreditunion.ca/" />
		<test url="https://khalsacreditunion.ca/" />
	<rule from="^http:" to="https:" />
```

This is a pretty unusual situation and moving the `test` under the `rule` gives a better hint to the reader about what's going on.

**Comment by lucaspetter** [comment]
Okay, I've moved the `test` under the `rule`.

**Comment by jeremyn** [comment]
Thanks, merged.

**Comment by lucaspetter** [comment]
Thanks.

**Pull request merged**
