### PR TITLE
[vpsFree.cz] Added new targets

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by fuglede** [comment]
https://rt.vpsfree.cz is broken;

    $ curl https://rt.vpsfree.cz
    curl: (60) SSL certificate problem: unable to get local issuer certificate

**Comment by Roman3349** [comment]
I will contact the owner to fix an incomplete certificate chain, thank you for notice.

**Comment by fuglede** [comment]
Cool; the rest of the changes in this one look good to me. Do you want to exclude the problematic subdomain for now, or should we just close the PR for now and reopen it if the chain gets fixed?

**Comment by Roman3349** [comment]
I excluded the problematic subdomain now.

**Pull request merged**
