### PR TITLE
Update Pbsrc.com.xml

### LINKED ISSUE #3527: Pbsrc.com STILL breaks photobucket functionality
This was reported as an issue in the 2015.8.13 version and is still an outstanding issue in 2015.12.16.

Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

### PR DESCRIPTION
**Pull request by terrorist96**
Fixes #3527

### CODE REVIEW

**Comment by J0WI** [comment]
Could you check if you can solve the issue by excluding just a single file?
A good way to start is by looking at the loaded resources: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

If you see a CORS error in the console, you may able to fix it by excluding just the .xml source. Otherwise you may have to exclude JS and SWF resources.

**Comment by terrorist96** [comment]
Here's a screenshot of the console with the Pbsrc.com rule active and inactive. What am I looking for?

**Comment by J0WI** [comment]
Hmm, there are some mixed content issues.
Can you check if allowing the mixed content would work?

**Comment by terrorist96** [comment]
There's no option in Chrome to 'load unsafe scripts', so I'm not sure how you want me to check if allowing mixed content works or not.

**Comment by J0WI** [comment]
Just have a look at https://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content

**Comment by terrorist96** [comment]
Bro, I just said, there's no shield icon in the address bar for me to click in order to load unsafe scripts. Can you please try reproducing this bug yourself so you can see what I'm talking about?
All I know is that disabling the Pbsrc rule fixes the issue. I don't understand why it's so difficult to disable this rule on photobucket.

**Comment by J0WI** [comment]
Sorry I just realized, that the Flash file is not loaded if you have no Flash Player installed.
You should see something like `/flash/zeroclipboardFV3.swf` loaded in your network monitor. Can you try if an exclusion for that would fix it?

**Comment by terrorist96** [comment]
I see zeroclipboardFV3.swf when I disable the Pbsrc rule. How would I test an exclusion? I think this would have been fixed a long time ago if someone more experienced would take a look, instead of this back and forth lol.

**Comment by terrorist96** [comment]
How's that ^
???

**Comment by J0WI** [comment]
You regex syntax is wrong, but I would prefer to avoid the wildcard anyway when possible.
You also have to add a test url for the exclusion.

**Comment by terrorist96** [comment]
Well I don't know what more you want me to do. This is too much work trying to figure out what you want me to do. Someone else can fix it; don't care anymore.

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10

**Comment by J0WI** [comment]
> Well I don't know what more you want me to do. This is too much work trying to figure out what you want me to do. Someone else can fix it; don't care anymore.

Okay I close this. I proposed a fix in #3527 if you like to give it a chance again.

**Pull request closed without merging**
