### PR TITLE
Create nytimes2tsqtnxek.onion.xml

### PR DESCRIPTION
**Pull request by Bisaloo**
#12122

### CODE REVIEW

**Comment by koops76** [comment]
@Bisaloo Better stick it in `NYTimes.com.xml` though.

**Comment by Bisaloo** [comment]
> @Bisaloo Better stick it in NYTimes.com.xml though.

Why?

**Comment by koops76** [comment]
@Bisaloo Technically the same website.

**Comment by Bisaloo** [comment]
True. But it is quite possible that the onion may be down when the clearnet domain isn't (or *vice versa*). It is more robust to add them in different rulesets in that regard.

**Pull request merged**
