### PR TITLE
Added searchteria.co.jp

### PR DESCRIPTION
**Pull request by luixxiul**
See #6045

### CODE REVIEW

**Comment by fuglede** [comment]
You don't really need the test URL in cases like these; one is automatically inferred from the target host. As it's set up right now, the test is actually [run twice](https://travis-ci.org/EFForg/https-everywhere/jobs/149292462#L1572).

**Comment by luixxiul** [comment]
@fuglede ok done

**Comment by luixxiul** [comment]
@fuglede sometimes the test is run twice, sometimes once, why?

**Comment by fuglede** [comment]
That sounds weird. Do you have the link to an example where it's run twice where it shouldn't be?

**Comment by luixxiul** [comment]
Sorry, maybe I misunderstood something. No problem.

**Pull request merged**
