### PR TITLE
Add juliar.org

### PR DESCRIPTION
**Pull request by TheAndreiM**

### CODE REVIEW

**Comment by TheAndreiM** [comment]
Why did the checks fail?

**Comment by TheAndreiM** [comment]
OK! We are good to go.

**Comment by gloomy-ghost** [comment]
Thanks for your contribution! Can you switch [L4](https://github.com/TheAndreiM/https-everywhere/blob/34c913ba0fc975d283759eb710d8f4e6f4ab1d55/src/chrome/content/rules/Juliar.xml#L4) and [L5](https://github.com/TheAndreiM/https-everywhere/blob/34c913ba0fc975d283759eb710d8f4e6f4ab1d55/src/chrome/content/rules/Juliar.xml#L5) so that they are in alphabetical order?

**Comment by TheAndreiM** [comment]
Switched. Thanks!

**Pull request merged**
