### PR TITLE
Re-enable and add Costco.xml to ruleset-whitelist.csv

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Related: #5377

**Comment by J0WI** [comment]
Could you also increase the coverage of this rule? Some subdomains can be secured now.

**Comment by J0WI** [comment]
BTW: I think the 403 error was because of the issue with Akamai hosts. Fetch test should pass now.

**Comment by koops76** [comment]
@J0WI Request review.

**Pull request merged**
