### PR TITLE
Update UW.edu.xml - iSchool redirection

### PR DESCRIPTION
**Pull request by flynn16**

### CODE REVIEW

**Comment by flynn16** [comment]
Hello.

Could you re-run this build job [#36003.4](https://travis-ci.org/EFForg/https-everywhere/jobs/325158950)?

**Comment by jeremyn** [comment]
@flynn16 FYI, you can rerun Travis tests yourself by closing and reopening the pull request.

**Comment by flynn16** [comment]
Great. Now all tests have passed.

**Comment by jeremyn** [comment]
Please:

- [ ] Delete `<!-- iSchool certificate matching problem -->` and instead add `- www.ischool ᵐ` directly below `honors` in the top comment
- [ ] Delete the `rule` with `from="^https`, because we avoid doing HTTPS > HTTPS rewrites
- [ ] Delete both new `test`s, because the first `test` duplicates the [implicit test](https://github.com/EFForg/https-everywhere/blob/45cf7c85151609862175b09c8ee682d204846465/CONTRIBUTING.md#left-wildcards) created by the `www.ischool` `target`, and the second `test` isn't needed because we're deleting the `https` `rule`.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
