### PR TITLE
Create Nikkei.com.xml

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please:

Note as `Reset`:
- [ ] invz.nikkei.com
- [ ] leap.nikkei.com
- [ ] sp.nikkei.com

`Refused`:
- [ ] www.nikkei.com
- [ ] adb.nikkei.com
- [ ] adpriv.nikkei.com
- [ ] adprivcache.nikkei.com
- [ ] adrep.nikkei.com
- [ ] ag.adrep.nikkei.com
- [ ] jinji.api.nikkei.com
- [ ] markets.api.nikkei.com
- [ ] page.api.nikkei.com
- [ ] jinji.api323.nikkei.com
- [ ] markets.api323.nikkei.com
- [ ] page.api323.nikkei.com
- [ ] appli.nikkei.com
- [ ] appli323.nikkei.com
- [ ] mx.asia.nikkei.com
- [ ] asianreview.nikkei.com
- [ ] aspn.dspx.nikkei.com
- [ ] qmd.dspx.nikkei.com
- [ ] dspxapi.nikkei.com
- [ ] dspxapi323.nikkei.com
- [ ] dsquare.nikkei.com
- [ ] election.nikkei.com
- [ ] m.nikkei.com
- [ ] m323.nikkei.com
- [ ] mb.nikkei.com
- [ ] mw.nikkei.com
- [ ] markets.mw.nikkei.com
- [ ] mw323.nikkei.com
- [ ] mx.nikkei.com
- [ ] mx3.nikkei.com
- [ ] mx4.nikkei.com
- [ ] mxt.nikkei.com
- [ ] autodiscover.nex.nikkei.com
- [ ] nwp.nikkei.com
- [ ] parts.nikkei.com
- [ ] pr.nikkei.com
- [ ] markets.api.pre.nikkei.com
- [ ] page.api.pre.nikkei.com
- [ ] appli.pre.nikkei.com
- [ ] room323.nikkei.com
- [ ] store.nikkei.com
- [ ] xc.nikkei.com

`Timeout`:
- [ ] id.dev.nikkei.com
- [ ] id.dev-ext.nikkei.com
- [ ] hack.nikkei.com
- [ ] rebuild.nikkei.com
- [ ] weather.nikkei.com

`Invalid Certificate`:
- [ ] my.api.nikkei.com
- [ ] applicdn.nikkei.com
- [ ] applicdnv2.nikkei.com
- [ ] applicdnv2org.nikkei.com
- [ ] asia.nikkei.com
- [ ] horizon.asia.nikkei.com
- [ ] link.asia.nikkei.com
- [ ] video.asia.nikkei.com
- [ ] cdn.nikkei.com
- [ ] mail.cn.nikkei.com
- [ ] regist.asia.dev.nikkei.com
- [ ] faq.nikkei.com
- [ ] mainta.nikkei.com
- [ ] niid.nikkei.com
- [ ] nkispa.nikkei.com
- [ ] stats.nikkei.com
- [ ] style.nikkei.com

`404`:
- [ ] eb.store.nikkei.com

`MCB`:
- [ ] zh.cn.nikkei.com (can be secured)

Add targets:
- [ ] regist.asia.nikkei.com
- [ ] evernote.nikkei.com
- [ ] id.nikkei.com
- [ ] idrp.nikkei.com
- [ ] lissn.nikkei.com
- [ ] maint.nikkei.com
- [ ] partsa.nikkei.com
- [ ] s.nikkei.com
- [ ] sp-ssl.nikkei.com
- [ ] sstats.nikkei.com
- [ ] support.nikkei.com
- [ ] vdata.nikkei.com
- [ ] vrid.nikkei.com

**Comment by gloomy-ghost** [comment]
Thanks, merged.

**Comment by Foorack** [comment]
@gloomy-ghost Weird, support.nikkei.com does not redirect too many times for me...

**Comment by ivysrono** [comment]
@Foorack https://travis-ci.org/EFForg/https-everywhere/jobs/175056721#L218

**Comment by Foorack** [comment]
@ivysrono Ah okay.

**Pull request merged**
