### PR TITLE
[Coast Capital Savings] New ruleset

### PR DESCRIPTION
**Pull request by lucaspetter**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Thanks. Please:

- [ ] Add target `agency.coastcapitalsavings.com`

Note as `Invalid Certificate`:
- [ ] annualreport.coastcapitalsavings.com
- [ ] copsforcancer.coastcapitalsavings.com
- [ ] www.copsforcancer.coastcapitalsavings.com

**Comment by lucaspetter** [comment]
Okay, I've made the changes. How did you find those extra hosts? Thanks.

**Comment by gloomy-ghost** [comment]
The general suggestion is recursive searching 
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

Also there is a script, but you need to check that is it legal in your country. You can find more information at #7277 

The ruleset is good, merged.

**Comment by lucaspetter** [comment]
I've been using recursive searching and looking through sites' HTML, but didn't know about Sublist3r. Thanks.

**Pull request merged**
