### PR TITLE
 Update National_Geographic.xml

### PR DESCRIPTION
**Pull request by episkorowski**
#12901
Just removed the www-s redirect, website loads now.

I had trouble with the testing, since some of the subdomains in the rule don't seem to exist anymore, namely donate and natgeotv. Can't create test URLs for URLs that aren't valid anymore, so I'm not sure if I can proceed without restructuring everything.

This is my first pull request for the project, so let me know if I messed something up.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Hi, thank you for your pull request!

Unfortunately, you did not pick the easiest ruleset to start with.

As you can read in our [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#example-ruleset-before-style-guidelines-are-applied), we are [moving away from left wildcard when possible](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#left-wildcards).

This means that you should try to [find the subdomains associated with this domain](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains), and add a target for each one that supports `https`. Because this domain has a lot of subdomains and because your main goal here is to solve #12901, it is probably fine if you add the most relevant ones using favorite search engine for now.

Just so you know, the tests are failing because you are currently using a wildcard without any test url. [Left wildcards require at least three test url](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md). Because this ruleset has not been updated in a long time, it does not fulfill this requirement and the tests are failing. But it does not matter here because if you follow the new guidelines, you probably won't need any test url.

Feel free to let me know if you have further questions.

**Comment by episkorowski** [comment]
Thanks for the feedback. I used Sublist3r to get the subdomains of the site so I could add those as targets and simplify the regex. I did fetch tests and pruned some of the subdomains that didn't seem to resolve or support HTTPS, but there are still a bunch that return errors. The site works, though. Should I proceed by just removing the targets that cause errors in the fetch tests?

**Comment by Bisaloo** [comment]
You shouldn't add all subdomains and rely on the automated tests to detect non-functional targets. Many errors, such as active mixed content or content different between the `http` and `https` version of the page can't be detected by the tests. Instead, you should manually test all the targets that you add.

As I said, you don't necessarily have to add all subdomains at the moment. It is a huge amount of work and it doesn't need to be done in a single pull request. Please just add subdomains that you manually tested.

`Sublist3r` has the tendency to list a lot of bogus subdomains, hence my recommendation to use a search engine in this case. `Sublist3r` is fine for "simpler" domains though.

**Comment by Bisaloo** [comment]
[The tests also complain that one targets is listed in two different rulesets.](https://travis-ci.org/EFForg/https-everywhere/jobs/324938159#L602)

> failure: Hostname news.nationalgeographic.com with platform '' shows up in 2 different rulesets.

You should merge [National_Geographic.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/National_Geographic.com-problematic.xml) into the main ruelset.

**Comment by episkorowski** [comment]
I implemented the changes that you suggested. I did some manual testing and ran the automated tests with everything seemingly passing, but I ran into a problem trying to make a commit. It runs the automated tests before I commit and it gives me an error. 

Heres the output:

```
Thu, 04 Jan 2018 23:10:51 -0500: Stashing unrelated changes in Git...
Thu, 04 Jan 2018 23:10:52 -0500: Running ruleset validation tests on changed rulesets:
Thu, 04 Jan 2018 23:10:52 -0500: Skipped validation of src/chrome/content/rules/National_Geographic.com-problematic.xml - not found.
usage: trivial-validate.py [-h] [--quiet]
trivial-validate.py: error: unrecognized arguments: src/chrome/content/rules/National_Geographic.xml
Thu, 04 Jan 2018 23:10:52 -0500: Failure encountered during ruleset validation.
Thu, 04 Jan 2018 23:10:52 -0500: Reverting Git stash...
```
I didn't get anything like this before with my previous commits. Does this mean that the file itself is an invalid argument or something in it is? I'm sure it still exists with the same filename in the directory so I'm confused. I also didn't get an error like this with the other tests.

Thanks for your patience.

**Comment by Bisaloo** [comment]
The ruleset in its new version should not trigger an error as far as I can tell. Can you try to bypass the tests?

`git commit --no-verify` and if necessary `git push --no-verify`.

I am not sure what went wrong with the pre-commit tests, I will have a look and will open a new issue if necessary.

**Comment by episkorowski** [comment]
Shoot, something went wrong and now there's a bunch of other people's commits in this PR. I don't know how that happened. I'm sorry, this is my first time using git for contributing to a project and I'm still figuring stuff out. Is there any way to clean this up or should I just close this PR and open a new one with the changes? Again, thank you for your patience.

**Comment by Bisaloo** [comment]
Don't worry, it's okay, I've been there ^^.

I am guessing you did something such as

```bash
git rebase -i master
git push # doesn't work, tells you that you need to pull first
git pull
git push
```

when you wanted to 

```bash
git rebase -i master
git push --force
```

Here, you use the `--force` flag because you want to overwrite your previously pushed commits. But be careful with it (the `git` manual probably has a warning on this).

It is possible to fix this but I am not entirely sure how to do it myself. I would need to try different things so I don't think I can guide you through it. Feel free to open a new PR with your changes. You can tag me in the new PR.

**Comment by episkorowski** [comment]
Yeah, that's about what I did. I'll make a note of that.

I'll just close this and open a new PR with the changes.

**Pull request closed without merging**
