### PR TITLE
Re-activate and Update Techmeme.com.xml

### PR DESCRIPTION
**Pull request by cschanaj**
#9842

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Put all five problem subdomains in the top comment under the single problem type `Invalid certificate`
- [ ] Add a `target` and `rule` for http://search.techmeme.com [here](https://github.com/cschanaj/https-everywhere/blob/bfc28548a67bebf6835915b6420e87026a15b15a/src/chrome/content/rules/Techmeme.com.xml#L15) like this:

```xml
    <target host="search.techmeme.com" />
 
    <rule from="^http://search\.techmeme\.com/" to="https://www.techmeme.com/search" />
```

**Comment by cschanaj** [comment]
done. thanks!!

**Comment by jeremyn** [comment]
Thanks for making the changes, but `search.techmeme.com` should be in the top comment too, so people know what the special `rule` is for.

**Comment by jeremyn** [comment]
Thanks again, merged.

**Pull request merged**
