### PR TITLE
syllable.org

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks. I didn't check all the non-English variants but I think all of these except https://forum.development.org have active mixed-content blocking. How do you want to handle that?

**Comment by galeksandrp** [comment]
Ads only. We can prefer security over usability.

**Comment by jeremyn** [comment]
We should definitely not break their ads.

**Comment by galeksandrp** [comment]
Added `platform="mixedcontent"`

**Comment by jeremyn** [comment]
Thanks. Just to confirm, are you okay with squash-and-merge on this and other pull requests?

**Comment by galeksandrp** [comment]
Yes.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
