### PR TITLE
Add Net-metrix.ch.xml and update Wemfbox.ch.xml

### PR DESCRIPTION
**Pull request by J0WI**
`Wemfbox.ch.xml` is only tracking anyway.
See also: #14293

### CODE REVIEW

**Comment by jeremyn** [comment]
Where are you getting information about the redirects? For example how would I verify this change is correct?
```xml
		<rule from="^http://wetter\.wemfbox\.ch/"
		to="https://we-ssl.wemfbox.ch/" />
```

to
```xml
		<rule from="^http://wirelter\.wemfbox\.ch/"
		to="https://we-ssl.wemfbox.ch/" />
```

Neither `wetter.wemfbox.ch` nor `wirelter.wemfbox.ch` redirect themselves to `we-ssl.wemfbox.ch`.

**Comment by J0WI** [comment]
I was searching for the source of `wirelter.wemfbox.ch` (which I found in an archived version of the site) and found `we-ssl.wemfbox.ch` in the current source code of `https://www.wireltern.ch/`.

**Comment by cschanaj** [comment]
related to #14660

**Comment by Bisaloo** [comment]
Related: #12297

**Comment by J0WI** [comment]
I just rebased this. Would be great to get a review here to fix the mentioned issues.

**Pull request merged**
