### PR TITLE
Update known supported subdomains for IETF.org

### PR DESCRIPTION
**Pull request by maxnystrom**
Also added some test URLs.

### CODE REVIEW

**Comment by J0WI** [comment]
Please see also:
www.apps.ietf.org
xml2rfc.ietf.org

The comments about *.tools.ietf.org and mixed content are not up to date.
Further, you can remove the `(partial)` flag from the rule name.

**Comment by J0WI** [comment]
Sorry, I didn't remember that one when I merged #8321. Could you rebase your changes on top of the current master? I think some of them are obsolete now.

**Comment by J0WI** [comment]
ping @maxnystrom

**Comment by jeremyn** [comment]
I'm closing this due to lack of response from @maxnystrom .

**Pull request closed without merging**
