### PR TITLE
Add option to opt-out EASE mode warning page

### PR DESCRIPTION
**Pull request by cschanaj**
@Hainish @zoracon This PR add an advanced option for users to opt-out EASE mode warning page in order to workaround with #17192. 

Any hope for merging before #17157? 

---

For future reference, this PR also disabled the selenium test for the `#showCounter` sanity check. This is because adding new options slow down the asynchronous `chrome.storage.get`. This resulted in failing selenium test. 

In 9612b19, I tried to avoid the bulk get operations and 3/4 selenium tests passed. However, standalone callback for each option introduce unnecessary code complexity. 

In 84b6910, I tried to increase the timeout to 10 seconds for each reload. This slows down the selenium test terribly and 4/4 tests failed. 

In 21fe45b and c225836, I disabled the selenium test for the `#showCounter` sanity check and added comments in the source code. Travis passed.

### CODE REVIEW

**Comment by zoracon** [comment]
@cschanaj Sorry for missing this discussion and contribution. We plan on doing another release this month so I am hoping to get more tweaks in. 

Overall if the user decides to opt-out of the page it sort of defeats the purpose of BAUR (soon to be EASE) being enabled. They can choose to uncheck BAUR if this mode does not fit their needs. But issue #17192 brings up a great point about self-signed certs and sites that don't exist. I'll get to work on that ASAP.

However the Selenium change you made is a good improvement. We been having issues since that test is a bit flaky. So thank you for that!

**Comment by Bisaloo** [comment]
> Overall if the user decides to opt-out of the page it sort of defeats the purpose of BAUR (soon to be EASE) being enabled.

I'm not sure I understand what you mean. For a very long time, there was no interstitial error page and users would get the default browser error. EASE would nonetheless still force all connections to HTTPS.

**Comment by cschanaj** [comment]
This PR was intended to allow the users to opt-out the warning page without leaving the EASE mode, this prevents certain privacy/ security risks disabling EASE mode. Since #17192 looks like an advanced-users-only problem, I have put it in the advanced option tab. 

In #17192, it was mentioned that identifying the errors in Firefox is tricky and subjected to upstream changes. I would think an option to opt-out the warning page is a good thing to have.

**Comment by zoracon** [comment]
> > Overall if the user decides to opt-out of the page it sort of defeats the purpose of BAUR (soon to be EASE) being enabled.
> 
> I'm not sure I understand what you mean. For a very long time, there was no interstitial error page and users would get the default browser error. EASE would nonetheless still force all connections to HTTPS.

Yes, they would get the default browser error in EASE mode, but would not have access to add exempt http links. The interstitial page is not only a an alternative to the browser default page, but a place to venture forth and add to the "exempt links" list we implemented when EASE came about.

**Comment by zoracon** [comment]
> This PR was intended to allow the users to opt-out the warning page without leaving the EASE mode, this prevents certain privacy/ security risks disabling EASE mode. Since #17192 looks like an advanced-users-only problem, I have put it in the advanced option tab.
> 
> In #16418, it was mentioned that identifying the errors in Firefox is tricky and subjected to upstream changes. I would think an option to opt-out the warning page is a good thing to have.

If advanced users get the option to opt-out of the interstitial, do you also conclude that they would not want access to the "Sites Disabled" list? We not only provide an alternative interstitial, but this option as well with that page.

**Comment by zoracon** [comment]
After some discussion with bringing up these points I much rather focus on the bugs in the case of advanced users and improve the interstitial experience. Providing an opt out would ultimately not help us see the potential bugs advanced users come across. The interstitial appears not only as a warning but a "one stop" for adding exemptions. 

As we incorporate new UX in the near future, maybe we can add the network code in a "read more" for advanced users.

**Comment by cschanaj** [comment]
I'd consider adding a domain to the "Site Disable" the last resort when dealing with page breakage, it is arguably less secure than the default mode if the disabled domain serves mostly upgrade-able content. Otherwise, quitting EASE mode is a more promising resolution for average users.

However, if advanced users are not allowed to leave the EASE mode. The interstitial breaks the "Add a rule for this site" feature rendering it impossible for advanced users to add the "user rule" from the extension popup. 

I would expect when an advance found that `^` is unreachable over HTTPS, they will try to prepend `www` to the URL and see if it works. If `www` works, visit `^` again and add an trivial snapping rule, so that the breakage will not show up for a while. This can be done in completely and conveniently in EASE mode without type the whole URL again in the address bar. 

If this PR is not needed, I am ok closing it. thanks.

**Comment by zoracon** [comment]
> I'd consider adding a domain to the "Site Disable" the last resort when dealing with page breakage, it is arguably less secure than the default mode if the disabled domain serves mostly upgrade-able content. Otherwise, quitting EASE mode is a more promising resolution for average users.
> 
> However, if advanced users are not allowed to leave the EASE mode. The interstitial breaks the "Add a rule for this site" feature rendering it impossible for advanced users to add the "user rule" from the extension popup.
> 
> I would expect when an advance found that `^` is unreachable over HTTPS, they will try to prepend `www` to the URL and see if it works. If `www` works, visit `^` again and add an trivial snapping rule, so that the breakage will not show up for a while. This can be done in completely and conveniently in EASE mode without type the whole URL again in the address bar.
> 
> If this PR is not needed, I am ok closing it. thanks.

This helps us to think about a good prompt for adding a rule for the "sites disabled" and get more users to easily request or add a rule. I will work to improve that from this disfromcussion. 

I can close out this but I am flagging this for the UX development that is in the works.

**Comment by cschanaj** [comment]
Thanks.

**Pull request closed without merging**
