### PR TITLE
Update Microsoft-mixedcontent.xml and Microsoft.xml

### PR DESCRIPTION
**Pull request by renyouguo**

### CODE REVIEW

**Comment by J0WI** [comment]
I think this can be safely merged into the default Micorsoft rules since I get redirected to https://blogs.msdn.microsoft.com/ anyway.

**Comment by J0WI** [comment]
Please always document the hosts you removed (if they still exists) that other don't readd them accidentally in future.

**Comment by renyouguo** [comment]
@J0WI  There is no conflicts several days ago?

**Comment by J0WI** [comment]
We had a huge clean up this week, you should rebase your branch against current master to fix any conflicts.

**Comment by renyouguo** [comment]
#4913

**Pull request closed without merging**
