### PR TITLE
Make trivial rule for macromates.com

### PR DESCRIPTION
**Pull request by jish**

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for your ruleset! There are a bunch of subdomains that you didn't include that you can see [here](https://www.google.com/search?q=site%3A*.macromates.com&ie=utf-8&oe=utf-8#q=site:*.macromates.com+-site:manual.macromates.com), such as `wiki`, `blog` etc. Can you please add them if they work or note them as problems if they don't? [Here](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=problematic+domains) are examples for noting bad domains.

**Comment by jish** [comment]
I added a `<target>` tag for `license.macromates.com` and listed all of the others as Problematic domains.

**Comment by jeremyn** [comment]
Thanks. A couple more things:

- [ ] Add targets for `macromates.com` and `shop.macromates.com`
- [ ] Note a reason for the problematic domains. It looks like they're all certificate mismatches so you can just add `(certificate mismatch)` to the right of each of them in the comment.

**Comment by jish** [comment]
I've added `shop.macromates.com` and documented the certificate mismatches.

**Comment by jeremyn** [comment]
Thanks again. Merged. I see you already had `macromates.com`, and I'm not sure how I missed that on re-review. I'm sorry about that.

**Pull request merged**
