### PR TITLE
[Greenpeace-Energy.de] new ruleset

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Comment by reedy** [comment]
It seems the remote server 301s these requests back to HTTP... As well as adding the www if necessary

```
reedy@ubuntu64-shell-esxi:~$ curl -I http://greenpeace-energy.de
HTTP/1.1 301 Moved Permanently
Date: Thu, 30 Apr 2015 19:41:29 GMT
Server: Apache/2.2.22 (Debian)
Location: http://www.greenpeace-energy.de/
Content-Type: text/html; charset=iso-8859-1

reedy@ubuntu64-shell-esxi:~$ curl -I http://www.greenpeace-energy.de
HTTP/1.1 307 Temporary Redirect
Date: Thu, 30 Apr 2015 19:41:53 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.39-0+deb7u2
Location: http://www.greenpeace-energy.de/index.html
Content-Type: text/html; charset=UTF-8

reedy@ubuntu64-shell-esxi:~$ curl -I https://www.greenpeace-energy.de
HTTP/1.1 307 Temporary Redirect
Date: Thu, 30 Apr 2015 19:42:03 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.39-0+deb7u2
Location: http://www.greenpeace-energy.de/index.html
Content-Type: text/html; charset=UTF-8

reedy@ubuntu64-shell-esxi:~$ curl -I https://greenpeace-energy.de
HTTP/1.1 301 Moved Permanently
Date: Thu, 30 Apr 2015 19:42:10 GMT
Server: Apache/2.2.22 (Debian)
Location: http://www.greenpeace-energy.de/
Content-Type: text/html; charset=iso-8859-1

reedy@ubuntu64-shell-esxi:~$
```

**Comment by julianladisch** [comment]
This is the result when activating the ruleset:

http://greenpeace-energy.de/
HTTP/1.1 301 Moved Permanently
http://www.greenpeace-energy.de/
https-everywhere changes to
https://www.greenpeace-energy.de/
HTTP/1.1 307 Temporary Redirect
http://www.greenpeace-energy.de/index.html
https-everywhere changes to
https://www.greenpeace-energy.de/index.html
This page loads correctly.

https://greenpeace-energy.de
HTTP/1.1 301 Moved Permanently
http://www.greenpeace-energy.de/
https-everywhere (see above)

All four URLs you tried result in the correctly loading page https://www.greenpeace-energy.de/index.html

The rule adding www avoids another 301 redirect.

Please explain which URL doesn't work for you or what problem you would like to have fixed.

**Comment by reedy** [comment]
```
reedy@ubuntu64-shell-esxi:~$ curl -I https://www.greenpeace-energy.de
HTTP/1.1 307 Temporary Redirect
Date: Thu, 30 Apr 2015 19:42:03 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.39-0+deb7u2
Location: http://www.greenpeace-energy.de/index.html
Content-Type: text/html; charset=UTF-8

reedy@ubuntu64-shell-esxi:~$ curl -I https://greenpeace-energy.de
HTTP/1.1 301 Moved Permanently
Date: Thu, 30 Apr 2015 19:42:10 GMT
Server: Apache/2.2.22 (Debian)
Location: http://www.greenpeace-energy.de/
Content-Type: text/html; charset=iso-8859-1

reedy@ubuntu64-shell-esxi:~$
```

In both of those rules, asking for the HTTPS versions of the pages result in the server 301 redirecting them back to their HTTP equivalents

**Comment by julianladisch** [comment]
I cannot reproduce any loop.

https://www.greenpeace-energy.de gets redirected to http://www.greenpeace-energy.de/index.html , but the ruleset changes this to https://www.greenpeace-energy.de/index.html , and there isn't any redirect of this index.html:

    > curl -I https://www.greenpeace-energy.de/index.html
    HTTP/1.1 200 OK
    Date: Fri, 01 May 2015 21:40:27 GMT
    Server: Apache/2.2.22 (Debian)
    X-Powered-By: PHP/5.4.39-0+deb7u2
    Cache-Control: private
    Content-Length: 45720
    Content-Type: text/html; charset=utf-8

The ruleset rewrites your second example https://greenpeace-energy.de to https://www.greenpeace-energy.de , so it actually fetches the same URL as your first example.

Please explain how to reproduce the loop, or what scenario you would like to have anticipated.

**Comment by reedy** [comment]
Ah, I didn't notice that it doesn't redirect when it's on the index.html

Quirky setup on the server it seems

```
reedy@ko-kra:~$ curl -I -L https://www.greenpeace-energy.de/
HTTP/1.1 307 Temporary Redirect
Date: Sat, 02 May 2015 01:14:38 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.39-0+deb7u2
Location: http://www.greenpeace-energy.de/index.html
Content-Type: text/html; charset=UTF-8

HTTP/1.1 200 OK
Date: Sat, 02 May 2015 01:14:39 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.39-0+deb7u2
Cache-Control: private
Content-Length: 40420
Content-Type: text/html; charset=utf-8
```

**Pull request merged**
