### PR TITLE
Rules: Mibbit (add wiki.mibbit.com) (+tests)

### PR DESCRIPTION
**Pull request by Havvy**

### CODE REVIEW

**Comment by reedy** [comment]
Test failure is unrelated, my fault, sorry

**Comment by Havvy** [comment]
I was expecting a test failure [I have no clue what I'm doing....], but an unrelated one not so much.

Is it possible to have Travis CI retry a build?

**Comment by reedy** [comment]
It should be redoing it now. Though, I'm not sure if your commit needs rebasing first, or if this will work. Will see what happens in a few minutes

**Comment by reedy** [comment]
Looks like they're passing now

**Pull request merged**
