### PR TITLE
Refactor/Breakdown of Background JS

### PR DESCRIPTION
**Pull request by zoracon**
Taken from PR: #18896

First attempt breaking down this file to accomplish:

- Writing in more documentation via jsDoc
- Making the code more readable
- Moving utility code into modules
- Making the code easier to migrate to potential MV3 port (#17268)

Since this is the "Brownfield" Branch for Javascript. Coordinating what this can look like "live" with a staging percentage group. I think Chrome has this capability, but still researching. If that can't be done, I will ask in the mean time that maintainers and other volunteers test this branch out before we merge into master.

### CODE REVIEW

**Comment by pipboy96** [comment]
Greenfield branch is meant for a complete rewrite from scratch. This is still a brownfield code, but good job, this is still direly needed.

**Comment by zoracon** [comment]
> Greenfield branch is meant for a complete rewrite from scratch. This is still a brownfield code, but good job, this is still direly needed.

I see my lack of sleep got to me and I switched the two terms. I will change the name of the branch :)

**Comment by pipboy96** [comment]
@zoracon Theoretically, you can make the testing version log all errors and send them to EFF in encrypted form (for example OpenPGP). What do you think about this idea? I would like to try implementing this if you think it's a good idea. On the downsides, it may require changing our privacy policy and would need us to implement an opt-out, and also I think it would be good to allow the user to view what exactly gets sent.

**Comment by zoracon** [comment]
Sorry for the move around, the usual way of being able to push a new branch name isn't taking to remote at the moment. PR moved here with updated commit: https://github.com/EFForg/https-everywhere/pull/19737

**Pull request closed without merging**
