### PR TITLE
Create Mixtape.moe.xml

### PR DESCRIPTION
**Pull request by koops76**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
https://hstspreload.com/api/v1/status/mixtape.moe
This domain is already in the preload list

**Comment by koops76** [comment]
@gloomy-ghost `Forbidden`

**Comment by koops76** [comment]
@gloomy-ghost Why did it pass `preloaded` test

**Comment by gloomy-ghost** [comment]
CI checks rulesets against the release version of preload list, which is updated slower than the preload list in central branch.

**Pull request closed without merging**
