### PR TITLE
[Rdio.com] Update default_off reason

### LINKED ISSUE #1746: Rdio.com keeps logging out on Chrome on Linux with the extension
The https://rdio.com with the https everywhere version keeps logging out. The login is also not saved. The http version works fine.

### PR DESCRIPTION
**Pull request by Bisaloo**
fix #1746

### CODE REVIEW

**Comment by jeremyn** [comment]
I think we can delete this ruleset entirely.

**Comment by jeremyn** [comment]
Do you mind if I change the commit message name to `Delete Rdio.xml (#14949)`?

**Comment by Bisaloo** [comment]
No, it's fine, you can change it.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
