### PR TITLE
DRY out loading of rulesets, make everything parsed through addFromJson

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by pipboy96** [comment]
🎉

**Comment by pipboy96** [comment]
@Hainish Do you have Keybase?

**Comment by Hainish** [comment]
@pipboy96 I have an account but I don't have the software set up. You can email me if you want to reach out, contact info and public key is available at https://www.eff.org/about/staff/william-budington

**Comment by pipboy96** [comment]
@Hainish Well, GPG+email isn't exactly low latency or fool-proof communication method. I can use it for now though.

**Comment by cschanaj** [comment]
For future reference: `addFromXML` is only used when the debug ruleset is used.

**Pull request merged**
