### PR TITLE
Updating lib-wasm library

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by pipboy96** [comment]
@Hainish Should I try reproducing?

**Comment by Hainish** [comment]
@pipboy96 only if you want, the tests are in place in the lib-wasm library and travis has reproduced.

**Comment by pipboy96** [comment]
@Hainish So reproducing is now automatic? Cool. I will reproduce anyway and post the result though.

**Comment by pipboy96** [comment]
@Hainish Reproduced!

**Pull request merged**
