### PR TITLE
[press-anime-nenkan.com] New ruleset

### PR DESCRIPTION
**Pull request by press-git**
For more user privacy and security we wish record our public website to https-everywhere public list

thank you in advance for your work in this privacy tool

### CODE REVIEW

**Comment by J0WI** [comment]
Since this host already supports preloaded HSTS, there is no need to include it also in HTTPS Everywhere. The preloaded HSTS feature is much more powerful.

Thanks anyway for submitting this rule!

**Comment by press-git** [comment]
Thanks for your response

In Tor HSTS Preloading is not apply many week after others (Chrome, Firefox, ...) whereas HTTPS Everywhere is natively used. It creates a rift security in HSTS preload without HTTPS Everywhere rules. 

SSL Lab test with this host : (HSTS preload is not updated in Thor browser, after six week configure HSTS preload)
https://www.ssllabs.com/ssltest/analyze.html?d=press-anime-nenkan.com&s=2001%3a41d0%3a2%3a7bba%3a0%3a0%3a0%3a1&latest

Please consider this reason for add rule for this host and other, additional at HTST Preload, for more user security.

**Comment by J0WI** [comment]
Not that the reference on SSL Labs is outdated and that HTTPS Everywhere is also not updated regularly.
A short test an Tor Browser Bundle loaded press-anime-nenkan.com over https on my initial request. So it seems to be already included.

**Comment by press-git** [comment]
Thanks for your response

How do you see that ? When I load the host on the tor browser the failover to https is longuer than to firefox. Unfortunately i have no other tool than SSL Labs for check this preload in Tor browser.

I am much interested to discover new method for check SSL hosts configuration. Thanks for the time you give of our interest in communications security.

**Comment by J0WI** [comment]
You can verify on Tor by the following steps:
1. Download a fresh Tor Browser Bundle
2. Disable HTTPS Everywhere
3. Open Tor and open Developer > Network
4. Navigate to http://press-anime-nenkan.com (make sure it's http, not https)
5. You will see that the first request Tor does was https
6. You can verify this by browsing to a site like http://youtube.com (again NOT https) and you will see that the browser connect over http and gets a https redirect from the server

When you click on the lock icon on the network monitor, you will get some more security indicators. On the Headers Tab you also see, that you are serving the preloaded HSTS header.

See also https://github.com/ssllabs/ssllabs-scan/issues/317 to track the issue on SSL Labs.

**Pull request closed without merging**
