### PR TITLE
Changes corresponding to the changes in the lib-wasm submodule

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by pipboy96** [comment]
Is this just renaming the library?

**Comment by Hainish** [comment]
@pipboy96 this separates the WASM library from a new generalized core library which is abstracted from any WASM specifics.

Please go ahead and do `git submodule update --init --recursive` and re-build the docker container and build the `.wasm` file again to verify.

**Comment by Hainish** [comment]
@pipboy96 feel free to re-check whenever you have a chance.  I'd like to include a test in the https://github.com/EFForg/https-everywhere-lib-wasm repo which checks if the build hash is the same as expected.  I've assigned this to myself: https://github.com/EFForg/https-everywhere-lib-wasm/issues/2

**Comment by pipboy96** [comment]
@Hainish I can right now, sry for delay.

**Comment by pipboy96** [comment]
@Hainish

### ✅ Successfully reproduced!

<details>
<summary>🔒 <b>GPG-signed statement</b></summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I, pipboy96 (pipboy96@protonmail.com), hereby testify that a file called https_everywhere_lib_bg.wasm with SHA-256 hash of 73b09852436067ad1f13357d4c2d0dff9a3d9c7ac0932e7396ed3499483d677d and size of 93394 bytes fully corresponds to a Git commit with hash a616064ac86244c522a8088086d8821987f29fd6 and was successfully reproduced by me from its source code.
-----BEGIN PGP SIGNATURE-----

iI4EARYIADYWIQROV8sHuKtZUjpKQXlrXPDIQKF3dAUCXRK7PxgccGlwYm95OTZA
cHJvdG9ubWFpbC5jb20ACgkQa1zwyEChd3Q4ggEA1jblFMejyd2PwVWAv6M/Uvju
Y3qDweQvAwJGHMMh9H8A/3pAvxrK2alw/tdZIvIWARBEtkehg4ghw9xNP7sQUFAL
=bIBn
-----END PGP SIGNATURE-----
```

</summary>

**Pull request merged**
