### PR TITLE
vulkan-casino.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by J0WI** [comment]
How are all these hosts related?
It seems that they don't belong all to the same portal.

**Comment by galeksandrp** [comment]
Seems yes, they only sharing same trademark.

Should I split it to multiple files?

**Comment by J0WI** [comment]
For them who belongs to the same content/portal I'm okay with one file. Other may be separated and linked with comments if they are related.

**Comment by J0WI** [comment]
@galeksandrp are you interested in continuing here?

**Pull request closed without merging**
