### PR TITLE
Update Lifehacker.com.xml

### PR DESCRIPTION
**Pull request by jeremyn**
This pull request partially resolves issue #3069.

### CODE REVIEW

**Comment by J0WI** [comment]
It seems that every user gets his own subdomain on this network. So we should document this and use a wildcard.
Our code style also requires tabs instead of spaces.

**Comment by jeremyn** [comment]
I've made updates to the ruleset and squashed it into one commit.

I'm having trouble with `securecookie`. Note it needs to catch all of `lifehacker.com`, `.lifehacker.com`, `skillet.lifehacker.com`, `.skillet.lifehacker.com` etc. With the very general configuration in my pending change, on https://lifehacker.com it's missing `lifehacker.com > __k_iut`. I've also tried to be more specific:

```xml
	<securecookie host="^\.?lifehacker.com$" name=".+" />
	<securecookie host="^\.?\w+\.lifehacker.com$" name=".+" />
```

but it's still missing `__k_iut`. Do you have any suggestions?

**Comment by J0WI** [comment]
No idea about the cookie issue. Is this a blocker?
Rule lgtm.

**Comment by jeremyn** [comment]
Not a blocker for me, go ahead and merge, thanks.

**Pull request merged**
