### PR TITLE
support unprefixed box-sizing

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Should we still support Firefox <29 (removing the prefix fallback)?

**Comment by J0WI** [comment]
*ping* @fuglede

**Comment by semenko** [comment]
I don't quite understand this -- does `box-sizing: border-box` fix a visual issue for you?

**Comment by J0WI** [comment]
I have no idea why we use box-sizing, but the moz prefix is deprecated.

**Comment by semenko** [comment]
Oh, sure, reasonable. :+1:

**Pull request merged**
