### PR TITLE
[FMLife.com] Default_off ruleset

### LINKED ISSUE #14925: HTTPS on fmylife.com broken
Type: ruleset issue

Domain: fmylife.com

A few months ago HTTPS on http://www.fmylife.com stopped working. It now just shows various HTTP error codes on a Cloudflare error page, see https://www.fmylife.com. I don't know why, but they still didn't fix it, so I suggest to disable the rule for the site.

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #14925

### CODE REVIEW

**Comment by jeremyn** [comment]
Can you please list out the problems with each of the four sites in the top comment? I get:

* https://fmylife.com : HTTP 521
* https://www.fmylife.com : HTTP 521
* https://cdn6.fmylife.com : HTTP 504
* https://media.fmylife.com : HTTP 504

**Comment by Bisaloo** [comment]
How do you see the formatting here?

**Comment by jeremyn** [comment]
How about this?

```xml
<!--
	For other Beta & Cie coverage, see Beta-and-Cie.xml.

	03.2018: all included subdomains fail.

	HTTP 504:
		cdn6.fmylife.com
		cdn7.fmylife.com
		media.fmylife.com

	HTTP 521:
		fmylife.com
		www.fmylife.com

-->
```

(Sublist3r only shows `cdn6` and `cdn7` as matching `cdn\d`.)

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
