### PR TITLE
Add www.lloydsbank.com

### PR DESCRIPTION
**Pull request by alexmuller**
The certificate doesn't support the bare domain.

### CODE REVIEW

**Comment by anand-bhat** [comment]
You can force the non-www domain to www with something like this:

	<target host="lloydsbank.com" />
	<target host="www.lloydsbank.com" />

	<rule from="^http://(?:www\.)?lloydsbank\.com/"
		to="https://www.lloydsbank.com/" />

**Comment by semenko** [comment]
Or simply exclude the bare domain, since we don't want to prevent the site owner from using barenames in the future.

**Comment by alexmuller** [comment]
I think this'll work as is, only the `www` subdomain is included as a target.

**Comment by semenko** [comment]
Fine by me. Thanks!

**Pull request merged**
