### PR TITLE
Npm audit trivialize cdn rules scripts

### PR DESCRIPTION
**Pull request by cschanaj**

### CODE REVIEW

**Comment by pipboy96** [comment]
Can you split the code changes and the ruleset changes?

**Comment by cschanaj** [comment]
@pipboy96 changes made, thanks.

**Comment by cschanaj** [comment]
@Hainish the trivialize cdn rules script is vulnerable as per npm audit, would you merge this?

**Comment by pipboy96** [comment]
@zoracon Please review, this issue is security-critical!

**Pull request merged**
