### PR TITLE
Add ruleset for DidierStevens.com

### PR DESCRIPTION
**Pull request by wesinator**

### CODE REVIEW

**Comment by pipboy96** [comment]
Can you enumerate all subdomains?

**Comment by wesinator** [comment]
> See also `workshop.didierstevens.com`

does not have TLS active. 
`curl: (7) Failed to connect to workshop.didierstevens.com port 443: Connection timed out`

**Comment by J0WI** [comment]
Please document it as described here:
https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
