### PR TITLE
Remove wild-card-in-the-middle check in rules.js

### PR DESCRIPTION
**Pull request by zoracon**
Related to removing wildcard in the middle support #4369
Related #12319

### CODE REVIEW

**Comment by Bisaloo** [comment]
I'm not really familiar with node but wouldn't this break right wildcards as well? 

We still have a couple of right wildcards in rulesets such as [`Google.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.xml). We can remove them by fixing #13682 first.

**Comment by cschanaj** [comment]
> 
> 
> I'm not really familiar with node but wouldn't this break right wildcards as well?
> 
> We still have a couple of right wildcards in rulesets such as [`Google.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.xml). We can remove them by fixing #13682 first.

I agree with @Bisaloo that it might break right-wildcards. We need a standalone check for the right-wildcards if we want to preserve them. IMHO fixing #13682 is a better option though.

AFAIK, this might also break left wildcards such that `www.asset.example.com` will not be matched by `*.asset.example.com` but `*.example.com`. I think this can be fixed by adjusting the starting index in the lower for-loop.

**Comment by zoracon** [comment]
I'll test with wild cards on the right. it likely breaks those looking at the logic. There's logic still looking through the left below the deleted logic though. I'll close this for now if this does break those on the right.

**Comment by zoracon** [comment]
Looks like this does in fact break the ones on the right, closing for now.

**Pull request closed without merging**
