### PR TITLE
Update gimp.org.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
add wiki.gimp.org

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] The change to `Sina.xml` should go in a different pull request.

**Comment by jeremyn** [comment]
Thanks. Please make these changes to do a complete update for this ruleset:

Note as `Invalid certificate` in a [top comment](https://github.com/EFForg/https-everywhere/search?utf8=%E2%9C%93&q=problematic):
- [ ] https://ftp.gimp.org
- [ ] https://gui.gimp.org
- [ ] https://irc.eu.gimp.org
- [ ] https://irc.gimp.org
- [ ] https://registry.gimp.org

Note as `Refused` in the top comment:
- [ ] https://pippin.gimp.org
- [ ] https://www.it.gimp.org

Also:
- [ ] Add a `securecookie` tag between the `target`s and `rule`: `<securecookie host=".+" name=".+" />`
- [ ] Move the `www.gimp.org` target directly under the `gimp.org` target.
- [ ] The change to `Sina.xml` should go in a different pull request.

**Comment by gloomy-ghost** [comment]
#6765

**Comment by jeremyn** [comment]
Looks good, thanks. One last thing: we like to [squash-and-merge](https://help.github.com/articles/about-pull-request-merges/) commits in pull requests, which means we combine all the commits into one commit in your name. Is that all right with you?

**Comment by gloomy-ghost** [comment]
Sure, that's all right.

Thanks

**Comment by jeremyn** [comment]
Thanks again, merged.

**Pull request merged**
