### PR TITLE
Update aastocks.com.xml, add exclusion, fix #14275

### LINKED ISSUE #14275: Breaks aastock.com
Type: ruleset issue
Domain: aastock.com

Some internal pages are broken, eg.:
https://www.aastocks.com/en/stocks/quote/dynamic-chart.aspx?symbol=00005  (charts doesn't load, logging showed on devtools)

I also contacted the site supports, they said the site do not support HTTPS.

### PR DESCRIPTION
**Pull request by cschanaj**
Video thumbnails and images are broken over HTTPS

### CODE REVIEW

**Comment by Bisaloo** [comment]
Did you test it? It doesn't seem to fix the videos for me

**Comment by cschanaj** [comment]
The rulesets worked for me while visiting http://aastocks.com/aatv/; may I know which page you encounter the issues?



P.S. I loaded the new ruleset from the debugging rulesets page

**Comment by Bisaloo** [comment]
http://aastocks.com/aatv/ as well. Weird...Let me see if I can find out what's wrong.

**Comment by cschanaj** [comment]
I updated my comment in https://github.com/EFForg/https-everywhere/pull/16370#issuecomment-415698149; the old rules rewrite http://www.aastocks.com/aatv/ to https; btw it seem that ^ recently supported https and was not covered; so to reproduce the bug you need to visit `www` version

**Comment by Bisaloo** [comment]
Looks like a CORS issue

screenshot from 2018-08-24 11-14-36
screenshot from 2018-08-24 11-10-49

**Comment by cschanaj** [comment]
I got some CORS issues on Google Chrome as well, but apparently they don't break the page.. Strange..

Google Chrome: Version 68.0.3440.106 (Official Build) (64-bit)

screenshot_2018-08-24_17-26-50

screenshot_2018-08-24_17-27-04

**Comment by Bisaloo** [comment]
Well, it doesn't work for me even when HTTPS-Everywhere is disabled. I will try to find another computer to test it.

Can you also fix #14275 while we're at it?

**Comment by Bisaloo** [comment]
Hum, it works now. I'm not entirely sure why. Maybe because I updated chromium?

**Comment by Bisaloo** [comment]
Can you also verify that you can play a video *in full*? It always stops at some point for me but that's probably just a network issue.

**Comment by cschanaj** [comment]
> Hum, it works now. I'm not entirely sure why. Maybe because I updated chromium?

Neither do I, but I guess this is a likely reason. 

> Can you also verify that you can play a video in full?

Yes, I can play the video in full on both Firefox and Google Chrome

**Comment by cschanaj** [comment]
@Bisaloo I think #14275 is fixed in 9a05b7a

cc @Hainish I think the labeller is crashed, this is supposed to be the `top-1k`

**Comment by Hainish** [comment]
Thanks @Bisaloo, it should be running now.

**Pull request merged**
