### PR TITLE
[RedHat.com] Update and reactivate ruleset

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by koops76** [comment]
partner.redhat.com returns 404 over HTTPS, please remove the target and add it to nonfunctional domains. I sent a [pull request](https://github.com/Bisaloo/https-everywhere/pull/5) to your fork.

**Comment by Bisaloo** [comment]
@J0WI, that's strange, I can reproduce by visiting http://partner.redhat.com with HTTPS-Everywhere enabled. I'm using FF 54.0.

**Comment by Bisaloo** [comment]
Okay, I am not sure what is going on but:

- on your first visit, http://partner.redhat.com/ will `404`.
- on subsequent visits, it redirects to https://redhat.secure.force.com/partner/PartnerAccess just fine.

**Comment by koops76** [comment]
Maybe just add this redirect to the ruleset?

**Comment by Bisaloo** [comment]
I'd rather not. It's probably not the safest idea to blindly add a rewrite rule when we are not fully understanding what is going on.

For example, this could the sign that they are in the process of updating their website and a complicated rewrite rule could break the website in the next couple of days.

**Comment by koops76** [comment]
@Bisaloo First it redirects to https://www.redhat.com/wapps/sfconnector/partner/login.html which 404s, but the next time it redirects to redhat.secure.force.com

**Comment by J0WI** [comment]
@Bisaloo is this now ready to merge?

**Comment by Bisaloo** [comment]
Yes, the issue I had got fixed server side.

**Pull request merged**
