### PR TITLE
Ligatus:

### PR DESCRIPTION
**Pull request by numismatika**
- add cb,d2,i,trk.helios subdomains
- convert to current style guide

### CODE REVIEW

**Comment by Roman3349** [comment]
https://(www.)ligatus.com/ Works for me.

**Comment by numismatika** [comment]
indeed the country specific domains work now.
I adjusted the rule for this

**Comment by J0WI** [comment]
See also:
directads2.ligatus.com
ms.ligatus.com
analysis.ligatus.com
r.ligatus.com
h.ligatus.com
reporting.ligatus.com

**Comment by numismatika** [comment]
ms was already in.

**Comment by J0WI** [comment]
Please fix the errors exposed by Travis.

**Comment by numismatika** [comment]
Checks pass now @J0WI

**Pull request merged**
