### PR TITLE
torrent related sites

### PR DESCRIPTION
**Pull request by galeksandrp**
- Exceptions
	- PimpMyuTorrent
	- DuckieTorrent
	- DuckieTV
- Deletes
	- torque.bittorrent.com

### CODE REVIEW

**Comment by J0WI** [comment]
The GitHub Part LGTM, but please have a look at the subdomains of bittorrent.com. The comments are not up to date and some of them may work now.

**Comment by J0WI** [comment]
Okay, I can't merge it with those unrelated changes in the Python scripts.
Could you split this up in multiple PRs?

**Comment by galeksandrp** [comment]
Split Python scripts into #4923

**Comment by Hainish** [comment]
Superceded by https://github.com/EFForg/https-everywhere/pull/4748 - thank you!

**Pull request closed without merging**
