### PR TITLE
Disable Politiken.dk.

### PR DESCRIPTION
**Pull request by jsha**
Per report in IRC, rule breaks streaming video.

Possible fix at https://github.com/EFForg/https-everywhere/pull/1170,
but not tested.

cc @cooperq @diracdeltas for code review.

### CODE REVIEW

**Comment by jsha** [comment]
Merging as TBR (To Be Reviewed).

**Comment by cooperq** [comment]
LGTM

**Comment by fuglede** [comment]
I revamped the rule in #1170, including only the parts where it's clear what it does. Tried to get in touch with the original author without success, unfortunately.

Anyway, my guess is that the site is probably either the most popular or second most popular Danish news site among https-e users so having any kind of covering would be very beneficial.

**Comment by jsha** [comment]
Thanks! Sorry I missed that pull request for so long. Can you merge latest master and confirm that it still fixes streaming video?

**Comment by fuglede** [comment]
No problem; I could have certainly timed that better.

But good thing you asked: they've changed their design recently and it seems like the URL pattern for pages with video streams have changed so that the old fix no longer applies (or I might have simply missed those before). Roughly: before, video pages were all called politiken.dk/tv/..., but now some individual articles also include videos. On the bottom line, the exclusion pattern from my branch fixes the issue on many, but not quite all pages. Seems impossible to fix on mixed content-skeptical platforms though. I'll try to get in touch with a dev and get back.

**Pull request merged**
