### PR TITLE
Update srg-ssr.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
@jeremyn this is the only PR blocking #8833. Can we get rid of the downgrade here?

**Comment by ivysrono** [comment]
Maybe you can empty the downgrade-whitelist.txt

**Comment by jeremyn** [comment]
https://ws.srf.ch (examples: https://ws.srf.ch/cr/zNxFwFy?iframe=true , https://ws.srf.ch/cr/zN5QNP9?iframe=true ) look okay to me, except for some mixed content blocking that seems harmless.

**Comment by J0WI** [comment]
I can confirm that the mixed content is trivial. Is there anything else preventing this from merge?

**Comment by jeremyn** [comment]
@J0WI I'm not sure if you're asking me or @ivysrono , but I haven't reviewed this beyond the one comment I made above.

**Comment by ivysrono** [comment]
@J0WI is asking you @jeremyn

**Comment by ivysrono** [comment]
I will not have time to do these complex rules after this week.

**Comment by J0WI** [comment]
@jeremyn can we get rid of this last downgrade for the next release?

**Comment by jeremyn** [comment]
@J0WI Are you asking me to do a general review of this pull request or are you asking me something more specific?

**Comment by J0WI** [comment]
I'm asking you for a review to resolve #8833.

**Comment by jeremyn** [comment]
I get `Secure connection failed` but these are listed as `Refused`:
- [ ] https://360langstrasse.srf.ch
- [ ] https://seidenstrasse.srf.ch

This works for me but is listed as `HTTP redirect`:
- [ ] https://www.rtr.ch ([here](https://github.com/J0WI/https-everywhere/blob/1eac30420fb3ff3ea49ea52583a7b0545f87423d/src/chrome/content/rules/srg-ssr.xml#L31))

I get `HTTP redirect` but this has a `target`:
- [ ] https://mediaww.rsi.ch

These work for me but they have `HTTP redirect` `exclusions`:
- [ ] https://www.srf.ch/play/ ([here](https://github.com/J0WI/https-everywhere/blob/1eac30420fb3ff3ea49ea52583a7b0545f87423d/src/chrome/content/rules/srg-ssr.xml#L90))
- [ ] https://m.srf.ch/play/ ([here](https://github.com/J0WI/https-everywhere/blob/1eac30420fb3ff3ea49ea52583a7b0545f87423d/src/chrome/content/rules/srg-ssr.xml#L91))

Also:
- [ ] https://www.swissinfo.ch/fre and  https://www.swissinfo.ch/eng work for me but there are a bunch of `exclusion`s and `test`s [here](https://github.com/J0WI/https-everywhere/blob/1eac30420fb3ff3ea49ea52583a7b0545f87423d/src/chrome/content/rules/srg-ssr.xml#L96-L116), and `(www\.)?swissinfo.ch` is listed as `HTTP redirect` [here](https://github.com/J0WI/https-everywhere/blob/1eac30420fb3ff3ea49ea52583a7b0545f87423d/src/chrome/content/rules/srg-ssr.xml#L33). Is there anything wrong with these URLs?
- [ ] There's a `downgrade` comment in `Craigslist.org.xml` [here](https://github.com/EFForg/https-everywhere/blob/0730806c368676d92c1947d4855ac91fb06f5be9/src/chrome/content/rules/Craigslist.org.xml#L9-L14) that I guess should be removed, since there is no `downgrade` in that ruleset.

**Comment by J0WI** [comment]
Great, therefore we can also remove those exclusions.
See #9791 for Craigslist.org.xml

**Comment by J0WI** [comment]
Thanks!

**Pull request merged**
