### PR TITLE
Add AntennaPod.org (#18042)

### LINKED ISSUE #18042: Add https://antennapod.org
I'm sure this would be easier if your markup were anything like what I've seen on GitHub before. 🤷‍♂️

Specifically, you should have a method within the addon to report websites that can (and will) load with HTTP, but that have valid SSL certificates.

I'm really not sure what will happen with this issue, given the puzzling markup.

### PR DESCRIPTION
**Pull request by pipboy96**
Closes #18042.

### CODE REVIEW

**Comment by pipboy96** [comment]
@Bisaloo Done.

**Comment by Bisaloo** [comment]
Can you add a top comment explaning this please?

**Comment by pipboy96** [comment]
@Bisaloo Done.

**Comment by Bisaloo** [comment]
Thanks

**Pull request merged**
