### PR TITLE
[taxact.com] New ruleset

### PR DESCRIPTION
**Pull request by youdly**

### CODE REVIEW

**Comment by J0WI** [comment]
I found some more non-functional subdomains:
proadvance.taxact.com
danica.taxact.com
bizadvance.taxact.com

**Comment by youdly** [comment]
Updated comment.

**Comment by J0WI** [comment]
Sorry, there are two broken ones I didn't catch before:
m.taxact.com
ef.taxact.com

Please do not overwrite previous commits, so I can review the changes faster.

**Comment by youdly** [comment]
Added comment.

[fuglede](https://github.com/EFForg/https-everywhere/pull/3037#issuecomment-149004004) previously told me to squash the commits.

**Comment by J0WI** [comment]
Okay, thanks!

**Pull request merged**
