### PR TITLE
#9576

### PR DESCRIPTION
**Pull request by J0WI**
See #9576

### CODE REVIEW

**Comment by J0WI** [comment]
Maybe we can re-enable the securecookie rule together with `away.vk.com`, see https://github.com/EFForg/https-everywhere/issues/9576#issuecomment-295256665

**Comment by Hainish** [comment]
I don't have an account and can't sign up for one without a phone number, so I can't double-check on this.

@jeremyn do you have a VK account?

I'm willing to merge without a review for the sake of expediency, since this comes from a trusted user and is a top-100.  But first I'd like to see if I can find someone in the office here that I can test this account with.  In the future it would be nice to allow a day or so before flagging urgent ruleset bugs.

**Comment by jeremyn** [comment]
I don't have a VK account.

**Comment by J0WI** [comment]
Just to clarify: I was making these changes based on the feedback in #9576. Since the final fix is just adding a target I don't expect any regressions. The first attempt with exclusions was more risky.

**Pull request merged**
