### PR TITLE
Update www.elcorteingles.es.xml

### PR DESCRIPTION
**Pull request by I-have-50-open-PRs-to-HTTPS-EVERYWHERE**

### CODE REVIEW

**Comment by J0WI** [comment]
Would you also like to search for subdomains here? Please also add `^`.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@J0WI Added

**Comment by J0WI** [comment]
Please have a look at Travis, there is a mismatch and an incomplete cert chain.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
sorry for that @J0WI should pass travis now

**Pull request merged**
