### PR TITLE
Create qiniu.com.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Comment by ivysrono** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Qbox.me.xml

**Comment by ivysrono** [comment]
kb/support Unable to connect in Tor.

**Comment by gloomy-ghost** [comment]
It's just general time out

**Comment by jeremyn** [comment]
I disagree with the wildcards for `*.qbox.me` and `*.qnssl.com` for the usual reasons.

**Comment by gloomy-ghost** [comment]
It's a https CDN domain, likes a248.e.akamai.net

#7281 is still pending though.

**Comment by jeremyn** [comment]
Why does that matter for it being a wildcard?

**Comment by gloomy-ghost** [comment]
There are about half a million subdomains according to the number of Qiniu's customers. They all work for file distribution, and https://dn-xxx.qbox.com isn't a page that a regular user will be visiting.

**Pull request closed without merging**
