### PR TITLE
Add ESLint Travis task (WebExtensions)

### PR DESCRIPTION
**Pull request by koops76**
Like #10897 but for WebExtensions! 😎

### CODE REVIEW

**Comment by koops76** [comment]
ping @Hainish

**Comment by yfdyh000** [comment]
@koops76 No "webextensions" in "env"?

**Comment by koops76** [comment]
@yfdyh000 Fixed. Also fixed for `master` in #11190.

**Comment by Hainish** [comment]
It is unnecessary to add this separately to the [`webextensions`](https://github.com/EFForg/https-everywhere/tree/webextensions) branch, because

1. The syntax for [`webextensions`](https://github.com/EFForg/https-everywhere/tree/webextensions) should not differ from the syntax for the current Chrome extension in any significant way
2. We already have a `.eslint.json` file in `master`.  Adding this separately (and with different indentation, to note) will cause merge conflicts down the line.  It's better to modify this file in `master` instead.

**Pull request closed without merging**
