### PR TITLE
TotalFreedom Ruleset

### PR DESCRIPTION
**Pull request by zD12**
Redirect http://TotalFreedom.boards.net to https://TotalFreedom.boards.net

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the pull request. This ruleset should really cover all of the `*.boards.net` subdomains, for example see [this Google search](https://www.google.com/#q=site:*.boards.net). Are you interested in doing that?

**Comment by zD12** [comment]
@jeremyn, not exactly possible without inadvertently harming the website itself. 

All '*.boards.net' forums were originally designed for HTTP, not SSL. As a result, forcing all websites to use SSL will break many sites due to mixed traffic (i.e. 'This page is trying to load scripts from unauthenticated sources'). 

Though, if we neglected this (and we shouldn't), you'd want to add:

- *.proboards.com
- *.boards.net
- *.freeforums.net

**Comment by jeremyn** [comment]
Right, we shouldn't actually add a wildcard `*.boards.net`. Wildcards are discouraged by the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md). Instead we should list working domains individually, and note non-working domains as having problems.

**Comment by J0WI** [comment]
I think in the case of "customer subdomains" it's okay to have wildcards. There might be a huge list that change often, so it's impossible for us to maintain.
Let's use a `platform="mixedcontent"` ruleset for the customer domains and a separate ruleset for CDN hosts.

**Comment by jeremyn** [comment]
@J0WI 

> Let's use a `platform="mixedcontent"` ruleset for the customer domains and a separate ruleset for CDN hosts.

For "customer subdomains" I agree that the only likely problem is mixed content blocking, so moving them all into a `platform="mixedcontent"` should be fine.

What do you mean by "CDN hosts" in this example?

**Comment by J0WI** [comment]
Some resources are loaded from the related `storage.proboards.com` host, which supports HTTPS.

**Comment by jeremyn** [comment]
Oh, okay. Yes, any non-customer domains like `storage`, `www` and so on should go into a non-`mixedcontent` ruleset.

**Comment by zoracon** [comment]
The testing environment has been stale for this PR, trying to readjust by open and closing

**Comment by zoracon** [comment]
Ah the original repo is unknown. Apologies for the lag in reviews. If @zD12 Opens back up make sure to ping me for review

**Pull request closed without merging**
