### PR TITLE
rm Vimeo.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
Preloaded
[Chromium](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json#5416), [Firefox](https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#9286), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11910)

HTTPS Header: Strict-Transport-Security: max-age=15552000; includeSubDomains; preload

### CODE REVIEW

**Comment by jeremyn** [comment]
`vimeo.com` is HSTS preloaded but `vimeocdn.com` isn't, so we can't remove this ruleset entirely.

**Comment by gloomy-ghost** [comment]
Σ(っ °Д °;)っ
How did the test pass without any testing URLs?

**Comment by jeremyn** [comment]
I don't know. I submitted issue #7272 for that problem. In the meantime, can you please add three tests for the wildcard?

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
