### PR TITLE
Remove help.yelp.com exclusion

### PR DESCRIPTION
**Pull request by bouk**
Seems to respond correctly now (though it redirects to some random page on yelp)

### CODE REVIEW

**Comment by jeremyn** [comment]
https://help.yelp.com always seems to redirect to the same page at `yelp.com`, and http://help.yelp.com does the same redirect, so that's unusual but is fine for us.

- [ ] Remove the now-unneeded comment `ʰ Desk.com / redirects to http` [here](https://github.com/bouk/https-everywhere/blob/4439f715d9b1a07d84cc36077a1befd80f6912ae/src/chrome/content/rules/Yelp.xml#L17)

**Comment by bouk** [comment]
@jeremyn fixed

**Comment by jeremyn** [comment]
Thanks for the change.

I added one more item to the checklist in https://github.com/EFForg/https-everywhere/pull/13474#issuecomment-341837312, I'm sorry I didn't mention that before.

**Comment by bouk** [comment]
done

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
