### PR TITLE
Add Bank of Scotland

### PR DESCRIPTION
**Pull request by jacobgelling**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Please add targets:
apply.bankofscotland.co.uk
banking.bankofscotland.co.uk
campaign.bankofscotland.co.uk
cbonline.bankofscotland.co.uk
cbstats.bankofscotland.co.uk
cdn.bankofscotland.co.uk
community.bankofscotland.co.uk
du.bankofscotland.co.uk
ep-mobileinsurance-ava.bankofscotland.co.uk
ep-mobileinsurance-urca.bankofscotland.co.uk
secure.form.bankofscotland.co.uk
help.bankofscotland.co.uk
home-insurance.bankofscotland.co.uk
images.bankofscotland.co.uk
isite.bankofscotland.co.uk
logos2-cashback.bankofscotland.co.uk
marketing.bankofscotland.co.uk
www.mycarfinance.bankofscotland.co.uk
online.bankofscotland.co.uk
online-business.bankofscotland.co.uk
request.bankofscotland.co.uk
secure.bankofscotland.co.uk
secure-business.bankofscotland.co.uk

Note as `Refused`:
communityfund.bankofscotland.co.uk

Note as `Timeout`:
bankingbos.bankofscotland.co.uk
bankingboscomm.bankofscotland.co.uk
bankingboscorp.bankofscotland.co.uk
bankingcomm.bankofscotland.co.uk
bankingcorp.bankofscotland.co.uk
decisionswellmade.bankofscotland.co.uk
dsweb03.bankofscotland.co.uk
dsweb04.bankofscotland.co.uk
dsweb07.bankofscotland.co.uk
dsweb08.bankofscotland.co.uk
ep-idaw.bankofscotland.co.uk
ep-scpi.bankofscotland.co.uk
mobile.bankofscotland.co.uk
mound.bankofscotland.co.uk
quicksilver.bankofscotland.co.uk
stag-entrepreneurs.bankofscotland.co.uk
w1.bankofscotland.co.uk
w2.bankofscotland.co.uk

`Invalid certificate`:
secure.budget-tool.bankofscotland.co.uk
business.bankofscotland.co.uk
cbonlineupgrade.bankofscotland.co.uk
www.community.bankofscotland.co.uk
corporate.bankofscotland.co.uk
customer.bankofscotland.co.uk
email.bankofscotland.co.uk
homeinsurance.bankofscotland.co.uk
privatebanking.bankofscotland.co.uk
promotions.bankofscotland.co.uk
resources.bankofscotland.co.uk
toolbox.bankofscotland.co.uk

**Comment by J0WI** [comment]
@jacobgelling see also:
```
cbonline.bankofscotland.co.uk
corporate.bankofscotland.co.uk
decisionswellmade.bankofscotland.co.uk
isite.bankofscotland.co.uk
mycarfinance.bankofscotland.co.uk
www.mycarfinance.bankofscotland.co.uk
online.bankofscotland.co.uk
toolbox.bankofscotland.co.uk
secure.bankofscotland.co.uk

**Comment by jeremyn** [comment]
@jacobgelling Are you still interested in working on this?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @jacobgelling .

**Pull request closed without merging**
