### PR TITLE
Update Pandora.xml

### PR DESCRIPTION
**Pull request by redranamber**
Fixed from #6862

### CODE REVIEW

**Comment by jeremyn** [comment]
Thanks for the ruleset. Some initial comments:

* We strongly prefer that you list subdomains as targets instead of using a wildcard.
* Please indent the ruleset according to our [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md).
* Any list of URLs should be sorted alphabetically starting with the top-level domain and reading left, with `^` and `www` moved to the top. So for example: `^`, `www`, `amp`, `stats`.

**Comment by redranamber** [comment]
Fixed the style but the wildcard is necessary because they store images on unique subdomains.

**Comment by jeremyn** [comment]
Can you give some examples?

**Comment by redranamber** [comment]
https://mediaserver-cont-ch1-1-v4v6.pandora.com/images/public/amz/6/0/8/2/800032806_500W_500H.jpg
https://mediaserver-cont-sv5-3-v4v6.pandora.com/images/public/rovi/albumart/2/2/2/7/093624987222_500W_500H.jpg

**Comment by jeremyn** [comment]
I guessed at the URL scheme and found these URLs by hand using DNS lookup:

https://mediaserver-cont-ch1-1-v4v6.pandora.com
https://mediaserver-cont-ch1-2-v4v6.pandora.com
https://mediaserver-cont-sv3-1-v4v6.pandora.com
https://mediaserver-cont-sv3-2-v4v6.pandora.com
https://mediaserver-cont-sv3-3-v4v6.pandora.com
https://mediaserver-cont-sv5-1-v4v6.pandora.com
https://mediaserver-cont-sv5-2-v4v6.pandora.com
https://mediaserver-cont-sv5-3-v4v6.pandora.com

@redranamber Can you casually browse a little in Pandora and see if you find any `mediaserver` URL that isn't in this list?

@fuglede @J0WI Can either of you think of a way to effectively add a target for `mediaserver-cont-*-v4v6.pandora.com` ?

**Comment by redranamber** [comment]
I also see some coming from https://mediaserver-cont-dc6-2-v4v6.pandora.com and many are also coming from *.p-cdn.com such as http://cont-2.p-cdn.com/images/public/amz/9/2/3/8/781676658329_500W_500H.jpg which appears to be a Pandora domain.

**Comment by redranamber** [comment]
I did a search and found it is http://cont-2.p-cdn.com.ipaddress.com/

**Comment by jeremyn** [comment]
`mediaserver-cont-dc6-2-v4v6.pandora.com` and `cont-2.p-cdn.com` both seem to have guessable number schemes that you could list specifically.

When we list targets specifically, we can check each of them and confirm they're good. If we use wildcards though, then we might break functionality for subdomains we don't know about. Especially for a high traffic site like Pandora, we want to be careful.

**Comment by redranamber** [comment]
I also see
http://t3-2.p-cdn.com/
http://cont-1.p-cdn.com/
http://t2-1.p-cdn.com/
http://t2-2.p-cdn.com/

**Comment by J0WI** [comment]
> @fuglede @J0WI Can either of you think of a way to effectively add a target for mediaserver-cont-*-v4v6.pandora.com ?

No, but you can use a wildcard target and regex with all working hosts in the from to rule. But this also requires test urls.

**Comment by jeremyn** [comment]
@J0WI That's a good idea, thanks.

@redranamber So what that means is that instead of

```xml
<rule from="^http:" to="https:"/>
```

you should do something like

```xml
<rule from="^http://(advertising\.|amp\.|mediaserver-cont-.+-v4v6\.)?pandora\.com" to="https://$1pandora.com"/>
```

Of course you need to add the other subdomains and test it, but that's the general idea.

**Comment by fuglede** [comment]
The unescaped dot will not pass the tests, but you could use either `\d` or just the relevant character classes.

**Comment by jeremyn** [comment]
@fuglede You mean the dot here: `.+`? You probably know, but that's not a period, but rather a regex wildcard.

**Comment by fuglede** [comment]
Yep, but they are not currently allowed; https://github.com/EFForg/https-everywhere/blob/master/utils/trivial-validate.py#L77 (we had a brief discussion on this recently that I might be able to dig up if necessary.)

**Comment by jeremyn** [comment]
I see, thanks. In that case, replace the second rule in my earlier comment with this:

```xml
<rule from="^http://(advertising\.|amp\.|mediaserver-cont-\w{3}-\d{1}-v4v6\.)?pandora\.com" to="https://$1pandora.com"/>
```

**Comment by redranamber** [comment]
It seems the p-cdn.com resources need to be secured also to prevent them from being blocked as mixed content. So this includes an attempt at securing it.

**Comment by jeremyn** [comment]
By the way, recent issue #6875 is a good example of why wildcards are risky.

**Comment by redranamber** [comment]
I think this is a case where it's more likely to have an issue caused by not using a wildcard. I keep finding new subdomains while testing and some of them are being blocked automatically by Firefox as mixed content. Another I just saw is http://audio-ch1-t3-1-v4v6.pandora.com/

**Comment by terrorist96** [comment]
#3069

**Comment by redranamber** [comment]
I think for now the rule should just include the domains I haven't seen any problems with. So i have cut down the rule to just those.

**Comment by jeremyn** [comment]
I think we should really try to include domains like `mediaserver` and `p-cdn.com`. Where are you getting mixed content blocking (MCB)? You shouldn't get MCB loading a `.jpg` for example.

I don't have a Pandora account so I can't help you search for these domains myself, sorry. In fact for that reason I'm probably not the best reviewer for this. @fuglede @J0WI Do either of you have a Pandora account you can use, and if so can you take over here?

**Comment by fuglede** [comment]
> @fuglede @J0WI Do either of you have a Pandora account you can use, and if so can you take over here?

Unfortunately not, no.

**Comment by Hainish** [comment]
I have an account.  LGTM

**Pull request merged**
