### PR TITLE
Update Ars-Technica.xml

### PR DESCRIPTION
**Pull request by terrorist96**
Addresses #4196

### CODE REVIEW

**Comment by terrorist96** [comment]
@J0WI what does `needs test coverage update` mean?

**Comment by J0WI** [comment]
This will fail ruleset tests, see https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md

**Comment by terrorist96** [comment]
Please tell me what to add/remove to fix it. Thanks.

**Comment by J0WI** [comment]
You need to add test urls for every possible expression that matches the rule and at least three examples for wildcards.

**Comment by terrorist96** [comment]
Even for all the existing rules?  How can I find test URLs? Something like this: `https://arstechnica.com/civis/viewtopic.php?f=2&t=1308189&p=30695775#p30695775`? 
And I don't know what you mean by wildcards.

**Comment by J0WI** [comment]
Exactly. Note that the test urls should be as generic as possible and should not contain any errors (e.g. 404).

There is a wildcard target host on https://github.com/EFForg/https-everywhere/pull/4201/files#diff-aa9c3be14dc8df076fc11fd18d4adeabR72
You could also replace this with a list of subdomains as target hosts.

**Comment by terrorist96** [comment]
Here's what I'm trying to accomplish: if I comment on an article from arstechnica.com and someone comments after me, I'll get an email with a link like this
http://arstechnica.com/civis/viewtopic.php?f=2&t=1310747&p=30849471&e=30849471
If I'm not already logged in, this will take me to a page to log in. Https isn't forced for this page and it should be. The default login page (accessed by clicking the login button from the site) ends in civis/ucp.php, which is already covered by the rule, but the link to login that redirects to a specific thread (as obtained from an email notification) ends in civis/viewtopic.php, which doesn't have https forced. So I can't give a generic version of the link; it has to point to a specific thread, like the example I just pasted for the article about the Tesla Model X. If you strip the stuff after viewtopic.php, it will load a 404 page.

**Comment by terrorist96** [comment]
Actually, the generic http://arstechnica.com/civis/ needs https forced too.

**Comment by terrorist96** [comment]
@fuglede I need help getting this merged.

**Comment by terrorist96** [comment]
Not fixed in (Version: 2016.5.10)

**Comment by J0WI** [comment]
Please read our guides carefully:
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md

This ruleset does not comply with our current standards, so it needs to be rewritten.
This means:
- get rid of unneeded wildcards
- remove non-capturing groups
- test coverage
- update documentation

**Comment by jeremyn** [comment]
@J0WI I get what you're saying but this is literally a one-line change, and `Ars-Technica.xml` is [already in the whitelist](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-coverage-whitelist.txt#L438). I think this can be merged after the whitelist hash is updated, although @terrorist96 has deleted their branch so we might need a new pull request. What do you think?

**Comment by Hainish** [comment]
source repo deleted

**Pull request closed without merging**
