### PR TITLE
Add lelux.fi

### PR DESCRIPTION
**Pull request by theel0ja**
can be removed

### CODE REVIEW

**Comment by pipboy96** [comment]
You should use HSTS preloading instead: https://hstspreload.org/

**Comment by pipboy96** [comment]
@theel0ja 
Change

    strict-transport-security: max-age=63072000

to

    strict-transport-security: max-age=63072000; includeSubDomains; preload

Then submit your domain to https://hstspreload.org/.

Then I think this PR should be merged, but once your domain will be preloaded in all browsers, it will be automatically reverted as a part of `hsts-prune` run.

**Comment by pipboy96** [comment]
@theel0ja Also: https://hstspreload.org/?domain=eliasojala.me

**Comment by theel0ja** [comment]
Submitted `lelux.fi` to HSTS Preloading list. Will fix `eliasojala.me` soon.

**Comment by theel0ja** [comment]
However, this subdomain should be excluded:

```
http://tor-exit-ams1.lelux.fi/
```

**Comment by pipboy96** [comment]
@theel0ja Use sslh or HAProxy to share port 443 between Tor and nginx/Caddy.

**Comment by theel0ja** [comment]
Yeah probably I could, but I don't think it's worth it.

**Comment by pipboy96** [comment]
@theel0ja Perhaps move to a dedicated second-level domain?

**Comment by theel0ja** [comment]
Hm. I could do `https://tor-info.lelux.fi/` or something.

However I want that people can access `tor-exit-ams1.lelux.fi` as it's the reverse record of the IP address of that machine.

**Comment by pipboy96** [comment]
@theel0ja Those are subdomains I see that have HTTP servers running:
```
searx.lelux.fi - Found open ports: 443, 80
search.lelux.fi - Found open ports: 443, 80
monitoring.lelux.fi - Found open ports: 443, 80
www.lelux.fi - Found open ports: 443, 80
fi1.lelux.fi - Found open ports: 443, 80
haku.lelux.fi - Found open ports: 443, 80
admin.dns.lelux.fi - Found open ports: 443, 80
git.lelux.fi - Found open ports: 443, 80
wiki.lelux.fi - Found open ports: 443, 80
ipv4.tracker.lelux.fi - Found open ports: 443, 80
status.lelux.fi - Found open ports: 443, 80
```
Are there more?

**Comment by pipboy96** [comment]
It's quite hard to exclude just one domain from the rewrite without enumerating each domain and including all of them but the one that needs to be excluded.

**Comment by pipboy96** [comment]
@theel0ja Kudos for preloading `theel0ja.info`! :+1:

**Comment by theel0ja** [comment]
Can be removed

**Pull request closed without merging**
