### PR TITLE
Update easyicon.net.xml

### PR DESCRIPTION
**Pull request by gloomy-ghost**
MCB Fixed

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] https://www.easyicon.net/vip/ has mixed content blocking for jQuery. I don't know what actual functionality is broken but I don't like breaking jQuery. I think we should keep that `exclusion`. What do you think?

**Comment by gloomy-ghost** [comment]
Well... They fixed https://www.easyicon.net/thank.php which was in my feedback, but left all others behind.

I'll update this thread after these pages are fixed.

**Comment by gloomy-ghost** [comment]
It should be fixed by now, can you check again?

**Comment by jeremyn** [comment]
Looks good, merged.

**Pull request merged**
