### PR TITLE
Create sex169.xml

### PR DESCRIPTION
**Pull request by stlwvikx**

### CODE REVIEW

**Comment by stlwvikx** [comment]
@Hainish @jeremyn @J0WI @gloomy-ghost @ivysrono 
Three months later, could you review?

**Comment by jeremyn** [comment]
Thanks for your contribution, however please don't ping specific people to review specific pull requests unless they are already involved with it.

**Comment by jeremyn** [comment]
@stlwvikx Are you still interested in working on this pull request?

**Comment by jeremyn** [comment]
I'm closing this pull request due to lack of response from @stlwvikx . I've noted `a7s7.com`, `sex169.biz`, `sex169.pw`, `sex169.xyz`, and `video169.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-355315208` in case someone else wants to make pull requests for these domains.

**Pull request closed without merging**
