### PR TITLE
Update xvideos.com.xml

### PR DESCRIPTION
**Pull request by Folant**

### CODE REVIEW

**Comment by jeremyn** [comment]
- [ ] Delete the two [extra `rule`s](https://github.com/Folant/https-everywhere/blob/eda882412e2990f3d6ff5bedada23d0fc4257cba/src/chrome/content/rules/XVideos.com.xml#L49-L52) in `XVideos.com.xml`

**Comment by jeremyn** [comment]
Thanks.

I looked more closely at the original ruleset and noticed `control` and `jp`, which we should keep. I've added them to the checklist. I'm sorry I didn't include these in the checklist the first time.

**Comment by Folant** [comment]
@jeremyn Done.

**Comment by jeremyn** [comment]
Thanks again, merged.

**Pull request merged**
