### PR TITLE
Update PornHub.xml

### PR DESCRIPTION
**Pull request by Folant**
#9353

### CODE REVIEW

**Comment by numismatika** [comment]
did they get rid of the phncdn.com domain completely?

**Comment by Folant** [comment]
No, but it seems that none of them support HTTPS. (Also many URLs I find on HTTP simply can't be retrieved)

**Comment by Folant** [comment]
Added working phncdn.com subdomains and documented others.

**Comment by jeremyn** [comment]
Please make the changes described below.

I've simply stated how these domains should look in the final version. It's implied that you should also remove them from wherever else they might be. So for example, `rtsp.pornhub.com` should be removed from `Timeout` as well as added to `Connection refused`.

Mark as `Connection refused`:
- [ ] https://rtsp.pornhub.com

Mark as `Invalid certificate`:
- [ ] https://i0.cdn2a.image.pornhub.phncdn.com
- [ ] https://i1.cdn2a.image.pornhub.phncdn.com
- [ ] https://cdn1a.limg.pornhub.phncdn.com

Mark as `No working URL known` or add a `test` URL that gets either a 200 or 30X:
- [ ] https://img.pornhub.com
- [ ] https://services.pornhub.com
- [ ] https://stage.pornhub.com
- [ ] https://bd.phncdn.com
- [ ] https://be.phncdn.com
- [ ] https://bi.phncdn.com
- [ ] https://bl.phncdn.com
- [ ] https://bm.phncdn.com
- [ ] https://bm2.phncdn.com
- [ ] https://bv.phncdn.com
- [ ] https://cd.phncdn.com
- [ ] https://cdn1-smallimg.phncdn.com
- [ ] https://cdn1d-static-shared.phncdn.com
- [ ] https://ce.phncdn.com
- [ ] https://ci.phncdn.com
- [ ] https://cl.phncdn.com
- [ ] https://cm.phncdn.com
- [ ] https://cs.phncdn.com
- [ ] https://cv.phncdn.com
- [ ] https://de.phncdn.com
- [ ] https://dl.phncdn.com
- [ ] https://dm.phncdn.com
- [ ] https://dv.phncdn.com
- [ ] https://ssc.phncdn.com

Not in DNS, remove entirely:
- [ ] https://cd.pornhub.phncdn.com
- [ ] https://ce.pornhub.phncdn.com
- [ ] https://cm.pornhub.phncdn.com
- [ ] https://cs.pornhub.phncdn.com
- [ ] https://cv.pornhub.phncdn.com
- [ ] https://cdn2b.download.pornhub.phncdn.com
- [ ] https://cdn2b.mobile2.pornhub.phncdn.com
- [ ] https://staticb.thumbzilla.phncdn.com
- [ ] https://ph-static.phncdn.com
- [ ] https://cdn1.static.pornhub.phncdn.com
- [ ] https://cdn1a.static.pornhub.phncdn.com

Mark as `Redirects to HTTP`:
- [ ] https://cms.pornhub.com

Mark as `Timeout`:
- [ ] https://cdn1.static.youporn.phncdn.com

Add `test`:
- [ ] https://bs.phncdn.com/misc/pdf/pornhub_AdultColoringBook_sample.pdf
- [ ] https://ss.phncdn.com/html5player/videoPlayer/oldFlash/stable/xtube/player.swf

For example a `target` and `test` should go together like this:

```xml
	<target host="bs.phncdn.com"/>
		<test url="http://bs.phncdn.com/misc/pdf/pornhub_AdultColoringBook_sample.pdf" />
```

Also:
- [ ] The `phncdn.com` comments and rules should be moved into a separate `Phncdn.com.xml` file with `ruleset` `name` `phncdn.com`, because these are CDN domains for other sites besides `pornhub.com` domains.

**Comment by jeremyn** [comment]
I've updated https://github.com/EFForg/https-everywhere/pull/9363#issuecomment-307506094 through commit https://github.com/EFForg/https-everywhere/pull/9363/commits/a1cbe39f886b862c695aad5c5a442c2035cbc0a0.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
