### PR TITLE
Update hko.gov.hk.xml to include weather.gov.hk

### PR DESCRIPTION
**Pull request by ipaucek4680**
(This is a re-submission of #18147)
@cschanaj

### CODE REVIEW

**Comment by cschanaj** [comment]
I get a valid (wildcard) certificate using `openssl`, would you include `m.weather.gov.hk` in the ruleset and see if Travis throw an error?

```bash
$ openssl s_client -connect m.weather.gov.hk:443
CONNECTED(00000003)
depth=2 C = HK, O = Hongkong Post, CN = Hongkong Post Root CA 1
verify return:1
depth=1 C = HK, ST = Hong Kong, L = Hong Kong, O = Hongkong Post, CN = Hongkong Post e-Cert CA 1 - 15
verify return:1
depth=0 C = HK, ST = Hong Kong, L = Hong Kong, O = Hong Kong SAR Government, OU = 0002142877, OU = 000000000000000000000000HKO, OU = Hongkong Post e-Cert (Server), OU = Hong Kong Observatory, CN = *.weather.gov.hk
verify return:1
---
Certificate chain
 0 s:/C=HK/ST=Hong Kong/L=Hong Kong/O=Hong Kong SAR Government/OU=0002142877/OU=000000000000000000000000HKO/OU=Hongkong Post e-Cert (Server)/OU=Hong Kong Observatory/CN=*.weather.gov.hk
   i:/C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post e-Cert CA 1 - 15
 1 s:/C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post e-Cert CA 1 - 15
   i:/C=HK/O=Hongkong Post/CN=Hongkong Post Root CA 1
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIInzCCB4egAwIBAgIUVnPtks+ecLybAi6lEbuG26UgIfswDQYJKoZIhvcNAQEL
BQAwdjELMAkGA1UEBhMCSEsxEjAQBgNVBAgTCUhvbmcgS29uZzESMBAGA1UEBxMJ
SG9uZyBLb25nMRYwFAYDVQQKEw1Ib25na29uZyBQb3N0MScwJQYDVQQDEx5Ib25n
a29uZyBQb3N0IGUtQ2VydCBDQSAxIC0gMTUwHhcNMTgwNTI4MDgzNDU4WhcNMjAw
NTI4MDgzNDU4WjCB9jELMAkGA1UEBhMCSEsxEjAQBgNVBAgTCUhvbmcgS29uZzES
MBAGA1UEBxMJSG9uZyBLb25nMSEwHwYDVQQKExhIb25nIEtvbmcgU0FSIEdvdmVy
bm1lbnQxEzARBgNVBAsTCjAwMDIxNDI4NzcxJDAiBgNVBAsTGzAwMDAwMDAwMDAw
MDAwMDAwMDAwMDAwMEhLTzEmMCQGA1UECxMdSG9uZ2tvbmcgUG9zdCBlLUNlcnQg
KFNlcnZlcikxHjAcBgNVBAsTFUhvbmcgS29uZyBPYnNlcnZhdG9yeTEZMBcGA1UE
AxQQKi53ZWF0aGVyLmdvdi5oazCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAK7hRmg7DY6uXEEcGMQbnvoU7Pyi/+LLO8pLzCOOGVeFBaRznV97Vwk7T380
gcyR2aVny2rfxgNMQEFa4T2ChUSqaKy0JHX4WhWDOk18jCqQIvQUqYVG8PLLbG3O
B3a1sqsF0iZC7gTn/s5x19p4lPxF936rrXFQSG+A+qB9Imf26u6yTdLbPNvqlQI6
9r9Cb1S7OAGEgN5u+8WpeoHR62F0K3dROvI4diYfMRgkjxx5l+C7EZkqP0X3gaZJ
2x+1XKU5GZgATrXWaE8PrIOl2QHYatGXyKA9OI0ULRaBp5+ImqPLoFPWATEY25cd
DVp2jU1huF03YbkMTn55jbBASScCAwEAAaOCBKIwggSeMD4GA1UdIAQ3MDUwMwYK
KwYBBAH9HgEBJTAlMCMGCCsGAQUFBwIBFhd3d3cuaG9uZ2tvbmdwb3N0Lmdvdi5o
azArBgNVHREEJDAighAqLndlYXRoZXIuZ292Lmhrgg53ZWF0aGVyLmdvdi5oazAJ
BgNVHRMEAjAAMIGABggrBgEFBQcBAQR0MHIwQgYIKwYBBQUHMAKGNmh0dHA6Ly93
d3cxLmhvbmdrb25ncG9zdC5nb3YuaGsvcm9vdC9lY2VydF9jYV8xLTE1LmNydDAs
BggrBgEFBQcwAYYgaHR0cDovL29jc3AxLmhvbmdrb25ncG9zdC5nb3YuaGswDgYD
VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAfBgNV
HSMEGDAWgBRM73etI0rWRUgo15gs/iEaZfRKHTBIBgNVHR8EQTA/MD2gO6A5hjdo
dHRwOi8vY3JsMS5ob25na29uZ3Bvc3QuZ292LmhrL2NybC9lQ2VydENBMS0xNUNS
TDEuY3JsMB0GA1UdDgQWBBT3yMINNMEDV0uE6S8TSw3sjE8GlDCCAuYGCisGAQQB
1nkCBAIEggLWBIIC0gLQAHYApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN
3BAAAAFjpd5YNwAABAMARzBFAiEA+kXhKBES26YrtJMc/vlhnf2Kz1sbZY5SYpcc
mRB4w2UCIARc8BcR5x9+K/5cZyXs8VxudbHFIFzbaQ1G5bY0k5KlAHYA7ku9t3XO
YLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFjpd5bxgAABAMARzBFAiEAhxq1
ObadoWoWkwVBe3ov7MlL8p/14Vfn8Q8pXYJGVcUCIBySLYSmhVu57V4fskBYJsVy
pEZQowCSCSHW1AIrCkCXAHYAu9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e
0YUAAAFjpd5c4QAABAMARzBFAiADwJKT0naX8W/NOWVpV6zye/pJu8pzgrNSTYSu
swCWVAIhAJMB3bpPqvBl9osK8xvFNPeFewcwxxr5taX5Q3XyegehAHYAb1N2rDHw
MRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAFjpd5nEAAABAMARzBFAiBEiS8j
cPyzF+60T1168gs73GLOxo/7LrIXUKCLG47sigIhAKSHs8xnY6gViBBvlKZztw7M
YT4exU1nvQuEDw2wGJvvAHYAVYHUwhaQNgFK6gubVzxT8MDkOHhwJQgXL6OqHQcT
0wwAAAFjpd5n/wAABAMARzBFAiEAvnj4XH/6sOAilLfCK7iYEikxCVq7HqEcx8Vg
STE51nUCIGoKfXC9wO6TnlSVNqkdBCebIShOWrn7c224cP9QNElIAHYAXqdz+d9W
wOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFjpd5t+gAABAMARzBFAiEA51/1
fwBsesltu5YvavIaARMaqQDOUJ4lCKBQsOdbDVoCIC/2gXTKJLuI+Kb9oW7PWV+Q
nAgDcFw5T0Rc9spbmVrzMA0GCSqGSIb3DQEBCwUAA4IBAQBK2Glb6NmBcn91QH3O
F6nAiWyiIX0br4ZOXxQenSsJEoWdkUe24GMAnCumWbdDbzuwhj51pt0rRHOWn5Cu
bdymFwAN3unstG0izKkzXiw2CDZDF3CJ6FGyKZfqd9qL3BYp28ETfVPqSf2RKwn/
JZ3hcaTs7TRfvOCJSYXKuOGYbGQVN/i/MkF3VLw7uKiSMqkH0q7KJOXqg2WppotO
kVd1TPbvPYHl9zmoPUHg8L5Kq/TlHfY7ygiiVxqlQLZRiDPvWv8SRcgpoYBe/TpV
LfediGQqLflPLA2GIlX6qkuUnIY6dydEEZoK09sdFGXb4RthBpm33YPQ03nWXEKy
NSib
-----END CERTIFICATE-----
subject=/C=HK/ST=Hong Kong/L=Hong Kong/O=Hong Kong SAR Government/OU=0002142877/OU=000000000000000000000000HKO/OU=Hongkong Post e-Cert (Server)/OU=Hong Kong Observatory/CN=*.weather.gov.hk
issuer=/C=HK/ST=Hong Kong/L=Hong Kong/O=Hongkong Post/CN=Hongkong Post e-Cert CA 1 - 15
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4158 bytes and written 423 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: C5C5B554F6532E52FAB48DD84E8AD3FF20840E4CC2DB7FC037DAB9EBD1681682
    Session-ID-ctx:
    Master-Key: F68C248D9CE28BF68E2534205D2197F92D8AC87FB10C6F13B8B528C8CA80A518632719AE556672D5AF8F2613404E1BAA
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 5b e9 48 28 39 35 e3 8f-4d dd c6 3a fd 0f 05 b9   [.H(95..M..:....
    0010 - cb 13 7b 45 86 19 7c f3-f6 2e 34 0f 80 68 a7 c6   ..{E..|...4..h..
    0020 - 62 09 2b 74 d4 d6 c3 c4-17 bd 5f c7 ad 11 96 19   b.+t......_.....
    0030 - 61 09 b4 70 53 75 88 52-ed a1 91 d3 74 e4 ef 83   a..pSu.R....t...
    0040 - 82 2f 0f 5c 17 3c 3e a4-8e 7d 57 06 79 26 db 93   ./.\.<>..}W.y&..
    0050 - 70 71 ad cf 29 8c 5c f6-04 a9 17 58 52 f6 5d 83   pq..).\....XR.].
    0060 - f8 62 fd ee 9c c1 66 ef-fc 5f f6 8d 0d 0b e6 1c   .b....f.._......
    0070 - 6f 73 24 18 c5 50 35 67-a1 ec ef 28 80 d7 7d e3   os$..P5g...(..}.
    0080 - fe 1f af a3 70 28 ce 6e-e4 86 d4 cd 90 95 c5 db   ....p(.n........
    0090 - 9f dd 64 ab 69 6a 11 9d-c2 39 c4 9c d2 40 fe b2   ..d.ij...9...@..
    00a0 - 22 3e 92 96 a8 10 d5 4a-21 1e dd e8 8c dc b2 87   ">.....J!.......
    00b0 - f0 21 aa f9 b9 89 c1 97-3a 39 82 33 e1 85 9b dd   .!......:9.3....

    Start Time: 1562304631
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

HTTP/1.1 400 Bad Request
Date: Fri, 05 Jul 2019 05:30:40 GMT
Server: Apache
Content-Length: 226
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
read:errno=0
```

**Comment by ipaucek4680** [comment]
I tested again using `openssl` and can confirm that the certificate is correct now. I do not know why Travis Firefox ESR test failed, but given that all other tests passed, I believe the ruleset is OK.

**Comment by cschanaj** [comment]
It seems that `m.weather.gov.hk` failed intermittently because it resolves to 2 distinct IP addresses  `103.30.70.38` and `203.129.68.45`. In particular, SSL is not configured correctly for `103.30.70.38`

@J0WI @Bisaloo was there any consensus on how to deal with host like this?

**Comment by ipaucek4680** [comment]
> It seems that `m.weather.gov.hk` failed intermittently because it resolves to 2 distinct IP addresses `103.30.70.38` and `203.129.68.45`. In particular, SSL is not configured correctly for `103.30.70.38`

`m.weather.gov.hk` is a Hong Kong government website and this kind of problem should not happen. Should we inform the [Office of the Government Chief Information Officer](https://www.ogcio.gov.hk) (政府資訊科技總監辦公室)?

**Comment by cschanaj** [comment]
I believe this is a a good idea. Would you mind to contact them on this matter?

**Comment by ipaucek4680** [comment]
@cschanaj 
I would like to do so but it seems not that simple:
1. If I ask `3dns1.hgctr.com` for `m.weather.gov.hk`, I get `103.30.70.7` (it seems that the result may change, but the address will be something like `103.30.x.x`).
2. Then I connect to the above IP and get a valid certificate:
```
$ echo | openssl s_client -servername m.weather.gov.hk -connect 103.30.70.7:443 2>/dev/null | openssl x509 -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            56:73:ed:92:cf:9e:70:bc:9b:02:2e:a5:11:bb:86:db:a5:20:21:fb
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = HK, ST = Hong Kong, L = Hong Kong, O = Hongkong Post, CN = Hongkong Post e-Cert CA 1 - 15
        Validity
            Not Before: May 28 08:34:58 2018 GMT
            Not After : May 28 08:34:58 2020 GMT
        Subject: C = HK, ST = Hong Kong, L = Hong Kong, O = Hong Kong SAR Government, OU = 0002142877, OU = 000000000000000000000000HKO, OU = Hongkong Post e-Cert (Server), OU = Hong Kong Observatory, CN = *.weather.gov.hk
```
3. If I try the IP you provided earlier (i.e. `103.30.70.38`), I get an invalid certificate. This time, the certificate is not `CN = cam, emailAddress = root@cam` (see #18147), but is `CN = noah, emailAddress = root@noah`:
```
$ echo | openssl s_client -servername m.weather.gov.hk -connect 103.30.70.38:443 2>/dev/null | openssl x509 -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 13200 (0x3390)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = --, ST = SomeState, L = SomeCity, O = SomeOrganization, OU = SomeOrganizationalUnit, CN = noah, emailAddress = root@noah
        Validity
            Not Before: Mar 15 03:36:26 2019 GMT
            Not After : Mar 14 03:36:26 2020 GMT
        Subject: C = --, ST = SomeState, L = SomeCity, O = SomeOrganization, OU = SomeOrganizationalUnit, CN = noah, emailAddress = root@noah
```
It looks like the problem is only reproducible when the DNS server gives a "bad" IP address of `m.weather.gov.hk`.

**Comment by J0WI** [comment]
> @J0WI @Bisaloo was there any consensus on how to deal with host like this?

We used to document the inconsistent behaviour in comments and exclude the target.
But I'm getting completely different results here:

https://www.ssllabs.com/ssltest/analyze.html?d=m.weather.gov.hk

**Comment by ipaucek4680** [comment]
Just now I clicked on the link provided by @J0WI and the website said the error was common name mismatch. Then I clicked on "ignore mismatch and continue the test", and the results are:
Screenshot

**Comment by J0WI** [comment]
I just noticed the new IP in your screenshot.
It seems that the host uses a TTL of just 30 sec for it's DNS entry and changes it very frequently. That's a really bad practice.

**Comment by ipaucek4680** [comment]
I have excluded `m.weather.gov.hk`:
```
		SSL peer certificate was not OK:
		- kids.hko.gov.hk
		- pda.hko.gov.hk
		- wap.hko.gov.hk
		- m.weather.gov.hk (sometimes)
```

**Comment by cschanaj** [comment]
thanks!!

**Pull request merged**
