### PR TITLE
Add Darwinsys.com.xml

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by pipboy96** [comment]
Website has misconfigured TLS (incomplete certificate chain). Closing for now. Feel free to reopen if the website authors fix the issue.

**Comment by J0WI** [comment]
I would like to keep this PR because of https://github.com/EFForg/https-everywhere/issues/6966#issuecomment-471204878

**Comment by pipboy96** [comment]
You can reopen this issue at any moment. As of now it can't be merged.

**Comment by pipboy96** [comment]
not sure if tag is appropriate, there should be a "blocked by external bug" tag.

**Comment by pipboy96** [comment]
@J0WI Thanks. Will merge the moment the fixes are merged.

**Pull request merged**
