### PR TITLE
zamos.ru

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by galeksandrp** [comment]
HSTS

**Comment by galeksandrp** [comment]
HSTS

**Comment by jeremyn** [comment]
Thanks. Please:

- [ ] Add a general `securecookie` (because the user can log in)

**Comment by galeksandrp** [comment]
Added.

**Comment by jeremyn** [comment]
According to the [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), the generic `securecookie` should be `.+`/`.+`, not `.`/`.`. Please change it.

**Comment by galeksandrp** [comment]
Thanks.

**Comment by jeremyn** [comment]
Thanks, merged.

**Pull request merged**
