### PR TITLE
Trivial rule for personalausweisportal.de

### PR DESCRIPTION
**Pull request by KommX**

### CODE REVIEW

**Comment by julianladisch** [comment]
Good, please also add securecookie.

**Comment by KommX** [comment]
Like this?
I am not yet that familiar with secure cookies.

**Comment by julianladisch** [comment]
Almost perfect.  Make www\\. optional:

    <securecookie host="^(www\.)?personalausweisportal\.de$" name=".+" />

**Comment by KommX** [comment]
Done.

**Comment by julianladisch** [comment]
Well done!  I checked out your npa branch and it works perfectly.

**Pull request merged**
