### PR TITLE
Ensure that the translations script does not attempt to convert nonexistant translation files

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by pipboy96** [comment]
@Hainish Can we somehow get rid of this conversion step?

**Comment by zoracon** [comment]
> @Hainish Can we somehow get rid of this conversion step? Am I correct that it's impossible without changes on Tor Project's side?

@pipboy96 Since are translations are directly ran by Tor Project's translations efforts, correct. We can not modify the process in a way that separates for now.

**Comment by pipboy96** [comment]
@zoracon Can't we just move them into GitHub repo and handle them the same way as code? (I just ask, I do not propose this change immediately)

**Comment by zoracon** [comment]
> @zoracon Can't we just move them into GitHub repo and handle them the same way as code? (I just ask, I do not propose to change anything now)

Statically, yes. But dynamically as strings change those translations efforts are not handled by solely by us. It takes bigger effort and capacity we do not have internally.

**Pull request merged**
