### PR TITLE
Resubmit thecustomizewindows.com

### PR DESCRIPTION
**Pull request by AbhishekGhosh**
Old ruleset had issues - https://github.com/AbhishekGhosh/https-everywhere/blob/0a7eccd81524198aa4308cb2b91156ab2d8d3d34/src/chrome/content/rules/thecustomizewindows.com.xml which is made easy now.

### CODE REVIEW

**Comment by AbhishekGhosh** [comment]
Issue opened - https://github.com/EFForg/https-everywhere/issues/9463

**Comment by jeremyn** [comment]
@AbhishekGhosh Regarding your question in #9463 about the failing tests: we don't allow new rulesets if all of the domains in that ruleset are HSTS preloaded. See [here](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#hsts-preloaded-rules) in `CONTRIBUTING.md`. In this case `thecustomizewindows.com` and subdomains are HSTS preloaded, so Travis fails on the `preloaded` step.

So this pull request should be closed. Does that make sense?

**Comment by AbhishekGhosh** [comment]
@ jeremyn Thanks a lot for quick reply. I have a wish to be inside https://www.eff.org/https-everywhere/atlas/ That is my reason of doing so much push pull.

**Comment by jeremyn** [comment]
HSTS preloading does (almost) the exact same thing as HTTPS Everywhere. We don't want to include unnecessary rulesets for various reasons such as improving performance and minimizing developer maintenance effort.

**Comment by AbhishekGhosh** [comment]
Aha. Now completely understood. Saw the discussion - https://github.com/EFForg/https-everywhere/issues/7126 Thanks a lot for the quick replies.

**Pull request closed without merging**
