### PR TITLE
Update 3FM.xml

### PR DESCRIPTION
**Pull request by J0WI**
miss configured server

### CODE REVIEW

**Comment by reedy** [comment]
Did you mean to re-enable HTTPS?

https://www.3fm.nl/ seems to work fine, bar a few mixed content issues

**Comment by J0WI** [comment]
the problem is https://3fm.nl/

**Comment by jsha** [comment]
I think what @reedy meant was that you left the `default_off` attribute. Did you want to delete that?

**Comment by J0WI** [comment]
oh, sure.

**Pull request merged**
